Add visual state for PointerEntered
dotnet/maui pull request #10003
Opened 2022-09-08 18:25 UTC by rachelkang

### Description of Change

Introduces new visual state `PointerEntered` for when the mouse cursor is hovering over a view.
When both `PointerEntered` and `Pressed` states are defined, the `PointerEntered` state kicks in when the view is hovered but not pressed.

Related to #9592
Related to #9861 

### Issues Fixed

Fixes #7570
Fixes #9715

Related to #9139

2022-09-08 23:05 UTC, PureWeen commented on src/Controls/src/Core/Platform/GestureManager/GestureManager.Windows.cs
> +						if (ElementGestureRecognizers is ObservableCollection<IGestureRecognizer> oc)
I think these can just be 

`if (ElementGestureRecognizers != null)`

2022-09-08 23:10 UTC, PureWeen requested changes
I think you'll need to add logic so that calling

`Element.GestureRecognizers.Clear()`

Doesn't remove your PointerGestureRecognizer from the composite controls

![image](https://user-images.githubusercontent.com/5375137/189241254-1fa53e9b-8788-4951-b3d9-8d2f90cc84d1.png)


Maybe add some tests [here](https://github.com/dotnet/maui/blob/cc8a118b51cd2fe9af0dc9d87933d49b4576080e/src/Controls/tests/Core.UnitTests/ViewUnitTests.cs#L14)

Where you can validate that the `PointerGestureRecognizer` gets added to the composite collection and that it stays around after calling clear

2022-09-14 20:44 UTC, PureWeen commented on src/Controls/src/Core/View.cs
> +			if (IsPointerOver)
I'd say just move this to `VisualElement` where the other checks are and that `Disabled` should take precedence over `IsPointerOver`

That's how the ordering works for WinUI so we should just stay consistent

2022-09-14 20:44 UTC, PureWeen commented on src/Controls/tests/Core.UnitTests/ViewUnitTests.cs
> +#if !ANDROID
These tests don't run on a device they just run as a netstandard library so the ANDROID definition areas will have no effect.

2022-09-14 20:46 UTC, PureWeen requested changes

2022-09-14 20:46 UTC, PureWeen commented on src/Controls/src/Core/View.cs
> +		PointerGestureRecognizer _recognizerForPointerOverState = new PointerGestureRecognizer();
- Move these properties to the top of the file
- I wouldn't instantiate this here. Instantiate it inside `CompositeGesturesRecognizers`

_recognizerForPointerOverState ??= new PointerGestureRecognizer();

2022-09-15 15:09 UTC, PureWeen commented on src/Controls/src/Core/VisualElement.cs
> +		protected internal bool IsPointerOver = false;
Remove protected

2022-09-15 21:12 UTC, PureWeen commented on src/Controls/src/Core/VisualElement.cs
> +		internal bool _isPointerOver = false;
```suggestion
		internal bool IsPointerOver {get; private set;}
```

2022-09-20 20:07 UTC, rachelkang commented
Working well on windows and pretty well on mac!

(mac has slightly inconsistent behavior that is reported here - https://github.com/dotnet/maui/issues/10227_

2022-09-20 20:07 UTC, PureWeen approved these changes

2022-09-20 21:04 UTC, merged