Update Font inline docs
dotnet/maui pull request #10014
Opened 2022-09-09 11:53 UTC by jfversluis

### Description of Change
Adding inline docs for the Core Font objects

Related to #3960

2022-09-09 16:04 UTC, rmarinho commented
Build is failing 

```
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\EmbeddedFontLoader.cs(35,11): error CS0103: The name 'Path' does not exist in the current context [D:\a\_work\1\s\src\Core\src\Core.csproj]
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(807,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net6.0-windows10.0.19041\\input.json" "obj\Release\net6.0-windows10.0.19041\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Core\src\Core.csproj]
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(807,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net6.0-windows10.0.20348\\input.json" "obj\Release\net6.0-windows10.0.20348\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Fonts\FontFile.cs(20,119): error CS0419: Ambiguous reference in cref attribute: 'FileNameWithExtension'. Assuming 'FontFile.FileNameWithExtension(string?)', but could have also matched other overloads including 'FontFile.FileNameWithExtension()'. [D:\a\_work\1\s\src\Core\src\Core.csproj]
```

2022-09-12 21:49 UTC, hartez requested changes
Some wording and punctuation stuff.

2022-09-12 21:49 UTC, hartez commented on src/Core/src/Fonts/FileSystemEmbeddedFontLoader.cs
> +		/// <param name="rootPath">The path that will be used to copy the font to on the filesystem.</param>
Maybe "Destination filesystem path for the font"?

2022-09-12 21:49 UTC, hartez commented on src/Core/src/Fonts/FileSystemEmbeddedFontLoader.cs
> +		/// <param name="serviceProvider">The applications <see cref="IServiceProvider"/>.
"applications" -> "application's"

2022-09-12 21:49 UTC, hartez commented on src/Core/src/Fonts/FileSystemEmbeddedFontLoader.cs
> +		/// <param name="getRootPath">Function that is executed to retrieve the path that will be used to copy the font to on the filesystem.</param>
Maybe "Function which retrieves the destination filesystem path for the font."?

2022-09-12 21:49 UTC, hartez commented on src/Core/src/Fonts/FontManager.Windows.cs
> +		/// <param name="fontRegistrar">A <see cref="IFontRegistrar"/> instance to retrieve details from about registered fonts.</param>
Maybe "An IFontRegistrar instance for retrieving details about the registered fonts."?

2022-09-29 15:44 UTC, hartez approved these changes

2022-09-30 11:56 UTC, rmarinho approved these changes

2022-09-30 11:56 UTC, merged