[Housekeeping] Complete pending TODOs in Core
dotnet/maui pull request #10015
Opened 2022-09-09 11:54 UTC by jsuarezruiz

### Description of Change

Complete pending `TODOs `in Core.

2022-09-12 10:27 UTC, rmarinho requested changes
Build is failing

```
D:\a\_work\1\s\src\Core\src\Platform\iOS\TimePickerExtensions.cs(80,44): error CS1061: 'ITimePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ITimePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\iOS\DatePickerExtensions.cs(137,44): error CS1061: 'IDatePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IDatePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\iOS\TimePickerExtensions.cs(80,44): error CS1061: 'ITimePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ITimePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\iOS\DatePickerExtensions.cs(137,44): error CS1061: 'IDatePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IDatePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(91,39): error CS1061: 'ILabel' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ILabel' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBoxExtensions.cs(191,39): error CS1061: 'IView' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IView' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(807,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net6.0-windows10.0.20348\\input.json" "obj\Release\net6.0-windows10.0.20348\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBoxExtensions.cs(191,39): error CS1061: 'IView' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IView' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(91,39): error CS1061: 'ILabel' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ILabel' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(807,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net6.0-windows10.0.19041\\input.json" "obj\Release\net6.0-windows10.0.19041\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Core\src\Core.csproj]
    10 Warning(s)
```

2022-09-27 11:39 UTC, jsuarezruiz commented
> Build is failing
> 
> ```
> D:\a\_work\1\s\src\Core\src\Platform\iOS\TimePickerExtensions.cs(80,44): error CS1061: 'ITimePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ITimePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\iOS\DatePickerExtensions.cs(137,44): error CS1061: 'IDatePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IDatePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\iOS\TimePickerExtensions.cs(80,44): error CS1061: 'ITimePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ITimePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\iOS\DatePickerExtensions.cs(137,44): error CS1061: 'IDatePicker' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IDatePicker' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(91,39): error CS1061: 'ILabel' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ILabel' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBoxExtensions.cs(191,39): error CS1061: 'IView' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IView' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(807,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net6.0-windows10.0.20348\\input.json" "obj\Release\net6.0-windows10.0.20348\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBoxExtensions.cs(191,39): error CS1061: 'IView' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'IView' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> D:\a\_work\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(91,39): error CS1061: 'ILabel' does not contain a definition for 'GetEffectiveFlowDirection' and no accessible extension method 'GetEffectiveFlowDirection' accepting a first argument of type 'ILabel' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\src\Core.csproj]
> C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(807,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net6.0-windows10.0.19041\\input.json" "obj\Release\net6.0-windows10.0.19041\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Core\src\Core.csproj]
>     10 Warning(s)
> ```

It seems that we have removed the `GetEffectiveFlowDirection` extension method, any specific reason?

2022-10-17 17:29 UTC, hartez requested changes
Need confirmation that flow direction actually has a problem with these controls.

2022-10-17 17:29 UTC, hartez commented on src/Core/src/Platform/iOS/TimePickerExtensions.cs
> +			var effectiveFlowDirection = timePicker.GetEffectiveFlowDirection();
Are we even sure this needs to be done anymore? Is the alignment of the text actually incorrect when the flow direction is RTL? I strongly suspect that GetEffectiveFlowDirection is no longer needed here.

2022-11-03 08:19 UTC, jsuarezruiz commented
To help focus and move faster, we're going to have fewer open PRs and focus on the ones we'll be working on in each release. This PR is not included in the next release so I close it for now. I will reopen it and adapt to changes later.

2022-11-03 08:19 UTC, closed without merging