Implement more WinUI SwitchHandler properties
dotnet/maui pull request #1007
Opened 2021-05-11 12:24 UTC by jsuarezruiz

### Description of Change ###

Implement more WinUI SwitchHandler properties:
- TrackColor
- ThumbColor

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might effect accessibility?
No

2021-05-14 09:21 UTC, rmarinho requested changes
Looking at this sample i don't see the ThumbColor changing is this expected ? 

`verticalStack.Add(new Switch() { OnColor = Colors.Green,  ThumbColor = Colors.Yellow });`

![image](https://user-images.githubusercontent.com/1235097/118250164-13813780-b49e-11eb-9f93-12bbfe85e5d7.png)

![image](https://user-images.githubusercontent.com/1235097/118250207-1d0a9f80-b49e-11eb-9224-ffb50c8ab366.png)

2021-05-17 17:19 UTC, rmarinho commented
It's  working better, but seems first time it still shows the default color, and the  `TrackColor` just changes  when it loses focus:
![image](https://user-images.githubusercontent.com/1235097/118530217-506a5a00-b73c-11eb-8823-c82b804ebbb9.png)


![image](https://user-images.githubusercontent.com/1235097/118529762-c5895f80-b73b-11eb-8daf-1d0fd15626b6.png)

2021-05-28 19:20 UTC, rachelkang requested changes
seconding Rui - the track color doesn't initialize properly

2021-07-06 12:22 UTC, jsuarezruiz commented
Could we get another review for the PR again? The Thumb color is set correctly regardless of state (IsToggled). As for OnColor, if the state is Off, the color is not set until the state changes, if it is On, the track background color is applied directly.

2021-07-06 17:23 UTC, rachelkang commented
> Could we get another review for the PR again? The Thumb color is set correctly regardless of state (IsToggled). As for OnColor, if the state is Off, the color is not set until the state changes, if it is On, the track background color is applied directly.

@jsuarezruiz the issue still remains with the OnColor switch - the first time the switch is toggled on, the track color turns blue. Then, it automatically changes to red and remains red. Whenever the switch is toggled on after that, it goes straight to red

2021-09-24 12:29 UTC, rmarinho approved these changes

2021-09-24 12:34 UTC, rmarinho commented on src/Core/src/Platform/ImageSourceExtensions.cs
> +				return new Task<IImageSourceServiceResult<NativeImage>?>(() => null);
@PureWeen  same NRE, this a better fix ?

2021-09-24 17:04 UTC, rachelkang reviewed
Previous issue I noted was fixed! Yay

One thing I'm still noticing though is that on focus/hover, the switch track color appears lighter - but if I'm seeing this correctly, this is only the case for the default blue ones. If we could somehow standardize and maintain the highlight on the custom track colors too (the red one here), I think that would be a good idea

![winui_maui_switch_color](https://user-images.githubusercontent.com/21988533/134713576-32dc239a-02ef-460f-a91b-59e4bff1fa00.gif)

2021-09-24 17:15 UTC, rmarinho commented
Created a issue for this @rachelkang  https://github.com/dotnet/maui/issues/2685

2021-09-24 17:15 UTC, merged