Feat: Added "Keyboard.None"
dotnet/maui pull request #10375
Opened 2022-09-28 15:41 UTC by GabrielGavrilov

### Description of Change

Added "Keyboard.None"

### Issues Fixed

Fixes #10331

2022-09-28 15:41 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=10375) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=10375) before we can accept your contribution.<br/><br/>:x: GabrielGavrilov [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=10375)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=10375) it.</sub>

2022-09-29 08:00 UTC, jfversluis requested changes
I don't think this implementation is complete?

2022-09-29 08:00 UTC, jfversluis commented on src/Core/src/Primitives/Keyboard.cs
> +			get { return s_none ??= new NoneKeyboard(); }
The type `NoneKeyboard` doesn't exist, does it?

2022-09-29 08:00 UTC, jfversluis commented on src/Core/src/Primitives/Keyboard.cs
> +		/// <include file="../../docs/Microsoft.Maui/Keyboard.xml" path="//Member[@MemberName='None']/Docs/*" />
You'll also have to add the actual docs for it, not just replace the member name here

2022-09-29 12:08 UTC, closed without merging