[Android] Improve CollectionView scrolling
dotnet/maui pull request #10523
Opened 2022-10-06 16:21 UTC by jsuarezruiz

### Description of Change

This PR include changes to:
- Dispose (reset BindingContext, dispose etc) the internal ContentViews from CollectionView on Android.
- Added a Shadow's Cache. With the sample from the issue, creating a list of 100 items after scroll to the end was creating 100*3=300 bitmaps (shadows). The drawing and memory penalty was high. With the cache included in the same sample, only 15 bitmaps are created and they are constantly reused.

With these changes, the scroll behavior pass from unusable to something much better but jittering is still noticeable. We still MUST continue reviewing samples, debugging and improving to offer the best possible experience with the CollectionView.

For now this PR is a Draft. I have tried the shadows gallery samples, and some extra examples without finding issues, everything works in the same way as before but using the cache. However, because the changes are noticeable, I want to include more examples and make more tests/improvements.

### Issues Fixed

Fixes #9485

2022-10-10 22:58 UTC, AmrAlSayed0 commented on src/Core/src/Platform/Android/WrapperView.cs
> +			return Shadow.GetHashCode();
I'm very skeptical about this cache.

First, the cache instance should be static as it doesn't matter if 2 different views are using the "same" shadow (which is a likely situation if you're using a resource key) the same bitmap could be applied.

Second, what counts as the "same" shadow is not only the virtual views' shadow but also the dimensions. 2 views with exactly the same shadow properties, i.e same shadow hashcode, but different dimensions can't use the same bitmap.

Third, `InvalidateShadow` removes the shadow from the hash but that's not really what you want. It is called on every shadow change which means that there will only ever be 1 shadow in the cache and it is the current one. I don't think that's how caches are used 😅. Maybe a more complex cache like LRU-cache would help.

2022-12-14 21:13 UTC, hartez commented
> Dispose (reset BindingContext, dispose etc) the internal ContentViews from CollectionView on Android.

Do you have any data to show this improves scrolling speed? It doesn't seem like it would have any bearing on the scrolling, since it doesn't happen until the CollectionView is being disposed (or the ItemsSource changes).

The shadow caching portion may help with the scrolling speed, but I'm suspicious of the other changes. This should be two separate PRs so we can evaluate each one independently.

2022-12-14 21:16 UTC, hartez requested changes

2022-12-14 21:16 UTC, hartez commented on src/Core/src/Platform/Android/ShadowCache.cs
> +			Debug.WriteLine($"Add {id}");
Left a debugging statement in there.

2022-12-14 21:16 UTC, hartez commented on src/Core/src/Platform/Android/ShadowCache.cs
> +				Debug.WriteLine($"Adding {id}, count is {_cache.Count}");
Another debugging statement.

2022-12-14 21:16 UTC, hartez commented on src/Core/src/Platform/Android/ShadowCache.cs
> +			Debug.WriteLine($"Remove {id}");
Debugging statement.

2022-12-14 21:16 UTC, hartez commented on src/Core/src/Platform/Android/ShadowCache.cs
> +					Debug.WriteLine($"Reference {bitmapReference.Reference}, count is {_cache.Count}");
Debugging statement.

2022-12-14 21:16 UTC, hartez commented on src/Core/src/Platform/Android/ShadowCache.cs
> +						Debug.WriteLine($"Removing {id}, count is {_cache.Count}");
Debugging statement.

2022-12-14 21:16 UTC, hartez commented on src/Core/src/Platform/Android/ShadowCache.cs
> +		readonly Dictionary<string, BitmapReference> _cache;
Rather than all this custom code, can this be done with a ConcurrentDictionary?

2022-12-15 10:11 UTC, jsuarezruiz commented
Converted back to Draft. Rebasing and testing everything, something has changed in this time and it doesn't work as expected. I will review everything to know what changed.

2023-02-15 13:40 UTC, jsuarezruiz commented
The approach is good but we will reopen it with a different implementation.

2023-02-15 13:40 UTC, closed without merging