Remove gesture from page that interferes with accessibility
dotnet/maui pull request #10948
Opened 2022-10-26 20:58 UTC by PureWeen

### Description of Change

The code we use to try and auto close the keyboard when clicking off of an entry field causes the UISwitch to not work the first time you interact with it

If you take the following code
```XAML
 <VerticalStackLayout>
        <Switch WidthRequest="50"></Switch>
    </VerticalStackLayout>
```

- Turn on VO
- Navigate to switch
- double tap
- nothing happens
- double tap again and now it works fine. 

### Breaking Change

This breaks the behavior where clicking off an entry closes the keyboard. That behavior was added before XF was even made public so it's questionable code. The main issue here is that we don't have Keyboard APIs that users can use. So, we probably want to couple this with Keyboard APIs for NET8 or examples of how users can tap into the keyboard themselves.

2022-10-28 16:07 UTC, jsuarezruiz commented on src/Core/src/Handlers/Page/PageHandler.iOS.cs
> -			var uiTapGestureRecognizer = new UITapGestureRecognizer(a => nativeView?.EndEditing(true));
Should we include with this changes an alternative way to manage the keyboard etc?

2022-12-12 18:55 UTC, rachelkang requested changes
Looks great to me! Switch issue is definitely no longer.

Just left a couple of nitpick comments

2022-12-12 18:55 UTC, rachelkang commented on src/Core/src/Platform/iOS/ResignFirstResponderTouchGestureRecognizer.cs
> +		internal static void Update(UITextView uIControl, UIWindow? window)
I would suggest something like`textView` or `platformTextView` to distinguish from the following function


```suggestion
		internal static void Update(UITextView textView, UIWindow? window)
```

2022-12-12 18:55 UTC, rachelkang commented on src/Core/src/Platform/iOS/ResignFirstResponderTouchGestureRecognizer.cs
> +		internal static void Update(UIControl uIControl, UIWindow? window)
trivial, but I think the `uIControl` casing can be a bit confusing

```suggestion
		internal static void Update(UIControl platformControl, UIWindow? window)
```

2022-12-12 18:55 UTC, rachelkang commented on src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
> +				void OnFocused(object? sender, AView.FocusChangeEventArgs e)
```suggestion
				void OnUnFocused(object? sender, AView.FocusChangeEventArgs e)
```

2022-12-12 18:55 UTC, rachelkang commented on src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
> +				view.FocusChange += OnFocused;
```suggestion
				view.FocusChange += OnUnFocused;
```

2022-12-12 18:55 UTC, rachelkang commented on src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
> +				// Even thuogh the event fires unfocus hasn't fully been achieved
```suggestion
				// Even though the event fires unfocus hasn't fully been achieved
```

2023-01-12 16:13 UTC, rachelkang approved these changes
LGTM!

2023-01-12 17:12 UTC, merged

2023-01-19 22:40 UTC, mattleibow commented
/backport to net7.0