CodeQL only on main/non-public builds
dotnet/maui pull request #11273
Opened 2022-11-10 21:21 UTC by Redth

Adjust when CodeQL is enabled to run.

2022-11-11 10:58 UTC, rmarinho commented on eng/pipelines/common/variables.yml
> +            eq(variables['Build.DefinitionName'], 'MAUI-private')
```suggestion
            eq(variables['Build.DefinitionName'], 'MAUI')
```

2022-11-11 10:59 UTC, rmarinho commented on eng/pipelines/common/variables.yml
> +            eq(variables['Build.DefinitionName'], 'MAUI-private')
THe real name, other thing we can use is check if it's on devdiv

```
eq(variables['System.TeamProject'], 'devdiv')
```

2022-11-11 11:00 UTC, rmarinho requested changes
The BuilDefiniatioName is not that one, but we could just a check to see if it's on devdiv, but that will enable also for other pipelines like DeviceTests or Megatron

2022-11-14 10:49 UTC, rmarinho commented
/azp run

2022-11-14 10:49 UTC, rmarinho approved these changes

2022-11-21 14:38 UTC, jfversluis approved these changes

2022-11-21 14:38 UTC, merged