[Android] Fix crash disconnecting the IndicatorView
dotnet/maui pull request #11346
Opened 2022-11-14 16:19 UTC by jsuarezruiz

### Description of Change

Fix crash disconnecting the IndicatorView on Android.

### Issues Fixed

Fixes #11310

2022-11-18 16:06 UTC, rmarinho approved these changes

2022-11-22 16:40 UTC, Redth requested changes
@jsuarezruiz can you add a test for this?  Given this didn't cause any tests to fail I assume we don't have coverage - maybe there's an opportunity here to add a test that covers disconnect for all handler cases?

2022-11-24 11:38 UTC, jsuarezruiz commented
> @jsuarezruiz can you add a test for this? Given this didn't cause any tests to fail I assume we don't have coverage - maybe there's an opportunity here to add a test that covers disconnect for all handler cases?

Yes, good suggestions. We have a test that validates the disconnection of handlers. However, it only does it in those controls where we have the Stub and tests. I have added what is necessary to pass the tests with the IndicatorViewHandler.

![image](https://user-images.githubusercontent.com/6755973/203775233-b73bbd71-715d-4f29-b7cc-ca1bf32ad358.png)

In another PR I will review adding the pending controls and in another validate basic properties of the IndicatorView (Background, Count etc).

2022-12-06 22:52 UTC, Redth approved these changes

2022-12-06 22:53 UTC, merged

2022-12-15 15:51 UTC, mattleibow commented
/backport to net7.0