Update Essentials Accelerometer API Docs
dotnet/maui pull request #11370
Opened 2022-11-15 13:01 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-11-15 13:32 UTC, jsuarezruiz approved these changes

2022-11-15 17:18 UTC, hartez requested changes
Looks good, some suggestions.

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +	/// Accelerometer data of the acceleration of the device in three dimensional space.
```suggestion
	/// Accelerometer data of the acceleration of the device in three-dimensional space.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Event triggered when reading of sensor changes.
```suggestion
		/// Occurs when the sensor reading changes.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Event triggered when a shake has been detected on the device.
```suggestion
		/// Occurs when the accelerometer detects that the device has been shaken.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Gets if reading the accelerometer is supported on this device.
```suggestion
		/// Gets a value indicating whether reading the accelerometer is supported on this device.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Gets if accelerometer is being monitored.
```suggestion
		/// Gets a value indicating whether the accelerometer is being monitored.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Event triggered when reading of sensor changes.
```suggestion
		/// Occurs when the accelerometer reading changes.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Event triggered when a shake has been detected on the device.
```suggestion
		/// Occurs when the accelerometer detects that the device has been shaken.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Gets if accelerometer is being monitored.
```suggestion
		/// Gets a value indicating whether the accelerometer is being monitored.
```

2022-11-15 17:18 UTC, hartez commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		/// Gets if reading the accelerometer is supported on this device.
```suggestion
		/// Gets a value indicating whether reading the accelerometer is supported on this device.
```

2022-11-16 19:57 UTC, hartez approved these changes

2022-11-17 08:41 UTC, merged

2022-11-24 15:42 UTC, Redth commented
/backport to net6.0

2022-11-24 15:42 UTC, Redth commented
/backport to net7.0

2022-11-24 16:49 UTC, Redth commented
/backport to net6.0

2022-11-24 16:49 UTC, Redth commented
/backport to net7.0