Update Essentials Battery API Docs
dotnet/maui pull request #11380
Opened 2022-11-15 15:12 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-11-15 16:05 UTC, hartez requested changes
Looks good, couple of suggestions.

2022-11-15 16:05 UTC, hartez commented on src/Essentials/src/Battery/Battery.shared.cs
> +	/// Enumerates states of the battery.
```suggestion
	/// Describes possible states of the battery.
```

2022-11-15 16:11 UTC, hartez approved these changes

2022-11-18 13:04 UTC, jsuarezruiz approved these changes

2022-11-18 13:04 UTC, merged

2022-11-24 16:50 UTC, Redth commented
/backport to net6.0

2022-11-24 16:50 UTC, Redth commented
/backport to net7.0