Update Essentials Clipboard Docs
dotnet/maui pull request #11395
Opened 2022-11-15 21:05 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-11-16 10:38 UTC, jsuarezruiz approved these changes

2022-11-16 19:48 UTC, hartez requested changes

2022-11-16 19:48 UTC, hartez commented on src/Essentials/src/Clipboard/Clipboard.shared.cs
> +		/// Gets whether there is any text on the clipboard.
```suggestion
		/// Gets a value indicating whether there is any text on the clipboard.
```

2022-11-16 19:48 UTC, hartez commented on src/Essentials/src/Clipboard/Clipboard.shared.cs
> +		/// Event that is triggered when the clipboard content changes.
```suggestion
		/// Occurs when the clipboard content changes.
```

2022-11-16 19:48 UTC, hartez commented on src/Essentials/src/Clipboard/Clipboard.shared.cs
> +		/// Event that is triggered when the clipboard content changes.
```suggestion
		/// Occurs when the clipboard content changes.
```

2022-11-16 19:48 UTC, hartez commented on src/Essentials/src/Clipboard/Clipboard.shared.cs
> +		/// Gets whether there is any text on the clipboard.
```suggestion
		/// Gets a value indicating whether there is any text on the clipboard.
```

2022-11-18 17:07 UTC, hartez approved these changes

2022-11-18 19:39 UTC, merged

2022-11-24 16:51 UTC, Redth commented
/backport to net6.0

2022-11-24 16:51 UTC, Redth commented
/backport to net7.0