Update Essentials Browser API Docs
dotnet/maui pull request #11394
Opened 2022-11-15 20:57 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-11-16 10:39 UTC, jsuarezruiz approved these changes

2022-11-16 19:56 UTC, hartez requested changes

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// Open the browser to specified uri.
```suggestion
		/// Open the browser to specified URI.
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/Browser.shared.cs
> +		/// <param name="uri">Uri to launch.</param>
```suggestion
		/// <param name="uri">URI to open.</param>
```

2022-11-16 19:56 UTC, hartez commented on src/Essentials/src/Browser/BrowserLaunchOptions.shared.cs
> +		/// <summary>Only applicable iOS: launches the browser as a page sheet with the�system preferred browser where supported.</summary>
```suggestion
		/// <summary>Only applicable to iOS: launches the browser as a page sheet with the system preferred browser where supported.</summary>
```

2022-11-18 16:58 UTC, hartez approved these changes

2022-11-18 17:03 UTC, merged

2022-11-24 16:50 UTC, Redth commented
/backport to net6.0

2022-11-24 16:50 UTC, Redth commented
/backport to net7.0