Update Essentials Compass API Docs
dotnet/maui pull request #11414
Opened 2022-11-16 15:06 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-11-22 16:47 UTC, Redth commented on src/Essentials/src/Compass/Compass.shared.cs
> +		/// <param name="right">Left to compare.</param>
```suggestion
		/// <param name="right">Right to compare.</param>
```

2022-11-22 16:47 UTC, Redth commented on src/Essentials/src/Compass/Compass.shared.cs
> +		/// <param name="right">Left to compare.</param>
```suggestion
		/// <param name="right">Right to compare.</param>
```

2022-11-23 00:01 UTC, hartez requested changes

2022-11-23 00:01 UTC, hartez commented on src/Essentials/src/Compass/Compass.shared.cs
> +		/// Gets if compass is actively being monitored.
```suggestion
		/// Gets a value indicating whether the compass is actively being monitored.
```

2022-11-23 00:01 UTC, hartez commented on src/Essentials/src/Compass/Compass.shared.cs
> +		/// Gets or sets if the calibration screen should be displayed.
```suggestion
		/// Gets or sets a value specifying whether the calibration screen should be displayed.
```

2022-11-23 00:01 UTC, hartez commented on src/Essentials/src/Compass/Compass.shared.cs
> +		/// Gets or sets if the calibration screen should be displayed.
```suggestion
		/// Gets or sets a value specifying whether the calibration screen should be displayed.
```

2022-11-25 10:26 UTC, jfversluis commented on src/Essentials/src/Compass/Compass.shared.cs
> +		/// <param name="right">Left to compare.</param>
🤦‍♂️

2023-01-10 17:14 UTC, hartez approved these changes

2023-01-10 17:14 UTC, merged

2023-01-19 15:43 UTC, mattleibow commented
/backport to net7.0