Update Essentials Connectivity API Docs
dotnet/maui pull request #11415
Opened 2022-11-16 15:21 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-11-16 20:03 UTC, hartez requested changes

2022-11-16 20:03 UTC, hartez commented on src/Essentials/src/Connectivity/Connectivity.shared.cs
> +	/// The Connectivity APIs lets you monitor for changes in the device's network conditions, check the current network access, and how it is currently connected.
```suggestion
	/// The Connectivity API lets you monitor for changes in the device's network conditions, check the current network access, and determine how it is currently connected.
```

2022-11-16 20:03 UTC, hartez commented on src/Essentials/src/Connectivity/Connectivity.shared.enums.cs
> +		/// <summary>The WiFi data connection.</summary>
```suggestion
		/// <summary>The Wi-Fi data connection.</summary>
```

2022-11-18 17:07 UTC, hartez approved these changes

2022-11-18 19:39 UTC, merged

2022-11-24 16:51 UTC, Redth commented
/backport to net6.0

2022-11-24 16:51 UTC, Redth commented
/backport to net7.0

2022-12-29 13:46 UTC, Santiagosaiz commented on src/Essentials/src/Connectivity/Connectivity.shared.enums.cs
> +		/// <summary>The WiFi data connection.</summary>
@Santiagosaiz4inittowinit