Implement ClearButtonVisibility property in WinUI Entry
dotnet/maui pull request #1147
Opened 2021-06-02 10:29 UTC by jsuarezruiz

### Description of Change ###

Implement `ClearButtonVisibility` properties in WinUI Entry

![WinUI-Entry-ClearButtonVisibility](https://user-images.githubusercontent.com/6755973/120465313-1fc22b80-c39e-11eb-85f7-0c09464c5808.gif)
win
### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- No

2021-06-02 12:00 UTC, jsuarezruiz commented
/azp run

2021-06-02 18:52 UTC, rachelkang requested changes
When I press the clear button, the page sometimes randomly auto-scrolls / jumps downward - not sure what's going on there, but would be great if you could look into it!

2021-06-07 16:34 UTC, Redth approved these changes

2021-06-09 14:16 UTC, jsuarezruiz commented
@rachelkang I suspect it is related to Focus management  or the Shim ScrollView. Could you open an issue so we don't forget about the issue?

2021-06-16 10:14 UTC, merged