[Android] Fix shadows size in clipped views
dotnet/maui pull request #11603
Opened 2022-11-24 09:46 UTC by jsuarezruiz

### Description of Change

Fix shadows size in clipped views on Android.

![Screenshot_1669222539](https://user-images.githubusercontent.com/6755973/203751507-5207ab08-e06f-4cd0-ac46-cb376354c0c0.png)

### Issues Fixed

Fixes #11578

2022-11-24 11:56 UTC, rmarinho requested changes
Test is failing 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1235097/203778743-8ea0e5b6-8b52-475b-8add-e391ab42011f.png">

2022-11-24 12:25 UTC, jsuarezruiz commented
> Test is failing
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/1235097/203778743-8ea0e5b6-8b52-475b-8add-e391ab42011f.png">

Leave a small change behind, fixed.

2022-11-30 21:27 UTC, Redth commented
@jsuarezruiz I pushed one small change to capture the Context and cache its use in a couple places in this view.

2022-12-01 12:20 UTC, jsuarezruiz commented
> @jsuarezruiz I pushed one small change to capture the Context and cache its use in a couple places in this view.

Better, thanks.

2022-12-01 12:24 UTC, jsuarezruiz commented
> > Test is failing
> > <img alt="image" width="436" src="https://user-images.githubusercontent.com/1235097/203778743-8ea0e5b6-8b52-475b-8add-e391ab42011f.png">
> 
> Leave a small change behind, fixed.

@rmarinho Could you review it again?. Thanks.

2022-12-16 22:18 UTC, rachelkang approved these changes
LGTM! Ready to go once all tests are passing

2023-01-11 15:57 UTC, jsuarezruiz commented on src/Core/src/Platform/Android/WrapperView.cs
> +						var density = _context.GetDisplayDensity();
@Redth Thoughts?

2023-02-10 09:44 UTC, jsuarezruiz commented on src/Core/src/Platform/Android/WrapperView.cs
> +						var density = _context.GetDisplayDensity();
Rui, reviewed and applied changes. Could you review it again?

2023-02-10 14:07 UTC, rmarinho approved these changes

2023-02-10 14:08 UTC, merged