Ensure invisible views don't get rows/columns when generating AndExpand layouts
dotnet/maui pull request #11712
Opened 2022-11-28 23:13 UTC by hartez

### Description of Change

When generating the underlying representation of a legacy AndExpand StackLayout, space is being allotted for invisible Views. These changes check View visibility before allotting space.

### Issues Fixed

Fixes #11678

2022-11-29 11:55 UTC, rmarinho requested changes
Can we add a test that when we change back the visibility to `Visible` it will relayout correctly ?

2022-11-29 15:53 UTC, hartez commented
> Can we add a test that when we change back the visibility to `Visible` it will relayout correctly ?

Are you asking for a unit test that shows visible items being laid out in the correct place? Or are you asking for a device test showing that changing item visibility triggers a re-layout on each platform?

2022-11-29 16:00 UTC, rmarinho commented
I think we can do a unit test on controls

2022-11-30 12:43 UTC, rmarinho approved these changes

2022-11-30 12:43 UTC, merged

2022-12-08 15:58 UTC, Redth commented
/backport to net7.0