[Android] Clear before each Image Source change
dotnet/maui pull request #11787
Opened 2022-12-01 13:05 UTC by jsuarezruiz

### Description of Change

We get the `'Canvas: trying to use a recycled bitmap android.graphics.Bitmap@5601f7b'` error changing the image Source dynamically (could happen also just recycling items). 

@mohachouch Give a workaround here https://github.com/dotnet/maui/issues/10032#issuecomment-1333432080

We are not clearing the old images before update https://github.com/dotnet/maui/pull/7348. This is causing issues working with Images and changing the Source, working with Images and other controls like CarouselView, CollectionView, etc. This PR include changes to clear (again) before each Image Source change. Applied the change only in Android where we have the issues. Noticed why we removed it before and in other platforms is working correctly. Want to review Glide options to see if we can avoid the problems with a different approach.

![image](https://user-images.githubusercontent.com/6755973/205089508-f0069240-bf2a-4ea1-b9fa-5426f565af86.png)

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/11519 
Fixes https://github.com/dotnet/maui/issues/11130 
Fixes https://github.com/dotnet/maui/issues/10032 
Fixes https://github.com/dotnet/maui/issues/9712 
Fixes https://github.com/dotnet/maui/issues/8809 
Fixes https://github.com/dotnet/maui/issues/9011
Fixes https://github.com/dotnet/maui/issues/8178 
Fixes https://github.com/dotnet/maui/issues/8809

2022-12-01 22:56 UTC, mattleibow reviewed
I recall the clearing causes a flicker... Maybe we are disposing an image when we shouldn't?

Who is disposing the bitmap? If it is us, then we probably should stop. Disposing also destroys the cache so we are just making things worse.

Clearing the image hides the problem and also potentially interferes with glide... Maybe...

2022-12-02 17:08 UTC, brabebhin commented
It most definitely is "us" disposing the images. After battling with this bug for months, and checking similar errors on android side, it is maui framework disposing the image when it shouldn't. The whole point of using glide is to have glide handle caching and disposing of images. 

The idea of disposing the source deterministically inherently bad when not using caches.  It makes sense when you change the source of an image and never look back. But this causes problems with scrolling controls that implement virtualization, because the same source may be changed and restored several times depending on scrolling direction.

Native android doesn't have flickering issues with images,  I don't understand why maui would,  unless images are handled incorrectly.

2022-12-02 17:31 UTC, mattleibow commented
By flickering I mean that if the image takes a few ms to load, it will flick blank and then the new image: https://github.com/dotnet/maui/issues/6625

2022-12-05 11:44 UTC, brabebhin commented
Anyhow, flickering is a mare annoyance. This bug takes the M out of MAUI cause it kills off any android support, so please prioritize it accordingly.

2022-12-23 03:36 UTC, hartez commented
After digging into this a bit, I'm fairly certain the problem is in our MauiCustomViewTarget Java implementation. The `onResourceCleared` method doesn't do anything, and it should. I think this is what it _should_ be doing:

```
    @Override
    protected void onResourceCleared(@Nullable Drawable placeholder) {
		this.view.setImageDrawable(placeholder);
    }
```

Because our implementation doesn't immediately update the drawable when the underlying bitmap is ejected from the bitmap pool, there's a very narrow window between ejecting the resource and the new resource being ready where a call to draw the image can result in using the old, ejected bitmap. 

The solution in this PR avoids that problem, but at the cost of making it impossible for Glide to actually manage the bitmaps in the pool. Because this PR's solution changes the drawable outside of Glide's control, Glide's reference counts end up being incorrect and it thinks the underlying bitmap is _always_ in use. Eventually, this can end up causing OOM errors.  

(Note that with out current code, `placeholder` is always null, because we haven't created a way for MAUI to use that feature of Glide yet. So a draw call that hits the narrow window can still cause a brief flicker. Proper placeholder usage (and better RecyclerView prediction, for CollectionView/CarouselView) will fix that. It's still a _much_ shorter flicker than what we see in this PR's solution.)

I'll create a PR for this on Tuesday and we can do some more testing. But I'm fairly certain it's the right answer.

2022-12-23 03:37 UTC, hartez requested changes
This will prevent the crashes, but at the cost of ruining Glide's memory management and eventually crashing for a different reason. See my other comment for what I believe is a more correct solution.

2022-12-28 18:09 UTC, PureWeen commented
Closing in favor of
https://github.com/dotnet/maui/pull/12310

2022-12-28 18:09 UTC, closed without merging