Update Essentials Email API Docs
dotnet/maui pull request #11868
Opened 2022-12-05 13:40 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-12-06 16:46 UTC, hartez requested changes

2022-12-06 16:46 UTC, hartez commented on src/Essentials/src/Email/Email.shared.cs
> +		/// Opens the default email client to allow the user to send the message with the provided subject, body and recipients.
```suggestion
		/// Opens the default email client to allow the user to send the message with the provided subject, body, and recipients.
```

2022-12-07 09:03 UTC, jfversluis commented on src/Essentials/src/Email/Email.shared.cs
> +		/// <summary>The email message body is HTML (not supported on Windows).</summary>
Good call! I fixed it for the other one, but not this one. The reason for it is that the `remarks` field on an enum value is not shown in the online API docs browser. So for visibility I'm keeping this one as it is.

2022-12-13 17:43 UTC, hartez approved these changes

2022-12-13 17:43 UTC, merged

2023-01-05 15:49 UTC, Redth commented
/backport to net7.0