Update Essentials Gyroscope API Docs
dotnet/maui pull request #11925
Opened 2022-12-07 11:51 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-12-07 13:42 UTC, jfversluis commented on src/Essentials/src/Gyroscope/Gyroscope.shared.cs
> +		///	Equality operator for equals.
```suggestion
		/// Equality operator for equals.
```

2022-12-07 20:52 UTC, PureWeen commented
/azp run

2022-12-14 23:49 UTC, hartez requested changes

2022-12-14 23:49 UTC, hartez commented on src/Essentials/src/Gyroscope/Gyroscope.shared.cs
> +	/// Contains the axis readings measured by the user's device gyroscope.
```suggestion
	/// Contains the axis readings measured by the device's gyroscope.
```

2022-12-15 13:45 UTC, rmarinho commented
/azp run

2022-12-15 13:50 UTC, rmarinho approved these changes

2022-12-15 16:07 UTC, hartez approved these changes

2022-12-15 16:07 UTC, merged

2023-01-05 15:56 UTC, Redth commented
/backport to net7.0

2023-01-05 16:00 UTC, Redth commented
/backport to net7.0