Update Essentials Geolocation API Docs
dotnet/maui pull request #11924
Opened 2022-12-07 11:41 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-12-07 11:52 UTC, jfversluis commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="right">Left to compare.</param>
Interesting, I think I copy/pasted this, so this might be in more docs as well... 😅 thanks!

2022-12-07 13:27 UTC, jsuarezruiz commented
/azp run

2022-12-07 20:34 UTC, hartez requested changes

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Geolocation/GeolocationRequest.shared.cs
> +		/// Gets or sets whether to requests full permission to temporarily use location services with full accuracy.
```suggestion
		/// Gets or sets whether to request full permission to temporarily use location services with full accuracy.
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// Initializes a new instance of the <see cref="Location"/> class with the specified latitude, longitude and timestamp.
```suggestion
		/// Initializes a new instance of the <see cref="Location"/> class with the specified latitude, longitude, and timestamp.
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="timestamp">Timestamp for the location (UTC based).</param>
```suggestion
		/// <param name="timestamp">UTC timestamp for the location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// Initializes a new instance of the <see cref="Location"/> class with the specified latitude, longitude and altitude.
```suggestion
		/// Initializes a new instance of the <see cref="Location"/> class with the specified latitude, longitude, and altitude.
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="latitudeStart">Latitude coordinate of the starting location where is being calculated from.</param>
```suggestion
		/// <param name="latitudeStart">Latitude coordinate of the starting location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="longitudeStart">Longitude coordinate of the starting location where is being calculated from.</param>
```suggestion
		/// <param name="longitudeStart">Longitude coordinate of the starting location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="locationEnd">End location to calculate the distance to.</param>
```suggestion
		/// <param name="locationEnd">The end location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="locationStart">Start location to calculate from.</param>
```suggestion
		/// <param name="locationStart">The start location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="latitudeEnd">Latitude coordinate of the end location where we're calculating the distance to.</param>
```suggestion
		/// <param name="latitudeEnd">Latitude coordinate of the end location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="longitudeEnd">Longitude coordinate of the end location where we're calculating the distance to.</param>
```suggestion
		/// <param name="longitudeEnd">Longitude coordinate of the end location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="locationStart">Start location to calculate from.</param>
```suggestion
		/// <param name="locationStart">The start location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="longitudeStart">Longitude coordinate of the starting location where is being calculated from.</param>
```suggestion
		/// <param name="longitudeStart">Longitude coordinate of the starting location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="latitudeEnd">Latitude coordinate of the end location where we're calculating the distance to.</param>
```suggestion
		/// <param name="latitudeEnd">Latitude coordinate of the end location.</param>
```

2022-12-07 20:34 UTC, hartez commented on src/Essentials/src/Types/Location.shared.cs
> +		/// <param name="longitudeEnd">Longitude coordinate of the end location where we're calculating the distance to.</param>
```suggestion
		/// <param name="longitudeEnd">Longitude coordinate of the end location.</param>
```

2022-12-13 15:57 UTC, hartez approved these changes

2022-12-13 15:58 UTC, merged

2023-01-05 15:48 UTC, Redth commented
/backport to net7.0