Update Essentials Map API Docs
dotnet/maui pull request #11936
Opened 2022-12-07 14:29 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2022-12-13 18:44 UTC, hartez requested changes

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific location with launch options.
```suggestion
		/// then opens the installed application to a specific location with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific placemark with launch options.
```suggestion
		/// then opens the installed application to a specific placemark with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific location with launch options.
```suggestion
		/// then opens the installed application to a specific location with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific location with launch options.
```suggestion
		/// then opens the installed application to a specific location with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific location with launch options.
```suggestion
		/// then opens the installed application to a specific location with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific location with launch options.
```suggestion
		/// then opens the installed application to a specific location with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific location with launch options.
```suggestion
		/// then opens the installed application to a specific location with launch options.
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="latitude">Latitude to open to.</param>
```suggestion
		/// <param name="latitude">Target latitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// <param name="longitude">Longitude to open to.</param>
```suggestion
		/// <param name="longitude">Target longitude.</param>
```

2022-12-13 18:44 UTC, hartez commented on src/Essentials/src/Map/Map.shared.cs
> +		/// then open the installed application to a specific placemark with launch options.
```suggestion
		/// then opens the installed application to a specific placemark with launch options.
```

2022-12-15 11:46 UTC, rmarinho approved these changes

2023-01-10 17:13 UTC, hartez approved these changes

2023-01-10 17:13 UTC, merged

2023-01-19 15:43 UTC, mattleibow commented
/backport to net7.0