Maui 395 port editor autosize to handler
dotnet/maui pull request #1202
Opened 2021-06-08 00:51 UTC by AndrewLang

### Description of Change ###

Implements #395 Port Editor.AutoSize to handler

### Additions made ###

- Adds interface `ITextInputAutoSize` with AutoSize property
- Adds AutoSize property map to EditorHandler
- Adds AutoSize mapping methods to EditorHandler for Android and iOS
- Adds extension methods to apply AutoSize on Android/iOS
- Adds UILabel subclass MauiLabel (to support Padding, since UILabel doesn't by default)
- Adds DeviceTests for initial AutSize values on iOS and Android
- Implements ITextInputAutoSize on IEditor

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [x] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

2021-06-08 00:51 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=1202) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=1202) before we can accept your contribution.<br/><br/>:x: AndrewLang [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=1202)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=1202) it.</sub>

2021-06-08 07:20 UTC, AmrAlSayed0 commented
The thing about this property is that it is not a inherit property of the editor but it is a property of the _behavior_ of the editor. This changes the font size of the editor, should FontSize on the VirtualView be changed to be synced with the actual editor's FontSize? I mean this is a rare case but I would imagine a scenario where someone auto sizes an editor and then reads the new size to use it to size some other editor's or label's font.

2021-06-08 07:44 UTC, jsuarezruiz commented on src/Core/tests/DeviceTests.Android/Core.DeviceTests.Android.csproj
> +    <AotAssemblies>false</AotAssemblies>
These changes seem unrelated, could you undo them?

2021-06-08 07:45 UTC, jsuarezruiz reviewed
Could you also add the [PortHandler] attributes to the Renderers?. Thanks!

2021-06-19 23:43 UTC, AndrewLang commented
> Could you also add the [PortHandler] attributes to the Renderers?. Thanks!

Yes, I have added attribute [PortHandler] to EditorRenderer. Anything els.

2021-07-01 22:09 UTC, PureWeen requested changes

2021-07-01 22:09 UTC, PureWeen commented on src/Core/src/Platform/Android/EditTextExtensions.cs
> +				editText.SetAutoSizeTextTypeUniformWithConfiguration(editText.AutoSizeMinTextSize, editText.AutoSizeMaxTextSize, editText.AutoSizeStepGranularity, (int)ComplexUnitType.Sp);
I don't think this is the correct API to use for this one.  Doesn't this API cause the font to autosize? We don't want the font to change size based on the size of the editor.  In the original implementation Android was able to just update its size by re-measuring so we might need to change the invalidation code.

2021-07-01 22:22 UTC, PureWeen commented
@AndrewLang I rebased this PR as well so hopefully that doesn't mess you up too much locally

2021-07-02 17:12 UTC, PureWeen commented on src/Core/src/Platform/Windows/TextBoxExtensions.cs
> +				textBox.AcceptsReturn = false;
I don't think this is the correct approach for this. The Editor should always be set to AcceptsReturns = true

For example if the user forces the height of the editor to "500" then the editor should still accept returns 

I think what you might be running up against here are some layout behavior that's not implemented yet

Which is why things aren't resizing for you

2021-11-16 21:56 UTC, PureWeen commented
/azp run

2021-11-16 22:10 UTC, hartez approved these changes

2021-11-16 22:35 UTC, PureWeen commented
/azp run

2021-11-18 21:28 UTC, PureWeen commented
/azp run

2021-11-18 22:56 UTC, PureWeen approved these changes

2021-11-18 22:56 UTC, merged