Notify CheckBox Foreground update after Color changed (alternative)
dotnet/maui pull request #12102
Opened 2022-12-14 14:46 UTC by jsuarezruiz

### Description of Change

Notify Foreground update after Color changed. We was invalidating the UpdateForeground method before update the Foreground property value. This PR is an alternative approach to https://github.com/dotnet/maui/pull/9678

![fix-9404](https://user-images.githubusercontent.com/6755973/186897391-85f75fa5-cca4-497b-9f0e-dcad7d337645.gif)

### Issues Fixed

Fixes #9404

2022-12-28 18:16 UTC, PureWeen requested changes
Looks good! Can you add a test for the color change?

2023-01-10 13:52 UTC, jsuarezruiz commented
> Looks good! Can you add a test for the color change?

Sure thing, added some device tests.
![image](https://user-images.githubusercontent.com/6755973/211569114-b95c8c23-6852-4848-8b69-74ba75b477c9.png)

Could you review it again?

2023-01-10 16:19 UTC, PureWeen approved these changes

2023-01-10 18:49 UTC, merged

2023-01-19 15:46 UTC, mattleibow commented
/backport to net7.0