Rename W2DImage to PlatformImage
dotnet/maui pull request #12104
Opened 2022-12-14 15:32 UTC by jfversluis

_Copied details from: #9948_

### Description of Change

With this changes we can avoid this issue:
![image](https://user-images.githubusercontent.com/6755973/176698917-e99423bc-686b-49e7-b724-ac0e41f6ed99.png)
I have renamed not only W2DImage, but also W2Canvas and other classes to align the naming with the rest of platforms.

NOTE: This will be landing in .NET 8 because of the API changes

### Issues Fixed

Fixes #8509
Fixes https://github.com/dotnet/Microsoft.Maui.Graphics/issues/457
Fixes https://github.com/dotnet/Microsoft.Maui.Graphics/issues/402
Fixes https://github.com/dotnet/docs-maui/issues/722
Fixes https://github.com/dotnet/docs-maui/issues/820
Fixes https://github.com/dotnet/docs-maui/issues/1122

2022-12-15 11:40 UTC, jsuarezruiz reviewed
Pending changes in the public API `D:\a\_work\1\s\src\Core\src\Platform\Windows\GraphicsExtensions.cs(113,50): error RS0016: Symbol 'AsPoint' is not part of the declared API [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net7.0-windows10.0.19041]`

2022-12-15 14:22 UTC, mattleibow commented
Instead of a straight rename, can we rather make it conditional. If we just rename we break all existing code.

By conditional I mean we can make the win2d nuget still using the old name, and add the new name to graphics. We can use file linking and set some defines.

This was we can make win2d ToPlatformImage and stuff convert to the new types.

This is all because breaking this now might be very bad. And we can obsolete the old name too.

2022-12-15 14:24 UTC, mattleibow requested changes
This is all very good but we need to keep the old win2d package and use that to redirect customers.

We can also do implicit converters if need be.

2022-12-15 14:24 UTC, mattleibow commented on src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Shipped.txt
> -~override Microsoft.Maui.Controls.Handlers.PolygonHandler.ConnectHandler(Microsoft.Maui.Graphics.Win2D.W2DGraphicsView nativeView) -> void
We can't edit the shipped files. Only a release branch can.

2023-01-17 19:14 UTC, jfversluis commented
Closing this in favor of #12578

2023-01-17 19:14 UTC, closed without merging