Give fallback width/height for Shapes prior to layout
dotnet/maui pull request #12356
Opened 2022-12-30 16:53 UTC by hartez

### Description of Change

The GetPath implementations in several shapes are relying on the Width/Height values being set, which is invalid if the shapes have not been through the layout process.

These changes add an internal version of GetPath() for use in PathForBounds() which includes width/height parameters; the updated implementation of PathForBounds() uses the Width/Height properties if they are set and falls back to the width/height values in the viewBounds parameter if they are not (equivalent to the behavior before #12326). 

The parameterless implementations of GetPath() are left intact (still using the Width/Height properties). 

### Issues Fixed

Ellipses and Rectangles no longer rely on Width/Height being set at points in the lifecycle when those values are not available.

2022-12-30 23:05 UTC, PureWeen approved these changes

2023-01-02 11:29 UTC, rmarinho requested changes
```
D:\a\_work\1\s\src\Core\tests\DeviceTests.Shared\HandlerTests\HandlerTestBase.cs(173,23): error CS1061: 'View' does not contain a definition for 'AssertColorAtPointAsync' and no accessible extension method 'AssertColorAtPointAsync' accepting a first argument of type 'View' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Core\tests\DeviceTests.Shared\Core.DeviceTests.Shared.csproj::TargetFramework=net7.0-tizen]
    294 Warning(s)
```

2023-01-03 11:43 UTC, rmarinho approved these changes

2023-01-04 12:20 UTC, mattleibow reviewed
This is good as it stands with regards to code. However this causes an issue in some areas:

1. I can no longer make a custom shape because of the new internal abstract
2. If I have a custom shape (derived from say Rectangle) and have been overriding the parameterless method, now my code is no longer being run

Not sure what to do here... This method will probably have to go public in net8 to avoid the first issue. But the second one is still an issue.

2023-01-04 12:25 UTC, rmarinho commented
Since this is target to main that is net8, can't we already add the api as public instead of internal ?

2023-01-04 15:50 UTC, hartez commented
> This is good as it stands with regards to code. However this causes an issue in some areas:
> 
> 1. I can no longer make a custom shape because of the new internal abstract

Presumably this would break any existing custom shapes, too, right? Probably need to make that method `internal virtual` with an empty body.

> 2. If I have a custom shape (derived from say Rectangle) and have been overriding the parameterless method, now my code is no longer being run

For Path, Polyline, Polygon, and Line it's not an issue, because the new method just calls the old one. But yeah, it's an issue for Ellipse and the Rectangles. Let me see if I can work out a way to not break that.

2023-01-04 17:37 UTC, hartez commented
@mattleibow Okay, went with a different tactic to avoid the new internal method and keep existing shape subclasses working as they did before. It's not elegant, but I don't think it breaks anything.

2023-01-06 17:18 UTC, hartez commented
/azp run

2023-01-06 21:46 UTC, mattleibow approved these changes
Much better, but still ugly :(

Not sure how to do this right even if we could change the API... Might need to do some funny stuff.

2023-01-06 21:46 UTC, merged

2023-01-12 22:02 UTC, PureWeen commented
/backport to net7.0