Update Essentials Share API Docs
dotnet/maui pull request #12722
Opened 2023-01-17 19:20 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2023-01-17 19:50 UTC, hartez requested changes, later dismissed

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share a single file.
```suggestion
		/// Show the operating system's user interface to share a single file.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share multiple files.
```suggestion
		/// Show the operating system's user interface to share multiple files.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share text.
```suggestion
		/// Show the operating system's user interface to share text.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share text.
```suggestion
		/// Show the operating system's user interface to share text.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share text.
```suggestion
		/// Show the operating system's user interface to share text.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share a single file.
```suggestion
		/// Show the operating system's user interface to share a single file.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share multiple files.
```suggestion
		/// Show the operating system's user interface to share multiple files.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Show the operating systems user interface to share text.
```suggestion
		/// Show the operating system's user interface to share text.
```

2023-01-17 19:50 UTC, hartez commented on src/Essentials/src/Share/Share.shared.cs
> +		/// Gets or sets the title to use on the operating systems share user interface.
```suggestion
		/// Gets or sets the title to use on the operating system's share user interface.
```

2023-01-19 09:17 UTC, mattleibow approved these changes

2023-01-19 09:17 UTC, merged

2023-01-26 15:54 UTC, PureWeen commented
/backport to net7.0