Update SemanticScreenReader API Docs
dotnet/maui pull request #12724
Opened 2023-01-17 19:32 UTC by jfversluis

### Description of Change

Moves the external comments to inline and minor improvements.

### Issues Fixed

Related to #3960

2023-01-17 19:45 UTC, hartez requested changes, later dismissed

2023-01-17 19:45 UTC, hartez commented on src/Essentials/src/SemanticScreenReader/SemanticScreenReader.shared.cs
> +		/// Announces the specified text through the operating systems screen reader.
```suggestion
		/// Announces the specified text through the operating system's screen reader.
```

2023-01-17 19:45 UTC, hartez commented on src/Essentials/src/SemanticScreenReader/SemanticScreenReader.shared.cs
> +		/// Announces the specified text through the operating systems screen reader.
```suggestion
		/// Announces the specified text through the operating system's screen reader.
```

2023-01-19 09:06 UTC, mattleibow approved these changes

2023-01-19 09:06 UTC, merged

2023-01-26 15:54 UTC, PureWeen commented
/backport to net7.0