[Android] Avoid to disconnect a disposed PlatformView on Android
dotnet/maui pull request #12881
Opened 2023-01-24 13:25 UTC by jsuarezruiz

### Description of Change

Avoid to disconnect a disposed PlatformView on Android.

### Issues Fixed

Fixes #12644

2023-02-03 02:08 UTC, jean-marinduque commented
hi, was wondering when will this be released? I am encountering an issue that this release might fix

2023-02-05 04:56 UTC, PureWeen requested changes
Do we have code anywhere that's disposing of `MauiAppCompatEditText` ?  I wonder why it's getting disposed of in the first place. 

Like, if we override dispose on `MauiAppCompatEditText` can we trigger the conditions of when it gets hit?

2023-02-07 16:44 UTC, mandel-macaque approved these changes

2023-02-08 12:58 UTC, jsuarezruiz commented
> Do we have code anywhere that's disposing of `MauiAppCompatEditText` ? I wonder why it's getting disposed of in the first place.
> 
> Like, if we override dispose on `MauiAppCompatEditText` can we trigger the conditions of when it gets hit?
> 
> I think the bug is with framerenderer and this code here
> 
> <img alt="image" width="577" src="https://user-images.githubusercontent.com/5375137/216802644-30b6a9c1-b14f-4c2d-8684-33a0a92d83c6.png">
> 
> I think when `ViewHandlerDelegate` we need to not call dispose here and just remove this code.

I was suspicious of `ShellSection` and changing tabs but I have not been able to reproduce it, although from the logs it is clearly trying to dispose a `MauiAppCompatEditText ` already disposed.

2023-03-01 08:07 UTC, jean-marinduque commented
any update?

2023-03-01 18:02 UTC, PureWeen commented
@jean-marinduque do you have a stack trace of your exception?

2023-03-01 18:17 UTC, PureWeen requested changes
Based on the stack trace I think this is a bug inside `FrameRenderer`

When dispose is called we are calling `Dispose` on all the children and then calling `DisconnectHandler` on the `Frame`

![image](https://user-images.githubusercontent.com/5375137/222224867-56fd534d-a100-47d1-a872-7496ccb5c3ef.png)

I think we need to just remove the call to `child?.dispose` 

We should probably also remove the call to `dispose` inside `ViewHandlerDelegator` when `DisconnectHandler` is called as well. 

If we want to make a change around checking if the platform view is alive then I wonder if we want to generalize that. 

We already have a call called `CanInvokeMappers` where we won't invoke any mappers when disposed, so maybe we need that for disconnect as well.  Ideally we wouldn't :-/ but might not hurt

2023-03-10 08:06 UTC, closed without merging