Fix timing on iOS Toolbar
dotnet/maui pull request #12888
Opened 2023-01-24 16:50 UTC by PureWeen

### Description of Change

With MAUI we moved the code for processing `Toolbar` logic up into the xplat layer by way of an xplat `Toolbar` control. This allowed us to consolidate the toolbar logic that was copy and pasted across all platforms and between shell and non-shell. On iOS the shell toolbar management is handled by `ShellPageToolbarTracker` which gets instantiated for every single page. The code inside that tracker needs to ignore any `toolbar` updates if it's not the currently visible page. 

iOS is also a little bit tricky to wire up with regards to timing the back button title text. The BackButton text is based on the  `UIViewController.NavigationItem` of the previous page so we have to pull the `BackButtonBehavior` off the incoming page and set it on the `NavItem` of the previous page before the current page is visible.  `NavigationPage` gets around this by making it so the user has to set `NavigationPage.BackButtonTitle` on the previous page. `NavigationPage` basically replicates how `iOS` propagates back button text where as `Shell` lets you set the back button text on the currently visible page. 

### Issues Fixed

Fixes #10945
Fixes #11691
Fixes #9269
Fixes #9842
Fixes #9687

2023-01-24 17:22 UTC, PureWeen commented
@rmarinho I tested this on a 13.7 and a 14.5 iPhone

Let me know if I should test back further from that.

2023-01-24 21:07 UTC, PureWeen commented on src/TestUtils/src/DeviceTests/AssertionExtensions.iOS.cs
> +				return result.Class.Name?.Contains("UINavigationBarContentView", StringComparison.OrdinalIgnoreCase) == true;
@rmarinho

2023-01-26 12:31 UTC, rmarinho requested changes
@PureWeen  seems is failing just 1 test now 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7243580&view=ms.vss-test-web.build-test-results-tab

2023-01-26 23:05 UTC, rmarinho approved these changes

2023-01-26 23:05 UTC, merged

2023-04-13 09:11 UTC, PureWeen commented
Adding this one back into the pool for some discussion. This one fixes a bunch of issues and I think we can break apart a few parts of this one. 

For example, I think just backporting the xplat changes [here](https://github.com/dotnet/maui/pull/12888/files#diff-953760fc28b84326460f63e7ca19e18a6554962c946d851a456948b1b5db3e85R1509-R1516) will fix a number of issues

2023-04-19 13:28 UTC, angelru commented
When will these changes be available?