Replace MessagingCenter in AlertManager
dotnet/maui pull request #12910
Opened 2023-01-25 22:29 UTC by mattleibow

### Description of Change

Since the `MessagingCenter` was obsolete and now marked internal, we would love to remove it! Now it is happening!!!

This PR starts that process by removing usages of the `MessagingCenter` in the `AlertManager`.

2023-01-26 08:23 UTC, jsuarezruiz commented
/azp run

2023-01-27 02:40 UTC, PureWeen commented
Can we also add an interface and register it to the scoped container? Maybe something like 

`IAlertPlatformManager` that all the platform level code gets moved to? 

Or is that a separate PR?

2023-01-27 09:46 UTC, mattleibow commented
Ah I am doing this as I have no way to test currently

2023-02-07 13:34 UTC, jsuarezruiz commented
There are several unit tests failing, I think there are pending changes in the tests too.

2023-02-07 13:42 UTC, mattleibow commented
Yeah, I need to have a look as we can no longer just subscribe to some global messaging center. A tiny bit tricky, but I am sure we can fix it :)

2023-02-10 22:29 UTC, hartez requested changes, later dismissed
Questions about null subscriptions.

2023-02-10 22:29 UTC, hartez commented on src/Controls/src/Core/Platform/AlertManager/AlertManager.cs
> +			// this really should not be happening so we should probably log this
So maybe let's do log this, then?

2023-02-10 22:29 UTC, hartez commented on src/Controls/src/Core/Platform/AlertManager/AlertManager.cs
> +			// this really should not be happening so we should probably log this
Is this even possible? Can CreateSubscription return null?

2025-04-08 14:21 UTC, jfversluis commented
Stale, let's go with #27888

2025-04-08 14:21 UTC, closed without merging