Fix Download warning
dotnet/maui pull request #13067
Opened 2023-02-01 21:02 UTC by lutzroeder

Fix `warning CS8321: The local function 'Download' is declared but never used` build warning.

2023-02-01 21:26 UTC, mattleibow approved these changes

2023-02-01 22:10 UTC, Eilon requested changes

2023-02-01 22:10 UTC, Eilon commented on eng/cake/dotnet.cake
> +        // void Download(string id, string version, params string[] sources)
I'd just delete it. Deleted code can be retrieved from source control.

2023-02-01 22:20 UTC, Eilon approved these changes

2023-02-02 00:49 UTC, mattleibow approved these changes

2023-02-02 01:17 UTC, merged