[iOS/MacCatalyst] Fix Editor scrolling
dotnet/maui pull request #13234
Opened 2023-02-09 19:50 UTC by rmarinho

### Description of Change

There were two issues keeping the Editor from scrolling:
 - We were always updating the ContentOffset to center the text, even if there was no available space. If there's no space to center (the text is bigger than the container) we should not center the text and just it be able to scroll.
- The constrains added to the placeholder so it has the same insets as the UITextView were keeping the UITextView from scrolling and right now I can't explain why. To fix this we can just use the MauiLabel that we have that allows to center and set insets to a UILabel.

I m not sure I can write a device test for this issue. 
To test the code you can visit the Editor gallery see it looks the same with and without this change. 
This code can be used to check that we are able to scroll and placeholders work.

```
<VerticalStackLayout
        Spacing="10"
        Padding="30,0"
        VerticalOptions="Center">
         <Editor Placeholder="Placeholder" />
         <Editor BackgroundColor="red" HeightRequest="100" Placeholder="Placeholder" VerticalTextAlignment="Center" />
       
        <Editor BackgroundColor="red" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="Center" />
        <Editor BackgroundColor="Yellow" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="End" />
        <Editor BackgroundColor="Green" HeightRequest="100" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />

    </VerticalStackLayout>
```

### Issues Fixed

Fixes #12485

2023-02-09 20:20 UTC, mandel-macaque approved these changes

2023-02-13 18:08 UTC, tj-devel709 commented
I found an issue most likely.

If I put the editor inside something scrollable (and there is enough content to actually scroll), I can no longer focus the editor. In the below example, the editors that are not focusable are the Blue and Orange ones.

```xaml
<VerticalStackLayout
        Spacing="10"
        Padding="30,0"
        VerticalOptions="Center">
        <Editor Placeholder="Placeholder" />
        <Editor BackgroundColor="red" HeightRequest="100" Placeholder="Placeholder" VerticalTextAlignment="Center" />

        <Editor BackgroundColor="red" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="Center" />
        <Editor BackgroundColor="Yellow" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="End" />
        <Editor BackgroundColor="Green" HeightRequest="100" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />

        <ScrollView>
            <VerticalStackLayout>
                <BoxView HeightRequest="800"/>
                <Editor BackgroundColor="Blue" HeightRequest="100" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />
                <Editor BackgroundColor="Orange" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="Center" />
                <BoxView HeightRequest="800"/>
            </VerticalStackLayout>
        </ScrollView>

        <BoxView HeightRequest="800"/>

    </VerticalStackLayout>
``` 


https://user-images.githubusercontent.com/50846373/218538027-1f2b54f5-b67b-449d-8d48-37156d36d118.mov

2023-02-13 18:09 UTC, tj-devel709 requested changes
See above post :)

2023-02-14 02:21 UTC, tj-devel709 commented
When testing current behavior on the main branch, in the sandbox, the inner scrollview did not want to scroll. I'm not sure why but I made the boxviews smaller so you can see the blue and orange editors there. They are editable, but again, that scroll is not working so I'm not sure

https://gist.github.com/tj-devel709/50731bbb10b18414bbb96a0f00fec158

https://user-images.githubusercontent.com/50846373/218622281-2fcaa6c6-1164-49e6-b3f9-681b28715b65.mov

2023-02-14 14:36 UTC, rmarinho commented
@tj-devel709  I think the issue is more with having scrollview inside vertical stack layout that will not work since the VerticalStackLayout will stretch .. try this sample code the archives what you wanted to test I think 

```
<Grid
        Padding="30,0"
        VerticalOptions="Center">
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>

        <VerticalStackLayout>
            <Editor Placeholder="Placeholder" />
            <Editor BackgroundColor="red" HeightRequest="100" Placeholder="Placeholder" VerticalTextAlignment="Center" />

            <Editor BackgroundColor="red" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="Center" />
            <Editor BackgroundColor="Yellow" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="End" />
            <Editor BackgroundColor="Green" HeightRequest="100" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />
        </VerticalStackLayout>
        <ScrollView>
            <VerticalStackLayout>
                <BoxView HeightRequest="200"/>
                <Editor BackgroundColor="Blue" HeightRequest="100" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />
                <Editor BackgroundColor="Orange" HeightRequest="100" Text="Lorem ipsum dolor sit amet" VerticalTextAlignment="Center" />
                <BoxView HeightRequest="500" BackgroundColor="Pink"/>
            </VerticalStackLayout>
        </ScrollView>
    </Grid>
    ```

2023-02-14 15:40 UTC, tj-devel709 commented
Okay, yeah you get something like this then!

Uploading Screen Recording 2023-02-14 at 9.39.24 AM.mov…

2023-02-15 12:44 UTC, rmarinho commented
Hum seems to work fine here, btw on the scrollview set   <ScrollView Grid.Row="1">


https://user-images.githubusercontent.com/1235097/219030587-21ac1782-4a84-4e54-af72-67cbb5cd4c50.mov

2023-02-15 19:35 UTC, tj-devel709 commented
> Hum seems to work fine here, btw on the scrollview set

Can you edit the text in the editors inside the scrollview area?

2023-02-16 22:02 UTC, tj-devel709 approved these changes
Working pretty good for me now :)

2023-02-16 22:06 UTC, merged

2023-02-27 19:04 UTC, avilink commented
Will this fix be merged into .NET 7 as well? Or do we need to switch to .NET 8 preview 1 now?

2023-04-09 21:27 UTC, hxhannes68 commented
I need this fix in .NET7 as well. Is there no other way? Can I apply the change you made here to my .NET 7 project as well? Replace the control? Or just use it as a new one?

2023-06-01 05:09 UTC, cat0363 commented
Hopefully this fix will be backported to .NET 7.
On iOS, it's a fatal bug. I'm having trouble because scrolling doesn't work 
when I enter a string that exceeds the height of the Editor. 
If you don't plan to backport, could you point me to a workaround?
Thank you.

2023-08-04 14:43 UTC, SamuelJames101 commented
Need this back ported to .Net 7

2023-08-08 22:41 UTC, babenkovitaliy commented
This is extremely frustrating how a whole bunch of fixes are getting pushed only to .NET 8, which is not getting released until November. The whole purpose of having new major releases is to release features, not bug fixes. C'mon Microsoft!!

2023-08-14 10:46 UTC, Hooterr commented
Wow, this is extremely basic and should've been added to .net 7 months ago...

2023-08-17 20:43 UTC, babenkovitaliy commented
I gave up on Microsoft doing the right thing (from laying their long-time employees to releasing bug fixes to existing live products). The fact that .NET 7.0 feels like an alpha build forced my hand to move my application to .NET 8.0, since the "preview" feature seems like a more stable build than a "Golden Build" .NET 7.0.

2023-09-26 18:00 UTC, gerhartz commented
@rmarinho @PureWeen any chance this will get into .Net 7? Or at least a workaround? Its unusable right now on iOS. I dont know how we are all expected to ship production Maui apps with this.

2023-10-03 14:28 UTC, FM1973 commented
Did anyone find a workaround for .net 7?