[iOS] Fix sizing of button when using CharacterSpacing
dotnet/maui pull request #13250
Opened 2023-02-10 15:50 UTC by rmarinho

### Description of Change

We were setting the CharacterSpacing on the internal label while we can use the AttributedTitle on UIButton itself so it sizes correctly .

### Issues Fixed

Fixes #10293

2023-02-10 22:09 UTC, mandel-macaque approved these changes

2023-02-10 22:20 UTC, hartez commented
@rmarinho   Looks like the device test needs to be updated. Maybe the `GetNativeCharacterSpacing()` method should be using `GetAttributedTitle()` instead of `TitleLabel`?

2023-02-10 22:20 UTC, hartez requested changes
Change looks good, need to bring the tests up to date.

2023-02-13 19:25 UTC, hartez approved these changes

2023-02-14 11:32 UTC, jsuarezruiz commented on src/Core/tests/DeviceTests/Handlers/Button/ButtonHandlerTests.iOS.cs
> +			//var attributedText = button.TitleLabel.AttributedText;
Can we remove the commented line?

2023-02-14 11:32 UTC, jsuarezruiz commented on src/Core/tests/DeviceTests/Handlers/Button/ButtonHandlerTests.iOS.cs
> +			var attributedText = button.GetAttributedTitle(UIControlState.Normal);
The changes looks nice, and we already have tests validating the CharacterSpacing property but could we add a device test where we get the width of the native button before updating the CharacterSpacing and after setting it and check that the updated value is greater than the initial one?

2023-02-15 15:58 UTC, jsuarezruiz approved these changes

2023-02-15 15:58 UTC, merged