Essentials: Port Xamarin.MediaGallery
dotnet/maui pull request #13564
Opened 2023-02-25 21:30 UTC by dimonovdd

### Description of Change

[Xamarin.MediaGallery](https://github.com/dimonovdd/Xamarin.MediaGallery) was created as temporary solution. During its existence, that project has helped many developers. `PickAsync`,  `CapturePhotoAsync` and `SaveAsync ` were debugged and tested in it in many projects. 

It's time to get rid of this workaround. 

### API Changes 

1.  All members from `IMediaPicker` and `MediaPicker` marked as `[Obsolete("Use MediaGallery")]`
2.  All logic is moved to new `IMediaGallery` and `MediaGallery`

### Behavioral Changes

#### iOS

- `PHPickerViewController` for iOS above 13

#### Android

- [New Photo picker](https://developer.android.com/training/data-storage/shared/photopicker) for Android above API 30 with ExtensionVersion >= 2
- Removed the use of `IntermediateActivity`. This is a very bad disease of `Essentials`. `IntermediateActivity` to an increase in the probability of destruction of `MainActivity`, a need to request unnecessary permissions, ugly visual behavior together with `Intent.CreateChooser` and etc.

### Related with

1.  [Xamarin.MediaGallery](https://github.com/dimonovdd/Xamarin.MediaGallery)
2.  https://github.com/xamarin/Essentials/pull/1628
3.  https://github.com/xamarin/Essentials/pull/1750 and https://github.com/xamarin/Essentials/pull/1475
4.  and more issues 

### Status

- [ ] Android (partially implemented)
- [ ] iOS
- [ ] UWP
- [ ] Tizen
- [ ] Sample
- [ ] Tests

2023-02-26 19:20 UTC, dimonovdd commented
@jfversluis Hi

I think the API should not contain the ability to edit files (Rotate, Quality and etc.). We can do it as extension methods in Community Toolkit.

```csharp
public static void Rotate(this MediaFileResult file)
{

}
```



https://gist.github.com/jfversluis/431488a54ab67b56cf54368e0ef1eb35

2023-02-27 02:42 UTC, drasticactions commented
I don't know the advantages of merging this code into the mainline of MAUI versus leaving it as a separate library or moving it into the community toolkit instead. Moving it into MAUI would tie this code to its release schedule, making it harder to iterate on changes or release fixes should the need arise. Couldn't we obsolete the existing Media Picker control and point people to this library or the community toolkit instead?

2023-02-27 08:01 UTC, dimonovdd commented
> Couldn't we obsolete the existing Media Picker control and point people to this library or the community toolkit instead?

What about FilePicker, Contacts and etc. They all have problems.

2023-02-27 16:53 UTC, mandel-macaque requested changes

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.android.cs
> +				File.Delete(_tempFilePath);
There is not need to do a  File.Exists, File.Delete already does that check, from https://learn.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-7.0#remarks

> If the file to be deleted does not exist, no exception is thrown.

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +			Extension = document.FileUrl.PathExtension!;
re we sure we want to ignore the PathExtension being null? can Extension be already nullable?

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +		NSUrl assetUrl;
Missing nullability annotations

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +			base.PlatformDispose();
id document and assetUrl are set by all the constructors, they do not need to be nullable and we won't need to add ? or set them to null. Looks like there is something funny with the nullability annotations in the code.

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +			return Task.FromResult(imgWithMetadata?.AsStream());
The compiler should have thrown a warning, we are returning a Task<Stream?> when the signature states is a Task<Stream>

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +			if (img == null || metadata == null)
```suggestion
			if (img is null || metadata is null)
```

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +		NSMutableData imgWithMetadata;
Same comment as with the previous

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +				return;
this will leave the object in un "unknown" state, is that what we want over throwing an exception? Will that result in an error later?

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +			base.PlatformDispose();
Same comment

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +			if (!(identifiers?.Length > 0))
Making thins complicated. We can check for null, in the later part of the method you do FirstOrDefault, so if the array is empty, you will get the default => null.

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.cs
> +				return identifiers.FirstOrDefault(i => i == UTTypes.Jpeg.Identifier);
Any followed by a first or default is a double iteration of the IEnumerable that should not be needed.Can we just simplify this ifs to not iterate that many times over the collection?

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.ios.tvos.watchos.macos.cs
> +				: OldUTType.CopyAllTags(identifier, OldUTType.TagClassMIMEType)?.FirstOrDefault();
The nullability of the return types seems to be wrong. Should be string?

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/FileSystem/FileSystem.shared.cs
> +			return null;
Could be much simpler with a switch expression.

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.android.cs
> +			Uri outputUri = null;
```suggestion
			Intent? intent = null;
			Uri? outputUri = null;
```

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.android.cs
> +				return null;
Returning null gut the method signature is Task<IEnumerable<MediaFileResult>>, either change the signature or return Array.Empty<MediaFileResult>()

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.android.cs
> +			Intent intent = null;
```suggestion
			Intent? intent = null;
```

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.android.cs
> +			if (data != null && !(clipCount > 1))
```suggestion
			if (data is not null && clipCount <= 1)
```

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.uwp.cs
> +			if (file != null)
```suggestion
			if (file is not null)
```

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.uwp.cs
> +			return null;
Either do not return null or change the signature. Array.Empty would work here as with the previous comment.

2023-02-27 16:53 UTC, mandel-macaque commented on src/Essentials/src/MediaGallery/MediaGallery.uwp.cs
> +					return null;
Same comment as with previous methods.

2023-02-27 16:55 UTC, dimonovdd commented
@mandel-macaque thanks. But this is draft

2023-02-27 23:34 UTC, drasticactions commented
> > It may well be worth it, but that's the cost someone on the MAUI team may need to pay in the future.
> 
> I think someone thought about it when API was added to Essentials

I would argue the opposite, hence why it is in the condition it's in.

2023-03-05 14:58 UTC, dimonovdd commented
@jfversluis @mattleibow Hi
Do you have any ideas or comments?

2023-03-06 09:23 UTC, jfversluis commented
Sorry it took a little while to get back to you! We had to discuss a couple of things about this. Here is our/my thoughts.

In it's current form I don't think this is something we want to do. 

What I like about this PR is that we're going to `MediaGallery` which opens up possibilities for the future. You've already added functionality to save something to the gallery for instance, which wouldn't make sense with the `MediaPicker` name. So that's great!

However, I don't think enough value is added to warrant the deprecation of `MediaPicker` and move to `MediaGallery`. What happens with this PR is that we present people with a breaking change, but ultimately they don't get much functionality in return.

Don't get me wrong, I see the use of the more modern APIs, picking multiple files, saving files and all that. But from all the feedback that I've been seeing what people _really_ want is the things I've mentioned to you before and described in the spec I was working on: rotation, or at least the meta data so they can do it themselves, compression, etc.

That is also where we have different opinions. I don't agree with the fact that the functionality to get the correct rotation should be in the .NET MAUI Community Toolkit. With a functionality like this I, as a developer, assume that I will be able to get the media in a way that I don't have to do all kinds of processing myself, certainly not when that processing functionality also involves taking on another dependency.

So back to this PR. Right now for us, unfortunately, this is not a priority. So you helping us out would definitely be amazing. But you have also stated that your time is limited which is understandable. If you are not able to do anymore work on this than you have already done, I think we should close this for now and revisit later.

If you do want to spend some more time on it I think here is some things that we want to consider:

* Add more value in the form of more functionality:
  * Add the option to get the rotated version
  * And/or provide the meta data with the picked file so people can rotate themselves
  * Add the option to resize/compress
  * Potentially other things in the spec I wrote, but the above I think is minimal
* I don't think deprecation and removal should be done in 1 version. We want to deprecate `MediaPicker` first just by adding the `[Obsolete]` tag, keep the functionality so people will have some time to actually make the switch from `MediaPicker` to `MediaGallery`, instead of being forced to update their app because `MediaPicker` is already deleted

Or, there is the whole thing that Tim mentioned above. Maybe we have to face that `MediaPicker` isn't living up to the quality that we'd like to and we can't give it the attention it deserves right now and we just need to deprecate it as a whole and provide it as a third-party package for the time being. Personally I'd hate that, but that does allow us to move a bit quicker and also already provide this for .NET 7.

The .NET MAUI Community Toolkit would then be a great fit I think to keep it close to the .NET MAUI main package, but we can take this functionality in as a whole, start building on top of it, shape it to what we want and hopefully in the future bring it back to .NET MAUI but now as a more complete solution.

In either case, thank you for your great work on the `MediaGallery` plugin throughout the years and your willingness to bring this to us in the form of this PR. I hope you can understand our point of view as well.

Let me know your thoughts! Or if anyone else wants to chime in that is appreciated as well of course. 😄

2023-12-01 15:36 UTC, jfversluis commented
OK, so before we reach the 1 year birthday of this PR let's deal with it. Unfortunately, in this case that means closing it for right now.

At this time we have other things that we have on our [roadmap](https://github.com/dotnet/maui/wiki/Roadmap) and where we want to spend our time. A big PR like this will take up a big chunk of our time reviewing, maybe write some code ourselves, testing, etc. Also, I do think I would want to make some changes to the API before we add this to .NET MAUI directly, which means we need to spend even more time on it. Since this is not something that we determined to be a higher priority right now, we can't do justice to your work and give it the attention it deserves, I'm going to have to close this for the time being.

Additionally, this code is already in a great plugin that is available for people and I hope that will continue to serve people well. As much as I, personally, want to improve this part of .NET MAUI out-of-the-box just as you, this is not the right time.

Thank you so much for the time and effort you have spend on this.

In order to still make this happen, for .NET MAUI, I think a good approach would be to divide it up significantly in many smaller PRs that are easier to digest for us as a team. However, I don't want to waste your time, so if you even are considering doing any more, please contact us first and talk about a plan.

Again, thank you and although this is probably not the outcome you had hoped it to be, at least it will bring some clarity for the time being.

2023-12-01 15:36 UTC, closed without merging