[Android] Fix issue calculating the threshold using SwipeItemViews
dotnet/maui pull request #13615
Opened 2023-03-01 11:06 UTC by jsuarezruiz

### Description of Change

Fix issue calculating the threshold using SwipeItemViews on Android.

![fix-open-prog-swipeview](https://user-images.githubusercontent.com/6755973/222122026-a4145e8c-e486-4020-8c6e-5225ef1765e8.gif)

### Issues Fixed

Fixes #13547

2023-03-01 11:11 UTC, jsuarezruiz commented on src/Core/src/Platform/Android/MauiSwipeView.cs
> +			UpdateSwipeItems();
With the changes, we measure the SwipeItemViews before getting the threshold. What happened was that the size obtained from each SwipeItemView was zero and the default thjreshold value was used.

2023-03-01 17:36 UTC, PureWeen requested changes
Can we add a test? 

When opening the swipeview programmatically we can see if the size matches what we expect?

2023-03-01 23:35 UTC, mandel-macaque approved these changes
Approving as long as @PureWeen are considered.

2023-03-10 13:09 UTC, jsuarezruiz commented
> Can we add a test?
> 
> When opening the swipeview programmatically we can see if the size matches what we expect?

Added different device tests.

2023-03-22 13:34 UTC, rmarinho approved these changes

2023-03-22 13:56 UTC, PureWeen approved these changes

2023-03-22 13:56 UTC, merged