[iOS] Implement ScrollView Orientation
dotnet/maui pull request #13657
Opened 2023-03-02 17:30 UTC by rmarinho

### Description of Change

Seems there was no specific implementation for ScrollViewOrientation on iOS. So it was always allowing to scroll in both directions, 13412 

The issue is the ContentSize of the UIScrollView is not set on the correct dimension by constraining to the size of the scrollview depending on the orientation. 
There `IContentView.CrossPlatformMeasure` on ScrollView.Impl does try to constrain when measuring using the orientation but the final `DesiredSize` is always the expressed WidthRequested/HeightRequested.

So one way to fix is to set take in account the orientation when setting the UIScrollView ContentSize.

- This pr also removes some old code we couldn't remove before but that was not being used anywhere.
- Removed: static Microsoft.Maui.Handlers.ScrollViewHandler.MapContentSize

```
public static Microsoft.Maui.Handlers.ScrollViewHandler.MapContentSize
public static Microsoft.Maui.Platform.ScrollViewExtensions.UpdateContentSize
```

### Issues Fixed

Fixes #13412

2023-03-02 17:34 UTC, rmarinho commented on src/Core/src/Platform/iOS/ScrollViewExtensions.cs
> +		internal static Size AccountForOrientation(this Size size, double widthConstraint, double heightConstraint, IScrollView view)
Should this be public now since is going to net8?

2023-03-02 17:54 UTC, mandel-macaque approved these changes

2023-03-02 22:52 UTC, rmarinho commented
@hartez I have specially doubts also why do we have 2 methods setting the ContentSize of the UIScrollView.

2023-03-08 21:41 UTC, hartez requested changes

2023-03-15 18:17 UTC, rmarinho commented on src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
> -		// We don't actually have this mapped because we don't need it, but we can't remove it because it's public
Ok I will remove this so we might want to also backport this pr.

2023-03-15 18:33 UTC, rmarinho commented on src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
> +			handler.PlatformView?.UpdateOrientation(scrollView);
I have tried with SetNeedsLayout() but that doesn't work. Doesn't seem to trigger any Measure or Arrange. 
The `UpdateOrieantation` will set the ContentSize.

2023-03-15 18:58 UTC, rmarinho commented on src/Core/src/Platform/iOS/ScrollViewExtensions.cs
> +		internal static Size AccountForOrientation(this Size size, double widthConstraint, double heightConstraint, IScrollView view)
Fixed!

2023-03-15 18:59 UTC, rmarinho commented on src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
> +			handler.PlatformView?.UpdateOrientation(scrollView);
I think I figured it out, I need to grab is the child ContainerView we create to host the Content

2023-03-15 20:02 UTC, rmarinho commented on src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
> +			handler.PlatformView?.UpdateOrientation(scrollView);
Should be good now

2023-03-17 15:23 UTC, hartez approved these changes

2023-03-17 15:23 UTC, merged

2023-03-22 08:00 UTC, Glorfindel83 commented
Thanks for fixing this - what's the easiest way to find out in which MAUI version this will be available? I have the repository downloaded but even with SourceTree it's complicated to get a good overview. (It's not that critical for me that I need to compile my own MAUI, I'm just using the Stable update channel in Visual Studio.)

2023-03-22 12:24 UTC, rmarinho commented
it would be in a net8 version, p3 or p4