Fix next keyboard into a ListView and TableView iOS
dotnet/maui pull request #13838
Opened 2023-03-11 00:17 UTC by tj-devel709

### Description of Change
On iOS, pressing the next keyboard button should bring us into the first element of a ListView or TableView. However, in the logical ordering, ListView and TableView cells are out of order. By using the TableView.VisibleCells, we can reorder as needed and allow the ordering of the elements to be as we expect.

I did not see a ListView or TableView stub in the src/Core/test directory, but I created a video demo here:

https://user-images.githubusercontent.com/50846373/224452298-9f229b31-edd1-4dda-bb5f-c6a9c7cd9fac.mov

### Issues Fixed

Fixes #13176

2023-03-11 00:19 UTC, tj-devel709 commented on src/Core/src/Platform/iOS/ViewExtensions.cs
> +				return table.FindNextView(0, isValidType);
Double check if we need this else?

2023-03-13 18:51 UTC, mandel-macaque approved these changes

2023-03-13 18:51 UTC, mandel-macaque commented on src/Core/src/Platform/iOS/ViewExtensions.cs
> +		internal static T? FindResponder<T>(this UIViewController controller) where T : UIViewController
+1 on the use of generics, well done.

2023-03-14 15:43 UTC, PureWeen commented on src/Core/src/Platform/iOS/ViewExtensions.cs
> +		internal static UIView? SetContainerView(this UIView? startingPoint)
```suggestion
		internal static UIView? GetContainerView(this UIView? startingPoint)
```

?

2023-03-14 16:36 UTC, tj-devel709 commented on src/Core/src/Platform/iOS/ViewExtensions.cs
> +		internal static UIView? SetContainerView(this UIView? startingPoint)
Fixed!

2023-03-16 17:27 UTC, PureWeen requested changes
Can we add tests to this?

2023-03-27 21:26 UTC, PureWeen commented on src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
> +					var firstResponder = layout.ToPlatform().FindFirstResponder();
This is probably fine. If we start seeing random failures from these tests we should move them all into a collection. As long as this block of code runs uninterrupted we should be fine.

2023-03-27 21:26 UTC, PureWeen approved these changes

2023-03-27 21:26 UTC, merged