[Windows] Fix Shadow positions issues
dotnet/maui pull request #13959
Opened 2023-03-15 13:10 UTC by jsuarezruiz

### Description of Change

Fix Shadow positions issues under some scenarios (with some Views). With this PR the shadow is invalidated after resize the shadow host or under other conditions like resizing the Window.
 
![fix-13944](https://user-images.githubusercontent.com/6755973/225318076-51d8d83c-6952-4a13-a8f5-90d04a9b6ecf.gif)

Can validate the changes with the added sample in the Shadows section from the .NET MAUI Gallery.

_NOTE: Is still a draft because I'm validating other issue using Transparent colors in the host._

### Issues Fixed

Fixes #13944

2023-03-16 08:32 UTC, jsuarezruiz commented
Have done tests validating the behavior with a Transparent background in the Host, and the Shadow is rendering now
![image](https://user-images.githubusercontent.com/6755973/225559495-c4f24aef-bbd5-4d55-961c-1478ff363b60.png)

2023-03-16 16:23 UTC, mandel-macaque requested changes

2023-03-16 16:23 UTC, mandel-macaque commented on src/Core/src/Platform/Windows/WrapperView.cs
> +				if (_shadowVisual != null)
```suggestion
				if (_shadowVisual is not null)
```

2023-03-20 15:51 UTC, mandel-macaque approved these changes

2023-03-22 16:17 UTC, rmarinho approved these changes

2023-03-22 16:18 UTC, merged