Fix ListProxy GC issues
dotnet/maui pull request #13973
Opened 2023-03-15 23:07 UTC by hartez

### Description of Change

Updates MultiPage tests to ensure that ListProxy collection changed handler issues show up consistently (rather than only showing up intermittently on release builds). 

Fixes weak reference issue with ListProxy's collection changed handler. The ListProxy is creating a WeakNotifyCollectionChangedProxy using a method group; there's no other reference to the generated delegate, so if the GC kicks in the delegate is collected and the collection changed handler no longer fires. This PR creates a reference to the delegate in ListProxy so the delegate isn't collected.

2023-03-15 23:25 UTC, mattleibow reviewed
@jonathanpeppers should we be using the await Yield trickery here in the tests?

2023-03-16 01:43 UTC, hartez commented
> @jonathanpeppers should we be using the await Yield trickery here in the tests?

Not sure what trickery you're referring to, but as written these fail consistently in debug mode without the fix - no trickery required.

2023-03-16 01:50 UTC, jonathanpeppers requested changes
Let me review what is going on here tomorrow. If this is a problem, this only fixes it in one place -- and it's in several places.

Or does this one somehow work because it is a lamdba expression?

https://github.com/dotnet/maui/blob/7e2ee17fdede96aed837f599a6c7f0d1be109595/src/Controls/src/Core/VisualElement.cs#L107

2023-03-16 05:44 UTC, jonathanpeppers approved these changes
Ok, this change is good -- fixes part of the issue. I will merge so other PRs can be green.

I will address the other cases like this tomorrow, example in https://github.com/jonathanpeppers/maui/commit/03a9e60802f28ce2f569389a6a62681705718859.

2023-03-16 05:45 UTC, merged