Do not scroll for UIAlertControllers
dotnet/maui pull request #14100
Opened 2023-03-21 17:30 UTC by tj-devel709

### Description of Change

When a UIAlertController is rendered, the scrolling is already handled behind the scenes. There is not a need for any additional scrolling to happen here so we can ignore the scrolling on the KeyboardAutoManagerScroll side.

https://user-images.githubusercontent.com/50846373/226692800-e10f2d34-f2ce-4a42-8e73-f42449d53925.mov

### Issues Fixed

Fixes #14041

2023-03-22 16:05 UTC, drasticactions approved these changes
Tried on the PR branch and it worked for me.

2023-03-22 20:14 UTC, PureWeen requested changes
Looks good! Add tests and toggle the `IsKeyboardScrolling` flag!

2023-03-27 21:37 UTC, PureWeen commented on src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
> +						_ = uIWindow.RootViewController.PresentViewControllerAsync(alert, true);
I don't think we want to ignore past these Async calls. 

My thoughts for this test
1) await these calls
2) make this test part of a Collection. You can see where this is done a few places with an inner class

[Category(TestCategory.Accessibility)]
		[Collection(ControlsHandlerTestBase.RunInNewWindowCollection)]
		public class InNewWindowCollection : ControlsHandlerTestBase
		{

3) use entry.GetBoundingBox to validate that the location of the entry hasn't shifted

2023-03-27 21:40 UTC, PureWeen requested changes

2023-03-27 21:40 UTC, PureWeen commented on src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
> +						_ = uIWindow.RootViewController.PresentViewControllerAsync(alert, true);
I don't think we want to ignore past these Async calls. 

My thoughts for this test
1) await these calls
2) make this test part of a Collection. You can see where this is done a few places with an inner class

[Category(TestCategory.Accessibility)]
		[Collection(ControlsHandlerTestBase.RunInNewWindowCollection)]
		public class InNewWindowCollection : ControlsHandlerTestBase
		{

3) use entry.GetBoundingBox to validate that the location of the entry hasn't shifted

2023-03-30 16:30 UTC, PureWeen requested changes

2023-03-30 16:30 UTC, PureWeen commented on src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
> +						var initialEntryBox = entryBoxFunc.Invoke();
Remove invoke calls

2023-03-30 23:38 UTC, PureWeen approved these changes

2023-03-31 02:25 UTC, merged