[ios] cleanup Loaded/Unloaded observers
dotnet/maui pull request #14140
Opened 2023-03-22 17:48 UTC by jonathanpeppers

Watching console output while navigating pages on iOS shows:

    2023-03-22 11:34:15.865716-0500 Warning: observer object was not disposed manually with Dispose()
    2023-03-22 11:34:15.866240-0500 Warning: observer object was not disposed manually with Dispose()

Reviewing the code:

    uiView.Layer.RemoveObserver(observer.Value, observer.Key);
    observers.Remove(observer.Key);

It actually does not call `observer.Value.Dispose()`, and we should be able to simply dispose instead of `RemoveObserver()`.

I think we can simplify this code in general:

* Store a `List<IDiposable>`, we don't need a dictionary.

* Call `Dispose()` instead of `RemoveObserver()`

* We know the capacity is 2, pass that in.

This does not solve any memory issues, but at least prevents the warning.

It may also improve performance a bit.

2023-03-22 17:52 UTC, rolfbjarne approved these changes, later dismissed

2023-03-22 17:52 UTC, rolfbjarne commented on src/Core/src/Platform/iOS/ViewExtensions.cs
> +					observer.Dispose();
Yes, that's correct.

2023-03-22 20:12 UTC, jonathanpeppers commented
It appears if you make this change, and run the full MAUI device tests suite, it crashes with:
```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10be6a7c4 - /Users/jopepper/Library/Developer/CoreSimulator/Devices/423F3267-C88A-4296-8573-E0332C10EC91/data/Containers/Bundle/Application/9392E3FD-EBBA-433F-9243-6DB69B08B7E4/Microsoft.Maui.Controls.DeviceTests.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10be0eade - /Users/jopepper/Library/Developer/CoreSimulator/Devices/423F3267-C88A-4296-8573-E0332C10EC91/data/Containers/Bundle/Application/9392E3FD-EBBA-433F-9243-6DB69B08B7E4/Microsoft.Maui.Controls.DeviceTests.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10bd656cf - /Users/jopepper/Library/Developer/CoreSimulator/Devices/423F3267-C88A-4296-8573-E0332C10EC91/data/Containers/Bundle/Application/9392E3FD-EBBA-433F-9243-6DB69B08B7E4/Microsoft.Maui.Controls.DeviceTests.app/libmonosgen-2.0.dylib : mono_sigsegv_signal_handler_debug
	0x120c30dfd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x15f2756b8 - /Applications/Xcode_14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ProxCardKit.framework/ProxCardKit : 

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x11f233a9a):0x11f233a8a  f6 74 6c 48 89 fb 48 b8 f8 ff ff ff ff 7f 00 00  .tlH..H.........
0x11f233a9a  48 8b 4f 20 48 21 c1 8b 09 f6 c1 01 75 09 48 8b  H.O H!......u.H.
0x11f233aaa  0b 48 23 41 20 8b 08 0f ba e1 1d 73 24 48 89 df  .H#A ......s$H..
0x11f233aba  4c 89 f6 31 d2 e8 6c cc ff ff 48 85 c0 74 12 48  L..1..l...H..t.H

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSendSuper_CGRect <0x0009e>
	  at UIKit.UIView:set_Frame <0x00090>
	  at Microsoft.Maui.Platform.ContainerViewController:ViewDidLayoutSubviews <0x000a0>
	  at System.Object:runtime_invoke_direct_void__this__ <0x00120>
	  at <unknown> <0x00000>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x001c6>
	  at UIKit.UIApplication:UIApplicationMain <0x0002e>
	  at UIKit.UIApplication:Main <0x0011c>
	  at Microsoft.Maui.DeviceTests.Program:Main <0x0006e>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00108>
	  at <unknown> <0x00000>
=================================================================

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

An error has occurred in the native fault reporting. Some diagnostic information will be unavailable.

=================================================================
	Native stacktrace:
=================================================================
	0x10be6a7c4 - /Users/jopepper/Library/Developer/CoreSimulator/Devices/423F3267-C88A-4296-8573-E0332C10EC91/data/Containers/Bundle/Application/9392E3FD-EBBA-433F-9243-6DB69B08B7E4/Microsoft.Maui.Controls.DeviceTests.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10be0eade - /Users/jopepper/Library/Developer/CoreSimulator/Devices/423F3267-C88A-4296-8573-E0332C10EC91/data/Containers/Bundle/Application/9392E3FD-EBBA-433F-9243-6DB69B08B7E4/Microsoft.Maui.Controls.DeviceTests.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10bd656cf - /Users/jopepper/Library/Developer/CoreSimulator/Devices/423F3267-C88A-4296-8573-E0332C10EC91/data/Containers/Bundle/Application/9392E3FD-EBBA-433F-9243-6DB69B08B7E4/Microsoft.Maui.Controls.DeviceTests.app/libmonosgen-2.0.dylib : mono_sigsegv_signal_handler_debug
	0x120c30dfd - /usr/lib/system/libsystem_platform.dylib : _sigtramp

Exiting early due to double fault.
```

2023-03-22 22:24 UTC, PureWeen requested changes
https://github.com/dotnet/maui/pull/14140#issuecomment-1480201283

2023-03-23 02:36 UTC, jonathanpeppers commented
Wait @PureWeen how is this green? When I got the error above I was running the device tests in Debug mode in the simulator.

2023-03-28 22:51 UTC, PureWeen commented
> Wait @PureWeen how is this green? When I got the error above I was running the device tests in Debug mode in the simulator.

Yea, that's the same thing I've hit before too unfortunately which is why I've never quite taken the plunge calling dispose. We could probably add some awaits or things around the tests to get rid of the crash but it's one of those things I'm a bit curious about the root cause just in case there is something more sinister here going on.

2023-04-26 22:00 UTC, jonathanpeppers commented on src/Core/src/Platform/iOS/ContainerViewController.cs
> +			currentPlatformView.Frame = View.Bounds;
This fixes the above crash when running these tests in Debug mode on a simulator ^^

But now a new one:

```
Unhandled Exception:
  ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: <__MonoMac_NSAsyncActionDispatcher: 0x60000228b560>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
  Key path: bounds
  Observed object: <CALayer: 0x60000228b0e0>
  Change: {
      kind = 1;
      new = "NSRect: {{0, 0}, {1024, 1366}}";
      old = "NSRect: {{0, 0}, {0, 0}}";
  }
  Context: 0x60000228b560
  Native stack trace:
  	0   CoreFoundation                      0x000000010c6288ab __exceptionPreprocess + 242
  	1   libobjc.A.dylib                     0x000000011daacba3 objc_exception_throw + 48
  	2   Foundation                          0x0000000113eb39b9 -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:] + 0
  	3   Foundation                          0x0000000113eb3e93 NSKeyValueNotifyObserver + 304
  	4   Foundation                          0x0000000113eb76f0 NSKeyValueDidChange + 462
  	5   Foundation                          0x0000000113eb338c NSKeyValueDidChangeWithPerThreadPendingNotifications + 146
  	6   QuartzCore                          0x00000001176f697d _ZN2CA5Layer10end_changeEPNS_11TransactionEjP11objc_objectS4_ + 53
  	7   QuartzCore                          0x00000001176ecaf3 -[CALayer setBounds:] + 511
  	8   QuartzCore                          0x00000001176ed885 -[CALayer setFrame:] + 595
  	9   UIKitCore                           0x0000000128d96b50 -[UIView _backing_setFrame:] + 83
  	10  UIKitCore                           0x00000001299a9cb3 -[UIView(Geometry) setFrame:] + 356
  	11  libxamarin-dotnet-debug.dylib       0x0000000109f1149c xamarin_dyn_objc_msgSendSuper + 220
  	12  ???                                 0x000000015c83eca7 0x0 + 5847116967
  	13  libmonosgen-2.0.dylib               0x000000010a6d842a ves_pinvoke_method + 474
  	14  libmonosgen-2.0.dylib               0x000000010a6ca6a5 interp_exec_method + 3717
  	15  libmonosgen-2.0.dylib               0x000000010a6c7e53 interp_runtime_invoke + 259
  	16  libmonosgen-2.0.dylib               0x000000010a4ee89d mono_runtime_try_invoke + 157
  	17  libmonosgen-2.0.dylib               0x000000010a4f0a2f mono_runtime_invoke + 95
  	18  libxamarin-dotnet-debug.dylib       0x0000000109f086b0 xamarin_invoke_trampoline + 6320
  	19  libxamarin-dotnet-debug.dylib       0x0000000109f10019 xamarin_arch_trampoline + 105
  	20  libxamarin-dotnet-debug.dylib       0x0000000109f111fe xamarin_x86_64_common_trampoline + 118
  	21  UIKitCore                           0x00000001299c87b3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2837
  	22  QuartzCore                          0x00000001176fb02c _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 526
  	23  QuartzCore                          0x00000001177065b9 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
  	24  QuartzCore                          0x0000000117617b0c _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 626
  	25  QuartzCore                          0x000000011764f69b _ZN2CA11Transaction6commitEv + 735
  	26  UIKitCore                           0x00000001293ca35b _afterCACommitHandler + 105
  	27  CoreFoundation                      0x000000010c587055 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
  	28  CoreFoundation                      0x000000010c5819c2 __CFRunLoopDoObservers + 515
  	29  CoreFoundation                      0x000000010c581f0d __CFRunLoopRun + 1161
  	30  CoreFoundation                      0x000000010c5816a7 CFRunLoopRunSpecific + 560
  	31  GraphicsServices                    0x00000001217e928a GSEventRunModal + 139
  	32  UIKitCore                           0x0000000129395ad3 -[UIApplication _run] + 994
  	33  UIKitCore                           0x000000012939a9ef UIApplicationMain + 123
  	34  libxamarin-dotnet-debug.dylib       0x0000000109ecba5a xamarin_UIApplicationMain + 58
  	35  libmonosgen-2.0.dylib               0x000000010a6d95f9 do_icall + 345
  	36  libmonosgen-2.0.dylib               0x000000010a6d8103 do_icall_wrapper + 291
  	37  libmonosgen-2.0.dylib               0x000000010a6ca4ff interp_exec_method + 3295
  	38  libmonosgen-2.0.dylib               0x000000010a6c7e53 interp_runtime_invoke + 259
  	39  libmonosgen-2.0.dylib               0x000000010a4ecde8 mono_runtime_invoke_checked + 136
  	40  libmonosgen-2.0.dylib               0x000000010a4f4dfc do_exec_main_checked + 92
  	41  libmonosgen-2.0.dylib               0x000000010a623e42 mono_jit_exec + 354
  	42  libxamarin-dotnet-debug.dylib       0x0000000109f0fe77 xamarin_main + 1927
  	43  Microsoft.Maui.Controls.DeviceTests 0x0000000100f50e14 main + 68
  	44  dyld                                0x0000000109ba92bf start_sim + 10
  	45  ???                                 0x00000002016aa52e 0x0 + 8613700910
  	46  ???                                 0x0000000000000003 0x0 + 3
  
     at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
     at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
     at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
     at Microsoft.Maui.DeviceTests.Program.Main(String[] args) in /Users/jopepper/src/maui/src/Controls/tests/DeviceTests/Microsoft.Maui.TestUtils.DeviceTests.Runners.SourceGen/Microsoft.Maui.TestUtils.DeviceTests.Runners.SourceGen.CodeBehindGenerator/TestRunner.iOS.sg.cs:line 18
  Native stack trace:
  	0   CoreFoundation                      0x000000010c6288ab __exceptionPreprocess + 242
  	1   libobjc.A.dylib                     0x000000011daacba3 objc_exception_throw + 48
  	2   Foundation                          0x0000000113eb39b9 -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:] + 0
  	3   Foundation                          0x0000000113eb3e93 NSKeyValueNotifyObserver + 304
  	4   Foundation                          0x0000000113eb76f0 NSKeyValueDidChange + 462
  	5   Foundation                          0x0000000113eb338c NSKeyValueDidChangeWithPerThreadPendingNotifications + 146
  	6   QuartzCore                          0x00000001176f697d _ZN2CA5Layer10end_changeEPNS_11TransactionEjP11objc_objectS4_ + 53
  	7   QuartzCore                          0x00000001176ecaf3 -[CALayer setBounds:] + 511
  	8   QuartzCore                          0x00000001176ed885 -[CALayer setFrame:] + 595
  	9   UIKitCore                           0x0000000128d96b50 -[UIView _backing_setFrame:] + 83
  	10  UIKitCore                           0x00000001299a9cb3 -[UIView(Geometry) setFrame:] + 356
  	11  libxamarin-dotnet-debug.dylib       0x0000000109f1149c xamarin_dyn_objc_msgSendSuper + 220
  	12  ???                                 0x000000015c83eca7 0x0 + 5847116967
  	13  libmonosgen-2.0.dylib               0x000000010a6d842a ves_pinvoke_method + 474
  	14  libmonosgen-2.0.dylib               0x000000010a6ca6a5 interp_exec_method + 3717
  	15  libmonosgen-2.0.dylib               0x000000010a6c7e53 interp_runtime_invoke + 259
  	16  libmonosgen-2.0.dylib               0x000000010a4ee89d mono_runtime_try_invoke + 157
  	17  libmonosgen-2.0.dylib               0x000000010a4f0a2f mono_runtime_invoke + 95
  	18  libxamarin-dotnet-debug.dylib       0x0000000109f086b0 xamarin_invoke_trampoline + 6320
  	19  libxamarin-dotnet-debug.dylib       0x0000000109f10019 xamarin_arch_trampoline + 105
  	20  libxamarin-dotnet-debug.dylib       0x0000000109f111fe xamarin_x86_64_common_trampoline + 118
  	21  UIKitCore                           0x00000001299c87b3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2837
  	22  QuartzCore                          0x00000001176fb02c _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 526
  	23  QuartzCore                          0x00000001177065b9 _ZN2CA5Layer [...]

2023-09-26 01:01 UTC, closed without merging