[iOS/Catalyst] Fix clipping issues with some views
dotnet/maui pull request #14362
Opened 2023-04-03 11:03 UTC by jsuarezruiz

### Description of Change

Fix clipping issues with some views on iOS.

<img width="551" alt="Captura de pantalla 2023-04-03 a las 13 01 14" src="https://user-images.githubusercontent.com/6755973/229491650-5ba6b106-c8a0-4041-886e-4ae61c4bd976.png">

### Issues Fixed

Fixes #14357

2023-04-03 11:04 UTC, jsuarezruiz commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			if (backgroundLayer is null)
This is the main change.

2023-04-03 15:56 UTC, mandel-macaque requested changes

2023-04-03 15:56 UTC, mandel-macaque commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			if (_borderView != null)
```suggestion
			if (_borderView is not null)
```

2023-04-03 15:56 UTC, mandel-macaque commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			if (BackgroundMaskLayer != null)
```suggestion
			if (BackgroundMaskLayer is not null)
```

2023-04-03 15:56 UTC, mandel-macaque commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			if (_borderView != null)
```suggestion
			if (_borderView is not null)
```

2023-04-04 15:00 UTC, jsuarezruiz commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			if (backgroundLayer is null)
We wrap some controls for certain visual effects like applying background gradient etc.
For this reason, we have to clip the background layer as well if it exists.

2023-04-04 21:26 UTC, mandel-macaque approved these changes

2023-04-10 09:58 UTC, rmarinho approved these changes

2023-04-10 09:58 UTC, merged