Handle Grid * expansion when size is larger than minimum, but less than sufficient to display full size
dotnet/maui pull request #14902
Opened 2023-05-03 02:47 UTC by hartez

### Description of Change

(This is an expansion of the fix in #14114, which handled part of this problem on Windows, but didn't successfully fix it on Android and iOS. It also caused havoc in several other layout situations.)

When a Grid with * rows/columns is measured, the measurement should return the minimal values for those rows/columns to contain their content. When the Grid is arranged, those *s should (in some situations) be expanded to fill in the extra space if the arranged size is larger than the measured size. 

However - that expansion _should not_ automatically be to the full potential size of the * rows/columns if the target size is not sufficient to contain it. Instead, the expansion should be distributed among the available space so that the smallest * rows/columns expand at the greatest rate until all rows/columns can be expanded to their full size. 

This PR handles that expansion properly, and also avoids the rounding errors described in #14694. This includes smoothly expanding as the window size is changed in environments (e.g., Desktop) where that's an issue.

In this PR:

- New tests to cover the various permutations of the situations described above
- Some cleanup and clarification of old tests
- Removal of vestigial methods in GridStructure
- A lot of method renaming in GridStructure to clarify what it's doing

### Issues Fixed

Fixes #14694

Probably several others, I'll check that in the morning.

2023-05-15 16:40 UTC, PureWeen requested changes
I think there's still an issue on iOS here

I've rebased on main and used the code you have here
https://github.com/dotnet/maui/issues/14694

<img width="488" alt="image" src="https://github.com/dotnet/maui/assets/5375137/b81b0803-97f0-438f-8cec-b5a105c49766">

2023-05-16 02:54 UTC, hartez commented
> I think there's still an issue on iOS here
> 
> I've rebased on main and used the code you have here #14694
> 
> <img alt="image" width="488" src="https://user-images.githubusercontent.com/5375137/238414201-b81b0803-97f0-438f-8cec-b5a105c49766.png">

Okay, should be fixed now. The changes were pointing up a long-standing problem with the ContentView/LayoutView backing controls, where they were measuring unnecessarily during LayoutSubviews.

2023-05-16 16:46 UTC, PureWeen approved these changes

2023-05-16 16:47 UTC, merged

2023-06-14 18:33 UTC, hartez commented
/backport to net7.0