Added a new GetContentTypeHashCode
dotnet/maui pull request #1498
Opened 2021-06-29 22:54 UTC by Clancey

Dropped net standard 2.0 support from the old libs.

GetContentTypeHashCode Is used so we can get the "Shape" of a Layout.
This can be used for things like Cell Re-use Identifiers. If an Item has the same GetContentTypeHashCode(), it uses the same exact controls/layout so can be re-used/recycled.

2021-07-01 04:36 UTC, mattleibow commented on src/Controls/src/Core/ContentPage.cs
> +			}
This should probably be set in the BindingProperty's onChanged delegate - otherwise this will not fire when set via XAML.

2021-07-01 04:36 UTC, mattleibow commented on src/Controls/src/Core/Layout.cs
> +			TypeHashCode = null;
These 2 should not be needed as any change to `InternalChildren` will fire InternalChildrenOnCollectionChanged.

2021-07-04 12:58 UTC, rmarinho commented
/azp run

2021-07-07 20:37 UTC, hartez commented on src/Controls/src/Core/Layout.cs
> +		int GetChidrensTypeHasCode()
GetChidrensTypeHasCode -> GetChidrensTypeHashCode

2021-07-07 20:46 UTC, hartez commented
> If an Item has the same GetContentTypeHashCode(), it uses the same exact controls/layout so can be re-used/recycled.

How does that work? Hash codes aren't unique, so there's no guarantee that two items with different children won't end up with the same hash code. We'd be re-using controls/layout that don't match.

2021-07-12 23:12 UTC, Clancey commented
> > If an Item has the same GetContentTypeHashCode(), it uses the same exact controls/layout so can be re-used/recycled.
> 
> How does that work? Hash codes aren't unique, so there's no guarantee that two items with different children won't end up with the same hash code. We'd be re-using controls/layout that don't match.

It really should be unique enough. It's what is used to handle Dictionaries in dotnet, and hash sets. So for Comet, I use it and have not had a collision. If it has one, it will be fine, for that collision, it will rebuild the UI stack. So less performance, but more performant than what we are doing now.

2021-07-15 17:25 UTC, hartez commented
> > > If an Item has the same GetContentTypeHashCode(), it uses the same exact controls/layout so can be re-used/recycled.
> > 
> > 
> > How does that work? Hash codes aren't unique, so there's no guarantee that two items with different children won't end up with the same hash code. We'd be re-using controls/layout that don't match.
> 
> It really should be unique enough. It's what is used to handle Dictionaries in dotnet, and hash sets. So for Comet, I use it and have not had a collision. If it has one, it will be fine, for that collision, it will rebuild the UI stack. So less performance, but more performant than what we are doing now.

So instead of: 

"If an Item has the same GetContentTypeHashCode(), it uses the same exact controls/layout so can be re-used/recycled."

you mean:

"If an Item has a different GetContentTypeHashCode(), it uses different controls/layout so it cannot be re-used. If an Item has the same GetContentTypeHashCode(), it _might_ use the same exact controls/layout; we can then verify that, and re-use it."

2021-07-22 21:49 UTC, Redth commented on src/Controls/src/Core/Layout.cs
> +		public override int GetContentTypeHashCode() => TypeHashCode ??= GetChidrensTypeHasCode();
```suggestion
		public override int GetContentTypeHashCode() => TypeHashCode ??= GetChidrensTypeHashCode();
```

2021-07-22 21:49 UTC, Redth commented on src/Controls/src/Core/Layout.cs
> +		int GetChidrensTypeHasCode()
```suggestion
		int GetChidrensTypeHashCode()
```

2021-07-22 21:55 UTC, mattleibow commented on src/Controls/src/Core/HandlerImpl/ContentPage.Impl.cs
> +		public override int GetContentTypeHashCode() => TypeHashCode ?? (this.GetType(), Content.GetContentTypeHashCode()).GetHashCode();
Should this be a `??=`? Are you wanting to set/cache the value from `GetHashCode()`

2021-07-22 21:57 UTC, mattleibow commented
Even though dictionaries use a hash code, there is also an equality check. This is why you have to override both GetHashCode and Equals. Will this cause issues?

2021-07-22 22:01 UTC, mattleibow commented
Is it possible to maybe use some unique ID? that a property change results in an increment or something? SkiaSharp has this type of concept where each object has an ID that jets updated for changes that affect certain things.

This feel hacky.

2021-07-22 22:13 UTC, mattleibow requested changes
I am not super happy with this as this feels like an implementation detail for one specific framework. We don't use it in Controls and adding it to the base interfaces means that _all_ implementers need to add it.

Since this is just added in Core on the interface, I think this is maybe better suited to an instance method on the base Comet view.

The idea is not inherently bad, but this is not a Core concept.

2021-09-22 13:13 UTC, Redth commented
Closing for now, let's keep this in mind in the future and possibly re-open/tweak it.

2021-09-22 13:13 UTC, closed without merging