[Android] Fix Border RoundRectangle Corner Radius issue
dotnet/maui pull request #14995
Opened 2023-05-09 12:32 UTC by jsuarezruiz

### Description of Change

Fix Border RoundRectangle Corner Radius issue on Android.

### Issues Fixed

Fixes #14936

2023-05-10 14:42 UTC, jsuarezruiz commented on src/Controls/src/Core/HandlerImpl/RoundRectangle.Impl.cs
> +			density = (float)DeviceDisplay.MainDisplayInfo.Density;
Reviewing why we need this changes and if have more sense to apply it at other level. We have not used density before.

2023-05-10 15:01 UTC, jsuarezruiz commented on src/Controls/src/Core/HandlerImpl/RoundRectangle.Impl.cs
> +			density = (float)DeviceDisplay.MainDisplayInfo.Density;
Maybe related to https://github.com/dotnet/maui/commit/982d809eb9567f75ea810a3d7aedb6aac8f8284c#diff-9962b2ab4d4a0eb4922307e668bfe7d868c4fac7919a9463a3cba1859a6de86fL417-L423

2023-07-25 14:27 UTC, Redth commented on src/Controls/src/Core/Shapes/RoundRectangle.cs
> +			density = (float)DeviceDisplay.MainDisplayInfo.Density;
```suggestion
			density = Handler?.MauiContext?.Context?.GetDisplayDensity()
	?? (float)DeviceDisplay.MainDisplayInfo.Density;
```

2023-07-25 14:28 UTC, Redth commented on src/Controls/src/Core/Shapes/RoundRectangle.cs
> +			density = (float)DeviceDisplay.MainDisplayInfo.Density;
```suggestion
			density = Handler?.MauiContext?.Context?.GetDisplayDensity()
	?? (float)DeviceDisplay.MainDisplayInfo.Density;
```

2023-08-15 01:10 UTC, jstedfast commented on src/TestUtils/src/DeviceTests/AssertionExtensions.Windows.cs
> +			var bitmap = await view.ToBitmap(mauiContext);
yes, it is intentionally like all of the other helper methods that do the same.

2023-08-16 14:53 UTC, jstedfast commented
At this point I just need to adjust the Points in the DeviceTests to work for iOS.

2023-08-16 19:21 UTC, jstedfast commented
Looks like the iOS Border tests are passing now, but oddly it's getting other errors.

2023-08-18 15:59 UTC, jstedfast commented
Seems like random tests are failing

2023-08-18 20:35 UTC, jstedfast approved these changes, later dismissed

2023-08-18 22:23 UTC, PureWeen requested changes, later dismissed
Not sure if this is related to this PR but I noticed in android the border sizing doesn't seem correct. 

I merged in your iOS border samples and notice that android has an odd black border between the red and blue. 

![image](https://github.com/dotnet/maui/assets/5375137/c18fb1bc-6803-42d5-aa53-438e833a8d83)

2023-08-29 15:18 UTC, jstedfast approved these changes

2023-08-29 17:48 UTC, jstedfast commented
I'm beginning to wonder if the density calculation is wrong. It seems like MauiDrawable.Android.cs should pass in `_strokeThickness / _density` instead of `_strokeThickness` because `strokeThickness` has already been multiplied by `_density` but all of the path calculations assume "Maui coordinates" instead of "Android coordinates".

2023-08-29 22:38 UTC, jstedfast commented
Replace by https://github.com/dotnet/maui/pull/17087

2023-08-29 22:38 UTC, closed without merging