[net7.0] [Windows] Fix CollectionView.RemainingItemsThresholdReached
dotnet/maui pull request #15417
Opened 2023-06-02 17:21 UTC by hartez

Backport of #14391 to net7.0

/cc @hartez @Foda

2023-06-05 06:56 UTC, jsuarezruiz commented
/azp run

2023-06-05 16:10 UTC, rmarinho requested changes
```
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(94,13): error CS0246: The type or namespace name 'WSetter' could not be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(94,6): error CS1061: 'SetterBaseCollection' does not contain a definition for 'OfType' and no accessible extension method 'OfType' accepting a first argument of type 'SetterBaseCollection' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(97,4): error CS0103: The name 'Assert' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(133,5): error CS0103: The name 'Assert' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(94,13): error CS0246: The type or namespace name 'WSetter' could not be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(94,6): error CS1061: 'SetterBaseCollection' does not contain a definition for 'OfType' and no accessible extension method 'OfType' accepting a first argument of type 'SetterBaseCollection' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(97,4): error CS0103: The name 'Assert' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.Windows.cs(133,5): error CS0103: The name 'Assert' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net7.0-windows10.0.20348]
  ```

2023-06-09 13:34 UTC, jfversluis approved these changes

2023-06-09 14:38 UTC, PureWeen requested changes

2023-06-09 16:00 UTC, closed without merging

2023-06-13 20:49 UTC, Foda commented on src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
> +		public async Task ValidateItemContainerDefaultHeight()
`ValidateItemContainerDefaultHeight` wasn't part of my PR -- was this added by accident?

2023-06-13 20:49 UTC, Foda commented
> Closing this, the original PR on main doesn't work either. No point in backporting this one, we can look at backporting again once it works on main.

@hartez @PureWeen Why on earth do our tests not report failures???
https://github.com/dotnet/maui/pull/14391/checks?check_run_id=13245158008