[Android] Allow full screen videos from WebView
dotnet/maui pull request #15472
Opened 2023-06-06 12:15 UTC by jsuarezruiz

### Description of Change

Allow full screen videos from WebView.

![image](https://github.com/dotnet/maui/assets/6755973/79538e70-eed7-4277-b825-a1e2f25aa193)

To validate the changes can use the new added sample to the WebView galleries in the .NET MAUI Gallery App.

### Issues Fixed

Fixes #8030
Fixes #7720

2023-06-06 14:45 UTC, vhugogarcia commented
Hello @jsuarezruiz,

Thanks for adding this new feature to .NET MAUI Webviews on Android. I would like to share some ideas here.

On this method, we need to return to the original orientation of the device. However, there are some points we need to cover and validate:

- Phone in portrait-mode, enters full screen it goes in landscape-mode, then when returning from full screen the device orientation must change to portrait-mode again.
- it may happen that the app is compatible with Tablet/Phone in landscape-only. So, if the video goes full screen when returned it must not change to portrait-mode because the app only supports landscape-mode.

How this can be solved? well, if it is possible to know the orientation supported by the app then we can just add a validation for it, otherwise, we need to think how to validate that for the second scenario.

2023-06-06 14:49 UTC, vhugogarcia commented
Also, we need to validate which is the status of the current SystemBars settings are on the app, because for example, I may have an application that only shows the StatusBar and not the navigation bar, so by doing this, we are showing status and navigation bar which may not be the expected result.

`context.Window.InsetsController?.Show(WindowInsets.Type.SystemBars());`

So, we may need to validate if the user has StatusBarVisible and NavigationBar visible before enter full screen save it on a variable or somewhere, and then when returning we show only what was visible. :) 

What do you think @jsuarezruiz ?

2023-06-07 06:59 UTC, jsuarezruiz commented
> Also, we need to validate which is the status of the current SystemBars settings are on the app, because for example, I may have an application that only shows the StatusBar and not the navigation bar, so by doing this, we are showing status and navigation bar which may not be the expected result.
> 
> `context.Window.InsetsController?.Show(WindowInsets.Type.SystemBars());`
> 
> So, we may need to validate if the user has StatusBarVisible and NavigationBar visible before enter full screen save it on a variable or somewhere, and then when returning we show only what was visible. :)
> 
> What do you think @jsuarezruiz ?

Good point. Agree. I will review it shortly. Thanks for all the feedback.

2023-10-18 11:59 UTC, vhugogarcia commented
Hello @jsuarezruiz , is this going to be available in .NET MAUI 8 GA? 🙂👍🏻

2024-01-18 12:45 UTC, jsuarezruiz commented
@jfversluis, @tj-devel709 Added you as reviewers. Could you take a look when you can? Thanks.
​

2024-01-24 10:27 UTC, jfversluis approved these changes, later dismissed

2024-03-20 14:13 UTC, rmarinho commented
@jsuarezruiz can you retarget net9.0 ?

2024-04-25 11:20 UTC, jfversluis requested changes
As per https://github.com/dotnet/maui/issues/22049 can we make sure to include `BlazorWebView` in this as well?

2024-09-10 11:23 UTC, axylophon commented
Yes it should also be fixed when using Maui Blazor Hybrid.
Currently fullscreen is not working.

2024-11-26 15:53 UTC, retepz commented
So this didn't make the .NET 9 cutoff?

2024-12-20 14:34 UTC, jfversluis requested changes
> D:\a\_work\1\s\src\Core\src\Platform\Android\MauiWebChromeClient.cs(147,5): error CA1422: This call site is reachable on: 'Android' 21.0 and later. 'Window.SetDecorFitsSystemWindows(bool)' is obsoleted on: 'android' 35.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-android35.0]
D:\a\_work\1\s\src\Core\src\Platform\Android\MauiWebChromeClient.cs(108,5): error CA1422: This call site is reachable on: 'Android' 21.0 and later. 'Window.SetDecorFitsSystemWindows(bool)' is obsoleted on: 'android' 35.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-android35.0]

2025-01-10 22:38 UTC, vikher commented
If you're looking to implement full-screen functionality for Android WebView video playback, you can use the following workaround. This approach involves creating a custom handler that extends MauiWebChromeClient to support full-screen video features.

Steps to Implement:
Create a custom WebPlayerChromeClient:

```
using Android.App;
using Android.Content.Res;
using Android.OS;
using Android.Views;
using Android.Widget;
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Platform;

namespace Mobile.Handlers
{
    public class WebPlayerChromeClient : MauiWebChromeClient
    {
        private readonly Activity context;
        private int originalUiOptions;
        private Android.Views.View customView;
        private ICustomViewCallback videoViewCallback;
        private bool disposed = false; // To detect redundant calls

        public WebPlayerChromeClient(IWebViewHandler handler) : base(handler)
        {
            this.context = Microsoft.Maui.ApplicationModel.Platform.CurrentActivity;
        }

        public override void OnHideCustomView()
        {
            if (context != null)
            {
                if (context.Window.DecorView is FrameLayout layout)
                    layout.RemoveView(customView);
                
                if (!IsTablet(context))
                    context.RequestedOrientation = Android.Content.PM.ScreenOrientation.Portrait;

                if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.R)
                {
                    context.Window.SetDecorFitsSystemWindows(true);
                    context.Window.InsetsController?.Show(WindowInsets.Type.SystemBars());
                }
                else
                {
                   context.Window.DecorView.SystemUiVisibility = (StatusBarVisibility)originalUiOptions;
                }

                videoViewCallback.OnCustomViewHidden();
                customView?.Dispose(); // Dispose the custom view if it implements IDisposable
                customView = null;
                videoViewCallback = null;
            }
        }

        public override void OnShowCustomView(Android.Views.View view, ICustomViewCallback callback)
        {
            if (customView != null)
            {
                OnHideCustomView();
                return;
            }

            if (context == null)
                return;

            videoViewCallback = callback;
            customView = view;
            customView.SetBackgroundColor(Android.Graphics.Color.White);
            context.RequestedOrientation = Android.Content.PM.ScreenOrientation.Landscape;

            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.R)
            {
                context.Window.SetDecorFitsSystemWindows(false);
                context.Window.InsetsController?.Hide(WindowInsets.Type.SystemBars());
            }
            else
            {
                originalUiOptions = (int)context.Window.DecorView.SystemUiVisibility;
                var newUiOptions = originalUiOptions | (int)SystemUiFlags.LayoutStable | (int)SystemUiFlags.LayoutHideNavigation | (int)SystemUiFlags.LayoutHideNavigation |
                                (int)SystemUiFlags.LayoutFullscreen | (int)SystemUiFlags.HideNavigation | (int)SystemUiFlags.Fullscreen | (int)SystemUiFlags.Immersive;

                context.Window.DecorView.SystemUiVisibility = (StatusBarVisibility)newUiOptions;
            }

            if (context.Window.DecorView is FrameLayout layout)
                layout.AddView(customView, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MatchParent, ViewGroup.LayoutParams.MatchParent));
        }

        private bool IsTablet(Activity context)
        {
            return (context.Resources.Configuration.ScreenLayout & ScreenLayout.SizeMask) >= ScreenLayout.SizeLarge;
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this); // Prevent finalization if already disposed
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposed)
                return;

            if (disposing)
            {
                // Dispose managed resources
                customView?.Dispose();
                // Dispose videoViewCallback if it implements IDisposable
                if (videoViewCallback is IDisposable disposableCallback)
                {
                    disposableCallback.Dispose();
                }
            }

            // Free unmanaged resources here, if any

            disposed = true;
        }

        // Destructor (finalizer) if you use unmanaged resources
        ~WebPlayerChromeClient()
        {
            Dispose(false);
        }

    }
}

```

Add a handler to enable video features:

```
using System.Runtime.Versioning;

namespace Mobile.Handlers
{
    public class WebViewVideoHandler
    {
        [SupportedOSPlatform("android26.0")]
        public static void EnableVideoFeatures()
        {
#if ANDROID
            Microsoft.Maui.Handlers.WebViewHandler.Mapper.ModifyMapping(
                nameof(Android.Webkit.WebView.WebChromeClient),
                (handler, view, args) =>
                {
                    if (Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
                    {
                        handler.PlatformView.SetWebChromeClient(new WebPlayerChromeClient(handler));
                    }
                });
#endif
        }
    }
}

```

Register the handler in MauiProgram.cs:
Add the following line to your CreateMauiApp method:

`WebViewVideoHandler.EnableVideoFeatures();
`


This code sets up the necessary functionality to manage full-screen video playback by handling OnShowCustomView and OnHideCustomView. It also ensures compatibility with both tablets and phones, supporting immersive mode on Android devices.

2025-01-20 13:40 UTC, jsuarezruiz commented
This PR is from... 2023! It requires changes from the original implementation due to using deprecated APIs. I just rebased, but it would require a change in implementation. I'm moving it to Draft until I have the changes.

2025-03-17 14:13 UTC, jsuarezruiz commented on src/Controls/samples/Controls.Sample/Pages/Controls/WebViewGalleries/WebViewFullScreenVideoGallery.xaml.cs
> +				Html = "<html><iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/YE7VzlLtp-4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-wr
Yeah, updated. Now should be better.

2025-03-17 14:13 UTC, jsuarezruiz commented
Updated implementation without use obsolete APIs.

2025-03-19 11:45 UTC, jsuarezruiz commented on src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
> +override Microsoft.Maui.Platform.MauiWebChromeClient.OnHideCustomView() -> void
Need to retarget to net10.0 @PureWeen?

2025-03-25 12:25 UTC, jfversluis approved these changes

2025-03-25 16:52 UTC, rmarinho approved these changes

2025-03-26 13:01 UTC, merged