Restore & obsolete Windows MauiWebView ctor
dotnet/maui pull request #15541
Opened 2023-06-09 08:22 UTC by jfversluis

### Description of Change

Restores the original constructor for the Windows MauiWebView to prevent an ABI break. Added the obsolete attribute to direct people to the overloaded version.

### Issues Fixed

NA

2023-06-09 09:51 UTC, jsuarezruiz approved these changes

2023-06-09 14:09 UTC, PureWeen requested changes
Can we maintain some of the old behavior pre-adding the new ctor? Still run all the code from the other ctor sans the handler part?

2023-06-12 08:36 UTC, jfversluis commented
> Can we maintain some of the old behavior pre-adding the new ctor? Still run all the code from the other ctor sans the handler part?

Reinstated the existing functionality, wrapped it in a method so we don't duplicate code. Additionally I added a null-check for the handler that was added so that doesn't throw any NREs.

Technically when you're using the old ctor you will end up in the current scenario where everything works as before, and the cookies are broken. Switching to the new ctor will fix that for people.

2023-06-12 14:58 UTC, PureWeen approved these changes

2023-06-12 14:58 UTC, merged