Fix DataTrigger behavior that can cause some strange inconsistencies
dotnet/maui pull request #15655
Opened 2023-06-14 20:19 UTC by widavies

I'd recommend reading #10189 first, the writeup is very clear and helpful for understanding this problem.

The problem here is simple, but the possible solutions to it are rather complicated depending on the expected behavior we're looking for.

### The problem
Multiple `DataTriggers` with identical `Binding` values causes inconsistent behavior.

Each `DataTrigger` is backed by a `TriggerBase`. This class gets notified whenever the associated trigger condition changes. It manages a `Setter` for the target property and will either [`Apply()` or `UnApply()`](https://github.com/dotnet/maui/blob/9b091fd530cf54bb8c756474fc7585ec125a9b66/src/Controls/src/Core/Interactivity/TriggerBase.cs#LL100C5-L100C6) the setter depending on the evaluation of the condition. Note that `UnApply()` will restore a property to its default value.

The problem is that `DataTriggers` are not ordered in any particular way. Assume that we have two `DataTriggers`'s with the same `Binding` value. Let's say the `Binding` value changes, and one `DataTrigger` now evaluates to `true` and the other to `false`. Because their is no enforced execution order, the `DataTrigger` that evaluates to `true` may run first. If both `DataTrigger`'s target the same property, the first data trigger will `Apply()` its `Setter`, updating the value correctly but the second trigger will run its `UnApply()` which resets the target property to its default value.

### Possible solutions
The way I see it, there are several possible solutions:

1) Create an ordered event delivery system for `DataTriggers`s. The condition of each `DataTrigger` is first evaluated. All the `DataTriggers` whose conditions are false are executed first. This isn't perfect though - these `DataTriggers` will set their target properties back to their default value and then back again to a new value when the second `true` group of `DataTriggers` run. This could maybe cause the property to flicker, although I'm not entirely sure if all `OnPropertyChanged()` events are marshalled before a UI refresh event so maybe it'd be fine.
2) During XAML parsing detect if the several `DataTriggers` are logical opposites (or mutually exclusive), if we can guarantee that one `DataTrigger` is _always_ active, no more, no less, than we could disable the `UnApply()` setters on all the triggers.
3) I think this is the easiest, but in my mind a trigger is really a casual thing - "When X becomes true, do Y". It doesn't really make sense to me that "when X becomes false, set Y to default". The pull request I attached makes this change. That way the `DataTrigger` does not bother resetting the target property back to its default. This is _a_ solution, but not sure if it potentially breaks something else or if its desired. I can certainly update this PR to solution 1 or 2 however it starts to add a lot of interdependency between components when it would be a lot cleaner design-wise to have them separated. 

### Description of Change

When the condition tracked by a `DataTrigger` becomes false, do not reset target property to default settings.

### Issues Fixed 

Fixes #10189

2023-06-14 21:08 UTC, widavies commented
Linking https://github.com/xamarin/Xamarin.Forms/issues/13571 & https://github.com/xamarin/Xamarin.Forms/issues/13369
as they may be fixed by this as well.

2023-07-19 11:31 UTC, jsuarezruiz commented
/azp run

2024-02-06 09:22 UTC, StephaneDelcroix commented
Were you abler to retest this after the changes induced by SetterSpecificity ?

2024-02-06 09:55 UTC, StephaneDelcroix requested changes
merging this code will likely revert some other behaviours that we might want. In order to consider this, could you 1/write a unit test, 2/rebase on top of recent main (that contains changes that might already fix this) ?

2025-09-09 12:49 UTC, jfversluis commented
This PR seems stale and no response from the original author, its unlikely that we're moving this forward in the current state, so closing this for now. If someone still things this is something we need and/or wants to look into this, please let us know :)

Thanks!

2025-09-09 12:49 UTC, closed without merging