IsNullOrEmpty for Paint not returning true if Color(s) are not set
dotnet/maui pull request #15668
Opened 2023-06-15 07:12 UTC by mos379

### Description of Change

Adding additional condition for IsNullOrEmpty check

### Issues Fixed

Fixes #15667

2023-06-15 15:45 UTC, jsuarezruiz commented on src/Controls/tests/Core.UnitTests/LinearGradientBrushTests.cs
> +			LinearGradientBrush noColorLinearGradientBrush = new LinearGradientBrush
Updated unit test

2023-06-21 10:10 UTC, rmarinho commented
/azp run

2023-06-28 13:41 UTC, PureWeen commented
/azp run

2023-07-05 14:13 UTC, jsuarezruiz approved these changes, later dismissed

2023-07-05 19:30 UTC, mattleibow requested changes
This PR is on the right track, but after my first comment about adding a test, I think we may also actually want to rather make null become white instead. So a "blank" gradient is the same as 2 white stops?

What happens if one of the stops is null - such that start and end are not null, but there is one in the middle that is null. 

@jsuarezruiz thoughts?

2023-07-06 11:21 UTC, jsuarezruiz commented on src/Core/tests/UnitTests/PaintTests.cs
> +		public void TestNullOrEmptyLinearGradientPaint()
Added this one https://github.com/dotnet/maui/blob/43b757d401aedc30b131ae53cdd4cf57e2e4ed56/src/Controls/tests/Core.UnitTests/LinearGradientBrushTests.cs#L78

2023-07-06 11:26 UTC, jsuarezruiz commented on src/Core/src/Graphics/PaintExtensions.cs
> +				return gradientPaint == null || gradientPaint.GradientStops.Length == 0 || gradientPaint.StartColor == null || gradientPaint.EndColor == null;
Mnn, could be an option. i changed this validation for now to check if the gradient StartColor and EndColor is null. In that case, without start and end colors, we can consider the gradient empty.

2023-07-06 23:18 UTC, mattleibow commented on src/Controls/tests/Core.UnitTests/LinearGradientBrushTests.cs
> +					new GradientStop()
What happens when one is null and the other is a color?

What happens if there is a null stop in the middle?

2023-09-04 20:24 UTC, mattleibow commented
/azp run

2023-09-05 05:12 UTC, mos379 commented on src/Core/src/Graphics/PaintExtensions.cs
> +				return gradientPaint == null || gradientPaint.GradientStops.Length == 0 || gradientPaint.StartColor == null || gradientPaint.EndColor == null;
@mattleibow how much longer do we have to wait for this tiny fix?

2023-09-27 07:59 UTC, mos379 commented
@samhouts this is still the case crashing my application
easy to reproduce 
```
    <Style
        x:Key="TestBackground"
        ApplyToDerivedTypes="True"
        TargetType="{x:Type ContentPage}">
        <Setter Property="Background">
            <Setter.Value>
                <LinearGradientBrush EndPoint="0,1">
                    <GradientStop Offset="0.1" />
                    <GradientStop Offset="1" Color="Red" />
                </LinearGradientBrush>
            </Setter.Value>
        </Setter>
    </Style>
```
crashes 
while adding a color to the first gradient works

tested with 8.0.100-rc.1.23455.8

2023-09-27 08:06 UTC, mos379 commented on src/Core/src/Graphics/PaintExtensions.cs
> +				return gradientPaint is null || gradientPaint.GradientStops.Length == 0 || (gradientPaint.StartColor is null && gradientPaint.EndColor is null);
@jsuarezruiz this additional bracket does not solve the issue when only one color does not exist/work

2023-10-12 16:41 UTC, samhouts commented
/azp run

2024-03-30 10:43 UTC, jfversluis commented
/rebase

2024-06-12 15:25 UTC, jsuarezruiz commented
/rebase

2024-06-12 15:27 UTC, jsuarezruiz commented
/azp run

2025-02-19 10:18 UTC, jfversluis commented
/rebase

2025-03-03 18:49 UTC, mattleibow approved these changes

2025-03-03 18:49 UTC, merged

2025-03-04 09:27 UTC, mos379 commented
WOW after almost 2 years :)