[essentials] ensure WebUtils.ParseQueryString captures fragment parameters
dotnet/maui pull request #15662
Opened 2023-06-15 03:29 UTC by rdavisau

### Description of Change

Makes `WebUtils.ParseQueryString` extract parameters from both `Uri.Query` and `Uri.Fragment`, resolving a regression from net8p4 to net8p5.

### Issues Fixed

Fixes #15661

2023-06-15 03:29 UTC, rdavisau commented
@dotnet-policy-service agree

2023-06-26 09:49 UTC, jfversluis commented
/azp run

2023-06-26 14:37 UTC, jstedfast commented
My understanding is that query parameters MUST come before the URI fragment (which can only be terminated by the end of the URI).

https://www.rfc-editor.org/rfc/rfc3986#section-3.5

Can you show me where my interpretation is wrong?

There's also this syntax: `URI           = scheme ":" hier-part [ "?" query ] [ "#" fragment ]` which, again, indicates that the fragment is always last.

2023-06-26 14:42 UTC, jstedfast requested changes
Before this gets merged, lets make sure that it is valid to have a query string located within the fragment of a URI. I don't believe that it is valid.

2023-06-27 01:21 UTC, rdavisau commented
Maybe the confusion comes from the name of the method `WebUtils.ParseQueryString`?

Originally, (despite the name) it had the behaviour of "extract all parameters from the url" and handled parameters whether they were in query string and/or fragment. That's covered by tests for the class and is also mentioned as the expected behaviour [here](https://github.com/dotnet/maui/blob/517da936a085156563d392cb9dab94ed8a240a5f/src/Essentials/src/WebAuthenticator/WebAuthenticatorResult.shared.cs#L34). [The perf change](https://github.com/dotnet/maui/commit/edeae340ab9ee9d8a8a5f5fc3dfb4a0f17729ff3#diff-686959c852a62a0b284d6cf92e5b61a6871108fbfc177d8ef9be7ccc94fbc2dfR18) made `ParseQueryString` only extract from the query string, which is consistent with the name of the method, but fails the fragment test and breaks existing users of `WebAuthenticator` that rely on it handling parameters contained in a fragment of the auth response. This PR aims to undo that regression specifically. The `ParseQueryString` method is not part of the public API so I think it could be ok to rename.

2023-06-27 15:47 UTC, jstedfast commented
Well, based on the comment that specifically states that it is meant to parse the fragment as if it contained query parameters, then I guess the correct solution here is to parse both sets as your patch does.

2023-06-27 15:47 UTC, jstedfast approved these changes

2023-06-27 15:47 UTC, merged