Use base Width and Height on Android PlatformGraphicsView
dotnet/maui pull request #15721
Opened 2023-06-19 01:43 UTC by BioTurboNick

### Description of Change

I noticed that this type is using some special OnSizeChanged interface, which is stored as an int but then turned back into a float.

Why not just use the Width and Height of the base class directly? This PR does that.

### Issues Fixed

I am troubleshooting an issue where some drawables are drawing based on an outdated size value. The GraphicsView itself has the proper dimensions after the rendering pass, but the drawable may not. 

I don't know if it fixes the issue, but it seems like it could.

2023-06-19 06:08 UTC, jsuarezruiz commented
/azp run

2023-06-19 12:35 UTC, BioTurboNick commented
@dotnet-policy-service agree

I cannot tell if the CI failures mean I broke something 😂

2023-06-19 15:49 UTC, BioTurboNick commented
It's possible I'm not fully understanding what OnSizeChanged is doing here, or why the values have to be stores separately.

E.g. if they're platform units vs. MAUI units?

I may have found an alternative solution to my issue, though. So if I'm wrong, this can just be closed.

2023-06-26 15:02 UTC, jsuarezruiz requested changes
The build is failing:
`/Users/builder/azdo/_work/2/s/src/Graphics/src/Graphics/PublicAPI/net-android/PublicAPI.Unshipped.txt(804,1): error RS0017: Symbol 'override Microsoft.Maui.Graphics.Platform.PlatformGraphicsView.OnSizeChanged(int width, int height, int oldWidth, int oldHeight) -> void' is part of the declared API, but is either not public or could not be found [/Users/builder/azdo/_work/2/s/src/Graphics/src/Graphics/Graphics.csproj::TargetFramework=net7.0-android]`

Because you need to update the /Graphics/src/Graphics/PublicAPI/net-android/PublicAPI.Unshipped.txt file including the changes in the PlatformGraphicsView class. Using Visual Studio, can get a direct fix automatically from the suggestions.

2023-07-06 06:47 UTC, PureWeen commented
> It's possible I'm not fully understanding what OnSizeChanged is doing here, or why the values have to be stored separately.
> 
> E.g. if they're platform units vs. MAUI units?
> 
> I may have found an alternative solution to my issue, though (extend PlatformTouchGraphicsView and call Invalidate in OnLayout). So if I'm wrong, this can just be closed - but perhaps there's something wrong in the coordination here to be looked at.
> 
> EDIT: Or maybe I was just observing #15195 again, though I thought I was on 7.0.81... ugh.

Can you log an issue with a repro so we can validate what you are fixing? There are some fixes coming to layouts in the next SR of .NET7 so perhaps that will resolve your issue?

2023-07-06 06:48 UTC, PureWeen commented on src/Graphics/src/Graphics/Platforms/Android/PlatformGraphicsView.cs
> +			var dirtyRect = new RectF(0, 0, Width, Height);
I think you would use MeasuredWidth and MeasuredHeight here

2023-07-16 14:03 UTC, BioTurboNick commented
I'm going to close this because I'm not entirely sure it does anything and I can't test it.

2023-08-08 08:11 UTC, closed without merging

2023-08-08 08:12 UTC, mattleibow commented
I see the bot is being funny... But yeah, not sure what this will affect and if the number are actually different.