Add logic to set DefaultLabelPosition on the WinUI CommandBar
dotnet/maui pull request #15835
Opened 2023-06-23 19:02 UTC by Foda

### Description of Change

Make the default label position on WinUI CommandBar use "right" by default, or if there's only icons collapsed by default.

### Issues Fixed

Fixes #12063

2023-06-23 20:29 UTC, PureWeen requested changes
Can we add tests?

If you look in `ControlsHandlerTestBase.Windows.cs` you'll see some helper methods in there from grabbing the command bar so you can validate the different pivots.

2023-06-27 03:52 UTC, mattleibow reviewed
This looks great! 

can you add a test to check when adding text that it causes the layout to change. For example, add items with just icons and display, the change to have text and check to see it updates to Right.

2023-06-27 18:11 UTC, Foda commented
> This looks great!
> 
> can you add a test to check when adding text that it causes the layout to change. For example, add items with just icons and display, the change to have text and check to see it updates to Right.

Ah, that's a good idea.

2023-07-13 08:54 UTC, PureWeen approved these changes

2023-07-13 08:54 UTC, merged