Include headers/footers in EmptySource count so they show up when ItemsSource is null
dotnet/maui pull request #15979
Opened 2023-07-03 21:11 UTC by hartez

### Description of Change

The EmptySource on Android is aware of the header and footer, but doesn't include them in the `Count`. Which means that the adapters don't know to display them when the ItemSource is `null`.

This change adjusts the reported `Count` from EmptySource to account for the presence of the header and footer.

### Issues Fixed

Fixes #8934

2023-07-03 23:57 UTC, haritha-mohan approved these changes

2023-07-05 15:21 UTC, PureWeen requested changes
Can we add some additional tests that would cover the case(s) found by the legacy gallery?

2023-07-05 19:40 UTC, mattleibow commented
/rebase

2023-07-05 19:40 UTC, mattleibow commented
I see the less correct https://github.com/dotnet/maui/pull/15688 is merged... yuet no conflicts even since it touches the same files...

2023-07-05 19:46 UTC, mattleibow commented
I see it was reverted actually: https://github.com/dotnet/maui/pull/15886

This is the issue that Shane was referring to: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7979402&view=ms.vss-test-web.build-test-results-tab

2023-07-05 22:06 UTC, hartez commented
> Can we add some additional tests that would cover the case(s) found by the legacy gallery?

Aren't they covered by the legacy gallery tests?

2023-07-07 21:37 UTC, PureWeen commented
> > Can we add some additional tests that would cover the case(s) found by the legacy gallery?
> 
> Aren't they covered by the legacy gallery tests?

We only run these tests on the main/feature branches. Ideally, we'll grow enough coverage inside our new appium tests/device tests (which run on every PR) that we can eventually just obsolete our legacy gallery tests once we feel that we've pretty much reached coverage parity.

2023-07-10 14:55 UTC, PureWeen approved these changes

2023-07-10 14:55 UTC, merged