Reduce Confusion of DateSelected Event in DatePicker (Split Into DateSelected and DateChanged)
dotnet/maui pull request #16153
Opened 2023-07-13 23:19 UTC by expensivecow

### Description of Change

Hello! 

Currently, the NET MAUI DatePicker class supports a single event interface "DateSelected". Given the name of the interface, many developers assumed the event would trigger every time a user sets the DatePicker control (see #9180, #13156, #16007). Unfortunately, this does not seem to be the case as the event is only called when the Date value is changed.

**Investigation**

Looking into the issue a bit deeper, I found that this is because the DateSelected event is hooked to the DatePicker's DateProperty PropertyChanged event like the following: 

```C#
/// <include file="../../docs/Microsoft.Maui.Controls/DatePicker.xml" path="Type[@FullName='Microsoft.Maui.Controls.DatePicker']/Docs/*" />
public partial class DatePicker : View, IFontElement, ITextElement, IElementConfiguration<DatePicker>, IDatePicker
{
	/// <summary>Bindable property for <see cref="Date"/>.</summary>
	public static readonly BindableProperty DateProperty = BindableProperty.Create(nameof(Date), typeof(DateTime), typeof(DatePicker), default(DateTime), BindingMode.TwoWay,
		coerceValue: CoerceDate,
		propertyChanged: DatePropertyChanged
		defaultValueCreator: (bindable) => DateTime.Today);

        ...

	static void DatePropertyChanged(BindableObject bindable, object oldValue, object newValue)
	{
		var datePicker = (DatePicker)bindable;
 
                // DateSelected event will only ever trigger when the DateProperty is changed!
		EventHandler<DateChangedEventArgs> selected = datePicker.DateSelected;
          
		if (selected != null)
			selected(datePicker, new DateChangedEventArgs((DateTime)oldValue, (DateTime)newValue));
	}
}
```

**Proposed Fix**

I would like to propose the DatePicker support two events, DateSelected and DateChanged, to clear the confusion of the current DateSelected event. Specifically:

1. DateSelected - Called when the user selects a date (regardless of whether it is the same value)
2. DateChanged - Called when the DateProperty value changes from value x to value y (where x != y)

To implement the proposal I have made the following changes:

1. Added one additional event handler "DateChanged" to DatePicker class, and added DateChanged definition to related Public API files (net, net-android, net-ios, net-maccatalyst, net-tizen, net-windows, netstandard)
2. Modified DatePropertyChanged method to use DateChanged Event instead of DateSelected Event
3. Hooked DateSelected Event to the DateProperty's CoerceValueDelegate

**Tests For Changes**

To test the changes, I have added controls to the DatePicker Gallery within the Maui.Controls.Sample. Instructions are found below for testing purposes:

1. Select the DatePicker under the label "Date Selected/Changed Events"
2. Set the DateTime to the same value and click "OK"

Expectation: 
Label with caption "Selected: " populates with a date, while label with caption "Changed: " remains the same.

3. Set the DateTime to the following day and click "OK"

Expectation:
Both labels with caption "Selected: " and "Changed: "  are set with the following day

I have tested and confirmed that the above expectations both work for iOS (16.2), and Android (API33).

### Issues Fixed

Fixes #9180, #13156, #16007

2023-07-27 04:12 UTC, PradeepPappuAto commented
Can this PR be prioritised please and make it available for .Net7?

2023-08-07 14:46 UTC, PureWeen commented
@expensivecow If we made the DateSelected property nullable so the field could be blank would that suffice? Or would this additional property also be useful in that scenario?

2023-08-10 20:35 UTC, expensivecow commented
Hi @PureWeen, making the DateSelected property nullable so the field could be blank would suffice for this scenario. The additional property serves two purposes:

1. It enables developers to create a custom nullable datetime picker control in the case the DateSelected property was left not nullable
2. Provides an interface that allows developers to perform functionality on when the user selects a date rather than only when the date is changed

One thought may be whether there are any cases where a user may want a non-nullable datetime picker control... but I cannot think of a use case off the top of my head. Regardless, I am more than happy to implement changes to make the property nullable if that is the better solution!

2024-10-08 11:21 UTC, StepKie commented
@PureWeen 
Several issues are blocked by this PR not moving forward, can this be considered, please?
#13156 is the most pressing one, is very basic, and has been open for over 1,5 years now
Thank you for your consideration.

2024-10-10 07:05 UTC, StepKie approved these changes
LGTM

2025-06-17 12:40 UTC, jfversluis commented
/azp run MAUI-DeviceTests-public

2025-06-19 10:59 UTC, jfversluis commented
Failing test is unrelated

2025-06-23 10:57 UTC, rmarinho requested changes
Changes go to the Unshipped.txt files

2025-06-23 10:57 UTC, rmarinho commented on src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Shipped.txt
> +Microsoft.Maui.Controls.DatePicker.DateChanged -> System.EventHandler<Microsoft.Maui.Controls.DateChangedEventArgs>
this is wrong we just change the unshiped files

2025-07-15 10:58 UTC, rmarinho commented
/azp run

2025-07-15 15:43 UTC, rmarinho approved these changes

2025-07-15 16:10 UTC, PureWeen requested changes
- need to rereview API based on hacing merged nullable https://github.com/dotnet/maui/pull/27921

2025-07-15 17:47 UTC, PureWeen requested changes
Looking at some more of the API surface we are adding for NET10

we are also adding an "IsOpen" and "IsClosed" property
https://github.com/dotnet/maui/pull/29323

So, developers can use that property to see that the picker has been closed. 

And from that react accordingly

2025-07-15 20:41 UTC, PureWeen commented
After discussing with the team we're going to close this one

With .NET 10 the addition of "Nullable" for the pickers and the addition of "IsOpen" should create sufficient enough API to achieve what's required here. Plus, we are not keen on changing the behavior of "DateSelected" at this point in time. 

It's an unfortunate name for the API but we'd rather not break users

2025-07-15 20:41 UTC, closed without merging