[Android] Fix issue setting CarouselView position on Ctor or Appearing
dotnet/maui pull request #16165
Opened 2023-07-14 11:09 UTC by jsuarezruiz

### Description of Change

Fix issue setting CarouselView position on Ctor or Appearing.

![fix-droid-cv-position](https://github.com/dotnet/maui/assets/6755973/de00f20b-1026-40c3-b834-7231d262617e)

To validate the changes use the CarouselView samples setting the position in the Ctor or OnAppearing from the .NET MAUI Gallery.

<img width="432" alt="Captura de pantalla 2023-07-14 a las 12 40 04" src="https://github.com/dotnet/maui/assets/6755973/6bbe1fd0-eedf-48de-8d9c-6e532ed99b0b">

### Issues Fixed

Fixes #7575

2023-07-14 11:45 UTC, jsuarezruiz commented on src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
> +			if (oldItemViewAdapter != null && _initialized)
Initializing the CarouselView, the first property invalidated is the ItemsSource property, which is responsible at the Android platform level for creating the Adapter etc. After that, the ItemTemplate property also updates the Adapter that already exists https://github.com/dotnet/maui/blob/5a95a116fe4596d775214c055e8155b15dac19ca/src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs # L122 and resets the position to 0.

With this change, we only change the Adapter if the PlatformView is initialized.

2023-07-24 14:36 UTC, jsuarezruiz commented on src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
> +			if (oldItemViewAdapter != null && _initialized)
Add an UI Test!

2023-07-27 10:21 UTC, jsuarezruiz commented on src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
> +			if (oldItemViewAdapter != null && _initialized)
Added UI Tests.
<img width="250" alt="Captura de pantalla 2023-07-27 a las 12 20 16" src="https://github.com/dotnet/maui/assets/6755973/69a6b1ca-80ec-402a-a986-4014353a3e62">

2023-07-31 17:50 UTC, rmarinho commented
/rebase

2023-07-31 17:54 UTC, rmarinho requested changes
Seems the test is failing on android. I rebased to see if it still fails.

2023-08-21 10:58 UTC, rmarinho approved these changes

2023-08-21 10:58 UTC, merged