Implement PointerPressed and PointerReleased
dotnet/maui pull request #16213
Opened 2023-07-18 18:39 UTC by rachelkang

### Description of Change

WIP MacCatalyst impl

Implemented on Windows

### Issues Fixed

Fixes #13346

2023-07-21 19:50 UTC, jknaudt21 commented
Thanks for adding docs 🥇

2023-07-26 18:24 UTC, samhouts requested changes
I do love pasta, but not COPYPASTA! 🍝

2023-07-26 18:24 UTC, samhouts commented on src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml.cs
> +			pgrLabel.Text = "Thanks for releasing me! Press me again or leave me!";
don't leave me 😭

2023-07-26 18:24 UTC, samhouts commented on src/Controls/src/Core/PointerGestureRecognizer.cs
> +		/// An object to be passed to the PointerPressedCommand. This is a bindable property.
```suggestion
		/// An object to be passed to the PointerReleasedCommand. This is a bindable property.
```

2023-07-26 22:42 UTC, samhouts approved these changes

2023-08-02 13:28 UTC, PureWeen requested changes
Thoughts on these Remarks?

https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointerreleased?view=winrt-22621#remarks

2023-08-02 13:45 UTC, rachelkang commented
> Thoughts on these Remarks?
> 
> https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointerreleased?view=winrt-22621#remarks

I'll test more scenarios that might be affected by this (i.e. releasing pointer over a different control). Let me know if there are other edge case scenarios that come to mind!

2023-08-08 19:02 UTC, PureWeen approved these changes

2023-08-08 19:02 UTC, merged