[net8.0] Ignore cells leak
dotnet/maui pull request #16231
Opened 2023-07-19 14:47 UTC by rmarinho

### Description of Change

Try get a green build for net8.0

2023-07-19 15:05 UTC, jsuarezruiz commented on src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
> +		//public async Task CellsDoNotLeak()
Better use just Skip with a comment (the comment will help to understand the status). Also, should we create a related issue where @jonathanpeppers could work?

2023-07-19 15:54 UTC, jonathanpeppers requested changes, later dismissed
Let's fix this test. Can you share cases where it failed?

It's already caught a new leak that was introduced in: https://github.com/dotnet/maui/pull/15856

2023-07-19 17:26 UTC, rmarinho commented
@jonathanpeppers first time it started was with Android bump commit https://github.com/dotnet/maui/commit/310d5d4f3a4805de148d55bd5d991c46692cb2b8 doesn't make much sense

2023-07-19 19:28 UTC, jonathanpeppers commented
Let's try this: https://github.com/dotnet/maui/pull/16237

And then it's possible there is something that is going wrong in .NET 8? If this still fails.

2023-07-20 10:57 UTC, Redth approved these changes

2023-07-20 11:06 UTC, merged

2023-07-20 13:49 UTC, jonathanpeppers commented on src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
> +			await AssertionExtensions.WaitForGC(labels.ToArray());
Ok awesome! Glad this fixed it.