Fix device tests to tun on arm64
dotnet/maui pull request #16408
Opened 2023-07-27 17:09 UTC by mattleibow

### Description of Change

Right now the device tests assume an x64 host. This PR will enable running on arm64 hosts.

2023-07-28 10:17 UTC, rmarinho requested changes
It's failing to provision the android images on windows.

https://dev.azure.com/xamarin/public/_build/results?buildId=91728&view=logs&j=22083a8f-f531-5d1a-9d1c-44debe18920a&t=aef5f1be-4bed-5de7-be44-f42d3ac5bea4

2023-07-28 14:13 UTC, rmarinho commented
/rebase

2023-07-28 23:04 UTC, rmarinho commented
It works!

2023-07-28 23:05 UTC, rmarinho approved these changes

2023-07-31 16:55 UTC, sbanni commented on eng/devices/android.cake
>  			else
Can we just have the one if (emulator) and then else to arm64?

2023-07-31 16:56 UTC, sbanni approved these changes

2023-07-31 16:56 UTC, merged