Use consistent nav bar styling
dotnet/maui pull request #16591
Opened 2023-08-07 21:21 UTC by BretJohnson

Use the same nav bar style for the gallery pages and the issues pages. This looks better aesthetically and avoids an issue where issue page screenshots aren't consistent, depending on whether you've ever visited a gallery page or not.

See more details in the Teams chat here:
https://teams.microsoft.com/l/message/19:46c9eef68efe400393f538bd778e4718@thread.v2/1691428231798?context=%7B%22contextType%22%3A%22chat%22%7D

2023-08-07 21:52 UTC, Eilon approved these changes, later dismissed
The Teams chat is not accessible to me, but this sounds reasonable.

2023-08-10 23:13 UTC, Eilon commented
Looks like the test is failing on iOS and Windows now: https://dev.azure.com/xamarin/public/_build/results?buildId=92639&view=ms.vss-test-web.build-test-results-tab&runId=2055450&resultId=100012&paneView=debug

```
Error message
VisualTestUtils.VisualTestFailedException :
Snapshot different than baseline: Issue15330Test.png (12.01% difference)
If the correct baseline has changed (this isn't a a bug), then update the baseline image.
See test attachment or download the build artifacts to get the new snapshot file.


More info: https://aka.ms/visual-test-workflow



Stack trace
   at VisualTestUtils.VisualRegressionTester.Fail(String message)
   at VisualTestUtils.VisualRegressionTester.VerifyMatchesSnapshot(String name, ImageSnapshot actualImage, String environmentName, ITestContext testContext)
   at Microsoft.Maui.AppiumTests.UITestBase.VerifyScreenshot(String name) in /Users/builder/azdo/_work/3/s/src/Controls/tests/UITests/Tests/UITestBase.cs:line 183
   at Microsoft.Maui.AppiumTests.Issues.Issue15330.Issue15330Test() in /Users/builder/azdo/_work/3/s/src/Controls/tests/UITests/Tests/Issues/Issue15330.cs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

2023-08-10 23:13 UTC, Eilon requested changes
Need to fix failing test(s).

2023-08-11 15:50 UTC, Eilon commented
@BretJohnson - iOS and Windows still seem sad 😢 

```
VisualTestUtils.VisualTestFailedException :
Snapshot different than baseline: Issue15330Test.png (6.93% difference)
If the correct baseline has changed (this isn't a a bug), then update the baseline image.
See test attachment or download the build artifacts to get the new snapshot file.


More info: https://aka.ms/visual-test-workflow



Stack trace
   at VisualTestUtils.VisualRegressionTester.Fail(String message)
   at VisualTestUtils.VisualRegressionTester.VerifyMatchesSnapshot(String name, ImageSnapshot actualImage, String environmentName, ITestContext testContext)
   at Microsoft.Maui.AppiumTests.UITestBase.VerifyScreenshot(String name) in /Users/builder/azdo/_work/3/s/src/Controls/tests/UITests/Tests/UITestBase.cs:line 183
   at Microsoft.Maui.AppiumTests.Issues.Issue15330.Issue15330Test() in /Users/builder/azdo/_work/3/s/src/Controls/tests/UITests/Tests/Issues/Issue15330.cs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

2023-08-11 15:51 UTC, Eilon commented
Though, the % difference is lower now, so it's getting better 😉

2023-08-13 23:09 UTC, Eilon approved these changes

2023-08-14 15:13 UTC, PureWeen approved these changes

2023-08-14 15:14 UTC, merged