Update VisualElement docs
dotnet/maui pull request #16754
Opened 2023-08-15 11:36 UTC by jfversluis

### Description of Change

Moves the external comments to inline, adds missing comments and minor improvements.

### Issues Fixed

Related to https://github.com/dotnet/maui/issues/3960

2023-08-16 13:52 UTC, rmarinho commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +    /// </remarks>
formatting

2023-08-16 18:45 UTC, jknaudt21 requested changes

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Signals the start of a batch of changes to the elements properties. This can benefit performance if a bigger number of property values are changed.
I'd move the second sentence to the remarks

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <remarks>Application authors will not generally need to batch updates manually as the animation framework will do this for them.</remarks>
```suggestion
		/// <remarks>Application authors will generally not need to batch updates manually, as the animation framework will do this for them.</remarks>
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Occurs when children of this element are changed in order.
```suggestion
		/// Occurs when order of this element's children changes.
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Attempts to set focus to this element.
```suggestion
		/// Attempts to set the keyboard focus on this element.
```
I think we might need to be clearer that this focus is for entries or keyboard-focusable stuff. That being said I'm not even 100% sure what this property does so I might be wrong.

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <remarks>If the minimum size that the visual element needs in order to be displayed on the device is larger than can be accommodated by<paramref name="widthConstraint" /> and <paramref name="he
```suggestion
		/// <remarks>If the minimum size that the visual element needs in order to be displayed on the device is larger than can be accommodated by <paramref name="widthConstraint" /> and <paramref name="heightConstraint" />, the return value may represent a rectangle that is larger in either one or both of those parameters.</remarks>
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Unsets focus to this element.
```suggestion
		/// Unsets keyboard focus on this element.
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Causes the <see cref="ChildrenReordered"/> event to be triggered.
```suggestion
		/// Raises the <see cref="ChildrenReordered"/> event.
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <returns>The requested size that a visual element wants in order to be displayed on the device.</returns>
```suggestion
		/// <returns>The requested size that the element requires in order to be displayed on the device.</returns>
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// This method is called when the size of the element is set during a layout cycle. Implement this method to add class handling for this event.
```suggestion
		/// Method that is called when the size of the element is set during a layout cycle. Implement this method to add class handling for this event.
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// This method is called during a layout cycle to signal the start of a sub-tree layout.
```suggestion
		/// Method that is called during a layout cycle to signal the start of a sub-tree layout.
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Positions child objects and determines a size for a <see cref="VisualElement"/>. Parent objects that implement custom layout for their child elements should call this method from their layout o
I'd recommend putting the second sentence in the remarks

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Provides a way to allow subclasses (e.g., <see cref="ScrollView"/>) to override <see cref="Arrange(Rect)"/> even though
```suggestion
		/// Allows subclasses to override <see cref="Arrange(Rect)"/> even though
```

2023-08-16 18:45 UTC, jknaudt21 commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// MeasureOverride provides a way to allow subclasses (e.g., Layout) to override Measure even though
```suggestion
		/// Provides a way to allow subclasses to override <see cref="Measure"/> even though
```

2023-08-16 18:56 UTC, jknaudt21 commented
We also need to document the explicit interface implementations since the docs tooling will not automatically grab these. Hopefully an `<inheritdoc>` should be enough. 

A lot of them come from IView and IElement, and are properties we already have documented, such as `Height`. 

To get a quick reference of the items that are missing, see: https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.visualelement?view=net-maui-7.0#explicit-interface-implementations

2023-08-22 12:21 UTC, jfversluis commented on src/Controls/src/Core/VisualElement/VisualElement.cs
Yeah I was on the fence about that one. Looking at other Microsoft frameworks they mix it as well, but you're right, let me add some uniformity here.

2023-08-22 14:18 UTC, samhouts requested changes

2023-08-22 14:18 UTC, samhouts commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <para>In XAML, resource dictionaries are filled with key/value pairs that are specified in XAML and consequently created at run time. The keys in the resource dictionary are specified with the
```suggestion
		/// <para>In XAML, resource dictionaries are filled with key/value pairs that are specified in XAML and consequently created at runtime. The keys in the resource dictionary are specified with the <c>x:Key</c> attribute of the XAML tag for the type to create. An object of that type is created, and is initialized with the property and field values that are specified either by additional attributes or by nested tags, both of which, when present, are simply string representations of the property or field names. The object is then inserted into the <see cref="ResourceDictionary" /> for the enclosing type at runtime.</para>
```

2023-08-22 14:18 UTC, samhouts commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <para>Resource dictionaries and their associated XML provide the application developer with a convenient method to reuse code inside the XAML compile-time and run-time engines.</para>
```suggestion
		/// <para>Resource dictionaries and their associated XML provide the application developer with a convenient method to reuse code inside the XAML compile-time and runtime engines.</para>
```

2023-08-22 14:18 UTC, samhouts commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Gets and sets the front-to-back z-index of an element within a layout. This is a bindable property.
```suggestion
		/// Gets or sets the front-to-back z-index of an element within a layout. This is a bindable property.
```

2023-08-22 14:18 UTC, samhouts commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <returns>The resulting size of this elements frame by the platform.</returns>
```suggestion
		/// <returns>The resulting size of this element's frame by the platform.</returns>
```

2023-08-22 15:32 UTC, samhouts approved these changes

2023-08-22 16:57 UTC, jknaudt21 approved these changes

2023-08-22 17:40 UTC, merged

2023-08-22 17:50 UTC, jfversluis commented
Should be relatively easy to backport and will increase the coverage of the docs in vCurrent

2023-08-22 18:19 UTC, hartez requested changes

2023-08-22 18:19 UTC, hartez commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// Gets or sets a value which overrides the maximum height the element will request during layout. This is a bindable property.
```suggestion
		/// Gets or sets the maximum height the element will request during layout. This is a bindable property.
```

2023-08-22 18:19 UTC, hartez commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <para><see cref="MaximumHeightRequest"/> is used to override the results of a call to <see cref="GetSizeRequest(double, double)"/> by setting the maximum height property. This causes overflow h
```suggestion
		/// <para><see cref="MaximumHeightRequest"/> is used to ensure that the element has no more than the specified height during layout.
```

2023-08-22 18:19 UTC, hartez commented on src/Controls/src/Core/VisualElement/VisualElement.cs
> +		/// <remarks>The y value of an element is set during the layout cycle.</remarks>
```suggestion
		/// <remarks>The position of an element is set during layout.</remarks>
```

2023-08-24 14:45 UTC, jfversluis commented
/backport net7.0

2023-08-24 14:55 UTC, jfversluis commented
/backport to net7.0