[MacCatalyst] Implement PointerPressed and PointerReleased
dotnet/maui pull request #16925
Opened 2023-08-22 15:58 UTC by rachelkang

### Description of Change

Implemented PointerPressed and PointerReleased for MacCatalyst

### Issues Fixed

Fixes #13346

2023-09-07 16:30 UTC, PureWeen requested changes
it looks like some events are firing multiple times

```XAML
<VerticalStackLayout>
        <Label Text="test me">
            <Label.GestureRecognizers>
                <PointerGestureRecognizer PointerReleased="PointerGestureRecognizer_PointerReleased"
                                          PointerEntered="PointerGestureRecognizer_PointerEntered"
                                          PointerExited="PointerGestureRecognizer_PointerExited"
                                          PointerMoved="PointerGestureRecognizer_PointerMoved"
                                          PointerPressed="PointerGestureRecognizer_PointerPressed"
                                          ></PointerGestureRecognizer>

            </Label.GestureRecognizers>

        </Label>

    </VerticalStackLayout>
```
    
    
```C#
    void PointerGestureRecognizer_PointerReleased(System.Object sender, Microsoft.Maui.Controls.PointerEventArgs e)
		{
			System.Diagnostics.Debug.WriteLine("PointerGestureRecognizer_PointerReleased");
		}

		void PointerGestureRecognizer_PointerEntered(System.Object sender, Microsoft.Maui.Controls.PointerEventArgs e)
		{
			System.Diagnostics.Debug.WriteLine("PointerGestureRecognizer_PointerEntered");
		}

		void PointerGestureRecognizer_PointerExited(System.Object sender, Microsoft.Maui.Controls.PointerEventArgs e)
		{
			System.Diagnostics.Debug.WriteLine("PointerGestureRecognizer_PointerExited");
		}

		void PointerGestureRecognizer_PointerMoved(System.Object sender, Microsoft.Maui.Controls.PointerEventArgs e)
		{
			System.Diagnostics.Debug.WriteLine("PointerGestureRecognizer_PointerMoved");
		}

		void PointerGestureRecognizer_PointerPressed(System.Object sender, Microsoft.Maui.Controls.PointerEventArgs e)
		{
			System.Diagnostics.Debug.WriteLine("PointerGestureRecognizer_PointerPressed");
		}
```

If I press the mouse down and then move it outside the bounds of the label these are the events that I get raised after I release

```
PointerGestureRecognizer_PointerMoved
PointerGestureRecognizer_PointerMoved
PointerGestureRecognizer_PointerMoved
PointerGestureRecognizer_PointerReleased
PointerGestureRecognizer_PointerEntered
PointerGestureRecognizer_PointerExited
```

2023-09-29 11:44 UTC, jsuarezruiz reviewed
Seems like the build is failing by a merge error (duplicated member in GesturePlatformManager)
```
D:\a\_work\1\s\src\Controls\src\Core\Platform\GestureManager\GesturePlatformManager.Windows.cs(521,8): error CS0111: Type 'GesturePlatformManager' already defines a member called 'OnPgrPointerPressed' with the same parameter types [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\a\_work\1\s\src\Controls\src\Core\Platform\GestureManager\GesturePlatformManager.Windows.cs(525,8): error CS0111: Type 'GesturePlatformManager' already defines a member called 'OnPgrPointerReleased' with the same parameter types [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-windows10.0.20348]
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(841,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Release\net7.0-windows10.0.20348\\input.json" "obj\Release\net7.0-windows10.0.20348\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-windows10.0.20348]
    16 Warning(s)
    6 Error(s)
```

2023-10-09 19:21 UTC, rachelkang commented
oops, thanks for catching @jsuarezruiz - fixed!

2023-10-16 16:02 UTC, samhouts commented
@rachelkang Failing tests?

2023-10-23 16:57 UTC, rachelkang commented
hopefully this makes the tests all happy! drag and drop appium tests look good now locally on mac

2023-10-24 18:33 UTC, rachelkang commented
yay all green now!!! phew

2023-10-26 19:56 UTC, PureWeen commented on src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs
> +								if (view.ToPlatform().Bounds.Contains(originPoint))
should we change this to
eventTracker?.PlatformView

Just to make sure we're consistent?
 That way if `eventTracker?.PlatformView` changes to something else this code will all continue to work

2023-11-10 13:14 UTC, jsuarezruiz reviewed
Have sense to include with this PR changes in the PointerGestureRecognizerEvents sample page and some UI Tests?. I can add it if you want.

2023-11-15 18:58 UTC, davidortinau commented
Would like to have this for parity pls

2023-11-22 01:37 UTC, tounaobun commented
I'm wondering why Windows supports PointerPressed & PointerReleased events while macOS doesn't support on 8.0.3 version. Hope this issue could be fixed in the next release.

2023-11-22 22:14 UTC, PureWeen approved these changes

2023-11-23 20:05 UTC, Redth approved these changes

2023-11-26 16:24 UTC, PureWeen commented
/rebase

2023-11-27 03:45 UTC, merged