Avoid NRE if no shell items are visible
dotnet/maui pull request #16946
Opened 2023-08-23 03:06 UTC by BretJohnson

Fixes #16940

Add null checks to avoid an NRE if no shell items are currently visible. This can happen if for some strange reason the user has an empty <Shell> element in the XAML, with no children. It can also happen in a transient states where certain items are hidden, others are about to be shown, and between those two things happening no items are visible - that's the case with bug #16940

However, the app gets into this state it's better not to crash. With the null checks present, the UI behaves reasonably (at least on Windows) - the app window is blank with no current shell item selected.

2023-08-23 11:14 UTC, rmarinho commented
Is it possible to add a test?

2023-08-23 23:31 UTC, BretJohnson commented
> Is it possible to add a test?

Yes. I plan to add an Appium based test for this (after spending a few hours today trying to reproduce the issue with a device 
test).

2023-08-24 21:54 UTC, PureWeen commented
The original sample no longer crashes but the item visibility doesn't seem quite correct

Initial Load
![image](https://github.com/dotnet/maui/assets/5375137/5e69ca09-d16f-43a9-926a-29eb90f951e7)

First click
![image](https://github.com/dotnet/maui/assets/5375137/c36553ac-eb59-4598-9a70-a4ebad972e8b)

Second click (this is wrong?)
![image](https://github.com/dotnet/maui/assets/5375137/d716add7-4a3c-4c36-bd49-548ab844bb77)

Third Click
![image](https://github.com/dotnet/maui/assets/5375137/c5205acb-1183-4c9c-82fc-661dc678924a)

Fourth Click
![image](https://github.com/dotnet/maui/assets/5375137/945a82ff-d913-4efa-92f6-857436f70dba)

2023-08-24 21:54 UTC, PureWeen requested changes
Item visibility doesn't seem quite correct

2023-08-25 01:41 UTC, BretJohnson commented
> Item visibility doesn't seem quite correct

I debugged this to investigate and it appears to be a WinUI bug. At the "Second click (this is wrong?)" step, the `FlyoutItems` ObservableCollection (which drives the WinUI flyout menu items, via binding) looks correct - it contains both items. If you resize the app window to trigger things getting repainted, both menu items display at that point - they are present, the UI just wasn't fully refreshed at first.

I then tried to reproduce this UI refresh issue in a standalone WinUI app, to write up a bug for the WinUI team, but kept being blocked by the https://github.com/microsoft/microsoft-ui-xaml/issues/8770 crash with the steps in this scenario, with the particular sequence of Adds and Removes on the ObservableCollection. I'm not sure why that crash doesn't happen in the steps here with MAUI, but it doesn't (though other steps trigger it). In any case, a WinUI UI refresh issue seems relatively minor compared to the other WinUI issues here.

2023-08-25 15:31 UTC, Redth approved these changes

2023-09-29 11:37 UTC, jsuarezruiz approved these changes

2023-09-29 16:23 UTC, BretJohnson commented
Current status:
This PR is probably OK to merge as is. But let's wait for the WinUI team to investigate https://github.com/microsoft/microsoft-ui-xaml/issues/8770 (internal link https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/46242968). 
That investigation may yield an additional workaround we can make on our side, to avoid the issue here https://github.com/dotnet/maui/pull/16946#pullrequestreview-1594523987.

2023-10-11 14:41 UTC, BretJohnson commented
Current status on WinUI issue above (as of yesterday): No fix yet, investigating this now. There seems to be a [stale cached collection size](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmicrosoft%2FWinUI%2F_git%2Fmicrosoft-ui-xaml-lift%3Fpath%3D%2Fcontrols%2Fdev%2FRepeater%2FItemsSourceView.cpp%26version%3DGBmain%26line%3D21%26lineEnd%3D21%26lineStartColumn%3D4%26lineEndColumn%3D25%26lineStyle%3Dplain%26_a%3Dcontents&data=05%7C01%7CBret.Johnson%40microsoft.com%7Ca4424b806b1c45fd70cc08dbc9b491f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638325549623175003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tyETdpbp%2FpYl7Ne2TTieJmHZG%2Bic0VOzMLx%2BVGmQ%2BDg%3D&reserved=0) which is what is causing layout to index past the end of the array.

2023-11-26 01:01 UTC, closed without merging