Fix #16470 - [Android]
dotnet/maui pull request #16965
Opened 2023-08-23 20:54 UTC by widavies

### Description of Change

Both changes modify the API of `TabbedPage`

1) Added `BarTabMode` which can be set on `TabbedPage` to make tabs fixed or scrollable
2) Added `BarIndict

### Issues Fixed

Fixes #16470

2023-08-24 07:38 UTC, jfversluis requested changes
Couple of git merge indicators in there.

Additionally, I'm not sure if this is the way to implement this. This is very specific to Android and would confuse people trying to use this on other platforms. While this might fix the issue at hand, I feel that we should have a more platform specific way of doing this.

2023-08-24 07:38 UTC, jfversluis commented on src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
> +>>>>>>> Stashed changes
This doesn't look right

2023-08-24 07:38 UTC, jfversluis commented on src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
> +>>>>>>> Stashed changes
This doesn't look right

2023-08-24 14:47 UTC, widavies commented
> Couple of git merge indicators in there.
> 
> Additionally, I'm not sure if this is the way to implement this. This is very specific to Android and would confuse people trying to use this on other platforms. While this might fix the issue at hand, I feel that we should have a more platform specific way of doing this.

Good point, I had that thought when I was working on this - I would assume iOS has identical flags on their tab view, but I'm not certain. Maybe for now I could add the feature as an Android specific flag, similar to this example for toolbar placement from your [official docs](https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/tabbedpage-toolbar-placement):
```xaml
<TabbedPage ...
            xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
            android:TabbedPage.ToolbarPlacement="Bottom">
    ...
</TabbedPage>
```

Oops, looks like a bad merge on the API there. I'll go ahead and fix that. Just to confirm - I'm assuming that I'll add the new API to the "unshipped" API listing, and then if this PR gets approves it will get moved to the "shipped" API listing? Or should I put it on the "shipped" API listing to begin with?

Thanks

2023-08-28 23:53 UTC, PureWeen commented
Apologies @widavies, but can we look at adding this one into the Maui Community Toolkit as an Attached Property?

https://github.com/CommunityToolkit/Maui

Unfortunately, we're past the point of being able to take new APIs right now for .NET 8. The other option would be to discuss this one for .NET 9 in a few months.

2023-09-08 19:42 UTC, widavies commented
@PureWeen No worries, sure, I'll look into creating a pull request in the community toolkit. Do we want to close this PR or should we keep it open for .NET 9?

2023-09-11 23:24 UTC, samhouts commented
Probably best to close it for now. After GA, we can reopen it or create a new one. Thanks!!

2023-09-11 23:24 UTC, closed without merging