Add View docs
dotnet/maui pull request #17220
Opened 2023-09-05 20:00 UTC by jknaudt21

### Description of Change

Add docs for View

### Issues Fixed

Related to #3960

2023-09-06 09:41 UTC, jfversluis requested changes

2023-09-06 09:41 UTC, jfversluis commented on src/Controls/src/Core/View/View.cs
> +		/// <returns> All child elements visually beneath <paramref name="point"/>.</returns>
```suggestion
		/// <returns>All child elements visually beneath <paramref name="point"/>.</returns>
```

2023-09-06 09:41 UTC, jfversluis commented on src/Controls/src/Core/View/View.cs
> +		/// Gets or sets the <see cref="LayoutOptions" /> that define how the element gets laid in a layout cycle. This is a bindable property.
```suggestion
		/// Gets or sets the <see cref="LayoutOptions" /> that define how the element gets laid out in a layout cycle. This is a bindable property.
```

2023-09-06 09:41 UTC, jfversluis commented on src/Controls/src/Core/View/View.cs
> +		/// Gets or sets the <see cref="LayoutOptions" /> that define how the element gets laid in a layout cycle. This is a bindable property.
```suggestion
		/// Gets or sets the <see cref="LayoutOptions" /> that define how the element gets laid out in a layout cycle. This is a bindable property.
```

2023-09-06 18:06 UTC, jknaudt21 commented on src/Controls/src/Core/View/View.cs
> +		/// This is not necessary for elements that natively support certain gestures. For example, <see cref="Button"/> already supports taps.
Added this commit to address this: https://github.com/dotnet/maui/pull/17220/commits/068b75ac8fb410cf826ada62e6117fdbc7b407e9

2023-09-06 18:25 UTC, jfversluis approved these changes

2023-09-06 18:26 UTC, jfversluis commented
Suggesting backport because it's relatively safe to do and gives up more coverage on the docs in vCurrent

2023-09-06 20:05 UTC, merged

2023-10-24 19:51 UTC, PureWeen commented
/backport to release/8.0.1xx-rc2.2