[Android] Fix ScrollView filling layouts
dotnet/maui pull request #17243
Opened 2023-09-06 23:58 UTC by jknaudt21

### Problem

`ScrollView` controls would try to fill their parent container on Android even thought that wasn't the expected behavior. In cases where the `MaximumHeight` property was set, the `ScrollView` would grow to that size.

The problem was being caused by additional logic placed to make `ScrollView` fill an entire page (and thereby size child elements correctly) when it is the topmost element. More specifically, we would[ set the height's MeasureSpec to ](https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/ScrollView/ScrollViewHandler.Android.cs#L53-L73)`MeasureSpecMode.Exactly`. This caused the layout to grow to _exactly_ its largest constraint, i.e the MaximumHeight. For more context on why this was originally done, see #7514

### Solution
We check if the `ScrollView`'s parent is a layout. Or more specifically, if the _handler_ of the parent is a `ILayoutHandler`. The reason why handlers are being used rather than the elements themselves is because this logic is within Core, and I couldn't reference types inside Controls.

**Note:** This is a tentative fix. I'm not 100% sure this is the right approach but I also didn't want to regress the fixes in #7514
### Before & After
```
    <VerticalStackLayout>
        <ScrollView MaximumHeightRequest="300" BackgroundColor="LightBlue">
            <Label Text="Hello world" />
        </ScrollView>
    </VerticalStackLayout>
```
| Before | After | 
| -- | -- | 
| ![image](https://github.com/dotnet/maui/assets/32918747/3a6fbbdc-0062-4ca3-9504-782139bb27a1) | ![image](https://github.com/dotnet/maui/assets/32918747/4dd242bb-1d59-4442-af4e-4b038103b56b) |

### Issues Fixed

Fixes #16464

2023-09-07 16:57 UTC, hartez commented
> Does is look the same on iOS?

Yes.

2023-09-07 17:24 UTC, jknaudt21 commented
Adding a couple screenshots based on offline discussion: 

<details> <summary> ScrollView not contained in a layout (click me) </summary>

```
 <ScrollView BackgroundColor="LightBlue">
            <Label Text="Hello world" />
  </ScrollView>
```

![image](https://github.com/dotnet/maui/assets/32918747/f8431791-ffb3-4dd1-941c-171e751a4cf3)

</details>

<details> <summary> ScrollView inside a grid (click me) </summary>

```
<Grid>
     <ScrollView BackgroundColor="LightBlue">
            <Label Text="Hello world" />
     </ScrollView>
</Grid>
```

![image](https://github.com/dotnet/maui/assets/32918747/bcf1e6eb-696b-4430-a323-79103ba5ff38)

</details>

2023-09-12 23:52 UTC, mattleibow reviewed
Is this something the visual tests need to confirm? OR is the added test enough?

2023-09-15 21:12 UTC, hartez commented
With this layout:

```xaml
    <Grid>
        <ScrollView Background="LightBlue"
                    MaximumHeightRequest="500"
                    VerticalOptions="Fill">
            <VerticalStackLayout Background="LightGreen"
                                 Margin="5">
                <Label Text="Hello" />
            </VerticalStackLayout>

        </ScrollView>
    </Grid>
```

The inner VSL _should_ be filling up the ScrollView's viewport, because the ScrollView is set to Fill in the vertical direction. But it's not, when this PR is in effect, because the fill feature is being disabled by the check for a Layout as the ScrollView's parent.

2023-09-15 21:12 UTC, hartez commented
> Is this something the visual tests need to confirm? OR is the added test enough?

This should be verifiable with Device Tests, but the current implementation is wrong.

2023-09-15 23:41 UTC, hartez commented
The flaw in the original logic is that it doesn't take into account the situation where the constraint is infinite (meaning the measurement should ignore `Fill` and just size to the content) but the `MeasureSpec` is `AtMost` _because_ of the `MaximumHeight` (or `MaximumWidth`). 

We just need to skip the `FillViewPort` logic entirely if the measurement constraint in the ScrollView's unconstrained direction is infinite. 

Something like this:
```csharp
if (platformView.FillViewport)
{
	/*	With FillViewport active, the Android ScrollView will measure the content at least once; if it is 
		smaller than the ScrollView's viewport, it measure a second time at the size of the viewport
		so that the content can properly fill the whole viewport. But it will only do this if the measurespec
		is set to Exactly. So if we want our ScrollView to Fill the space in the scroll direction, we need to
		adjust the MeasureSpec accordingly. If the ScrollView is not set to Fill, we can just leave the spec
		alone and the ScrollView will size to its content as usual. */

	/*	We have to make sure that the constraint in the ScrollView direction isn't infinity; in that case,
		even with Fill in effect, the content's size should be only what's required to display it. */

	var orientation = virtualView.Orientation;

	if (!double.IsInfinity(heightConstraint))
	{
		if (orientation == ScrollOrientation.Both || orientation == ScrollOrientation.Vertical)
		{
			heightSpec = AdjustSpecForAlignment(heightSpec, virtualView.VerticalLayoutAlignment);
		}
	}

	if (!double.IsInfinity(widthConstraint))
	{
		if (orientation == ScrollOrientation.Both || orientation == ScrollOrientation.Horizontal)
		{
			widthSpec = AdjustSpecForAlignment(widthSpec, virtualView.HorizontalLayoutAlignment);
		}
	}
}
```

2023-09-15 23:45 UTC, hartez requested changes
Needs to account for the situation outlined in https://github.com/dotnet/maui/pull/17243#issuecomment-1721869048

2023-09-19 00:19 UTC, jknaudt21 commented
@hartez  I addressed your feedback. Thanks for catching the error!

@mattleibow  I added [this additional test ](https://github.com/dotnet/maui/pull/17243/files#diff-11df1bf7ca8cbfa62d1bc3c447de4275fcb801c2942ebfdf735e12fae61ff182R129-R147) that catches the case that E.Z outlined in his comments.

2023-09-20 21:37 UTC, jknaudt21 commented
So the tests were failing because of off-by-one (or two) pixels in Android. 

For some reason iOS and Mac render a layout whose height I specify to be 500 to be ~460, which is surprising. I made the test less strict since this PR doesn't touch any Apple code.

2023-10-09 17:52 UTC, hartez submitted a review, later dismissed

2023-10-11 18:23 UTC, jknaudt21 commented
Seems the test I wrote is failing for windows after the rebase, so I'll investigate why

2023-10-12 20:53 UTC, hartez approved these changes

2023-10-12 21:15 UTC, merged