[X] don't expant types to Extension for x:Static
dotnet/maui pull request #17276
Opened 2023-09-08 14:37 UTC by StephaneDelcroix

### Description of Change

if a type name exists with an Extension suffix, xaml rules require us to use that. But not for x:Static

### Issues Fixed

- fixes #11833

2023-09-19 19:42 UTC, samhouts commented
Do we know if this is a path that is commonly used? Is this going to break a bunch of people?

2023-09-20 06:03 UTC, StephaneDelcroix commented
> Do we know if this is a path that is commonly used? Is this going to break a bunch of people?

it's only affecting namespace with both MyClass and MyClassExtension defined. I believe this is safe and the modified behaviour is the expected one

2023-09-20 15:04 UTC, StephaneDelcroix commented
this is a dupe pr. the dupe is #15903. pick a single one

2024-06-06 16:40 UTC, mattleibow commented
@StephaneDelcroix this has been many coffee cycles since this was created... Do we still want/need this?

2024-09-12 08:43 UTC, StephaneDelcroix commented
> @StephaneDelcroix this has been many coffee cycles since this was created... Do we still want/need this?

y, but in net9

2025-01-28 14:11 UTC, mattleibow requested changes
This PR has ABI breaks as you noted, however, even if we switch to a new TFM (net10) old libraries that use this type and are built with an older maui will still break. People would have to recompile.

One workaround we can do is use default interface members.

Unless... and you would be on the hook for this (not sure what the hook would be and/or if it is enforceable) you say that this type is not meant to be used by anyone outside of maui and doing so is them opting into breaks.

And then this needs that oh-so-common rebase.

2025-01-28 14:11 UTC, mattleibow commented on src/Controls/tests/Xaml.UnitTests/LoaderTests.cs
> +			var bindingType = XamlParser.GetElementType(new XmlType("http://schemas.microsoft.com/dotnet/2021/maui", "Binding", null), null, null, true, out var ex);
Is this single line change sufficient tests for this PR? Also, that link goes nowhere and seems to make some sort of indication that this test is specific.

Is there a need to check cases where a Type and TypeExtension both exist are OK?

2025-01-28 14:57 UTC, StephaneDelcroix commented on src/Controls/tests/Xaml.UnitTests/LoaderTests.cs
> +			var bindingType = XamlParser.GetElementType(new XmlType("http://schemas.microsoft.com/dotnet/2021/maui", "Binding", null), null, null, true, out var ex);
Binding and BindingExtension both exists

2025-01-29 09:33 UTC, StephaneDelcroix commented
I reviewed this again. the only risk of breaking change would be if a 3rd party provide a markup extension that invoke `serviceproviderGetService(typeof(IXamlTypeResolver))` which is unlikely

2025-01-29 09:46 UTC, StephaneDelcroix commented
no longer a breaking change

2025-01-31 09:15 UTC, StephaneDelcroix commented
/azp run

2025-01-31 14:11 UTC, mattleibow submitted a review, later dismissed

2025-02-02 20:41 UTC, StephaneDelcroix commented
/azp run

2025-02-03 22:33 UTC, PureWeen commented
/rebase

2025-02-04 11:32 UTC, mattleibow approved these changes

2025-02-04 11:32 UTC, merged