Update Flyout when Shell.FlyoutContent changes
dotnet/maui pull request #17359
Opened 2023-09-13 20:48 UTC by spadapet

### Description of Change

`Shell.FlyoutContent` allows users to change what the Shell's flyout looks like:
* https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout#replace-flyout-content

If `FlyoutContent` changed at runtime, the UI didn't update (either going to custom content, or reverting back to default content when setting `FlyoutContent` to `null`).

The update functionality was already there, like when `IFlyoutView.Flyout` changed, but that property was also exposed as `Shell.FlyoutContent`.

### Issues Fixed

Fixes #9080 (Shell.FlyoutContent does not update with hot reload)

2023-09-13 21:56 UTC, spadapet commented
There is still an issue where removing the value of FlyoutContent _the first time_ will not paint the default flyout text until the window is resized. Adding FlyoutContent always works. A different bug would be needed, or there may already be a bug, such as:

* https://github.com/dotnet/maui/issues/14377

2023-09-19 16:28 UTC, spadapet commented
Ping @PureWeen for review. I think this change is good even if first removing FlyoutContent on WinUI doesn't render the text. That can be solve separately.

2023-09-20 22:04 UTC, PureWeen requested changes
looks good!

Can you add tests?

2023-09-25 17:51 UTC, spadapet commented
> looks good!
> 
> Can you add tests?

@PureWeen, test added

2023-09-26 14:42 UTC, PureWeen approved these changes

2023-09-26 14:42 UTC, merged

2023-10-24 14:39 UTC, PureWeen commented
/backport to release/8.0.1xx-rc2

2023-10-24 15:00 UTC, PureWeen commented
/backport to release/8.0.1xx-rc2.1