[Windows] Fix tab colors not updating on add/remove
dotnet/maui pull request #17591
Opened 2023-09-22 21:51 UTC by Foda

### Description of Change

Fix tab colors not updating when adding or removing items

### Issues Fixed

(Partially) Fixes #17237

2023-09-25 15:36 UTC, jfversluis approved these changes, later dismissed
Verified by running the test locally that it passes. This should work automatically now that the Windows device tests have been merged in the pipeline from here on out.

This looks good to me!

2023-09-25 22:22 UTC, PureWeen requested changes
looks like text color still isn't quite updating when tab comes back 

![image](https://github.com/dotnet/maui/assets/5375137/03aa2f43-6a80-41db-b618-de495dad9f1d)

2023-09-26 20:51 UTC, PureWeen approved these changes, later dismissed

2023-09-26 20:55 UTC, PureWeen commented
Related issue
https://github.com/dotnet/maui/issues/17668

2023-10-26 17:24 UTC, Foda commented
/rebase

2025-03-25 08:22 UTC, jsuarezruiz commented
@Foda Could you rebase to fix conflicts?

2025-06-06 10:21 UTC, rmarinho commented
/rebase

2025-09-09 12:55 UTC, jfversluis commented
This PR seems stale and no response from the original author, its unlikely that we're moving this forward in the current state, so closing this for now. If someone still things this is something we need and/or wants to look into this, please let us know :)

Thanks!

2025-09-09 12:55 UTC, closed without merging