Wrap Image with a container on Windows so that it is centered with AspectFill
dotnet/maui pull request #17665
Opened 2023-09-26 19:04 UTC by japarson

### Description of Change
On Windows, we use [Microsoft.UI.Xaml.Controls.Image](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.image?view=windows-app-sdk-1.3) which has a [stretch](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.stretch?view=windows-app-sdk-1.3) property. When this property is set in WinUI, the image will not be centered. According to the WinUI team, this is intended behavior:

![image](https://github.com/dotnet/maui/assets/59936622/7424105a-b81d-4e10-96ef-511351d77d5f)

As you can see in the screenshot above, one workaround we can utilize is to wrap the image in a `Grid`. Luckily, we can utilize the existing [WrapperView](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Windows/WrapperView.cs) on Windows by adding a `ContainerView` to the Windows `ImageHandler`.

#### Before
![image](https://github.com/dotnet/maui/assets/59936622/92b5a8f3-c2f7-4742-bcc2-8f22bff52e15)

#### After
![image](https://github.com/dotnet/maui/assets/59936622/8b7da23f-3953-4527-bc58-b60faaa2d620)

### Issues Fixed
Fixes #10645

Copied from https://github.com/dotnet/maui/pull/15122

2023-10-06 17:56 UTC, emaf approved these changes, later dismissed

2023-10-06 20:16 UTC, hartez requested changes
We need to resolve our design discussion about how to handle remapping within Core before we can merge this. Scheduled a meeting, we'll update this as soon as we figure it out.

2023-10-09 19:51 UTC, PureWeen commented on src/Core/src/Handlers/Image/ImageHandler.Windows.cs
> +				ViewHandler.MapHeight(handler, view);
Once we merge [PR](https://github.com/dotnet/maui/pull/17918),  we can rebase this PR to use the new extention methods.

2023-12-21 16:48 UTC, PureWeen commented
/rebase

2024-03-27 22:01 UTC, PureWeen commented
For now let's just merge this without the updated extensions. 
And we can just fix those in post

2024-03-28 21:04 UTC, Foda commented
@japarson Could you please resolve conflicts and add a UI test? Thanks!

2024-04-22 17:57 UTC, japarson commented
> @japarson Could you please resolve conflicts and add a UI test? Thanks!

@Foda Test is added and conflicts are resolved.

2024-04-23 18:37 UTC, Foda approved these changes, later dismissed
LGTM

2024-05-13 13:28 UTC, jsuarezruiz commented on src/Controls/tests/UITests/snapshots/windows/Issue10645Test.png
With the changes in the UI Test runner, we need to regenerate the snapshot (now navigates directly to the issue page, and the NavigationBar will no be rendered).

2024-05-13 13:29 UTC, jsuarezruiz commented
/azp run

2024-05-13 13:36 UTC, jsuarezruiz commented on src/Controls/tests/UITests/snapshots/windows/Issue10645Test.png
Running a new build.

2024-08-16 17:49 UTC, PureWeen approved these changes, later dismissed

2024-08-17 21:22 UTC, PureWeen requested changes
screen shot for Issue10645Test is failing

@Foda can you check if we just need to update screen shot? or if something broke?

2024-08-20 18:22 UTC, PureWeen approved these changes

2024-08-21 09:26 UTC, merged