Correctly expand rows/columns when grid padding
dotnet/maui pull request #17750
Opened 2023-09-30 00:29 UTC by mattleibow

### Description of Change

When expanding star definitions, the targetSize
parameter contains the padding (which is
removed). However, the calculation for the
the GridMinimum[Width|Height]() also has the
padding which also needs to be removed.

### Issues Fixed

Fixes #16815

2023-10-02 16:59 UTC, hartez requested changes
Looks good, just make the test parameters clearer.

2023-10-02 16:59 UTC, hartez commented on src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
> +		public void StarRowsCalculateCorrectlyWhenGridWidthNearsMinWidth(double gridWidth, double v0W, double v1X)
```suggestion
		public void StarRowsCalculateCorrectlyWhenGridWidthNearsMinWidth(double widthConstraint, double view0ExpectedWidth, double view1ExpectedX)
```

2023-10-02 16:59 UTC, hartez commented on src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
> +		public void StarColsCalculateCorrectlyWhenGridHeightNearsMinHeight(double gridHeight, double v0H, double v1Y)
```suggestion
		public void StarColsCalculateCorrectlyWhenGridHeightNearsMinHeight(double heightConstraint, double view0ExpectedHeight, double view1ExpectedY)
```

2023-10-05 12:01 UTC, jsuarezruiz approved these changes

2023-10-05 15:58 UTC, emaf approved these changes

2023-10-06 15:55 UTC, hartez approved these changes

2023-10-06 20:04 UTC, merged

2023-10-24 01:43 UTC, mattleibow commented
/backport to net8.0

2023-10-24 15:07 UTC, PureWeen commented
/backport to release/8.0.1xx-rc2.1