Make Entitlements in Templates for MacCatalyst more consistent between debug and release configs.
dotnet/maui pull request #17833
Opened 2023-10-04 19:31 UTC by dustin-wojciechowski

### Description of Change
Make Entitlements in MacCatalyst Templates more consistent between debug and release configs. 

See [teams conversation](https://teams.microsoft.com/l/message/19:989ffa44998147aca4ceaf7482967668@thread.skype/1696009594958?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1696009594958&teamName=VS%20Client%20Experiences&channelName=MAUI%20%F0%9F%8C%BA&createdTime=1696009594958) for more context (MSFT only)

2023-10-05 17:58 UTC, Eilon reviewed
This definitely aligns with what I was looking for in our discussion. Can you confirm that you tested locally on a Mac in debug/release and native/hybrid to make sure there's nothing unexpected about using Sandbox in debug?

2023-10-07 17:43 UTC, dustin-wojciechowski commented
> This definitely aligns with what I was looking for in our discussion. Can you confirm that you tested locally on a Mac in debug/release and native/hybrid to make sure there's nothing unexpected about using Sandbox in debug?

Yes, I tested locally with two new maui-mobile and maui-blazor projects and there were no issues running the samples.

2023-10-09 11:26 UTC, jsuarezruiz submitted a review, later dismissed

2023-10-09 14:56 UTC, mattleibow reviewed
Is it possible to remove all the conditions in the templates and make all the items in the plist? For the dev tools, we can just comment it out and a user can uncomment if they want it. I would like to reduce the things in the csproj file.

2023-10-09 15:21 UTC, PureWeen requested changes
Currently this PR is targeting main (SR1) with a GA milestone. 
Can you please update the Milestone to SR1 or update the targeted branch to net8.0.

2023-10-09 18:43 UTC, dustin-wojciechowski commented
> Currently this PR is targeting main (SR1) with a GA milestone. Can you please update the Milestone to SR1 or update the targeted branch to net8.0.

Changed targeted branch to net8.0.

2023-10-11 21:48 UTC, mattleibow requested changes
I think this is almost ready, just need to remove the item in the csproj as it is already added.

2023-10-11 21:48 UTC, mattleibow commented on src/Templates/src/templates/maui-blazor/MauiApp.1.csproj
>    </PropertyGroup>
This should not be necessary as the globs will add it:

https://github.com/dotnet/maui/blob/81fd8f6a9bd5ed5d4b41bff5f370801323c90050/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.SingleProject.targets#L53

2023-10-11 21:48 UTC, mattleibow commented on src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
>    </PropertyGroup>
Same as above.

2023-10-12 04:38 UTC, mattleibow approved these changes

2023-10-12 18:05 UTC, PureWeen approved these changes

2023-10-12 18:26 UTC, PureWeen commented
/backport to release/8.0.1xx-rc2.1

2023-10-12 19:34 UTC, Eilon approved these changes
Much cleaner!!

2023-10-12 19:34 UTC, merged