Enable more legacy tests
dotnet/maui pull request #17931
Opened 2023-10-10 14:03 UTC by jfversluis

### Description of Change

Ignore the failing iOS tests for now on the legacy UI tests so that we can get the remaining tests going in an automated fashion.

2023-10-10 21:12 UTC, PureWeen requested changes
iOS tests seem like they didn't run
https://dev.azure.com/xamarin/public/_build/results?buildId=98547&view=results

2023-10-11 12:48 UTC, jfversluis commented on eng/devices/devices-shared.cake
> +	}
We had a case where we updated the UITest dependency and all iOS tests came up as inconclusive. For NUnit this still passes and so we thought: hooray, all green!

To make sure we notice something might be up, check the results and fail the test run if this scenario comes up.

2023-10-12 11:27 UTC, jfversluis commented on eng/devices/devices-shared.cake
> +	}
Moved this into a separate PR #17971

2023-10-12 11:27 UTC, jfversluis commented
@PureWeen as discussed, this PR as-is, moved the check for the tests not running to a separate PR here: #17971

2023-10-12 17:52 UTC, PureWeen commented
/rebase

2023-10-14 23:01 UTC, PureWeen approved these changes

2023-10-14 23:01 UTC, merged