MenuItem gets updated when IconImageSource changes - Fix 17210
dotnet/maui pull request #18119
Opened 2023-10-18 20:19 UTC by jm-goldacker

### Description of Change

I added an event handler method that subscribes to the `SourceChanged` event of the `MenuItem`'s `IconImageSource`.

When this event occurs, subscribers will be notified that the `IconImageSourceProperty` of the `MenuItem` changed - so the UI will update.

### Issues Fixed

Fixes #17210 

examples from public reproduction project repository, before swapping icons:
![image](https://github.com/dotnet/maui/assets/37597561/90973b5c-49d0-4434-a994-29fe92ed337c)

after swapping icons:
![image](https://github.com/dotnet/maui/assets/37597561/2b04fd54-e051-4ae8-b2a1-9493473f578c)

The examples can be found in the Maui.Controls.Sample project.

2023-10-18 20:27 UTC, jm-goldacker commented
The issue mentions "Binding does not work with glyph."

This is the corresponding code in the reproduction project:
`<MenuFlyoutItem.IconImageSource>
    <FontImageSource Glyph="{Binding Icon1}"  FontFamily="IconsFont" Color="Blue"/>
</MenuFlyoutItem.IconImageSource>`

That code will not render the glyph. The problem is the binding. 

I solved it by referencing the binding source:
`<MenuFlyoutItem.IconImageSource>
    <FontImageSource Glyph="{Binding BindingContext.Icon1, Source={x:Reference menuBarSamplePage}}" FontFamily="IconsFont"/>
</MenuFlyoutItem.IconImageSource>`

Is it intended to work like that?
If not, I will still have to put some work into this issue 😅

2025-01-27 18:46 UTC, mattleibow requested changes
Thanks for this PR! The fix looks right, but I think the issue you pointed out with the weird binding context may be because we are not properly propagating the context to menu items.

Are you still able to look at this PR? I know it has been a day or year... Let me know. I will try and be more responsive. Back in 2023, things were more crazy - now we got time to look at PRs :P

Some questions for the binding issue:
* Does binding things like text work?
* I wonder if you rebase things will be better - it has been over a year now
* Are you able to add a UI test to verify the menu has changed? This PR has a UI test for menu items that you can reference: https://github.com/dotnet/maui/pull/26886

Let me know if you still feel like working on this issue.

2025-02-01 19:06 UTC, jm-goldacker commented
Hi,
thanks for looking into the PR.

I would indeed like to continue working on this issue.

2025-09-09 13:00 UTC, jfversluis commented
Work was unfortunately not continued, if you still would want to do that, please let us know. Closing for now.

2025-09-09 13:00 UTC, closed without merging