[net8.0] Add NuGet package information
dotnet/maui pull request #18197
Opened 2023-10-20 15:00 UTC by mattleibow

### Description of Change

Add more detailed and correct information into the packages. Also make sure they all have icons.

| Before | After |
| :-: | :-: |
| ![before](https://github.com/dotnet/maui/assets/1096616/dc28fa96-a573-45e7-8789-83a1956a9fe2) | ![after](https://github.com/dotnet/maui/assets/1096616/bad6682a-9349-44e7-902b-70b1d95b5aa1) |

2023-10-20 15:33 UTC, Eilon requested changes
This looks great. I read all the text for all the packages and the grammar/spelling is good, and this is all way better than before.

I added a note about the icon per your chat.

2023-10-20 15:33 UTC, Eilon commented on src/BlazorWebView/src/Maui/Microsoft.AspNetCore.Components.WebView.Maui.csproj
> +  </PropertyGroup>
Looks like the AspNetCore packages all use the purple square .NET icon. I can't find where in the build it comes from, but you can go to https://nuget.info/packages/Microsoft.AspNetCore.Components.WebView/8.0.0-rc.2.23480.2 and download Icon.png, add to this repo, and reference that in the metadata here.

2023-10-20 15:40 UTC, hartez approved these changes, later dismissed

2023-10-20 15:40 UTC, hartez commented on src/Controls/src/NuGet/Controls.NuGet.csproj
> +		<Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. Using .NET MAUI, you can develop apps that can run on
```suggestion
		<Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. Using .NET MAUI, you can develop apps that can run on Android, iOS, macOS, Tizen, and Windows from a single shared codebase.</Description>
```

2023-10-20 15:40 UTC, hartez commented on src/Controls/src/NuGet/Controls.NuGet.csproj
> +		<Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. Using .NET MAUI, you can develop apps that can run on
I think technically both are correct, but AFAIK we use "codebase" in other places. This suggestion is 100% optional.

2023-10-20 15:53 UTC, davidbritch submitted a review, later dismissed
Approving because my feedback is real nit picking stuff.

One thing I noticed, and eventually stopped commenting on is application vs app. Some descriptions use app. Some use application. I've no preference. I just like consistency :)

2023-10-20 15:53 UTC, davidbritch commented on src/Controls/Foldable/src/Controls.Foldable.csproj
> +    <Description>Foldable or multi-screen device support for .NET Multi-platform App UI (.NET MAUI) apps.</Description>
Another nit pick: up until now it was always applications rather than apps.

2023-10-20 15:53 UTC, davidbritch commented on src/Controls/Maps/src/Controls.Maps.csproj
> +    <Description>Maps and mapping support for .NET Multi-platform App UI (.NET MAUI) apps.</Description>
Nit pick: apps again rather than applications. Either are good with me. I'm just pointing out the inconsistency.

2023-10-20 15:53 UTC, davidbritch commented on src/Controls/src/Build.Tasks/Controls.Build.Tasks.csproj
> +		<Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package only contains the MSBuild tasks and othe
Apps vs applications.

2023-10-20 15:53 UTC, davidbritch commented on src/Essentials/src/Essentials.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains a large collection of cross-p
```suggestion
    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains a collection of cross-platform APIs for working with device sensors and other features.</Description>
```

2023-10-20 15:53 UTC, davidbritch commented on src/Graphics/src/Graphics.Skia/Graphics.Skia.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains additional graphics and drawi
```suggestion
    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains additional graphics and drawing APIs for using the SkiaSharp graphics engine with .NET MAUI Graphics.</Description>
```

2023-10-20 15:53 UTC, davidbritch commented on src/Graphics/src/Graphics.Win2D/Graphics.Win2D.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains additional graphics and drawi
```suggestion
    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains additional graphics and drawing APIs for using the Win2D graphics engine with .NET MAUI Graphics. This package is no longer needed and all APIs are now also in the Microsoft.Maui.Graphics package.</Description>
```

2023-10-20 15:53 UTC, davidbritch commented on src/Graphics/src/Graphics/Graphics.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains a large collection of cross-p
```suggestion
    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains a collection of cross-platform graphics and drawing APIs.</Description>
```

2023-10-20 15:53 UTC, davidbritch commented on src/SingleProject/Resizetizer/src/Resizetizer.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains the image, font and raw asset
```suggestion
    <Description>.NET Multi-platform App UI (.NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. This package contains image, font and raw asset processing tools.</Description>
```

2023-10-20 15:53 UTC, davidbritch commented on src/Workload/Microsoft.Maui.Sdk/Microsoft.Maui.Sdk.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) SDK.</Description>
Doesn't really tell you the purpose of this package.

2023-10-20 15:53 UTC, davidbritch commented on src/Workload/Microsoft.NET.Sdk.Maui/Microsoft.NET.Sdk.Maui.csproj
> +    <Description>.NET Multi-platform App UI (.NET MAUI) workload manifest. Please do not reference directly.</Description>
```suggestion
    <Description>.NET Multi-platform App UI (.NET MAUI) workload manifest. Please do not reference this package directly.</Description>
```

2023-10-20 16:20 UTC, mattleibow commented
@davidbritch  I went with apps instead of applications as that is what all our concept docs say.

2023-10-20 18:28 UTC, Eilon approved these changes, later dismissed

2023-10-23 08:08 UTC, jfversluis submitted a review, later dismissed
Build fails with a bunch of these

> D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\BlazorWebView\src\Maui\Microsoft.AspNetCore.Components.WebView.Maui.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\BlazorWebView\src\Maui\Microsoft.AspNetCore.Components.WebView.Maui.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\BlazorWebView\src\Maui\Microsoft.AspNetCore.Components.WebView.Maui.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Graphics\src\Graphics.Skia\Graphics.Skia.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Graphics\src\Graphics.Skia\Graphics.Skia.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Graphics\src\Graphics.Skia\Graphics.Skia.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Core\src\Core.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Core\maps\src\Maps.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Core\maps\src\Maps.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Core\maps\src\Maps.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Controls\Maps\src\Controls.Maps.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Controls\Maps\src\Controls.Maps.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Controls\Maps\src\Controls.Maps.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057: The target "_MauiPackReadmeFile [D:\a\_work\1\s\src\Graphics\src\Graphics\Graphics.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:        [D:\a\_work\1\s\src\Graphics\src\Graphics\Graphics.csproj]
D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rtm.23519.6\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(214,11): error MSB4057:       SetVersions" does not exist in the project. [D:\a\_work\1\s\src\Graphics\src\Graphics\Graphics.csproj]

2023-10-23 10:56 UTC, rmarinho commented
/rebase

2023-10-23 19:13 UTC, mattleibow commented
![image](https://github.com/dotnet/maui/assets/1096616/3ef333b4-663c-428f-9eaf-d1b7c879384f)

2023-10-23 19:33 UTC, Eilon approved these changes

2023-10-23 21:45 UTC, rmarinho approved these changes

2023-10-23 22:22 UTC, merged

2023-10-24 14:37 UTC, PureWeen commented
/backport to release/8.0.1xx-rc2