Add device test for PR #18356
dotnet/maui pull request #18387
Opened 2023-10-26 19:07 UTC by emaf

### Description of Change

Tests for https://github.com/dotnet/maui/pull/18356

### Issues Fixed

N/A

2023-10-26 19:15 UTC, PureWeen approved these changes

2023-10-26 23:15 UTC, PureWeen requested changes
New test is failing on iOS

2023-10-27 06:20 UTC, jsuarezruiz commented
> New test is failing on iOS

CollectionViewItemsWithFixedWidthAndDifferentHeight
Assert.Equal() Failure: Values differ\nExpected: 2\nActual:   3

2023-11-03 20:18 UTC, emaf commented
@PureWeen @hartez I filed a new issue for the failure on iOS (https://github.com/dotnet/maui/issues/18517) and skipped that platform on this test

2023-11-06 23:18 UTC, PureWeen approved these changes

2023-11-06 23:18 UTC, merged