Fix broadcast receiver register on android 14.0/34+
dotnet/maui pull request #18520
Opened 2023-11-03 21:13 UTC by Redth

This adds a new helper method for registering broadcast receivers, which takes a bool for exporting the service or not, and on API 34 and higher, it calls the newer overload which takes the `ReceiverFlags` and passes the corresponding `NotExported` or `Exported` value to the bool parameter of the util method.

This allows us to call the right overload if we are on API 34 (Android 14.0) or newer where the declaration is required.

Also some older GetLocale()/SetLocale() methods are removed which were unused.

Fixes #17861

2023-11-03 21:21 UTC, Redth commented
I haven't been able to test on an Android 14.0 (API 34) device, and the documentation is not the clearest to me: If this receiver is listening for broadcasts sent from the system or from other apps—even other apps that you own—use the [RECEIVER_EXPORTED](https://developer.android.com/reference/androidx/core/content/ContextCompat#RECEIVER_EXPORTED()) flag. If instead this receiver is listening only for broadcasts sent by your app, use the [RECEIVER_NOT_EXPORTED](https://developer.android.com/reference/androidx/core/content/ContextCompat#RECEIVER_NOT_EXPORTED()) flag.

> If this receiver is listening for broadcasts sent from the system or from other apps—even other apps that you own—use the [RECEIVER_EXPORTED](https://developer.android.com/reference/androidx/core/content/ContextCompat#RECEIVER_EXPORTED()) flag. If instead this receiver is listening only for broadcasts sent by your app, use the [RECEIVER_NOT_EXPORTED](https://developer.android.com/reference/androidx/core/content/ContextCompat#RECEIVER_NOT_EXPORTED()) flag.

We are listening for system events, so it sounds like we should use `RECEIVER_EXPORTED` however it seems to work just fine with `RECEIVER_NOT_EXPORTED` on the simulator.

2023-11-03 21:24 UTC, mattleibow commented
https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter,%20java.lang.String,%20android.os.Handler)

> For apps targeting [Build.VERSION_CODES.UPSIDE_DOWN_CAKE](https://developer.android.com/reference/android/os/Build.VERSION_CODES#UPSIDE_DOWN_CAKE), either [RECEIVER_EXPORTED](https://developer.android.com/reference/android/content/Context#RECEIVER_EXPORTED) or [RECEIVER_NOT_EXPORTED](https://developer.android.com/reference/android/content/Context#RECEIVER_NOT_EXPORTED) must be specified if the receiver is not being registered for [system broadcasts](https://developer.android.com/guide/components/broadcasts#system-broadcasts) or a [SecurityException](https://developer.android.com/reference/java/lang/SecurityException) will be thrown.

2023-11-13 20:45 UTC, PureWeen submitted a review, later dismissed
I tested the connectivity sample in essentials and it no longer crashes with these changes

2023-11-13 21:38 UTC, mattleibow requested changes, later dismissed
Needs tests, will add.

2023-11-13 22:01 UTC, mattleibow approved these changes

2023-11-13 22:03 UTC, mattleibow commented
I tested on a Pixel 6 with Android 14 / API 34 and a Samsung A53 5G with Android 13 / API 33. I could reproduce the crash for Connectivity, and this PR fixed it. I did not observe crashes for Battery, and this PR does not seem to change anything.

I added some tests that confirmed my observations before & after the PR.

2023-11-13 22:08 UTC, PureWeen approved these changes

2023-11-13 22:11 UTC, mattleibow commented
Once this is merged, it should appear on the nightly feeds.

2023-11-14 09:46 UTC, merged

2023-11-15 15:51 UTC, Alex-Dobrynin commented
When this fix will be released? Today I've downloaded new VS with .net 8 and other updates and got this crash