[WinUI] Fix resizing CV rows when content size changed
dotnet/maui pull request #18553
Opened 2023-11-06 23:20 UTC by emaf

### Description of Change

When measuring the ItemContentControl we might not get the right value if the size of its content just changed. In order to ensure we get the up to date value, we first measure the content (to update DesiredSize), and then we measure the ItemContentControl.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/18078

2023-11-06 23:50 UTC, emaf commented
EZ mentioned this looks good :)

2023-11-20 10:34 UTC, krdmllr commented
Hi, since I raised the Bug, do you have an ETA when this will get merged/released?

2023-11-20 23:35 UTC, PureWeen requested changes

2023-11-20 23:35 UTC, PureWeen commented on src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
> +			var size = new WSize(width, height);
There are a couple things about this override that seem a little bit off to me.

- The layout call on line 311 is using VisualElement and it should probably be using `IView`
- It seems wrong that there's a layout call in this code at all, the layout call should probably be inside the `override arrange` ?


Like if I use the following code, the initial size is a bit weird but then once you start clicking the buttons it sizes correctly. 

I'm curious if there's a "Delete more code" solution here. 

```C#
protected override WSize MeasureOverride(WSize availableSize)
{
	if (_renderer == null)
	{
		return base.MeasureOverride(availableSize);
	}

	var width = ItemWidth == default ? availableSize.Width : ItemWidth;
	var height = ItemHeight == default ? availableSize.Height : ItemHeight;
	var size = new WSize(width, height);

	//if (this.Content is FrameworkElement content 
	//	&& CanMeasureContent(content) 
	//	&& (content.DesiredSize.Height != content.Height || content.DesiredSize.Width != content.Width))
	//{
	//	// Measure content to update its desired size if its Height/Width just changed
	//	content.Measure(size);
	//}

	var theSize = _renderer.VirtualView.Measure(size.Width, size.Height);
	var measuredSize = base.MeasureOverride(theSize.ToPlatform());
	var finalWidth = Max(measuredSize.Width, ItemWidth);
	var finalHeight = Max(measuredSize.Height, ItemHeight);
	var finalSize = new WSize(finalWidth, finalHeight);
	var frameworkElement = Content as FrameworkElement;
	var visualElement = _renderer.VirtualView as IView;
	var margin = _renderer.VirtualView.Margin;

	frameworkElement.Margin = WinUIHelpers.CreateThickness(margin.Left, margin.Top, margin.Right, margin.Bottom);
	//visualElement.Arrange(new Rect(0, 0, finalWidth, finalHeight));

	/*if (CanMeasureContent(frameworkElement))
	{
		frameworkElement.Measure(finalSize);
	}*/

	return finalSize;
}
```

2023-11-21 00:37 UTC, PureWeen commented on src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
> +			var size = new WSize(width, height);
Does this work?

```C#
/// <inheritdoc/>
protected override WSize ArrangeOverride(WSize finalSize)
{
	if (_renderer == null)
	{
		return base.ArrangeOverride(finalSize);
	}

	/*var width = ItemWidth == default ? finalSize.Width : ItemWidth;
	var height = ItemHeight == default ? finalSize.Height : ItemHeight;
	var size = new WSize(width, height);*/

	var result =  base.ArrangeOverride(finalSize);
	return result;
}

/// <inheritdoc/>
protected override WSize MeasureOverride(WSize availableSize)
{
	if (_renderer == null)
	{
		return base.MeasureOverride(availableSize);
	}

	var width = ItemWidth == default ? availableSize.Width : ItemWidth;
	var height = ItemHeight == default ? availableSize.Height : ItemHeight;
	var size = new WSize(width, height);
	var frameworkElement = Content as FrameworkElement;


	// Do we really need this margin code?
	var margin = _renderer.VirtualView.Margin;
	frameworkElement.Margin = WinUIHelpers.CreateThickness(margin.Left, margin.Top, margin.Right, margin.Bottom);

	var measuredSize = base.MeasureOverride(size);
	var finalWidth = Max(measuredSize.Width, ItemWidth);
	var finalHeight = Max(measuredSize.Height, ItemHeight);
	var finalSize = new WSize(finalWidth, finalHeight);

	return finalSize;
}
```

2023-11-21 15:53 UTC, PureWeen commented on src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
> +			var size = new WSize(width, height);
Alternate thoughts
https://github.com/dotnet/maui/pull/18932

2023-11-22 16:32 UTC, emaf commented
Closing in favor of https://github.com/dotnet/maui/pull/18932

2023-11-22 16:32 UTC, closed without merging