Arrange content based on arrangement bounds rather than viewport bounds
dotnet/maui pull request #18586
Opened 2023-11-07 20:24 UTC by hartez

### Description of Change

The final content arrangement was being done using the viewport bounds, which are offset by the scroll distance. The arrangement _should_ be done by the ScrollView's arrangement bounds, as passed into the `CrossPlatformArrange()` method.

### Issues Fixed

Fixes #18513

2023-11-07 21:12 UTC, PureWeen requested changes
Tested against our template and it looks like the scroll bars return

https://github.com/dotnet/maui/tree/fix-18513-repro

2023-11-08 15:02 UTC, PureWeen requested changes
D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.iOS.cs(350,8): error CS0128: A local variable or function named 'contentSize' is already defined in this scope [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net8.0-maccatalyst]
D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.iOS.cs(348,32): error CS0104: 'Point' is an ambiguous reference between 'System.Drawing.Point' and 'Microsoft.Maui.Graphics.Point' [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net8.0-ios]
D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.iOS.cs(350,8): error CS0128: A local variable or function named 'contentSize' is already defined in this scope [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net8.0-ios]
    36 Warning(s)
    4 Error(s)

2023-11-09 10:32 UTC, PureWeen commented
/azp run

2023-11-09 17:57 UTC, PureWeen commented
/rebase

2023-11-09 18:37 UTC, tj-devel709 approved these changes, later dismissed
I applied this PR and was able to see that my scrollviews that used to come too far down on the screen are respecting the bottom safe areas as I would expect!

2023-11-10 13:13 UTC, PureWeen approved these changes

2023-11-10 17:58 UTC, Redth approved these changes

2023-11-13 00:52 UTC, merged