Appshell item template
dotnet/maui pull request #18615
Opened 2023-11-08 08:45 UTC by licon4812

### Description of Change

This PR adds AppShell item templates so that users can add an Appshell to their application if they started with a blank project

2023-11-08 17:07 UTC, Eilon requested changes
Hi, I left a few comments in this PR, but we also need to verify that this feature aligns with scenarios that we want to support. Tagging @PureWeen to confirm that.

2023-11-08 17:07 UTC, Eilon commented on src/Templates/src/templates/maui-appshell-csharp/NewAppshell1.cs
> +		shell = new Shell()
I think this field is not declared anywhere?

2023-11-08 17:07 UTC, Eilon commented on src/Templates/src/templates/maui-appshell-xaml/NewAppshell1.xaml.cs
> +		InitializeComponent();
Formatting here is mixing tabs and spaces.

2023-11-08 17:07 UTC, Eilon commented on src/Templates/src/Microsoft.Maui.Templates.csproj
Were any changes to this file deliberate? If not, please undo the changes to this file.

2023-11-08 17:07 UTC, Eilon commented on src/Templates/src/templates/maui-appshell-csharp/NewAppshell1.cs
> +				new FlyoutItem{ Title = "Cats" }
I suggest instead of cats/dogs, to use a more generic `Item 1` and `Item 2`

2024-01-19 07:56 UTC, mattleibow commented
/azp run

2024-02-10 00:01 UTC, PureWeen commented
@jfversluis @davidortinau  thoughts?

2024-02-12 15:59 UTC, davidortinau commented on src/Templates/src/templates/maui-appshell-csharp/NewAppshell1.cs
> +			Children =
Same comment as the XAML version, we shouldn't provide code that doesn't work as expected, but instead a sample of code that would work when implemented specific to the app. 

Also this isn't a valid implementation. It should look something like this:

```csharp
public class MyShell : Shell
{
	public MyShell()
	{
		this.Items.Add(new FlyoutItem
		{
			Title = "Dashboard",
			Items =
			{
				new ShellContent
				{
					ContentTemplate = new DataTemplate(typeof(DashboardPage)),
				}
			}
		});

		this.Items.Add(new FlyoutItem
		{
			Title = "Add Vocab",
			Items =
			{
				new ShellContent
				{
					ContentTemplate = new DataTemplate(typeof(AddVocabularyPage)),
				}
			}
		});
	}
}
```

2024-02-12 16:46 UTC, davidortinau commented
Generally I'm okay with having item templates for this, however we should consider if we want to promote the notion of using multiple Shells in a single project. What we have been seeing is devs using multiple Shells for scenarios that are better achieved with the features of a single Shell using the visibility and enabled properties. For example, swapping shell implementations on MainPage is not performant compared to using those properties.

2024-02-12 22:48 UTC, licon4812 commented
Maybe have the appshell as an option in the project creation instead of an item template?

2024-02-14 09:41 UTC, jfversluis commented
Let's take a step back: what is the thing we're trying to solve with this? What triggered you @licon4812 to implement this?

I don't think we ever heard much ask for adding this by other users? Granted, this will be something that is extra and will not bother people unless they go looking for it. On the other hand, we will be the ones having to maintain this and once it's in there, its hard to remove it again.

2024-02-14 09:46 UTC, licon4812 commented
Basically, I just want an option to add a shell to a project IF the project was created without one. Basically just a minor thing

2024-02-14 10:03 UTC, licon4812 commented
@jfversluis  that is a very good point, I was basically just wanting a time savour, which might already exist in plugins anyway.

2024-02-16 10:12 UTC, jfversluis commented
All things considered I don't think this is something we would want to do right now. But again: your efforts and point of view are appreciated. Looking forward to your next contribution!

2024-02-16 10:12 UTC, closed without merging