[Testing] Added UI Test for manual test D13
dotnet/maui pull request #18710
Opened 2023-11-13 09:34 UTC by jsuarezruiz

### Description of Change

Added UI Test for manual test D13.

### Issues Fixed

Fixes #18703

2023-11-26 22:59 UTC, PureWeen requested changes

2023-11-26 22:59 UTC, PureWeen commented on src/Controls/tests/UITests/snapshots/ios/EditorTextAlignmentWorks.png
Can't see the bottom editor field on android or iOS. I wonder if we could use device tests to locate the text somehow? Or maybe these editors fields can be side by side?

2023-11-29 14:54 UTC, jsuarezruiz commented on src/Controls/tests/UITests/snapshots/ios/EditorTextAlignmentWorks.png
Applied changes to the sample to capture all the cases in the snapshot.
![Screenshot_1701269609](https://github.com/dotnet/maui/assets/6755973/ff476c30-5e42-4216-b86f-5a723a74008f)

2023-11-29 14:55 UTC, jsuarezruiz commented on src/Controls/tests/UITests/snapshots/ios/EditorTextAlignmentWorks.png
NOTE: Waiting the build to generate the new snapshots on CI.

2023-11-29 18:46 UTC, hartez submitted a review, later dismissed

2024-03-14 12:43 UTC, jfversluis commented
We're focussing on other areas of the testing right now. Lets close this in the meantime and revisit later.

2024-03-14 12:43 UTC, closed without merging