Update readme with latest blog
dotnet/maui pull request #18763
Opened 2023-11-15 16:37 UTC by davidortinau

Also removed the older links

2023-11-15 18:26 UTC, PureWeen requested changes

2023-11-15 18:26 UTC, PureWeen commented on README.md
> +* November 14, 2023 - [Announcing .NET MAUI in .NET 8]([https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-rc-2/](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in
```suggestion
* November 14, 2023 - [Announcing .NET MAUI in .NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8/)
```

2023-11-15 18:54 UTC, PureWeen approved these changes

2023-11-16 15:14 UTC, PureWeen commented
/rebase

2023-11-16 15:15 UTC, PureWeen approved these changes

2023-11-16 19:31 UTC, jfversluis approved these changes

2023-11-17 01:13 UTC, merged