[iOS] Set text color of unselected TabbedPage tabs
dotnet/maui pull request #18777
Opened 2023-11-16 00:44 UTC by emily-curry

### Description of Change

Currently, the text color of unselected tabs is set to a internal default value and cannot be controlled. This is a regression from the .NET7 versions of MAUI, where it matched the icon color of the tab. This change updates the iOS-specific code for TabbedPage so that the text color is set to `UnselectedTabColor`.

### Issues Fixed

https://github.com/dotnet/maui/issues/18775

2023-11-16 00:45 UTC, emily-curry commented
@dotnet-policy-service agree

2024-04-17 17:15 UTC, dustin-wojciechowski commented
Hi @emily-curry, I just pulled this down and tried testing it out against the reproduction steps using maui-samples in the related issue and it doesn't seem to be working. 

Here's what I got:

On Main Branch:

https://github.com/dotnet/maui/assets/89540402/c3f2bdde-369c-4bde-ac83-0c0c747cdef2

On this branch:
https://github.com/dotnet/maui/assets/89540402/7ab7db41-d268-4bde-ba3d-1084323b2b78

Would you mind pulling this down again and taking another look at it?  Maybe something got lost in translation bringing the repro in. Thanks! :)

2024-04-17 17:17 UTC, dustin-wojciechowski requested changes

2024-06-04 06:42 UTC, jsuarezruiz commented
/azp run

2024-09-17 16:34 UTC, closed without merging