Allow GesturePlatformManager to be created for views with null window…
dotnet/maui pull request #18938
Opened 2023-11-21 19:45 UTC by artemvalieiev

### Description of Change

In the case of Maui Embedding, there is no window, and the gesture manager is always skipping the initialization of PlatformManager.
My changes allow a GestureManager to be created with a null window. I also keep the behavior of recreating/clearing the GesturePlatformManager when the window is removed or replaced.

### Issues Fixed
Fixes [[regression/8.0.0] TapGestureRecognizers not working in maui embedded](https://github.com/dotnet/maui/issues/17948)

2023-11-22 22:47 UTC, PureWeen requested changes
I tested through this a bit, and it looks like it works. 

I'd like to figure out a more overall fix that we can apply where we are able to actually set a window of some sort for embedded scenarios. 

There are a few cases where that's going to be relevant in order to fix this overall. For example, loaded/unloaded events are also broken currently on embedded. 

If we still don't have a great fix in the SR2 timeline, then I think it'd be worth merging this and possibly doing something similar for loaded/unloaded.

2023-12-04 16:12 UTC, Redth commented
We have this issue: https://github.com/dotnet/maui/issues/1718 which tracks the concept a bit.  I think we can revisit the bigger picture in an upcoming sprint soon to see what changes we would need to make and scope the effort for doing this the 'right way'.

2023-12-06 21:22 UTC, mattleibow requested changes

2023-12-11 18:45 UTC, mattleibow commented
Added this to the larger effort for next year to make embedding work better in all cases: https://github.com/dotnet/maui/issues/1718

2023-12-11 18:45 UTC, mattleibow commented
/azp run

2023-12-11 22:23 UTC, mattleibow approved these changes

2023-12-11 22:49 UTC, PureWeen approved these changes
@artemvalieiev thank you for this PR!

This is a great way for us to resolve this issue until we can build a better embedding story. 

From what I can tell, we only regressed gestures between net7/net8. Other areas, like unloaded and loaded, were unfortunately never working. 

We are actively working on the overall story here. These changes make sense until we can provide a better overall fix.

2023-12-11 22:54 UTC, merged