Update ShellSectionRenderer.cs
dotnet/maui pull request #18945
Opened 2023-11-22 07:44 UTC by 1c3f0x84

[Fix crash navigating in Shell and trying to get the navbar visibility](https://github.com/xamarin/Xamarin.Forms/pull/14689)

2023-11-22 17:17 UTC, dpozimski approved these changes
sounds good

2023-11-28 23:17 UTC, hartez submitted a review, later dismissed

2023-12-01 15:40 UTC, jfversluis commented
/azp run

2023-12-01 15:41 UTC, jfversluis requested changes
Some minor things, otherwise looks good!

2023-12-01 15:41 UTC, jfversluis commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
> +				if(element != null)
```suggestion
				if (element is not null)
```

2023-12-01 15:41 UTC, jfversluis commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
> +				bool navBarVisible = false;
```suggestion
				bool navBarVisible;
```

2023-12-02 12:23 UTC, jfversluis commented
/azp run

2023-12-02 12:37 UTC, jfversluis approved these changes

2023-12-04 08:13 UTC, merged

2023-12-04 08:14 UTC, jfversluis commented
Thank you for your contribution @1c3f0x84 !

2023-12-10 15:16 UTC, dpozimski commented
> I just stumbled on this bug myself in .NET 7. Is there a workaround, or is it a case of waiting for the next service release?

Tried to manually implement ShellSectionRenderer with proper fix but some members and methods are internal visible in MAUI assembly.

Would be great if someone found solution for this.

2023-12-13 13:40 UTC, jeff-eats-pubsubs commented
Just encountered this in .NET 8