[iOS] Fix Flyout Header breaking clicking over items
dotnet/maui pull request #19125
Opened 2023-11-30 01:57 UTC by emaf

### Description of Change

The Flyout Header height was being defined as `ArrangedHeaderViewHeightWithNoMargin` + `HeaderTopMargin`, but the `HeaderView.MeasuredHeight` (value on which `ArrangedHeaderViewHeightWithNoMargin` is based on) does include the margin so we were accounting for it twice and making the header go over the items below it, making them not clickable. When there is no margin, `HeaderTopMargin` represents the safe area and it should not be accounted for either.

Also renamed `ArrangedHeaderViewHeightWithNoMargin` and `MeasuredHeaderViewHeightWithNoMargin`, to `ArrangedHeaderViewHeightWithMargin` and `MeasuredHeaderViewHeightWithMargin`, since both include the top margin value: https://github.com/dotnet/maui/blob/main/src/Core/src/Layouts/LayoutExtensions.cs#L27.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/17965

2023-11-30 13:13 UTC, jsuarezruiz reviewed
I think something is missing based on the build errors.

```
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Shell\ShellFlyoutTests.iOS.cs(38,11): error CS0103: The name 'OpenFlyout' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net8.0-maccatalyst]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Shell\ShellFlyoutTests.iOS.cs(39,30): error CS0103: The name 'GetFlyoutPlatformView' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net8.0-maccatalyst]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Shell\ShellFlyoutTests.iOS.cs(45,58): error CS0103: The name 'GetSafeArea' does not exist in the current context [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net8.0-maccatalyst]
    3 Error(s)
```

2023-12-07 23:16 UTC, emaf commented
Skipping new test cases for Android since there is a bug that makes those fail. https://github.com/dotnet/maui/pull/19303 fixes that problem and re-enables the tests. It's a draft PR just because it depends on this one and needs to be rebased once this is merged so it only contains the Android specific fix.

2023-12-12 21:32 UTC, PureWeen requested changes
It looks like when you set Flyout Header Behavior to scroll it's also collapsing while it scrolls

![image](https://github.com/dotnet/maui/assets/5375137/58899e54-da77-4b8b-abec-6551e45f79b7)

After scroll

![image](https://github.com/dotnet/maui/assets/5375137/a2609b9e-ffa7-48a7-b84b-edc9c5c21151)

2023-12-15 16:25 UTC, emaf commented
> It looks like when you set Flyout Header Behavior to scroll it's also collapsing while it scrolls
> 
> ![image](https://private-user-images.githubusercontent.com/5375137/290009308-58899e54-da77-4b8b-abec-6551e45f79b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc3ODIsIm5iZiI6MTcwMjY1NzQ4MiwicGF0aCI6Ii81Mzc1MTM3LzI5MDAwOTMwOC01ODg5OWU1NC1kYTc3LTRiOGItYWJlYy02NTUxZTQ1Zjc5YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTYyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZmZmFkMTgzYTQ5MzNmMDhhODJjYmE0M2ZjOWRmNzY4YTkyOTdmM2QyOTJjNWRmZWEzODdlMmU0MzRmODY0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2wx4n8Xe8uEDo4beMBF6EhyBhHsYl_40IR72lnKBECI)
> 
> After scroll
> 
> ![image](https://private-user-images.githubusercontent.com/5375137/290009272-a2609b9e-ffa7-48a7-b84b-edc9c5c21151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc3ODIsIm5iZiI6MTcwMjY1NzQ4MiwicGF0aCI6Ii81Mzc1MTM3LzI5MDAwOTI3Mi1hMjYwOWI5ZS1mZmE3LTQ4YTctYjg0Yi1lZGM5YzVjMjExNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTYyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTIwNDlhZGU4ODIzNWI3NzgwZGMxZjdhOTAzZmUyYzZjZTc1Y2E0NTQ0YjcwOTc5MzFmNzBmMDYxNDM2ZTQ3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dK8PMVTy-TOx5QKd1CqLpWnVeW7qVjdEtge6KVfzGlc)

This is now fixed by https://github.com/dotnet/maui/pull/19125/commits/52c5ae99769c7ead1a96fe5a15c4f6c8fa7eb1b6

2023-12-15 21:13 UTC, emaf commented
> This is now fixed by [52c5ae9](https://github.com/dotnet/maui/commit/52c5ae99769c7ead1a96fe5a15c4f6c8fa7eb1b6)

Removed that commit. After chatting with @PureWeen, this seems to be the right behavior for now, since we don't have a bindlable property that would let us know if the `IgnoreSafeArea` property is explicitely set.

2024-01-08 19:18 UTC, PureWeen commented
/rebase

2024-01-09 00:06 UTC, PureWeen approved these changes

2024-01-09 01:32 UTC, merged