Clean up / Linq removal
dotnet/maui pull request #19260
Opened 2023-12-06 18:11 UTC by imememani

### Description of Change

Clean up (using switch in place of if chain) for better readability and used more up to date .NET syntax as well as removing the usage of LINQ.

### Issues Fixed

N/A

Fixes #

N/A

2023-12-06 21:59 UTC, hartez requested changes

2023-12-06 23:43 UTC, affableashish commented
[Switch expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression) are much cleaner IMHO.

I recommend changing your switch statements to:

```c#
return strValue switch
{
    _ when Compare(nameof(Linear)) => Linear,
    _ when Compare(nameof(SinIn)) => SinIn,
    //  and so on...
    _ => "put default value here"
};
```

And add this local method for case insensitive comparison:
```c#
bool Compare(string right) => string.Equals(strValue, right, StringComparison.InvariantCultureIgnoreCase);
```

2023-12-10 18:07 UTC, imememani commented on src/Core/src/Converters/EasingTypeConverter.cs
> +					return nameof(Linear);
You are 100% correct, I've fixed the return value.

2023-12-10 18:09 UTC, imememani commented on src/Core/src/Converters/EasingTypeConverter.cs
> +			switch (easing)
Fixed, it should now take this into account, thanks!

2023-12-10 18:10 UTC, imememani commented
@affableashish Great suggestion, it does look much more readable and allows case to be ignored, I've pushed some changes to factor the suggestions in.

2024-01-04 18:32 UTC, albyrock87 commented
Is there a reason to not use `Enum.TryParse` (with case-insensitive bool parameter) and `ToString` instead of the two switch statements?

2024-06-06 14:20 UTC, mattleibow commented
/rebase

2024-06-06 15:25 UTC, mattleibow commented
/azp run

2024-06-06 15:29 UTC, mattleibow approved these changes

2024-06-06 17:20 UTC, PureWeen approved these changes

2024-06-07 06:25 UTC, merged