WarnAsErrors. wip. don't merge
dotnet/maui pull request #19337
Opened 2023-12-11 14:17 UTC by StephaneDelcroix

### Description of Change

### Issues Fixed

Fixes #

2023-12-13 16:39 UTC, rmarinho requested changes

2023-12-14 07:50 UTC, StephaneDelcroix commented on src/Controls/src/Build.Tasks/XamlCTask.cs
> +			Context.NoWarn = noWarn?.Split([';'], StringSplitOptions.RemoveEmptyEntries).Select(s => {
both test and sample projects are using it, so testing it. we could add a msbuild test, but msbuild tests are slooooooooow

2023-12-15 11:53 UTC, rmarinho commented on src/Controls/src/Build.Tasks/XamlCTask.cs
> +			Context.NoWarn = noWarn?.Split([';'], StringSplitOptions.RemoveEmptyEntries).Select(s => {
Ok I was more talking in testing like `XC010R`  as a warning error, it should skip , but a test would be good to make sure :) But not blocking on this.

2023-12-18 11:55 UTC, rmarinho approved these changes

2023-12-18 11:55 UTC, merged