Disable failing semantic tests on iOS
dotnet/maui pull request #19344
Opened 2023-12-11 21:09 UTC by mattleibow

### Description of Change

Test are failing, so skip for now until we get a green build.

### Issues Fixed

Fixes #19122

2023-12-11 21:13 UTC, mattleibow commented
These tests need to be re-enabled again asap: https://github.com/dotnet/maui/issues/19345

2023-12-12 10:26 UTC, jfversluis requested changes
See internal chat. I wonder if these are actually worth disabling.

2023-12-12 11:57 UTC, rmarinho approved these changes

2023-12-12 11:58 UTC, rmarinho commented
LEt's see if it helps we can always revert this.

2023-12-12 12:26 UTC, jfversluis approved these changes

2023-12-12 12:26 UTC, merged