Make `PointerOver` to have higher priority than `Focused` state
dotnet/maui pull request #19812
Opened 2024-01-10 21:08 UTC by MartyIX

### Description of Change

This is just an idea how to fix #19752. I'm very much unsure whether:

* #19752 is actually a bug or if it is "by design"
* whether this is possibly a good approach or not.

I figured that creating a PR is the easiest way to demonstrate what I mean.

* `main` behavior: 
    ![Animation](https://github.com/dotnet/maui/assets/203266/0ccdb1d6-aac9-4967-a32a-a171e78e2bc2)
* PR's behavior:  
    ![Animation](https://github.com/dotnet/maui/assets/203266/e8731f10-7b32-4a73-948e-c6ab5d8cb01b)

btw: #11840 was merged and it changed `VisualElement` file like this: https://github.com/dotnet/maui/pull/11840/files#diff-2863605ee57ca6009796676e9d6d910295c5e1866866797d219268c93c79491b. Maybe @redth can chime in with some feedback.

### Issues Fixed

Fixes #19752

2024-06-06 20:42 UTC, Foda submitted a review, later dismissed
LGTM -- please revert the main page changes before merging.

2024-06-06 21:44 UTC, Foda approved these changes, later dismissed

2024-06-12 15:15 UTC, jsuarezruiz commented
/azp run

2025-01-28 16:28 UTC, mattleibow approved these changes

2025-01-28 16:29 UTC, mattleibow requested changes
Needs UI tests. The sandbox sample you had was good.

2025-01-28 22:29 UTC, PureWeen commented
> > Needs UI tests. The sandbox sample you had was good.
> 
> I think that @PureWeen was against the approach of this PR.
> 
> I did try to add a UI test but I'm unable to finish it because I'm not sure how to make the first button to be focused on Windows. @jsuarezruiz Would you know please?

@mattleibow usually with windows don't they add new states that are suffixed with PointerOver?

Are we worried about this being a breaking change or unexpected?

If I remember correctly, I don't think WinUI, for example, ever uses Focus for a VSM

2025-01-30 14:47 UTC, mattleibow commented
I think this PR and description actually points out the issue here: https://github.com/dotnet/maui/pull/27477 but the TL;DR is that the focus states are supposed to be in a separate group so that a button can both be focused AND be pointer over.

Thougts?

2025-01-30 15:53 UTC, mattleibow commented
I just copied the WinUI code, but that does not mean that it is the only way.

Since the code I have just typed now is totally different to anything we have, let's move the discussion to https://github.com/dotnet/maui/pull/27477

2025-03-06 14:30 UTC, closed without merging