Optimize IndexOf lookups
dotnet/maui pull request #19963
Opened 2024-01-18 06:37 UTC by symbiogenesis

This extension method in Core is referenced in at least 19 places.

With this change, the performance in some cases is orders of magnitude better.

https://dotnetfiddle.net/Anb4rA

2024-01-18 12:30 UTC, jsuarezruiz submitted a review, later dismissed

2024-01-18 14:18 UTC, jonathanpeppers requested changes
It looks like you wrote a manual benchmark instead of using BenchmarkDotNet.

Can you add a benchmark for this change? and add it to this PR?

https://github.com/dotnet/maui/tree/main/src/Core/tests/Benchmarks/Benchmarks

Then let us know your results before/after. Thanks!

2024-01-18 14:58 UTC, StephaneDelcroix submitted a review, later dismissed

2024-01-18 15:59 UTC, symbiogenesis commented
Before:

```
| Method         | Mean     | Error     | StdDev    | Gen0      | Allocated |
|--------------- |---------:|----------:|----------:|----------:|----------:|
| IndexOfList    | 5.500 ms | 0.1088 ms | 0.1990 ms | 5093.7500 |  45.78 MB |
| IndexOfArray   | 5.245 ms | 0.1018 ms | 0.1524 ms | 5093.7500 |  45.78 MB |
| IndexOfHashSet | 5.820 ms | 0.1139 ms | 0.2595 ms | 5093.7500 |  45.78 MB |
```

After:

```
| Method         | Mean        | Error      | StdDev     | Gen0      | Allocated  |
|--------------- |------------:|-----------:|-----------:|----------:|-----------:|
| IndexOfList    |    89.60 us |   1.777 us |   1.975 us |         - |          - |
| IndexOfArray   |    89.87 us |   1.551 us |   1.375 us |         - |          - |
| IndexOfHashSet | 5,479.40 us | 107.325 us | 173.310 us | 5093.7500 | 48000043 B |
```

2024-01-18 16:00 UTC, jonathanpeppers approved these changes
Awesome! Thank you!

I will put this on the list for some far future blog post. 😄

2024-01-19 07:47 UTC, mattleibow approved these changes

2024-01-19 07:47 UTC, mattleibow commented
/azp run

2024-01-19 10:30 UTC, merged