Make sure to await async test asserts
dotnet/maui pull request #19994
Opened 2024-01-19 08:04 UTC by mattleibow

### Description of Change

Await the async methods.

2024-01-19 08:06 UTC, StephaneDelcroix submitted a review, later dismissed

2024-01-19 12:32 UTC, rmarinho requested changes
Build is failing, missing using for Task

2024-01-19 19:20 UTC, mattleibow commented
> Was this not noticed because there was no warning or does MSVS warn about missing await?

NO, this was from your comment on another PR. But, my IDE does not report this - even after removing all cases of NoWarn... I ran a build and nothing either. Not sure why it was allowed - I tested in normal code and no warnings. Even CI is set to error on warning yet it builds?

2025-01-27 18:50 UTC, mattleibow commented
Closing this as it is out of date and other PRs have been merged. If we have any still remaining, we can either open smaller PRs for quick reviews and/or open another issue.

2025-01-27 18:50 UTC, closed without merging