Batch CollectionChanged events via ObservableRangeCollection
dotnet/maui pull request #20036
Opened 2024-01-21 09:42 UTC by symbiogenesis

There are a bunch of places where we were doing some kind of bulk update on an ObservableCollection

By pulling in the ObservableRangeCollection from the XamarinCommunityToolkit and MvvmHelpers that is maintained by @jamesmontemagno we can see that there is some significant performance improvement to be had.

I created a related benchmark file in my [other PR](https://github.com/dotnet/maui/pull/19982) and when I run it today I get the following:

Before:

| Method         | Mean     | Error    | StdDev   | Median   | Gen0      | Gen1      | Gen2     | Allocated |
|--------------- |---------:|---------:|---------:|---------:|----------:|----------:|---------:|----------:|
| ChangeContent  | 25.35 ms | 0.506 ms | 1.088 ms | 24.93 ms | 2437.5000 |  500.0000 | 187.5000 |  20.61 MB |
| ChangeTemplate | 76.63 ms | 1.485 ms | 1.651 ms | 76.57 ms | 7285.7143 | 7142.8571 | 142.8571 |  65.39 MB |

After:

| Method         | Mean      | Error     | StdDev   | Median    | Gen0      | Gen1      | Gen2     | Allocated |
|--------------- |----------:|----------:|---------:|----------:|----------:|----------:|---------:|----------:|
| ChangeContent  |  9.884 ms | 0.5224 ms | 1.507 ms |  9.072 ms |  828.1250 |  484.3750 | 171.8750 |   6.04 MB |
| ChangeTemplate | 77.759 ms | 1.5091 ms | 1.797 ms | 77.525 ms | 7285.7143 | 7142.8571 | 142.8571 |  65.39 MB |

2024-01-25 17:27 UTC, symbiogenesis commented
@jonathanpeppers

I followed your advice and did some profiling. My speedscope results looked garbled and I couldn't get much knowledge out of PerfView except to see that there were tons and tons of threads. But Visual Studio memory profiling was intuitive. Still learning the tools.

While running the sample app in [this branch](https://github.com/symbiogenesis/Maui.DataGrid/tree/memory-test
) of my open source DataGrid, just scroll a lot.

Or use the settings to try to toggle whether pagination is enabled, multiple times.

This code is not using any platform-specific code, and shouldn't be super slow. The memory profiling showed tons of `ItemTemplateContext` objects and calls from ObservableItemTemplateCollection. 

I already had this PR open to address this kind of issue involving `ObservableCollection`s. So I knew that batching the CollectionChanged events was the right approach.

And this probably explains seeing tons of threads in PerfView, because each CollectionChanged event was probably running in its own thread.

I could write a benchmark to try to prove that this is a better approach by orders of magnitude on large collections, but that one is Windows-specific and writing a Windows platform benchmark requires creating another project.

2024-01-26 11:11 UTC, AlleSchonWeg commented
Hi @symbiogenesis 
could you make the ObservableRangeCollection public? I missed this type of collection in MAUI. In XF we had such type in the xct.

2024-01-26 17:26 UTC, symbiogenesis commented
> Hi @symbiogenesis could you make the ObservableRangeCollection public? I missed this type of collection in MAUI. In XF we had such type in the xct.

That would be an API change that would need to be approved by the MAUI team. If they like this PR then the code will be there for them to expose as public whenever they like.

2024-01-26 17:29 UTC, symbiogenesis commented
In reality, ObservableCollection itself should be updated to expose ranged operations, and this is one of the most-requested .NET features for years.

https://github.com/dotnet/runtime/issues/18087

2024-06-06 18:05 UTC, Foda commented
This all looks fine to me, thoughts @PureWeen?

2024-07-11 00:43 UTC, PureWeen commented
/azp run

2024-07-24 01:36 UTC, symbiogenesis commented
Need to rerun tests

2024-07-24 16:30 UTC, PureWeen commented
/azp run

2024-10-05 16:07 UTC, symbiogenesis commented
Is this good to merge?

2024-11-27 12:37 UTC, rmarinho commented
/azp run

2024-11-27 12:37 UTC, rmarinho requested changes
Do we have some kind of benchmark to show numbers of performance improvements ?

2025-09-09 13:09 UTC, jfversluis commented
No response from original author, and stale by now. Closing for the time being, please let us know if you want to continue working on this, thanks!

2025-09-09 13:09 UTC, closed without merging