Implemented ios:Slider.UpdateOnTap
dotnet/maui pull request #20124
Opened 2024-01-24 00:04 UTC by kubaflo

### Description of Change

I implemented the ios:Slider.UpdateOnTap property in the same way it has been implemented in Xamarin Forms

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20098

https://github.com/dotnet/maui/assets/42434498/ce5397cc-4106-4f81-8162-35bfd0183885

2024-01-26 12:08 UTC, jsuarezruiz reviewed
Could you include a sample to allow check/test the platform specific here: https://github.com/dotnet/maui/tree/main/src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS?

2024-01-26 12:19 UTC, kubaflo commented
@jsuarezruiz sure I will do it later today

2024-01-27 12:30 UTC, kubaflo commented
@jsuarezruiz the sample page has already been in the code https://github.com/dotnet/maui/blob/main/src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSSliderUpdateOnTapPage.xaml

2024-02-11 21:53 UTC, PureWeen commented on src/Controls/src/Core/Slider/Slider.iOS.cs
> +﻿#nullable disable
Agreed, don't worry about putt this on any new files

2024-02-12 00:12 UTC, kubaflo commented on src/Controls/src/Core/Slider/Slider.iOS.cs
> +﻿#nullable disable
Done

2024-06-01 16:15 UTC, PureWeen commented on src/Controls/src/Core/Slider/Slider.Mapper.cs
> +		public static IPropertyMapper<ISlider, SliderHandler>? ControlsSliderMapper = new ControlsMapper<Slider, SliderHandler>(SliderHandler.Mapper);
I don't think we need to add this

2024-06-01 16:16 UTC, PureWeen requested changes

2024-06-01 16:16 UTC, PureWeen commented on src/Controls/src/Core/Slider/Slider.iOS.cs
> +		public static void MapUpdateOnTap(SliderHandler handler, Slider slider) =>
Can we just make all public APIs added in this PR internal? 

So, we're not adding any new API?

2024-06-02 09:16 UTC, PureWeen commented
/azp run

2024-06-11 09:56 UTC, jsuarezruiz approved these changes, later dismissed

2024-06-19 14:10 UTC, Yves-Be commented
This seems a bit wonky when using a centered Slider and a fixed width, I'm getting negative values that are being set. 
`<Slider
      Minimum="0"
      Maximum="100"
      WidthRequest="256"
      HeightRequest="64"
      HorizontalOptions="Center"/>
      `


Perhaps something is still missing compared to Xamarin? `tappedLocation.X` now seems to be relative to the control frame already, so I don't think we need to subtract `control.Frame.X`

2024-06-24 18:36 UTC, kubaflo commented
@Yves-Be you're absolutely right! Thank you yot pointing it out!

2024-07-16 18:12 UTC, PureWeen commented
/azp run

2024-09-07 00:47 UTC, PureWeen commented on src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
> +		internal void MapUpdateOnTap(bool isMapUpdateOnTapEnabled)
Yea, if we're not adding an interface at the core level then controls level inside the xaml class makes sense

2024-10-31 12:21 UTC, kubaflo commented
@jsuarezruiz done :)

2024-11-17 01:34 UTC, mattleibow commented on src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
> +					_sliderTapRecognizer = new UITapGestureRecognizer((recognizer) =>
@kubaflo we may need to make sure the slider is part of the memory leak tests and then also use the proxy patterns for ios.

2024-11-17 01:34 UTC, mattleibow commented
/azp run

2025-01-17 20:55 UTC, codychaplin commented
Any update on this?

2025-03-03 15:36 UTC, jfversluis commented
Anyone waiting on this, would you be able to verify the fix in this PR following [these instructions](https://github.com/dotnet/maui/wiki/Testing-PR-Builds)?

At the time of writing the build still needs to complete, but whenever it does, please pull down the packages and let us know if that fixes the issue and does not introduce and new unwanted behavior. Thanks!

2025-03-04 11:13 UTC, jsuarezruiz requested changes

2025-03-04 11:13 UTC, jsuarezruiz commented on src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
> +					_sliderTapRecognizer = new UITapGestureRecognizer((recognizer) =>
@kubaflo Could you include a test similar to https://github.com/dotnet/maui/blob/d6dca87b2ad70c4d6e3ac4d635603773f91c5137/src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs#L55 but with the Slider on iOS and using the Platform Specific? Let me know if need helps, and I can include it.

2025-03-04 14:16 UTC, kubaflo commented
@jsuarezruiz I've added a device test

2025-03-05 10:00 UTC, jsuarezruiz requested changes

2025-03-05 10:00 UTC, jsuarezruiz commented on src/Controls/tests/DeviceTests/Elements/Slider/SliderTests.iOS.cs
> +                //slider.On<iOS>().SetUpdateOnTap(true);
This line should not be commented, right?

2025-03-05 12:45 UTC, kubaflo commented on src/Controls/tests/DeviceTests/Elements/Slider/SliderTests.iOS.cs
> +                //slider.On<iOS>().SetUpdateOnTap(true);
Right!

2025-03-05 12:46 UTC, kubaflo commented on src/Controls/tests/DeviceTests/Elements/Slider/SliderTests.iOS.cs
> +                //slider.On<iOS>().SetUpdateOnTap(true);
@jsuarezruiz any idea of how to fix it?

![Simulator Screenshot - iPhone 16 Pro Max - 2025-03-05 at 13 43 49](https://github.com/user-attachments/assets/fec43d57-7962-45c8-b99f-439d3250350b)

It appears that the _sliderTapRecognizer is leaking, I'm disposing it in DisconnectHandler, but this method is not called :/

2025-03-22 02:17 UTC, bhavanesh2001 commented on src/Controls/tests/DeviceTests/Elements/Slider/SliderTests.iOS.cs
> +                var layout = new VerticalStackLayout();
I ran into a similar issue in [#28331](https://github.com/dotnet/maui/pull/28331). We can't use this pattern to test for leaks here, because the `Label` is never actually attached to a `Window`. As a result, `DisconnectHandler()` never gets called, and the gesture isn't cleaned up.

You might want to check out the device test [here](https://github.com/dotnet/maui/pull/28331/files);  it might help in adjusting the test setup.

2025-03-22 02:17 UTC, bhavanesh2001 commented on src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
> +				PlatformView.RemoveGestureRecognizer(_sliderTapRecognizer);
to be safe, set `_sliderTapRecognizer.ShouldReceiveTouch = null;` here

2025-03-22 06:09 UTC, bhavanesh2001 commented on src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
> +						var control = PlatformView;
The `PlatformView` should be passed into the gesture’s action via a `WeakReference`, otherwise the memory leak test will fail.

Something like this.

https://github.com/dotnet/maui/blob/5ee4e8f4d234f915896f4c3b47b459c30656c673/src/Core/src/Platform/iOS/LabelExtensions.cs#L117C3-L123C52

2025-03-26 05:00 UTC, bhavanesh2001 reviewed
In order to ensure that the gesture doesn't interfere with any other gestures added/inherited to the control.

2025-03-26 05:00 UTC, bhavanesh2001 commented on src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
> +					});
```suggestion
                    })
                    {
      					    CancelsTouchesInView = false,
      					    ShouldRecognizeSimultaneously = (gesture, otherGesture) => true
                    };
```

2025-04-14 14:57 UTC, rmarinho commented
/rebase

2025-07-03 19:17 UTC, jingliancui commented
hi Team, may I know why this fix will be delay on any service release again and again please?

2025-08-16 17:34 UTC, PureWeen commented
/rebase

2025-08-16 17:35 UTC, PureWeen commented
/azp run

2025-11-26 14:39 UTC, jfversluis commented
/rebase

2025-11-26 14:59 UTC, jfversluis approved these changes

2025-11-26 14:59 UTC, merged