Fixed Switch Thumb and On Colors
dotnet/maui pull request #20346
Opened 2024-02-03 23:45 UTC by kubaflo

### Description of Change

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19380

|Before|After|
|---|---|
|<video src="https://github.com/dotnet/maui/assets/42434498/1bf06f72-6da2-4959-b667-7a9baf40f936"/>|<video src="https://github.com/dotnet/maui/assets/42434498/2f55b919-4f66-4301-8cc7-8c7d24c3024e"/>|

2024-02-05 07:15 UTC, jsuarezruiz commented
/azp run

2024-03-05 11:54 UTC, BlueRaja commented
Any reason this has been sitting unmerged for a month? Seems like a pretty basic and critical bug to be sitting unfixed for months now

2024-03-05 11:55 UTC, rmarinho commented
/azp run MAUI-UITests-public

2024-03-19 17:02 UTC, MAUIoxo commented
@jsuarezruiz @rmarinho 
Just wanted to ask why this is not merged to main for such a long time now? Is there anything missing? Still waiting for this to be fixed. And this fix was provided long time ago. Any reason for that?

2024-03-20 12:53 UTC, rmarinho commented
@MAUIoxo  we are not sure this is correct fix to work with VSM. we were discussing internally.

2024-03-20 15:46 UTC, MAUIoxo commented
Thanks for the update on this! So, at least we know why it is parked 😊

2024-04-12 07:42 UTC, elparasite commented
> @MAUIoxo we are not sure this is correct fix to work with VSM. we were discussing internally.

Hi, was the discussion effective ?
This is an unbearable suspense.

2024-04-13 11:21 UTC, MAUIoxo commented
> > @MAUIoxo we are not sure this is correct fix to work with VSM. we were discussing internally.
> 
> Hi, was the discussion effective ? This is an unbearable suspense.

Yes it was - I found out that this issue is going to take forever and probably no one's going to deal with a solution anytime soon, so I guess I'll just have to come up with my own solution :D 

Here is an example of a `CustomSwitch` with a `CustomSwitchHandler` that allows me to set the `OnColor` and `ThumbColor` as in a normal `Switch` in `XAML` and map the states of `IsToggled`, `OnColor` and `ThumbColor` to the corresponding properties of the newly created iOS `UISwitch`. This is just a solution for iOS, but I am currently working on something similar for Android and will post it, too when ready. I've tested it with also with scrolling so that the View elements also have to be updated correspondingly. At least it works for me...

<br/>

**CustomSwitch**:
```cs
namespace OptimizerApp.Pages.Views.Controls.CustomSwitch
{
    public class CustomSwitch : Switch
    {
        
    }
}
```

<br/>

**Integration in XAML Code**:
```xaml
...
<constrols:CustomSwitch ... IsToggled="{Binding IsSelected, Mode=TwoWay}" ThumbColor="{StaticResource Gray100}" OnColor="{StaticResource DarkOrange1}" />
...
```

<br/>

**CustomSwitchHandler**:

```cs
#if IOS

using OptimizerApp.Pages.Views.Controls.CustomSwitch;
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Platform;
using UIKit;

namespace OptimizerApp.Platforms.iOS.ControlHandlers
{
    public partial class CustomSwitchHandler : ViewHandler<CustomSwitch, UISwitch>
    {
        /// <summary>
        /// Configures property mappings for the CustomSwitch and binds UI properties to platform-specific handlers.
        /// This mapper directs changes in MAUI's CustomSwitch properties to appropriate methods that
        /// update the native iOS UISwitch, ensuring UI consistency and responsiveness:
        /// - 'IsToggled' updates the switch's active state.
        /// - 'OnColor' adjusts the color when the switch is on.
        /// - 'ThumbColor' changes the color of the switch thumb.
        /// These mappings ensure that the visual state of the UISwitch is synchronized with the CustomSwitch.
        /// </summary>
        public static PropertyMapper<CustomSwitch, CustomSwitchHandler> CustomSwitchMapper = new PropertyMapper<CustomSwitch, CustomSwitchHandler>
        {
            [nameof(CustomSwitch.IsToggled)] = MapIsToggled,
            [nameof(CustomSwitch.OnColor)] = MapOnColor,
            [nameof(CustomSwitch.ThumbColor)] = MapThumbColor
        };

        
        public CustomSwitchHandler() : base(CustomSwitchMapper)
        {
        }

        /// <summary>
        /// Creates the native UISwitch view
        /// </summary>
        /// <returns>The newly created UISwitch instance</returns>
        protected override UISwitch CreatePlatformView()
        {
            return new UISwitch();
        }

        /// <summary>
        /// Connects this handler to the UISwitch, setting up event handlers and initial state
        /// </summary>
        /// <param name="platformView">The UISwitch to connect</param>
        protected override void ConnectHandler(UISwitch platformView)
        {
            base.ConnectHandler(platformView);

            platformView.ValueChanged += OnSwitchValueChanged;
            platformView.On = VirtualView.IsToggled;    // Synchronize the UISwitch's state with the IsToggled property of the MAUI CustomSwitch

            SetSwitchColors(platformView, VirtualView);
        }

        /// <summary>
        /// Disconnects this handler from the UISwitch and clean up the event handlers
        /// </summary>
        /// <param name="platformView">The UISwitch to disconnect</param>
        protected override void DisconnectHandler(UISwitch platformView)
        {
            platformView.ValueChanged -= OnSwitchValueChanged;
            base.DisconnectHandler(platformView);

            // Reset UI properties
            ResetSwitchColors(platformView);
        }

        /// <summary>
        /// Sets the ThumbColor and OnTintColor of the UISwitch based on the properties of the CustomSwitch
        /// </summary>
        /// <param name="uiSwitch">The native UISwitch</param>
        /// <param name="customSwitch">The MAUI CustomSwitch</param>
        private static void SetSwitchColors(UISwitch uiSwitch, CustomSwitch customSwitch)
        {
            // Setting the null-values will set it to default values
            uiSwitch.ThumbTintColor = customSwitch.ThumbColor != default(Color) ? customSwitch.ThumbColor.ToPlatform() : null;
            uiSwitch.OnTintColor = customSwitch.OnColor != default(Color) ? customSwitch.OnColor.ToPlatform() : null;
        }

        /// <summary>
        /// Resets the ThumbColor and OnTintColor properties of the UISwitch to defaults
        /// </summary>
        /// <param name="uiSwitch">The UISwitch to reset</param>
        private void ResetSwitchColors(UISwitch uiSwitch)
        {
            uiSwitch.ThumbTintColor = null;
            uiSwitch.OnTintColor = null;
        }

        /// <summary>
        /// Map changes in the OnColor property to the UISwitch
        /// </summary>
        public static void MapOnColor(CustomSwitchHandler handler, CustomSwitch customSwitch)
        {
            if (handler.PlatformView != null)
            {
                handler.PlatformView.OnTintColor = customSwitch.OnColor.ToPlatform();
            }
        }

        /// <summary>
        /// Map changes in the ThumbColor property to the UISwitch
        /// </summary>
        public static void MapThumbColor(CustomSwitchHandler handler, CustomSwitch customSwitch)
        {
            if (handler.PlatformView != null)
            {
                handler.PlatformView.ThumbTintColor = customSwitch.ThumbColor.ToPlatform();
            }
        }

        /// <summary>
        /// Map changes in the IsToggled property to the UISwitch
        /// </summary>
        public static void MapIsToggled(CustomSwitchHandler handler, CustomSwitch customSwitch)
        {
            if (handler.PlatformView != null)
            {
                handler.PlatformView.On = customSwitch.IsToggled;                
                handler.UpdateSwitchColors(handler.PlatformView, customSwitch);     // Update colors when switch is toggled/untoggled
            }
        }

        private void OnSwitchValueChanged(object sender, EventArgs e)
        {
            var uiSwitch = (UISwitch)sender;
            VirtualView.IsToggled = uiSwitch.On;

            UpdateSwitchColors(uiSwitch, VirtualView);
        }

        /// <summary>
        /// Update the OnTintColor and ThumbColor with the colors defined in the customSwitch
        /// </summary>
        private void UpdateSwitchColors(UISwitch uiSwitch, CustomSwitch customSwitch)
        {
            if (uiSwitch.On)
            {
                if (customSwitch.OnColor != default(Color))
                {
                    uiSwitch.OnTintColor = customSwitch.OnColor.ToPlatform();
                }
            }

            if (customSwitch.ThumbColor != default(Color))
            {
                uiSwitch.ThumbTintColor = customSwitch.ThumbColor.ToPlatform();
            }
        }
    }
}

#endif
```
<br/>

**MauiProgram.cs**:
```cs
...
#if IOS
using OptimizerApp.Platforms.iOS.ControlHandlers;
#endif
...

var builder = MauiApp.CreateBuilder();
builder
    .UseMauiApp<App>()
    ...
    .ConfigureMauiHandlers(handlers =>
    {
        // The handler will only be called if the target platform is iOS
#if IOS
        handlers.AddHandler<CustomSwitch, CustomSwitchHandler>();
#endif
    });
...
```

![CustomSwitchHandler](https://github.com/dotnet/maui/assets/140683727/0857dc14-51bf-4fb3-9042-a3e7fb2e7550)

2024-06-11 11:51 UTC, jsuarezruiz commented
/azp run

2024-06-13 07:49 UTC, jsuarezruiz commented
/azp run

2024-07-20 20:52 UTC, AncientLust commented
Any change to fix this basic functionality?

> Any reason this has been sitting unmerged for a month? Seems like a pretty basic and critical bug to be sitting unfixed for months now

Let's wait when we hit a year. Seems like a minor bug, who uses switches anyway..

2024-07-20 20:54 UTC, AncientLust commented
> Any reason this has been sitting unmerged for a month? Seems like a pretty basic and critical bug to be sitting unfixed for months now

Let's wait when we hit a year. Seems like a minor bug, who uses switches anyway..

2024-07-29 16:51 UTC, AncientLust commented
For me the simplest solution was to go into Resources/Styles/Styles.xaml, search for "Switch" and set colors you need both for dark and white theme.

2024-10-31 12:03 UTC, jsuarezruiz commented
> I have tried this, but its not working. ThumbColor not getting changed even if set using DataTrigger.
> 
>  Screen.Recording.2024-08-14.at.11.01.17.PM.mov

@kubaflo

2024-10-31 14:18 UTC, kubaflo commented
@jsuarezruiz could you please /azp 

@divyesh008 can you please try again with changes I've just added

2024-11-15 09:23 UTC, jsuarezruiz commented
/rebase

2024-11-15 09:37 UTC, jsuarezruiz commented
/azp run

2025-03-08 01:16 UTC, kubaflo commented
> Any reason this has been sitting unmerged for a month? Seems like a pretty basic and critical bug to be sitting unfixed for months now

It's the anniversary of your comment 😂

2025-03-08 06:59 UTC, MAUIoxo commented
> > Any reason this has been sitting unmerged for a month? Seems like a pretty basic and critical bug to be sitting unfixed for months now
> 
> It's the anniversary of your comment 😂

The 7th year is always the critical one 😅😂

2025-05-13 16:36 UTC, mattleibow requested changes
Picking option red because I wonder if this is fixed or requires a different fix to work with the style specificities.

Also, could the "not working" be the case because the is no Normal style to fall back to?

2025-05-13 16:36 UTC, mattleibow commented on src/Controls/src/Core/Switch/Switch.cs
> +				((IView)bindable)?.Handler?.UpdateValue(nameof(ISwitch.ThumbColor));
didn't this property automatically fire this update?

2025-05-13 16:36 UTC, mattleibow commented on src/Controls/src/Core/Switch/Switch.cs
> +			((IView)bindable)?.Handler?.UpdateValue(nameof(ISwitch.ThumbColor));
Maybe with the new work @StephaneDelcroix did with style specificities, this is no longer needed and the style should swap?

2025-05-13 16:36 UTC, mattleibow commented
/rebase

2025-05-13 17:53 UTC, kubaflo commented
@mattleibow you're right. The changes are no longer needed, so I'm closing this PR

2025-05-13 17:53 UTC, closed without merging