Re-Enable CA1416
dotnet/maui pull request #20477
Opened 2024-02-09 20:33 UTC by PureWeen

### Description of Change

### Issues Fixed

Fixes #

2024-02-12 07:59 UTC, jsuarezruiz commented on src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
Require this validation on more places (essentials etc):

`D:\a\_work\1\s\src\Essentials\src\Screenshot\Screenshot.ios.cs(89,4): error CA1416: This call site is reachable on: 'MacCatalyst' 13.1 and later. 'UIGraphics.EndImageContext()' is unsupported on: 'maccatalyst' 17.0 and later. `

2024-03-27 19:52 UTC, stephen-hawley requested changes

2024-03-27 19:52 UTC, stephen-hawley commented on src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.iOS.cs
> +				using (var renderer = new UIGraphicsImageRenderer(new CGSize(width, height), format))
minor - there's no reason to use a block which you can just do:
```
using var renderer = new UIGraphicsImageRenderer(new CGSize(width, height), format);
```

2024-03-27 19:52 UTC, stephen-hawley commented on src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs
> +				var resultImage = renderer.CreateImage((UIGraphicsImageRendererContext imageContext) =>
same

2024-03-27 19:52 UTC, stephen-hawley commented on src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs
> +			using (var renderer = new UIGraphicsImageRenderer(target.Size))
same

2024-05-16 22:43 UTC, PureWeen commented
/rebase

2024-05-21 16:15 UTC, PureWeen commented
/rebase

2024-05-22 21:58 UTC, PureWeen commented
/rebase

2024-06-24 14:27 UTC, stephen-hawley submitted a review, later dismissed

2024-07-09 21:39 UTC, PureWeen commented
/azp run

2024-12-12 21:50 UTC, closed without merging