Remove Switch On/Off content
dotnet/maui pull request #20487
Opened 2024-02-10 01:19 UTC by dotMorten

### Description of Change

Removes the default On/Off text on the Windows ToggleSwitch. This brings consistency with iOS and Android, and avoids issues with not being able to style the text.

### Issues Fixed

Fixes #20486

I've validated the fix with Sandbox app. I'd love to add some unit tests too, but need a little guidance wrt where to put that, and how to verify that it no longer renders the text.

2024-02-12 10:40 UTC, jsuarezruiz reviewed
Hi Morten,

You have different ways to validate it with tests.
On the one hand, you can create a DeviceTests here https://github.com/dotnet/maui/blob/main/src/Core/tests/DeviceTests/Handlers/Switch/SwitchHandlerTests.Windows.cs#L16
Using xUnit you can create a test similar to https://github.com/dotnet/maui/blob/main/src/Core/tests/DeviceTests/Handlers/Switch/SwitchHandlerTests.cs#L14 where with a method you access the ToggleSwitch and you validate that the OffContent and OnContent properties are null.
You can also create a UITest, creating a golden test where a reference snapshot is created and the test compares each screenshot pixel by pixel with the reference. Example: https://github.com/dotnet/maui/blob/b43f2650b9a38ec56689e7d760c4f74f9c9867db/src/Controls/tests/UITests/Tests/Issues/Issue17610.cs#L46

2024-02-12 15:49 UTC, PureWeen requested changes
Can you retarget this for net9.0?

2024-02-13 00:03 UTC, dotMorten commented
@PureWeen Done!

2024-02-13 00:46 UTC, rmarinho submitted a review, later dismissed

2024-02-29 17:59 UTC, rmarinho approved these changes

2024-02-29 17:59 UTC, merged