[iOS] Shell page title fix
dotnet/maui pull request #20575
Opened 2024-02-14 11:42 UTC by kubaflo

### Description of Change

Shell page title fix - setting the shell page's toolbar title in the `ViewDidLoad` method

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20199

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/60bac422-3e82-4aa1-bc64-5707b6303e74" />|<video src="https://github.com/dotnet/maui/assets/42434498/08f4ad53-b434-40f9-bcae-651c1e6507d1" />|

2024-03-21 10:29 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2024-04-16 11:45 UTC, jsuarezruiz commented
Added pending test snapshot.

2024-04-24 19:59 UTC, dustin-wojciechowski approved these changes, later dismissed

2024-04-24 19:59 UTC, dustin-wojciechowski commented
/azp rebase

2024-04-24 20:01 UTC, dustin-wojciechowski commented
/rebase

2024-04-24 20:03 UTC, dustin-wojciechowski commented
/azp run

2024-04-29 21:10 UTC, PureWeen commented
/rebase

2024-04-29 22:31 UTC, PureWeen requested changes

2024-04-29 22:31 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs
> +				NavigationItem.Title = _shellContext.Shell.Toolbar.Title;
I think the bug with this one is that Disappearing is never fired on the root page.

Like if you set a break point on disapearing

```C#
	public class Issue20199Page : ContentPage {

		protected override void OnAppearing()
		{
			base.OnAppearing();
		}

		protected override void OnDisappearing()
		{
			base.OnDisappearing();
		}
	}
```

disappearing never fires

if we get disappearing to fire (or perhaps get appearing to not fire)
That should fix the title

2024-04-30 14:04 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs
> +				_tracker = tracker;
Is this change still correct to have?

2024-04-30 14:28 UTC, kubaflo commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs
> +				_tracker = tracker;
Right! No need for this one

2024-04-30 14:54 UTC, PureWeen approved these changes

2024-04-30 14:54 UTC, PureWeen commented
/azp run

2024-04-30 15:08 UTC, dustin-wojciechowski approved these changes

2024-05-01 05:51 UTC, PureWeen commented
/rebase

2024-05-01 05:52 UTC, PureWeen commented
/azp run

2024-05-01 05:55 UTC, PureWeen commented
/azp run

2024-05-01 17:39 UTC, merged