ContentPage CSharp  Item Template
dotnet/maui pull request #2063
Opened 2021-08-12 12:19 UTC by jsuarezruiz

### Description of Change ###

ContentPage Csharp  Item Template.

### PR Checklist ###

- [x] Targets the correct branch 

#### Does this PR touch anything that might affect accessibility?
- No

2021-08-13 16:38 UTC, Eilon requested changes

2021-08-13 16:38 UTC, Eilon commented on src/Templates/src/templates/maui-contentpage-csharp/.template.config/template.json
> +        "description": "namespace for the generated code",
```suggestion
        "description": "Namespace for the generated code.",
```

2021-08-13 16:38 UTC, Eilon commented on src/Templates/src/templates/maui-contentpage-csharp/.template.config/template.json
> +    "identity": "Microsoft.Maui.ContentPage",
Similar to my comment in other PRs, does this identity need to be different from the XAML one below?

2021-08-25 00:45 UTC, mattleibow approved these changes

2021-08-25 10:40 UTC, rmarinho approved these changes

2021-08-25 10:41 UTC, merged