ContentView XAML Item Template
dotnet/maui pull request #2064
Opened 2021-08-12 12:19 UTC by jsuarezruiz

### Description of Change ###

ContentView XAML  Item Template.

### PR Checklist ###

- [x] Targets the correct branch 

#### Does this PR touch anything that might affect accessibility?
- No

2021-08-13 16:38 UTC, Eilon requested changes

2021-08-13 16:38 UTC, Eilon commented on src/Templates/src/templates/maui-contentview-xaml/.template.config/template.json
> +    "identity": "Microsoft.Maui.ContentView",
See this comment: https://github.com/dotnet/maui/pull/2065#discussion_r688642467

2021-08-13 16:38 UTC, Eilon commented on src/Templates/src/templates/maui-contentview-xaml/.template.config/template.json
> +            "description": "namespace for the generated code",
```suggestion
            "description": "Namespace for the generated code.",
```

2021-08-24 17:39 UTC, Redth approved these changes

2021-08-25 00:46 UTC, mattleibow approved these changes

2021-08-25 12:56 UTC, merged