Update Maps Project API Docs
dotnet/maui pull request #20893
Opened 2024-02-28 12:53 UTC by jfversluis

### Description of Change

This adds all the missing API docs for the Maps project. Additionally this enables build errors when public XML docs are not found where they should be in order to prevent future documentation from being forgotten.

### Issues Fixed

Related to #3960

2024-02-28 18:33 UTC, jknaudt21 requested changes
Some docs for the boolean properties should follow the more standard wording "Gets or sets **a value that indicates** ...".
More info: https://github.com/dotnet/dotnet-api-docs/wiki/Summary%3A-Property

Other than that lgtm.

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/Map.cs
> +		/// Gets or sets if scrolling by user input is enabled. Default value is <see langword="true"/>.
```suggestion
		/// Gets or sets a value that indicates if scrolling by user input is enabled. Default value is <see langword="true"/>.
```

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/Map.cs
> +		/// Gets or sets if zooming by user input is enabled. Default value is <see langword="true"/>.
```suggestion
		/// Gets or sets a value that indicates if zooming by user input is enabled. Default value is <see langword="true"/>.
```

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/Map.cs
> +		/// Gets or sets if the map shows an indicator of the current position of this device. Default value is <see langword="false"/>
```suggestion
		/// Gets or sets a value that indicates if the map shows an indicator of the current position of this device. Default value is <see langword="false"/>
```

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/Map.cs
> +		/// Gets or sets if the map shows current traffic information. Default value is <see langword="false"/>.
```suggestion
		/// Gets or sets a value that indicates if the map shows current traffic information. Default value is <see langword="false"/>.
```

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/MapElement.cs
> +	/// Represents an element which is visually drawn on the map control.
Maybe add a cref to the word map?
```suggestion
	/// Represents an element which is visually drawn on the <see cref="Map"/> control.
```

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/Pin.cs
> +	/// Represents a pin on the map control.
Cref the map?

2024-02-28 18:33 UTC, jknaudt21 commented on src/Controls/Maps/src/Pin.cs
> +		///	Equality operator for equals.
Whitespace seems off

2024-02-28 18:33 UTC, jknaudt21 commented on src/Core/maps/src/Core/ICircleMapElement.cs
> +
Missing docs?

2024-02-28 19:30 UTC, jfversluis commented on src/Controls/Maps/src/Pin.cs
> +	/// Represents a pin on the map control.
```suggestion
	/// Represents a pin on the <see cref="Map"/> control.
```

2024-02-28 19:30 UTC, jfversluis commented on src/Controls/Maps/src/Pin.cs
> +		///	Equality operator for equals.
```suggestion
		/// Equality operator for equals.
```

2024-02-28 19:32 UTC, jfversluis commented on src/Core/maps/src/Core/ICircleMapElement.cs
> +
```suggestion
		/// <summary>
		/// Gets the radius.
		/// </summary>
```

2024-02-28 19:59 UTC, jknaudt21 approved these changes

2024-02-29 10:26 UTC, jfversluis commented
/rebase

2024-02-29 10:36 UTC, jsuarezruiz approved these changes

2024-03-01 15:28 UTC, jfversluis commented
Test failures unrelated

2024-03-01 15:28 UTC, merged