[iOS] Shell/NavigationPage TitleView (#5063)
dotnet/maui pull request #20959
Opened 2024-03-02 15:11 UTC by kubaflo

## Current behavior
 Layout options have no effect on the title view. The content inside the `titleView` behaves as it has both `HorizontalOptions` and `VerticalOptions` set to `Fill`. Also, notice that there's a horizontal margin that cannot be removed even with setting the negative values to margin eg. `Margin="-20,0"` (https://github.com/dotnet/maui/issues/19231)

### Currently
<img width="385" alt="Screenshot 2024-03-02 at 14 58 41" src="https://github.com/dotnet/maui/assets/42434498/d2948732-783a-4e12-81cb-32b8d02bea22">

## Proposed behavior https://github.com/dotnet/maui/issues/5063
Utilizes our current LayoutOptions to indicate how you want a TitleView to layout on the screen and removes the default horizontal margin so that we can customize it.

```
<NavigationPage.TitleView>
    <HorizontalStackLayout BackgroundColor="red">
        <Label VerticalOptions="Center" Text="Navigation page's title"/>
        <Image Source="dotnet_bot.png" Scale="0.8"/>
    </HorizontalStackLayout>
</NavigationPage.TitleView>
```

### `Default` - (horizontal and vertical options set to fill implicitly)

<img width="385" alt="Screenshot 2024-03-02 at 15 00 41" src="https://github.com/dotnet/maui/assets/42434498/03949fdc-7467-48c7-a308-083e01509a6b">

### `HorizontalOptions="Start"`
<img width="385" alt="Screenshot 2024-03-02 at 15 02 14" src="https://github.com/dotnet/maui/assets/42434498/7d874679-047e-414f-a4a3-2c0ca909da92">

### `HorizontalOptions="Center"`
<img width="385" alt="Screenshot 2024-03-02 at 15 04 44" src="https://github.com/dotnet/maui/assets/42434498/b8c892b8-87fb-49df-8b01-2bd183e21a96">

### `HorizontalOptions="End"`
<img width="385" alt="Screenshot 2024-03-02 at 15 05 47" src="https://github.com/dotnet/maui/assets/42434498/46ffd14e-56e4-4420-b1dd-b777989efd7d">

### `VerticalOptions="Start"`
<img width="385" alt="Screenshot 2024-03-02 at 15 09 49" src="https://github.com/dotnet/maui/assets/42434498/b01a4b8b-704c-42b7-837c-c5225dae62fb">

### `VerticalOptions="Center"`
<img width="385" alt="Screenshot 2024-03-02 at 15 07 58" src="https://github.com/dotnet/maui/assets/42434498/3db14960-ffc0-43e2-b477-a7f762f59871">

### `VerticalOptions="End"`
<img width="385" alt="Screenshot 2024-03-02 at 15 06 56" src="https://github.com/dotnet/maui/assets/42434498/93167311-5b23-4f73-8832-7438a1c9d42b">

### `VerticalOptions="Start"` `HorizontalOptions="Start"`
<img width="385" alt="Screenshot 2024-03-02 at 15 15 30" src="https://github.com/dotnet/maui/assets/42434498/a462142e-2a6d-4edc-91e5-46a03318708b">

### `VerticalOptions="Center"` `HorizontalOptions="Center"`
<img width="385" alt="Screenshot 2024-03-02 at 15 14 42" src="https://github.com/dotnet/maui/assets/42434498/5c460b0c-1c24-48c8-ac84-29210903ac6b">

### `VerticalOptions="End"` `HorizontalOptions="End"`
<img width="385" alt="Screenshot 2024-03-02 at 15 15 07" src="https://github.com/dotnet/maui/assets/42434498/a2e28892-5865-4f62-8ba0-9d2a632cdbfc">

## Remarks
I didn't implement anything that changes the behavior when additional toolbar items are added. For example, if there's a back button the title view places itself to the right of this button. It is because I'm not sure what is the desired behavior. On one hand, it looks weird that when we want to center the title it is moved to the right, but on the other, it is the default iOS's behavior and I believe a future discussion should be made https://github.com/xamarin/Xamarin.Forms/issues/4848
<img width="385" alt="Screenshot 2024-03-02 at 16 10 55" src="https://github.com/dotnet/maui/assets/42434498/2eee7174-d379-49cc-9e44-c7b4b4556298">

2024-03-20 16:24 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2024-03-29 15:37 UTC, Pastajello commented
Oh my, never knew I'd see a fix from the issue I suffered 4 years ago in X.F. days! Are there any plans to add it to .net 8 SR 4? (hopefully)

2024-04-03 09:45 UTC, idzson approved these changes

2024-04-16 11:38 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
> +			const int SystemMargin = 16;
Could you include a comment with a link to the Apple docs or similar?

2024-04-16 11:38 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
> +					spacer.Width -= 4;
Have you done tests with 6.1" and 6.7" simulators or devices?

2024-04-19 10:37 UTC, jsuarezruiz commented
/azp run

2024-04-30 17:53 UTC, PureWeen requested changes
can you retarget this for net9?

2024-04-30 18:05 UTC, kubaflo commented
> can you retarget this for net9?

Yep, I think it is a good idea

2024-05-31 19:36 UTC, TheXenocide commented
> > can you retarget this for net9?
> 
> Yep, I think it is a good idea

Is there no chance we can get this fix in a patch release for .NET 8? Preferably sooner than later? I'm wrestling with this issue at the moment and would really appreciate a fix but we only use LTS versions for production apps.

2024-05-31 19:37 UTC, TheXenocide commented
I also can't use this code directly in our app because too many pieces are internal for me to drop this in as a replacement renderer.

2024-10-11 09:24 UTC, Felix-Dev commented
@kubaflo Any update on this PR? What is blocking progress here?

2024-10-11 09:33 UTC, kubaflo commented
Hi, @Felix-Dev it is not up to me what will happen with this pr

2024-10-25 21:05 UTC, rmarinho commented
/rebase

2024-11-14 15:59 UTC, Felix-Dev commented
@PureWeen What is blocking this PR from being merged? The "requested changes" seems to have been adressed by @kubaflo. We are interested in seeing this change land in MAUI. Thanks!

2024-11-19 17:04 UTC, jbeacham commented
This is also affecting us, an app with millions of users being forced to migrate to MAUI. Huge gaps on either end of the nav bar if we try to do any other color. Any update? Any workaround? @PureWeen

2024-11-19 18:37 UTC, jbeacham commented
@kubaflo It looks like 2 failing checks. Anything you're familiar with so this can get merged?

2024-11-19 18:55 UTC, kubaflo commented
@jbeacham Hi!, It's not up to me when and if PRs get merged, but I will rebase this one and solve conflicts :)

2024-11-20 08:13 UTC, amirvenus commented
I seem to have a similar issue on android too

2024-11-29 23:19 UTC, dainius-r commented
@kubaflo thanks for PR, have you noticed similar PR for Android, or maybe some workaround?

2024-11-29 23:45 UTC, kubaflo commented
@dainius-r regarding the left margin: https://github.com/dotnet/maui/pull/20967
When it comes to LayoutOptions, I think they are respected on Android

```
<NavigationPage.TitleView>
    <HorizontalStackLayout HorizontalOptions="End" BackgroundColor="red">
        <Label VerticalOptions="Center"
                Text="Navigation page's title"/>
        <Image Source="dotnet_bot.png"
                Scale="0.8"/>
    </HorizontalStackLayout>
</NavigationPage.TitleView>
```

<img src="https://github.com/user-attachments/assets/371e3f94-e098-4132-a406-a2a3a812bb74" width="300px"/>

2024-12-03 23:56 UTC, dainius-r commented
@kubaflo many thanks, that's my issue I was lookin for https://github.com/dotnet/maui/pull/20967

2025-07-04 06:15 UTC, YZahringer commented
Any update on this PR? What is blocking progress here?

2025-08-27 12:30 UTC, jfversluis commented
/rebase

2025-08-27 12:32 UTC, jfversluis commented
/azp run MAUI-UITests-public

2025-08-28 13:11 UTC, jfversluis approved these changes

2025-08-28 13:11 UTC, merged