[Android] Navigation bar - left margin fix
dotnet/maui pull request #20967
Opened 2024-03-03 01:17 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/18843

|Before|After|
|--|--|
|<img src="https://github.com/dotnet/maui/assets/42434498/7ecdede0-012f-4715-a695-8d96589adace" width="300px"/>|<img src="https://github.com/dotnet/maui/assets/42434498/0c41c8f1-52bf-4c55-aabe-331de2fd68df" width="300px"/>|

2024-04-16 11:35 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2024-05-10 09:07 UTC, jsuarezruiz commented
/azp run

2024-05-10 09:07 UTC, jsuarezruiz commented
/azp run

2024-06-10 13:44 UTC, jsuarezruiz commented
/azp run

2024-07-13 17:30 UTC, PureWeen commented
/azp run

2024-10-31 11:54 UTC, jsuarezruiz commented
/rebase

2024-10-31 11:56 UTC, jsuarezruiz commented
/azp run

2024-12-06 19:15 UTC, dainius-r commented
@kubaflo if I understand this fix correctly you are setting `contentInsetStart` from default 16dp to 0, if `TitleView` is `Layout` with horizontal alignment.

What if we just use horizontal aligned `Label`, then `TitleView` will be with additional margin?
For my workaround I updated android style for toolbarStyle to:
```
<style name="MauiToolbar" parent="Widget.Material3.Toolbar">
  <item name="contentInsetStart">0dp</item>
</style>
```
Maybe just use style changes in this fix and don't have any `contentInsetStart`, this will be noticeble anly when there is no `NavigationIcon` and even if title is centered, without margin title will be at correct center on toolbar, what do you think?

2025-06-10 11:23 UTC, YZahringer commented
any news on this fix? could be consider for a V9 SR?

2025-06-12 00:30 UTC, mattleibow requested changes
What will happen if we have a hamburger?

What happens if you remove the title view? For example, you may put something there temporarily.

also as mentioned, what happens if you stick a label, or image in there? Or a content view?

I feel like the question should be answered first: when would we want the space and when would we want full control?

2025-06-12 23:37 UTC, kubaflo commented
@mattleibow I've added a commit

2026-01-10 22:55 UTC, kubaflo commented
# PR Review: #20967 - [Android] Navigation bar - left margin fix

**Date:** 2026-01-10 | **Issue:** [#18843](https://github.com/dotnet/maui/issues/18843) | **PR:** [#20967](https://github.com/dotnet/maui/pull/20967)

## ✅ Status: COMPLETE

| Phase | Status |
|-------|--------|
| Pre-Flight | ✅ COMPLETE |
| 🧪 Tests | ✅ COMPLETE |
| 🚦 Gate | ✅ PASSED |
| 🔧 Fix | ✅ COMPLETE |
| 📋 Report | ✅ COMPLETE |

---

<details>
<summary><strong>📋 Issue Summary</strong></summary>

**Description:**
When using NavigationPage.TitleView on Android, there's an unwanted left margin (default 16dp contentInsetStart from Android toolbar) that appears on the navigation bar. This margin doesn't appear on Windows/other platforms.

**Steps to Reproduce:**
1. Create a new MAUI project
2. Change MainPage to NavigationPage in App.xaml.cs
3. Add NavigationPage.TitleView in MainPage.xaml
4. Launch on Android - see left margin/padding

**Reproduction Link:** [MADSENSE.MAUI.Sample.App](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/navigationBar-margin-left)

**Platforms Affected:**
- [x] Android
- [ ] iOS
- [ ] Windows
- [ ] MacCatalyst

**Regression:** Not sure, not tested in previous versions

**Workarounds Found (from community):**
1. Set BarBackgroundColor from code-behind instead of XAML (stanbilliet)
2. Override Android styles.xml with custom toolbar style setting contentInsetStart to 0dp (Domik234)

</details>

<details>
<summary><strong>📁 Files Changed</strong></summary>

| File | Type | Changes |
|------|------|---------|
| `src/Controls/src/Core/Toolbar/Toolbar.Android.cs` | Fix | +15 lines |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue18843.xaml` | Test HostApp | +26 lines |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue18843.xaml.cs` | Test HostApp | +35 lines |
| `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18843.cs` | NUnit Test | +25 lines |

</details>

<details>
<summary><strong>💬 PR Discussion Summary</strong></summary>

**Key Comments:**

**From mattleibow (Reviewer - CHANGES_REQUESTED on 2025-06-12):**
- "What will happen if we have a hamburger?" (navigation icon)
- "What happens if you remove the title view?" (temporary TitleView)
- "What happens if you stick a label, or image in there? Or a content view?"
- Core question: "When would we want the space and when would we want full control?"

**From dainius-r (Community - 2024-12-06):**
- Questions the logic: "What if we just use horizontal aligned Label, then TitleView will be with additional margin?"
- Suggests: "Maybe just use style changes in this fix and don't have any contentInsetStart"
- Points out: Without margin, title will be at correct center on toolbar even when there's no NavigationIcon

**From jeremy-visionaid (2025-05-21):**
- Also experiencing this in Shell.TitleView on iOS and MacCatalyst too (possibly related to #5063)

**Author's Response (2025-06-12):**
- Added a commit (presumably addressing reviewer concerns)

**Disagreements to Investigate:**
| Concern | Reviewer Says | Current Fix | Status |
|---------|---------------|-------------|--------|
| Hamburger icon | What happens with navigation icon present? | Only removes inset for Layout with Margin/HorizontalOptions set | ⚠️ NEEDS TESTING |
| Label/Image TitleView | What if TitleView is not a Layout? | Restores default inset for non-Layout | ⚠️ NEEDS VERIFICATION |
| Dynamic TitleView | What if TitleView is removed/changed? | Restores _defaultStartInset when condition not met | ⚠️ EDGE CASE |
| Always remove margin | Should we always remove contentInsetStart? | Conditional based on Layout + properties | ⚠️ DESIGN DECISION |

**Edge Cases to Check:**
- [ ] TitleView with NavigationIcon (hamburger menu)
- [ ] TitleView as Label (not Layout)
- [ ] TitleView as Image (not Layout)
- [ ] TitleView as ContentView
- [ ] TitleView removed dynamically
- [ ] TitleView changed from Layout to Label
- [ ] TitleView without Margin/HorizontalOptions set

**Author Uncertainty:**
- Initial fix may not have addressed all TitleView types (responded to reviewer by adding commit)

</details>

<details>
<summary><strong>🧪 Tests</strong></summary>

**Status**: ✅ COMPLETE

- [x] PR includes UI tests
- [x] Tests follow naming convention (`Issue18843`)
- [x] Tests compile successfully

**Test Files:**
- HostApp: `src/Controls/tests/TestCases.HostApp/Issues/Issue18843.xaml[.cs]`
- NUnit: `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18843.cs`

**Test Scenario:**
- HorizontalStackLayout with Margin=0 as TitleView
- Contains Label (AutomationId="title") + Image
- Verifies entire navigation bar is red via VerifyScreenshot() (no white margin on left)
- Android-only test (`#if ANDROID`)

**Compilation:** ✅ Both HostApp and Tests projects compile successfully

</details>

<details>
<summary><strong>🚦 Gate - Test Verification</strong></summary>

**Status**: ✅ PASSED

- [x] Tests FAIL without fix (bug reproduced)

**Result:** ✅ PASSED - Tests correctly reproduced the bug (failed as expected)

**Verification Output:**
```
╔═══════════════════════════════════════════════════════════╗
║         VERIFICATION PASSED ✅                            ║
╠═══════════════════════════════════════════════════════════╣
║  Tests FAILED as expected (bug is reproduced)             ║
║                                                           ║
║  Next: Implement a fix, then rerun to verify tests pass.  ║
╚═══════════════════════════════════════════════════════════╝
```

**Note:** Test initially failed to compile due to missing `[Category(UITestCategories.Navigation)]` attribute. Fixed and rerun successful.

</details>

<details>
<summary><strong>🔧 Fix Candidates</strong></summary>

**Status**: ✅ COMPLETE

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| 1 | Agent Analysis | Always remove contentInsetStart for any TitleView | ⚠️ NOT TESTED | Would be `Toolbar.Android.cs` | Simpler but may break navigation icon spacing - reviewer concerns about hamburger menu validate PR's conditional approach |
| PR | PR #20967 | Conditionally remove contentInsetStart only when TitleView is Layout with Margin or HorizontalOptions set; restore default otherwise | ✅ PASS (Gate) | `Toolbar.Android.cs` (+15) | Original PR - addresses reviewer concerns by being selective |

**Analysis:**

**Alternative Considered (Candidate #1):**
- Always remove contentInsetStart (`parent.SetContentInsetsAbsolute(0, 0)`) for ANY TitleView
- **Simpler**: 6 lines vs PR's 15 lines
- **Risk**: Would break spacing when navigation icon (hamburger menu) is present
- **Why PR's approach is better**: Reviewer@mattleibow specifically asked "What will happen if we have a hamburger?" - the conditional logic in PR addresses this by only removing inset when developer explicitly sets Margin/HorizontalOptions, indicating they want full control

**PR's Fix Design:**
1. **Stores default inset** (`_defaultStartInset`) on first use
2. **Removes inset** when TitleView is Layout + (Margin OR HorizontalOptions set) - signals developer wants control
3. **Restores default** for other cases (Label, Image, or Layout without custom positioning)

**Why this is correct:**
- Addresses issue #18843 (unwanted margin with custom TitleView layouts)
- Preserves default behavior for simple TitleViews (where the inset provides proper spacing from nav icon)
- Addresses reviewer's "hamburger" concern - hamburger + simple label would keep proper spacing

**Edge cases handled:**
- ✅ TitleView with navigation icon - conditional logic preserves spacing
- ✅ TitleView as Label/Image - restores default inset  
- ✅ TitleView removed dynamically - default can be restored

**Exhausted:** Yes (PR's conditional approach is the correct solution - simpler alternatives would break navigation icon spacing)
**Selected Fix:** PR's fix - Addresses both the bug AND reviewer concerns about navigation icons

</details>

---

**Next Step:** After Gate passes, rea [...]

2026-01-27 19:43 UTC, PureWeen commented
/rebase

2026-03-22 16:48 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-23 15:14 UTC, merged