ContentView also needs to handle InputTransparent
dotnet/maui pull request #21025
Opened 2024-03-05 21:45 UTC by mattleibow

### Description of Change

Not sure yet how this was not found in the tests, but content views also need to handle the input transparent logic separately.

If the flow of input transparency is not specifically handled, the native views will be wrapped with a blanket interceptor. In most cases, this is fine - buttons, labels and images do not have content. However, things like layouts, content views and scroll views do have content that needs to respect the cascading input transparency.

### Issues Fixed

Fixes #21002

2024-03-05 23:35 UTC, mattleibow commented on src/Core/src/Handlers/Layout/LayoutHandler.Android.cs
> +			ViewHandler.MapInputTransparent(handler, layout);
This logic is no longer needed as we do it in the ViewHandler mapper.

2024-03-05 23:35 UTC, mattleibow commented on src/Core/src/Handlers/View/ViewHandler.cs
> +				managing.InputTransparent = view.InputTransparent;
If the native view supports managing its own transparency state, then use that instead of blindly wrapping.

2024-03-05 23:35 UTC, mattleibow commented on src/Core/src/Platform/Tizen/ViewExtensions.cs
> -		internal static bool NeedsContainer(this IView? view)
Merged this with all the others.

2024-03-05 23:35 UTC, mattleibow commented on src/Core/src/ViewExtensions.cs
> +			if (view?.InputTransparent == true && (platformView is null || platformView is not IInputTransparentManagingView))
This line matches the change in the transparency logic - if we can handle it ourselves, we don't wrap.

2024-04-24 13:58 UTC, PureWeen commented
/rebase

2024-04-24 14:01 UTC, jsuarezruiz reviewed
Seems that there are some related tests failing:

```
ScrollViewInputTransparencySimpleMatrix(True,False,False)

Expected string length 65 but was 62. Strings differ at index 55.
Expected: "...t: ScrollViewTransControlIsClickableIsNotPassThru (SUCCESS 1)"
But was:  "...t: ScrollViewTransControlIsClickableIsNotPassThru (FAIL 1)"
```

2024-07-15 06:28 UTC, maonaoda commented
How long will this take to wait?

2024-09-03 11:59 UTC, DavidV1603 commented
Hello,

what is the status of this pull request? It would help me and my app a lot, if this would work again, because it breaks some UIs, and I have not found a work around.

2025-05-08 14:34 UTC, PureWeen requested changes
fix merge conflicts

2026-01-17 14:18 UTC, closed without merging

2026-01-17 14:18 UTC, kubaflo commented
Moving it here: https://github.com/dotnet/maui/pull/33582