Fix display of ActionSheet in modal view on Windows
dotnet/maui pull request #21295
Opened 2024-03-19 06:43 UTC by japarson

### Description of Change

When we call `DisplayActionSheet` from a modal dialog, we encounter an issue with the `MauiContext` at the following line:
https://github.com/dotnet/maui/blob/d03a2c66aa22b8a76eb3adec4235d17f917adf5f/src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs#L212-L216

In this situation, `VirtualView.RequireMauiContext()` will return the `MauiContext` for the `Window`. This is problematic as it causes some strange behavior when converting the view to a `Handler`. Here, we can see that the view's `Handler` will be different from the `Window's `Handler`.
https://github.com/dotnet/maui/blob/d03a2c66aa22b8a76eb3adec4235d17f917adf5f/src/Core/src/Platform/ElementExtensions.cs#L67-L68

As a result, we end up getting a new `Handler` from the `Window`s `MauiContext` and setting it here:
https://github.com/dotnet/maui/blob/d03a2c66aa22b8a76eb3adec4235d17f917adf5f/src/Core/src/Platform/ElementExtensions.cs#L96

When we set the new `Handler`, the modal dialog actually ends up disappearing, while the window itself is still in a modal state, rendering it unusable:
![14829_freeze](https://github.com/dotnet/maui/assets/59936622/2b7b4854-b105-4da5-8ca6-e5d7b56c2457)

Furthermore, we end up getting a null `pageParent` which leads us to attempt showing the `ActionSheet` from the `current` view:
https://github.com/dotnet/maui/blob/d03a2c66aa22b8a76eb3adec4235d17f917adf5f/src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs#L219-L220

However, when we execute this here we end up hitting an exception related to a null `XamlRoot`:
![image](https://github.com/dotnet/maui/assets/59936622/b85d3c34-910d-40db-8f7c-33638ba9f8d5)

To make matters worse, when we catch the exception we attempt to use `UI.Xaml.Window.Current` to show the `ActionSheet` which is also null.
https://github.com/dotnet/maui/blob/d03a2c66aa22b8a76eb3adec4235d17f917adf5f/src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs#L227-L228

We can avoid this whole debacle by using `sender.RequireMauiContext()` instead.

### Demo
![14829_fix](https://github.com/dotnet/maui/assets/59936622/96f40f39-86fc-436e-ad08-89c8fe34444b)

### Issues Fixed

Fixes #14829

2024-03-22 22:34 UTC, PureWeen requested changes

2024-03-22 22:34 UTC, PureWeen commented on src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs
> +					var current = sender.ToPlatform(sender.RequireMauiContext());
can this just be `sender.ToPlatform()`

At this point the sender should already have handler and all we're wanting to do here is retrieve it

2024-03-27 12:19 UTC, jsuarezruiz approved these changes

2024-03-27 22:15 UTC, PureWeen approved these changes

2024-03-27 22:15 UTC, merged