[iOS] Disabled Editors Show Keyboard Partially When Tapped - Fix
dotnet/maui pull request #21347
Opened 2024-03-21 00:58 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/21059

|Before|After|
|--|--|
|<img src="https://github.com/dotnet/maui/assets/42434498/1d18ce6e-be7d-4141-91af-05cfd17d4561" width="300px"/>|<img src="https://github.com/dotnet/maui/assets/42434498/37d5c84b-2789-415e-9a07-2ac6359a1cd4" width="300px"/>|

2024-03-21 10:02 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2024-03-21 15:40 UTC, PureWeen commented
@tj-devel709

2024-04-03 13:41 UTC, jsuarezruiz commented
Added pending snapshot for the added test.

2024-04-19 10:34 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2024-05-10 08:54 UTC, jsuarezruiz commented
@tj-devel709 Thoughts?

2024-06-01 16:19 UTC, PureWeen requested changes

2024-06-01 16:19 UTC, PureWeen commented on src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
> +				var _accessoryView = new MauiDoneAccessoryView();
Can this check if the accessory view has already been set and then just not re-instantiate it?

2024-06-02 09:18 UTC, PureWeen commented on src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
> +				handler.PlatformView.InputAccessoryView = null;
only set this to null if the InputAccessoryView type is MauiDoneAccessoryView

2024-06-04 08:18 UTC, jsuarezruiz commented
/azp run

2025-08-23 03:58 UTC, PureWeen commented
/rebase

2026-01-11 00:15 UTC, kubaflo commented
# PR Review: #21347 - [iOS] Disabled Editors Show Keyboard Partially When Tapped

**Date:** 2026-01-10 | **Issue:** [#21059](https://github.com/dotnet/maui/issues/21059) | **PR:** [#21347](https://github.com/dotnet/maui/pull/21347)

## ⏳ Status: IN PROGRESS - CRITICAL TEST ISSUE FOUND

| Phase | Status |
|-------|--------|
| Pre-Flight | ✅ COMPLETE |
| 🧪 Tests | ✅ COMPLETE |
| 🚦 Gate | ❌ FAILED - Test Cannot Detect Bug |
| 🔧 Fix | ⏳ PENDING (Blocked by Gate) |
| 📋 Report | ⏳ PENDING |

---

<details>
<summary><strong>📋 Issue Summary</strong></summary>

**Issue #21059**: Tapping on any disabled editor will show a small bar at the bottom of the screen with a "Done" button. As you can see in the example I have one editor that is enabled and one that is disabled and alternate tapping on each one. If an editor is disabled I don't think it should show anything at all when tapping on it.

**Steps to Reproduce:**
1. Create a new .NET MAUI 8 project
2. On MainPage.xaml add an editor and set its IsEnabled property to be false
3. Run the app on iOS and tap on the editor to see the issue

**Platforms Affected:**
- [x] iOS
- [ ] Android
- [ ] Windows
- [ ] MacCatalyst

**Regression:** No, this is something new

**Version with bug:** 8.0.7 SR2

</details>

<details>
<summary><strong>📁 Files Changed</strong></summary>

| File | Type | Changes |
|------|------|---------|
| `src/Core/src/Handlers/Editor/EditorHandler.iOS.cs` | Fix | +8 -1 lines |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue21059.xaml` | Test | +11 lines |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue21059.xaml.cs` | Test | +15 lines |
| `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21059.cs` | Test | +30 lines |
| `src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarShouldNotBeVisibleAfterClickingDisabledEditor.png` | Test | Binary |

</details>

<details>
<summary><strong>💬 PR Discussion Summary</strong></summary>

**Key Comments:**
- @PureWeen assigned @tj-devel709 (March 21, 2024)
- @jsuarezruiz added pending snapshot for the test (April 3, 2024)
- @jsuarezruiz pinged @tj-devel709 for thoughts (May 10, 2024)
- @PureWeen requested rebase (August 23, 2025)

**Inline Code Review Comments:**

| File:Line | Reviewer Says | Status |
|-----------|---------------|--------|
| EditorHandler.iOS.cs:137 | @PureWeen: "Can this check if the accessory view has already been set and then just not re-instantiate it?" | ⚠️ INVESTIGATE |
| EditorHandler.iOS.cs:150 | @PureWeen: "only set this to null if the InputAccessoryView type is MauiDoneAccessoryView" | ⚠️ INVESTIGATE |

**Note:** Line references in comments may refer to an earlier version of the PR before changes.

**Author Uncertainty:**
- None explicitly stated

</details>

<details>
<summary><strong>🧪 Tests</strong></summary>

**Status**: ✅ COMPLETE

- [x] PR includes UI tests
- [x] Tests compile successfully
- [x] Tests follow naming convention (`Issue21059`)
- ⚠️ **Test Quality Issue**: Relies solely on screenshot verification (see Gate findings)

**Test Files:**
- HostApp: `src/Controls/tests/TestCases.HostApp/Issues/Issue21059.xaml[.cs]`
- NUnit: `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21059.cs`
- Snapshot: `src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarShouldNotBeVisibleAfterClickingDisabledEditor.png`

**Test Type:** UI Tests (iOS only, using screenshot verification)

**Test Scenario:**
1. Page with disabled Editor (IsEnabled=False)
2. Test clicks on the disabled editor
3. Waits 500ms for animation
4. Verifies via screenshot that no toolbar appears at bottom

</details>

<details>
<summary><strong>🚦 Gate - Test Verification</strong></summary>

**Status**: ❌ FAILED - Test Cannot Properly Detect Bug

**Critical Issue Found:**
The test uses screenshot-based verification (`VerifyScreenshot()`) but the baseline snapshot was created WITH the fix applied. This makes the test unable to catch regressions.

**Test Results:**
- ❌ **WITHOUT fix**: Test PASSED (unexpected - should have FAILED to detect bug)
- ✅ **WITH fix**: Test PASSED (expected)

**Root Cause:**
Screenshot comparison tests can only verify "no visual regression from baseline" but cannot verify "bug is actually fixed" unless baseline was created WITHOUT the fix. The baseline `ToolbarShouldNotBeVisibleAfterClickingDisabledEditor.png` was created after the fix was applied, so it shows the correct state (no toolbar). When tested without the fix:
1. The screenshot comparison doesn't detect the toolbar appearing
2. Timing issues (500ms delay) might mean toolbar state varies
3. Screenshot tolerance settings may allow the difference

**Recommended Fix Approaches:**
1. **Programmatic verification** (Best): Query the InputAccessoryView.Hidden property or check view hierarchy
2. **Baseline recreation**: Create baseline WITHOUT the fix, verify it fails, then apply fix
3. **Hybrid approach**: Both screenshot AND programmatic check

**Result:** Gate FAILED - Test does not properly validate the fix catches the bug

</details>

<details>
<summary><strong>🔧 Fix Candidates</strong></summary>

**Status**: ⏳ PENDING

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #21347 | Explicitly hide MauiDoneAccessoryView in MapIsEnabled when editor is disabled | ⏳ PENDING (Gate) | `EditorHandler.iOS.cs` (+8/-1) | Original PR - adds check in MapIsEnabled before calling UpdateIsEnabled |

**Exhausted:** No
**Selected Fix:** PENDING

</details>

---

**Next Step:** ⛔ GATE BLOCKED - Tests cannot properly detect the bug. Must fix test or accept limitation before continuing to Phase 4.

2026-01-11 00:15 UTC, closed without merging

2026-01-11 00:15 UTC, kubaflo commented
Working fine in net10