fix issue in orientation of images
dotnet/maui pull request #21458
Opened 2024-03-26 15:56 UTC by stephen-hawley

### Description of Change

Added code to retrieve image orientation from the metadata, translate it and apply it to the image constructor.

### Issues Fixed

Fixes #21314

In brief, pull the image properties from the `CGImageSource` and translate it to the values for the UIImage constructor.
The conversion code was based on this [documentation](https://developer.apple.com/documentation/imageio/cgimagepropertyorientation?language=objc) from Apple.

2024-03-26 16:03 UTC, PureWeen commented
/azp run

2024-03-26 16:23 UTC, dalexsoto submitted a review, later dismissed
❤️

2024-03-27 11:47 UTC, rmarinho commented on src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs
> +		static UIImageOrientation ToUIImageOrientation (CGImageSource cgImageSource)
The code format is not quite right :) seems mono days? we provide the rules in a .editorconfig.. 

Our dotnet format on this file only will also work.

2024-03-27 11:48 UTC, rmarinho commented
Will this be a breaking change? Like before images will always appear UP and now can show in a different orientation? Should we target this only to net9 ?

2024-03-28 23:32 UTC, PureWeen requested changes
Can you add a UITest? our docs are somewhat lacking in that area but you can see an example here.

https://github.com/dotnet/maui/pull/20352

2024-04-12 15:13 UTC, stephen-hawley commented
/azp run

2024-04-12 22:06 UTC, mattleibow commented
/azp run

2024-04-13 07:11 UTC, mattleibow approved these changes, later dismissed

2024-04-13 13:38 UTC, PureWeen commented
/rebase

2024-04-13 16:55 UTC, PureWeen commented
/azp run

2024-04-14 14:59 UTC, PureWeen commented
/azp run

2024-04-14 22:43 UTC, PureWeen approved these changes

2024-04-14 22:44 UTC, PureWeen commented
Test failures unrelated

2024-04-14 22:45 UTC, merged