[Windows] Prevent image from covering text in buttons if the image is too big
dotnet/maui pull request #21516
Opened 2024-03-28 21:05 UTC by Foda

### Description of Change

Prevent image from covering text in buttons if the image is too big to fit.

Before:
![image](https://github.com/dotnet/maui/assets/890772/c4857267-fd76-4e67-bae1-2e0b9fb79bcd)

After:
![image](https://github.com/dotnet/maui/assets/890772/f531679d-9544-4323-bb25-1ca02479ee31)

### Issues Fixed

Fixes #21513

2024-03-28 23:09 UTC, PureWeen commented on src/Controls/tests/UITests/Tests/Issues/Issue21513.cs
> +			this.IgnoreIfPlatforms(new [] { TestDevice.Mac, TestDevice.iOS, TestDevice.Android });
Can you also run this on android and generate the images there? Hopefully they are the same and we don't have to fix anything on android

2024-03-29 23:05 UTC, PureWeen requested changes
It looks like this breaks line break 

```XAML
 <VerticalStackLayout>
     <Button ImageSource="dotnet_bot.png" LineBreakMode="WordWrap" Text="awiohe fiawefhawifh awiuefh awiuefh wiauefh iawefhawiuefh awiuefh awiuefh awiufh awuiefh wiauefh wuiaefh awiuefh "></Button>
 </VerticalStackLayout>
 ```
![image](https://github.com/dotnet/maui/assets/5375137/495f9c8e-ed4e-4e90-96d2-dabe4fe3b4ab)


here's main
![image](https://github.com/dotnet/maui/assets/5375137/6ef77020-d48f-4717-8d00-36a3af0c0353)

2024-04-02 11:37 UTC, jsuarezruiz approved these changes, later dismissed
LGTM. Tested with different fonts, font sizes, character spacing etc.
![issue-21513](https://github.com/dotnet/maui/assets/6755973/2a37897b-d77a-409f-9ea9-ae4bebce20be)

2024-04-05 21:14 UTC, PureWeen approved these changes

2024-04-06 00:32 UTC, merged