Fix null reference exception in KeyboardAutoManagerScroll when UIWindow is null
dotnet/maui pull request #21753
Opened 2024-04-10 10:46 UTC by Axemasta

### Description of Change

There is a `NullReferenceException` being thrown by the `KeyboardAutoManagerScroll` during specific scenarios such as using a [BottomSheet](https://github.com/the49ltd/The49.Maui.BottomSheet) and focussing an `Editor` control.

After raising the issue @Larhei noted that this crash is also happening within the `SearchHandler` so its not just external libraries that are affected.

I have added a null check to return early from `AdjustPosition` if the `UIWindow` is `null`.

### Issues Fixed

Fixes #21726

### Methodology

I have verified this locally by referencing the [BottomSheet](https://github.com/the49ltd/The49.Maui.BottomSheet) library (at great pain I might add... I had to reference the source locally and remove all nugets 🤦‍♂️) and then verifying the issue happened on the `Maui.Controls.Sample` app.

I then debugged through the `KeyboardAutoManagerScroll` class to verify where the `NullReferenceException` was throwing, added a null check + return and then verified my example worked at runtime.

I have attached a video of the sample app, the `UIWindow` showing null in the debugger & the crash no longer happening on my fix branch.

https://github.com/dotnet/maui/assets/33064621/c807a490-da94-46d8-ad69-b8f7291af564

2024-04-10 11:15 UTC, rmarinho commented
/azp run MAUI-UITests-public

2024-04-12 18:18 UTC, tj-devel709 commented
Hi, great catch and thank you very much for the reproduction. I was able to reproduce on my end as well. I am curious and will look a little deeper at this issue and see why the Window is null in this case and the searchHandler!

2024-04-12 18:39 UTC, Larhei commented
Hi @tj-devel709,

my nullpointer from Searchhandler was because I am calling EndEdit on the UiSearchbar of the Searchhandler when navigating to my page. I want to move the Carret out of the Searchhandler when user switched Tab. So this is triggering  KeyboardAutoManagerScroll In my case. Workout for me KeyboardAutoManagerScroll.Detatch , endedit and KeyboardAutoManagerScroll.Connect. But Wy Window is null. Good Question.

2024-04-19 10:18 UTC, jsuarezruiz commented
/azp run

2024-04-19 15:38 UTC, tj-devel709 commented
https://github.com/dotnet/maui/assets/50846373/5643fb66-eb4b-4ef8-9af0-ad4095127cd6

Added another check to bail from the KeyboardScrolling if the current View that was focused is not inside the ContainerViewController that was found. This will make sure that we are not trying to use the wrong ContentViewController as well which happens when using the BottomSheet plugin and possibly other third-party libraries when calling the sheet from a modal. 

This should fix https://github.com/dotnet/maui/issues/21160 as well!

2024-04-19 15:41 UTC, tj-devel709 commented
/azp run

2024-04-19 19:05 UTC, tj-devel709 commented
/azp run

2024-04-19 19:22 UTC, tj-devel709 commented
Sorry about the force push - accidentally messed up branch but looks back to normal now!

2024-04-19 19:22 UTC, tj-devel709 commented
/azp run

2024-04-23 13:01 UTC, PureWeen requested changes
Wait until https://github.com/dotnet/maui/pull/21951 is merged

2024-04-24 20:26 UTC, tj-devel709 commented
The above has been merged! I will throw on a UITest before we merge this one though to be sure we don't regress this behavior in the future!

2024-04-26 14:15 UTC, tj-devel709 commented
/azp run

2024-04-26 14:17 UTC, PureWeen approved these changes

2024-04-26 16:29 UTC, PureWeen commented
Failing test is unrelated and will be fixed by
https://github.com/dotnet/maui/pull/22081

2024-04-26 16:29 UTC, merged