IndexOf() stackOverflow fix (#20083)
dotnet/maui pull request #21965
Opened 2024-04-21 11:49 UTC by kubaflo

### Description of Change

A small correction to this PR: https://github.com/dotnet/maui/pull/20083 that fixes the StackOverflow exception

<img width="933" alt="Screenshot 2024-04-21 at 13 34 51" src="https://github.com/dotnet/maui/assets/42434498/a9ad0c43-507c-4229-8164-375a63e063c7">

<img width="801" alt="Screenshot 2024-04-21 at 13 46 06" src="https://github.com/dotnet/maui/assets/42434498/79084dc6-a28e-4ea7-a066-f26bbf693f5a">

### Issues Fixed

Fixes https://github.com/dotnet/maui/pull/20083

2024-04-21 16:02 UTC, symbiogenesis commented
I would change lines 150-153 to the following and leave everything else unchanged.

```csharp
if (enumerable is List<T> list)
{
	var predicateNew = new Predicate<T>(predicate);
	return list.FindIndex(predicateNew);
}
```

2024-04-21 17:17 UTC, kubaflo commented
> This won't fix it. There is an infinite recursive loop. Sorry about that! Good catch.
> 
> I would replace lines 150-153 with the following and leave everything else unchanged.
> 
> ```cs
> if (enumerable is List<T> list)
> {
> 	var listPredicate = new Predicate<T>(predicate);
> 	return list.FindIndex(listPredicate);
> }
> 
> if (enumerable is T[] array)
> {
> 	var arrayPredicate = new Predicate<T>(predicate);
> 	return Array.FindIndex(array, arrayPredicate);
> }
> ```

The solution that I'm proposing fixes it - I tested it

2024-04-21 17:19 UTC, symbiogenesis commented
> > This won't fix it. There is an infinite recursive loop. Sorry about that! Good catch.
> > I would replace lines 150-153 with the following and leave everything else unchanged.
> > ```cs
> > if (enumerable is List<T> list)
> > {
> > 	var listPredicate = new Predicate<T>(predicate);
> > 	return list.FindIndex(listPredicate);
> > }
> > 
> > if (enumerable is T[] array)
> > {
> > 	var arrayPredicate = new Predicate<T>(predicate);
> > 	return Array.FindIndex(array, arrayPredicate);
> > }
> > ```
> 
> The solution that I'm proposing fixes it - I tested it

I think testing more would show that it still isn't fixed, because the self-referential call. The code I propose should also fix it, with no other changes on any lines.

2024-04-21 17:21 UTC, kubaflo commented
> > > This won't fix it. There is an infinite recursive loop. Sorry about that! Good catch.
> > > I would replace lines 150-153 with the following and leave everything else unchanged.
> > > ```cs
> > > if (enumerable is List<T> list)
> > > {
> > > 	var listPredicate = new Predicate<T>(predicate);
> > > 	return list.FindIndex(listPredicate);
> > > }
> > > 
> > > if (enumerable is T[] array)
> > > {
> > > 	var arrayPredicate = new Predicate<T>(predicate);
> > > 	return Array.FindIndex(array, arrayPredicate);
> > > }
> > > ```
> > 
> > 
> > The solution that I'm proposing fixes it - I tested it
> 
> I think testing more would show that it still isn't fixed, because the self-referential call. The code I propose should fix it, with no other changes on any lines.

Yep, your fix works

2024-04-22 10:51 UTC, rmarinho commented
/azp run

2024-04-22 11:38 UTC, jsuarezruiz commented on src/Core/src/Extensions/EnumerableExtensions.cs
> +			if (enumerable is List<T> list)
Could we include some unit tests?

2024-04-22 15:08 UTC, rmarinho requested changes
Yeah, since it passed the first time, would be great to add a test to reproduce the issue so it doesn't happen again

2024-04-22 15:37 UTC, symbiogenesis commented
Added them here:

https://github.com/dotnet/maui/pull/21978

2024-04-22 15:41 UTC, kubaflo commented
@rmarinho so can we please merge these 2 PRs since it is annoying that we cannot debug now without making these changes to the source code

2024-04-22 15:48 UTC, merged