Optimize ordering of children in Flex layout
dotnet/maui pull request #21961
Opened 2024-04-20 18:39 UTC by symbiogenesis

This had a TODO comment to use mergesort, but LINQ offers a highly optimized quicksort that would be just as good.
 
Before:

| Method                    | Mean     | Error     | StdDev    | Median   | Gen0     | Completed Work Items | Lock Contentions | Gen1     | Gen2    | Allocated |
|-------------------------- |---------:|----------:|----------:|---------:|---------:|---------------------:|-----------------:|---------:|--------:|----------:|
| LayoutLotsOfItemsWithWrap | 6.331 ms | 0.7514 ms | 2.2156 ms | 4.612 ms | 171.8750 |                    - |                - | 140.6250 | 31.2500 |   1.57 MB |
| LayoutLotsOfItemsNoWrap   | 4.432 ms | 0.0798 ms | 0.0747 ms | 4.402 ms | 171.8750 |                    - |                - | 140.6250 | 31.2500 |   1.57 MB |

After:

| Method                    | Mean     | Error     | StdDev    | Median   | Gen0     | Completed Work Items | Lock Contentions | Gen1     | Gen2    | Allocated |
|-------------------------- |---------:|----------:|----------:|---------:|---------:|---------------------:|-----------------:|---------:|--------:|----------:|
| LayoutLotsOfItemsWithWrap | 4.513 ms | 0.2016 ms | 0.5312 ms | 4.336 ms | 171.8750 |                    - |                - | 132.8125 | 39.0625 |   1.56 MB |
| LayoutLotsOfItemsNoWrap   | 4.479 ms | 0.0850 ms | 0.0754 ms | 4.470 ms | 171.8750 |                    - |                - | 132.8125 | 39.0625 |   1.56 MB |

2024-04-21 06:44 UTC, symbiogenesis commented on src/Core/src/Layouts/Flex.cs
> +									.OrderBy(x => x.value.Order)
True. I did check that OrderBy is a stable sort. I could leave a comment about that being a requirement.

2024-04-22 10:52 UTC, rmarinho commented
/azp run

2024-04-23 12:10 UTC, mattleibow commented
> Another idea: Having a struct for value+index might lead to better perf. I'm not too sure what { value, index } will create, if a struct or a class behind the scenes.

@MartyIX can you use a value tuple? `(value, index)` Does that make a difference with allocations or something?

2024-04-23 17:25 UTC, mattleibow commented
Do you have the new numbers for this?

>  I think the most recent change should remove them entirely.

2024-04-23 17:27 UTC, mattleibow commented
Can we add some tests to demonstrate the old code and new code are equivalent? Or at least verify there are tests for this case.

2024-05-10 06:33 UTC, jsuarezruiz commented
/azp run

2024-08-23 16:42 UTC, jonathanpeppers commented on src/Core/src/Layouts/Flex.cs
> +									.ToArray();
If you test an example without System.Linq, does it perform slightly better?
* https://stackoverflow.com/a/17399982

A plain `for-loop` to create an array, and `Array.Sort()` might be able to do the job really well.

2024-08-23 19:21 UTC, jonathanpeppers commented on src/Core/src/Layouts/Flex.cs
> +									.ToArray();
If it has to be stable, this might be the best option.

2025-06-07 00:40 UTC, mattleibow commented
/rebase

2025-06-07 00:45 UTC, mattleibow commented
@symbiogenesis do you perhaps still have the benchmark code lying around? I see there is a `FlexLayoutBenchmarker`but that is maybe for something else?

2025-06-07 00:46 UTC, mattleibow commented
@jonathanpeppers it has been a while, but did you have any more thoughts?

2025-06-07 00:49 UTC, mattleibow approved these changes

2025-06-07 00:56 UTC, mattleibow requested changes
Both Copilot and Chat GPT say the indices are not the same

Let's analyze and compare the two algorithms in .NET:

### First Algorithm

```cs
var indices = new int[item.Count];
for (int i = 0; i < item.Count; i++)
{
    indices[i] = i;
    for (int j = i; j > 0; j--)
    {
        int prev = indices[j - 1];
        int curr = indices[j];
        if (item[prev].Order <= item[curr].Order)
        {
            break;
        }
        indices[j - 1] = curr;
        indices[j] = prev;
    }
}
```

- This is an **insertion sort** on the indices of `item`, sorting by `item[i].Order`.
- It is **stable**: equal elements retain their original order because the `<=` comparison ensures that if two elements are equal, the earlier one stays before the later one.
- The result, `indices`, is an array of the original indices, sorted by `item[i].Order`.

### Second Algorithm

```cs
var indices = item.OrderBy(x => x.Order)
                  .Select((value, index) => index)
                  .ToArray();
```

- This uses LINQ's `OrderBy`, which is a **stable sort** (guaranteed by .NET).
- However, `.Select((value, index) => index)` returns the index in the sorted sequence, not the original index.
- If you want the original indices, you should use:
  ```cs
  var indices = item.Select((x, i) => new { x, i })
                    .OrderBy(x => x.x.Order)
                    .Select(x => x.i)
                    .ToArray();
  ```
- As written, the second algorithm does **not** return the same result as the first. The first returns the original indices in sorted order; the second returns the new indices (0, 1, 2, ...) after sorting.

### Equivalence

- **Not equivalent as written.**  
  - The first returns original indices sorted by `Order`.
  - The second returns the new positions (0, 1, 2, ...) after sorting, not the original indices.

### Stability

- **Both are stable sorts** (insertion sort and LINQ's `OrderBy`).

---

**Summary:**
- The first algorithm is a stable insertion sort on indices.
- The second, as written, is not equivalent and does not return the same result.
- To make the second equivalent, use:
  ```cs
  var indices = item.Select((x, i) => new { x, i })
                    .OrderBy(x => x.x.Order)
                    .Select(x => x.i)
                    .ToArray();
  ```
- Both are stable sorts.

2025-06-09 14:47 UTC, jonathanpeppers commented
@mattleibow I don't know if I trust the AI comments, because it hallucinated invalid code:

```csharp
var indices = item.Select((x, i) => new { x, i }) // Why using new?
                  .OrderBy(x => x.x.Order) // Ok, maybe .x.x is Psuedocode?
                  .Select(x => x.i) // But then if this is an int, what is .i?
                  .ToArray();
```

Should we just prove out the new code with a unit test or two?

We could check `Children` with the same `Order` are stable sorted?

2025-06-09 14:49 UTC, jonathanpeppers commented on src/Core/src/Layouts/Flex.cs
> -					var indices = new int[item.Count];
An alternate idea would be to use `ArrayPool<int>` here, as it's a temporary array.

2025-06-09 14:49 UTC, jonathanpeppers commented on src/Core/src/Layouts/Flex.cs
> +									.ToArray();
I generally like this over the old code, because it's way more understandable. 👍

2026-03-08 11:21 UTC, kubaflo commented
## Summary

Replaces the manual insertion sort in `Flex.cs` with `Enumerable.Range(0, item.Count).OrderBy(i => item[i].Order)` — a correct, readable, and stable LINQ sort.

## Problem

PR #21961 attempted this optimization but introduced a **correctness bug**:

```csharp
// ❌ BROKEN — always produces [0, 1, 2, ...] regardless of Order values
var indices = item.OrderBy(x => x.Order)
                  .Select((value, index) => index)
                  .ToArray();
```

After `OrderBy` sorts the items, `.Select((value, index) => index)` returns the position in the *sorted* sequence (always `0, 1, 2, …`), not the original child indices. This makes `ordered_indices` a no-op identity mapping.

## Fix

```csharp
// ✅ CORRECT — sorts original indices by child Order, stable sort guaranteed
ordered_indices = Enumerable.Range(0, item.Count)
    .OrderBy(i => item[i].Order)
    .ToArray();
```

This creates indices `[0, 1, 2, …]` then reorders them by the `Order` property of the corresponding child. LINQ's `OrderBy` is guaranteed stable in .NET.

## Tests Added

4 new tests in `FlexOrderTests.cs`:
- **TestReverseOrderingElements** — reversed Order values
- **TestStableSortPreservesInsertionOrder** — children with equal Order retain insertion order
- **TestNegativeOrderValues** — negative Order sorts before zero
- **TestOrderWithRowDirection** — ordering works in horizontal layout

All 5 FlexOrder tests pass ✅

## Performance

This change provides the same algorithmic improvement as #21961 (O(n log n) vs O(n²) insertion sort) while being **correct**. The allocation profile is similar — one `int[]` array via `ToArray()`.

2026-03-08 11:46 UTC, kubaflo commented
<!-- AI Summary -->

## 🤖 AI Summary

<!-- SECTION:PR-REVIEW -->
<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fix Flex layout child ordering: use correct LINQ stable sort</strong> · <a href="https://github.com/dotnet/maui/commit/2eca877e1b610a5eb8ad6358f7df6b2f645be7b3"><code>2eca877</code></a></summary>

---

**PR:** #21961 - Optimize ordering of children in Flex layout
**Author:** symbiogenesis (Edward Miller) - Community Contribution ✨
**Labels:** area-layout, community ✨, layout-flex, perf/general
**URL:** https://github.com/dotnet/maui/pull/21961

**Type:** Performance optimization / refactoring (not a bug fix for a user-facing bug)
**Platforms Affected:** All (cross-platform change to `Flex.cs`)

### Summary

Replaces the manual insertion sort in `Flex.cs` with LINQ `Enumerable.Range(0, item.Count).OrderBy(i => item[i].Order)` for better readability and O(n log n) performance vs O(n²) insertion sort.

### Files Changed

**Fix files (1):**
- `src/Core/src/Layouts/Flex.cs` (+7, -22)

**Test files (1):**
- `src/Controls/tests/Core.UnitTests/FlexOrderTests.cs` (+119, -0) — unit tests

**Test type:** Unit Tests (Core.UnitTests)

### Key Findings

1. **Correctness Bug (Now Fixed):** An earlier version of this PR had a broken LINQ expression: `item.OrderBy(x => x.Order).Select((value, index) => index).ToArray()`. This always returned `[0, 1, 2, ...]` regardless of Order values, making it a no-op identity mapping. Reviewers (mattleibow, jonathanpeppers, Copilot) flagged this.

2. **Current Code is Correct:** The PR was updated to use `Enumerable.Range(0, item.Count).OrderBy(i => item[i].Order).ToArray()`, which correctly sorts original indices by each child's Order property.

3. **Stability is Preserved:** LINQ's `OrderBy` is guaranteed stable in .NET (unlike `Array.Sort`). The original insertion sort was also stable. The requirement for stable sort is preserved.

4. **Performance Improvement:** Benchmarks show ~29% improvement when items have no wrap (wrapping case also improved).

5. **Tests Added:** 4 new unit tests covering: reversed ordering, stable sort with equal Order, negative Order values, and Row direction ordering.

### Reviewer Discussion

| File:Line | Reviewer | Concern | Status |
|-----------|----------|---------|--------|
| Flex.cs:994 | MartyIX | Should comment about OrderBy stability requirement | Addressed in code comment |
| Flex.cs:996 | jonathanpeppers | Consider ArrayPool<int> for temp array | Open suggestion |
| Flex.cs:996 | jonathanpeppers | Array.Sort without LINQ might be faster | MartyIX notes it's not stable; resolved |
| Flex.cs:993 | mattleibow (CHANGES_REQUESTED) | Original LINQ was incorrect — not equivalent | Fixed with Enumerable.Range approach |
| (comment) | kubaflo | Posted alternative fix analysis confirming correctness issue and proposing same fix | Corroborates current approach |

**Prior Copilot review comment:** flagged that `.Select((value, index) => index)` returns position in sorted sequence, not original index.

**mattleibow** had `CHANGES_REQUESTED` then later `APPROVED` — the fix was accepted.

### Fix Candidates Table

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #21961 | Replace insertion sort with `Enumerable.Range(0, n).OrderBy(i => item[i].Order).ToArray()` | ⏳ PENDING (Gate) | `Flex.cs` (-22/+7) | Original PR (corrected after initial review) |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fix Flex layout child ordering: use correct LINQ stable sort</strong> · <a href="https://github.com/dotnet/maui/commit/2eca877e1b610a5eb8ad6358f7df6b2f645be7b3"><code>2eca877</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** N/A (Unit Tests — cross-platform)
**Mode:** Unit Test Verification (refactoring PR — standard fail/pass Gate not applicable)

### Notes on Gate Mode

This PR is a **performance optimization / refactoring**, not a bug fix for a user-facing bug. The `verify-tests-fail-without-fix` skill targets UI tests; this PR uses unit tests only. The traditional "tests FAIL without fix, PASS with fix" cycle doesn't apply because both the old insertion sort and the new LINQ implementation are functionally correct.

Instead, Gate verified that the unit tests confirm the new LINQ implementation produces correct behavior.

### Test Results

| Test | Result |
|------|--------|
| TestOrderingElements (pre-existing) | ✅ PASS |
| TestReverseOrderingElements | ✅ PASS |
| TestStableSortPreservesInsertionOrder | ✅ PASS |
| TestNegativeOrderValues | ✅ PASS |
| TestOrderWithRowDirection | ✅ PASS |

**Total: 5/5 passed** (3.69 seconds)

### Interpretation
The new `Enumerable.Range(0, item.Count).OrderBy(i => item[i].Order).ToArray()` implementation is behaviorally equivalent to the original insertion sort. Tests confirm:
- Correct ordering (high Order → later position)
- Stable sort (equal Order values preserve insertion order)
- Negative Order values sort correctly
- Works in both Column and Row directions

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fix Flex layout child ordering: use correct LINQ stable sort</strong> · <a href="https://github.com/dotnet/maui/commit/2eca877e1b610a5eb8ad6358f7df6b2f645be7b3"><code>2eca877</code></a></summary>

---

## Phase 3: Fix Analysis

### Why try-fix Skill Was Not Used

This PR is a **performance optimization / refactoring** (not a bug fix). The try-fix skill requires a "broken baseline" where tests fail without the fix. For this PR:
- The original insertion sort code is **functionally correct** (tests pass)
- The PR's LINQ code is **also correct** (tests also pass)
- There is no broken baseline to revert to

Additionally, the tests are **unit tests** (not UI/device tests), so the `BuildAndRunHostApp.ps1` test command doesn't apply.

Instead, a code analysis was performed to evaluate alternative implementation approaches.

---

### Fix Candidates — Alternative Implementations Analyzed

| # | Approach | Correct | Stable | Performance | Notes |
|---|----------|---------|--------|-------------|-------|
| PR | `Enumerable.Range(0, n).OrderBy(i => item[i].Order).ToArray()` | ✅ | ✅ | O(n log n) | Clean, readable, one int[] allocation |
| 1 | `item.OrderBy(x => x.Order).Select((v, i) => i).ToArray()` | ❌ | ✅ | O(n log n) | **Bug**: returns 0,1,2,… always (early PR version) |
| 2 | `item.Select((x, i) => new { x, i }).OrderBy(x => x.x.Order).Select(x => x.i).ToArray()` | ✅ | ✅ | O(n log n) | ⚠️ Allocates anonymous objects on heap |
| 3 | `item.Select((x, i) => (x, i)).OrderBy(t => t.x.Order).Select(t => t.i).ToArray()` | ✅ | ✅ | O(n log n) | ✅ ValueTuple (struct), less allocation than #2 |
| 4 | Insertion sort (original) | ✅ | ✅ | O(n²) | Correct but slower, harder to read |
| 5 | `Array.Sort()` with custom comparer | ✅ | ❌ | O(n log n) | Not stable by default; more complex to make stable |
| 6 | `Enumerable.Range` + `ArrayPool<int>` | ✅ | ✅ | O(n log n) | ✅ Reduces GC pressure; ⚠️ Requires manual pool return |

### Analysis Notes

**Candidate 1 (rejected):** This was the initial version of the PR. Multiple reviewers (mattleibow, jonathanpeppers, copilot-pull-request-reviewer, kubaflo) identified that `.Select((value, index) => index)` returns the position in the *sorted sequence* (always 0,1,2,...), not the original index. The PR author corrected this.

**Candidate 2 vs 3:** Both are correct alternatives. ValueTuple (#3) is slightly better than anonymous types (#2) due to struct vs heap allocation, but both add complexity compared to the PR's approach.

* [...]

2026-03-08 18:44 UTC, merged