Add converters to DatePicker and TimePicker for DateOnly and TimeOnly, respectively
dotnet/maui pull request #21989
Opened 2024-04-23 03:13 UTC by symbiogenesis

I realize that full DateOnly and TimeOnly support is not implemented yet. This is a start in that direction.

Fixes https://github.com/dotnet/maui/issues/20438

As mentioned in the comments there, fixing that bug is merely a subset of https://github.com/dotnet/maui/issues/1100 which can be fixed without the need for a full implementation.

2024-04-23 08:10 UTC, jsuarezruiz commented
/azp run

2024-05-10 10:14 UTC, jsuarezruiz commented
There are some compilation errors:

`D:\a\_work\1\s\src\Controls\src\Core\TimePicker\TimePicker.cs(71,47): error CS0246: The type or namespace name 'TimeOnlyConverter' could not be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]`

2024-06-06 00:53 UTC, symbiogenesis commented
> There are some compilation errors

Should be fixed now

2024-06-25 15:30 UTC, symbiogenesis commented
@Eilon

2024-08-07 14:46 UTC, symbiogenesis commented on src/Controls/src/Core/TimePicker/TimePicker.cs
> +#if NET6_0_OR_GREATER
It was explained to me in another PR that netstandard2.0 support will be maintained for the foreseeable future

https://github.com/dotnet/maui/pull/19965#event-13464335155

2025-01-15 03:35 UTC, symbiogenesis commented
This one would be nice to have. @Foda

2025-01-15 20:55 UTC, Foda commented
> This one would be nice to have. @Foda

A simple unit test would be great!

2025-02-20 23:25 UTC, symbiogenesis commented
> @symbiogenesis are you still interested in completing this one? Else I will take over!

Looks like I had some changes locally that I didn't push, yet. So I just pushed those.

Needs the conflicts resolved. If you could resolve those, I would be appreciative.

2025-02-21 07:58 UTC, jfversluis commented
I don't think adding the properties was part of the plan? The whole point of this was that it would convert TimeOnly and DateOnly to TimeSpan & DateTime right? So that we could use this with the existing properties.

As mentioned in #27930 and #27921 unfortunately we can't use DateOnly and TimeOnly since they are not supported in netstandard. And as you pointed out yourself, we're going to have to support that for a while to come. So this seems like a nice in-between solution :)

2025-02-21 18:53 UTC, symbiogenesis commented
Ok, that makes sense. Must be why I didn't include those earlier.

Added some tests.

2025-04-10 12:09 UTC, jfversluis commented
/azp run MAUI-public

2025-04-21 13:01 UTC, rmarinho commented
/azp run

2025-04-22 09:27 UTC, rmarinho requested changes
Seems some unit tests are failing 
<img width="1073" alt="Screenshot 2025-04-22 at 10 26 54" src="https://github.com/user-attachments/assets/e1096e98-e02e-485a-b703-aeb63a5aff1f" />

2025-04-29 16:27 UTC, rmarinho commented
Needs rebase now

2025-05-07 14:38 UTC, PureWeen requested changes
@StephaneDelcroix review and approve before we merge please

2025-05-08 05:55 UTC, StephaneDelcroix requested changes
Its still very early in the morning, and I'm not properly caffeinated, but the implementation feels reversed:
When a property, or a type, is attributed with a TypeConverter, we expect ConvertFrom to convert to the actual type, or type of property. This is used e.g. by Xaml inflators to convert FROM a string to a DateTime in this sample
ConvertTo takes the value of the type (known to be of type DateTime in your example) to whatever you want to convert it back, like a string for serialisation, or the type in your ViewModel (DateOnly)

Also, this affects the xaml inflation, and will be executed every time you set a date or time in XAML. and instead of relying on default handling will invoke a converter. For perf reasons, the converter should provide a compiled counterpart for XamlC (but only supports convert from string). This also requires a Xaml Unit test that tests the behaviour of this using all inflators

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +public class DateOnlyToDateTimeConverter : TypeConverter, IExtendedTypeConverter
rename to DateTimeTypeConverter

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/TimeOnlyToTimeSpanConverter.cs
> +public class TimeOnlyToTimeSpanConverter : TypeConverter, IExtendedTypeConverter
rename to TimeSpanTypeConverter

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +            return DateOnly.FromDateTime(result);
return value should ba a DateTime

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +            return DateOnly.FromDateTime(dateTime);
should pass-thru and return the DateTime

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +            return DateOnly.FromDateTime(result);
should return a DateTime

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +        throw new NotSupportedException($"Cannot convert \"{value}\" into {typeof(DateOnly)}");
DateTime

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +        if (value is DateOnly dateOnly)
but... value is a DateTime ???

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +        => sourceType == typeof(string) || sourceType == typeof(DateTime);
should also accept a DateOnly

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +        }
and it should support destinationType being DateOnly

2025-05-08 05:55 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateOnlyToDateTimeConverter.cs
> +    public override object ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type? destinationType)
this is the one that matters for the 2-way binding

2025-05-09 21:55 UTC, symbiogenesis commented
> Its still very early in the morning, and I'm not properly caffeinated, but the implementation feels reversed: When a property, or a type, is attributed with a TypeConverter, we expect ConvertFrom to convert to the actual type, or type of property. This is used e.g. by Xaml inflators to convert FROM a string to a DateTime in this sample ConvertTo takes the value of the type (known to be of type DateTime in your example) to whatever you want to convert it back, like a string for serialisation, or the type in your ViewModel (DateOnly)
> 
> Also, this affects the xaml inflation, and will be executed every time you set a date or time in XAML. and instead of relying on default handling will invoke a converter. For perf reasons, the converter should provide a compiled counterpart for XamlC (but only supports convert from string). This also requires a Xaml Unit test that tests the behaviour of this using all inflators

Addressed all the comments. Should handle more conversions now. Did not add XAML tests.

2025-05-14 17:21 UTC, rmarinho commented
> > Its still very early in the morning, and I'm not properly caffeinated, but the implementation feels reversed: When a property, or a type, is attributed with a TypeConverter, we expect ConvertFrom to convert to the actual type, or type of property. This is used e.g. by Xaml inflators to convert FROM a string to a DateTime in this sample ConvertTo takes the value of the type (known to be of type DateTime in your example) to whatever you want to convert it back, like a string for serialisation, or the type in your ViewModel (DateOnly)
> > Also, this affects the xaml inflation, and will be executed every time you set a date or time in XAML. and instead of relying on default handling will invoke a converter. For perf reasons, the converter should provide a compiled counterpart for XamlC (but only supports convert from string). This also requires a Xaml Unit test that tests the behaviour of this using all inflators
> 
> Addressed all the comments. Should handle more conversions now. Did not add the XAMLC counterpart or associated tests.
> 
> Is there perhaps a good example XAMLC converter and associated tests that I could use as a reference?

Heres an example of how to add a test that also runs against xamlc. the boolean tests with and without xamlc enables 

https://github.com/dotnet/maui/blob/main/src/Controls/tests/Xaml.UnitTests/ColorConverter.xaml.cs#L24

2025-06-17 22:13 UTC, rmarinho commented
/azp run

2025-06-19 08:42 UTC, StephaneDelcroix requested changes
DateTime and TimeSpan conversions are built-in, not sure wee ned to add a converter to support xOnly, but we might need to extend the support of the built-in conversion

could you please ad some xaml unit tests ?

also, this would need a compiled converter, or it'll slow xaml inflation of all files with dates or times in it

2025-06-19 08:42 UTC, StephaneDelcroix commented on src/Controls/src/Core/DateTimeTypeConverter.cs
> +public class DateTimeTypeConverter : TypeConverter, IExtendedTypeConverter
no need to implement IExtended, and require the serviceProvider

2025-06-19 08:42 UTC, StephaneDelcroix commented on src/Controls/src/Core/TimeSpanTypeConverter.cs
> +public class TimeSpanTypeConverter : TypeConverter, IExtendedTypeConverter
same

2025-07-03 20:21 UTC, PureWeen requested changes
@symbiogenesis can you rebase and address @StephaneDelcroix 's comments? 

If you don't have time currently just let me know and we can take over

2025-07-25 20:05 UTC, PureWeen commented
https://github.com/dotnet/maui/pull/30790

2025-07-25 20:05 UTC, closed without merging