[Android] Border Stroke gradient can only switch to another gradient - fix
dotnet/maui pull request #22168
Opened 2024-05-02 14:44 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/22042

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/e81549e7-319a-4f4c-82a9-b032fd3f3756" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/928c234d-3530-469b-8dbf-97758462e019" width="300px"/>|

2024-05-03 10:18 UTC, jsuarezruiz commented
/azp run

2024-05-09 08:27 UTC, jsuarezruiz commented
/azp run

2024-05-13 10:22 UTC, jsuarezruiz submitted a review, later dismissed

2024-08-03 21:39 UTC, PureWeen commented
/azp run

2024-08-03 21:40 UTC, PureWeen requested changes

2024-08-03 21:40 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22042.cs
> +			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.iOS, TestDevice.Mac, TestDevice.Windows });
Can you update this to use if/defs instead of "this.IgnoreIfPlatforms"

2024-08-04 00:50 UTC, PureWeen commented
/azp run

2024-08-06 12:20 UTC, PureWeen commented
/azp run

2024-08-06 19:52 UTC, PureWeen commented
/azp run

2024-08-07 16:52 UTC, PureWeen approved these changes

2024-08-07 16:52 UTC, merged