Remove implicit reference to Maui Compatibility and template references
dotnet/maui pull request #22203
Opened 2024-05-03 19:59 UTC by PureWeen

### Description of Change

For new users it's not advantageous (and can be confusing) to have the Maui Compatibility package referenced. Nothing from this package should be used by new projects. 

### TODO
What updates need to be made to the migration tool? Does it already set UseMauiCompat to true?

2024-05-03 22:30 UTC, mattleibow approved these changes

2024-05-07 12:39 UTC, MitchBomcanhao commented
UseMauiCompatibility completely breaks controls based on ContentView on Windows, so we already have to disable it.
see 
https://github.com/dotnet/maui/issues/13739
https://github.com/dotnet/maui/issues/19779

2024-05-13 14:10 UTC, davidortinau submitted a review, later dismissed
When I had tried this previously, the package was always referenced no matter what I did with UseMauiCompat. My expectation is that with these changes, unless the package is directly referenced or UseMauiCompat is explicitly true, then the package will not be included. If I'm reading it correctly, that seems to be the case. Correct?

2024-05-14 18:43 UTC, mattleibow commented
That is correct. After this PR, if you are not adding the package or setting the property, then the compat package should not be included.

2024-05-14 18:43 UTC, mattleibow approved these changes, later dismissed

2024-05-14 18:49 UTC, Eilon requested changes
There's a new template in the house, maui-blazor-solution. Probably needs to be updated too!

2024-05-15 16:39 UTC, PureWeen commented
/rebase

2024-05-15 17:01 UTC, Eilon commented
@PureWeen can you update this file too? https://github.com/dotnet/maui/blob/net9.0/src/Templates/src/templates/maui-blazor-solution/MauiApp.1/MauiApp.1.csproj#L62

2024-05-15 23:20 UTC, Eilon approved these changes

2024-05-16 10:23 UTC, merged