Picker Attribute "SelectedIndex" Not being respected on page load - fix
dotnet/maui pull request #22353
Opened 2024-05-12 14:47 UTC by kubaflo

Fixes https://github.com/dotnet/maui/issues/9150

For the following code:
```
        <Picker FontSize="15"
                AutomationId="picker"
                SelectedIndex="1"
                x:Name="picker">
            <Picker.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>0</x:String>
                    <x:String>1</x:String>
                    <x:String>2</x:String>
                </x:Array>
            </Picker.ItemsSource>
        </Picker>
```

|Before|After|
|--|--|
|<img src="https://github.com/dotnet/maui/assets/42434498/61e7e704-2d8b-4ca2-9453-770a417191c2" width="300px"/>|<img src="https://github.com/dotnet/maui/assets/42434498/62d7e4a6-0e28-4fa9-a03e-00b630bdd987" width="300px"/>|

2024-05-13 05:11 UTC, jsuarezruiz commented
/azp run

2024-05-13 11:10 UTC, jsuarezruiz commented
/azp run

2024-05-20 06:22 UTC, jsuarezruiz commented
/azp run

2024-05-20 11:28 UTC, jsuarezruiz commented
/azp run

2024-06-04 11:20 UTC, jsuarezruiz commented
@kubaflo Could you rebase to fix the conflicts? Thanks in advance.

2024-06-07 23:07 UTC, kubaflo commented
@jsuarezruiz I've rebased and solved conflicts

2024-06-10 16:54 UTC, jsuarezruiz commented
/azp run

2024-06-13 06:47 UTC, jsuarezruiz commented
/azp run

2025-03-10 15:43 UTC, bhavanesh2001 commented
Can this be reviewed?

2025-03-11 03:36 UTC, bhavanesh2001 requested changes
Couple of things I noticed

- If i define my picker something like this 
```c#
 <Picker  SelectedIndex="2"
                Title="Choose an item" SelectedIndexChanged="Picker_SelectedIndexChanged" 
                 >
            <Picker.Items>
                <x:String>Item 1</x:String>
                <x:String>Item 2</x:String>
                <x:String>Item 3</x:String>
                <x:String>Item 4</x:String>
                <x:String>Item 5</x:String>
            </Picker.Items>
        </Picker>
```
this will throw on page load in both iOS and Android

- `SelectedIndexChanged` is getting fired on Page load in `Android`  but not in `iOS` . I think it shouldn't get fired .

2026-02-02 16:38 UTC, closed without merging