Fix null handling in UpdateIndicatorLayout method (#22361)
dotnet/maui pull request #22382
Opened 2024-05-13 22:41 UTC by kubaflo

Fixes https://github.com/dotnet/maui/issues/22361

2024-05-13 22:42 UTC, PureWeen requested changes

2024-05-13 22:42 UTC, PureWeen commented on src/Controls/src/Core/IndicatorView/IndicatorView.cs
> +			else if (indicatorView.IndicatorLayout != null)
```suggestion
			else if (indicatorView.IndicatorLayout is not null)
```

Can you add a unit test as well?

2024-05-13 22:43 UTC, kubaflo commented on src/Controls/src/Core/IndicatorView/IndicatorView.cs
> +			else if (indicatorView.IndicatorLayout != null)
sure

2024-05-14 06:11 UTC, jsuarezruiz commented
/azp run

2024-05-14 12:58 UTC, rmarinho approved these changes

2024-05-14 16:01 UTC, PureWeen approved these changes

2024-05-14 16:01 UTC, merged