Revoke #19349. Fixes #20684
dotnet/maui pull request #22566
Opened 2024-05-22 07:31 UTC by BaY1251

This change comes from #19349, which simply and crudely piles up a large number of threads before loading the interface,Causing a significant decrease in performance. I don't have a better way, so I have to delete it

### Description of Change

Revoke src\Core\AndroidNative\maui\src\main\java\com\microsoft\maui\PlatformInterop.java changed in #19349

### Issues Fixed

Fixes #20684

2024-05-22 08:10 UTC, jsuarezruiz commented
/azp run

2024-05-22 13:11 UTC, PureWeen commented
@BaY1251 do you still see your original issue on the latest nightly build of MAUI?

2024-05-22 14:40 UTC, PureWeen requested changes
I've seen this type of loop happen a few times from this code, but, in my experience this usually happens because of bad code further up the chain. For example, this PR https://github.com/dotnet/maui/pull/22347 that will be part of SR6 fixes an issue where updates to Frame cause a bunch of ping ponging. 

Plus, we also have an issue with rounding on android currently. 

I'd be curious to investigate why the loop is happening before we just revert this code.

2024-05-22 18:58 UTC, closed without merging

2024-05-23 02:05 UTC, BaY1251 commented
@PureWeen  I don't think my PR is a good solution, fortunately you have found a better way

2024-05-24 02:10 UTC, BaY1251 commented
@PureWeen 
PS:
#22347 is valid.
> I'd be curious to investigate why the loop is happening before we just revert this code.

I am still searching for the root cause of the problem, it seems like it's not just a rounding problem.
I printed the log and saw that the height was constantly being changed to completely different values.
I'm not sure about this part of the code, could you please check it.

Code:
.\src\Core\src\Platform\Android\MauiScrollView.cs

log:
MauiScrollView.OnLayout: base.OnLayout(False,0,0,1920,936)
ViewExtensions.UpdateHeight: AutomationId:TopStackLayout,Height:936
ViewExtensions.UpdateHeight: AutomationId:GoToTestButton,Height:936
MauiScrollView.OnLayout: _hScrollView.Layout(False,0,0,1920,936)
ViewExtensions.UpdateHeight: AutomationId:TopStackLayout,Height:37
ViewExtensions.UpdateHeight: AutomationId:GoToTestButton,Height:37
MauiScrollView.OnLayout: base.OnLayout(False,0,0,1920,936)
ViewExtensions.UpdateHeight: AutomationId:TopStackLayout,Height:936
ViewExtensions.UpdateHeight: AutomationId:GoToTestButton,Height:936
MauiScrollView.OnLayout: _hScrollView.Layout(False,0,0,1920,936)
ViewExtensions.UpdateHeight: AutomationId:TopStackLayout,Height:37
ViewExtensions.UpdateHeight: AutomationId:GoToTestButton,Height:37

2024-05-24 02:18 UTC, BaY1251 commented
`_hScrollView.Layout(0, 0, hScrollViewWidth, hScrollViewHeight);`

I just need to delete this line of code and the world will be clean, but I believe the problem is not that simple.

2024-05-24 03:31 UTC, BaY1251 commented
@PureWeen  Please check the PR #22628