Cross TabBar navigation broken on iOS - Fix
dotnet/maui pull request #22655
Opened 2024-05-26 18:03 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/22570

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/263f9bca-6d6e-426d-8e42-3c06e18e0919" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/56398344-4c38-40e4-a689-82e06e2a6595" width="300px"/>|

2024-05-27 06:10 UTC, jsuarezruiz commented
/azp run

2024-05-27 14:59 UTC, rmarinho approved these changes

2024-05-27 15:00 UTC, rmarinho requested changes
This tests is failing 

```
EnsureOnAppearingFiresForLastPageOnlyAbsoluteRoute
```

2024-05-28 22:48 UTC, kubaflo commented
@rmarinho I think now should be good :)

2024-06-01 13:07 UTC, PureWeen commented
/azp run

2024-06-04 11:15 UTC, jsuarezruiz approved these changes, later dismissed

2024-07-05 13:13 UTC, PureWeen commented
/azp run

2024-07-05 14:19 UTC, PureWeen requested changes

2024-07-05 14:19 UTC, PureWeen commented on src/Controls/src/Core/Shell/ShellNavigationManager.cs
> +				await _shell.Dispatcher.DispatchAsync(() =>
I'm curious to investigate this a bit further and see if we can base this fix on something more deterministic.

2024-10-23 10:01 UTC, jsuarezruiz commented
/rebase

2024-10-23 10:01 UTC, jsuarezruiz commented
/azp run

2024-10-23 11:00 UTC, jsuarezruiz commented
/azp run

2024-12-01 13:58 UTC, kubaflo commented
Closing in favor of https://github.com/dotnet/maui/pull/26292 & https://github.com/dotnet/maui/pull/22574

2024-12-01 13:58 UTC, closed without merging