[Android] Navigation layout improvement
dotnet/maui pull request #22785
Opened 2024-06-02 23:37 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/22755

|ToolbarPlacement="Bottom"|ToolbarPlacement="Top"|
|--|--|
|<img src="https://github.com/dotnet/maui/assets/42434498/b14fedbc-0f9c-407b-a155-1e80bc47ec78" width="300px"/>|<img src="https://github.com/dotnet/maui/assets/42434498/15a7a480-98dd-4eab-8552-f3d372c605e9" width="300px"/>|

2024-06-03 06:04 UTC, jsuarezruiz commented
/azp run

2024-06-03 14:59 UTC, PureWeen requested changes

2024-06-04 11:28 UTC, jsuarezruiz commented on src/Core/src/Platform/Android/Resources/Layout/navigationlayout.axml
> +<androidx.constraintlayout.widget.ConstraintLayout
Yeah, also the change in the hierarchy force changes in tests etc
![image](https://github.com/dotnet/maui/assets/6755973/c145c109-f380-460e-8f4b-1c812de65fae)

2024-06-04 18:56 UTC, kubaflo commented
Here's the second possible fix https://github.com/dotnet/maui/pull/22836

2024-06-04 18:56 UTC, closed without merging