[X] allow namescope resolution before parenting
dotnet/maui pull request #22854
Opened 2024-06-05 14:46 UTC by StephaneDelcroix

### Description of Change

when an element doesn't override the NameScope (DataTemplate, etc...) FindName fails until the element is parented.

this PR sets a field (less expensive than a BP) used only during that time, and allow VSM to be applied.

### Issues Fixed

- fixes #22001

2024-08-12 22:22 UTC, PureWeen commented
/rebase

2024-08-13 20:11 UTC, PureWeen requested changes
Failures from the UI tests on this PR seem valid

2024-09-18 11:49 UTC, PureWeen commented
/rebase

2024-09-24 22:42 UTC, PureWeen commented
/rebase

2024-10-03 11:06 UTC, StephaneDelcroix commented
> Failures from the UI tests on this PR seem valid

fixed

2024-10-03 14:38 UTC, StephaneDelcroix commented on src/Controls/src/Core/Element/Element.cs
> +		[EditorBrowsable(EditorBrowsableState.Never)]
no, that was what was failing earlier. it's accessed by XAMLC generated code, which is user code

2024-10-03 19:35 UTC, PureWeen approved these changes

2024-10-03 19:35 UTC, merged

2024-10-03 19:36 UTC, PureWeen commented
/backport to release/8.0.1xx-sr9