Use DialogFragment for Android modals
dotnet/maui pull request #22869
Opened 2024-06-05 20:21 UTC by pictos

### Description of Change

This should be merged on `net9` branch, but since it's hard to make the .net9-preview don't mess-up with my env. I'm target .net8, when it gets approved this should rebased and re-target. I hope that @PureWeen can do this hard task for me xP.

### Issues Fixed

Fixes #22587

2024-06-05 21:22 UTC, PureWeen commented
/azp run

2024-06-06 06:29 UTC, jsuarezruiz commented
Don't worry @pictos, we can retarget to net9.0.

2024-06-08 01:51 UTC, PureWeen commented
Android UITests failing
![image](https://github.com/dotnet/maui/assets/5375137/1876d014-5e20-4323-9089-27faf0ee3602)


The controls device tests are crashing.
I'm guessing the modal tests inside device tests will need to be adjusted somewhat to handle DialogFragments

2024-06-11 03:23 UTC, pictos commented
@PureWeen, not sure if all tests will run again, but I think that I fixed the issue. I was using the `DialogFragment.ShowNow` method and it was causing issues with the `FragmentManager`, changing it to `DialogFragment.Show` seems to fix the issue.

2024-06-11 13:38 UTC, jsuarezruiz commented
/azp run

2024-06-11 19:59 UTC, pictos commented
from the logs looks like the Appium couldn't find the element, but it navigates to the correct screen (at least locally), is that some Appium issue?


> Failed AppDoesntCrashWhenReusingSameTitleView [16 s]
  Error Message:
   System.TimeoutException : Timed out waiting for element...
  Stack Trace:
     at UITest.Appium.HelperExtensions.Wait(Func`1 query, Func`2 satisfactory, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 804
   at UITest.Appium.HelperExtensions.WaitForAtLeastOne(Func`1 query, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 821
   at UITest.Appium.HelperExtensions.WaitForElement(IApp app, String marked, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency, Nullable`1 postTimeout) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 316
   at Microsoft.Maui.TestCases.Tests.Issues.Issue16499.AppDoesntCrashWhenReusingSameTitleView() in /_/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16499.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

2024-06-24 15:08 UTC, PureWeen commented
/azp run

2024-06-26 00:45 UTC, PureWeen commented
/rebase

2024-06-26 00:46 UTC, PureWeen commented
/azp run

2024-07-04 20:13 UTC, PureWeen commented
/rebase

2024-07-04 20:36 UTC, PureWeen requested changes
These two tests fail for me locally

Maybe resolving them will fix the other exceptions?

<img width="438" alt="image" src="https://github.com/dotnet/maui/assets/5375137/57721224-0574-4852-b44f-0a1d3253f4a0">

2024-07-05 08:05 UTC, mattleibow commented
/azp run

2024-07-06 15:02 UTC, PureWeen commented
/azp run

2024-07-08 20:16 UTC, jonathanpeppers commented
/azp run

2024-07-17 14:05 UTC, PureWeen commented
/azp run

2024-07-17 21:36 UTC, PureWeen commented
/azp run

2024-07-18 16:21 UTC, PureWeen commented on src/Core/src/Platform/Android/Resources/anim/nav_modal_default_enter_anim.xml
> +    android:duration="500"
```suggestion
    android:duration="300"
```

2024-07-18 16:21 UTC, PureWeen commented on src/Core/src/Platform/Android/Resources/anim/nav_modal_default_exit_anim.xml
> +      android:duration="500"
```suggestion
      android:duration="300"
```

2024-07-18 16:46 UTC, PureWeen commented
/azp run

2024-07-18 18:17 UTC, PureWeen commented
/azp run

2024-07-19 17:55 UTC, PureWeen commented
/azp run

2024-07-22 18:44 UTC, PureWeen commented
/azp run

2024-07-24 22:25 UTC, PureWeen commented
/azp run

2024-07-24 22:30 UTC, PureWeen commented
/azp run

2024-07-25 03:26 UTC, PureWeen commented
/azp run

2024-07-25 07:13 UTC, PureWeen approved these changes

2024-07-25 07:14 UTC, PureWeen commented
Test failures are on iOS. This PR only has changes on Android

2024-07-25 07:14 UTC, merged