fix: fix 23131 can`t reuse BottomItem`s tabEnabled
dotnet/maui pull request #23132
Opened 2024-06-19 10:08 UTC by maonaoda

### Description of Change

### Issues Fixed

Fixes #23131

2024-11-22 18:56 UTC, mattleibow commented
/rebase

2024-11-22 18:57 UTC, mattleibow commented
/azp run

2025-07-23 12:16 UTC, mattleibow requested changes
Is it possible to add a UI test for this?

2025-08-05 14:53 UTC, jfversluis commented
No response to our request for a test, closing for now. Let us know if you still want to take this further.

2025-08-05 14:53 UTC, closed without merging