[Windows] Fix select-all Entry select logic
dotnet/maui pull request #23329
Opened 2024-06-27 22:19 UTC by Foda

### Description of Change

The problem is caused by the following:
* Entry gains focus
* Cursor position and selection length are set, values propagate to WinUI TextBox
* Entry is unfocused
* Entry gains focus again
* Cursor position and selection length are set, but the values are the same, so we don't set the values again on the WinUI TextBox
* WinUI TextBox handles input event, moves cursor to where you click (note: the native WinUI TextBox seems to have special logic around canceling this logic if setting selection during an OnFocus event? this is where the issue comes from!)
* WinUI control then propagates cursor position and selection length values to the Maui Entry, text is now unselected

The fix here is to just always ensure setting cursor position and selection length flows to the native WinUI TextBox control. A better solution might be adding a `Select` and `SelectAll` method to `Entry`, but for now this will work.

2024-07-01 18:42 UTC, PureWeen commented on src/Controls/src/Core/InputView/InputView.cs
> +			set
@StephaneDelcroix  thoughts on this?

2024-08-19 18:56 UTC, PureWeen requested changes
> A better solution might be adding a Select and SelectAll method to Entry, but for now this will work.

We could just add this for now via the command mappers. Would that be a better solution here then firing the UpdateValue everytime?

Now in net9 with the new overrides, we could just target this to net9 and then fire a commandmapper that does the "SelectAll" behavior.

2024-10-23 09:58 UTC, jsuarezruiz commented
/azp run

2024-11-18 17:41 UTC, Foda commented
/rebase

2025-12-22 16:06 UTC, TrainCo commented
Has this code been merged?  The issue is pretty old but we still have a pending issue open that references this fix and from what I see on this page, the PR has been "running" since January so I just want to be sure someone has this in their sights.

2026-05-11 18:34 UTC, kubaflo commented
Closing in favor of #35383, which incorporates this fix with the review suggestions applied:

- `IssueTracker.ManualTest` → `IssueTracker.Github, 23329` for proper test correlation
- `PlatformAffected.UWP` → `PlatformAffected.Windows`
- Removed unused `using System.Diagnostics;`

Thank you @Foda for the original fix — you're listed as co-author on the new PR. 🙏

2026-05-11 18:34 UTC, closed without merging