Revert "Revert "Internalize MessagingCenter (#12582)""
dotnet/maui pull request #23527
Opened 2024-07-10 06:37 UTC by jfversluis

Reverts dotnet/maui#16798 to remove MessagingCenter for .NET 9

Fixes #16813

2024-07-10 09:10 UTC, mattleibow submitted a review, later dismissed

2024-07-10 09:44 UTC, jfversluis commented
Not merge to main and merge that to net9 @mattleibow ?

2024-07-10 09:59 UTC, mattleibow commented
Not sure what you mean, but I retargeted to net9 if that is what you mean?

But if you mean another net9-main merge branch, that is just a temp branch that we use to merge main up to net9.

2024-07-10 14:24 UTC, PureWeen requested changes
Drafting for now while we finalize plans here

2024-07-15 21:05 UTC, PureWeen commented
Leaving in place for another year

2024-07-15 21:05 UTC, closed without merging