[Android] Added Platform specific ripple color
dotnet/maui pull request #23599
Opened 2024-07-13 17:41 UTC by kubaflo

### Description of Change

Right now the only way to set a ripple color for buttons is to use custom mappers or platform specific code. But, for image buttons there is currently no way to do anything.

### Public API Changes

```
<Button 
   xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
   android:Button.RippleColor="Green"/>
```

```
<ImageButton 
   xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
   android:ImageButton.RippleColor="Green"/>
```

Fixes https://github.com/dotnet/maui/issues/22805

https://github.com/user-attachments/assets/928f0db9-bdfc-4da3-bcf1-6abc9ae73003

### Notes
I will remove the pragma warning disable RS0016 if this PR makes sense

2024-10-23 09:54 UTC, jsuarezruiz commented
/azp run

2024-10-29 16:04 UTC, jsuarezruiz commented
/rebase

2024-11-14 12:33 UTC, jsuarezruiz commented
/rebase

2024-11-21 10:00 UTC, jsuarezruiz commented
/rebase

2024-12-06 15:14 UTC, jfversluis commented
@kubaflo could you rebase this one please? Thanks!

2024-12-06 19:00 UTC, kubaflo commented
@jfversluis sure thing! done :)

2025-01-28 13:39 UTC, mattleibow requested changes
Unless someone does not like this feature, I think it is great.

I added a few comments, but it seems like all the bits are there. This will need to all be internal and then made public in net10 or in a SR if we are allowed to.

Alos, no idea how to test this because it is an OS animation... Msybe a device test that sets the ripple then background and/or border (and in reverse) and just read the derawable.

2025-01-28 13:39 UTC, mattleibow commented on src/Controls/src/Core/Button/Button.Mapper.cs
> +			ButtonHandler.Mapper.ReplaceMapping<Button, IButtonHandler>(nameof(PlatformConfiguration.AndroidSpecific.Button.RippleColorProperty), MapRippleColor);
This will result in a mapping of `"RippleColorProperty"`, this should be a string or even just:

```suggestion
			ButtonHandler.Mapper.ReplaceMapping<Button, IButtonHandler>(PlatformConfiguration.AndroidSpecific.Button.RippleColorProperty.PropertyName, MapRippleColor);
```

2025-01-28 13:39 UTC, mattleibow commented on src/Controls/src/Core/ImageButton/ImageButton.Mapper.cs
> +			ImageButtonHandler.Mapper.ReplaceMapping<ImageButton, IImageButtonHandler>(nameof(PlatformConfiguration.AndroidSpecific.ImageButton.RippleColorProperty), MapRippleColor);
Same as above:

```suggestion
			ImageButtonHandler.Mapper.ReplaceMapping<ImageButton, IImageButtonHandler>(PlatformConfiguration.AndroidSpecific.ImageButton.RippleColorProperty.PropertyName, MapRippleColor);
```

2025-01-28 13:39 UTC, mattleibow commented on src/Controls/src/Core/PlatformConfiguration/AndroidSpecific/Button.cs
> +		/// <include file="../../../../docs/Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific/Button.xml" path="//Member[@MemberName='GetRippleColor']/Docs/*" />
Not sure these docs exist, might need to be code docs.

2025-01-28 13:39 UTC, mattleibow commented on src/Controls/src/Core/PlatformConfiguration/AndroidSpecific/ImageButton.cs
> +		/// <include file="../../../../docs/Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific/ImageButton.xml" path="//Member[@MemberName='SetRippleColor'][1]/Docs/*" />
Same as above, docs need to be created in code.

2025-01-28 13:39 UTC, mattleibow commented on src/Controls/src/Core/PlatformConfiguration/AndroidSpecific/ImageButton.cs
> +		public static Color GetRippleColor(BindableObject element)
Make this internal for net9, and then open a new issue for us to make public in net10 or if the powers that be allow us to add ABI.

2025-01-28 13:39 UTC, mattleibow commented on src/Controls/src/Core/Button/Button.Android.cs
> +			if(button.IsSet(PlatformConfiguration.AndroidSpecific.Button.RippleColorProperty))
What happens if the user does a clear value? If we set the color to red and then unset, it will stay red. It should maybe pass null and the handler can assume that null == default?

2025-01-28 13:39 UTC, mattleibow commented on src/Core/src/Platform/Android/ButtonExtensions.cs
> +		internal static void UpdateRippleColor(this MaterialButton platformView, Color rippleColor)
This is just when the ripple color updates, but what happens when you update the background after? I think the code above will overwrite as it uses the `platformView.RippleColor` to get the color. We can/should probably overwrite that or even use that property instead.

2025-01-28 13:39 UTC, mattleibow commented on src/Core/src/Platform/Android/ImageButtonExtensions.cs
> +				ripple.SetColor(Android.Content.Res.ColorStateList.ValueOf(rippleColor.ToPlatform()));
Same as above.

2025-01-28 14:23 UTC, mattleibow commented
I wonder if this should be targeted at net10.0 instead?

2025-02-02 17:14 UTC, kubaflo commented
> I wonder if this should be targeted at net10.0 instead?

Hmmm that's a good question

2025-02-03 11:31 UTC, kubaflo commented
@mattleibow I think I've resolved comments :)

2025-03-31 10:55 UTC, rmarinho commented
/azp run

2025-04-09 11:21 UTC, rmarinho commented
/azp run

2025-04-09 11:22 UTC, rmarinho submitted a review, later dismissed

2025-04-10 07:35 UTC, jsuarezruiz requested changes
There are some pending changes in public APIs files:

```
C:\a\_work\1\s\.dotnet\sdk\10.0.100-preview.3.25175.10\Microsoft.Common.CurrentVersion.targets(1890,5): warning NU1702: ProjectReference 'C:\a\_work\1\s\src\Controls\src\Xaml.Design\Controls.Xaml.Design.csproj' was resolved using '.NETFramework,Version=v4.7.2' instead of the project target framework '.NETCoreApp,Version=v10.0'. This project may not be fully compatible with your project. [C:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj::TargetFramework=net10.0]
C:\a\_work\1\s\.dotnet\sdk\10.0.100-preview.3.25175.10\Microsoft.Common.CurrentVersion.targets(1890,5): warning NU1702: ProjectReference 'C:\a\_work\1\s\src\Controls\src\Core.Design\Controls.Core.Design.csproj' was resolved using '.NETFramework,Version=v4.7.2' instead of the project target framework '.NETCoreApp,Version=v10.0'. This project may not be fully compatible with your project. [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net10.0]
C:\a\_work\1\s\src\Controls\src\Core\PlatformConfiguration\AndroidSpecific\ImageButton.cs(144,74): error RS0016: Symbol 'SetRippleColor' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=netstandard2.0]
C:\a\_work\1\s\src\Controls\src\Core\PlatformConfiguration\AndroidSpecific\Button.cs(80,22): error RS0016: Symbol 'SetRippleColor' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=netstandard2.0]
C:\a\_work\1\s\src\Controls\src\Core\PlatformConfiguration\AndroidSpecific\ImageButton.cs(144,74): error RS0016: Symbol 'SetRippleColor' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net10.0]
C:\a\_work\1\s\src\Controls\src\Core\PlatformConfiguration\AndroidSpecific\Button.cs(80,22): error RS0016: Symbol 'SetRippleColor' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net10.0]
C:\a\_work\1\s\src\Controls\src\Core\PlatformConfiguration\AndroidSpecific\ImageButton.cs(144,74): error RS0016: Symbol 'SetRippleColor' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=netstandard2.1]
C:\a\_work\1\s\src\Controls\src\Core\PlatformConfiguration\AndroidSpecific\Button.cs(80,22): error RS0016: Symbol 'SetRippleColor' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [C:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=netstandard2.1]
    6 Error(s)
```

Could you review it?

2025-04-14 06:49 UTC, jsuarezruiz requested changes
Could include some tests in the DeviceTest project just using the Platform Specific and checking the `RippleDrawable` color?

2025-04-14 23:32 UTC, kubaflo commented
> Could include some tests in the DeviceTest project just using the Platform Specific and checking the `RippleDrawable` color?

I'm not quite sure how to do it

2025-04-15 13:07 UTC, jsuarezruiz commented
> > Could include some tests in the DeviceTest project just using the Platform Specific and checking the `RippleDrawable` color?
> 
> I'm not quite sure how to do it

You need to add a test in this class https://github.com/dotnet/maui/blob/8e875b73fd7a1500fc012559cf66118f2bbfd633/src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Android.cs#L15

Something like:

```
[Fact]
[Description("The RippleColor property of a Button Platform Specific should match with native RippleDrawable Color")]
public async Task RippleColorPlatformSpecific()
```

Define the button with the added Platform Specific:

```
var expected = Colors.Red;

var button = new Button();
button.On<Controls.PlatformConfiguration.Android>().SetRippleColor(expected);
```

And then, create a method to get the RippleDrawable Color, to compare it using an `Assert.Equal`. To get the color, will require to use reflection:

```
int? GetRippleDrawableColor(Android.Views.View button)
{
	if (button.Background is RippleDrawable rippleDrawable)
	{
		var constantState = rippleDrawable.GetConstantState();

		if (constantState is not null)
		{
			var colorField = constantState.GetType().GetField("mColor", BindingFlags.NonPublic | BindingFlags.Instance);

			if (colorField is not null)
			{
				var colorStateList = colorField.GetValue(constantState) as ColorStateList;
				return colorStateList?.DefaultColor;
			}
		}
	}

	return null;
}
```

Finally, just launch the test runner App on an Android device our emulator and run the test.

Ok, I let you explore to add it, but just let me know if need help or if want myself adding some tests.

2025-04-17 16:29 UTC, rmarinho commented
/azo run

2025-04-17 16:29 UTC, rmarinho commented
/azp run

2025-04-21 11:11 UTC, rmarinho submitted a review, later dismissed

2025-04-21 11:12 UTC, rmarinho commented
/azp run

2025-04-22 05:55 UTC, jsuarezruiz requested changes
Requires some small changes to fix the build:

```
C:\a\_work\1\s\src\Core\src\Platform\Android\ImageButtonExtensions.cs(87,43): error CS0234: The type or namespace name 'Graphics' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?) [C:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net10.0-android36.0]
C:\a\_work\1\s\src\Core\src\Platform\Android\ImageButtonExtensions.cs(91,22): error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?) [C:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net10.0-android36.0]
C:\a\_work\1\s\src\Core\src\Platform\Android\ButtonExtensions.cs(94,43): error CS0234: The type or namespace name 'Graphics' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?) [C:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net10.0-android36.0]
C:\a\_work\1\s\src\Core\src\Platform\Android\ButtonExtensions.cs(98,22): error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?) [C:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net10.0-android36.0]
    4 Error(s)
```

2025-04-22 11:23 UTC, rmarinho commented
/azp run

2025-04-22 17:48 UTC, rmarinho approved these changes

2025-04-23 10:33 UTC, jsuarezruiz approved these changes
LGTM, just added a comment about a detail in the added device test.

2025-04-29 16:26 UTC, merged