Remove non-functioning code and instead throw a more helpful platform-not-supported error
dotnet/maui pull request #23617
Opened 2024-07-15 23:03 UTC by dotMorten

Also mark the APIs not supported on Windows.

### Description of Change

Removes old UWP code that will never work in a WinUI context. Instead throws a more helpful `PlatformNotSupportedException` and flags the API as unsupported on Windows.
The current experience is you first get a "add protocol to manifest" error, but addressing that, you then just get a COMException and you're no closer to finding out what the problem is.
This error will lead users to start looking for alternatives, rather than trying to troubleshoot the problem.

### Issues Fixed

Fixes #23616

2024-07-15 23:07 UTC, dotMorten commented on src/Essentials/src/WebAuthenticator/WebAuthenticator.uwp.cs
> +			throw new PlatformNotSupportedException("This implementation of WebAuthenticator does not support Windows. See https://github.com/microsoft/WindowsAppSDK/issues/441 for more details.");
Let me know if you have a better location to direct people to? 
You could direct to https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-8.0&tabs=windows#get-started, but that just directs to [a closed maui issue](https://github.com/dotnet/maui/issues/2702) which is just as confusing, and in turn that just directs to the above referenced issue, which is where the problem really needs to be addressed first.

2024-08-13 06:26 UTC, mattleibow commented
/zp run

2024-08-13 06:26 UTC, mattleibow commented
/azp run

2024-08-13 13:43 UTC, jfversluis requested changes, later dismissed
Build errors across the board!

2024-08-13 13:46 UTC, dotMorten commented
Thanks @jfversluis. Odd it definitely built for me when I submitted. Will take a look.

2024-08-14 13:21 UTC, mattleibow commented
/azp run

2024-08-17 15:24 UTC, dotMorten commented
@mattleibow @jfversluis I'm a little bit confused here. The build is failing on building unit tests that would never work on Windows: https://github.com/dotnet/maui/blob/main/src/Essentials/test/DeviceTests/Tests/WebAuthenticator_Tests.cs#L12
First of all the callback scheme isn't defined for the Windows app, so it'll immediately fail with a manifest error. Secondly, if you do add that to the manifest, the code would still throw the COM Exception I'm trying to get rid off and replace with the better exception.
So I was a bit surprised this test actually even compiles for Windows, and can't see how this test could ever have passed. Is this because of the `Traits.InteractionTypes.Human` attribute?  How was this test ever passing?

That leaves me a few options:
1. Ignore the warning using `#pragma warning disable CA1416`
2. Exclude the test from windows using `#if !WINDOWS`
3. 1 + Modify the test to test for the expected exception thrown on Windows.

2024-08-19 17:26 UTC, dotMorten commented
@jfversluis Thanks. I've made the recommended changes. I don't have a clue how to actually run these human tests though, so going off of the behavior I saw by running the code in a separate app.

2024-08-20 20:52 UTC, mattleibow commented
/azp run

2024-08-22 18:18 UTC, mattleibow approved these changes

2024-08-22 18:18 UTC, merged