[X] deprecated fontImageExtension
dotnet/maui pull request #23657
Opened 2024-07-17 16:02 UTC by StephaneDelcroix

### Description of Change

The passthrough markup extensions serves no purposes, and isn't as flexible as the complete FontImageSource (allowing bindings, dynamicresources, ...)

For convenience, the element syntax can be used as a markup syntax {FontImagesource}

### Issues Fixed

- fixes #23347

2024-07-17 21:50 UTC, rmarinho requested changes, later dismissed
You need to add *REMOVE* in the unpublished public api not removed them for the PublicAPI . 
Also a change to remove something don t you think should be targeting net9 ?

2024-08-23 12:27 UTC, StephaneDelcroix commented
@rmarinho fixed

2025-02-04 10:54 UTC, rmarinho commented
Please rebase on net10.0 branch

2025-02-05 08:15 UTC, StephaneDelcroix commented
> Please rebase on net10.0 branch

done

2025-02-07 12:10 UTC, jfversluis commented
/rebase

2025-02-09 19:37 UTC, jfversluis commented
/zp run

2025-02-10 16:47 UTC, jfversluis approved these changes

2025-02-10 16:48 UTC, merged