[iOS] Shadow for clipped visual element
dotnet/maui pull request #23872
Opened 2024-07-27 16:53 UTC by kubaflo

### Issues Fixed

Fixes # https://github.com/dotnet/maui/issues/23630

|Before|After|
|--|--|
|<img src="https://github.com/user-attachments/assets/18dfe175-bd93-46ec-af67-9ed99cf1b079" width="300px"/>|<img src="https://github.com/user-attachments/assets/a3962417-4c74-4c15-a9cd-3040198a9dad" width="300px"/>|

2024-08-09 14:26 UTC, jonathanpeppers commented
/azp run

2024-08-12 06:20 UTC, albilaga commented
@kubaflo this is not working when I set the clip on runtime. Let's say I want to clip it based on dynamic size, I will do something like this
```csharp
    public BorderShadowIssuePage()
    {
        InitializeComponent();
        Container.SizeChanged += ContainerOnSizeChanged;
    }
    
    private void ContainerOnSizeChanged(object? sender, EventArgs e)
    {
        if (Container.Height < 1 || Container.Width < 1)
        {
            return;
        }

        var cornerRadius = Container.Height / 2;
        Container.Clip =
            new RoundRectangleGeometry(new CornerRadius(cornerRadius),
                new Rect(0, 0, Container.Width, Container.Height));
    }
```
but if I reapply the shadow again after clipping then it is working. Like this
```csharp
    private void ContainerOnSizeChanged(object? sender, EventArgs e)
    {
        if (Container.Height < 1 || Container.Width < 1)
        {
            return;
        }

        var cornerRadius = Container.Height / 2;
        Container.Clip =
            new RoundRectangleGeometry(new CornerRadius(cornerRadius),
                new Rect(0, 0, Container.Width, Container.Height));
        Container.Shadow = new Shadow
        {
            Brush = Colors.Blue, Opacity = 0.8f, Radius = 20, Offset = new Point(0, 3)
        };
    }
```

2024-08-15 00:59 UTC, kubaflo commented
> @kubaflo this is not working when I set the clip on runtime. Let's say I want to clip it based on dynamic size, I will do something like this
> 
> ```cs
>     public BorderShadowIssuePage()
>     {
>         InitializeComponent();
>         Container.SizeChanged += ContainerOnSizeChanged;
>     }
>     
>     private void ContainerOnSizeChanged(object? sender, EventArgs e)
>     {
>         if (Container.Height < 1 || Container.Width < 1)
>         {
>             return;
>         }
> 
>         var cornerRadius = Container.Height / 2;
>         Container.Clip =
>             new RoundRectangleGeometry(new CornerRadius(cornerRadius),
>                 new Rect(0, 0, Container.Width, Container.Height));
>     }
> ```
> 
> but if I reapply the shadow again after clipping then it is working. Like this
> 
> ```cs
>     private void ContainerOnSizeChanged(object? sender, EventArgs e)
>     {
>         if (Container.Height < 1 || Container.Width < 1)
>         {
>             return;
>         }
> 
>         var cornerRadius = Container.Height / 2;
>         Container.Clip =
>             new RoundRectangleGeometry(new CornerRadius(cornerRadius),
>                 new Rect(0, 0, Container.Width, Container.Height));
>         Container.Shadow = new Shadow
>         {
>             Brush = Colors.Blue, Opacity = 0.8f, Radius = 20, Offset = new Point(0, 3)
>         };
>     }
> ```

Did you test with a build generated by this PR?

2024-08-15 06:25 UTC, albilaga commented
yes. tested with nuget packages from this PR generated

2024-08-15 09:16 UTC, kubaflo commented
@albilaga I see, but I'm not sure it is a bug. I think it is intentional to adjust the shadow on your own when you change a clip

2024-08-19 05:41 UTC, albilaga commented
yeah. the workaround should also still be possible but do you see how to fix this without touching maui source (I mean like using handler)? Because this is unfortunately blocking our migration

2024-09-02 15:49 UTC, rmarinho commented
/azp run

2024-11-13 11:44 UTC, jsuarezruiz commented
/rebase

2024-11-13 11:45 UTC, jsuarezruiz commented
/azp run

2024-11-15 08:59 UTC, jsuarezruiz commented
/azp run

2025-01-09 18:10 UTC, PureWeen commented
/rebase

2025-01-09 18:11 UTC, PureWeen commented
/azp run

2025-01-09 18:56 UTC, PureWeen commented
/azp run

2025-01-09 20:39 UTC, PureWeen commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			this.SetShadow(Shadow);
is there any concern about this stuff from a performance stand point?

LayoutSubViews => calls SetShadow() => calls this.SetShadow(shadow) => SetShadow does stuff to the CALayer and then always calls "SetNeedsDisplay" on the layer

So, I just wonder if this path of triggering SetShadow needs to not call "this.SetShadow"? or somehow just check if it's changed?

2025-01-09 23:57 UTC, kubaflo commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			this.SetShadow(Shadow);
Mhhh that's probably true. I've added one more commit

2025-01-10 07:04 UTC, jsuarezruiz commented
/azp run

2025-01-10 07:30 UTC, mattleibow requested changes
I am not sure we should be clipping the main layer in the shadow.

2025-01-10 07:30 UTC, mattleibow commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			Layer.Mask = shadowLayer;
Why does the shadow set the mask on the Layer, but the clipping/SetMask doesn't?

Why do we even have a mask layer? The code looks to be applying a mask to a layer that is then added as a sub layer (maybe since the code looks like it only works if the sub layer has a Delegate). So, we are creating, clipping and then adding the clipped as a sub layer... Why are we not just clipping the main Layer directly in the clip?

2025-01-10 18:10 UTC, rmarinho commented
/azp run

2025-01-15 14:21 UTC, albyrock87 commented on src/Core/src/Platform/iOS/WrapperView.cs
> +			Layer.Mask = shadowLayer;
@kubaflo @mattleibow I've just implemented a cleaner solution in #26789 which also solves an issue where setting `Clip = null` would hide all the content (due to an empty `Path`).

2025-01-29 20:57 UTC, PureWeen commented
closing this PR in favor of https://github.com/dotnet/maui/pull/26789

2025-01-29 20:57 UTC, closed without merging