[iOS] Using long-press navigation on back button - fix
dotnet/maui pull request #24003
Opened 2024-08-04 15:54 UTC by kubaflo

### Description of Change

The `[Export("navigationBar:shouldPopItem:")]` is not being triggered when navigating back with the iOS's callout menu

Fixes https://github.com/dotnet/maui/issues/23892

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/e77dcaa1-dcc8-40d3-a6f7-10434bc09886" width="300px"/>|<video src="https://github.com/user-attachments/assets/f687eb90-8779-4a67-9991-5c789f3d666f" width="300px"/>|

2024-10-23 09:50 UTC, jsuarezruiz commented
/azp run

2024-10-31 11:49 UTC, jsuarezruiz commented
/rebase

2024-10-31 11:51 UTC, jsuarezruiz commented
/azp run

2024-11-12 14:56 UTC, jsuarezruiz commented
/azp run

2024-12-12 13:13 UTC, jfversluis commented
/rebase

2024-12-17 09:59 UTC, jfversluis requested changes
OK after 5 retries I think something might actually be wrong here 😅

The error also seems somewhat relevant to what is changed here so I think we should look into it: "[FAIL] Back Button Behavior Text"

2025-01-06 09:42 UTC, PureWeen submitted a review, later dismissed
Can you add a test? 

The PR here uses a long press on the back button to simulator a long press on the back button

https://github.com/dotnet/maui/pull/25552

2025-01-06 16:08 UTC, kubaflo commented
@PureWeen `LongPress()` worked in the UITest

2025-02-10 22:44 UTC, PureWeen commented
/azp run

2025-02-14 14:25 UTC, jfversluis approved these changes

2025-02-14 14:26 UTC, merged