[Android] Fix incorrect height of CollectionView when ItemsSource is empty.
dotnet/maui pull request #24067
Opened 2024-08-07 11:56 UTC by Tamilarasan-Paranthaman

### Description of Change

The default padding was occupying space in the `MauiRecyclerView`. Padding should only be set if the `ItemsCount` is greater than zero; otherwise, it is not necessary to apply padding.

### Issues Fixed

Fixes #23148

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <img src="https://github.com/user-attachments/assets/84fb77b2-4576-477b-abd4-4f51d78609ef" > | <img src="https://github.com/user-attachments/assets/916f4451-8f86-4131-9e7a-01dcd68afe9b" > |

2024-08-07 14:23 UTC, jfversluis commented
/azp run

2024-08-07 20:02 UTC, PureWeen commented
I haven't been able to reproduce the original issue.

Here I'm running the code from the original issue against our sandbox. 

I'll test again once tests are added to see how you are reproducing this one. 

![image](https://github.com/user-attachments/assets/30cb540b-a1d2-4e63-84a1-f2f1a7f79874)

2024-08-08 14:54 UTC, PureWeen commented
/azp run

2024-08-08 19:04 UTC, PureWeen requested changes

2024-08-08 19:04 UTC, PureWeen commented on src/Controls/tests/TestCases.HostApp/Issues/Issue23148.xaml
> + x:Class="Maui.Controls.Sample.Issues.Issue23148">
Namespace here isn't correct

2024-08-08 23:54 UTC, PureWeen requested changes
Is there a device API I need to run this on to reproduce?

I ran Issue23148 on here and I'm not seeing it reproduce the issue.

The initial load of the page looks the same for me with or without this code change. 

![image](https://github.com/user-attachments/assets/aa42b54c-9918-4bac-86e2-c776469b4b08)

2024-08-09 08:59 UTC, karthikraja-arumugam commented
@PureWeen, I can reproduce the issue with the latest source as well. I'm using Visual Studio and an API 31 Pixel 5 emulator. We're testing this in the main branch, not with .net9. I hope this information helps.

![image](https://github.com/user-attachments/assets/69b71e0e-215e-4f88-af63-4070ed72bac7)

2024-08-09 10:08 UTC, SuthiYuvaraj commented
@PureWeen ,I have reproduced the issue using the latest dotnet maui main repository. The problem persists across API levels 31, 33, 34, and 35 on our emulators. For further reference, I've also attached a video demonstrating the issue.
![collectionview 1](https://github.com/user-attachments/assets/b92f19c9-ba01-4879-8b45-9d2a505c0d04)

2024-08-09 16:58 UTC, PureWeen requested changes
Alright, I was able to reproduce this on Windows but not on Mac (for whatever reason)

One concern I have is that the code checking for the item count no longer runs when items are added. If you run the sample, and click the add button, the `SetPadding` call never occurs on the RecyclerView. 

![image](https://github.com/user-attachments/assets/1db88ec6-bab8-41b7-81b1-a1511b19b4b8)

If you run the sample so that it initially has items, you'll notice that the padding will be different around the edges of the CV vs if it starts out empty and you add items.

So, I think the UpdateItemSpacing call will need to refire when an initial item is added? 

I'm also a little curious why setting padding causes an infinite height. Maybe there's a measuring issue elsewhere that's the fundamental problem

2024-10-25 09:56 UTC, jsuarezruiz commented
/azp run

2024-10-25 09:56 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23148.cs
> +			VerifyScreenshot();
Triggered build to generate snapshots.

2024-10-30 08:54 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23148.cs
> +			VerifyScreenshot();
Snapshots already available in the latest build.

Example (iOS):
![image](https://github.com/user-attachments/assets/f40474c5-0e20-4243-9750-c22dc7605b97)

2025-03-11 10:10 UTC, jsuarezruiz commented
/rebase

2025-03-25 06:55 UTC, jsuarezruiz commented
/rebase

2025-03-25 06:57 UTC, jsuarezruiz commented
/azp run

2025-03-25 12:24 UTC, jsuarezruiz requested changes
The build is failing because missing test snapshots. 
<img width="344" alt="image" src="https://github.com/user-attachments/assets/a3c97d7a-bd77-45ce-b59d-42c19c16c7e4" />
Are available in the latest build. Could you commit the images?

2025-08-05 13:38 UTC, closed without merging