[Android] Fix for the CarouselView doesn't scroll to the right Position after changing the ItemSource with Loop enabled
dotnet/maui pull request #24160
Opened 2024-08-12 15:06 UTC by Ahamed-Ali

### Description of Change

When reloading the ItemSource, the `CurrentItem `was set to null in the `UpdateAdapter`, which caused the `UpdateInitialPosition `method to miss calculating the `itemCount `based on the `CurrentItem`. As a result, the `LoopScale `value was incorrect in the `LoopedPosition `method, causing `centerPosition `to be set to 0 in the `GetGoToIndex `method of the **CarouselViewLoopManager** class. This led to a negative index position in the `GetGoToIndex `and prevented scrolling.

### Description of change

`CurrentItem `should only be null if there are no items. This change ensures that `CurrentItem `is not unnecessarily modified and that the position is updated properly with **looping concept**. Additionally, if suppose the ItemSource is dynamically set to null and then reloaded with items, the CurrentItem can be set to maintain the correct LoopScale value.

### Issue Fixed

Fixes #17283
Fixes #23023  ( Issue 1 and 3)

### Before Fix

https://github.com/user-attachments/assets/b4c11e61-139a-4f6a-8a47-0d0726007297

### After Fix

https://github.com/user-attachments/assets/f4313876-a361-42cc-88e4-c05c6dc2d4d2

2024-08-12 15:24 UTC, jfversluis commented
/azp run

2024-08-18 17:59 UTC, PureWeen requested changes

2024-08-18 17:59 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17283.cs
> +		public void Issue17283Test()
Give the test a more significant name indicating what's being tested here. 
This is the name that shows up in the test results so it's easier if it has a valid description

2024-08-26 09:14 UTC, Ahamed-Ali commented
Closing this due to duplicate PR created - https://github.com/dotnet/maui/pull/24431

2024-08-26 09:14 UTC, closed without merging