[IOS ]Fix border has an unexpected background animation
dotnet/maui pull request #24227
Opened 2024-08-14 09:48 UTC by Shalini-Ashokan

### Root cause
iOS adds default animations to certain actions, which can cause unexpected background animations on borders when the BackgroundColor or CornerRadius of a border is changed.

### Description of changes

The fix involves disabling native animations temporarily while updating background layers. This is done using a CATransaction block with AnimationDuration set to 0.

### Reference
Referred code changes from StrokeExtensions

### Issues Fixed
Fixes [21643](https://github.com/dotnet/maui/issues/21643)

### Output

2024-08-14 20:44 UTC, PureWeen commented
/azp run

2024-08-18 17:48 UTC, PureWeen commented
/azp run

2024-08-19 18:53 UTC, PureWeen requested changes
Screenshots are ready to generate

2024-08-21 16:33 UTC, PureWeen requested changes
After reviewing this PR, a community member has offered the following alternative

https://github.com/dotnet/maui/pull/24360

Let me know what you think

2024-08-22 09:54 UTC, Shalini-Ashokan commented
@PureWeen, The changes we added in this PR have fixed the issue on iOS. However, after further investigation, we found that the issue is also occurring on Mac. We checked that the changes provided in this [PR](https://github.com/dotnet/maui/pull/24360) resolve the issue on both iOS and Mac.

2024-08-27 14:07 UTC, Shalini-Ashokan commented
@PureWeen, Our fix addresses the issue on iOS, but the problem still persists on MacOS, We have tested PR [24360](https://github.com/dotnet/maui/pull/24360), and it resolves the issue on both platforms. Therefore, we can close this PR.

2024-08-27 14:07 UTC, closed without merging