[XC] Fallback to reflection-based bindings for bindings with "invalid" path
dotnet/maui pull request #24238
Opened 2024-08-14 14:36 UTC by simonrozsival

### Description of Change

We've improved binding optimizations in .NET 9 and it is now possible to compile all sorts of bindings that weren't supported in .NET 8 and earlier. This change can break existing code though:
- In the cases when there is a binding with a `Source` but it inherits the `x:DataType` from the parent, there can often be a mismatch between the `x:DataType` and the type of the `Source`
- Sometimes customers want to reference another element and access its BindingContext (`{Binding BindingContext.Title Source={x:Reference ...}}`). Since we don't support casting in the path, XamlC won't be able to correctly resolve and build the property chain (in the example `BindingContext` is of type `object` and it doesn't have any property `Title`).

While there are workarounds to these issues, it might be better to just fallback to a reflection-based binding that will resolve the actual properties at runtime in these cases to keep the apps working and produce a warning so that the developer can either choose to ignore it or address it. I am not 100% sure this is the right way to approach this issue so I'm keeping this as a draft for now. Feedback is very welcome.

I recommend hiding whitespace changes when looking at the code diff.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23711

2024-08-20 14:24 UTC, StephaneDelcroix approved these changes, later dismissed

2024-08-22 09:14 UTC, rmarinho requested changes, later dismissed
```
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/AutomationProperties.xaml(9,4): XamlC warning XC0618: Property, Property setter or BindableProperty "Name" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/AutomationProperties.xaml(10,4): XamlC warning XC0618: Property, Property setter or BindableProperty "HelpText" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/AutomationProperties.xaml(12,4): XamlC warning XC0618: Property, Property setter or BindableProperty "LabeledBy" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Maui17484.xaml(10,17): XamlC warning XC0618: Property, Property setter or BindableProperty "Name" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/WarnOnObsolete.xaml(6,25): XamlC warning XC0618: Property, Property setter or BindableProperty "ObsoleteBP" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/WarnOnObsolete.xaml(6,42): XamlC warning XC0618: Property, Property setter or BindableProperty "ObsoleteProp" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/WarnOnObsolete.xaml(6,61): XamlC warning XC0618: Property, Property setter or BindableProperty "ObsoletePropSetter" is deprecated. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/BindingsCompiler.xaml(28,20): XamlC error XC0045: Binding: Property "GlobalText" not found on "System.Object". [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/BindingsCompiler.xaml : XamlC error : Index (zero based) must be greater than or equal to zero and less than the size of the argument list. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Gh2517.xaml(6,12): XamlC error XC0045: Binding: Property "MissingProperty" not found on "Microsoft.Maui.Controls.Label". [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Gh2517.xaml : XamlC error : Index (zero based) must be greater than or equal to zero and less than the size of the argument list. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Gh3606.xaml(4,16): XamlC error XC0045: Binding: Property "Content" not found on "System.String". [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Gh3606.xaml : XamlC error : Index (zero based) must be greater than or equal to zero and less than the size of the argument list. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Maui20768.xaml(6,32): XamlC error XC0045: Binding: Property "Title" not found on "Microsoft.Maui.Controls.Xaml.UnitTests.ViewModel20768". [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Issues/Maui20768.xaml : XamlC error : Index (zero based) must be greater than or equal to zero and less than the size of the argument list. [/Users/builder/azdo/_work/2/s/src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj]
    7 Warning(s)
    8 Error(s)
```

2024-08-24 22:57 UTC, rmarinho commented
/rebase

2024-08-27 14:36 UTC, StephaneDelcroix approved these changes

2024-08-27 14:37 UTC, merged