[net9.0] Fix loop
dotnet/maui pull request #24230
Opened 2024-08-14 11:49 UTC by rmarinho

### Description of Change

Fix CarouselViewHandler controller2 looping setting the correct new version for the ItemsSource.

2024-08-14 19:32 UTC, Redth submitted a review, later dismissed

2024-08-14 19:32 UTC, Redth commented
/azp run

2024-08-16 16:58 UTC, PureWeen requested changes
Fix Failing Tests

2024-08-24 22:17 UTC, rmarinho commented on src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Shipped.txt
> -override Microsoft.Maui.Controls.Layout.Measure(double widthConstraint, double heightConstraint, Microsoft.Maui.Controls.MeasureFlags flags = Microsoft.Maui.Controls.MeasureFlags.None) -> Microsoft.M
this seems strange

2024-08-24 22:18 UTC, rmarinho commented on src/Controls/src/Core/Handlers/Items2/iOS/StructuredItemsViewController2.cs
> +		protected virtual string DetermineViewReuseId(NSString elementKind)
I m not sure about this implementation. We maybe should just  flat this to ItemsViewController

2024-08-26 17:06 UTC, merged