[Android] Add test for scroll without group
dotnet/maui pull request #24288
Opened 2024-08-16 20:46 UTC by Foda

### Description of Change

When looking up the item index, using the interface `IGroupableItemsViewSource` to determine if the list is grouped or not will not work as ungrouped lists also implement that interface. This PR adjusts the logic to check if the list is ungrouped via `UngroupedItemsSource`, then returns the index.

### Issues Fixed

Fixes #24272

2024-08-17 12:26 UTC, jfversluis commented
Looks like the test fails on iOS

2024-08-17 18:44 UTC, PureWeen approved these changes

2024-08-17 18:46 UTC, PureWeen requested changes
Looks like the test fails on iOS

2024-08-19 23:16 UTC, PureWeen approved these changes

2024-08-20 21:05 UTC, merged