BarBackground with Brush in NavigationPage on theme change
dotnet/maui pull request #24429
Opened 2024-08-25 23:14 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24428

<video width="400px" src="https://github.com/user-attachments/assets/15baccdf-e928-4454-ba99-e2d32971863f"/>

2024-08-26 10:47 UTC, rmarinho commented
/azp run

2024-10-04 10:00 UTC, jsuarezruiz commented
/azp run

2024-11-12 14:55 UTC, jsuarezruiz commented
/rebase

2024-11-12 14:56 UTC, jsuarezruiz commented
/azp run

2024-11-13 15:39 UTC, jsuarezruiz submitted a review, later dismissed

2024-11-13 15:39 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Android.Tests/snapshots/android/NavigationBarBackgroundShouldChange.png
```
Snapshot different than baseline: NavigationBarBackgroundShouldChange.png (size differs - baseline is 1124x2326 pixels, actual is 1124x2286 pixels)
If the correct baseline has changed (this isn't a a bug), then update the baseline image.
```

Could you update the snapshot?

2024-11-15 00:39 UTC, kubaflo commented on src/Controls/tests/TestCases.Android.Tests/snapshots/android/NavigationBarBackgroundShouldChange.png
Done :)

2024-11-15 08:57 UTC, jsuarezruiz commented
/azp run

2025-01-06 08:31 UTC, PureWeen commented
/azp run

2025-01-06 08:32 UTC, PureWeen commented
/rebase

2025-01-06 08:35 UTC, PureWeen commented
/azp run

2025-01-06 16:52 UTC, mattleibow reviewed
Looking good, I think we can add a verify for the initial light mode just in case something breaks and CI suddenly goes dark mode by default. #defensivetesting

2025-01-06 16:52 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24428.cs
> +				App.SetDarkTheme();
Could you add a verify here as well to check that the light mode is correct?

2025-01-06 16:56 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24428.cs
> +				App.SetDarkTheme();
Done :)

2025-01-06 17:03 UTC, mattleibow approved these changes, later dismissed

2025-01-06 20:30 UTC, PureWeen commented
/azp run

2025-01-07 23:59 UTC, PureWeen commented
/azp run

2025-01-07 23:59 UTC, PureWeen approved these changes

2025-01-08 17:50 UTC, PureWeen requested changes
NavigationBarBackgroundShouldChange is failing on android

2025-01-08 19:30 UTC, PureWeen commented
/azp run

2025-01-09 22:30 UTC, PureWeen approved these changes

2025-01-09 22:30 UTC, merged