Update a tabbar with gradient on app theme change
dotnet/maui pull request #24425
Opened 2024-08-25 14:58 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24356

<video src="https://github.com/user-attachments/assets/a674bac7-ce4d-44dc-9b6d-e24b0b8f3757" width="400px"/>

2024-08-30 12:58 UTC, rmarinho commented
/azp run

2024-08-30 22:18 UTC, rmarinho commented
/azp run

2024-09-04 14:59 UTC, StephaneDelcroix commented
does this fixes #24428 too ?

2024-09-04 15:02 UTC, kubaflo commented
> does this fixes #24428 too ?

No, https://github.com/dotnet/maui/pull/24429 fixes 24428

2024-11-06 09:34 UTC, AlleSchonWeg commented
Hi,
i'm waiting for this fix. Is there a problem with this PR?
Thank you

2024-11-12 14:54 UTC, jsuarezruiz commented
/rebase

2024-11-12 14:56 UTC, jsuarezruiz commented
/azp run

2024-11-13 12:05 UTC, jsuarezruiz requested changes

2024-11-13 12:05 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientInTabBarShouldChange.png
The test is failing on iOS. Could you update the snapshot?

```
VisualTestUtils.VisualTestFailedException :
Snapshot different than baseline: GradientInTabBarShouldChange.png (size differs - baseline is 1124x2326 pixels, actual is 1124x2286 pixels)
```

2025-02-05 11:46 UTC, AlleSchonWeg commented
Hi,
could this be merged!
Thank you

2025-02-13 12:47 UTC, jfversluis commented
/rebase

2025-02-14 13:12 UTC, jfversluis approved these changes

2025-02-14 13:13 UTC, jfversluis commented
Failed tests unrelated

2025-02-14 13:13 UTC, merged