Fix Text entry border disappear when changing to/from dark mode in Android
dotnet/maui pull request #24433
Opened 2024-08-26 07:22 UTC by devanathan-vaithiyanathan

### Root cause
The issue occurs because the border color of the Entry, Editor, Picker, TimePicker and DatePicker control in Android does not automatically update when switching between light and dark modes. The underlying problem is that the border color is not being re-applied or refreshed when the theme changes, leading to the border disappearing or not reflecting the correct color.

### Description of Change

In the overridden method of OnConfigurationChanged in MauiAppCompatActivity.Lifecycle, we invoked a ThemeChanged event, subscribed to it from the handlers, and called the UpdateBackground method.

### Issues Fixed

Fixes #15524

### Tested the behaviour in the following platforms
 
- [x] Android
- [ ] Windows
- [x] iOS
- [x] Mac

**Windows bug report** #24923

### Output

Before

https://github.com/user-attachments/assets/e1903921-44ab-4f2b-be44-76012ba366aa

After

https://github.com/user-attachments/assets/e472f578-f903-4cb1-bded-769096a52b28

2024-09-25 13:36 UTC, jfversluis commented
/azp run

2024-10-03 21:03 UTC, PureWeen requested changes
All Android Views have a method `OnConfigurationChanged` that you can override which will fire when the theme changes. I think instead of having to wire this up inside controls you can instead override `OnConfigurationChanged` and then I think you'd need to just add an event we can subscribe to from the handler. 

Then the Handler could call UpdateBackground

2024-10-04 13:13 UTC, devanathan-vaithiyanathan commented
> All Android Views have a method `OnConfigurationChanged` that you can override which will fire when the theme changes. I think instead of having to wire this up inside controls you can instead override `OnConfigurationChanged` and then I think you'd need to just add an event we can subscribe to from the handler.
> 
> Then the Handler could call UpdateBackground

Regarding the override of OnConfigurationChanged in Android Views, initially, I override OnConfigurationChanged in the MauiAppCompatEditText for the Entry control, invoked the event in the method, and subscribed to it from the EntryHandler.
 
After deploying the sample with this change, I observed that OnConfigurationChanged in MauiAppCompatEditText does not get triggered when changing the theme via a button click, so the theme does not change. However, when I changed the theme through the device's system settings (Android mobile), OnConfigurationChanged was triggered. Please refer to the attached  video showing the difference between the button click and device theme change in terms of how OnConfigurationChanged behaves in Android Views.
 
As a result, we have used the event in the already overridden OnConfigurationChanged method within MauiAppCompatActivity.Lifecycle. In this implementation, both theme changes via button click and mobile system theme changes work correctly.
 
Please share your suggestions on this change.


https://github.com/user-attachments/assets/799bdcdb-719b-4c32-a354-411da1e6f007


https://github.com/user-attachments/assets/21124ab4-819b-461a-a0fd-bd83bb243a0d

2024-10-07 10:03 UTC, jsuarezruiz commented
/azp run

2024-10-08 16:55 UTC, PureWeen commented
/azp run

2024-10-09 12:04 UTC, jsuarezruiz reviewed
Mnn, probably happens the same on the SearchBar, could you validate it? If happens, could you update the test to include the SearchBar?

2024-10-09 14:00 UTC, karthikraja-arumugam commented
> Mnn, probably happens the same on the SearchBar, could you validate it? If happens, could you update the test to include the SearchBar?

@jsuarezruiz,  I've tested the search bar issue and found that the colors of the underline and search icon do not change based on the theme. Additionally, the background implementation of the search bar differs from that of other fixed controls.

@Ahamed-Ali created a separate bug report for the theme issue with the search bar. We'll check this report https://github.com/dotnet/maui/issues/25153

2024-10-09 22:06 UTC, PureWeen requested changes

2024-10-09 22:06 UTC, PureWeen commented on src/Core/src/Handlers/DatePicker/DatePickerHandler.Android.cs
> +			if (platformView.Context is MauiAppCompatActivity context)
I don't think we can depend on the activity being of type `MauiAppCompatActivity`

Embedding scenarios aren't always going to inherit from `MauiAppCompatActivity`

2024-10-25 10:09 UTC, jsuarezruiz commented
/azp run

2024-10-30 09:12 UTC, jsuarezruiz requested changes

2024-10-30 09:12 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.HostApp/Issues/Issue15524.xaml
> +    <TimePicker AutomationId="TimePicker"/>
Set the Time property to a specific time. in the related test, the reference screenshot may have differences based on culture etc.
![image](https://github.com/user-attachments/assets/9eca1db1-7e7c-4654-883c-418972ae71e7)

2025-01-10 07:06 UTC, jsuarezruiz commented
@devanathan-vaithiyanathan  Could you rebase to fix the conflicts?

2025-01-13 06:05 UTC, devanathan-vaithiyanathan commented
> @devanathan-vaithiyanathan Could you rebase to fix the conflicts?

I have rebased the branch and resolved the conflicts

2025-01-29 12:28 UTC, jsuarezruiz commented
/rebase

2025-01-31 11:20 UTC, jsuarezruiz commented
/azp run

2025-02-03 12:31 UTC, jsuarezruiz requested changes

2025-02-03 12:31 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15524.cs
> +		[FailsOnWindows("Currently fails on Windows; see https://github.com/dotnet/maui/issues/24923")]
Needs a rebase, this no longer exists. Replaced by `FailsOnWindowsWhenRunningOnXamarinUITest`.

2025-02-12 09:28 UTC, devanathan-vaithiyanathan commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15524.cs
> +		[FailsOnWindows("Currently fails on Windows; see https://github.com/dotnet/maui/issues/24923")]
@jsuarezruiz, 
I have rebased this PR, removed the FailsOnWindowsWhenRunningOnXamarinUITest attribute, and added TestFailsOnWindows.

2025-03-25 06:56 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:24 UTC, jsuarezruiz commented
/azp run

2025-03-25 12:27 UTC, jsuarezruiz requested changes

2025-03-26 07:14 UTC, Ahamed-Ali commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15524.cs
> +		public void VerifyBorderVisibilityOnThemeChange()
This PR fixes the underline scenario for Entry, Editor, Picker, DatePicker, and TimePicker. As per Shane's comment, the theme implementation should apply to all controls. Therefore, we have moved this PR to draft, as additional implementation is needed to ensure consistency across all controls when changing the theme. 
 
Please review the [discussion](https://github.com/dotnet/maui/pull/24433#discussion_r1794298751) @jsuarezruiz

2025-03-27 08:29 UTC, jsuarezruiz requested changes

2025-03-27 08:29 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15524.cs
> +		public void VerifyBorderVisibilityOnThemeChange()
Pending snapshot on Mac
![image](https://github.com/user-attachments/assets/3fc589a5-42ea-4cb7-b01c-ed34e779487b)

2025-06-24 06:41 UTC, jsuarezruiz commented
Could you rebase to fix the conflicts? Thanks in advance.

2025-08-06 07:35 UTC, sheiksyedm commented
https://github.com/dotnet/maui/pull/24433/files#r1794298751

2025-08-06 07:35 UTC, closed without merging