Fix App Theme Binding For Non Elements
dotnet/maui pull request #24465
Opened 2024-08-27 12:54 UTC by Axemasta

We encountered [this](https://github.com/CommunityToolkit/Maui/issues/1994) bug in the community toolkit touch behavior. When an `AppThemeBinding` was set on the effect, the correct color for the app theme would load, but when the theme was changed at runtime the colors would not update. Only destroying the element completly (ie navigating away from & destroying the page) would allow you to see the correct colors, the next time you visited the page.

I was able to reproduce this issue with a basic `PlatformBehavior` outside of the community toolkit and through debugging the `AppThemeBinding` found a point where it cast the `BindableObject as Element`, which in the case of `PlatformBehavior`s is not valid.

### Description of Change

Add a fallback to `AppThemeProxy` to account for when `BindableObject` is not an `Element`.

### Issues Fixed

Fixes #24444

### Reproduction

I have a seperate branch with the code I used to debug and test this issue. Go to my branch [fix/24444/sample](https://github.com/Axemasta/maui/tree/fix/24444/sample) and run Maui.Controls.Sample, it will take you to a page with this issue setup (now fixed)

2024-08-30 12:56 UTC, rmarinho commented
/azp run

2024-09-03 11:04 UTC, mattleibow commented
Also, please add a unit test showing the issue and that this PR fixes it.

2024-09-03 13:16 UTC, Axemasta commented
> Also, please add a unit test showing the issue and that this PR fixes it.

I've added 3 tests to the `AppThemeTests.cs` test file. They follow the pattern other app theme tests use but use a platform behavior instead. I noticed a null reference in [`PlatformBehavior`](https://github.com/dotnet/maui/blob/60b9a694e43f6e5c159bf877148649b6ce4b6978/src/Controls/src/Core/Interactivity/PlatformBehavior.cs#L105) when running the tests, I've made it a pattern which is what Rider suggested, happy to change it if that style is frowned upon in this codebase.

If you run these tests with the live version of `AppThemeBinding` they all fail, if you have my changes they pass.

2024-09-04 10:31 UTC, StephaneDelcroix commented on src/Controls/src/Core/AppThemeBinding.cs
> +					Application.Current.RequestedThemeChanged += OnRequestedThemeChanged;
we stopped subscribing to that event, as it was causing huge perf bottleneck

2024-09-04 10:32 UTC, StephaneDelcroix commented on src/Controls/src/Core/AppThemeBinding.cs
> +			if (bindObj is Element element)
we stopped subscribing to the event

2024-09-04 10:37 UTC, StephaneDelcroix requested changes
Behaviors are meant to be shared by instance and shouldn't inherit from BO. the ColorBehavior shouldn't probably have a Color property, but a BindingBase Color, so the Behaviour would retain the binding that would be applied when the behaviour is effectively applied. that would also make it work for multiple kind of bindings, and not only for AppTheme

2024-09-04 10:39 UTC, StephaneDelcroix commented
I think this is a misuse/abuse of the API and shouldn't be fixed, as the fix only add a local workaround for the specific case. I believe this can be fixed in code by changing the point of view...

2024-09-04 12:01 UTC, Axemasta commented
@StephaneDelcroix Would you be able to provide a little more explanation and clarification as I'm not sure I understand here...

> Behaviors are meant to be shared by instance and shouldn't inherit from BO

This has always been the case since XF went open source, is this going to change in future versions? Wouldn't this have a catastrophic impact on any Behavior that is using bindable properties?

> but a BindingBase Color

I've had a chat with the MCT discord and we're a bit unsure on what this would look like. We need the color itself to set the colors on the view. This is true for all of the bindable properties on the `TouchBehavior`, we take their value and apply it straight to the native view

>  this can be fixed in code by changing the point of view...

Please could you give us an example of what this looks like, I don't understand how we could set this up differently to work

> I think this is a misuse/abuse of the API and shouldn't be fixed

The very [first documented example](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors?view=net-maui-8.0#create-a-platform-behavior) of how to use a platform behavior uses a color and code virtually identical to the `ColorBehavior` example I included in the unit test. Is there something I'm not getting here?

We've had quite a few technical issues getting [TouchBehavior](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/touch-behavior?tabs=toucheffect-xaml%2Ctouchbehavior-xaml) working using `PlatformBehavior` (I personally ported the XCT TouchEffect to maui line for line and it worked fine), and the issues our users are reporting cannot be fixed on our side since even if we hook into the theme changed event, the `ColorProperty` won't update to reflect the new app theme. I personally do think this is an issue on the maui side, obviously my fix is rudimentary to begin with but whilst `Behavior` inherits `BindableObject` (something its done its whole lie), we should be able to add bindable properties right?

2025-06-12 01:02 UTC, mattleibow commented
@StephaneDelcroix are you saying this PR should be merged at all? Besides the perf issue.

Do you have an example on how to use the behavior with a BindingBase property?

2025-06-12 07:23 UTC, StephaneDelcroix commented on src/Controls/src/Core/AppThemeBinding.cs
> +			if (bindObj is Element element)
and we won't re-add that code.

2025-06-12 07:28 UTC, StephaneDelcroix commented
> This has always been the case since XF went open source, is this going to change in future versions? Wouldn't this have a catastrophic impact on any Behavior that is using bindable properties?

it already has catastrophic impact when a behaviour is reused. the parenting is wrong, and it might leak

if you remove the ColorProperty in ColorBehavior, and replace by

```
public BindingBase ColorBinding {get; set;}
```

you can apply the binding on OnApply to a temporary BP on a temporary BO and get the value. we do that at other places

> are you saying this PR should be merged at all?

y, I don't think we should merge that. it can't be worked around in code

2025-06-18 12:43 UTC, Axemasta commented
I'll have a look at seeing how easy this is to work around using the `BindingBase` approach however I would like to raise a serious concern I have about Behavior at this time.

@StephaneDelcroix I understand that Behaviors are shared and a single instance can be attached to many views, however alot of porting from Xamarin to Maui has automatically changed `Effect` to `Behavior`, citing that `Behavior` is more modern and has a better architecture under the hood. The issue here is that for view specific effects, that have become behaviors they are now completely broken when used in real world applications. The example here is of course the MCT TouchBehavior, I helped the guys get it across the line and have noticed multiple bugs that the effect version (same underlying architecture) doesn't have. All of these issues are caused by how the maui code is processing `BindableObject`s and casting them as `Element`, with an `Effect` this is valid and with a `Behavior` it is not.

I've heard from people in the team and around the team that `Effect` is something that should not be used and that one day it could be on the chopping block. If that happens the ability to use TouchEffect from the CF days would be completely kneecapped because the Behavior port cannot:

- Bind to parent ancestors, it needs to use `x:Reference`s etc to set the correct binding context when within a data template
- Does not respond to app theme changes, if the theme switches from light to dark the `BindableProperty` still sees the `Light` color and nothing will ever update without setting 2 colors on the control of manually responding to the theme change

I think too many people have added bindable properties to `Behavior` to stop allowing `BindablePropertie`s on `Behavior`, instead we need a framework level distinction. We need 2 types of behaviors that either apply to 1 view or many views, imagine we give the single view behavior a way of returning its element so we can correctly handle it, a multi element behavior simply throws an exception when bound to 2 views and we're cooking. This is simply an idea but it really frustrates me that MCT is shipping a `Behavior` that is broken because the team was told to port Effect to Behavior, and all of the usability issues are on the maui side. I've personally back ported the MCT code to an `Effect` and it has none of the issues experienced with the `Behavior` version!

2025-07-09 19:15 UTC, pmahend1 commented on src/Controls/src/Core/AppThemeBinding.cs
> +					Application.Current.RequestedThemeChanged += OnRequestedThemeChanged;
@StephaneDelcroix is there a work-around without subscribing to RequestedThemeChanged?

2025-08-21 11:29 UTC, Axemasta commented
Bumping to keep this discussion alive. Can there be serious discussion from the Maui team around `PlatformBehavior` and its intended usage.

Due to the restrictions `Behavior` has there are numerous bugs that stem from adding `BindableProperties` and cracking on with building things (relative bindings won't work, app theme bindings won't update on theme changes). `Effect` solves this but I've been told privately that `Effect` is an old paradigm that **_could_** leave the product in the future. If that was the case we would be left in quite the pickle as the `PlatformBehavior` currently is designed for multi use & the single use approach is "forbidden". With .NET 10 around the corner, I believe its time the team really looked into these behavior issues and proposed a permanent solution. `TouchBehavior` in the community toolkit is in my opinion not useable until it can use all the features everything else has access to without workarounds (relative bindings) or hard no's (app theme bindings)

2026-03-08 19:02 UTC, kubaflo commented
Closing as suggested by this comment: https://github.com/dotnet/maui/pull/24465/changes#r1743496215. We don't think it is a right fix

2026-03-08 19:02 UTC, closed without merging

2026-03-09 09:53 UTC, Axemasta commented
Whilst I accept the team did not want these changes, this is still an issue for all users of maui and I think some form of discussion still needs to take place about how exactly this gets fixed moving forwards. I appreciate that this is probably something the team will discuss internally however from my perspective, this issue aswell as the relative bindings not working for behaviours represents a very rough edge for maui, one the team absolutely needs to be addressing.

Its clear that @StephaneDelcroix thinks theres a design problem with Behaviours
> Behaviors are meant to be shared by instance and shouldn't inherit from BO. the ColorBehavior shouldn't probably have a Color property, but a BindingBase Color, so the Behaviour would retain the binding that would be applied when the behaviour is effectively applied. that would also make it work for multiple kind of bindings, and not only for AppTheme

What is the team going to do to address this, whilst his suggestion of using binding base would work... its not exactly user friendly. When working with behaviours you'd have to be aware of this bug and design your behaviour differently to any other place within maui. Since the MCT ported `TouchEffect` to `TouchBehavior`, they have broken the paradigm (effect applies per view, behaviours should be shared), but I don't really think its their fault as they were told to use `PlatformBehaviour` many years ago and `Effect` is something from the xamarin days that doesn't really seem to see much use in maui, will it be getting deprecated?

Does it make sense to have a new behaviour type:
- `PlatformSharedBehavior`
- `PlatformSingleBehavior`

Should developers be using `Effect` instead if they want to create things like `TouchBehavior`. Behaviors with bindable property have 2 open bugs just raised by myself which are directly as result of working on the community toolkit:
- #24444
- #24313

I'd love to see a discussion about the path taken forwards, I don't want this issue to be forgotten about as its only going to keep cropping up until a decision is made about whether `Behaviour` should inherit `BindableObject`.