[X] Ignore Parent DataType on collection
dotnet/maui pull request #24530
Opened 2024-08-30 07:05 UTC by StephaneDelcroix

Picker.ItemDisplayBinding for example shouldn't inherit parent DataType

- fixes #23989

### Description of Change

### Issues Fixed

Fixes #

2024-09-02 07:53 UTC, simonrozsival approved these changes, later dismissed

2024-09-03 09:58 UTC, StephaneDelcroix commented on src/TestUtils/src/Microsoft.Maui.IntegrationTests/Utilities/BuildWarningsUtilities.cs
> +				File = "src/Controls/src/Xaml/XamlServiceProvider.cs.cs",
```suggestion
				File = "src/Controls/src/Xaml/XamlServiceProvider.cs",
```

2024-09-04 14:10 UTC, PureWeen requested changes
Template test on here still seems grumpy

```
Expected warnings file path 'src/Controls/src/Xaml/XamlServiceProvider.cs.cs' was not found.
Expected: not null
But was:  null
```

2024-09-12 13:40 UTC, StephaneDelcroix commented on src/TestUtils/src/Microsoft.Maui.IntegrationTests/Utilities/BuildWarningsUtilities.cs
> +							"Microsoft.Maui.Controls.Xaml.Internals.XamlServiceProvider.XamlServiceProvider(INode,HydrationContext): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttrib
```suggestion
							"Microsoft.Maui.Controls.Xaml.Internals.XamlServiceProvider.XamlServiceProvider(INode,HydrationContext): Using member 'Microsoft.Maui.Controls.Xaml.Internals.XamlDataTypeProvider.XamlDataTypeProvider(IElementNode,HydrationContext)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. XamlDataTypeProvider is not trim and AOT-compatible.",
```

2024-09-25 09:40 UTC, rmarinho approved these changes

2024-09-25 09:40 UTC, merged