Avoid recomputing bindings multiple times and bind BindingContext first
dotnet/maui pull request #24553
Opened 2024-08-31 12:30 UTC by albyrock87

### Description of Change

The two unit tests shows the expectation we all have about bindings:
- eventual `BindingContext` binding should apply before any property binding
- `Binding` should happen only once upon binding context inheritance

### Benchmarks

#### Before

| Method                                          | Mean     | Error   | StdDev  | Gen0     | Gen1    | Gen2    | Allocated |
|------------------------------------------------ |---------:|--------:|--------:|---------:|--------:|--------:|----------:|
| SetProperty                                     | 892.2 us | 7.64 us | 6.77 us |        - |       - |       - |     873 B |
| ApplyPropertyViaBindingContextInheritance       | 379.7 us | 3.94 us | 3.49 us |  76.6602 | 38.0859 |  3.9063 |  644003 B |
| ApplyBindingContextViaBindingContextInheritance | 775.7 us | 8.05 us | 7.13 us | 109.3750 | 54.6875 | 11.7188 |  919289 B |

#### After

| Method                                          | Mean     | Error   | StdDev  | Gen0    | Gen1    | Gen2   | Allocated |
|------------------------------------------------ |---------:|--------:|--------:|--------:|--------:|-------:|----------:|
| SetProperty                                     | 888.5 us | 0.69 us | 0.61 us |       - |       - |      - |     873 B |
| ApplyPropertyViaBindingContextInheritance       | 310.0 us | 1.34 us | 1.25 us | 72.7539 | 36.1328 | 1.9531 |  612002 B |
| ApplyBindingContextViaBindingContextInheritance | 549.1 us | 2.86 us | 2.38 us | 93.7500 | 46.8750 | 4.8828 |  784884 B |

### Issues Fixed

Fixes #10806

2024-09-02 10:09 UTC, albyrock87 commented on src/Controls/src/Core/BindableObject.cs
> +		protected void ApplyBindings()
This method appears unused, shall we `[Obsolete]` it?

2024-09-02 14:18 UTC, rmarinho commented
/azp run

2024-09-06 10:17 UTC, StephaneDelcroix requested changes
this looks good. and if it's green, well, go

there's a small risk associated to this, so I'd retarget to net9.0

2024-09-06 12:13 UTC, StephaneDelcroix approved these changes

2024-09-06 13:54 UTC, merged

2024-09-13 17:18 UTC, rmarinho commented
@albyrock87  @StephaneDelcroix  this test seem to be failing when merging main to net9.0 https://dev.azure.com/xamarin/public/_build/results?buildId=123788&view=ms.vss-test-web.build-test-results-tab&runId=3145016&resultId=102857&paneView=debug

2024-09-13 18:51 UTC, albyrock87 commented
@rmarinho looking at your PR, I see a lot of changes in `BindableObject` are missing.
https://github.com/dotnet/maui/pull/24553/files#diff-ebb14ec14b8baeffdd7b0ae40ffc8bf0e8944f76fdea50fcbc737fb142bfb44a
Maybe a mistake solving merge conflicts?