[IOS] - Fix error when running new template maui app on iOS
dotnet/maui pull request #24567
Opened 2024-09-02 09:16 UTC by NirmalKumarYuvaraj

### Root Cause
An exception was thrown because UITableView was not attached to a window in the Shell page.

### Description of Change
Added a condition to check if uITableView.Window is not null. This verifies the UITableView is attached to a window before retrieving visible cells

### Reference

### Issues Fixed 
Fixes #24525, #22452

### Output

2024-09-04 13:56 UTC, jfversluis commented
/azp run

2024-09-05 15:32 UTC, PureWeen requested changes
NavigationBetweenFlyoutItems looks like a legitimate failure

Bugzilla28570Test you can ignore

2024-09-09 11:57 UTC, NirmalKumarYuvaraj commented
@PureWeen, I've fixed the issue with NavigationBetweenFlyoutItems and I hope that the test case will pass without any failures

2024-09-09 18:18 UTC, PureWeen commented
/azp run

2024-09-09 18:36 UTC, PureWeen approved these changes

2024-09-09 20:26 UTC, PureWeen requested changes
I think the test can be removed from this

2024-09-09 20:26 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22452.cs
> +		App.WaitForElement("FlyoutItem1");
aw dang

unfortunately this automationid's don't work on WinUi it looks like

`NavigationBetweenFlyoutItems` is failing on windows. 

You can add a templated flyout item and then just place a label inside of it and use that?

2024-09-10 22:19 UTC, PureWeen requested changes
Looks like the test is still failing

If you want to replace the flyout item with your own template you can do this

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout?view=net-maui-8.0#define-flyoutitem-appearance

and then locate the items in the flyout that way

2024-09-11 20:58 UTC, PureWeen approved these changes

2024-09-11 20:58 UTC, merged