[Testing] Split off HandlerDoesNotLeak.DatePicker into its own UI test
dotnet/maui pull request #24585
Opened 2024-09-03 20:03 UTC by dustin-wojciechowski

### Description of Change

Split off HandlerDoesNotLeak.DatePicker into its own UI test.

### Issues Fixed
#24147

2024-09-03 20:58 UTC, PureWeen requested changes

2024-09-03 20:58 UTC, PureWeen commented on src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
> -	[InlineData(typeof(DatePicker))]
Instead of deleting this can you add a comment here

// This test was moved to MemoryTests.cs inside Appium

2024-09-03 20:58 UTC, PureWeen commented on src/Controls/tests/TestCases.HostApp/Issues/Issue24147.cs
> +            this.RunMemoryTest(() =>
Can we look at generalizing this test a bit more?

I think we're going to start moving a few of these from device tests to here and it'd probably be good not to have them spread out.

I'm thinking

- rename this to MemoryTests.cs
- Add an entry box and a button
- the test can now uses testcases to enter text and click the button for which test to run

2024-09-09 19:40 UTC, jonathanpeppers reviewed
If we introduce a leak, what does the test failure look like? I'm not certain the test is "the same", if you revert this commit does it fail?

* https://github.com/dotnet/maui/commit/39c144b5a7173023084dd8f259c3815248f3de43

2024-09-09 19:42 UTC, jonathanpeppers commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/MemoryTests.cs
> +		}
Can these be parameterized to a `[Theory]` if only one line is different, the string "WebView" vs "DatePicker"?

2024-09-09 20:47 UTC, PureWeen commented on src/Controls/tests/TestCases.HostApp/Issues/Issue22972.cs
> -            this.RunMemoryTest(() =>
I think leaving this test is fine

It's testing a somewhat slightly different scenario

2024-09-09 22:14 UTC, PureWeen approved these changes

2024-09-09 22:16 UTC, PureWeen commented
I'm going to go ahead and merge this for now

I realize we have some left over changes on here but we're getting a lot of failures right now on CI

We can adjust any findings in a follow up PR that will be incoming soon.

2024-09-09 22:16 UTC, merged