Fix layout when MinimumWidth/HeightRequest is removed on Windows
dotnet/maui pull request #24639
Opened 2024-09-06 22:59 UTC by spadapet

### Description of Change

`ViewExtensions.UpdateMinimumHeight|Width` for WinUI is supposed to update `FrameworkElement.MinHeight|Width` based on the MAUI property `MinimumHeightRequest/MinimumWidthRequest`. But it would completely skip the update when the value was removed, so the previously set value would stay in effect. That locks in the old `FrameworkElement.MinHeight|Width`, and layout doesn't change.

The fix is to remove `FrameworkElement.MinHeight|Width` when `MinimumHeightRequest/MinimumWidthRequest` is removed.

### Issues Fixed

Fixes #24638

2024-09-07 01:00 UTC, PureWeen requested changes
test is faiing

https://dev.azure.com/xamarin/public/_build/results?buildId=123366&view=ms.vss-test-web.build-test-results-tab&runId=3123614&resultId=100011&paneView=debug

2024-09-07 06:02 UTC, spadapet commented
> test is faiing
> 
> https://dev.azure.com/xamarin/public/_build/results?buildId=123366&view=ms.vss-test-web.build-test-results-tab&runId=3123614&resultId=100011&paneView=debug

Ack, the test passed locally on Windows and Android. Maybe I need to request a smaller min width/height since the height ended up being 486 instead of 500.

@PureWeen

2024-09-07 19:16 UTC, PureWeen requested changes

2024-09-07 19:16 UTC, PureWeen commented on src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs
> +				await AttachAndRun(grid, _ =>
I think the test here would be more accurate if you didn't do attachandrun again and just moved your assert tests up after the ClearValue calls

2024-09-08 17:38 UTC, PureWeen approved these changes

2024-09-08 18:45 UTC, merged