[net9.0][Enhancement][iOS] platform specific for entry's keyboard to have a done button
dotnet/maui pull request #24645
Opened 2024-09-07 11:55 UTC by kubaflo

### Description of Change

Right now the only way to set a ripple color for buttons is to use custom mappers or platform specific code. But, for image buttons there is currently no way to do anything.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24644

https://github.com/user-attachments/assets/e27fd999-652a-429b-99f2-f73c1340d845

2024-09-09 16:05 UTC, mattleibow commented
@kubaflo  is your description for another PR? It says ripple and button, but the PR is for iOS and Done.

2024-09-09 16:05 UTC, mattleibow commented
/azp run

2024-09-09 16:09 UTC, mattleibow commented
Editor already has this logic in Core, should this rather be added there as a feature?

2024-09-09 16:15 UTC, kubaflo commented
> @kubaflo is your description for another PR? It says ripple and button, but the PR is for iOS and Done.

@mattleibow my bad 😅 I initially copied pasted from this PR: https://github.com/dotnet/maui/pull/23599

2024-09-09 16:22 UTC, mattleibow commented
@PureWeen maybe this is better in Core for all Entry instances? Also, what if the user wants to hide from Editor? We added this for Editor without a way to disable, so maybe we need to come up with an API or something for net9.0?

2024-09-09 16:24 UTC, mattleibow commented
@tj-devel709 You are our resident "text entry" person/expert/guru...

2024-09-10 16:20 UTC, mattleibow requested changes
After a chat with some folks, I think this is worth making into an actual feature. We already do this for Editor, so making this work the same for Entry is a better thing.

Could this PR be updated to rather be a .NET 9 feature that basically always adds the Done button to Entry - just like we have in Editor.

2024-09-10 16:21 UTC, kubaflo commented
> After a chat with some folks, I think this is worth making into an actual feature. We already do this for Editor, so making this work the same for Entry is a better thing.
> 
> Could this PR be updated to rather be a .NET 9 feature that basically always adds the Done button to Entry - just like we have in Editor.

No problem, I will do it soon!

2024-09-11 00:04 UTC, kubaflo commented
@mattleibow done :)

2024-09-11 15:01 UTC, mattleibow commented
/azp run

2024-11-14 12:51 UTC, jsuarezruiz commented
/rebase

2024-11-18 11:34 UTC, jsuarezruiz commented
/azp run

2024-12-17 09:44 UTC, jfversluis commented
/rebase

2024-12-17 10:13 UTC, jfversluis commented
> After a chat with some folks, I think this is worth making into an actual feature. We already do this for Editor, so making this work the same for Entry is a better thing.
> 
> Could this PR be updated to rather be a .NET 9 feature that basically always adds the Done button to Entry - just like we have in Editor.

Hm not sure who you talked to, but I'd love to discuss this a bit more. Adding a (visual) breaking change without a way to opt-out doesn't sound like a great thing to me. 

It would make more sense to me to implement what we wanted to do originally here: make a platform-specific (or setting, if it is relevant to more platforms) that allows to customize this behavior for both the `Entry` and the `Editor`. Ideally with the setting set to true by default for the `Editor` since it's already on there and false for the `Entry` because we don't have it there today.

That way people can opt-in/out when they want but it doesn't change the default behavior of their apps today.

2025-06-06 20:15 UTC, Dreamescaper commented
> Ideally with the setting set to false for the Entry because we don't have it there today.

I disagree with that default, since it makes it inconsistent with other platforms, and simply doesn't make sense. What is the use-case when I'd want that button hidden?

Still, it would be better to have it done either way that not done at all, as currently Entry experience is very frustrating.

2025-06-26 09:59 UTC, jfversluis approved these changes, later dismissed

2025-08-05 22:58 UTC, PureWeen commented
> > After a chat with some folks, I think this is worth making into an actual feature. We already do this for Editor, so making this work the same for Entry is a better thing.
> > Could this PR be updated to rather be a .NET 9 feature that basically always adds the Done button to Entry - just like we have in Editor.
> 
> Hm not sure who you talked to, but I'd love to discuss this a bit more. Adding a (visual) breaking change without a way to opt-out doesn't sound like a great thing to me.
> 
> It would make more sense to me to implement what we wanted to do originally here: make a platform-specific (or setting, if it is relevant to more platforms) that allows to customize this behavior for both the `Entry` and the `Editor`. Ideally with the setting set to true by default for the `Editor` since it's already on there and false for the `Entry` because we don't have it there today.
> 
> That way people can opt-in/out when they want but it doesn't change the default behavior of their apps today.

@mattleibow ?

2025-08-06 00:26 UTC, PureWeen commented
/rebase

2025-08-06 00:29 UTC, PureWeen commented
/azp run

2025-08-20 18:05 UTC, PureWeen requested changes
@kubaflo can you fix tests on this one and rebase?

2025-08-21 04:10 UTC, PureWeen commented
/azp run

2025-08-23 19:28 UTC, PureWeen commented
/azp run

2025-08-23 19:28 UTC, PureWeen approved these changes

2025-08-27 12:24 UTC, jfversluis approved these changes
Let's do this. We can always add a opt-in/opt-out for it later!

2025-08-27 12:25 UTC, merged