Fix 20736
dotnet/maui pull request #24683
Opened 2024-09-10 07:44 UTC by Tamilarasan-Paranthaman

### Root Cause: 

- On iOS, when the Editor control is enclosed in a Border, the Border's ClipPath bounds cause only the initial content of the Editor to be visible. If the Editor is scrollable, the offset does not update correctly during vertical scrolling. As a result, only the initial content is visible during scrolling, while the rest of the view remains hidden.

 
### Description of Change: 

- To address this, I updated the border’s ContentMask path with the current values to ensure proper masking throughout the scrolling process.

### Issues Fixed

Fixes #20736
Fixes #18486

### Screenshots 

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600" controls source src="https://github.com/user-attachments/assets/278fe296-aaa7-4c88-974d-950c5d60b192"> | <video width="300" height="600" controls source src="https://github.com/user-attachments/assets/2d90a086-1e0b-45c3-9e2c-b3f237ffc527"> |

2024-09-24 01:49 UTC, last-Programmer commented
This is blocking me to migrate to border conrol from frame. with editor inside frame it is working fine. now the frame is deprecated in .net 9 and need to migrate to border. but without this fix we cant migrate. WIll it be fixed when .net 9 released.

thanks

2024-09-25 19:33 UTC, PureWeen requested changes
I ran the attached uitest without the fix and it doesn't reproduce the issue. 

It looks like it has to be inside a layout in order for it to reproduce

```XAML
  <VerticalStackLayout>
            <Border Stroke="LightGray">
                <Editor  HeightRequest="100"
                         Text="Line 1&#xa;Line 2&#xa;Line 3&#xa;Line 4&#xa;Line 5&#xa;Line 6&#xa;Line 7&#xa;" />
            </Border>
        </VerticalStackLayout>
```

If I remove the VSL then it no longer cuts. Which also makes me wonder if this is the correct fix. 

I worry about the EditorHandler having to inspect the parent to know if it needs a container. This fix feels a little bit like it's not resolving the core issue

2024-09-26 10:18 UTC, Tamilarasan-Paranthaman commented
@PureWeen, without the VerticalStackLayout, the Border will occupy the full height, and the issue only occurs when the editor's content height exceeds the content mask height. If you scroll the Editor with only 7 lines and without the VerticalStackLayout, the editor's content height will not extend beyond the content mask height. This issue typically appears after adding around 28 or 29 lines in this scenario.

However, you can still reproduce the issue without the VerticalStackLayout by setting the Border's HeightRequest to 150, which will reveal the problem when scrolling vertically.

I apologize for the inconvenience. I missed adding the VerticalStackLayout in my test case. Should I include the VerticalStackLayout or set the Border's HeightRequest in my test case? Which option would you recommend?

2024-10-03 15:23 UTC, cagriy commented
It works fine in Frame if anybody desperately needs rounded corners (or if this helps towards a fix).

2024-10-04 09:19 UTC, last-Programmer commented
@cagriy frame is being deprecated in .net 9. It is recommened to migrate to border since frame is deprecated and will be removed in future versions. Without this fix we cant migrate to border control.

2024-10-04 22:02 UTC, PureWeen requested changes

2024-10-04 22:02 UTC, PureWeen commented on src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
> +				if (VirtualView?.Parent is IBorderView)
I don't feel like this is the approach we'll want to take here. 

1) Users report that this all works fine with the Frame control
2) it doesn't feel like Editor should be reaching up to the parent here to figure out if it needs a container.  This feels like it's not fixing the root of the problem. 

I'm still poking a bit to see if I can figure out a better approach here. 

I'm curious if there's a way to fix this inside the BorderView control vs fixing here

2024-10-04 23:07 UTC, kubaflo commented
Hi! What do you think about this one https://github.com/dotnet/maui/pull/25098

2024-10-04 23:10 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20736.cs
> +			await Task.Delay(1000);
I'm not sure if this will generate the same screenshots every time 🤔

2024-11-26 12:53 UTC, jsuarezruiz commented
@Tamilarasan-Paranthaman Could you rebase to fix the conflicts? Thanks in advance.

2025-01-09 22:11 UTC, closed without merging