Create PlatformElementFactory to ElementHandler
dotnet/maui pull request #24704
Opened 2024-09-11 03:31 UTC by pictos

This PR adds ability to easily override the PlatformElement for ElementHandler, on ViewHandler we have the PlatformViewFactory as a way to override platform view that will be used by it. Now I'm adding this extension to ElementHandler as well.

2024-09-11 15:07 UTC, mattleibow commented on src/Core/tests/UnitTests/ElementHandlerTests.cs
> +			Assert.True(elementStub.PlatformView is CustomPlatformCell);
I think this is better for error messages and will fail if it is not exactly that type:

```suggestion
			Assert.IsType<CustomPlatformCell>(elementStub.PlatformView);
```

2024-09-11 16:17 UTC, mattleibow commented
/azp run

2024-09-11 17:30 UTC, mattleibow requested changes
Abusing the "request changes" because our dashboard requires that I pick something...

What was the reason for this one? Did you hit a specific case where you needed this? I think Element is mostly just Application, Window and MenuItem?

2024-09-12 00:59 UTC, pictos commented
@mattleibow, I'm sorry for taking so long to answer, during the week I can just enter here during the night.  

> What was the reason for this one? Did you hit a specific case where you needed this?

This was raised on a discussion with @PureWeen, Right now we can override the platformView from ViewHandlers without subclassing the view handler, so for example, in an iOS target, where we have

```cs
public partial class ButtonHandler : ViewHandler<IButton, UIButton>
{
}
```

If I want to customize the platformView to be a custom implementation of UIButton, I can do

`ButtonHandler.PlatformViewFactory = h => return new MyUIButton();`

and then I'm happy and the `Microsoft.Maui.Button` will renderer `MyUIButton`. 

That's not true for Elements... Since I don't have a Factory there I have to subclass the ElementHandler and override the `CreatePlatformElement`, this is too XF, no?

> I think Element is mostly just Application, Window and MenuItem?

No, MapPin is an Element, all Cells are Elements, the Popup control on MCT is an Element... So if it's needed to customize any of these we need to go with the an _anti-pattern_ (since, AFAIK, MauiHandlers aren't meant to be subclassed in order to customize it)

> The annoying thing is that the view handler will now have 2 factories :(


Looking into the unit test, there's only one Factory still, the factory inside the ElementHandler will not be shown for ViewHandlers types. As you can see in the screenshot.

<img width="976" alt="image" src="https://github.com/user-attachments/assets/3d6308f7-d65c-4a57-9113-09e59f527b74">

2024-10-17 19:25 UTC, closed without merging

2024-10-17 19:25 UTC, PureWeen commented
I'm closing this one for now pending more discussion