[Localization] Remove check not allowing translations to run on net9.0
dotnet/maui pull request #24724
Opened 2024-09-11 21:38 UTC by tj-devel709

### Description of Change

In the net9.0 branch, the translations section is not being applied. `- ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:` being false caused the localization templates not to be run. I'm not sure if we need to replace this with something else but I think it should work as this PR has it since that templates all have their own checks on whether to run.

### Issues Fixed

Fixes #

2024-09-11 22:16 UTC, rmarinho commented
Did we got anything for main?

2024-09-12 03:56 UTC, tj-devel709 commented
> Did we got anything for main? translations only happen on devdiv, having that code shouldn't t be the issue

Yeah it is being run in main right now: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10209378&view=logs&s=266d6c29-b55e-56e1-41c4-d0d9dc0f16a7

2024-09-12 14:34 UTC, tj-devel709 commented
/azp run

2024-09-13 09:18 UTC, rmarinho requested changes
you need to look at variables that start the process on common/variables.yaml

2024-09-13 18:38 UTC, tj-devel709 commented
> you need to look at variables that start the process on common/variables.yaml

The variable of `System.TeamProject` that was being used before does not appear to be in common/variables.yaml if that is what you mean? It seems to be an environment var that contains devdiv in the main branch but not in the net9.0 branch. Maybe it should be set in the net9.0 branch?

2024-09-16 21:03 UTC, tj-devel709 commented
/azp run

2024-09-26 15:20 UTC, tj-devel709 commented
This is incorrect and not needed!

2024-09-26 15:20 UTC, closed without merging