Relative layout content disappeared when Relative layout has the border with border stroke element.
dotnet/maui pull request #24841
Opened 2024-09-20 09:29 UTC by NanthiniMahalingam

### Root cause

•	When we set the stroke shape for border, visual element stroke shape is added to the border. Here, handler does not set to the stroke shape element. 
•	Therefore, IsPlatformEnabled property is set to false for stroke shape of visual element.
•	It caused the content disappeared due to update children calculation does not invoked.

### Description of changes

- I have added the condition if shape is ShapeView, convert the shapeview to ToPlatform by passing the border maui context for all the platform.

Validated the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

Issues Fixed:
Fixes [23934](https://github.com/dotnet/maui/issues/23934)

Output images:
Windows platform:
Before changes:
![image](https://github.com/user-attachments/assets/37839480-a952-4f59-9d96-7a64dfbeba95)

After changes:
![Windows_AfterChanges](https://github.com/user-attachments/assets/4610cfe2-fa41-49f0-9147-d6041a023982)

Android 
Before changes:
![Android_BeforeChanges](https://github.com/user-attachments/assets/b871ff61-99d4-4e88-8c28-9e3317750d82)

After changes:

<img width="252" alt="Android_AfterChanges" src="https://github.com/user-attachments/assets/a16b5382-e956-4d74-8d9e-346a12f05a40">

iOS 
Before changes:
![iOS_BeforeChanges](https://github.com/user-attachments/assets/33219ed7-8658-464c-ab8e-be2b6ffa4e62)

After changes:

![iOS_AfterChanges](https://github.com/user-attachments/assets/86a0885d-191e-42b4-ac9f-3ccd39625009)

macOS
Before changes:
![macOS_BeforeChanges](https://github.com/user-attachments/assets/9783cada-de38-40de-8917-6d47a23c340d)

After changes:
![macOS_AfterChanges](https://github.com/user-attachments/assets/8ed4cde8-54c2-46ad-8d48-29196f6ad09f)

2024-09-20 11:04 UTC, rmarinho commented
/azp run

2024-10-08 11:29 UTC, rmarinho commented
/azp run

2024-10-09 11:25 UTC, jsuarezruiz commented
/rebase

2024-10-09 15:24 UTC, PureWeen requested changes
Where is this check happening?

> • Therefore, IsPlatformEnabled property is set to false for stroke shape of visual element.

I'm wondering if we can resolve this issue without needing to call ToPlatform on the shapeviews

2024-10-16 13:44 UTC, NanthiniMahalingam commented
Hi @PureWeen 
> Where is this check happening?
> 
> > • Therefore, IsPlatformEnabled property is set to false for stroke shape of visual element.
> 
> I'm wondering if we can resolve this issue without needing to call ToPlatform on the shapeviews

We have modified the fix without the need to call the ToPlatform method on the shape view. Could you please verify once?

2024-10-25 09:47 UTC, jsuarezruiz commented
/azp run

2024-10-28 11:13 UTC, jsuarezruiz commented
/azp run

2024-10-31 16:36 UTC, jsuarezruiz reviewed
Only happens with RelativeLayout or with all the legacy layouts?

2024-11-01 06:59 UTC, NanthiniMahalingam commented
> Only happens with RelativeLayout or with all the legacy layouts?

Hi @jsuarezruiz ,
The issue occurs with all legacy layouts.

2025-01-06 09:49 UTC, PureWeen approved these changes

2025-01-06 09:49 UTC, merged