Fixed - 24866- [Windows] CollectionView with grouping fails to add items when a footer template is present or crashes when removing data.
dotnet/maui pull request #24867
Opened 2024-09-23 09:25 UTC by NirmalKumarYuvaraj

### Root Cause

 - **Add** - When a CollectionView contains grouping and a footer template, we create a new List<object> and add the footer to the list if the footer's item template type is not an IList. This prevents events such as CollectionChanged or INotifyCollectionChanged from being triggered on the original collection. As a result, when a new item is added to the collection, it is not reflected in the view.

 - **Clear** - When clearing the collection and adding items at runtime, a COM exception occurs when items are grouped. This happens because the OnItemsVectorChanged event is triggered whenever there is a change in the item collection, causing ListViewBase.ScrollIntoView to be called from a background thread, which leads to the COM exception.
 
### Description of Change
 
#### Windows 

 - **Add** - Reverting the changes made in PR #24205 caused the exception . This exception occurred due to the triggering of the TemplateCollectionChanged event, which was introduced during the implementation of drag-and-drop functionality for the CollectionView in PR #3768. Adding the footer to the items triggers the TemplateCollectionChanged event, which incorrectly adds the footer as a new item in the collection. Since the footer template is not the same type as the items in the original collection, this results in the exception. To resolve this, we can ignore the addition of the footer template to the ItemsSource.
 
 - **Clear** - Calling ListViewBase.ScrollIntoView after a slight delay helps avoid exceptions and ensures synchronized updates.
 
Validated the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [] iOS
- [] Mac
 
iOS and Mac has issues - #17969 
 
### Issues Fixed
  
Fixes #24866 

### Output 

#### Windows
**Before**

https://github.com/user-attachments/assets/2813d618-2c9d-4700-af20-8402b0779597

**After**

https://github.com/user-attachments/assets/bb96519e-5a70-47a8-a872-d61ac2cf8f4f

2024-10-23 09:39 UTC, jsuarezruiz commented
@NirmalKumarYuvaraj Could you rebase and fix the conflict? Thanks in advance.

2025-01-10 07:05 UTC, jsuarezruiz commented
@NirmalKumarYuvaraj Could you rebase to fix the conflicts?

2025-01-23 14:23 UTC, jfversluis commented
/azp run

2025-02-17 12:52 UTC, jsuarezruiz commented
/rebase

2025-02-24 16:31 UTC, jsuarezruiz commented
/rebase

2025-02-26 07:15 UTC, jsuarezruiz commented
/azp run

2025-02-26 10:17 UTC, jsuarezruiz requested changes
The test **JustWhalingAwayOnTheCollectionViewWithAddsAndClearsShouldNotCrash** is crashing:
`The app was expected to be running still, investigate as possible crash`
I think could be related with the changes, could you take a look?

2025-03-03 07:34 UTC, NirmalKumarYuvaraj commented
> The test **JustWhalingAwayOnTheCollectionViewWithAddsAndClearsShouldNotCrash** is crashing: `The app was expected to be running still, investigate as possible crash` I think could be related with the changes, could you take a look?

@jsuarezruiz , I have updated the code changes and ensured the test case is passing locally. Please let me know if you have any concerns.

![image](https://github.com/user-attachments/assets/e66d5606-9fe1-4951-9a99-336e2a2291fd)

2025-03-11 10:11 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:29 UTC, jsuarezruiz commented
/azp run

2025-06-09 07:37 UTC, jsuarezruiz commented
@NirmalKumarYuvaraj Could you fix the conflict?

2025-06-09 08:44 UTC, NirmalKumarYuvaraj commented
> @NirmalKumarYuvaraj Could you fix the conflict?

@jsuarezruiz , I have rebased the branch. please let me know if you have any concern.

2025-06-13 11:17 UTC, jsuarezruiz commented
/azp run

2025-06-24 16:06 UTC, bronteq commented
@jsuarezruiz friendly ping, no related issues on CI

2025-07-09 17:00 UTC, baaaaif commented
Would be great if this could be planned into a service release version

2025-07-15 12:12 UTC, jsuarezruiz commented
/rebase

2025-07-15 12:14 UTC, jsuarezruiz commented
/azp run

2025-07-17 07:25 UTC, NirmalKumarYuvaraj commented
@jsuarezruiz , CI is green

2025-08-22 13:38 UTC, bronteq commented
This is another related issue https://github.com/dotnet/maui/issues/20037

2025-10-31 12:15 UTC, jsuarezruiz commented
/rebase

2026-03-05 05:45 UTC, MFinkBK commented
@NirmalKumarYuvaraj @jfversluis Can we check if the PR can be merged at least for .NET MAUI 10? I'm trying to get rid of workarounds in my app and this is one of the issues. Thank you!

2026-03-05 08:24 UTC, jfversluis commented
@MFinkBK keep them coming! If you hop on the [MAUIverse Discord](https://mauiverse.net/discord) we can discuss a bit more easier. Would love to get rid of all of those for you.

2026-03-05 08:24 UTC, jfversluis commented
/rebase

2026-03-05 14:00 UTC, jfversluis commented
/azp run maui-pr-uitests

2026-03-06 07:38 UTC, MFinkBK commented
@jfversluis I can't quite figure out the checks... some were cancelled, some timed out and some reported errors on iOS. So are there problems we need to address? Quite hard to understand the checks... Thanks!

2026-03-06 12:01 UTC, jfversluis commented
@MFinkBK don't worry about those too much. Are you able to test the artifacts from this? I am mainly concerned with this one how it would impact performance for bigger lists.

2026-03-09 14:13 UTC, MFinkBK commented
@jfversluis I tested with the NuGet packages produced by the build (version name was "10.0.50-ci.pr24867.26155.2") and it fixed the crash on Windows when adding items on a grouped `CollectionView` in combination with an `ObservableCollection`. I didn't check timing as I usually don't have long lists of items in there. From looking at the code it seems it's mostly a rearrangement of code and two new `if` checks in `ObservableItemTemplateCollection.cs`.

2026-03-09 14:43 UTC, jfversluis requested changes
## Multi-Model Code Review

Three independent AI models (Claude Opus 4.5, Gemini 3 Pro, GPT-5.2) reviewed this PR and **all three converged on the same two blocking issues**.

### 🔴 CRITICAL: `RemoveFromSource` Index Bug — Will Crash at Runtime

In `ObservableItemTemplateCollection.cs`, the new footer-skip check accesses `args.OldItems[n]`, but `n` ranges from `startIndex+count-1` down to `startIndex`, while `args.OldItems` is **0-indexed** with length `count`.

```csharp
for (int n = startIndex + count - 1; n >= startIndex; n--)
{
    // BUG: If startIndex=3, count=2 → n=4,3
    // But OldItems only has indices 0 and 1 → IndexOutOfRangeException
    if ((ItemTemplateContext)args.OldItems[n] is not GroupFooterItemTemplateContext)
    {
        _itemsSource.RemoveAt(n);
    }
}
```

**Fix:**
```csharp
for (int n = startIndex + count - 1; n >= startIndex; n--)
{
    if ((ItemTemplateContext)args.OldItems[n - startIndex] is not GroupFooterItemTemplateContext)
    {
        _itemsSource.RemoveAt(n);
    }
}
```

### 🔴 HIGH: DispatcherQueue Closure Captures Potentially Disposed Objects

In `ItemsViewHandler.Windows.cs`, the `TryEnqueue` callback captures `VirtualView` and `ListViewBase` via closure. If the handler disconnects before the callback fires (e.g., user navigates away), these become null → `NullReferenceException`.

**Fix — add null guards inside the callback:**
```csharp
ListViewBase.DispatcherQueue.TryEnqueue(() =>
{
    if (VirtualView is null || ListViewBase is null)
        return;

    var itemsCount = items.Count;
    // ... rest of code
});
```

### 🟡 MEDIUM: `AddToSource` — Insertion Index Not Incrementing

When footer items are skipped in the `AddToSource` loop, the `startIndex` used for `_itemsSource.Insert(startIndex, ...)` is never incremented. For multi-item batch additions containing a mix of real items and footer items, subsequent real items will be inserted at the same index, potentially reversing their order.

### ✅ Changes That Are Correct

- **`GroupTemplateContext.cs` reorder**: The IList-first check is correct. The old code had a pre-existing bug (`Type is not IList` always evaluated true because `System.Type` never implements `IList`), meaning it always copied to a new `List<object>`, breaking `ObservableCollection` change notifications. The new ordering correctly preserves the original collection.
- **Test changes**: Removing `[FailsOnWindowsWhenRunningOnXamarinUITest]` is appropriate since this fix enables those tests to pass.
- **Overall approach**: Using `DispatcherQueue.TryEnqueue` to defer `ScrollIntoView` is the correct WinUI pattern to avoid COM exceptions during `VectorChanged` callbacks.

---

@NirmalKumarYuvaraj — The approach here is solid and fixes real bugs, but the `RemoveFromSource` index issue will cause crashes whenever items are removed from a position other than index 0 in a grouped CollectionView with footers. Could you address the issues above? Thanks! 🙏

2026-03-10 11:23 UTC, NirmalKumarYuvaraj commented
@jfversluis , Addressed the review concern. Please let me know if you have any concerns

2026-03-12 14:20 UTC, jfversluis approved these changes

2026-03-12 14:21 UTC, merged