[Improvement] Add ReturnType API for SearchBar
dotnet/maui pull request #24906
Opened 2024-09-24 14:27 UTC by redducks100

Closed the previous MR because of a stupid git mistake I made.

### Description of Change

Added ReturnType API for SearchBar like it is done for Entry.

### Issues Fixed

Fixes #19872 

![defaultReturnType](https://github.com/user-attachments/assets/3ee2d44b-462e-4006-a478-bc6cc0c9ba38) ![nextReturnType](https://github.com/user-attachments/assets/eed7cba4-54f6-44c7-8874-84364ef2105a)

2024-09-24 15:00 UTC, rmarinho commented
Needs to target net9.0

2024-09-24 16:00 UTC, rmarinho commented
/azp run

2025-03-05 12:55 UTC, rmarinho commented
/azp run

2025-03-10 14:57 UTC, jsuarezruiz approved these changes, later dismissed

2025-03-19 12:38 UTC, rmarinho commented
/rebase

2025-03-19 16:14 UTC, rmarinho commented
/azp run

2025-03-20 18:26 UTC, rmarinho commented
/azp run

2025-03-24 17:57 UTC, rmarinho requested changes
D:\a\1\s\src\Core\src\Handlers\SearchBar\SearchBarHandler.cs(38,36): error CS0021: Cannot apply indexing with [] to an expression of type 'method group' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=netstandard2.0]

2025-03-24 17:59 UTC, rmarinho commented
/azp run

2025-03-25 16:48 UTC, rmarinho submitted a review, later dismissed

2025-03-25 16:49 UTC, rmarinho approved these changes

2025-03-25 16:50 UTC, rmarinho commented
Tests were green before, on https://github.com/dotnet/maui/pull/24906/commits/b68ea9becda58bcab08a0f572c7455bd757c5fb0 , so we can merge

2025-03-25 16:50 UTC, merged