[Android] Fix scroll bar visibility set to Always not consistant
dotnet/maui pull request #24901
Opened 2024-09-24 13:28 UTC by redducks100

### Description of Change

On Android the vertical and horizontal scrollbars would fade even if visibility was set to "Always". This was due to not updating the ScrollBarFadingEnabled variable from the scrollViews. Setting this to false when visibility is set to "Always" fixes the issue and makes more sense from developer experience.

### Videos

Before fix:

https://github.com/user-attachments/assets/eec5a51c-0c36-4f9f-b7e4-fa22b2c9ab09

After fix:

https://github.com/user-attachments/assets/e350c5d9-8867-4580-ba5e-c6095efc3e39

### Issues Fixed
Fixes #24894
Fixes #12760

2024-09-25 22:20 UTC, PureWeen commented
/azp run

2024-10-28 13:07 UTC, redducks100 commented
Hey @PureWeen could you re-run the azure pipeline again? Did some changes to fix a bug I introduced (scrollBar was always visible when visibility was set to Default).

2024-11-04 14:59 UTC, jsuarezruiz commented
/azp run

2024-11-08 10:50 UTC, jsuarezruiz requested changes

2025-01-10 13:49 UTC, mattleibow requested changes
Thanks for this PR, let us know if you are having any issues addressing the comments or if you would like some assistance in getting this through the merge door..

2025-01-10 13:49 UTC, mattleibow commented on src/Core/src/Platform/Android/MauiScrollView.cs
> +				_hScrollView.ScrollbarFadingEnabled = scrollBarVisibility != ScrollBarVisibility.Always;
This looks like it is never reset if you do default. What happens if you move this out of the else and next to the line below:

```cs
_hScrollView.HorizontalScrollBarEnabled = scrollBarVisibility == ScrollBarVisibility.Always
```

I think it should still work.

2025-01-10 13:49 UTC, mattleibow commented on src/Core/src/Platform/Android/MauiScrollView.cs
> +				ScrollbarFadingEnabled = scrollBarVisibility != ScrollBarVisibility.Always;
Same as above, move it out of the else.

2025-01-10 13:49 UTC, mattleibow commented on src/Core/tests/DeviceTests/Handlers/ScrollView/ScrollViewHandlerTests.Android.cs
> +		public async Task VerticalScrollbarFadingInitializesCorrectly(ScrollBarVisibility visibility, bool expected)
Are you having issues adding this test?

2025-01-14 11:48 UTC, redducks100 commented on src/Core/tests/DeviceTests/Handlers/ScrollView/ScrollViewHandlerTests.Android.cs
> +		public async Task VerticalScrollbarFadingInitializesCorrectly(ScrollBarVisibility visibility, bool expected)
Yes, I tried using ValidatePropertyUpdatesValue but I can't access the ScrollbarFading property as it's not included in the public interface? Or maybe I was doing it wrong.. :(

2025-02-03 22:12 UTC, PureWeen commented
Closing this PR for now

I've asked Syncfusion to create a new PR with these changes and tests

2025-02-03 22:12 UTC, closed without merging