fix-5669-Fix for Windows SearchBar MaxLength > 0 not working properly.
dotnet/maui pull request #24919
Opened 2024-09-25 07:16 UTC by BagavathiPerumal

### Root cause

WinUI AutoSuggestbox does not have MaxLength property in native, SearchBar.MaxLength is not updated to native property.

### Description of Issue Fix

Got child of AutoSuggestbox which is textbox in OnLoaded event and in MapMaxLength and updated the  SearchBar.MaxLength to native textbox.MaxLength.

Tested the behavior in the following platforms.
 
- [x] Android
- [x] Windows
- [x] iOS
- [ ] Mac

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/5669

### Output

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/3f4fa6f2-b30e-4e73-b8c9-a7a79976cd5f"> | <video width="270" height="600"  src="https://github.com/user-attachments/assets/cd55d115-f6dd-4c67-9f9d-0b1f37f2cb8b"> |

2024-09-25 10:24 UTC, BagavathiPerumal commented on src/Core/src/Platform/Windows/SearchBarExtensions.cs
> +				textbox!.MaxLength = searchBar.MaxLength;
@MartyIX, I have modified changes. Could you please validate it once and let me know if there are any further concerns.

2024-09-25 10:51 UTC, BagavathiPerumal commented on src/Core/src/Platform/Windows/SearchBarExtensions.cs
> +			}
@MartyIX, I have modified changes based on your suggestion. Could you please validate it once and let me know if there are any further concerns.

2024-09-25 11:15 UTC, BagavathiPerumal commented on src/Core/src/Platform/Windows/SearchBarExtensions.cs
> +			if (child is not null && child.Count() > 0)
@MartyIX, I have modified changes. Could you please validate it once and let me know if there are any further concerns.

2024-09-25 11:39 UTC, BagavathiPerumal commented on src/Core/src/Platform/Windows/SearchBarExtensions.cs
> +			var child = platformControl.GetChildren<TextBox>();
@MartyIX, I have made changes based on your concerns. Please validate and let me know if there are any issues.

2024-09-26 11:30 UTC, jfversluis commented
/azp run

2024-09-26 18:43 UTC, rmarinho submitted a review, later dismissed
I think it's missing some using the builds is failing

```
D:\a\1\s\src\Core\src\Platform\Windows\SearchBarExtensions.cs(118,28): error CS1061: 'IEnumerable<TextBox?>' does not contain a definition for 'FirstOrDefault' and no accessible extension method 'FirstOrDefault' accepting a first argument of type 'IEnumerable<TextBox?>' could be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
```

2024-09-27 09:55 UTC, BagavathiPerumal commented
> I think it's missing some using the builds is failing
> 
> ```
> D:\a\1\s\src\Core\src\Platform\Windows\SearchBarExtensions.cs(118,28): error CS1061: 'IEnumerable<TextBox?>' does not contain a definition for 'FirstOrDefault' and no accessible extension method 'FirstOrDefault' accepting a first argument of type 'IEnumerable<TextBox?>' could be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
> ```

@rmarinho, I have modified changes for this issue. Could you please validate it once and let me know if there are any further concerns.

2024-09-27 10:18 UTC, rmarinho commented
Can we also rebase on main? we made some changes on the pipeline agents and we need the pr to pick them up. 

Thanks

2024-09-27 10:28 UTC, rmarinho commented
/rebase

2024-09-27 10:29 UTC, rmarinho commented
/azp run

2024-09-27 10:52 UTC, rmarinho commented
/azp run

2024-09-27 11:15 UTC, BagavathiPerumal commented
> Can we also rebase on main? we made some changes on the pipeline agents and we need the pr to pick them up.
> 
> Thanks

@rmarinho, I have rebased this branch successfully.

2024-10-01 08:35 UTC, rmarinho commented
/azp run

2024-10-02 21:20 UTC, PureWeen requested changes
SearchBarMaxLength failing

2024-10-03 07:34 UTC, BagavathiPerumal commented
> SearchBarMaxLength failing

@PureWeen, I have updated test image for this issue. Could you please validate it once and let me know if there are any further concerns.

2024-10-03 09:09 UTC, rmarinho commented
/azp run

2024-10-03 20:58 UTC, PureWeen requested changes

2024-10-03 20:58 UTC, PureWeen commented on src/Core/src/Platform/Windows/SearchBarExtensions.cs
> +				var textBox = children.FirstOrDefault();
By convention we stay away from using Linq

Can you remove the use of linq here?

2024-10-03 22:04 UTC, Foda submitted a review, later dismissed
LGTM, just please address LINQ comment

2024-10-04 07:42 UTC, BagavathiPerumal commented
> LGTM, just please address LINQ comment

@Foda, I have updated the code based on your suggestion. Could you please review it and let me know if you have any further concerns.

2024-10-04 21:54 UTC, PureWeen submitted a review, later dismissed

2024-10-04 21:55 UTC, PureWeen commented
/azp run

2024-10-07 11:54 UTC, jsuarezruiz commented
/azp run

2024-10-07 23:16 UTC, PureWeen approved these changes

2024-10-08 16:54 UTC, merged