First tests (disabled) from Control Gallery to Appium
dotnet/maui pull request #24943
Opened 2024-09-26 13:43 UTC by jfversluis

First PR moving remaining tests from the control gallery into the right place for more modern test running with Appium.

Tests are moved as disabled and we will run through these again to reenable them as we go.

Related to #24153

2024-09-27 11:02 UTC, jfversluis commented
/rebase

2024-10-02 19:27 UTC, PureWeen requested changes
Can we put all of these in a new folder specific to Bugzilla?

It'd be nice to get the issues folder a bit organized between
- Bugzilla
- XF Github
- MAUI Github

2024-10-06 21:37 UTC, jfversluis commented
We probably want to merge #25111 first to avoid conflicts

2024-10-08 10:17 UTC, jsuarezruiz approved these changes

2024-10-08 14:40 UTC, PureWeen approved these changes

2024-10-08 14:40 UTC, merged