[Android] Tabs briefly display wrong background color when navigating between flyout items
dotnet/maui pull request #24965
Opened 2024-09-27 10:35 UTC by NanthiniMahalingam

### Root Cause:
- On Android, the BottomNavigationView initially has a ColorDrawable with a white background, which is the default color during its creation. 
- Later, the BottomNavigationView background is changed to a ColorChangeRevealDrawable with an animation, transitioning to the color specified by IShellAppearanceElement.EffectiveTabBarBackgroundColor. 
- Since the previous background color (white) differs from the current color (black), the animation displays a transition from white to black when switching pages.
 
### Description of Change:
- To resolve this issue, the IShellAppearanceElement.EffectiveTabBarBackgroundColor is applied to the background of the BottomNavigationView immediately after its creation. 
- This ensures that no animation is triggered later, as the previous background color (black) and the current color (black) remain the same.

**Tested the behaviour in the following platforms.**
- [x] Android
- [] Windows
- [] iOS
- [] Mac

### Reference
N/A

### Issues Fixed
Fixes #16522

### Screenshots
Before changes:
![Before_changes](https://github.com/user-attachments/assets/30691737-50d0-406d-af36-bc297413c779)

After changes:
![After_changes](https://github.com/user-attachments/assets/601710cb-6e0c-4542-9c4b-b126dfdecf02)

2024-10-03 12:20 UTC, jfversluis commented
/azp run

2024-10-03 21:14 UTC, PureWeen submitted a review, later dismissed
Test failures on this one seem accurate

2024-10-09 11:27 UTC, jsuarezruiz commented
/rebase

2024-10-09 13:26 UTC, jsuarezruiz commented
/azp run

2024-10-09 15:30 UTC, PureWeen commented
> > Test failures on this one seem accurate
> 
> @PureWeen The test case failing seems to be in Windows, even though the fix is specifically added for android. Could you please check this once? If not can we try triggering the CI once.

> > Test failures on this one seem accurate
> 
> @PureWeen The test case failing seems to be in Windows, even though the fix is specifically added for android. Could you please check this once? If not can we try triggering the CI once.

The failure I'm referring to is that both API levels of the Android aren't running to completion

It looks like the changes here are causing the device tests on android to crash.
If you download the logcat file from the device test runs you should be able to see a crash in there that will need to be resolved

https://github.com/dotnet/maui/blob/main/docs/design/UITesting.md#logging

2024-10-15 06:26 UTC, NanthiniMahalingam commented
> > > Test failures on this one seem accurate
> > 
> > 
> > @PureWeen The test case failing seems to be in Windows, even though the fix is specifically added for android. Could you please check this once? If not can we try triggering the CI once.
> 
> > > Test failures on this one seem accurate
> > 
> > 
> > @PureWeen The test case failing seems to be in Windows, even though the fix is specifically added for android. Could you please check this once? If not can we try triggering the CI once.
> 
> The failure I'm referring to is that both API levels of the Android aren't running to completion
> 
> It looks like the changes here are causing the device tests on android to crash. If you download the logcat file from the device test runs you should be able to see a crash in there that will need to be resolved
> 
> https://github.com/dotnet/maui/blob/main/docs/design/UITesting.md#logging

•	I identified the cause of the crash during device testing on Android API 23. 
•	The issue arises because the EffectiveTabBarBackgroundColor property is null in this API version. 
•	To resolve this, I applied the DefaultBottomNavigationViewBackgroundColor as a fallback to ensure the background color is set properly.

2024-10-25 09:46 UTC, jsuarezruiz commented
/azp run

2024-10-30 08:24 UTC, jsuarezruiz requested changes
Could you include an UITest verifying the tabs background color?

2024-11-05 11:15 UTC, NanthiniMahalingam commented
> Could you include an UITest verifying the tabs background color?

Hi @jsuarezruiz 
I have added UI test case for TabBarBackgroundColor. Please let us know if you have any further concerns.

2024-11-05 12:05 UTC, jsuarezruiz commented
/azp run

2024-11-08 11:55 UTC, jsuarezruiz commented
/rebase

2024-11-11 16:18 UTC, jsuarezruiz commented
/azp run

2025-01-08 18:23 UTC, PureWeen commented
/azp run

2025-01-14 12:56 UTC, jsuarezruiz requested changes

2025-01-14 12:56 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +			if (_bottomView.Background is ColorDrawable background)
This initializes it correctly but If the `TabBarBackgroundColor` property changes at runtime, the color will not be updated, right?

2025-01-15 10:37 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +			if (_bottomView.Background is ColorDrawable background)
@jsuarezruiz  I verified that the TabBarBackgroundColor is updated correctly at runtime.

2025-01-16 10:35 UTC, jsuarezruiz commented
/azp run

2025-01-17 15:07 UTC, mattleibow reviewed
Not sure if this is correct, but why would we only update the background if it is a ColorDrawable and not just overwrite the color?

2025-01-17 15:07 UTC, mattleibow commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +			}
Is there a reason this is just in a `is ColorDrawable`? I there ever a chance that the drawable is something like a gradient or another type of drawable?

If this logic setting the background, should we just be set directly?

```suggestion
			if (ShellContext.Shell.GetAppearanceForPivot(ShellItem) is IShellAppearanceElement appearanceElement)
			{
				var color = appearanceElement.EffectiveTabBarBackgroundColor ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor;
				background.Color = new ColorDrawable(color.ToPlatform());
			}
```

2025-01-21 07:17 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +			}
@mattleibow The reason I initially checked for a ColorDrawable is that the BottomNavigationView's background is of type Drawable, and it is created with a ColorDrawable (typically white) by default. There is no possibility of any other type of drawable being used by default. Therefore, we need ColorDrawable in order to change its color.

2025-01-27 11:10 UTC, jsuarezruiz requested changes

2025-01-27 11:10 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs
> +		public void ShellTabBarBackgroundColor()
The snapshot for Catalyst is pending and available in the latest build. Could you commit the images?

2025-01-28 07:38 UTC, KarthikRajaKalaimani commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs
> +		public void ShellTabBarBackgroundColor()
@jsuarezruiz  I’ve committed the snapshot for Catalyst. Please let me know if you have any further concerns.

2025-01-28 22:40 UTC, PureWeen commented
/azp run

2025-02-03 12:35 UTC, jsuarezruiz commented
/azp run

2025-02-10 08:13 UTC, jsuarezruiz commented
/rebase

2025-02-10 08:16 UTC, jsuarezruiz requested changes

2025-02-10 08:16 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShellTabBarBackgroundColor.png
Requires rebase and update the macOS snapshot to pass the test.

2025-02-13 08:58 UTC, KarthikRajaKalaimani commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShellTabBarBackgroundColor.png
> Requires rebase and update the macOS snapshot to pass the test.

I have rebased the branch.

2025-02-14 22:30 UTC, PureWeen commented
/azp run

2025-02-25 09:43 UTC, jsuarezruiz commented
/rebase

2025-02-26 07:19 UTC, jsuarezruiz commented
/rebase

2025-02-26 07:57 UTC, jsuarezruiz commented
/azp run

2025-02-26 11:34 UTC, jsuarezruiz requested changes

2025-02-26 11:34 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +				if (appearance is IShellAppearanceElement appearanceElement)
Seems that, can combine these two ifs:

```
if (_bottomView.Background is ColorDrawable background 
    && appearance is IShellAppearanceElement appearanceElement)
```

Simplify it a little bit and increase the readability.

2025-02-26 11:34 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +					if (appearanceElement.EffectiveTabBarBackgroundColor is not null)
These if can also be simplified:
```
// Set the background color to the EffectiveTabBarBackgroundColor if it exists, otherwise use the default
background.Color = appearanceElement.EffectiveTabBarBackgroundColor?.ToPlatform()  ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor.ToPlatform();
```

2025-02-28 09:56 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +				if (appearance is IShellAppearanceElement appearanceElement)
> Seems that, can combine these two ifs:
> 
> ```
> if (_bottomView.Background is ColorDrawable background 
>     && appearance is IShellAppearanceElement appearanceElement)
> ```
> 
> Simplify it a little bit and increase the readability.

I have simplified the code as per your suggestion. Could you please review it and let me know if you have any concerns?

2025-02-28 09:56 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +					if (appearanceElement.EffectiveTabBarBackgroundColor is not null)
> These if can also be simplified:
> 
> ```
> // Set the background color to the EffectiveTabBarBackgroundColor if it exists, otherwise use the default
> background.Color = appearanceElement.EffectiveTabBarBackgroundColor?.ToPlatform()  ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor.ToPlatform();
> ```

I have simplified the code as per your suggestion. Could you please review it and let me know if you have any concerns?

2025-02-28 09:56 UTC, KarthikRajaKalaimani commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs
> +			App.WaitForElement("Label");
> Could be nice to change between tabs like in the original issue, but I think have not impact in the snapshot verification, so is ok.

I have modified the test case as per your suggestion. Could you please review it and let me know if you have any concerns?

2025-03-03 10:41 UTC, jsuarezruiz commented
/rebase

2025-03-03 10:43 UTC, jsuarezruiz commented
/azp run

2025-03-04 22:07 UTC, PureWeen requested changes

2025-03-04 22:07 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +			var appearance = ShellContext.Shell.GetAppearanceForPivot(ShellItem);
If I move this code into the `SetAppearance` call of this class it seems to do the same thing

![image](https://github.com/user-attachments/assets/17ed5f70-14f1-481c-8ebe-c4f4a43f30ce)


Can we do that instead of setting the `GetAppearanceForPivot` to internal?

2025-03-05 11:56 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
> +			var appearance = ShellContext.Shell.GetAppearanceForPivot(ShellItem);
> If I move this code into the `SetAppearance` call of this class it seems to do the same thing
> 
> ![image](https://private-user-images.githubusercontent.com/5375137/419209395-17ed5f70-14f1-481c-8ebe-c4f4a43f30ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExNzYwNDksIm5iZiI6MTc0MTE3NTc0OSwicGF0aCI6Ii81Mzc1MTM3LzQxOTIwOTM5NS0xN2VkNWY3MC0xNGYxLTQ4MWMtOGViZS1jNGY0YTQzZjMwY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMDVUMTE1NTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk0OTUzMWNlNGIzZDdhYjgxZGU1MjE4YTVmMTkwMjk4MThjZjcyOWNmZDliNzU2Zjg5NzlhMDc1YzQ3MzBjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F7nGWRDSmPQyUzX91ky6L23v9BV1SbpneVZTbF-WD0s)
> 
> Can we do that instead of setting the `GetAppearanceForPivot` to internal?

Yes It is working in SetAppearance call. I have modified the fix based on your suggestion. Could you please review it and let me know if you have any concerns?

2025-03-19 08:03 UTC, jsuarezruiz requested changes

2025-03-19 08:03 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs
> +		public void ShellTabBarBackgroundColor()
The test is failing on Windows:
`Snapshot different than baseline: ShellTabBarBackgroundColor.png (1.51% difference)`

Note, in red the differences:
![image](https://github.com/user-attachments/assets/e78abed3-49ec-4248-93ce-aef05598bbc8)
Could you take a look?

2025-03-24 06:33 UTC, KarthikRajaKalaimani commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs
> +		public void ShellTabBarBackgroundColor()
> The test is failing on Windows: `Snapshot different than baseline: ShellTabBarBackgroundColor.png (1.51% difference)`
> 
> Note, in red the differences: ![image](https://private-user-images.githubusercontent.com/6755973/424364778-e78abed3-49ec-4248-93ce-aef05598bbc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3OTgwNDksIm5iZiI6MTc0Mjc5Nzc0OSwicGF0aCI6Ii82NzU1OTczLzQyNDM2NDc3OC1lNzhhYmVkMy00OWVjLTQyNDgtOTNjZS1hZWYwNTU5OGJiYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjRUMDYyOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjUxNTlhNTQyNjVlMWNkYmUxMzYxMThmOGFmMmQ5NWUwMDBkMmMxMjIxZjIxYzdjNTRhMjFmMzU0OTAwNWRiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kU0DYKXr5oMPr01yuq2y51WYoCGE_8f7IENF6MuOoqw) Could you take a look?

I have updated the snapshot. Could you please review it and let me know if you have any concerns?

2025-06-09 07:37 UTC, jsuarezruiz commented
@NanthiniMahalingam Could you rebase? Thanks in advance.

2025-06-09 12:18 UTC, closed without merging

2025-06-09 12:18 UTC, NanthiniMahalingam commented
I'm closing this PR in reference to the newly created PR #29833