[iOS] Apply Shell.TitleColor to toolbar items
dotnet/maui pull request #24985
Opened 2024-09-28 18:42 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24984

|Before|After|
|--|--|
|<video src="" width="300px"/>|<video src="" width="300px"/>|

2024-09-30 10:39 UTC, jfversluis commented
/azp run

2024-10-01 16:03 UTC, PureWeen commented
/azp run

2024-10-03 17:03 UTC, PureWeen requested changes
I'm rerunning the tests on this one but there are a good amount of crashes on the iOS test runs that seem like they might be related to this PR

2024-10-05 00:30 UTC, kubaflo commented
@PureWeen It should work now

2024-10-30 15:17 UTC, PureWeen requested changes
Merge conflict

2024-11-06 09:31 UTC, jsuarezruiz commented
/azp run

2024-11-12 09:46 UTC, jsuarezruiz commented
/rebase

2024-11-12 09:47 UTC, jsuarezruiz commented
/azp run

2024-11-13 12:03 UTC, jsuarezruiz submitted a review, later dismissed

2024-11-13 12:03 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarItemsShouldBeVisible.png
The test is failing because the snapshot does not have the correct resolution, can you update it?

```
VisualTestUtils.VisualTestFailedException :
Snapshot different than baseline: ToolbarItemsShouldBeVisible.png (size differs - baseline is 1124x2326 pixels, actual is 1124x2286 pixels)
```

2024-11-14 11:59 UTC, jsuarezruiz commented
/azp run

2024-11-27 03:52 UTC, PureWeen requested changes

2024-11-27 03:52 UTC, PureWeen commented on src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
> +~Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.OnAppearanceChanged(Microsoft.Maui.Controls.ShellAppearance appearance) -> void
We can't change the public API

2025-01-29 17:07 UTC, PureWeen requested changes
Fix merge conflicts

2025-01-29 19:17 UTC, kubaflo commented
Done

2025-01-29 20:44 UTC, PureWeen commented
/azp run

2025-01-29 21:13 UTC, PureWeen requested changes
This one will need new screenshots uploaded once CI has finished

2025-01-30 17:20 UTC, kubaflo commented
@PureWeen I've added snapshots

2025-02-04 14:57 UTC, PureWeen commented
/rebase

2025-02-07 19:56 UTC, PureWeen commented
/azp run

2025-02-13 10:27 UTC, StephaneDelcroix approved these changes, later dismissed

2025-02-13 13:07 UTC, PureWeen requested changes

2025-02-13 13:07 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24878.cs
> -﻿#if ANDROID || WINDOWS
The snap shot on windows for this one seems wrong

It still has a white background

I think we should leave FAILS_ON_WINDOWS here and delete the windows snapshot

2025-02-13 15:25 UTC, PureWeen commented
/azp run

2025-02-13 15:26 UTC, PureWeen approved these changes

2025-02-14 22:06 UTC, PureWeen requested changes
I think you'll need to update the mac images based on our updated snap shot code

2025-02-16 13:10 UTC, kubaflo commented
@PureWeen done

2025-02-18 21:29 UTC, PureWeen commented
/azp run

2025-02-18 21:31 UTC, PureWeen commented
> @PureWeen done

thoughts on why catalyst has a white background vs iOS?

2025-02-19 00:03 UTC, kubaflo commented
> > @PureWeen done
> 
> thoughts on why catalyst has a white background vs iOS?
I don't know, especially when it works locally
![Screenshot 2025-02-19 at 01 03 04](https://github.com/user-attachments/assets/66106008-f28d-4a99-9a47-4ae57ac23e25)

2025-02-19 18:10 UTC, PureWeen commented
/azp run

2025-02-20 15:51 UTC, PureWeen submitted a review, later dismissed

2025-02-20 15:53 UTC, PureWeen commented
/azp run

2025-03-03 14:42 UTC, jsuarezruiz requested changes, later dismissed

2025-03-03 14:42 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24878.cs
>  	public void ToolbarItemsShouldBeVisible()
The test is failing on Android, iOS and Catalyst:

Example:
![image](https://github.com/user-attachments/assets/959ba0e2-af7a-439c-abb2-a524803dec3a)
Related with dark/light theme.

2025-03-03 15:18 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24878.cs
>  	public void ToolbarItemsShouldBeVisible()
Updated. Could you please /azp?

2025-03-04 12:48 UTC, jsuarezruiz commented
/rebase

2025-03-04 12:49 UTC, jsuarezruiz commented
/azp run

2025-03-12 12:11 UTC, mattleibow requested changes
Code looks good. The only nit I have is that the test only shows the end state, so maybe some bug set it before the theme changed. For example, due to some error, it defaults to while text.

2025-03-12 12:11 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24878.cs
>  		VerifyScreenshot();
Is it possible to add a screenshot before and after?

```suggestion
		App.WaitForElement("button");
		VerifyScreenshot("ToolbarItemsShouldBeVisible_Before");

		App.Click("button");

		App.WaitForElement("label");
		VerifyScreenshot("ToolbarItemsShouldBeVisible_After");
```

This way we can see what it would look like before the change and ensure that it did actually chnage.

2025-03-12 12:16 UTC, mattleibow commented
merged the code, let me re-gen the screenshots.

2025-03-12 12:17 UTC, mattleibow commented
/azp run MAUI-UITests-public

2025-03-12 13:03 UTC, mattleibow commented
I am not one for asking people to make PRs bigger, but this is so much overlap with #25102 that I wonder if it is best. We are touching the same test app, tests and images. The actual fix is small enough that it might be worth merging the two.

I like the extra addition of the icon on the Android PR.

2025-03-12 13:05 UTC, mattleibow requested changes
I am voting to merge with #25102

2025-03-12 13:08 UTC, mattleibow submitted a review, later dismissed
Actually, going to approve as it does not matter if the PRs are separate or merged, they all get merged at the end. All depends on if @kubaflo reads the option to merge and merges the PRs before the CI is green :)

If it is close and just needs reties, no need to worry - but the toolbar item icon as part of the test to make sure the color sticks there too is probably better here in iOS rather than fixing iOS in a separate PR if it does not work.

2025-03-17 12:51 UTC, rmarinho requested changes
Tests are failing ToolbarItemsShouldBeVisible

2025-03-17 14:00 UTC, rmarinho commented
/azp run

2025-03-17 14:00 UTC, rmarinho approved these changes

2025-03-17 18:59 UTC, rmarinho requested changes
We need to figure how to make sure we remove the observer so it doesn't t cause the pages to leak

2025-03-17 18:59 UTC, rmarinho commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
> +				shellController.RemoveAppearanceObserver(this);
I think this is not being disposed correctly and makes this test fail. 

https://dev.azure.com/xamarin/public/_build/results?buildId=138020&view=ms.vss-test-web.build-test-results-tab&runId=3911888&resultId=100461&paneView=debug

2025-03-17 19:07 UTC, kubaflo commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
> +				shellController.RemoveAppearanceObserver(this);
I can't open this link, but I think I got it. Could you please /azp again?

2025-03-18 15:12 UTC, rmarinho commented
/azp run

2026-03-01 23:35 UTC, closed without merging