[Android] Custom back button image color
dotnet/maui pull request #24993
Opened 2024-09-29 18:51 UTC by kubaflo

### Description
Now it works even when users change their theme in the runtime

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/17228
Fixes https://github.com/dotnet/maui/issues/24857

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/be1cf31d-dd55-4e87-ae08-a7e9545c864c" width="300px"/>|<video src="https://github.com/user-attachments/assets/5c17b588-b120-4335-841c-c54de3a5992d" width="300px"/>|

2024-10-03 09:07 UTC, rmarinho commented
/azp run

2024-10-03 21:25 UTC, PureWeen requested changes
Images are ready!

2024-10-03 22:59 UTC, kubaflo commented
@PureWeen done

2024-10-04 07:42 UTC, jsuarezruiz commented
/azp run

2024-10-09 22:25 UTC, PureWeen commented
/azp run

2024-10-23 09:38 UTC, jsuarezruiz commented
/azp run

2024-11-12 14:51 UTC, jsuarezruiz commented
/rebase

2024-11-13 11:31 UTC, jsuarezruiz commented
/azp run

2024-11-15 10:55 UTC, jsuarezruiz approved these changes

2025-04-22 22:31 UTC, merged