Fix deprecated API usage for embedded fonts on iOS/Catalyst 18.0+
dotnet/maui pull request #25025
Opened 2024-10-01 12:33 UTC by drasticactions

### Description of Change

`CTFontManager.RegisterGraphicsFont` throws a [deprecation warning](https://developer.apple.com/documentation/coretext/1499499-ctfontmanagerregistergraphicsfon) for iOS 18+. This was breaking my build.

https://github.com/xamarin/xamarin-macios/blob/main/src/CoreText/CTFontManager.cs#L445-L462

This PR attempts to change it to a supported API for these platforms, using `CTFontManager.RegisterFontsForUrl`. To do this, I believe, we need to write the font to a file on disk (in this case, in temp storage in the users application cache) and then register it.

2024-10-01 12:55 UTC, rmarinho commented on src/Core/src/Fonts/EmbeddedFontLoader.iOS.cs
> +			if (font.ResourceStream == null)
can we use is null ? and drop the private from the methods

2024-10-01 12:56 UTC, rmarinho commented
I think this should target to net9 when we merge the #25017

2024-10-02 16:29 UTC, PureWeen commented
/rebase

2024-10-02 16:41 UTC, rmarinho commented
Net9 is on iOS18 XCODE16 can we target that branch ?

2024-10-02 16:46 UTC, PureWeen commented
> Net9 is on iOS18 XCODE16 can we target that branch ?

I think this is fine for main so that if anyone is on XCODE 16 locally they are still able to compile main until we merge net9.0 into main

2024-10-03 14:22 UTC, PureWeen requested changes
Don't merge until 
https://github.com/dotnet/maui/pull/25055

is green and merged

2024-10-04 21:48 UTC, PureWeen commented
Because we merged
https://github.com/dotnet/maui/pull/25092 to fix the compile error on main

I'm going to close this PR in favor of
https://github.com/dotnet/maui/pull/25055

2024-10-04 21:48 UTC, closed without merging