[Winodws] Fixed TextCell Command executes only once
dotnet/maui pull request #25066
Opened 2024-10-03 07:28 UTC by Vignesh-SF3580

### Root Cause
While fixing a memory leak in ListView, the Cell's parent was set to null in the Unloaded event. This caused the TextCell's parent to be set to null during initial navigation, preventing commands from executing afterward.

### Description of Change
The fix ensures that the parent is set to null only when the parent control is a ListView. This preserves the memory leak fix while also resolving the issue with command execution in TextCell.

### Tested the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed
 
Fixes https://github.com/dotnet/maui/issues/21112
Fixes https://github.com/dotnet/maui/issues/16254

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/85b27388-50e9-4716-9bfc-52ca4e598527"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/a0284a84-fa04-43cc-acd8-d683f58d3362">) |

2024-10-04 07:32 UTC, jsuarezruiz commented
/azp run

2024-10-07 13:16 UTC, jsuarezruiz commented
/azp run

2024-10-09 12:12 UTC, jsuarezruiz commented
/azp run

2024-10-09 13:44 UTC, Vignesh-SF3580 commented
/rebase

2024-10-09 15:35 UTC, PureWeen commented
/azp run

2024-10-14 08:00 UTC, Vignesh-SF3580 commented
/rebase

2024-10-21 15:08 UTC, PureWeen commented
/azp run

2024-10-23 07:46 UTC, jsuarezruiz commented
/azp run

2024-10-25 00:49 UTC, PureWeen commented
/rebase

2024-10-25 00:52 UTC, PureWeen commented
/azp run

2024-10-25 09:39 UTC, Vignesh-SF3580 commented
/rebase

2024-10-25 09:45 UTC, jsuarezruiz requested changes

2024-10-25 10:30 UTC, Vignesh-SF3580 commented on src/Controls/tests/TestCases.HostApp/Issues/Issue21112.cs
> +	public class MainViewModel
I've updated the code based on your feedback. Could you please review it and let me know if there are any further concerns

2024-10-25 15:41 UTC, jsuarezruiz commented
/azp run

2024-10-29 12:48 UTC, jsuarezruiz approved these changes

2024-10-30 14:38 UTC, merged