Move TitleViewSetOnShellWorksAfterNavigation to Appium
dotnet/maui pull request #25094
Opened 2024-10-04 19:58 UTC by PureWeen

2024-10-05 11:46 UTC, rmarinho requested changes
The test is failing

2024-10-07 11:04 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12888.cs
> +		public void TitleViewSetOnShellWorksAfterNavigation()
Fails on Catalyst and iOS:

```
System.TimeoutException : Timed out waiting for element...

at UITest.Appium.HelperExtensions.Wait(Func`1 query, Func`2 satisfactory, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 1050
   at UITest.Appium.HelperExtensions.WaitForAtLeastOne(Func`1 query, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 1065
   at UITest.Appium.HelperExtensions.WaitForElement(IApp app, String marked, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency, Nullable`1 postTimeout) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 371
   at Microsoft.Maui.TestCases.Tests.Issues.Issue12888.TitleViewSetOnShellWorksAfterNavigation() in /_/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12888.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

2024-10-08 22:02 UTC, PureWeen commented
/azp run

2024-10-09 11:20 UTC, merged

2024-10-20 13:52 UTC, PureWeen commented
/backport to release/9.0.1xx