[Windows] Fix for the issue with Label text color when resetting from FormattedText.
dotnet/maui pull request #25119
Opened 2024-10-07 13:11 UTC by Tamilarasan-Paranthaman

### Root Cause of the issue 

When changing the label text to FormattedText with text color, and then switching back to normal text, the text retains the formatted text color. This is due to the TextHighlighter applied in the UpdateInlines method of FormattedStringExtensions, which is not cleared when reverting to normal text.

### Description of Change
 
I cleared the TextHighlighter in the propertyChanging method of the Formatted Text when the Old value is not null for Windows in the Label class, and it works fine.

### Issues Fixed

Fixes #24516

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/5d808f3f-1a78-42e2-a03d-94617ae7ed43"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/99f27829-4530-4cba-bc44-cdc6cb4294ad"> |

2024-10-08 06:17 UTC, jsuarezruiz commented
/azp run

2024-10-08 13:11 UTC, jsuarezruiz commented
/azp run

2024-10-08 20:08 UTC, PureWeen commented
/rebase

2024-10-09 12:13 UTC, jsuarezruiz commented
/azp run

2024-10-10 13:42 UTC, Tamilarasan-Paranthaman commented
/rebase

2024-10-10 16:03 UTC, PureWeen requested changes

2024-10-11 06:46 UTC, Tamilarasan-Paranthaman commented on src/Controls/src/Core/Label/Label.cs
> +					(label.Handler as LabelHandler)?.PlatformView?.TextHighlighters?.Clear();
I have moved the fix into the TextBlockExtensions and ensured that the issue is resolved. Please review it and share if you have any concerns.

2024-10-11 11:28 UTC, jsuarezruiz commented
/azp run

2024-10-15 16:47 UTC, Foda approved these changes

2024-10-15 16:50 UTC, PureWeen approved these changes

2024-10-15 19:16 UTC, merged