Entry Height gets updated when loaded inside the RoundRectangle Shape
dotnet/maui pull request #25166
Opened 2024-10-10 06:08 UTC by SuthiYuvaraj

### RootCause

Height for RoundRectangle is calculated and height is increased everytime for every measure. So for every input event in entry control, round rectangle is measured and height is updated. 
 
This issue may be break due to below PR:
[Rendering Shapes without explicit bounds. by VSadov · Pull Request #5817 · dotnet/maui (github.com)](https://github.com/dotnet/maui/pull/5817)
[Fixed Android RoundRectangle border logic by jstedfast · Pull Request #17087 · dotnet/maui (github.com)](https://github.com/dotnet/maui/pull/17087)
While reverting change in above PR, current fix is fixed and issue mentioned above PR replicates.

### Description of Change

 Declared boolean property in Shape.cs. Added if condition checking stroke thickness has already added to Height. So that height value for round rectangle does not increase for every measure. Also added property changed for Stroke thickness.

### Issues Fixed
Fixes #18092 

Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
###Output Screenshots
Before Issue Fix | After Issue Fix |
|----------|----------|
|<video width="300" height="600" alt="Before Fix video" src="https://github.com/user-attachments/assets/071fcbf0-e2be-4ba8-bb37-95efbaf845c2">|<video width="300" height="600" alt="After Fix video" src="https://github.com/user-attachments/assets/baf7f58b-941b-45a3-8100-1e1053301fd9">|

2024-10-11 11:29 UTC, jsuarezruiz commented
/azp run

2024-10-23 09:34 UTC, jsuarezruiz commented
/rebase

2024-10-23 09:35 UTC, jsuarezruiz commented
/azp run

2024-10-25 00:54 UTC, PureWeen commented
/rebase

2024-10-25 10:14 UTC, jsuarezruiz commented
/azp run

2025-02-04 12:13 UTC, jsuarezruiz approved these changes

2025-02-04 16:21 UTC, jsuarezruiz commented on src/Controls/src/Core/Shapes/Shape.cs
> +			// Get the inner path by subtracting the stroke thickness for a rounded rectangle, as the GetPath() method returns the path including the stroke thickness.
A better approach would be to align the behavior between the RoundRectangle and the rest of the shapes.

2025-02-04 16:25 UTC, PureWeen requested changes
https://github.com/dotnet/maui/pull/25166#discussion_r1941497567

2025-02-04 16:33 UTC, jsuarezruiz requested changes
Could we align the behavior between all the shapes? https://github.com/dotnet/maui/pull/25166#discussion_r1941497567

2025-02-05 12:47 UTC, SuthiYuvaraj commented on src/Controls/src/Core/Shapes/Shape.cs
> +			// Get the inner path by subtracting the stroke thickness for a rounded rectangle, as the GetPath() method returns the path including the stroke thickness.
@jsuarezruiz  @PureWeen, The issue occurs specifically with RoundRectangle because its [GetPath()](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Shapes/RoundRectangle.cs#L56) method does not exclude StrokeThickness from width and height calculations. In contrast, other shapes like Rectangle and Ellipse already account for StrokeThickness in their [GetPath()](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Shapes/Rectangle.cs#L49) implementations.
 
For example, in Rectangle.cs, GetPath() subtracts StrokeThickness from both width and height before creating the path. However, in RoundRectangle.cs, GetPath() directly uses the full width and height without adjusting for StrokeThickness.
 
As a result, each MeasureOverride() call includes StrokeThickness in the size calculation, causing the height to increase on every input event for RoundRectangle. To align behavior across all shapes, I have updated the RoundRectangle implementation to exclude StrokeThickness from GetInnerPath(), ensuring consistency with Rectangle.cs.

2025-02-12 07:40 UTC, sheiksyedm commented
> Could we align the behavior between all the shapes? [#25166 (comment)](https://github.com/dotnet/maui/pull/25166#discussion_r1941497567)

reply : https://github.com/dotnet/maui/pull/25166#discussion_r1942875473

2025-02-13 13:32 UTC, PureWeen commented on src/Controls/src/Core/Shapes/Shape.cs
> +			// Get the inner path by subtracting the stroke thickness for a rounded rectangle, as the GetPath() method returns the path including the stroke thickness.
What would happen if we just aligned the `GetPath` method of RoundRectangle to work like the `GetPath` of `Rectangle` and `Ellipse`?

The worry here is that we're creating an extra method that's purely for a special case scenario

2025-02-14 11:41 UTC, SuthiYuvaraj commented on src/Controls/src/Core/Shapes/Shape.cs
> +			// Get the inner path by subtracting the stroke thickness for a rounded rectangle, as the GetPath() method returns the path including the stroke thickness.
@PureWeen  The GetPath method of RoundRectangle was intentionally modified in a previous [PR](https://github.com/dotnet/maui/pull/17087) to remove any compensation for StrokeThickness, as the calling code now handles that separately. The PR description explicitly states that GetPath should use the width and height as-is, without adjustments for StrokeThickness.
To maintain consistency with the updated approach while still resolving the issue, I have applied the fix within GetInnerPath. This ensures that the behavior aligns with other shapes without altering GetPath, which has already been adjusted for a broader set of changes.

2025-02-26 07:19 UTC, jsuarezruiz commented
/rebase

2025-02-26 07:52 UTC, jsuarezruiz commented
/azp run

2025-06-09 07:38 UTC, jsuarezruiz commented
@SuthiYuvaraj Could you rebase? Thanks in advance.

2025-06-13 11:17 UTC, jsuarezruiz commented
/azp run

2025-07-15 12:11 UTC, jsuarezruiz commented
/rebase

2025-07-15 12:14 UTC, jsuarezruiz commented
/azp run

2025-12-03 16:59 UTC, StephaneDelcroix approved these changes

2025-12-03 17:00 UTC, merged