Added a null check for setting BarBackgroundColor for a NavigationPage
dotnet/maui pull request #25197
Opened 2024-10-11 09:45 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25114#issuecomment-2405726909
Code from this repo https://github.com/markmccaigue/MAUI8090BarBackgroundColorCrash/tree/main

|iOS|Android|
|--|--|
|<video src="https://github.com/user-attachments/assets/44b3376e-752e-4e4a-a91b-8bb7062c93eb" width="300px"/>|<video src="https://github.com/user-attachments/assets/17fcb331-c685-4a21-8d98-6c65fb077514" width="300px"/>|

2024-10-11 13:46 UTC, Redth submitted a review, later dismissed

2024-10-11 13:46 UTC, Redth commented
/azp run

2024-10-11 14:28 UTC, jsuarezruiz submitted a review, later dismissed

2024-10-11 17:14 UTC, PureWeen requested changes
Let's add UITest if we can 

Also, I'm curious why the code path is reaching here in the first place when it didn't used to

2024-10-14 15:21 UTC, PureWeen requested changes

2024-10-14 15:21 UTC, PureWeen commented on src/Controls/tests/TestCases.HostApp/Issues/Issue25114.xaml.cs
> +namespace Maui.Controls.Sample.Issues;
Can you remove the ".xaml." extension from this file?

2024-10-14 16:16 UTC, PureWeen commented
/azp run

2024-10-14 16:27 UTC, PureWeen commented
/backport to 8.0.1xx-sr9

2024-10-14 17:28 UTC, PureWeen approved these changes

2024-10-15 14:52 UTC, merged