Make Style nullable
dotnet/maui pull request #25230
Opened 2024-10-13 01:33 UTC by pictos

### Description of Change

Add the `?` symbol to the `Style` property of controls.

### Issues Fixed

Fixes #25227

2024-10-14 06:24 UTC, jsuarezruiz commented
/azp run

2024-10-14 07:07 UTC, jsuarezruiz requested changes, later dismissed

2024-10-14 07:07 UTC, jsuarezruiz commented on src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
> +Microsoft.Maui.Controls.StyleableElement.Style.get -> Microsoft.Maui.Controls.Style?
This change un PublicAPIs is pending in Tizen:

```
D:\a\_work\1\s\src\Controls\src\Core\StyleableElement\StyleableElement.cs(25,4): error RS0016: Symbol 'Style.get' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net9.0-tizen7.0]
D:\a\_work\1\s\src\Controls\src\Core\PublicAPI\net-tizen\PublicAPI.Unshipped.txt(86,1): error RS0017: Symbol 'Microsoft.Maui.Controls.StyleableElement.Style.get -> Microsoft.Maui.Controls.Style!' is part of the declared API, but is either not public or could not be found (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net9.0-tizen7.0]
    22 Warning(s)
    2 Error(s)
```

2024-10-14 07:26 UTC, StephaneDelcroix commented
it feels weird that among all the properties we have, not attributed as nullable, that Style is the only one to fail.

2024-12-05 11:57 UTC, mattleibow commented
I figured it out. We forgot to add the `#nullable disable` when we moved the style code into the new `StyleableElement`.

2024-12-05 11:57 UTC, mattleibow commented
/rebase

2024-12-05 11:58 UTC, mattleibow approved these changes

2024-12-05 12:01 UTC, mattleibow approved these changes

2024-12-05 12:01 UTC, mattleibow commented
/azp run

2024-12-05 12:02 UTC, mattleibow approved these changes, later dismissed

2024-12-05 16:53 UTC, mattleibow commented
/azp run

2024-12-06 22:42 UTC, PureWeen requested changes, later dismissed
/Users/builder/azdo/_work/3/s/src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt(88,1): error RS0017: Symbol 'Microsoft.Maui.Controls.StyleableElement.Style.get -> Microsoft.Maui.Controls.Style!' is part of the declared API, but is either not public or could not be found (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [/Users/builder/azdo/_work/3/s/src/Controls/src/Core/Controls.Core.csproj::TargetFramework=net9.0-tizen7.0]

2024-12-07 07:41 UTC, pictos commented
@PureWeen I removed that entry, not sure if I understood how that API file is written, but I believe when there's a `!` at the end, it indicates that value is not nullable, so I remove that line, since there's the same symbol declared there, but it's nullable

2024-12-09 19:18 UTC, jfversluis submitted a review, later dismissed

2024-12-11 09:16 UTC, jfversluis commented
/rebase

2024-12-12 09:13 UTC, jfversluis approved these changes

2024-12-12 09:14 UTC, merged