Fix for picker on hidden page opens after back navigation in Android
dotnet/maui pull request #25319
Opened 2024-10-16 10:38 UTC by BagavathiPerumal

### Root cause

The root cause of the issue is that the picker on MainPage unexpectedly opens the Picker dialog popup in FirstPage when navigating back, even though MainPage is not currently visible. This occurs because the Picker's focus changes during navigation back to FirstPage using Navigation.PopModalAsync(), triggering a click operation on the Picker, which opens the dialog regardless of MainPage's visibility.

### Description of Issue Fix

The fix involves removing the auto-open behavior on focus from the Pickers by eliminating the FocusChanged event, which handled the Picker's OnClick operation when focus changed. This adjustment prevents the Picker dialog from opening during page navigation. 

Specifically, when the Picker gains focus, the previous implementation would trigger PlatformView.CallOnClick() or OnClick(PlatformView, EventArgs.Empty), leading to the unwanted dialog popup. Additionally, the FocusableInTouchMode property is set to false to ensure that the Pickers do not gain focus unexpectedly.

Tested the behavior in the following platforms.
 
- [x] Windows
- [x] Mac
- [x] iOS
- [x] Android

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24862

### Reference

Removed the FocusChanged event to ensure Pickers on Android only pop up when tapped or the Enter key is pressed, instead of opening the picker popup when the focus changes during page navigation, based on the PR mentioned below as a reference.

https://github.com/dotnet/maui/pull/8913

### Output

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/635487c2-921f-4c21-9358-e6588e468e11"> | <video width="270" height="600"  src="https://github.com/user-attachments/assets/fd6fc03b-61a4-4e5c-aee2-6e0ba8237f7a"> |

2024-10-16 13:58 UTC, jsuarezruiz commented
/azp run

2024-10-22 13:15 UTC, jsuarezruiz commented
/azp run

2024-10-24 16:38 UTC, PureWeen commented
/rebase

2024-10-24 17:06 UTC, PureWeen requested changes
Unfortunately, I don't think we'll be able to take this PR as is. 

I wish on the PR you referenced we would have also applied this logic to `Picker` but since we didn't, this isn't really a behavior we can change right now especially if there isn't a replace API to open the picker from code. 

My current thought here is

1) We can keep this code how it currently is
2) We try to add code so that if the user calls "Focus" directly then we have that trigger the opening of the picker.

2024-10-28 06:52 UTC, BagavathiPerumal commented
> Unfortunately, I don't think we'll be able to take this PR as is.
> 
> I wish on the PR you referenced we would have also applied this logic to `Picker` but since we didn't, this isn't really a behavior we can change right now especially if there isn't a replace API to open the picker from code.
> 
> My current thought here is
> 
> 1. We can keep this code how it currently is
> 2. We try to add code so that if the user calls "Focus" directly then we have that trigger the opening of the picker.

@PureWeen, Thank you for the feedback. I understand the limitations here. I'll keep the current code as is and look into alternative solutions for this issue.

2024-11-06 12:31 UTC, jsuarezruiz commented
/rebase

2024-11-26 12:52 UTC, jsuarezruiz commented
/rebase

2025-03-25 06:58 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:24 UTC, jsuarezruiz commented
/azp run

2025-03-27 08:07 UTC, jsuarezruiz requested changes
The build is failing:

```
C:\a\_work\1\s\src\Controls\samples\Controls.Sample\Pages\UserInterface\VisualStatesPage.xaml(56,34): XamlC warning XC0022: Binding could be compiled to improve runtime performance if x:DataType is specified. See https://learn.microsoft.com/dotnet/maui/fundamentals/data-binding/compiled-bindings for more information. [C:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-windows10.0.20348.0]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(12,15): error CS0101: The namespace 'Maui.Controls.Sample.Issues' already contains a definition for 'MainPage' [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-maccatalyst]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(14,10): error CS0111: Type 'MainPage' already defines a member called 'MainPage' with the same parameter types [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-maccatalyst]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(12,15): error CS0101: The namespace 'Maui.Controls.Sample.Issues' already contains a definition for 'MainPage' [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-ios]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(14,10): error CS0111: Type 'MainPage' already defines a member called 'MainPage' with the same parameter types [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-ios]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(12,15): error CS0101: The namespace 'Maui.Controls.Sample.Issues' already contains a definition for 'MainPage' [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-tizen]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(14,10): error CS0111: Type 'MainPage' already defines a member called 'MainPage' with the same parameter types [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-tizen]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(12,15): error CS0101: The namespace 'Maui.Controls.Sample.Issues' already contains a definition for 'MainPage' [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-android]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(14,10): error CS0111: Type 'MainPage' already defines a member called 'MainPage' with the same parameter types [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-android]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(12,15): error CS0101: The namespace 'Maui.Controls.Sample.Issues' already contains a definition for 'MainPage' [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-windows10.0.20348.0]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(14,10): error CS0111: Type 'MainPage' already defines a member called 'MainPage' with the same parameter types [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-windows10.0.20348.0]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(12,15): error CS0101: The namespace 'Maui.Controls.Sample.Issues' already contains a definition for 'MainPage' [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-windows10.0.19041.0]
C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Issues\Issue24862.cs(14,10): error CS0111: Type 'MainPage' already defines a member called 'MainPage' with the same parameter types [C:\a\_work\1\s\src\Controls\tests\TestCases.HostApp\Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-windows10.0.19041.0]
    12 Error(s)
```

2025-03-27 08:07 UTC, jsuarezruiz requested changes

2025-03-27 08:07 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.HostApp/Issues/Issue24862.cs
> +	public class MainPage : ContentPage
Rename to something like `Issue24862MainPage`.

2025-06-14 15:04 UTC, PureWeen commented
Closing in favor of https://github.com/dotnet/maui/pull/29068

2025-06-14 15:04 UTC, closed without merging