Fixed [Windows] TapGestureRecognizer not working on Entry
dotnet/maui pull request #25311
Opened 2024-10-16 09:58 UTC by NirmalKumarYuvaraj

### Root Cause:
The Tapped and DoubleTapped events on _container (a FrameworkElement) is not firing when interacting with the Entry. As a result, the TapGestureRecognizer for the Entry is not being triggered.

### Description of Change:
I resolved the issue by modifying the event subscription for the Tapped and DoubleTapped events on the _container (a FrameworkElement). Instead of directly subscribing to the Tapped and DoubleTapped event, I used the AddHandler method, which ensures that handled events are still caught. This fix allows the Tapped and DoubleTapped event to be triggered even when interacting with the Entry control, allowing the TapGestureRecognizer to work as expected.

**Tested the behaviour in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Reference
N/A

### Issues Fixed
Fixes #12213

### Screenshots
**Before**
![Before](https://github.com/user-attachments/assets/9ba4ec4f-3229-4e6a-aef5-9ff19e858071)

**After**
![After](https://github.com/user-attachments/assets/0fe9af6b-a249-4602-88f6-2e88f2ec57a6)

2024-10-16 10:20 UTC, jsuarezruiz commented
/azp run

2024-10-17 10:00 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
> +					_container.RemoveHandler(FrameworkElement.TappedEvent, new TappedEventHandler(OnTap));
@MartyIX  Yes, your concern is valid. The `new` keyword creates a new instance of the `TappedEventHandler`, which is not the same instance as the one that was originally added. Therefore, using `new` in this context will not effectively remove the previously added handler. To properly remove an event handler, I reference the same instance of the handler that i used when adding it. Please check and let me know if you have any further concerns.

2024-10-17 10:31 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
> +					_container.RemoveHandler(FrameworkElement.TappedEvent, _tappedEventHandler);
I have nullified the event handlers as suggested. Please review and let me know if you have any further concerns.

2024-10-17 10:32 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
> +					_container.RemoveHandler(FrameworkElement.DoubleTappedEvent, _doubleTappedEventHandler);
I have nullified the event handlers as suggested. Please review and let me know if you have any further concerns.

2024-10-22 13:13 UTC, jsuarezruiz commented
/azp run

2024-10-22 21:56 UTC, PureWeen requested changes, later dismissed
https://github.com/dotnet/maui/pull/25311#discussion_r1810719569

2024-10-24 05:11 UTC, NirmalKumarYuvaraj commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12213.cs
> +		[FailsOnMac]
Failing on Catalyst because the VerifyScreenshot method is not implemented on macOS. Now the reason has been mentioned for clarity.

2024-10-25 09:48 UTC, jsuarezruiz commented
/azp run

2024-10-29 14:29 UTC, jsuarezruiz approved these changes

2024-10-30 14:39 UTC, PureWeen commented
@Foda can you review please?

2024-11-07 17:22 UTC, Foda approved these changes

2024-11-11 18:18 UTC, merged