Fix SafeArea adjustments
dotnet/maui pull request #25315
Opened 2024-10-16 10:14 UTC by kubaflo

### Description of Change

Added `ContentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentBehavior.Never;` to changes in this PR: https://github.com/dotnet/maui/pull/23729

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25266
Fixes https://github.com/dotnet/maui/issues/24246

2024-10-16 10:14 UTC, jsuarezruiz commented
/azp run

2024-11-12 09:54 UTC, jsuarezruiz commented
/rebase

2024-11-12 09:57 UTC, jsuarezruiz commented
/azp run

2024-11-14 12:25 UTC, jsuarezruiz requested changes
Could you update the Issue24246 class to fix the build errors?

2024-11-14 12:25 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24246.cs
> +	}
```
Build FAILED.

/Users/builder/azdo/_work/1/s/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24246.cs(25,3): error CS1513: } expected [/Users/builder/azdo/_work/1/s/src/Controls/tests/TestCases.Android.Tests/Controls.TestCases.Android.Tests.csproj]

```

2024-11-14 18:30 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24246.cs
> +	}
Sure, sorry about that 😅

2024-11-14 18:37 UTC, rmarinho commented
/azp run MAUI-public

2024-11-14 18:40 UTC, rmarinho commented
/azp run MAUI-UITests-public

2024-12-18 14:39 UTC, rmarinho commented
/rebase

2024-12-18 14:40 UTC, rmarinho commented
/azp run

2025-01-09 23:36 UTC, kubaflo commented
Closed in favor of https://github.com/dotnet/maui/pull/27043

2025-01-09 23:36 UTC, closed without merging