Update Window.cs
dotnet/maui pull request #25338
Opened 2024-10-17 07:37 UTC by jfversluis

### Description of Change

Trying to fix the empty title bar in Blazor Hybrid templates by updating the `Title` property in the `Window.cs` file. I don't think there is any reason to cast it specifically to `Shell` as each `Page` could have a title.

### Issues Fixed

Fixes #25337

2024-10-17 18:56 UTC, PureWeen requested changes
I don't think we want to do this

The guidance has typically just been to set it on the window yourself

2024-10-17 18:59 UTC, jfversluis commented
@PureWeen OK so why do we do it for Shell and not the rest? Because Shell is just the singular thing that people will have? 

You can still set the Window one and that will take precedence?

Just thinking about the File > New experience I guess, now we need one other place where I need to scrub the default template values to make the title show up nicely?

I don't have a strong opinion either way. @Eilon?

2024-10-18 17:14 UTC, PureWeen commented
> @PureWeen OK so why do we do it for Shell and not the rest? Because Shell is just the singular thing that people will have?
> 
> You can still set the Window one and that will take precedence?
> 
> Just thinking about the File > New experience I guess, now we need one other place where I need to scrub the default template values to make the title show up nicely?
> 
> I don't have a strong opinion either way. @Eilon?

Shell == Window

It's your entire window context

Shell basically represented Window in XF before we had the concept of a Window.

If we want Blazor to have a Window title it should go here
https://github.com/dotnet/maui/blob/net9.0/src/Templates/src/templates/maui-blazor/App.xaml.cs#L10-L13

2024-10-18 17:31 UTC, Eilon commented
So like this? https://github.com/dotnet/maui/pull/25387

2024-10-21 18:03 UTC, Eilon commented
@PureWeen / @jfversluis - so I guess we can close this if it's considered just a legacy behavior?

2024-10-25 23:48 UTC, closed without merging