[Testing] Refactor ported Xamarin.UITest tests
dotnet/maui pull request #25350
Opened 2024-10-17 11:14 UTC by jsuarezruiz

### Description of Change

We recently moved (as disabled) Xamarin.UITests tests from Control Gallery to Appium https://github.com/dotnet/maui/pull/25024.

When re-enabling them, the tests use `RunningApp` property that does not exist. This PR apply changes to avoid that issue using the correct `App` property.

2024-10-22 21:16 UTC, PureWeen requested changes
rebase

2024-10-23 09:18 UTC, jsuarezruiz commented
/azp run

2024-10-31 13:01 UTC, jfversluis commented
/rebase

2024-10-31 13:22 UTC, jfversluis commented
Looks like these changes were already merged as part of another PR!

2024-10-31 13:22 UTC, closed without merging