[Testing] Enabling ported UITests from Xamarin.UITests to Appium #2
dotnet/maui pull request #25378
Opened 2024-10-18 11:35 UTC by jsuarezruiz

### Description of Change

Continuation of https://github.com/dotnet/maui/pull/25178 This is the second group of tests enabled.

2024-10-23 09:18 UTC, jsuarezruiz commented
/azp run

2024-10-24 16:45 UTC, PureWeen requested changes, later dismissed

2024-10-24 16:45 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25943.cs
> +		[FailsOnMacWhenRunningOnXamarinUITestWhenRunningOnXamarinUITestWhenRunningOnXamarinUITest]
:-)

2024-10-25 07:07 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25943.cs
> +		[FailsOnMacWhenRunningOnXamarinUITestWhenRunningOnXamarinUITestWhenRunningOnXamarinUITest]
Ooops, fixed.

2024-10-29 11:48 UTC, jfversluis commented
/rebase

2024-10-29 11:49 UTC, jfversluis requested changes
Looks like we need a rebase here!

2024-10-31 09:32 UTC, jfversluis approved these changes

2024-10-31 09:35 UTC, merged