Creating .NET MAUI Project sometimes causes error *.png is being used  by another process
dotnet/maui pull request #25374
Opened 2024-10-18 10:29 UTC by dellis1972

Fixes https://github.com/dotnet/maui/issues/25207
Context
https://github.com/dotnet/android-tools/pull/245
https://github.com/dotnet/android/pull/9409

So there is a problem where the design time builds (DTB) of android sometimes lock files. This can happen when two processes try to write to the same file. This is not a great experience for our users as it just fails the build.

So lets try a few things to fix this.

1. Move the Resizetizer output for a DTB into the android `$(IntermediateOutputPath)designtime` folder. This will keep the DTB files completely separate. This should prevent clashes.
2. Add some retry code to the `SkiaSharpTools.Save` method. This will catch `UnauthorizedAccessException` exceptions as well as specific `IOException` types (Access Denied and Sharing Violation). This will allow us to catch when this happens and retry the write. There is a small delay before attempting to write the file again.

Note these code uses the Identical code as we are going to use in Android. We have introduced two new environment variables which can be used to control the new behavior.

1. `DOTNET_ANDROID_FILE_WRITE_RETRY_ATTEMPTS`. Integer, controls the number of times we try to write the file. The default is 10.
2. `DOTNET_ANDROID_FILE_WRITE_RETRY_DELAY_MS`. Integer, controls the delay in milliseconds between retry attempts.  Default is 1000ms (or 1 second).

### Description of Change

### Issues Fixed

Fixes #

2024-10-22 21:20 UTC, PureWeen commented
/azp run

2024-10-24 14:17 UTC, dellis1972 commented
I can't see where the issues with CI are? everything seems to be timing out?

2024-12-04 09:11 UTC, dellis1972 commented
@mattleibow  @Redth  any chance we can get this in? It might help with certain build issues

2024-12-04 09:26 UTC, mattleibow approved these changes

2024-12-04 10:29 UTC, rmarinho commented
/rebase

2024-12-04 10:33 UTC, rmarinho commented
ups sorry didn t saw you just force pushed, I rebased again the android was hanging the 1st run taking more than 1h. lets see if it was a fluke

2024-12-04 13:41 UTC, mattleibow approved these changes, later dismissed

2024-12-04 17:42 UTC, PureWeen requested changes, later dismissed
looks like template tests are all failing
https://dev.azure.com/xamarin/public/_build/results?buildId=129895&view=logs&jobId=8f6de8db-3d66-58dc-07d7-4a92e80cdb05&j=f3581e0c-6e47-5bad-9d98-3a98bd10977c&t=26132a5a-2e4c-526a-ae3b-42bdc526a803

2024-12-05 13:34 UTC, dellis1972 commented
> looks like template tests are all failing https://dev.azure.com/xamarin/public/_build/results?buildId=129895&view=logs&jobId=8f6de8db-3d66-58dc-07d7-4a92e80cdb05&j=f3581e0c-6e47-5bad-9d98-3a98bd10977c&t=26132a5a-2e4c-526a-ae3b-42bdc526a803

Whats the best way to run this locally? I've tried looking at the run logs but they are corrupt ("There was an exception while reading the log file: Unable to read beyond the end of the stream.") .

2024-12-05 17:08 UTC, dellis1972 commented on src/SingleProject/Resizetizer/src/SkiaSharpTools.cs
> +				}
lol. yup

2024-12-05 17:11 UTC, dellis1972 commented on src/SingleProject/Resizetizer/src/SkiaSharpTools.cs
> +				}
Added a return

2024-12-06 05:07 UTC, mattleibow approved these changes

2024-12-06 05:07 UTC, merged