[Android] CarouselView: Remove rounding from SizedItemContentView that results in off-by-one pixel error
dotnet/maui pull request #25411
Opened 2024-10-21 10:54 UTC by filipnavara

### Description of Change

CarouselViewHandler on Android has a measurement logic that converts back and forth between sizes in different units (`Context.FromPixels`/`Context.ToPixels`). The logic in `SizedItemContentView` was inadvertently rounding the values, resulting in some size measurement having an off-by-one width on certain devices and emulators (eg. 1079 instead of 1080).  This in turn resulted in the carousel being scrolled to incorrect item on re-measurement triggered from closing a modal page.

Before:
![carousel-before](https://github.com/user-attachments/assets/95e041cd-44a9-4f01-83d0-af25ac5daa9f)

After:
![carousel-after](https://github.com/user-attachments/assets/77a62805-b2c6-4ef9-9686-646c1f16a9a7)

### Issues Fixed

2024-10-21 22:07 UTC, rmarinho submitted a review, later dismissed

2024-10-21 22:07 UTC, rmarinho commented
/azp run

2024-10-23 08:34 UTC, jsuarezruiz requested changes
The **AddItemsToCarouselViewWorks** UITest is failing on Android. In the test we add a new item and try to scroll to it.

This are the differences:
![image](https://github.com/user-attachments/assets/d743db99-f7a4-48c9-a682-683d44f162c9)
The scroll seems to not be working, the CurrentItem keeps the first item.

2024-10-23 10:36 UTC, filipnavara commented
I made a pragmatic change that should fix the test.

2024-10-25 21:33 UTC, rmarinho commented
/azp run

2024-10-26 16:37 UTC, filipnavara commented
Seems like there was a lot of timeouts ... and a diff for the test above, which actually shows the fixed size:
![image](https://github.com/user-attachments/assets/5a1de9a6-2aab-42c7-8c86-31a37b376843)

2025-01-07 22:22 UTC, rmarinho commented
/reabse

2025-01-07 22:23 UTC, rmarinho commented
/rebase

2025-01-14 12:12 UTC, rmarinho commented
@filipnavara sorry it was my fault  I screwed up the force push I think . Can you reopen with your local copy ? Thanks

2025-01-14 12:15 UTC, filipnavara commented
> @filipnavara sorry it was my fault I screwed up the force push I think . Can you reopen with your local copy ? Thanks

Gotcha. I'll reopen and force push a rebased version.

2025-01-15 14:52 UTC, rmarinho commented
/azp run

2025-01-15 14:53 UTC, rmarinho commented
We need to update images tests for CarouselView

2025-02-10 21:56 UTC, PureWeen commented
I wonder if this is still an issue [after](https://github.com/dotnet/maui/pull/27179)

2025-02-10 22:04 UTC, filipnavara commented
> I wonder if this is still an issue [after](https://github.com/dotnet/maui/pull/27179)

The two PRs fixed unrelated issues even if they touched on the same topic.

2025-02-10 22:07 UTC, PureWeen commented
/azp run

2025-02-20 18:30 UTC, rmarinho commented
/rebase

2025-02-20 18:32 UTC, rmarinho commented on src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
> +							UpdatePosition(carouselPosition);
Should we set _scrollToCounter to 0 here ?

2025-02-20 18:32 UTC, rmarinho commented
/azp run

2025-02-24 17:54 UTC, rmarinho commented
/rebase

2025-02-24 17:56 UTC, rmarinho commented
/azp run

2025-02-28 11:27 UTC, filipnavara commented
There are three images that need to be updated in UITests. I'll look into it unless you beat me to it.

2025-03-04 13:00 UTC, jsuarezruiz requested changes

2025-03-04 13:00 UTC, jsuarezruiz commented on src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs
> +				targetWidth = Context.FromPixels(targetWidth);
I think based on this changes, there are three failing tests becuase small differences:
<img width="339" alt="image" src="https://github.com/user-attachments/assets/034c8ba9-0fb2-40a2-80b3-9842ac592faa" />

For example:
CarouselItemsShouldRenderProperly
`Snapshot different than baseline: CarouselItemsShouldRenderProperly.png (1.13% difference)`
![image](https://github.com/user-attachments/assets/de6bc891-c03c-461c-b47a-7db743df7f2f)

(In red the differences)

Could you review/update the snapshots? Let me know if can help.

2025-03-04 14:25 UTC, filipnavara commented on src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs
> +				targetWidth = Context.FromPixels(targetWidth);
I updated the screenshots.

2025-03-04 19:39 UTC, PureWeen commented
/azp run

2025-03-05 15:20 UTC, rmarinho submitted a review, later dismissed

2025-03-06 13:05 UTC, rmarinho commented
/rebase

2025-03-06 13:06 UTC, rmarinho commented
/azp run

2025-03-07 01:22 UTC, rmarinho commented
Needs to be update this screenshot on android for CarouselViewShouldRenderCorrectly

![CarouselViewShouldRenderCorrectly](https://github.com/user-attachments/assets/2b33e371-7211-4c1b-b43d-75c73082534f)

2025-03-07 01:42 UTC, filipnavara commented
> Needs to be update this screenshot on android for CarouselViewShouldRenderCorrectly

Yeah, there was a conflict for this one after the last merge. :-/ I updated it.

2025-03-07 10:42 UTC, rmarinho commented
/azp run

2025-03-12 12:25 UTC, mattleibow requested changes
Is it possible to rebase and also add a UI test that replicates the issue?

I assume it  just needs a CarouselView with a few items and then a button somewhere to push and then pop a modal? Is it just the matter of popping the modal that cases the CV to scroll incorrectly?

2025-03-12 12:34 UTC, filipnavara commented
> Is it possible to rebase and also add a UI test that replicates the issue?

I can rebase it but it will likely fail the UI tests again because of the changed baseline and the images will need to be updated. Frankly, it's becoming quite cumbersome doing this for several months now.

Replicating the issue with wrong scrolling may be a bit tricky. Replicating the wrong rounding resulting in wrongly sized items is already covered by existing tests.

2025-03-18 16:41 UTC, rmarinho commented
/azp run

2025-03-20 11:20 UTC, rmarinho commented
/azp run

2025-03-20 11:21 UTC, rmarinho submitted a review, later dismissed

2025-03-20 12:05 UTC, rmarinho commented
/azp run MAUI-DeviceTests-public

2025-03-20 12:24 UTC, rmarinho commented
/azp run MAUI-public

2025-03-21 10:23 UTC, rmarinho approved these changes

2025-03-21 10:23 UTC, merged

2025-03-21 10:32 UTC, filipnavara commented
@rmarinho Thanks!