Fixed crash when calling ItemsView.ScrollTo on unloaded CollectionView
dotnet/maui pull request #25444
Opened 2024-10-22 09:53 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23014

2024-10-22 17:56 UTC, rmarinho commented
/rebase

2024-10-23 07:34 UTC, jsuarezruiz commented
/azp run

2024-10-23 08:30 UTC, jsuarezruiz reviewed
The fix is correct, we have to check if the PlatformView is not null or disposed when invoking ScrollTo, but can we apply the verification in a single place or in the same place on each platform?

When ScrollTo is invoked the following event is invoked:
https://github.com/dotnet/maui/blob/c21b5184d1894426ece6bd8a298d1aea7f0bb468/src/Controls/src/Core/Items/ItemsView.cs#L154

Then, in every platform handler we subscribe to https://github.com/dotnet/maui/blob/c21b5184d1894426ece6bd8a298d1aea7f0bb468/src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs#L53

And try to do the scroll here https://github.com/dotnet/maui/blob/c21b5184d1894426ece6bd8a298d1aea7f0bb468/src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs#L593 where can check if control is not disposed.

2024-10-26 00:56 UTC, kubaflo commented
> The fix is correct, we have to check if the PlatformView is not null or disposed when invoking ScrollTo, but can we apply the verification in a single place or in the same place on each platform?
> 
> When ScrollTo is invoked the following event is invoked:
> 
> https://github.com/dotnet/maui/blob/c21b5184d1894426ece6bd8a298d1aea7f0bb468/src/Controls/src/Core/Items/ItemsView.cs#L154
> 
> Then, in every platform handler we subscribe to
> 
> https://github.com/dotnet/maui/blob/c21b5184d1894426ece6bd8a298d1aea7f0bb468/src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs#L53
> 
> And try to do the scroll here
> 
> https://github.com/dotnet/maui/blob/c21b5184d1894426ece6bd8a298d1aea7f0bb468/src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs#L593
> 
> where can check if control is not disposed.

I like the idea!

2024-10-26 00:57 UTC, kubaflo commented
@jsuarezruiz I've applied the verification in only one, platform shared place

2024-10-28 08:05 UTC, jsuarezruiz commented
/azp run

2024-11-28 23:47 UTC, rmarinho commented
/rebase

2024-11-28 23:48 UTC, rmarinho commented
/azp run

2025-08-23 12:27 UTC, PureWeen commented
/rebase

2025-08-23 12:28 UTC, PureWeen requested changes
Can you apply this to cv2 as well

2025-08-23 12:29 UTC, PureWeen commented
/azp run

2026-03-09 16:16 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-10 01:24 UTC, kubaflo commented
<!-- AI Summary -->

## 🤖 AI Summary

<!-- SECTION:PR-REVIEW -->
<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed crash when calling ItemsView.ScrollTo on unloaded CollectionView</strong> · <a href="https://github.com/dotnet/maui/commit/6ed7a8b60e52fd07c1c428681ab9190de1023f6f"><code>6ed7a8b</code></a></summary>

---

**Issue:** #23014 - App crashes when calling ItemsView.ScrollTo on unloaded CollectionView
**PR:** #25444 - Fixed crash when calling ItemsView.ScrollTo on unloaded CollectionView
**Author:** kubaflo (Jakub Florkowski) — Community Contribution ✨
**Platforms Affected:** iOS, Android, Windows, macOS (all platforms)
**Files Changed:** 1 implementation file, 3 test files

### Issue Summary

Exceptions are thrown on all platforms when calling `ScrollTo` on an unloaded CollectionView (after it's been removed from its parent). This can happen accidentally when `ScrollTo` is called from an event handler (e.g., `SelectionChanged`) that fires during XAML Hot Reload or during disposal. Each platform throws a different exception:
- **Windows**: NullReferenceException (handler still listening after `CleanUpCollectionViewSource()`)
- **Android**: `Java.Lang.IllegalArgumentException: Invalid target position`
- **iOS**: Index out of range exception

The user-reported workaround was to check `IsLoaded` before calling `ScrollTo`.

### Fix Approach

The fix adds a `DismissScroll()` guard in `ItemsView.cs` (the base class) that returns early if `Handler is null || ItemsSource is null`. This is called from both `ScrollTo` overloads before firing the `ScrollToRequested` event. Since it's in the base class, it applies to both cv1 and cv2 handlers.

### Key Reviewer Feedback

| Reviewer | Comment | Status |
|----------|---------|--------|
| jsuarezruiz | Apply the fix in a single shared place (not per-platform handler) | ✅ ADDRESSED - fix moved to `ItemsView.cs` |
| PureWeen | CHANGES_REQUESTED: "Can you apply this to cv2 as well" | ⚠️ INVESTIGATE - fix is in base class but concern may remain |

### Edge Cases / Disagreements

- PureWeen's CHANGES_REQUESTED is the current review state. The fix in `ItemsView.cs` is in the base class which both cv1 and cv2 inherit from. The test file uses `CollectionView2` (cv2 handler) to exercise the cv2 path. This may or may not fully satisfy PureWeen's concern.

### Files Changed

**Fix files:**
- `src/Controls/src/Core/Items/ItemsView.cs` (+11): Added `DismissScroll()` method and guards in `ScrollTo` overloads

**Test files:**
- `src/Controls/tests/TestCases.HostApp/Issues/Issue23014.xaml` (+30): XAML page using `CollectionView2` to reproduce the crash
- `src/Controls/tests/TestCases.HostApp/Issues/Issue23014.xaml.cs` (+35): Code-behind: removes CV from parent, calls `ScrollTo`, checks for crash
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23014.cs` (+26): UI test that clicks button and verifies "Success" label

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #25444 | Guard in `ItemsView.DismissScroll()` checking `Handler is null \|\| ItemsSource is null` | ⏳ PENDING (Gate) | `ItemsView.cs` (+11) | Original PR — base class fix covering all handlers |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed crash when calling ItemsView.ScrollTo on unloaded CollectionView</strong> · <a href="https://github.com/dotnet/maui/commit/6ed7a8b60e52fd07c1c428681ab9190de1023f6f"><code>6ed7a8b</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** android
**Mode:** Full Verification
**PR:** #25444

- Tests FAIL without fix ✅
- Tests PASS with fix ✅

### Details
- Fix files detected: `src/Controls/src/Core/Items/ItemsView.cs`
- TestFilter: `Issue23014`
- Both phases completed successfully

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed crash when calling ItemsView.ScrollTo on unloaded CollectionView</strong> · <a href="https://github.com/dotnet/maui/commit/6ed7a8b60e52fd07c1c428681ab9190de1023f6f"><code>6ed7a8b</code></a></summary>

---

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| 1 | try-fix (claude-sonnet-4.6) | `!IsLoaded \|\| ItemsSource is null` in `DismissScroll()` | ✅ PASS | `ItemsView.cs` | Semantically clear lifecycle API |
| 2 | try-fix (claude-opus-4.6) | Guard in `OnScrollToRequested` virtual method: `Window is null \|\| ItemsSource is null` | ✅ PASS | `ItemsView.cs` | Single dispatch point |
| 3 | try-fix (gpt-5.2) | Android platform guard in `MauiRecyclerView.ScrollTo`: `!IsAttachedToWindow` + adapter bounds | ✅ PASS | `MauiRecyclerView.cs` | Android-only, doesn't protect other platforms |
| 4 | try-fix (gpt-5.3-codex) | `Parent is null \|\| ItemsSource is null` guard in `ScrollTo` overloads | ✅ PASS | `ItemsView.cs` | Parent can be null in some edge cases |
| 5 | try-fix (gemini-3-pro-preview) | try/catch `IllegalArgumentException` in `ScrollHelper.cs` (Android) | ✅ PASS | `ScrollHelper.cs` | Exception swallowing — poor pattern |
| PR | PR #25444 | `Handler is null \|\| ItemsSource is null` in `DismissScroll()` | ✅ PASS (Gate) | `ItemsView.cs` (+11) | Base class fix, covers cv1 and cv2 |

### Cross-Pollination Summary

**Round 2:** claude-opus-4.6 → NO NEW IDEAS; gemini → NO NEW IDEAS; others proposed variations (deferred queue, handler layer, version token) — all dismissed as feature enhancements or over-engineering.

**Round 3:** gemini → NO NEW IDEAS; others proposed minor variations (unsubscribe in DisconnectHandler, PlatformView==null, LayoutManager null) — all dismissed as variations of existing approaches.

**Exhausted:** Yes (max 3 rounds, no new viable crash-fix approaches)

### Selected Fix: PR's fix

**Reasoning:** PR's fix (`Handler is null || ItemsSource is null`) is the most appropriate because:
1. ✅ `Handler` is the most direct indicator of platform operability — it's null when the view is disconnected from the visual tree
2. ✅ Placed in the base class `ItemsView` — covers all ItemsView subclasses including both cv1 and cv2 handlers
3. ✅ Minimal, surgical change (+11 lines)
4. ✅ Matches codebase patterns
5. ✅ Independently validated: 5 alternative approaches all confirmed the base-class guard strategy works
6. ✅ Exception-swallowing (Attempt 5) and platform-specific (Attempt 3) approaches are inferior

All try-fix alternatives validated the same fundamental approach (guard before platform operations), confirming the PR's design direction is correct. The primary difference between candidates is which readiness condition to check — `Handler is null` is the most semantically precise for platform operations.

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed crash when calling ItemsView.ScrollTo on unloaded CollectionView</strong> · <a href="https://github.com/dotnet/maui/commit/6ed7a8b60e52fd07c1c428681ab9190de1023f6f"><code>6ed7a8b</code></a></summary>

---

## ✅ Final Recommendation: APPROVE

### Summary

PR #25444 fixes a crash that occurs when `ItemsView.ScrollTo` is called on a CollectionView that has been removed from the visual tree (unloaded). The fix is minimal, correct, and placed in the base class so it covers all ItemsView subclasses and both handler implementations (cv1 and cv2).

Gate verification confirmed: tests **fail** without the fix and **pass** with it on Android. Five independent multi-model try [...]

2026-03-10 11:31 UTC, merged