[Android] Added a scroll bar for collection view
dotnet/maui pull request #25471
Opened 2024-10-23 12:53 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25468
Fixes https://github.com/dotnet/maui/issues/11369

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/8ae8caa1-3f21-4362-b401-348201b95292" width="300px"/>|<video src="https://github.com/user-attachments/assets/98e8af0b-9c3f-42f3-9fd6-93e0415729a0" width="300px"/>|

2024-10-25 21:31 UTC, rmarinho commented
/rebase

2024-10-26 23:45 UTC, rmarinho commented
/azp run

2024-10-26 23:57 UTC, kubaflo commented on src/Controls/tests/TestCases.HostApp/Issues/Issue25468.xaml.xaml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
Change this file name from Issue25468.xaml.xaml to Issue25468.xaml after uploading screenshots

2024-10-26 23:58 UTC, kubaflo commented on src/Controls/tests/TestCases.HostApp/Issues/Issue25468.cs
> +{
Change this file name from Issue25468.cs to Issue25468.xaml.cs after uploading screenshots

2024-11-18 11:29 UTC, jsuarezruiz commented
/azp run

2024-12-09 14:46 UTC, jfversluis commented
/rebase

2024-12-12 12:45 UTC, jfversluis commented
/rebase

2024-12-16 11:47 UTC, jfversluis requested changes
Test fails :( 

![image](https://github.com/user-attachments/assets/d5c4e3b4-d802-4843-99f6-021eaa4002ab)

2024-12-16 12:25 UTC, kubaflo commented
@jfversluis hmmm it looks like there are the same problems with other tests too. Could you please /azp again?

2024-12-18 07:52 UTC, jfversluis approved these changes

2024-12-18 07:52 UTC, merged