Fix Button Regression with null image source
dotnet/maui pull request #25485
Opened 2024-10-23 22:06 UTC by tj-devel709

This PR fixes an null reference issue that occurs when an button has its image set by UIButton.SetImage. Instead of using the Button.ImageSource.ToString() to see if the image has changed without needing to hold a reference to the image, the code now uses the UIButton.CurrentImage hash to determine if the image has changed. This helps us know if the image was changed in those situations where the Button.ImageSource is null but the UIButton.CurrentImage is still set.

### Description of Change

### Issues Fixed

Fixes #25409

2024-10-24 08:52 UTC, jsuarezruiz requested changes

2024-10-24 08:52 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.HostApp/Issues/Issue25409.xaml.cs
> +			var imageSource = new FileImageSource() { File = "shopping_cart.png" };
Could the test be extended to:
- Set the image when the button is tapped.
- Remove the image, setting a null value when tapping again.
- Reset the image by tapping the button again (for example, using a counter, odd sets image, even removes it).
?

2024-10-24 08:52 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25409.cs
> +using NUnit.Framework;
This specific test only have sense on iOS, right? Use compilation directives here.

2024-10-24 17:26 UTC, tj-devel709 commented
Okay, test has been rebased off the release/9.0.1xx branch, and it now uses the UIImage as a weakreference instead of the hash. Tests have also been updated on @jsuarezruiz's request!

2024-10-24 19:56 UTC, tj-devel709 commented
/azp run

2024-10-24 20:02 UTC, PureWeen commented on src/Controls/src/Core/Button/Button.iOS.cs
> +			_originalImageRef.TryGetTarget(out var _originalImage);
remove _ from this variable

2024-10-24 22:23 UTC, PureWeen requested changes
https://github.com/dotnet/maui/pull/25485/files#r1815631835

2024-10-25 02:14 UTC, PureWeen approved these changes

2024-10-25 06:34 UTC, jsuarezruiz approved these changes

2024-10-25 13:11 UTC, merged

2024-10-25 13:13 UTC, PureWeen commented
/backport to release/8.0.1xx-sr10

2024-10-30 14:49 UTC, PureWeen commented
/backport to 8.0.1xx-sr9