[iOS] Ensure Subviews are Not Covered by Tab Bar
dotnet/maui pull request #25490
Opened 2024-10-24 00:40 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25474

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/792cd79e-32d3-4f3e-9f26-8dc827ac14a7" width="300px"/>|<video src="https://github.com/user-attachments/assets/659d7b0b-894b-4987-933e-5f0ccdb075d5" width="300px"/>|

2024-10-28 08:03 UTC, jsuarezruiz commented
@kubaflo Could you rebase to fix the conflicts? Thanks in advance.

2024-10-28 11:55 UTC, kubaflo commented
@jsuarezruiz certainly! done

2024-10-29 14:34 UTC, rmarinho commented
/azp run

2024-11-05 02:27 UTC, kubaflo commented
@jfversluis I've checked and https://github.com/dotnet/maui/issues/17817 is already fixed on the latest NET9
<img src="https://github.com/user-attachments/assets/e8f0343e-8f7e-4592-91f4-27117e432bd8" width="300px"/>

2024-11-12 14:23 UTC, jsuarezruiz commented
/rebase

2024-12-16 11:36 UTC, rmarinho commented
/azp run

2024-12-16 14:31 UTC, rmarinho reviewed
I think we need to update some screenshots for iOS CollectionView test for this . Also @PureWeen  can this be in a SR or push a new 9.1.0 version ?

2025-01-09 11:01 UTC, jfversluis commented
/rebase

2025-01-09 22:37 UTC, PureWeen requested changes
I don't think we want to invest further into this API 

For now we should probably just make it so that CV2 is safearea aware and adjusts its contentinsets accordingly

Which I think is what we do with UIScrollView

2025-01-11 00:22 UTC, kubaflo commented
Closing this one because both CV and CV2 behave properly when we set `ios:Page.UseSafeArea="True"`

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Maui.Controls.Sample.MainPage"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="True"
             xmlns:local="clr-namespace:Maui.Controls.Sample">
    <CollectionView x:Name="collectionView">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Border Padding="20"
                        Background="Red"
                        HeightRequest="200">
                    <Label Text="{Binding .}"
                           VerticalOptions="Center"
                           HorizontalOptions="Center"/>
                </Border>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```

2025-01-11 00:22 UTC, closed without merging