Fix Shell Flyout Menu Visibility Issue When Navigating Between TabBar and Flyout Items
dotnet/maui pull request #25510
Opened 2024-10-24 17:13 UTC by vishnumenon2684

### Issue:
In the sample, if there are both flyout items and tab bar items in the Shell, navigating to a TabBar item causes the flyout menu icon to disappear. However, when navigating back to a flyout item, the flyout menu is not visible.
 
### Root Cause:
When navigating to a TabBar item, the flyout behavior is set to **Disabled**. Upon returning to a flyout item, the flyout behavior is not restored. This issue was previously working fine but regressed due to PR-[23863](https://github.com/dotnet/maui/pull/23863). In that PR, navigating using services clears the previous sections content cache, so when navigating back to the flyout page, the page is unavailable, preventing the flyout behavior from being reset.
 
### Fix:
When updating the flyout behavior, the visible page check is not required. Instead, it's necessary to verify whether the parent is a Shell section. Therefore, I replaced the check for the visible page with a check to ensure the **CurrentItem** is a **ShellSectionController**.

Fixes #25436

2024-10-24 17:22 UTC, PureWeen commented
/backport to main

2024-10-24 17:32 UTC, PureWeen commented on src/Controls/src/Core/Shell/Shell.cs
> +			if (CurrentItem is null || CurrentItem.CurrentItem is not IShellSectionController)
if ( CurrentItem?.CurrentItem is null)
    return;

would be the same yea?

2024-10-24 17:37 UTC, PureWeen requested changes
> the page is unavailable, preventing the flyout behavior from being reset.

I think with the way flyout behavior calculation works the fix here my be that we need to refire this Notify method once the CurrentPage becomes available again. 

The FlyoutBehavior value takes into account if the FlyoutBehavior is set on the Page itself which I think might cause this to miscalculate if the user has set FlyoutBehavior on the realized ContentPage

2024-10-29 09:27 UTC, karthikraja-arumugam commented
> The FlyoutBehavior value takes into account if the FlyoutBehavior is set on the Page itself which I think might cause this to miscalculate if the user has set FlyoutBehavior on the realized ContentPage

@PureWeen, based on the suggestion I'm looking for an alternate fix.

2024-10-30 08:40 UTC, jsuarezruiz commented
/azp run

2024-10-30 18:52 UTC, PureWeen requested changes
rebase this for main please

2024-11-01 12:18 UTC, vishnumenon2684 commented
> rebase this for main please

Hi @PureWeen , I have rebased the PR to main.

2024-11-01 12:49 UTC, jfversluis commented
/rebase

2024-11-01 12:51 UTC, jfversluis commented
/azp run

2024-11-06 18:33 UTC, PureWeen requested changes
Can you add a test?

2024-11-07 08:51 UTC, Ahamed-Ali commented
> Can you add a test?

I have added test cases @PureWeen

2024-11-08 09:53 UTC, jsuarezruiz commented
/rebase

2024-11-08 09:54 UTC, jsuarezruiz commented
/azp run

2024-11-12 11:59 UTC, jsuarezruiz commented
/azp run

2024-11-18 00:26 UTC, rmarinho commented
/azp run

2024-11-27 12:02 UTC, rmarinho approved these changes

2024-11-27 12:04 UTC, merged