Fix 13573
dotnet/maui pull request #25663
Opened 2024-11-04 11:38 UTC by SuthiYuvaraj

### Issue Details
When navigating between the pages , the ApplyQuerableAttributes need to be triggered with the navigating page data, In the current implementation , Navigating through Push and GoToAsync worked as expected , remaining navigation does not triggers the Query Attriute notification

### Root Cause
- Issue with GoToAsync , If we navigate the page using PopAsync, PopModalAsync or BackNavigation or Navigating between the FlyoutPages does not triggers ApplyQueryAttribute where in QueryAttribute is not properly set for this type of navigations
- Issue with TabBarNavigation - If we the navigate between the TabBar the page will be changed by updating the CurrentItemChanged , here QueryAttribute is not updated for the ItemChanges.
 
### Fix Details
- Fix for GoToAsync , On ApplyQueryAttributes on ShellNavigation Manager , updated the value of QuerableAttributes on Popping.
- Fix for TabBarNavigation- Invoked ApplyQueryAttributes on UpdateCurrentState to get the notification for all the ShellItem navigation

### Issues Fixed
Fixes #13537

2024-11-06 09:13 UTC, jsuarezruiz commented
/azp run

2024-11-08 12:44 UTC, jsuarezruiz commented
/rebase

2024-11-11 10:54 UTC, jsuarezruiz commented
/azp run

2024-11-18 12:34 UTC, jsuarezruiz commented
/rebase

2024-11-20 10:19 UTC, jsuarezruiz commented
/azp run

2024-11-25 15:58 UTC, jsuarezruiz commented
/azp run

2024-11-26 10:05 UTC, jsuarezruiz commented
/azp run

2024-11-26 12:22 UTC, jsuarezruiz requested changes
There are unit tests failing:

```
Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
Error Message:
Assert.False() Failure
Expected: False
Actual:   True

 Failed SetCurrentItemAddsToShellCollection [1 ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.UpdateCurrentState(ShellNavigationSource source) in /_/src/Controls/src/Core/Shell/Shell.cs:line 936
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in /_/src/Controls/src/Core/Shell/ShellNavigationManager.cs:line 204
   at Microsoft.Maui.Controls.Shell.<Initialize>g__SetCurrentItem|158_1() in /_/src/Controls/src/Core/Shell/Shell.cs:line 1284
   at Microsoft.Maui.Controls.Shell.<Initialize>b__158_0(Object s, NotifyCollectionChangedEventArgs e) in /_/src/Controls/src/Core/Shell/Shell.cs:line 1217
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

2024-11-27 07:50 UTC, SuthiYuvaraj commented
> There are unit tests failing:
> 
> ```
> Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
> Error Message:
> Assert.False() Failure
> Expected: False
> Actual:   True
> 
>  Failed SetCurrentItemAddsToShellCollection [1 ms]
>   Error Message:
>    System.NullReferenceException : Object reference not set to an instance of an object.
>   Stack Trace:
>      at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.UpdateCurrentState(ShellNavigationSource source) in /_/src/Controls/src/Core/Shell/Shell.cs:line 936
>    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in /_/src/Controls/src/Core/Shell/ShellNavigationManager.cs:line 204
>    at Microsoft.Maui.Controls.Shell.<Initialize>g__SetCurrentItem|158_1() in /_/src/Controls/src/Core/Shell/Shell.cs:line 1284
>    at Microsoft.Maui.Controls.Shell.<Initialize>b__158_0(Object s, NotifyCollectionChangedEventArgs e) in /_/src/Controls/src/Core/Shell/Shell.cs:line 1217
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
> ```

Hi @jsuarezruiz , The `UpdateCurrentState` method has been updated with proper null handling. Kindly review it and let us know if you  any concerns.

2024-11-27 14:20 UTC, jsuarezruiz commented
/azp run

2024-11-27 15:05 UTC, jsuarezruiz requested changes
Sorry, still there is one failing unit tests:

```
Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
Error Message:
Assert.False() Failure
Expected: False
Actual:   True
```

2024-11-28 08:04 UTC, SuthiYuvaraj commented
> Sorry, still there is one failing unit tests:
> 
> ```
> Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
> Error Message:
> Assert.False() Failure
> Expected: False
> Actual:   True
> ```

@jsuarezruiz, The failing unit test case is intended to verify that the query attribute should not be present during the initial loading. However, the bug report confirms this behavior as a valid bug https://github.com/dotnet/maui/issues/13537#issuecomment-1452800073.Therefore, the test case is no longer applicable. Can the failing test case be removed?

2024-12-16 07:56 UTC, SuthiYuvaraj commented
> Sorry, still there is one failing unit tests:
> 
> ```
> Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
> Error Message:
> Assert.False() Failure
> Expected: False
> Actual:   True
> ```

@jsuarezruiz  , After analyzing the failed test case (`InitialNavigationDoesntSetQueryAttributesProperty`) scenario, I have modified the fix to prevent invoking the `QueryableAttribute` during the initial loading. Kindly review it and share any concerns

2025-01-10 09:03 UTC, jsuarezruiz commented
/rebase

2025-01-10 11:33 UTC, jsuarezruiz commented
/azp run

2025-02-17 12:57 UTC, jsuarezruiz commented
/rebase

2025-02-18 10:53 UTC, StephaneDelcroix commented on src/Controls/src/Core/Shell/ShellItem.cs
> +			currentShellContent?.SetValue(ShellContent.QueryAttributesProperty, new ShellRouteParameters());
nit: indentation

2025-02-18 10:53 UTC, StephaneDelcroix commented on src/Controls/src/Core/Shell/ShellNavigationManager.cs
> +				if(isPopping)
nit: white space

2025-02-18 10:53 UTC, StephaneDelcroix commented on src/Controls/src/Core/Shell/Shell.cs
> +            if(oldValue is not null && newValue is not null && (shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem) && existing is null)
do we need to check for oldValue ?

2025-02-20 10:42 UTC, SuthiYuvaraj commented on src/Controls/src/Core/Shell/Shell.cs
> +            if(oldValue is not null && newValue is not null && (shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem) && existing is null)
Yes @StephaneDelcroix , The `ApplyQueryAttributes trigger` is not required for the initial load; therefore, a null check has been added for the `oldValue`.

2025-02-20 11:04 UTC, SuthiYuvaraj commented on src/Controls/src/Core/Shell/ShellItem.cs
> +			currentShellContent?.SetValue(ShellContent.QueryAttributesProperty, new ShellRouteParameters());
I have addressed the indentation issue. Let me know if anything else needs adjustment.

2025-02-20 11:04 UTC, SuthiYuvaraj commented on src/Controls/src/Core/Shell/ShellNavigationManager.cs
> +				if(isPopping)
I have addressed the whitespace issue. Let me know if anything else needs adjustment.

2025-02-26 07:23 UTC, jsuarezruiz commented
/azp run

2025-02-26 11:20 UTC, jsuarezruiz commented on src/Controls/src/Core/Shell/Shell.cs
> +            if(oldValue is not null && newValue is not null && (shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem) && existing is null)
This is a condition with a lot of checks. Not required but, we could improve the readability with small changes:

```
bool isRelevantShellItem = shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem;
bool isNewValueDifferent = oldValue is not null && newValue is not null && existing is null;

if (isNewValueDifferent && isRelevantShellItem)
```

2025-02-26 11:20 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13537.cs
> +#if !MACCATALYST
Why we avoid this test on Catalyst?

2025-02-27 14:50 UTC, SuthiYuvaraj commented on src/Controls/src/Core/Shell/Shell.cs
> +            if(oldValue is not null && newValue is not null && (shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem) && existing is null)
Hi @jsuarezruiz  , I have modified the condition based on your suggestion. Kindly review and let me know if you have any concern.

2025-02-27 15:04 UTC, SuthiYuvaraj commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13537.cs
> +#if !MACCATALYST
Hi @jsuarezruiz  , `App.TapBackArrow` does not actually tap the back arrow button. Instead, it taps the first tab element on the screen because both elements share the same accessibility identifier. To address this, Catalyst has been ignored, and appropriate comments have been added.

2025-03-05 10:08 UTC, jsuarezruiz commented
/azp run

2025-03-25 07:27 UTC, jsuarezruiz commented
/rebase

2025-05-08 20:57 UTC, PureWeen commented
@SuthiYuvaraj can you rebase this one to net10?

2025-05-28 21:54 UTC, rmarinho commented
/azp run

2025-07-01 06:59 UTC, jsuarezruiz commented
/rebase

2025-10-23 10:16 UTC, jsuarezruiz commented
/azp run

2025-12-04 15:26 UTC, StephaneDelcroix commented
when merged, merge additional tests from https://github.com/dotnet/maui/pull/33006

2025-12-04 15:31 UTC, StephaneDelcroix approved these changes

2025-12-04 16:08 UTC, merged