[iOS] Fix for Editor scaling creating new lines on older iOS versions
dotnet/maui pull request #25691
Opened 2024-11-05 13:37 UTC by Tamilarasan-Paranthaman

### Root Cause of the issue 

- The layout of the Editor behaves differently on iOS 17.5 and earlier versions when the scale changes at runtime. Specifically, the content height gradually increases when scaling down the Editor, suggesting improper handling of height. 

### Description of Change

-  It seems that iOS 18.0 handles this behavior correctly. To ensure consistent behavior similar to iOS 18.0, I wrapped the Editor in a container for iOS 17.5 and earlier versions. This container ensures that the layout remains stable and visually consistent, even when the Editor is scaled or resized. Since the issue is resolved in iOS 18.0 and later, the additional container is not needed for those versions.

### Issues Fixed

Fixes #25581

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/bde4b741-5cbe-49d4-89c6-546770c5a985"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/001f57da-855b-4106-9bf0-e9dc34b09395"> |

2024-11-05 14:00 UTC, PureWeen commented
/azp run

2024-11-06 11:14 UTC, jsuarezruiz requested changes

2024-11-07 08:23 UTC, Tamilarasan-Paranthaman commented on src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
> +			get
@jsuarezruiz, I have added a UITest sample for this issue.

2024-11-08 08:50 UTC, jsuarezruiz commented
/rebase

2024-11-08 08:51 UTC, jsuarezruiz commented
/azp run

2024-11-10 16:53 UTC, PureWeen requested changes
Test failing on winui

2024-11-11 10:46 UTC, jsuarezruiz commented
/azp run

2024-11-12 12:04 UTC, jsuarezruiz requested changes, later dismissed
The device tests:

```
ScrollEditor
Assert.True() Failure\nExpected: True\nActual:   False
```

and

```
ScrollNextEditor
Assert.True() Failure\nExpected: True\nActual:   False
```

are failing after the changes.

2024-11-13 09:41 UTC, Tamilarasan-Paranthaman commented
> The device tests:
> 
> ```
> ScrollEditor
> Assert.True() Failure\nExpected: True\nActual:   False
> ```
> 
> and
> 
> ```
> ScrollNextEditor
> Assert.True() Failure\nExpected: True\nActual:   False
> ```
> 
> are failing after the changes.

@jsuarezruiz, I have fixed this by restricting the Mac platform in the fix, as the issue occurred on the iOS platform. The cases have passed locally. Could you please check and let me know if you have any concerns?

<img width="687" alt="Screenshot" src="https://github.com/user-attachments/assets/5f0fdc78-cf9f-4faa-806b-b9e55ff9a7e6">

2024-11-20 10:19 UTC, jsuarezruiz commented
/azp run

2024-12-04 21:03 UTC, tj-devel709 commented
@Tamilarasan-Paranthaman did you see this issue in iOS 17? I have only noticed it in 15.5 and 16.4 but maybe there is a scenario it happens in 17 also?

2024-12-05 06:29 UTC, Tamilarasan-Paranthaman commented
> @Tamilarasan-Paranthaman did you see this issue in iOS 17? I have only noticed it in 15.5 and 16.4 but maybe there is a scenario it happens in 17 also?

@tj-devel709, I encountered this issue in iOS 17+ as well. Interestingly, I am currently unable to reproduce it in iOS 17+ (specifically tested on version 17.5). This is quite unusual, as the issue report also confirms it was [verified](https://github.com/dotnet/maui/issues/25581#issuecomment-2449448297) in version 17.5. Could you please share your thoughts on this and suggest how we should proceed?

2024-12-05 22:30 UTC, PureWeen commented
@Tamilarasan-Paranthaman let's just go with what you're seeing

Can you just set the operating system version check to whatever version you find that we need this for?

2024-12-06 10:48 UTC, Tamilarasan-Paranthaman commented
> @Tamilarasan-Paranthaman let's just go with what you're seeing
> 
> Can you just set the operating system version check to whatever version you find that we need this for?

@PureWeen, I have updated the version, and it will now apply only to versions below 17. Could you please check it now and let me know if you have any further concerns?

2024-12-06 21:47 UTC, PureWeen commented
/azp run

2024-12-09 16:49 UTC, tj-devel709 approved these changes
Confirmed with these new changes that it works with the following I versions!

18.1
18.0
17.5
17.2
17.01
16.4
15.5

2024-12-09 16:56 UTC, PureWeen approved these changes

2024-12-10 09:30 UTC, merged