[Testing] Enable snapshot tests on Catalyst
dotnet/maui pull request #25710
Opened 2024-11-06 08:39 UTC by jsuarezruiz

### Description of Change

Enable snapshot tests on Catalyst.

2024-11-07 12:03 UTC, jsuarezruiz commented
/rebase

2024-11-07 14:27 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImageSourceInitializesCorrectly.png
Clearly, the behavior from the Buttons is incorrect, same as on iOS actually. Will be fixed by https://github.com/dotnet/maui/pull/25373
After merge that PR, this snapshot must be updated.

2024-11-26 10:25 UTC, jfversluis requested changes
Has conflicts now, sorry!

2024-12-17 15:14 UTC, jfversluis commented
/rebase

2024-12-18 07:43 UTC, jfversluis approved these changes

2024-12-18 07:44 UTC, merged