[Android] Fix RadioButton using ContentPresenter not rendering
dotnet/maui pull request #25947
Opened 2024-11-19 14:19 UTC by jsuarezruiz

### Description of Change

Fix RadioButton using ContentPresenter not rendering on Android. Found the cause of the problem. The binding from ContentPresenter changed here https://github.com/dotnet/maui/commit/4c3a09c249f0b6a0980c99e160a9985749c761bb#diff-f01d408e1d2b3cd4a4c1bcf731586c215c9d57d4585d6815d5c89118a1ef3f44R20 (changes to allow trimming).

Working on a change fixing the issue and not breaking trimming at the same time.

### Issues Fixed

Fixes #25887

2024-11-20 16:23 UTC, mattleibow submitted a review, later dismissed
I got a comment on an idea of what maybe we should do: https://github.com/dotnet/maui/issues/24949#issuecomment-2488976639

2024-11-20 16:38 UTC, PureWeen requested changes
So I think @mattleibow is on to something here. 

It does feel like this should work
https://github.com/dotnet/maui/issues/24949#issuecomment-2488976639

I tested locally real quick and it didn't work, but, there might just be something simple that needs to be added/fixed

2024-11-21 17:20 UTC, PureWeen approved these changes

2024-11-21 17:21 UTC, merged

2024-11-21 17:21 UTC, PureWeen commented
/backport to release/9.0.1xx