Add fallback to ContentPresenter Content binding using reflection
dotnet/maui pull request #25992
Opened 2024-11-20 16:05 UTC by simonrozsival

### Description of Change

It turns out that for customers that are deriving from `TemplatedView` run into issues with the `ContentPresenter` and the binding for the `Content` property.
- For customers that don't trim their apps, the fallback to reflection would match the behavior they were experiencing in .NET 8
- For customers that trim/Native AOT their apps, the fallback likely won't do anything but it also won't produce any warning.

AFAIK we currently don't have any docs that would mention how to implement custom `TemplatedView` that could be updated to mention that the "proper" way to do this is to implement the `object IContentView.Content` property in the derived class. I added runtime warning but I'm not sure how many developers will actually see this or just miss it completely. 

cc @PureWeen @mattleibow @StephaneDelcroix @davidbritch 

### Issues Fixed

Fixes #25947

2024-11-21 08:11 UTC, jsuarezruiz requested changes, later dismissed

2024-11-21 08:11 UTC, jsuarezruiz commented on src/Controls/src/Core/ContentPresenter.cs
> +			SetBinding(
The test **RadioButtonWithValueChangeSelected** is failing on iOS.
![image](https://github.com/user-attachments/assets/7843b5e1-ced6-4d61-87f9-25e4d6cf607e)
Is not rendering the **Content**, the text.
![image](https://github.com/user-attachments/assets/2a7ea9fb-0871-45d8-8590-fef6ea8d6865)

2025-06-05 20:41 UTC, mattleibow commented
Can it handle multiple content presenters at once?

<img width="222" alt="image" src="https://github.com/user-attachments/assets/7c1e9f33-eafb-4e06-a0aa-b0ad6ac12314" />

```xaml

<ContentPage.Resources>
    <ResourceDictionary>
        <Style TargetType="local:MyHeaderedControl">
            <Setter Property="ControlTemplate">
                <Setter.Value>
                    <ControlTemplate>
                        <Grid Padding="5">
                            <Border Padding="10,20,10,10" Stroke="Red" StrokeThickness="2" StrokeShape="RoundRectangle">
                                <ContentPresenter Content="{TemplateBinding Content}" />
                            </Border>
                            <Grid HorizontalOptions="Center" VerticalOptions="Start" Background="Red" Margin="0,-10,0,0" Padding="10,5">
                                <ContentPresenter Content="{TemplateBinding Header}" />
                            </Grid>
                        </Grid>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </ResourceDictionary>
</ContentPage.Resources>

<Grid VerticalOptions="Center" HorizontalOptions="Center">
    <local:MyHeaderedControl WidthRequest="200">
        <local:MyHeaderedControl.Header>
            <Label Text="My Custom Header" FontSize="10" />
        </local:MyHeaderedControl.Header>
        <Label Text="This is the content of the custom control."/>
    </local:MyHeaderedControl>
</Grid>
```

```cs
[ContentProperty(nameof(Content))]
public class MyHeaderedControl : TemplatedView
{
	public static readonly BindableProperty HeaderProperty =
		BindableProperty.Create(nameof(Header), typeof(View), typeof(MyHeaderedControl), default(View));

	public static readonly BindableProperty ContentProperty =
		BindableProperty.Create(nameof(Content), typeof(View), typeof(MyHeaderedControl), default(View));

	public View Header
	{
		get => (View)GetValue(HeaderProperty);
		set => SetValue(HeaderProperty, value);
	}

	public View Content
	{
		get => (View)GetValue(ContentProperty);
		set => SetValue(ContentProperty, value);
	}
}
```

2025-08-04 07:00 UTC, simonrozsival commented
As far as I know there hasn't been a lot of requests for this feature from customers so I am closing the PR. We can always revisit this later.

2025-08-04 07:00 UTC, closed without merging