Fall back to loading .NET 8 date strings
dotnet/maui pull request #26033
Opened 2024-11-21 19:08 UTC by mattleibow

### Description of Change

### Issues Fixed

Fixes #25930

2024-11-21 20:26 UTC, Foda submitted a review, later dismissed

2024-11-22 10:14 UTC, jsuarezruiz approved these changes, later dismissed

2024-11-22 11:04 UTC, bronteq commented on src/Essentials/test/DeviceTests/Tests/Preferences_Tests.cs
> +			// dates were stored as ToString but in .NET 6 they are stored as ToBinary.
no .Net 6 but .Net 9

2024-11-23 03:02 UTC, PureWeen requested changes

2024-11-23 03:02 UTC, PureWeen commented on src/Essentials/test/DeviceTests/Tests/Preferences_Tests.cs
> +			// dates were stored as ToString but in .NET 6 they are stored as ToBinary.
Fix comment

2024-11-24 15:59 UTC, PureWeen approved these changes

2024-11-25 15:57 UTC, jsuarezruiz approved these changes

2024-11-26 10:19 UTC, jfversluis approved these changes

2024-11-26 10:20 UTC, merged