Fix leak on Command Element
dotnet/maui pull request #26044
Opened 2024-11-21 23:47 UTC by pictos

### Description of Change

This PRs make sure that controls that implements `ICommandElement` unsubscribe from `Command.CanExecuteChanged` event avoid the control to leak if the `Command` lives longer than it.

### Issues Fixed

Fixes #16124

2024-11-22 07:13 UTC, jsuarezruiz commented
/azp run

2024-11-25 11:27 UTC, jsuarezruiz requested changes
The build is failing because there are some unit tests not passing:

```
Failed ReenabledAfterCommandRemoved [< 1 ms]
Error Message:
Assert.True() Failure
Expected: True
Actual:   False


Failed RemovedCommandEnablesRefreshView [< 1 ms]
Error Message:
Assert.True() Failure
Expected: True
Actual:   False
```

Could you review it? Let me know if can help with something.

2024-12-14 20:18 UTC, pictos commented on src/Controls/src/Core/CommandElement.cs
> +			ve.Unloaded += OnUnloaded;
safe code to avoid the same control to subscribe the same event more than once. But this will be reworked, this approach will not be used

2025-06-05 20:26 UTC, pictos commented
Closing in favor of #29837 29837

2025-06-05 20:26 UTC, closed without merging