[iOS] Fix ShellContent Title Does Not Update at Runtime
dotnet/maui pull request #26062
Opened 2024-11-22 13:28 UTC by devanathan-vaithiyanathan

### Root cause
The issue occurred because the ShellContent title did not update dynamically in response to property changes. On iOS, real-time updates were not reflected as the Title property changes were not being observed.

### Description of Change

Implemented dynamic title updates for ShellContent by subscribing to the PropertyChanged event. This ensures that any changes to the Title property are observed and updated in real-time, resolving the issue where the title did not reflect updates dynamically.

### Issues Fixed

Fixes #26049 

### Tested the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

2024-11-25 11:05 UTC, jsuarezruiz commented
/azp run

2024-11-29 14:52 UTC, jsuarezruiz commented
/azp run

2025-01-06 10:04 UTC, PureWeen requested changes

2025-01-06 10:04 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs
> +			foreach (var shellContent in ShellSectionController.GetItems())
This isn't going to work when items are added or removed.

When an item is removed or added `OnShellSectionItemsChanged` is called which calls `ReloadData` at which point I think your event subscription here will be out of sync.

2025-01-09 11:39 UTC, devanathan-vaithiyanathan commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs
> +			foreach (var shellContent in ShellSectionController.GetItems())
I have modified the code to address the ShellSection items changes. Please review and let me know

2025-01-10 08:36 UTC, jsuarezruiz commented
/azp run

2025-01-16 10:36 UTC, jsuarezruiz commented
@devanathan-vaithiyanathan Could you fix the conflict? Thanks in advance.

2025-01-16 12:11 UTC, devanathan-vaithiyanathan commented
> @devanathan-vaithiyanathan Could you fix the conflict? Thanks in advance.

 I have resolved the conflicts

2025-01-29 17:17 UTC, PureWeen commented
/rebase

2025-01-29 18:27 UTC, PureWeen requested changes, later dismissed
Can you add a couple scenarios here

- Add a shellcontent dynamically
- you're able to update the title of that new tab
- remove that shellcontent
- you're able to update the title of an exising tab

2025-01-31 12:34 UTC, devanathan-vaithiyanathan commented
> Can you add a couple scenarios here
> 
> * Add a shellcontent dynamically
> * you're able to update the title of that new tab
> * remove that shellcontent
> * you're able to update the title of an exising tab

As per suggestion, I have modified the test. Please let me know if you have any concerns

2025-02-04 14:56 UTC, PureWeen commented
/rebase

2025-02-09 13:39 UTC, PureWeen commented
/azp run

2025-02-12 10:12 UTC, jsuarezruiz requested changes, later dismissed

2025-02-12 10:12 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs
> +		public void VerifyNewlyAddedShellContentTitle()
Pending macOS snapshots. Already available in the latest build:
![image](https://github.com/user-attachments/assets/c2982e7d-f7a9-4e62-aee5-b93f88ee79bc)
Could you commit the images?

2025-02-13 06:22 UTC, devanathan-vaithiyanathan commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs
> +		public void VerifyNewlyAddedShellContentTitle()
I have added mac snapshot. Please let me know if you any concerns

2025-02-13 13:10 UTC, jfversluis commented
/rebase

2025-02-13 13:19 UTC, jfversluis commented
Failing test unrelated

2025-02-13 13:21 UTC, jfversluis approved these changes

2025-02-13 13:21 UTC, merged