[iOS] Fixed Using safe area causes white area at the top upon entry focus
dotnet/maui pull request #26063
Opened 2024-11-22 14:11 UTC by devanathan-vaithiyanathan

### Root Cause
 When an Entry is focused and the keyboard opens, the view adjusts and scrolls downward, causing a white space to appear at the top of the screen.
 
### Description of Change
In the AdjustPosition method,  the move value is calculated when CursorRect.Y is less than topBoundary and CursorRect.Bottom is also less than bottomBoundar, which lead to unnecessary scrollling. To address this, a condition was added to ensure that if the move value is less than 0, it is reset to 0. 

### Issues Fixed

Fixes #25866 

### Validated the behaviour in the following platforms
- [] Android
- [] Windows
- [] iOS
- [x] Mac
  
Issue not reproduced in Android, WinUI and macOS. But ensured the changes with other platforms also

### Output Screenshot
| Before  | After  |
|---------|--------|
|  <img src="https://github.com/user-attachments/assets/65307e15-a48f-44db-90da-a5c31aefa0a2" width="320" height="640" controls></img>   |   <img src="https://github.com/user-attachments/assets/65307e15-a48f-44db-90da-a5c31aefa0a2" width="320" height="640" controls></img>   |

2024-11-22 17:44 UTC, jsuarezruiz commented
/azp run

2024-11-25 15:28 UTC, tj-devel709 requested changes

2024-11-26 13:54 UTC, devanathan-vaithiyanathan commented on src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
> +			}
I'll revisit the implementation and analyze an alternate fix to restrict unnecessary scrolling when the keyboard opens. I'll ensure the behavior accommodates scenarios like ScrollView scrolling into the safe area correctly when required.

2024-12-17 07:05 UTC, devanathan-vaithiyanathan commented on src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
> +			}
I have attempted to utilize the IgnoreSafeArea property as recommended. However, this property is not accessible within KeyboardAutoManagerScroll.cs, which limits its direct application in this context.
I explored using the ShouldIgnoreSafeAreaAdjustment field available in the class. However, this field is consistently returning false, which prevents it from being used effectively to address the described scenario.
Alternatively, is it worth investigating the logic behind the ShouldIgnoreSafeAreaAdjustment field or could you provide me with some other possible insights?

2025-02-26 10:50 UTC, jsuarezruiz requested changes
Could you include an UITest and verify the changes with for example a snapshot?

2025-08-06 22:44 UTC, PureWeen requested changes
@devanathan-vaithiyanathan Can you rebase this to net10.0 and let me know if this PR is still needed?

2025-08-07 09:54 UTC, Dhivya-SF4094 commented
> @devanathan-vaithiyanathan Can you rebase this to net10.0 and let me know if this PR is still needed?

@PureWeen I have rebased the changes to net10.0, and I can confirm that the issue still occurs when SafeAreaEdges="None" is set on the layout. With the fix provided in this PR, the issue is resolved as expected.

2025-10-21 11:38 UTC, jsuarezruiz commented
/rebase

2025-10-21 11:44 UTC, jsuarezruiz requested changes

2025-10-21 11:44 UTC, jsuarezruiz commented on src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
> +			// no need to move the screen down if we can already see the view
The clamping approach (`if (move < 0) { move = 0; }`) treats the symptom rather than the root cause. I think the condition `cursorRect.Y <= topBoundary && cursorRect.Bottom <= bottomBoundary` is too broad, it includes cases where the cursor is fully visible and shouldn't scroll.

2025-10-29 10:57 UTC, Dhivya-SF4094 commented on src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
> +			// no need to move the screen down if we can already see the view
@jsuarezruiz , I have updated the condition to ensure scrolling occurs only when the cursor is partially off-screen. The new check confirms that if the cursor is already fully visible within the screen area no movement is applied.

2025-12-07 23:16 UTC, PureWeen commented
/rebase

2026-01-24 12:05 UTC, kubaflo commented
Hi! It works in NET 10

2026-01-24 12:05 UTC, closed without merging