[Testing] Changes to fix randomly failing tests on CI
dotnet/maui pull request #26096
Opened 2024-11-25 12:37 UTC by jsuarezruiz

### Description of Change

Changes to fix randomly failing tests on CI. The failing tests are:

- GradientImageButtonBackground
- ImageButtonAspectFitWorks

The Pinclude changes to include a new method in the Appium helper to disable system animations. Also, modify the previous tests using the new method and adding a static wait.

2024-11-25 12:42 UTC, jsuarezruiz commented on src/TestUtils/src/UITest.Appium/Actions/AppiumAndroidSpecificActions.cs
> +					ShellHelper.ExecuteAdbCommand($"adb shell settings put global window_animation_scale 0");
Interesting reading: https://medium.com/@begunova/disable-mobile-animations-accelerate-appium-testing-666535939dc7

2024-11-25 23:35 UTC, PureWeen requested changes

2024-11-25 23:35 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24856.cs
> +				Thread.Sleep(1000);
Can we maybe just take the issue changes for this PR? 

VertifyScreenShot already has some code that retries after a delay

Maybe we just add some code into it for Android that tries against after a slightly longer delay. That way the solution is a bit general?

2024-11-27 13:13 UTC, StephaneDelcroix approved these changes

2024-11-28 14:55 UTC, rmarinho approved these changes

2024-11-28 14:55 UTC, merged