25534- Fix for Application crash on setting icon on toolbar item
dotnet/maui pull request #26126
Opened 2024-11-26 11:38 UTC by SuthiYuvaraj

### Root Cause

1. **Root Cause for the Exception**: The crash occurred because the `OnPropertyChanged` event for the `ToolbarItem.IconImageSource` was triggered before the page's handler was created during the second navigation. Initially, on the first navigation, this event fired after the page handler was initialized, allowing the `UpdateIconAndStyle` method to access the MauiContext through `item.FindMauiContext()`. However, after updating the `ToolbarItem.IconImageSource` multiple times, the event sequence changed. On subsequent navigations, the `OnPropertyChanged` event fired before the page handler was created, leaving the ToolbarItem without a valid parent handler. As a result, attempts to access `item.FindMauiContext()` failed, leading to a null reference exception and causing the app to crash.
2. **Cause for the Error** : IIOImageSource:439: *** ERROR: can't open '/path/to/image/sync' (fileExists == false) 
     The sample code used an `.svg` file for the toolbar icon without the correct extension or appropriate handling. Per [.NET MAUI guidelines](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image?view=net-maui-8.0#load-a-font-icon), SVG files are automatically converted to PNG files and must be referenced with a `.png` extension in the project. Using the incorrect extension or without extension caused the app to fail with error.

### Description of Change
To address this issue, a condition was added to the `UpdateIconAndStyle` method to ensure the `ToolbarItem`'s parent handler exists before attempting to access `item.FindMauiContext()`. This additional check prevents the method from executing when the required resources are not yet initialized, avoiding any null reference exceptions. This change ensures that updates to `ToolbarItem.IconImageSource` are safely handled during navigation, maintaining stability and preventing crashes caused by uninitialized platform dependencies.

### Issues Fixed
Fixes #25534 

Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Output Video
Before Issue Fix | After Issue Fix |
|----------|----------|
|<video width="600" height="300" alt="Before Fix video" src="https://github.com/user-attachments/assets/4c1b9a05-334f-4c73-a43c-c1ded130e8ea">|<video width="600" height="300" alt="After Fix video"  src="https://github.com/user-attachments/assets/78637b45-3fa3-49c6-900b-9f4c40e3f6a9" >|

2024-11-26 12:59 UTC, jsuarezruiz commented
/azp run

2024-12-03 05:36 UTC, praveenkumarkarunanithi commented
/rebase

2025-01-06 10:13 UTC, PureWeen requested changes

2025-01-06 10:13 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs
> +				if (item?.IconImageSource == null || item.Parent?.Handler is null)
Does it make sense to set the Image to `null` if the `Parent Handler` is null?

Maybe the check should be added to the else? Or the method should just exit out of `MauiContext` is null?

var mc = item.FindMauiContext()
if (mc is null) return;

2025-01-06 11:22 UTC, praveenkumarkarunanithi commented on src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs
> +				if (item?.IconImageSource == null || item.Parent?.Handler is null)
@PureWeen Thank you for the feedback. I've implemented the changes as suggested, focusing on proper MauiContext handling. The method now checks for a valid context before proceeding with image loading, addressing the concerns about potential null references. Please review and let us know if any further changes are required.

2025-01-07 22:09 UTC, PureWeen commented
/azp run

2025-01-07 22:09 UTC, PureWeen approved these changes

2025-01-08 11:11 UTC, rmarinho approved these changes

2025-01-08 20:54 UTC, PureWeen commented
- failing tests unrelated

2025-01-08 20:54 UTC, merged