Make MauiAppCompatEditText public & adapt EntryHandler
dotnet/maui pull request #26121
Opened 2024-11-26 09:22 UTC by jfversluis

### Description of Change

This change makes `MauiAppCompatEditText` public and makes the necessary changes to the Android `EntryHandler` accordingly.

This was triggered by https://github.com/dotnet/maui/issues/25728 because people had no way to implement the workaround probably because `MauiAppCompatEditText` could not be reached. Also there were a couple of TODOs in code to make this change.

2024-11-26 09:48 UTC, jsuarezruiz requested changes

2024-11-26 09:48 UTC, jsuarezruiz commented on src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
> +Microsoft.Maui.Platform.MauiAppCompatEditText
Build error:

```
D:\a\_work\1\s\src\Core\src\PublicAPI\net-android\PublicAPI.Unshipped.txt(88,1): error RS0025: The symbol 'override Microsoft.Maui.Handlers.BorderHandler.PlatformArrange(Microsoft.Maui.Graphics.Rect rect) -> void' appears more than once in the public API files (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) [D:\a\_work\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-android35.0]
    22 Warning(s)
    1 Error(s)

```

2024-11-26 12:00 UTC, jfversluis commented on src/Core/src/Handlers/Editor/EditorHandler.Android.cs
> +	public partial class EditorHandler : ViewHandler<IEditor, MauiAppCompatEditText>
😩

2024-11-27 03:20 UTC, PureWeen commented on src/Core/src/Handlers/Editor/EditorHandler.Android.cs
> +	public partial class EditorHandler : ViewHandler<IEditor, MauiAppCompatEditText>
We can't change the generic type.

I think the only change here we can look at doing is making `MauiAppCompatEditText` public 

I realize that makes the handler a little confusing :-/ 

But it'll be too breaking to change the generic type

2024-11-27 09:01 UTC, closed without merging