[nuget] Update System.Formats.Asn1
dotnet/maui pull request #26163
Opened 2024-11-27 14:54 UTC by rmarinho

### Description of Change

Update System.Formats.Asn1

### Issues Fixed

Fixes #26162

2024-11-27 15:40 UTC, Redth submitted a review, later dismissed

2024-11-27 16:36 UTC, jsuarezruiz approved these changes, later dismissed

2024-11-27 17:14 UTC, mattleibow requested changes
According to the `Microsoft.Build.Tasks.Core` package, we should not be referencing this package:

https://www.nuget.org/packages/Microsoft.Build.Tasks.Core/17.8.3#readme-body-tab

> This package contains implementations of [commonly-used MSBuild tasks](https://docs.microsoft.com/visualstudio/msbuild/msbuild-task-reference) that ship with MSBuild itself.
> 
> You do not need to reference this package to use these tasks in a build--they are available in any MSBuild environment.
> 
> If you are writing a new task, you may wish to reference [Microsoft.Build.Utilities.Core](https://www.nuget.org/Packages/Microsoft.Build.Utilities.Core) and derive from Microsoft.Build.Utilities.Task or Microsoft.Build.Utilities.ToolTask.


Maybe we can just delete and see if this fixes the issue?

2024-11-27 17:31 UTC, mattleibow commented
Looking at efcore, they only have 2 nugets:

https://github.com/dotnet/efcore/blob/d1e1dfa531dbf2d90df4a42ba71890ed5025dffd/src/EFCore.Tasks/EFCore.Tasks.csproj#L52-L53

And this also does not seem to be needed: https://www.nuget.org/packages/Microsoft.Build

2024-11-28 15:29 UTC, mattleibow approved these changes

2024-11-30 01:27 UTC, merged