[Testing] Added tests to validate the ItemsUpdatingScrollMode property in CarouselView
dotnet/maui pull request #26160
Opened 2024-11-27 14:47 UTC by jsuarezruiz

### Description of Change

Added tests to validate the ItemsUpdatingScrollMode property in CarouselView.

### Issues Fixed

Related with #25991

2024-12-04 10:42 UTC, rmarinho commented
/rebase

2024-12-10 10:38 UTC, rmarinho requested changes
Test is failing in several platforms

2025-01-22 11:48 UTC, jsuarezruiz commented
/rebase

2025-01-30 08:07 UTC, jsuarezruiz commented
The default value for the ItemsUpdatingScrollMode property is KeepItemsInView https://github.com/dotnet/maui/blob/44743aecb383d3a0562096c6524c8c097a1c57c7/src/Controls/src/Core/Items/ItemsUpdatingScrollMode.cs#L7
So, by default, the CarouselView should move the scroll to the first item after add a new one. That happens on Windows, after merge https://github.com/dotnet/maui/commit/c3f42a93976ca2e19f0ff657df6cdb94fc0bcef0

In the added UITest we can validate the behavior with the three enum options:
- KeepItemsInView keeps the first item in the list displayed when new items are added.
- KeepScrollOffset ensures that the current scroll position is maintained when new items are added.
- KeepLastItemInView adjusts the scroll offset to keep the last item in the list displayed when new items are added.

However, as described in the issue, on Android the position is maintained by default. That's wrong. However, more than fix the Windows behavior, seems like it is wrong on other platforms. @Tamilarasan-Paranthaman Could you check the tests results and align/fix the behavior between platforms?

Close in favor of https://github.com/dotnet/maui/pull/26608

2025-01-30 08:07 UTC, closed without merging