Provided description  for "checkboxes", "clear" and "New Task" button
dotnet/maui pull request #26192
Opened 2024-11-28 09:42 UTC by Vignesh-SF3580

### Issue Detail
Some UI elements in the ".NET 9 template" app lack semantic names, impacting screen reader usability.

### Description of Change
Added SemanticProperties.Description to checkboxes, NewTask button, and Clear button

### Issues Fixed
 
Fixes https://github.com/dotnet/maui/issues/26128

2024-11-29 19:33 UTC, rmarinho commented
/azp run

2025-01-06 10:28 UTC, PureWeen requested changes

2025-01-06 10:28 UTC, PureWeen commented on src/Templates/src/templates/maui-mobile/Pages/Controls/AddButton.xaml
> +    SemanticProperties.Description="New Task Button"
If we just set the `Description` to "Add a new task" and then don't supply a "Hint" 

I think that will cover it right?

Same comment goes for the other buttons in this PR

2025-01-06 12:55 UTC, Vignesh-SF3580 commented on src/Templates/src/templates/maui-mobile/Pages/Controls/AddButton.xaml
> +    SemanticProperties.Description="New Task Button"
I've updated the code based on your feedback. Could you please review it and let me know if there are any further concerns

2025-01-06 15:11 UTC, PureWeen commented
/azp run

2025-01-08 12:29 UTC, Vignesh-SF3580 commented
Reported issue was resolved in the following PRs.
https://github.com/dotnet/maui/pull/26920
https://github.com/dotnet/maui/pull/26919
https://github.com/dotnet/maui/pull/26903
https://github.com/dotnet/maui/pull/26921

2025-01-08 12:29 UTC, closed without merging