SelectionLength property update when entry is focused - fix
dotnet/maui pull request #26213
Opened 2024-11-29 01:59 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26158

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/a0b6cebe-7fd4-4705-b32e-81cf3fe34ec7" width="300px"/>|<video src="https://github.com/user-attachments/assets/d77f61e9-f198-4fab-8c18-fdab000f94ce" width="300px"/>|

2024-11-29 19:34 UTC, rmarinho commented
/azp run

2025-01-10 08:11 UTC, jsuarezruiz commented
/rebase

2025-01-10 08:25 UTC, jsuarezruiz commented
/azp run

2025-01-14 17:46 UTC, PureWeen commented
/azp run

2025-01-15 06:53 UTC, jsuarezruiz requested changes
There are several device tests related with the cursor position, selection etc failing:
<img width="358" alt="image" src="https://github.com/user-attachments/assets/60bc6355-bbb9-470b-80e3-653f16f11c6b" />

For example:
<img width="533" alt="image" src="https://github.com/user-attachments/assets/8d2cc961-eed1-4936-89f2-9af1783f3c18" />

2025-01-17 16:55 UTC, kubaflo commented
@jsuarezruiz tests should pass now

2025-02-10 22:20 UTC, PureWeen commented on src/Core/src/Platform/iOS/TextFieldExtensions.cs
> +					CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
Adding dispatching is always a little scary

Let's just be really sure there isn't a different path here before going with this

2025-02-10 23:58 UTC, kubaflo commented on src/Core/src/Platform/iOS/TextFieldExtensions.cs
> +					CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
I was trying to find another way, but I couldn't, and found some related stack overflow issues similar to this one that recommended using this technique

https://stackoverflow.com/questions/29843935/setselection-in-edittexts-onfocuschange
https://stackoverflow.com/questions/1446373/android-listview-setselection-does-not-seem-to-work

2025-02-12 14:38 UTC, sheiksyedm commented
@kubaflo The fix only resolves the issue when clicking the right corner of the Entry without touching the text area. If we click to focus over the text area, the issue still persists. When dynamically updating the Entry's SelectionLength on the focus event, it works as expected without the fix. Please check the video below. I'm not sure if this fix is really needed or if this issue represents a proper use case. 

https://github.com/user-attachments/assets/05d1d43e-f4df-436b-a93f-2d86a7470372

2025-02-19 14:04 UTC, StephaneDelcroix submitted a review, later dismissed

2025-03-03 13:40 UTC, jsuarezruiz commented
/rebase

2025-03-03 19:22 UTC, mattleibow requested changes
The code idea looks good, but the GC and/or manual disposal may break it.

* Maybe check IsAlive first
* Enable tests for Windows/macOS as this is a core feature for all platforms

2025-03-03 19:22 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26158.cs
> +﻿#if ANDROID || IOS
Is there a reason this is not for windows and mac as well?

2025-03-03 19:22 UTC, mattleibow commented on src/Core/src/Platform/Android/EditTextExtensions.cs
> +					editText.Post(() => editText.SetSelection(start, end));
I know this is probably overkill, but maybe this should be:

```suggestion
					editText.Post(() => 
					{
						if (editText.IsAlive())
						{
							editText.SetSelection(start, end);
						}
					);
```

2025-03-03 19:22 UTC, mattleibow commented on src/Core/src/Platform/iOS/TextFieldExtensions.cs
> +					CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
@PureWeen  do we have an `IsAlive` or something similar for iOS? `Window is not null`? `Handle != 0`?

2025-03-03 19:23 UTC, mattleibow commented
@kubaflo any thoughts on the comment by @sheiksyedm ?

2025-03-03 19:23 UTC, mattleibow commented
/azp run

2025-03-03 23:43 UTC, kubaflo commented
> @kubaflo The fix only resolves the issue when clicking the right corner of the Entry without touching the text area. If we click to focus over the text area, the issue still persists. When dynamically updating the Entry's SelectionLength on the focus event, it works as expected without the fix. Please check the video below. I'm not sure if this fix is really needed or if this issue represents a proper use case.
> 
>  Screen.Recording.2025-02-12.at.7.39.46.PM.mov

This is what this PR aims to resolve

2025-03-03 23:49 UTC, kubaflo commented on src/Core/src/Platform/Android/EditTextExtensions.cs
> +					editText.Post(() => editText.SetSelection(start, end));
Sure! Good idea

2025-03-03 23:58 UTC, kubaflo commented
@mattleibow I didn't find any iOS extension so I've simply added
`if (textField is not null && textField.Handle != IntPtr.Zero)`

2025-03-04 00:04 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26158.cs
> +﻿#if ANDROID || IOS
I'm not sure it will work, but let's try

2025-03-06 13:24 UTC, rmarinho commented
/rebase

2025-03-06 13:26 UTC, rmarinho commented
/azp run

2025-03-06 14:10 UTC, rmarinho approved these changes

2025-03-06 17:19 UTC, rmarinho commented
Waiting for screenshots , already have for winui

2025-03-06 17:21 UTC, rmarinho commented
Seems this is a issue on Windows too ..

![SelectionLengthShouldUpdateWhenEntryIsFocused](https://github.com/user-attachments/assets/22e2238a-0fdc-4502-b373-87ff112dfa73)

2025-03-06 18:14 UTC, kubaflo commented
> Seems this is an issue on Windows too .. maybe we need to create a new issue and ignore the test on this platform for now ? Let. s just see what MacCatalyst produces
> 
> ![SelectionLengthShouldUpdateWhenEntryIsFocused](https://private-user-images.githubusercontent.com/1235097/420021681-22e2238a-0fdc-4502-b373-87ff112dfa73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEyODUxMDYsIm5iZiI6MTc0MTI4NDgwNiwicGF0aCI6Ii8xMjM1MDk3LzQyMDAyMTY4MS0yMmUyMjM4YS0wZmRjLTQ1MDItYjM3My04N2ZmMTEyZGZhNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMDZUMTgxMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q0ZjQyNzgxMGY3MGVhMGFmOTg1ZDAxZWU4MGZmMmQ2N2ViNTk4MGQ2OWRjMDJjZTBiOGQ4NDg5ZWI3NDUyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Jzqem6XZIgyTddaNA2jATdzMBp3pTv-7_S_kDmzH9-o)

Yes, I wanted to ignore the test on Catalyst and Windows

2025-03-06 18:14 UTC, rmarinho requested changes
Ok code looks good but we have some issues with tests.

On iOS seems it sometimes the keyboard popups and it fails the test 

![EntrySelectionLengthRuntimeUpdate-diff 1](https://github.com/user-attachments/assets/8f13bb2c-b5c9-4468-bd41-c712dd5e667e)

On Catalyst it seems is not selecting also the text. 

![SelectionLengthShouldUpdateWhenEntryIsFocused 1](https://github.com/user-attachments/assets/dde5a85e-fcc9-425f-bb3d-47239b4cdf65)

on WinUI it also doesn't t , maybe we should create issues for catalyst and win and just fix the test on iOS ?

2025-03-06 18:22 UTC, kubaflo commented
@rmarinho I will have to upload new screenshots because I've added `App.DismissKeyboard();`

2025-03-19 17:09 UTC, rmarinho commented
/azp run

2025-03-19 17:09 UTC, rmarinho submitted a review, later dismissed

2025-04-14 15:50 UTC, rmarinho requested changes

2025-04-14 23:10 UTC, kubaflo commented on src/Core/src/Platform/iOS/TextFieldExtensions.cs
> +						if (textField is not null && textField.Handle != IntPtr.Zero)
Done

2026-03-17 18:50 UTC, kubaflo commented
<!-- AI Summary -->

## 🤖 AI Summary

<!-- SECTION:PR-REVIEW -->
<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/41a8eae7f9c5f23ecd6e061106b8e3bf0b22e5fb"><code>41a8eae</code></a> · <strong>Refactor</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #26158 - SelectionLength Property Not Applied to Entry at Runtime
**PR:** #26213 - SelectionLength property update when entry is focused - fix
**Platforms Affected:** Android, iOS
**Files Changed:** 2 implementation, 4 test

### Key Findings
- The linked issue is verified on Android and reports Android+iOS as affected platforms; the PR adds platform changes in both `src/Core/src/Platform/Android/EditTextExtensions.cs` and `src/Core/src/Platform/iOS/TextFieldExtensions.cs`.
- The PR adds a HostApp issue page plus an Appium UI test for `Issue26158`; the test currently compiles only on Android/iOS and uses `VerifyScreenshot()` after focusing the `Entry`.
- Review discussion repeatedly questioned the dispatch/post-based fix timing and disposal safety, especially on iOS; Android was updated to use `editText.Post(...)` guarded by `editText.IsAlive()`.
- PR discussion also notes screenshot/test instability on non-target platforms (Windows/MacCatalyst) and a keyboard-related screenshot issue on iOS; those concerns remain part of the review context even though Android is the requested validation platform.
- No prior agent review output was found in PR comments.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #26213 | Defer selection updates until after focus using platform-specific async dispatch/post logic, and add an issue UI test with screenshots | ⏳ PENDING (Gate) | `src/Core/src/Platform/Android/EditTextExtensions.cs`, `src/Core/src/Platform/iOS/TextFieldExtensions.cs`, `src/Controls/tests/TestCases.HostApp/Issues/Issue26158.cs`, `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26158.cs` | Original PR |

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ❌ FAILED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ❌

**Notes:** The added `Issue26158` UI test reproduces the bug on Android, but it still fails with the PR's current fix applied. Verification artifacts are under `CustomAgentLogsTmp/PRState/26213/PRAgent/gate/verify-tests-fail/`.

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| 1 | try-fix | Reapply selection from Android focus lifecycle in `EntryHandler.Android.cs`, suppressing `OnSelectionChanged` while focus settles | ❌ FAIL | 1 file | Visual behavior reportedly correct, but screenshot diff still failed due to environmental chrome noise |
| 2 | try-fix | On Android focus gain, capture cursor/selection values and use `PostDelayed(100ms)` in `EntryHandler.Android.cs` to reapply them after touch-up completes | ✅ PASS | 1 code file + 1 snapshot | Small Android-only handler change, but relies on a fixed delay |
| 3 | try-fix | Arm a one-shot restore on focus and reapply selection from `OnSelectionChanged` once if Android drifts the caret | ❌ FAIL | 1 file | Simpler than attempt 2, but still hit the same screenshot diff failure |
| 4 | try-fix | Use a one-shot `OnPreDrawListener` to restore selection just before the next frame after focus gain | ✅ PASS | 1 code file + 1 snapshot | Event-driven and deterministic; no magic delay or API churn |
| 5 | try-fix | Event-driven `ACTION_UP` interception in Android touch handling to consume/reapply the focus-time selection without delay timers | ❌ FAIL | 1 file | Distinct touch-path fix, but still ended with the same screenshot diff failure |
| 6 | try-fix | Track desired selection in `MauiAppCompatEditText` and synchronously restore it in subclass `OnFocusChanged` and `OnTouchEvent(ACTION_UP)` | ✅ PASS | 2 code files + PublicAPI + 1 snapshot | Robust but significantly more invasive and introduces API-surface churn |
| PR | PR #26213 | Defer Android selection update via `editText.Post(SetSelection)` in `EditTextExtensions`, plus analogous iOS dispatch change and issue UI test | ❌ FAILED (Gate) | 4 code files + snapshots | Gate proved the added Android test still fails with the PR fix |

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-opus-4.6 | 1 | Yes | Consume or ignore the first touch-driven cursor move after focus in the EditText subclass |
| claude-sonnet-4.6 | 1 | Yes | Override `OnTouchEvent` and synchronously reapply selection on `Action.Up` after native processing |
| gpt-5.3-codex | 1 | Yes | Arm a pending-selection flag and queue reapply specifically from the `ACTION_UP` event |
| gemini-3-pro-preview | 1 | Yes | Override touch handling to skip the focus-gaining `ACTION_UP` cursor placement entirely |
| claude-opus-4.6 | 2 | Yes | Preserve selection at source using `SetTextKeepState` or equivalent handler path |
| claude-sonnet-4.6 | 2 | Yes | Override focus handling synchronously in the Android text subclass |
| gpt-5.3-codex | 2 | Yes | IME/input-connection interception idea |
| gemini-3-pro-preview | 2 | No | No new ideas beyond delayed/event-driven family |
| claude-opus-4.6 | 3 | Yes | Filter/coerce initial IME `setSelection` calls after focus gain |
| claude-sonnet-4.6 | 3 | Yes | Set `EditorInfo.initialSelStart/initialSelEnd` in `OnCreateInputConnection` |
| gpt-5.3-codex | 3 | Yes | Custom `InputConnection` wrapper to intercept IME selection resets |
| gemini-3-pro-preview | 3 | No | No new ideas; recommends Attempt 4 as cleanest |

**Exhausted:** Yes — max 3 cross-pollination rounds completed; remaining proposals are narrower IME-hook variants of the same Android reset race.
**Selected Fix:** Candidate #4 — it passes the Android verification, is simpler than Candidate #6, avoids the arbitrary timer used by Candidate #2, and does not require public API changes.

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

## ⚠️ Final Recommendation: REQUEST CHANGES

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight | ✅ COMPLETE | Issue #26158 and PR/test context gathered; Android chosen per request and affected-platform scope |
| Gate | ❌ FAILED | Android verification showed the new issue test fails both without the fix and with the PR fix |
| Try-Fix | ✅ COMPLETE | 6 attempts run, 3 passing alternatives found, 3 cross-pollination rounds completed |
| Report | ✅ COMPLETE | |

### Summary
The PR should not be approved as-is for Android review. The added `Issue26158` test does reproduce the bug on Android, but the PR's current Android fix in `EditTextExtensions.UpdateCursorSelection` still leaves the test failing during full verification. That makes the gate fail.

The try-fix phase found multiple alternatives that outperform the PR on Android. The best candidate was an Android-only handler change that restores selection via a one-shot `OnPreDrawListener` immediately before the next frame after focus gain. That approach passed Android verification, is simpler than subclass-level synchronization, and avoids the arbitrary `100ms` delay needed by another passing alternative.

### Root Cause
Android resets or repositions the caret after the MAUI `Focused` event has already set `CursorPosition` and `SelectionLength`. The PR's current `editText.Post(SetSelection)` runs too early in that lifecycle, so a later Android focus/touch reset still wins and the selection is lost from the screenshot-verified state.

### Fix Quality
The current PR fix is insufficient for Android b [...]

2026-03-19 17:08 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-20 12:44 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-20 23:31 UTC, merged