[Android] Gradient background with ImageButton
dotnet/maui pull request #26297
Opened 2024-12-01 18:40 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23119

```
<ImageButton
        AutomationId="imageButton"
        WidthRequest="100"
        HeightRequest="100"
        HorizontalOptions="Center">
        <ImageButton.Background>
                <RadialGradientBrush
                        Center="0.5,0.5"
                        Radius="0.5">
                        <GradientStop
                                Color="green"
                                Offset="0.0"/>
                        <GradientStop
                                Color="red"
                                Offset="1.0"/>
                </RadialGradientBrush>
        </ImageButton.Background>
</ImageButton>
```

|Before|After|
|--|--|
|<img src="https://github.com/user-attachments/assets/66171b54-a411-401a-9328-22cdcbc7e1e9" width="300px"/>|<img src="https://github.com/user-attachments/assets/d5b02c8b-f0eb-40ae-9605-e0ea1b6a9394" width="300px"/>|

2025-01-10 08:11 UTC, jsuarezruiz commented
/rebase

2025-01-10 08:25 UTC, jsuarezruiz commented
/azp run

2025-01-10 08:29 UTC, jsuarezruiz requested changes, later dismissed

2025-01-10 08:29 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23119.cs
> +			VerifyScreenshot();
Could you commit the pending snapshots for the test?, Build is running, could use the build tests results to get them.

2025-01-10 18:48 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23119.cs
> +			VerifyScreenshot();
Done :)

2025-08-07 14:45 UTC, jfversluis commented
/azp run

2025-08-07 14:50 UTC, jfversluis approved these changes

2025-08-11 07:58 UTC, jfversluis requested changes
Still see a relevant test failure

> VisualTestUtils.VisualTestFailedException :
Snapshot different than baseline: GradientBackgroundShouldWorkWithImageButton.png (size differs - baseline is 1920x1080 pixels, actual is 789x563 pixels)
If the correct baseline has changed (this isn't a a bug), then update the baseline image.
See test attachment or download the build artifacts to get the new snapshot file.

2025-08-12 09:28 UTC, jfversluis approved these changes

2025-08-12 09:28 UTC, merged