Navigation from the 'more' tab
dotnet/maui pull request #26292
Opened 2024-12-01 13:37 UTC by kubaflo

Along with this @albyrock87's PR: https://github.com/dotnet/maui/pull/22574, the shell navigation should be flawless :)

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26165
Fixes https://github.com/dotnet/maui/issues/18193

2024-12-02 08:31 UTC, jfversluis commented
/azp run

2024-12-03 19:14 UTC, PureWeen commented
/rebase

2024-12-16 11:51 UTC, jfversluis requested changes
Tests failing for this one!

2024-12-16 21:03 UTC, PureWeen commented
/rebase

2024-12-16 21:04 UTC, PureWeen commented
/azp run

2025-01-06 20:34 UTC, PureWeen requested changes

2025-01-06 20:34 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +		public void ShellNavigationShouldWorkInMoreTab()
Looks like this test is failing on catalyst

2025-01-07 14:06 UTC, kubaflo commented
@PureWeen can we try again. The strange thing is that it passes locally though🤔
<img width="341" alt="Screenshot 2025-01-07 at 14 59 56" src="https://github.com/user-attachments/assets/5365b9bf-249b-45d0-a16c-1fbb0a26459c" />

I've also modified the other test

2025-01-07 16:51 UTC, PureWeen commented
/azp run

2025-01-08 00:04 UTC, PureWeen commented
/azp run

2025-01-10 07:04 UTC, mattleibow reviewed
Mostly just a question on how Apple did/recommended navigation from the More tab and then also, is the More tab on any other platform?

2025-01-10 07:04 UTC, mattleibow commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
> +				tabBarController.MoreNavigationController.PushViewController(viewController, animated);
Is pushing from the more tab a typical iOS thing? I have not been able to find an Apple app that does the more button, so I am not sure. In my mind the More tab is like a popup, but I suppose it does not look like it. However, since I have no idea what it is supposed to look like.

But, I am also not sure it really matters as the More tab is frowned upon so you should not be using it.

2025-01-10 07:04 UTC, mattleibow commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
> +				base.PushViewController(viewController, animated);
```suggestion
			{
				base.PushViewController(viewController, animated);
			}
```

2025-01-10 07:04 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +		public void ShellNavigationShouldWorkInMoreTab()
Does Mac Catalyst have a more tab?

2025-01-10 07:04 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6784.cs
> +#if IOS || MACCATALYST
Does the More tab exist on any other OS other than an iOS on an iPhone? Does it happen on iPad? Mac Catalyst? If it is just iOS, then we can maybe restrict this test to just be iOS.

2025-01-10 11:05 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +			App.Click("NavigationToPage6Button");
Here, could navigate back and use VerifyScreenshot to validate the "More" menu. 
![image](https://github.com/user-attachments/assets/44395d42-1b14-4e26-becf-27807a3c5021)
Then, navigate again to the Page 6 and continue testing, navigating to the detail page and Page 2.

2025-01-11 12:12 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6784.cs
> +#if IOS || MACCATALYST
Android also has something similar to the 'more' tab, but it behaves a bit differently

2025-01-11 12:14 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +		public void ShellNavigationShouldWorkInMoreTab()
It has, but it fails in pipelines, even though it works locally :/ Therefore, I've disabled it

2025-01-11 12:22 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +		public void ShellNavigationShouldWorkInMoreTab()
https://github.com/user-attachments/assets/a27baf55-8de7-402c-9756-3f0d05235ef1

2025-01-15 17:49 UTC, mattleibow approved these changes

2025-01-15 17:50 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +		public void ShellNavigationShouldWorkInMoreTab()
Can you open a new issue saying that you disabled the test so we can investigate later?

2025-01-15 17:51 UTC, mattleibow requested changes
Javier's comment on adding a test for the actual more tab is good. We need to make sure that navigating using links and then back should also work.

2025-01-15 23:56 UTC, kubaflo commented
@mattleibow @mattleibow I've extended the UiTest

2025-01-16 19:36 UTC, PureWeen commented
/azp run

2025-01-17 14:17 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
> +		public void ShellNavigationShouldWorkInMoreTab()
Made an issue: https://github.com/dotnet/maui/issues/27206

2025-01-17 14:19 UTC, mattleibow commented
I created an issue with a task to re-enable these tests on Mac Catalyst when we get a chance : https://github.com/dotnet/maui/issues/27206

2025-01-17 15:06 UTC, kubaflo commented
> FYI: I created an issue with a task to re-enable these tests on Mac Catalyst when we get a chance : #27206

Thanks!

2025-01-20 07:56 UTC, anandhan-rajagopal commented
> FYI: I created an issue with a task to re-enable these tests on Mac Catalyst when we get a chance : #27206

@mattleibow & @kubaflo  I have gone through the test cases and observed that there are multiple click actions, with each click leading to a new page, requiring further interaction with the elements on those pages. I suggest that we could wait for the elements to before executing any click actions. This might be successful in Catalyst and avoid flakiness in CI.

![image](https://github.com/user-attachments/assets/e9e27415-a8e0-4e35-adf7-ee1fee6bdcaa)

2025-01-20 11:39 UTC, kubaflo commented
> > FYI: I created an issue with a task to re-enable these tests on Mac Catalyst when we get a chance : #27206
> 
> @mattleibow & @kubaflo I have gone through the test cases and observed that there are multiple click actions, with each click leading to a new page, requiring further interaction with the elements on those pages. I suggest that we could wait for the elements to before executing any click actions. This might be successful in Catalyst and avoid flakiness in CI.
> 
> ![image](https://private-user-images.githubusercontent.com/97146406/404786161-e9e27415-a8e0-4e35-adf7-ee1fee6bdcaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczNzMyNTAsIm5iZiI6MTczNzM3Mjk1MCwicGF0aCI6Ii85NzE0NjQwNi80MDQ3ODYxNjEtZTllMjc0MTUtYThlMC00ZTM1LWFkZjctZWUxZmVlNmJkY2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIwVDExMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNGQ2ZGU3N2ZjMDU1NzU5YWJjODI2MjEwNTJlNGY1NzEzODMyNmYzODU0YjE1YTRiNWNmZWQ2MWM2NDE0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eOaivYw3blHPGi3CGmNMaB_l-0fLaEm_i8Co7OihH84)

Okay, thanks! I've added a commit🤞

2025-01-21 18:58 UTC, PureWeen commented
/azp run

2025-01-23 15:55 UTC, mattleibow approved these changes, later dismissed

2025-01-23 21:38 UTC, PureWeen requested changes
ShellNavigationShouldWorkInMoreTab failing on iOS

2025-01-24 15:42 UTC, PureWeen commented
/azp run

2025-01-28 00:26 UTC, PureWeen approved these changes

2025-01-28 12:26 UTC, merged