[iOS] GraphicsView DrawString - fix
dotnet/maui pull request #26304
Opened 2024-12-02 15:00 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24450
Fixes https://github.com/dotnet/maui/issues/8486
Fixes https://github.com/dotnet/maui/issues/4993

|Before|After|
|--|--|
|<img src="https://github.com/user-attachments/assets/c7fc942b-4f51-4892-8756-5bd09ae5a74d" width="300px"/>|<img src="https://github.com/user-attachments/assets/8d9f9144-9144-4585-9786-9ffa8033363e" width="300px"/>|

2024-12-03 10:18 UTC, jfversluis requested changes
Can you rebase this one for the new GraphicsView category?

2024-12-03 10:38 UTC, kubaflo commented
> Can you rebase this one for the new GraphicsView category?

Sure thing!

2024-12-03 10:40 UTC, jfversluis commented
/azp run

2025-01-10 08:10 UTC, jsuarezruiz commented
/rebase

2025-01-10 08:19 UTC, jsuarezruiz requested changes

2025-01-10 08:19 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.HostApp/Issues/Issue8486.cs
> +				canvas.DrawString("GraphicsText", dirtyRect.Left + dirtyRect.Width / 2, dirtyRect.Top + dirtyRect.Height / 2, HorizontalAlignment.Left);
Could you update the test to include multiple strings using all the different **HorizontalAlignment** options?

2025-01-10 18:40 UTC, kubaflo commented on src/Controls/tests/TestCases.HostApp/Issues/Issue8486.cs
> +				canvas.DrawString("GraphicsText", dirtyRect.Left + dirtyRect.Width / 2, dirtyRect.Top + dirtyRect.Height / 2, HorizontalAlignment.Left);
No problem! Done :)

2025-01-17 08:35 UTC, riccardominato commented
@kubaflo Thank you for this PR!

Since looking at the commits I've noticed `GetStringSize()` is used, I would like to point out https://github.com/dotnet/maui/issues/18679.
Don't know it the issue is applies to this PR, but maybe it's worth a check.

2025-02-26 11:29 UTC, rokmeglic71 commented
@Eilon  and @StephaneDelcroix please let me know what needs to be done here to make a step forward with this? Thank you for your time and effort.

2025-03-17 11:00 UTC, riccardominato commented
Unfortunately I can't test personally this PR, so sorry if I ask you to check.
Since the same issue currently happens using `ICanvas.DrawText()`, does this PR solve the bug also for this method?

2025-07-22 06:22 UTC, ghost commented
Until this fix is done, please find [workaround here](https://github.com/dotnet/maui/issues/4993#issuecomment-3101239999).

2026-03-09 15:56 UTC, kubaflo commented
/azp run

2026-03-09 16:19 UTC, kubaflo commented
/azp run

2026-03-09 23:01 UTC, kubaflo commented
<!-- AI Summary -->

## 🤖 AI Summary

<!-- SECTION:PR-REVIEW -->
<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update PlatformCanvas.cs</strong> · <a href="https://github.com/dotnet/maui/commit/e21d2f41ce08e029a4e2db825e236b05e0c02252"><code>e21d2f4</code></a></summary>

---

**PR:** #26304 - [iOS] GraphicsView DrawString - fix
**Author:** kubaflo (Jakub  Community ContributorFlorkowski) 
**Platforms Affected:** iOS, macOS/MacCatalyst (labels: `platform/ios`, `area-drawing`)
**Files Changed:** 1 implementation file, 2 test files, 4 snapshot images
**Current HEAD:** e21d2f41 (new commit since prior review)

### Issues Fixed
- #8486 - GraphicsView DrawString not rendering in iOS
- #24450 - DrawString not rendering in iOS
- #4993 - DrawString doesn't work on macCatalyst

### Problem Description
`ICanvas.DrawString(value, x, y, horizontalAlignment)` was silently failing to render text on iOS and macOS/MacCatalyst. Android was unaffected. The old code called the deprecated `CGContext.ShowTextAtPoint` API, which had known rendering issues on Apple platforms.

### Prior Agent Review (on commit 208bae3)
- **Pre-Flight COMPLETE**: 
- **Gate PASSED (ios)**: 
- **Fix  Selected PR's fix with recommended improvementsCOMPLETE **: 
- ** REQUEST  Resource management issues foundCHANGES Report**: 

### Author Response (commit  "Update PlatformCanvas.cs")e21d2f41 
The author addressed the resource management issues from the prior review:
-  Fixed: CTFont now created directly via `_font?.ToCTFont(_fontSize) ?? FontExtensions.GetDefaultCTFont(_fontSize)` (no intermediate CGFont leak)
-  Fixed: CTFont now properly disposed via `using var font = ...`
-  Fixed: NSAttributedString now properly disposed via `using var attributedString = ...`

### File Classification
| File | Type |
|------|------|
| `src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs` | Fix |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue8486.cs` | Test (HostApp) |
| `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8486.cs` | Test (NUnit) |
| Snapshot images (ios, ios-26, android, mac) | Test baselines |

### Remaining Open Issues
| File:Line | Concern | Status |
|-----------|---------|--------|
| `Issue8486.cs:4` | `PlatformAffected.iOS` should be `PlatformAffected.iOS \| PlatformAffected.MacCatalyst` since fix is in shared MaciOS  OPEN |code | 
| PR comments (riccardominato) | Other `DrawString` overloads and `DrawText` may have similar issues with bounding rect from `canvas.GetStringSize()` | 
### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #26304 | Replace deprecated `ShowTextAtPoint` with `CTLine`/`NSAttributedString` CoreText rendering; proper resource disposal via `   PENDING (Gate) | `PlatformCanvas.cs` (+10/-19 net in latest state) | Original  improved after prior review |PR using` |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update PlatformCanvas.cs</strong> · <a href="https://github.com/dotnet/maui/commit/e21d2f41ce08e029a4e2db825e236b05e0c02252"><code>e21d2f4</code></a></summary>

---

**Result PASSED:** 
**Platform:** ios
**Mode:** Full Verification (RequireFullVerification: true)

- Tests FAIL without fix (bug confirmed present when fix reverted) 
- Tests PASS with fix (fix confirmed working) 

**Test:** `DrawStringShouldDrawText` in `Issue8486`
**Merge Base:** 6c123d72
**Current HEAD:** e21d2f41 ("Update PlatformCanvas. resource disposal improvements)cs" 

The Gate confirms the latest commit (e21d2f41) still passes: resource disposal improvements did not break the fix.

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update PlatformCanvas.cs</strong> · <a href="https://github.com/dotnet/maui/commit/e21d2f41ce08e029a4e2db825e236b05e0c02252"><code>e21d2f4</code></a></summary>

---

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| A (prior) | try-fix | UIKit NSAttributedString.DrawString(CGPoint) via UIGraphics.PushContext PASS | `PlatformCanvas.cs` | Requires platform #if  more complex |branching  | 
 CTLine + TextMatrix PASS | `PlatformCanvas.cs` | Unnecessary CTTypesetter wrapping | | 
| C (prior) | try-fix | CTFramesetter path (DrawStringInPlatformPath  FAIL | `PlatformCanvas.cs` | 6.42% visual  alignment mismatch |diff routing) | 
| D (prior) | try-fix | Offscreen CGBitmapContext  FAIL | `PlatformCanvas.cs` | 7-8% visual  antialiasing mismatch |diff blit | 
| 1 | try-fix (claude-sonnet-4.6) | CTFont Glyph-Path Fill via GetPathForGlyph per  FAIL | `PlatformCanvas.cs` | 3.67% visual  non-CTLine antialiasing |diff character | 
| 2 | try-fix (claude-opus-4.6) | CTLine + SaveState + CTM TranslateCTM+ScaleCTM PASS | `PlatformCanvas.cs` | Clean isolation; slightly more code | | 
| 3 | try-fix (gpt-5.2) | CTLine + TextPosition + FlipTransform + SaveState/RestoreState PASS | `PlatformCanvas.cs` | Uses existing FlipTransform; more explicit state | | 
| 4 | try-fix (gpt-5.3-codex) | CTLine + TextPosition + FlipTransform (no SaveState PASS | `PlatformCanvas.cs` | Minimal diff vs PR; TextMatrix not used for position |) | 
| 5 | try-fix (gemini-3-pro-preview) | CTLine + SaveState + FlipTransform with Tx/Ty mutation PASS | `PlatformCanvas.cs` | Reuses FlipTransform field; state isolated | | 
| 6 | try-fix (claude-sonnet-4.6) | CTLine unified: GetTypographicBounds() for alignment, no private DrawString PASS | `PlatformCanvas.cs` | 5.94% diff vs existing PR  snapshot regen required |snapshots  | 
| PR | PR #26304 | CTLine + TextMatrix(1,0,0,-1,x,y) + proper  disposal for font/attributedString/textLine PASS (Gate) | `PlatformCanvas.cs` (+10/-19) | Original  resource leaks fixed in commit e21d2f41 |PR  | 

### Cross-Pollination Summary

| Round | Model | Response |
|-------|-------|----------|
 Ran as Attempt 6 |
| 2 | claude-opus-4.6 | NO NEW IDEAS |
| 2 | gpt-5.2 | NEW IDEA: Explicit font rendering flags (not a bug fix) |
| 2 | gpt-5.3-codex | NEW IDEA: Pixel-snapping (minor refinement, not tested) |
| 2 | gemini-3-pro-preview | NEW IDEA: TextKit/NSLayoutManager (far too complex) |
| 3 | claude-sonnet-4.6 | NEW IDEA: UIGraphics.PushContext (already done as Attempt A) |
| 3 | claude-opus-4.6 | NO NEW IDEAS |
| 3 | gpt-5.2 | NEW IDEA: CGContext rendering flags (not a bug fix) |
| 3 | gpt-5.3-codex | NO NEW IDEAS |
| 3 | gemini-3-pro-preview | NO NEW IDEAS |

**Exhausted:** Yes (max 3 rounds reached; remaining "new ideas" are either already tried or refinements/non-fixes)

**Key Finding:** Only CTLine.Draw()-based approaches produce pixel-identical output to baseline snapshots. All non-CTLine methods (glyph path fill, CTFramesetter, CGBitmapContext) produce 3-8% visual diffs due to antialiasing differences. Among CTLine variants, the PR's approach (TextMatrix encoding position+flip) is the minimal, clean solution.

**Selected Fix:** PR's  Correct and minimal; resource leaks already addressed by author in commit e21d2f41fix 

**Rationale:** The PR's approach is the minimal correct implementation: CTLine.Draw() with a single TextMatrix that encodes both the Y-flip and translation. All resource objects are properly disposed via `using var`. Attempt 6 (GetTypographicBounds) is a valid refinement but requires regenerating all 4 snapshot images due to sub-pixel metric differences between UIFont (used by GetStringSize) and CTFont (used by GetTypographicBounds). This additional churn is not justified given the PR already passes.

</details>

</details>

---

 [...]

2026-03-10 11:38 UTC, merged