Fix 26091
dotnet/maui pull request #26326
Opened 2024-12-03 07:43 UTC by Tamilarasan-Paranthaman

### Root Cause of the issue 

- The UITableViewCell was not returned correctly when retrieving the cell from GetPlatformCell. When adding a new row at runtime, the virtual view for the new cell was correctly updated, and the platform view was properly created. However, the handler was not assigned correctly for an already reused cell. For the existing cell, the handler had an incorrect platform view as it retained the platform view of a previously reused cell(ContextActions). This resulted in the previous platform view being incorrectly assigned as the `UITableViewCell`.
 

### Description of Change

-  I retrieved the `platformCell` using the `renderer.GetCell` method, based on the `reusableCell` and `cell`, instead of obtaining the platform view directly from the renderer.

### Issues Fixed

Fixes #26091

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="500"  src="https://github.com/user-attachments/assets/f41f6fcf-cd76-467f-8c6d-609c7f06abd5"> | <video width="300" height="500"  src="https://github.com/user-attachments/assets/24e79a8e-e255-4f08-94a6-1926b667908b"> |

2024-12-03 11:15 UTC, jfversluis commented
/azp run

2025-01-10 08:10 UTC, jsuarezruiz commented
/rebase

2025-01-10 08:15 UTC, jsuarezruiz commented
/azp run

2025-01-16 11:23 UTC, rmarinho commented
/azp run

2025-01-31 11:41 UTC, jsuarezruiz commented
/rebase

2025-02-05 12:08 UTC, jsuarezruiz commented
/azp run

2025-02-24 16:33 UTC, jsuarezruiz commented
/rebase

2025-02-26 08:43 UTC, jsuarezruiz commented
/azp run

2025-02-26 10:42 UTC, jsuarezruiz requested changes

2025-02-26 10:42 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/DynamicallyAddingTableViewCells.png
Requires to update the Catalyst snapshot (changed the resolution, because before the snapshot was from a full screen app mode, and not just the window size).

2025-02-26 10:42 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/CellTableViewCell.cs
> +			UITableViewCell platformCell;
Could simplify it in a single line:

`var platformCell = cell is not ViewCell ? renderer.GetCell(cell, reusableCell, tableView) : renderer.PlatformView;`

2025-02-27 12:54 UTC, Tamilarasan-Paranthaman commented on src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/CellTableViewCell.cs
> +			UITableViewCell platformCell;
@jsuarezruiz, I have made the changes as suggested

2025-03-07 11:59 UTC, jsuarezruiz commented
/rebase

2025-06-09 07:29 UTC, jsuarezruiz commented
/rebase

2025-06-13 11:28 UTC, jsuarezruiz commented
/rebase

2025-08-16 14:37 UTC, PureWeen commented
As we obsolete ListView in .NET 10, we'll no longer be accepting PRs for ListView so we can stay focused on CollectionView and ensuring it meets and exceeds everyone's needs.

2025-08-16 14:37 UTC, closed without merging