Update SkiaSharp
dotnet/maui pull request #26373
Opened 2024-12-04 19:50 UTC by mattleibow

### Description of Change

This PR updates SkiaSharp to the latest stable version.

The code is mostly the same, however there are some obsolete things that we may have to use for now as doing it correctly will have breaking changes in the `Microsoft.Maui.Graphics.Skia` NuGet API.

The change is the fact that in SkiaSharp v2.x, there was just a single `SKPaint` object that was used for paint/color/appearance AND font/text rendering. In the new SkiaSharp v3.x, this has been split into `SKPaint` and `SKFont` objects. Unfortunately, these types leaked out of a few MAUI types and thus changing it would force us to now expose a new `SKFont` argument in methods and return types of properties/methods.

This may be acceptable though since these types are semi-implementation details and typically are not used directly, but are used via the abstract types. 

Fixes #26099

2024-12-04 20:05 UTC, mattleibow commented
If the ABI breaks are acceptable, I can do it in this PR or in a separate one.

2025-02-15 00:33 UTC, PureWeen commented
@mattleibow is it concerning at all that the border on the regenerated images is different?

![image](https://github.com/user-attachments/assets/5fdcf2f5-7e09-44b0-ade5-385c5c4e5641)

2025-02-15 12:24 UTC, mattleibow commented
The red to green border? That is the github added and removed preview border. The images have no border.

Unless you see another border being added/removed in the actual image?

2025-02-15 19:00 UTC, PureWeen commented
> The red to green border? That is the github added and removed preview border. The images have no border.
> 
> Unless you see another border being added/removed in the actual image?

aw yea, derp
I was just curious what the diff is on these 500 images that my human eye can't see

![image](https://github.com/user-attachments/assets/500ce363-83bc-45c3-8860-95c57bd072f0)

2025-02-18 19:26 UTC, PureWeen commented on src/Graphics/src/Graphics.Skia/SkiaCanvasState.cs
> +		public SKFont FontFont
Some additional possible suggestions?

TextAttributes
SKFont
FontConfiguration
FontAttributes
FontDetails

2025-02-19 14:02 UTC, StephaneDelcroix approved these changes

2025-02-19 20:52 UTC, PureWeen requested changes
https://github.com/dotnet/maui/pull/26373#discussion_r1960442003

2025-02-24 15:03 UTC, jsuarezruiz approved these changes

2025-03-03 15:19 UTC, PureWeen approved these changes

2025-03-03 15:20 UTC, merged