Fix for UI not updating GridItemsLayout when Span becomes 1.
dotnet/maui pull request #26370
Opened 2024-12-04 16:11 UTC by BagavathiPerumal

### Root cause

The issue was caused because the ItemsWrapGrid size was not updated correctly when attempting to change the CollectionView item size. Additionally, the SizeChanged event for the ItemsWrapGrid was not triggered when the CollectionView size was reduced, resulting in the items inside the CollectionView not being resized properly during the resizing of the CollectionView.

### Description of Issue Fix

The fix involves adding a SizeChanged event to the FormsGridView and invoking the UpdateItemSize() method within this event to dynamically adjust the ItemsWrapGrid dimensions. This method ensures that the ItemsWrapGrid.ItemWidth and ItemHeight are set based on the FormsGridView.ActualWidth and FormsGridView.ActualHeight, allowing the ItemsWrapGrid to resize appropriately in sync with the CollectionView size changes.

Tested the behavior in the following platforms.
 
- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26083

### Output

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/90052d87-6902-4005-8dae-53d124edcd37"> | <video width="270" height="600"  src="https://github.com/user-attachments/assets/9dfea44c-0703-4bcb-82e3-eec4dcd3cd8e"> |

2024-12-04 17:14 UTC, kubaflo commented on src/Controls/src/Core/Platform/Windows/CollectionView/FormsGridView.cs
> +			SizeChanged += FormsGridView_SizeChanged;
Hi, I wonder if you could unsubscribe from this event somewhere?

2024-12-07 16:01 UTC, rmarinho commented
/azp run

2024-12-11 16:51 UTC, PureWeen commented
/azp run

2024-12-20 11:50 UTC, rmarinho commented
/azp run

2025-01-14 12:06 UTC, jsuarezruiz commented
/rebase

2025-01-30 20:47 UTC, Foda commented
/rebase

2025-01-31 12:28 UTC, jsuarezruiz commented
/azp run

2025-02-25 09:48 UTC, jsuarezruiz commented
/rebase

2025-02-26 08:43 UTC, jsuarezruiz commented
/azp run

2025-02-26 10:37 UTC, jsuarezruiz requested changes

2025-02-26 10:37 UTC, jsuarezruiz commented on src/Controls/src/Core/Platform/Windows/CollectionView/FormsGridView.cs
>  			_wrapGrid.MaximumRowsOrColumns = Span;
With the changes, I would include a validation if `_wrapGrid` is not null here.

2025-02-26 10:37 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26083.cs
> +			App.Tap("Button");
Not mandatory, but could be interesting to verify a snapshot before tap the button and change the Span property.

2025-02-26 10:37 UTC, jsuarezruiz commented on src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
> +			gridView.SizeChanged += OnGridViewSizeChanged;
Did you find the cause of why the SizeChanged event for the ItemsWrapGrid is not triggered when the CollectionView size is reduced? https://github.com/dotnet/maui/blob/48f19fd1435962119713ff1a8a87f05e0ad2c227/src/Controls/src/Core/Platform/Windows/CollectionView/FormsGridView.cs#L96

2025-03-04 09:21 UTC, BagavathiPerumal commented on src/Controls/src/Core/Platform/Windows/CollectionView/FormsGridView.cs
>  			_wrapGrid.MaximumRowsOrColumns = Span;
@jsuarezruiz, As suggested, I have added the null check condition for _WrapGrid.

2025-03-12 10:04 UTC, jsuarezruiz commented
/rebase

2025-03-12 10:06 UTC, jsuarezruiz commented
/azp run

2025-03-14 05:42 UTC, BagavathiPerumal commented on src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
> +			gridView.SizeChanged += OnGridViewSizeChanged;
@jsuarezruiz, This issue is replicated in native WinUI itself. The SizeChanged event of ItemsWrapGrid is not triggered properly when setting the item size in ItemsWrapGrid during resizing. Therefore, the SizeChanged event of GridView, which is the parent of ItemsWrapGrid, was used to dynamically adjust the ItemsWrapGrid dimensions.

2025-03-25 07:34 UTC, jsuarezruiz commented
/rebase

2025-08-11 06:35 UTC, BagavathiPerumal commented
Closed in favor of https://github.com/dotnet/maui/pull/31038

2025-08-11 06:35 UTC, closed without merging