[iOS] CV - Reset ScrollOffset when item source changes
dotnet/maui pull request #26376
Opened 2024-12-05 02:54 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26366

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/56db946a-6800-4aea-891d-067e9c4522cb" width="300px"/>|<video src="https://github.com/user-attachments/assets/023a5388-8f60-4170-b11c-3ca8691f85af" width="300px"/>|

2024-12-06 19:21 UTC, rmarinho commented
/azp run

2024-12-06 19:30 UTC, Redth commented
Do we want to always scroll back to the first item when the data source changes? I would think this is more up to the individual consumer to decide if they want to keep position, or simply scroll to a known index of the previously displayed item?

2024-12-06 23:49 UTC, kubaflo commented
Hi @Redth that's a good question. However, in the second case, should we fix Android? Because on Android it always scrolls to the top

2024-12-18 11:40 UTC, rmarinho commented
I was going to say this should work with `ItemsUpdatingScrollMode` but seems that just for adding items. So I guess, makes sense to get to 0 like android, and make sure windows does the same when a collection is reset. 

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/scrolling?view=net-maui-9.0#control-scroll-position-when-new-items-are-added

2025-01-09 15:41 UTC, rmarinho requested changes
Test Issue10222Test is failing

2025-01-09 17:59 UTC, kubaflo commented
@rmarinho I think this Pr needed to be rebased to fix the failure. Could you please /azp?

2025-01-10 12:40 UTC, jsuarezruiz commented
/rebase

2025-02-22 16:10 UTC, rmarinho commented
/rebase

2025-03-30 11:09 UTC, kubaflo commented
I've developed a simple Swift application, and I noticed that when we reload the data, the collection view doesn’t automatically scroll to the top. Given this behavior, I believe it's best to keep the current implementation as it is.

```swift
import UIKit

class CollectionViewViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {

    var items: [String] = Array(1...100).map { "\($0)" }
    
    let button: UIButton =
    {
        let button = UIButton(type: .system)
        button.setTitle("Reload", for: .normal)
        button.translatesAutoresizingMaskIntoConstraints = false
        return button
    }()
    
    let collectionView: UICollectionView =
    {
        let layout = UICollectionViewFlowLayout()
        layout.itemSize = CGSize(width: 100, height: 100)
        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        collectionView.backgroundColor = .red
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        collectionView.register(CustomCell.self, forCellWithReuseIdentifier: CustomCell.reuseIdentifier)
        return collectionView
    }()
    
    @objc func reloadData() {
        items = Array(50...100).map { "\($0)" }
        collectionView.reloadData()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        collectionView.dataSource = self
        collectionView.delegate = self
        button.addTarget(self, action: #selector(reloadData), for: .touchUpInside)
        view.addSubview(collectionView)
        view.addSubview(button)
        NSLayoutConstraint.activate([
            button.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            button.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            button.heightAnchor.constraint(equalToConstant: 44),
            button.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            collectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            collectionView.bottomAnchor.constraint(equalTo: button.topAnchor),
            collectionView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            collectionView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor)
        ])
        
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return items.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: CustomCell.reuseIdentifier, for: indexPath)
        if let customCell = cell as? CustomCell {
            customCell.configure(with: items[indexPath.item])
        }
        cell.backgroundColor = .blue
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
           return CGSize(width: collectionView.frame.width, height: 100) // Full width
       }
}

class CustomCell : UICollectionViewCell {
    static let reuseIdentifier = "CustomCell"
    
    let label: UILabel = {
        let label = UILabel()
        label.textAlignment = .center
        label.font = UIFont.systemFont(ofSize: 17, weight: .bold)
        return label
    }()
    
    override init(frame: CGRect) {
          super.init(frame: frame)
          setupView()
      }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func setupView() {
        addSubview(label)
        label.frame = bounds
    }
    
    func configure(with text: String) {
        label.text = text
    }
    
}
```
<video src="https://github.com/user-attachments/assets/60f96e44-57a4-4406-a4d2-73a3e39b495d"/>

2025-03-30 11:09 UTC, closed without merging