Fixed picker allows user input if the keyboard is visible
dotnet/maui pull request #26382
Opened 2024-12-05 09:08 UTC by NirmalKumarYuvaraj

### Issue Details
User can input text when keyboard is open in picker.

### Root Cause
The base view for the picker in the unfocused state is AppCompatEditText. It allows the user to edit using keyboard.

 
### Description of Change
Setting the e.Handled to true in the KeyPress will prevent from further processing of the keys.

 
Validated the behaviour in the following platforms
 
- [x] Android
- [ ] Windows
- [ ] iOS
- [ ] Mac
 
 
### Issues Fixed
  
Fixes #24930
Fixes #8265 

### Output 

|Before|After|
|--|--|
| <video src="https://github.com/user-attachments/assets/73c50ba4-a27e-47e8-9c48-cae9952902aa"> | <video src="https://github.com/user-attachments/assets/53d669a4-d1fc-4d19-a6b3-4235ee1f003d"> |

2024-12-05 17:59 UTC, Redth commented
/azp run

2024-12-07 16:01 UTC, rmarinho commented
/azp run

2025-01-10 11:56 UTC, jsuarezruiz commented on src/Core/src/Handlers/Picker/PickerHandler.Android.cs
> +			new MauiPicker(Context){ KeyListener = null };
Could we apply the property inside the `MauiPicker` class?

2025-01-13 10:44 UTC, NirmalKumarYuvaraj commented on src/Core/src/Handlers/Picker/PickerHandler.Android.cs
> +			new MauiPicker(Context){ KeyListener = null };
@jsuarezruiz , I have modified the code changes. Please let me know if you have any concerns.

2025-01-14 12:06 UTC, jsuarezruiz commented
/azp run

2025-02-02 23:30 UTC, DeepWorksStudios commented
This is a duplicate issue of #8265

2025-02-07 16:17 UTC, codeinapt commented
When is this adjustment ready?

2025-02-11 12:58 UTC, DeepWorksStudios commented
> When is this adjustment ready?

I have been waiting for this fix since 3 years when I originally reported that issue

2025-02-18 10:21 UTC, StephaneDelcroix approved these changes, later dismissed

2025-02-19 21:27 UTC, PureWeen requested changes
1) if we make these changes I think they should be moved here https://github.com/dotnet/maui/blob/b17db5eeac3d0e8aa02e587b3c9ac47ff43e56ac/src/Core/src/Platform/Android/PickerManager.cs#L18

2) From looking at PickerManager it doesn't look like we want to completely disable the keyboard

2025-02-20 13:17 UTC, NirmalKumarYuvaraj commented
> 1. if we make these changes I think they should be moved here https://github.com/dotnet/maui/blob/b17db5eeac3d0e8aa02e587b3c9ac47ff43e56ac/src/Core/src/Platform/Android/PickerManager.cs#L18
> 2. From looking at PickerManager it doesn't look like we want to completely disable the keyboard

@PureWeen , i have modified the code changes. please let me know if you have any concerns.

2025-02-26 08:36 UTC, jsuarezruiz commented
/rebase

2025-02-26 08:43 UTC, jsuarezruiz commented
/azp run

2025-02-26 10:27 UTC, jsuarezruiz submitted a review, later dismissed

2025-02-26 10:27 UTC, jsuarezruiz commented on src/Core/src/Platform/Android/PickerManager.cs
> +				e.Handled = true;
To avoid redundant handling of e.Handled can just move it before the if. Always prevent user to enter text and, keep the condition to avoid invoke the CallOnClick method if the key is Tab or arrow keys.

2025-02-26 12:19 UTC, NirmalKumarYuvaraj commented on src/Core/src/Platform/Android/PickerManager.cs
> +				e.Handled = true;
@jsuarezruiz , I have updated the code changes. Please let me know if you have any concerns.

2025-02-26 21:06 UTC, PureWeen requested changes, later dismissed

2025-02-26 21:06 UTC, PureWeen commented on src/Core/src/Platform/Android/PickerManager.cs
> +			e.Handled = true;
I don't think we'll want to handle every single keypress event. 

This will probably break scenarios where a user has a hardware keyboard connected to the device and is trying to use tab to navigate components

2025-03-11 12:05 UTC, NirmalKumarYuvaraj commented on src/Core/src/Platform/Android/PickerManager.cs
> +			e.Handled = true;
@PureWeen , Pressing the Tab key focuses on the EditText, causing the picker dialog to open. Navigation does not occur between the components. According to the implementation, a change in focus triggers the dialog to appear on the view. I have shared a video for reference. please let me know if you have any concerns.



https://github.com/user-attachments/assets/e284397b-738d-4994-b4bd-772993ebecea

2025-03-12 10:05 UTC, jsuarezruiz commented
/rebase

2025-03-12 10:06 UTC, jsuarezruiz commented
/azp run

2025-03-26 07:58 UTC, jsuarezruiz commented
/rebase

2025-03-27 07:53 UTC, jsuarezruiz commented
/azp run

2025-05-19 11:07 UTC, jsuarezruiz commented
/rebase

2025-05-19 11:10 UTC, jsuarezruiz commented
/azp run

2025-05-23 03:23 UTC, mattleibow approved these changes

2025-05-28 18:04 UTC, merged