Inconsistent Resize Behavior for Header/Footer - fix
dotnet/maui pull request #26456
Opened 2024-12-07 15:53 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26397

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/c5edf988-a6fd-476e-9cb9-235bc72d47a4" width="300px"/>|<video src="https://github.com/user-attachments/assets/b70a4dd3-2406-430b-add5-ab60a73a4f66" width="300px"/>|

2024-12-07 15:59 UTC, rmarinho commented
/azp run

2024-12-08 16:16 UTC, PureWeen requested changes

2024-12-08 16:16 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs
> +				header.MeasureInvalidated += OnHeaderMeasureInvalidated;
Let's see if we can get `setNeedsLayout` to work here

2024-12-09 11:15 UTC, rmarinho commented
/azp run

2024-12-13 11:42 UTC, rmarinho commented
Can we add a test ?

2024-12-13 11:46 UTC, kubaflo commented
@rmarinho yea, I will add a test but I will probably close this PR in favour of this one: https://github.com/dotnet/maui/pull/26576

However, I'm waiting for your and Shane's review of it. Though I've already spoken with him yesterday :)

2026-01-14 11:36 UTC, closed without merging