[Android] Click on flyout clicks on page behind - fix
dotnet/maui pull request #26461
Opened 2024-12-08 14:02 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26392

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/8beda2ab-6df4-4e2d-8ac8-ac5dcdfedecc" width="300px"/>|<video src="https://github.com/user-attachments/assets/57025fbc-f795-413d-a7fe-df71b3a119e5" width="300px"/>|

2024-12-09 12:29 UTC, rmarinho requested changes
Can we add a test ? There/s no override for this ? we need to add the listener ? 

Don t we need t clear the listener on dispose?

2024-12-09 12:42 UTC, kubaflo commented
@rmarinho 
So... Android uses `com.google.android.material.navigation.NavigationView` as a drawer that I bet has some configuration responsible for intercepting a click.

This is from the default Android studio template:
<img src="https://github.com/user-attachments/assets/c2be5ee2-3456-4e2b-935c-59c678a0b77e"/>

But we use a view which is of type LayoutGroup - ContentPage is converted to it after `.ToPlatform()` I think.
So it doesn't intercept a click without `android:clickable = true`

Also when I replaced `com.google.android.material.navigation.NavigationView` with LinearLayout in the default Android studio app, it also didn't intercept a click without `android:clickable = true`

But @PureWeen wrote that setting `android:clickable = true` would break accessibility

I wonder if setting the listener is the right approach then

2024-12-11 00:14 UTC, kubaflo commented on src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Android.cs
> +		internal class FlyoutContainer : ContentViewGroup
Yea, it looks good, but I switched
`return childView.Arrange(new Graphics.Rect(0, 0, widthConstraint, heightConstraint));`
with
`return childView.Measure(bounds.Width, bounds.Height);`

2024-12-13 21:44 UTC, PureWeen commented
/azp run

2025-08-27 08:07 UTC, ondrej-krc-jediny commented
Hello, it looks like this PR has been inactive for a while. I’d really appreciate this being wrapped up, as the issue it addresses is still relevant. Is there any chance this will be fixed in near future? Thanks a lot.

2026-03-08 10:14 UTC, closed without merging