[Android] ScrollView - Setting SetClipChildren to false
dotnet/maui pull request #26475
Opened 2024-12-09 12:54 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20922

```
<ScrollView>
    <Border HeightRequest="200"
            WidthRequest="200"
            AutomationId="Border"
            BackgroundColor="Red">
        <Border.Shadow>
            <Shadow Radius="20"
                    Brush="Gray"
                    Offset="1,50"/>
        </Border.Shadow>
    </Border>
</ScrollView>
```

|Before|After|
|--|--|
|<img src="https://github.com/user-attachments/assets/2d0e8e59-5b3e-4953-bc96-75658cd7555e" width="300px"/>|<img src="https://github.com/user-attachments/assets/3f31a65f-5cdc-4811-bbbe-f008af39f285" width="300px"/>|

2024-12-10 18:53 UTC, rmarinho commented
/azp run

2026-03-18 11:01 UTC, StephaneDelcroix submitted a review, later dismissed

2026-03-18 11:02 UTC, StephaneDelcroix commented
/azp run maui-pr-uitest, maui-pr-devicetests

2026-03-18 12:17 UTC, StephaneDelcroix reviewed
## Multi-Model Consensus Review -- Follow-up Note

### Status: ✅ Approved & auto-merge enabled

This PR was approved and has auto-merge (squash) enabled. For completeness, here are the minor findings from our multi-model review:

🟡 **MODERATE** `ScrollViewHandler.Android.cs:244` -- `paddingShim.SetClipChildren(false)` is applied unconditionally to **all** ScrollViews, not just those with shadows. This disables Android's display-list clipping optimization globally, increasing overdraw. Consider scoping to only apply when content has elevation/shadow in a future follow-up.

🟢 **MINOR** -- `SetClipToPadding(false)` may also be needed for complete shadow rendering near padded edges. And the outer `MauiScrollView` viewport may still clip overflow since only the inner `paddingShim` is addressed.

These are non-blocking observations for future consideration. The fix is a net improvement for the targeted shadow-clipping bug.

2026-03-18 12:18 UTC, StephaneDelcroix reviewed
## Multi-Model Consensus Review -- Follow-up Note

### Status: ✅ Approved & auto-merge enabled

This PR was approved and has auto-merge (squash) enabled. For completeness, here are the minor findings from our multi-model review:

🟡 **MODERATE** `ScrollViewHandler.Android.cs:244` -- `paddingShim.SetClipChildren(false)` is applied unconditionally to **all** ScrollViews, not just those with shadows. This disables Android's display-list clipping optimization globally, increasing overdraw. Consider scoping to only apply when content has elevation/shadow in a future follow-up.

🟢 **MINOR** -- `SetClipToPadding(false)` may also be needed for complete shadow rendering near padded edges. And the outer `MauiScrollView` viewport may still clip overflow since only the inner `paddingShim` is addressed.

These are non-blocking observations for future consideration. The fix is a net improvement for the targeted shadow-clipping bug.

2026-03-19 09:49 UTC, jfversluis requested changes
Build errors and all kinds of unrelated files in this PR @kubaflo

2026-03-19 17:03 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-20 12:41 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-20 14:50 UTC, kubaflo commented
/azp run maui-pr-uitests

2026-03-20 23:47 UTC, merged