[iOS] Inherit UiContainerView from GeneralWrapperView
dotnet/maui pull request #26576
Opened 2024-12-12 16:10 UTC by kubaflo

To inherit UIContainerView from GeneralWrapperView, GeneralWrapperView needs to be public, so if these changes are okay then I will modify the public API perhaps

This would close this one: https://github.com/dotnet/maui/pull/26456 

@rmarinho @PureWeen

2024-12-12 22:24 UTC, rmarinho commented
/azp run

2024-12-13 16:48 UTC, PureWeen commented
/rebase

2024-12-13 16:48 UTC, PureWeen commented
/azp run

2024-12-13 21:47 UTC, PureWeen requested changes
TitleViewSetOnShellWorksAfterNavigation

2024-12-14 02:08 UTC, PureWeen commented
/azp run

2024-12-17 15:32 UTC, kubaflo commented on src/Core/src/Platform/iOS/LabelExtensions.cs
> +NSError nsError = new();
Yea, sorry about it. Fixed now

2024-12-17 21:24 UTC, PureWeen commented
/azp run

2026-03-08 10:14 UTC, closed without merging