Fixed - [Windows] ListView Items Text Not Rendered inside the TabbedPage
dotnet/maui pull request #26681
Opened 2024-12-17 15:06 UTC by NirmalKumarYuvaraj

### Issue Details:
ListView Items Text not rendered inside the TabbedPage
 
### Root Cause:
The issue was caused by the current page content being added to the ContentPresenter twice. This occurred because the content was being added in both the ApplyTemplateFinished event of the MauiNavigationView and the SelectedMenuItemChanged event during page rendering. As a result, the Unloaded event of CellControl was triggered, which led to the CellControl's parent being set to null.
 
### Description of Change:
To resolve the issue, I modified the OnSelectedMenuItemChanged event handler to ensure the NavigateToPage method is only called when the selected page is different from the current page.
 
**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
### Reference:
N/A
 
### Issues Fixed:
 
Fixes #26488
 
### Screenshots
| Before Issue Fix | After Issue Fix |
|--|--|
| <image src="https://github.com/user-attachments/assets/f4035551-2493-49ec-9afa-639ee0d671eb"> | <image src="https://github.com/user-attachments/assets/d59c4674-8256-4a1c-bffe-3324e4be41d9">|

2024-12-19 09:30 UTC, jfversluis commented
/azp run

2025-01-31 12:06 UTC, jsuarezruiz commented
/rebase

2025-02-12 12:02 UTC, jsuarezruiz commented
/rebase

2025-02-26 11:42 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:35 UTC, jsuarezruiz commented
/rebase

2025-06-06 06:59 UTC, jsuarezruiz commented
/rebase

2025-06-06 07:00 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2025-06-13 11:29 UTC, jsuarezruiz requested changes
The test DefaultSelectedTabTextColorShouldApplyProperly is failing:
`Snapshot different than baseline: DefaultSelectedTabTextColorShouldApplyProperly.png (0.78% difference)`
![image](https://github.com/user-attachments/assets/64e80e5f-cc16-4ee8-a2f9-9427517a200a)

Could you review it?

2025-06-20 11:35 UTC, KarthikRajaKalaimani commented
> The test DefaultSelectedTabTextColorShouldApplyProperly is failing: `Snapshot different than baseline: DefaultSelectedTabTextColorShouldApplyProperly.png (0.78% difference)` ![image](https://private-user-images.githubusercontent.com/6755973/454842537-64e80e5f-cc16-4ee8-a2f9-9427517a200a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA0MTg4NTQsIm5iZiI6MTc1MDQxODU1NCwicGF0aCI6Ii82NzU1OTczLzQ1NDg0MjUzNy02NGU4MGU1Zi1jYzE2LTRlZTgtYTJmOS05NDI3NTE3YTIwMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MjBUMTEyMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFjN2M1Y2FiNjM3MmJkM2E3OGExMTFmNTA5ZTVjODRjNDUyMTA3ZTU1MzQ4NGRhZWViNDA1OWU1NDJjMDdlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XLVU-1rZNcAhSEVR7zXhRLQkS3WZzfCxGFYeSTT6yG8)
> 
> Could you review it?

I have Analyzed the failure of the DefaultSelectedTabTextColorShouldApplyProperly and Issue1323Test test cases and identified that the issue was due to incorrect vertical alignment.
 
Initially, the VerticalOptions property of the VerticalStackLayout was set to Center for the test case DefaultSelectedTabTextColorShouldApplyProperly, but it wasn't visually centered because of a mismatch in layout sizing during initialization. Specifically:
 
The content panel's height was initially 650 from native level.
 
Then, from the native level, the OnNavigationViewSizeChanged event of tabbed page was triggered, updating the NavigationView height to 730.
 
The content panel also resized to 730, and the vertical layout's Y position was set to 355, which centers it relative to 730, not the original content panel height (650).
 
This caused the layout to appear misaligned relative to the intended 650-height content area.
 
**After applying my fix:**
 
The NavigationView height remains 730, but the content panel height stays at 650, as defined from the native side.
 
The vertical layout's Y position is now correctly set to 315.6, which is the true center relative to the 650-height content panel.
 
This ensures the VerticalStackLayout is visually and functionally centered as expected. 

Can we resave the image ?

2025-08-16 14:36 UTC, PureWeen commented
As we obsolete ListView in .NET 10, we'll no longer be accepting PRs for ListView so we can stay focused on CollectionView and ensuring it meets and exceeds everyone's needs.

2025-08-16 14:36 UTC, closed without merging