Fix up relevant CA1416 warnings - Set 1
dotnet/maui pull request #26696
Opened 2024-12-18 09:35 UTC by Tamilarasan-Paranthaman

### Description of Change

The CA1416 warnings were already resolved in PR https://github.com/dotnet/maui/pull/26593  

In this PR, we have divided the file changes from that PR into smaller groups and included test cases for the affected areas to ensure proper functionality.

2024-12-20 14:18 UTC, jfversluis commented
/azp run

2025-02-22 14:34 UTC, jfversluis commented
/rebase

2025-02-22 14:38 UTC, jfversluis commented
@Tamilarasan-Paranthaman are you sure this PR has the right description and title? I don't see any changes related to CA1416

2025-02-24 07:40 UTC, Tamilarasan-Paranthaman commented
> @Tamilarasan-Paranthaman are you sure this PR has the right description and title? I don't see any changes related to CA1416

@jfversluis , as mentioned in the description, in this PR, I have divided the CA1416 warning fix file changes from the previous PR https://github.com/dotnet/maui/pull/26593 into smaller groups, identified the affected cases, and included test cases to ensure proper functionality. So, I have categorized them into different sets

2025-02-27 11:41 UTC, Tamilarasan-Paranthaman commented
> Could it be that some need a new snapshot or something here? I've retried 4 times but things keep failing, can you have a look @Tamilarasan-Paranthaman?

@jfversluis, I have resaved the Mac images, and a recently added test failed due to these changes on iOS. I have now fixed the issue. Could you please review and let me know if you have any concerns?

2025-03-05 09:01 UTC, jfversluis commented
/rebase

2025-03-20 09:39 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ContextActionCell.cs
> +				var context = ctx.CGContext;
This is almost duplicated two times, can create a method and reuse it. Should be something like:

```
private void FillRect(UIGraphicsImageRendererContext ctx, CGRect rect, CGColor color)
{
    var context = ctx.CGContext;
    context.SetFillColor(color);
    context.FillRect(rect);
}
```

```
using var renderer = new UIGraphicsImageRenderer(size);
DestructiveBackground = renderer.CreateImage(ctx =>
    FillRect(ctx, rect, Microsoft.Maui.Platform.ColorExtensions.Red.CGColor));
NormalBackground = renderer.CreateImage(ctx =>
    FillRect(ctx, rect, Microsoft.Maui.Platform.ColorExtensions.LightGray.CGColor));
```

2025-03-20 09:39 UTC, jsuarezruiz commented on src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs
> +			var renderer = new UIGraphicsImageRenderer(backgroundLayer.Bounds.Size, format);
Consider use a `using` here.
`using var renderer = new UIGraphicsImageRenderer(backgroundLayer.Bounds.Size, format);`

2025-03-20 09:39 UTC, jsuarezruiz commented on src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs
Can also verify the bounds at this point.

```
if (backgroundLayer.Bounds.Size.Width <= 0 || backgroundLayer.Bounds.Size.Height <= 0)
     return;
```

2025-03-24 11:01 UTC, Tamilarasan-Paranthaman commented on src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ContextActionCell.cs
> +				var context = ctx.CGContext;
@jsuarezruiz, I have modified it.

2025-03-25 07:35 UTC, jsuarezruiz commented
/azp run

2025-05-27 18:08 UTC, rmarinho requested changes
@Tamilarasan-Paranthaman  can you please rebase, there are some conflicts. Maybe target this to the inflight branch too.

2025-05-28 09:39 UTC, rmarinho commented
/azp run

2025-05-28 18:24 UTC, merged