Fixed Navigation Title disappears if Flyout is set to a new window
dotnet/maui pull request #26693
Opened 2024-12-18 04:57 UTC by NirmalKumarYuvaraj

Fixes #21645

2024-12-19 12:39 UTC, jfversluis commented
/azp run

2024-12-23 15:25 UTC, Redth commented
/azp run

2025-01-10 11:58 UTC, jsuarezruiz commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +			FlyoutPage isFlyoutPage = _currentPage.FindParentOfType<FlyoutPage>();
We can move this line to 87, and only access to the `FlyoutPage` when needed.

2025-01-10 15:09 UTC, prakashKannanSf3972 commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +			FlyoutPage isFlyoutPage = _currentPage.FindParentOfType<FlyoutPage>();
> We can move this line to 87, and only access to the `FlyoutPage` when needed.

Thank you for the review. Updated the FlyoutPage access as suggested.

2025-01-14 12:07 UTC, jsuarezruiz commented
/azp run

2025-01-30 23:09 UTC, PureWeen requested changes

2025-01-30 23:09 UTC, PureWeen commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +				if (isFlyoutPage?.Flyout == _currentPage)
I think the problem here is further up in the code. 

If the Appearing event is triggered from the FlyoutPage then I don't think we want _currentPage to get set to the FlyoutPage. 

For example, in this code the `_currentNavigationPage` gets set to null which seems bad because the `Details` page is stil a `NavigationPage`

For the FlyoutPage check here I think what we need to do a search up the tree to make sure this page isn't inside a `Flyout`

I don't think just checking that the `Flyout` matches is quite sufficient. 

As `FindParentOfType` is walking the tree up it should keep track just in case current page is the child of a page that's inside the `Flyout`

Flyout => NavPage => Page

2025-01-31 12:18 UTC, prakashKannanSf3972 commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +				if (isFlyoutPage?.Flyout == _currentPage)
> I think the problem here is further up in the code.
> 
> If the Appearing event is triggered from the FlyoutPage then I don't think we want _currentPage to get set to the FlyoutPage.
> 
> For example, in this code the `_currentNavigationPage` gets set to null which seems bad because the `Details` page is stil a `NavigationPage`
> 
> For the FlyoutPage check here I think what we need to do a search up the tree to make sure this page isn't inside a `Flyout`
> 
> I don't think just checking that the `Flyout` matches is quite sufficient.
> 
> As `FindParentOfType` is walking the tree up it should keep track just in case current page is the child of a page that's inside the `Flyout`
> 
> Flyout => NavPage => Page

@PureWeen,

This issue occurs when the user sets the main window as a **FlyoutPage** and dynamically updates FlyoutPage.Flyout = new ContentPage(). When this happens, the **OnPageAppearing** event is triggered for a page that is not part of the **NavigationView** (since only the Flyout details have a NavigationPage).
In this case, the dynamically assigned page is not wrapped in a **NavigationPage**, causing the toolbar visibility to be set to false in the following condition:
 
if (_currentNavigationPage == null)
{
    IsVisible = false;
    return;
}
To fix this, we added logic to check if the page belongs to a **FlyoutPage** and not inside the NavigationPage. We ensure this whether current page is **FlyoutPage.Flyout** and its parent is **FlyoutPage**  using the following line and return it before setting the visibility.
 
FlyoutPage isFlyoutPage = _currentPage.FindParentOfType<FlyoutPage>();
if (isFlyoutPage?.Flyout == _currentPage)
{
   return;
}

We ensured this fix with current window is a NavigationPage, ContentPage, FlyoutPage, and Shell. Do you think this logic might not work, cause any issues, or impact performance? If so, can you please suggest an alternative approach to improve this fix?

2025-02-07 21:39 UTC, PureWeen commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +				if (isFlyoutPage?.Flyout == _currentPage)
The problem is that the only appearing events we really care about are ones that come from the Details page stack. 

The pages that get set on the `FlyoutPage` should have zero influence on the toolbar. 

The issue somewhat comes from the fact that we are listening to the `Appearing` event on ToolbarTracker which is watching for appearing events on both the `FlyoutPage` and `Details` Page

But for this method, any appearing events that fire from the `FlyoutPage` should just get completely ignored

With your fix here the `_currentPage = cp;` will get set to the `FlyoutPage` which should never happen. 

The appearing event that fires from the `flyoutpage` should just get completely ignored

2025-02-10 22:49 UTC, PureWeen requested changes
Can the testing for this one just be a UnitTest? 

Since this change is only in xplat code it feels like we could just make this a unit test instead of a UI Test

2025-02-10 22:49 UTC, PureWeen commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +			if (currentParent is FlyoutPage flyoutPage && flyoutPage.Flyout == cp)
Can we make this search up the parent tree ? vs just check the Parent?

I worry about cases where the flyoutpage might have a flyout nested inside a different page. 
I realize this doesn't really happen very often but it seems like a good future proof.

2025-02-11 22:22 UTC, PureWeen requested changes

2025-02-11 22:22 UTC, PureWeen commented on src/Controls/tests/Core.UnitTests/FlyoutPageUnitTests.cs
> +			ContentPage contentPage = new ContentPage
Can you add a test where this is a navigationpage

2025-02-12 03:17 UTC, prakashKannanSf3972 commented on src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
> +			if (currentParent is FlyoutPage flyoutPage && flyoutPage.Flyout == cp)
Based on your suggestion, I have updated the approach to traverse the parent hierarchy using `FindParentOfType<FlyoutPage>()` instead of directly checking Parent. This ensures a more reliable and future-proof solution, even for nested `FlyoutPage` scenarios. A unit test has been implemented to validate this scenario.

2025-02-12 08:04 UTC, prakashKannanSf3972 commented on src/Controls/tests/Core.UnitTests/FlyoutPageUnitTests.cs
> +			ContentPage contentPage = new ContentPage
@PureWeen,

The `contentPage` is already wrapped within a `NavigationPage`, which is set to the `DetailPage` of FlyoutPage on line 481:
 
https://github.com/dotnet/maui/blob/34bae0b3b53b479b18cf7ace8cbad7f9d7a95670/src/Controls/tests/Core.UnitTests/FlyoutPageUnitTests.cs#L481
 
This ensures that the `FlyoutPage` operates within a `NavigationPage` context. Let me know if you have any specific concerns regarding this test.

2025-02-13 13:30 UTC, PureWeen commented on src/Controls/tests/Core.UnitTests/FlyoutPageUnitTests.cs
> +			ContentPage contentPage = new ContentPage
Yea, I'm wanting a version of the test where the content in the flyout is nested inside another page type.

Just to verify that scenario works

2025-02-14 12:44 UTC, prakashKannanSf3972 commented on src/Controls/tests/Core.UnitTests/FlyoutPageUnitTests.cs
> +			ContentPage contentPage = new ContentPage
The test has been updated to include the content in the flyout nested inside another page type as suggested. Let me know if you have any further concerns. Thanks!

2025-02-18 22:50 UTC, PureWeen commented
@NirmalKumarYuvaraj let me know what you think of my adjustments

2025-02-18 22:53 UTC, PureWeen commented
/azp run

2025-02-19 18:34 UTC, PureWeen commented
/azp run

2025-02-19 18:34 UTC, PureWeen requested changes
Looks like you checked a few wrong files in

I had rebased the PR so you'll need to update your local branch

2025-02-20 14:02 UTC, prakashKannanSf3972 commented
> @NirmalKumarYuvaraj let me know what you think of my adjustments

@PureWeen, Thank you for making adjustments to this PR!

While going through the changes, I noticed the following condition:

```
if (cp.FindParentOfType<FlyoutPage>()?.Flyout is { } flyout &&
                (cp == flyout || cp.FindParent(x => x == flyout) is not null))
{
    return;
}
```

From what I have observed, the first check ensures that `cp` is a child of `FlyoutPage`, and `cp == flyout` verifies whether `cp` itself is the `Flyout`. Since this already covers the intended scenario, Could you help me understand why the additional check `cp.FindParent(x => x == flyout)` is not null is needed?

Additionally, I encountered a compiler error with `cp.FindParent(x => x == flyout)`, as FindParent is not defined for ContentPage. I have attached the snapshot for reference.

<img width="578" alt="Screenshot 2025-02-20 at 6 07 45 PM" src="https://github.com/user-attachments/assets/8efc7797-fb89-4718-bf04-c8c12423c472" />

Would it be possible to rely solely on FindParentOfType<FlyoutPage>() instead? Or is there a specific case this additional check is meant to cover?

Looking forward to your insights.

2025-02-20 23:39 UTC, PureWeen commented
> > @NirmalKumarYuvaraj let me know what you think of my adjustments
> 
> @PureWeen, Thank you for making adjustments to this PR!
> 
> While going through the changes, I noticed the following condition:
> 
> ```
> if (cp.FindParentOfType<FlyoutPage>()?.Flyout is { } flyout &&
>                 (cp == flyout || cp.FindParent(x => x == flyout) is not null))
> {
>     return;
> }
> ```
> 
> From what I have observed, the first check ensures that `cp` is a child of `FlyoutPage`, and `cp == flyout` verifies whether `cp` itself is the `Flyout`. Since this already covers the intended scenario, Could you help me understand why the additional check `cp.FindParent(x => x == flyout)` is not null is needed?
> 
> Additionally, I encountered a compiler error with `cp.FindParent(x => x == flyout)`, as FindParent is not defined for ContentPage. I have attached the snapshot for reference.
> 
> <img alt="Screenshot 2025-02-20 at 6 07 45 PM" width="578" src="https://private-user-images.githubusercontent.com/127308739/415207759-8efc7797-fb89-4718-bf04-c8c12423c472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwOTM4OTQsIm5iZiI6MTc0MDA5MzU5NCwicGF0aCI6Ii8xMjczMDg3MzkvNDE1MjA3NzU5LThlZmM3Nzk3LWZiODktNDcxOC1iZjA0LWM4YzEyNDIzYzQ3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMFQyMzE5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDFiYjYyMTRkN2M2NDQ0N2Q2MDYxZjk3MDQ4ZGVhMTBiMjhmNjRhM2ZiNzMxZGM3MGRjOGFhM2ZlOGVlYTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3MpcEo_sUArDqnlbVvso5mJJ5aoPzfyEn2bNrXRdR1s">
> Would it be possible to rely solely on FindParentOfType() instead? Or is there a specific case this additional check is meant to cover?
> 
> Looking forward to your insights.

I'm probably being too careful here but the idea is trying not to assume the hierarchy here.

There might be some scenario where it's

FlyoutPage => Flyout => Page1 => Page2 => Page3 => Page4

OnAppearing fires on the Page4 so we need to be able to walk up that chain and see that it's inside the flyout.

I've modified the code a bit so it should compile now

2025-02-21 14:27 UTC, prakashKannanSf3972 commented
@PureWeen, 

I would like to seek clarification regarding the Flyout property assignment in the FlyoutPage
 
According to the FlyoutPage [Documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage?view=net-maui-9.0#create-a-flyoutpage) the Flyout property should be set to a `ContentPage`. However, in the test, it is assigned as a `NavigationPage`.
 
While testing this scenario, I observed that setting Flyout to a `NavigationPage` results in a crash on the Android platform. To provide more context, I have attached a video demonstrating the issue.

|.NET Sample|SandBox|
|--|--|
|<video src="https://github.com/user-attachments/assets/f693e5a8-90e1-4fc4-bbdf-d6bb0ed9072e"> |<video src ="https://github.com/user-attachments/assets/1afd847c-1216-491b-8cc4-7e3986278760">|
 
Could you please clarify if wrapping the `ContentPage` inside a `NavigationPage` for the `Flyout` property is intentional, or if it would be more appropriate to follow the documentation and use a ContentPage directly? 

Looking forward to your insights. Thanks!

2025-02-26 23:14 UTC, PureWeen commented
> @PureWeen,
> 
> I would like to seek clarification regarding the Flyout property assignment in the FlyoutPage
> 
> According to the FlyoutPage [Documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage?view=net-maui-9.0#create-a-flyoutpage) the Flyout property should be set to a `ContentPage`. However, in the test, it is assigned as a `NavigationPage`.
> 
> While testing this scenario, I observed that setting Flyout to a `NavigationPage` results in a crash on the Android platform. To provide more context, I have attached a video demonstrating the issue.
> 
> .NET Sample	SandBox
>  SimpleSample.mov 
>  SandBoxSample.mov 
> Could you please clarify if wrapping the `ContentPage` inside a `NavigationPage` for the `Flyout` property is intentional, or if it would be more appropriate to follow the documentation and use a ContentPage directly?
> 
> Looking forward to your insights. Thanks!

The unit test is somewhat contrived for the purposes of future proofing
I just wanted to validate that in nested scenarios the code would still work instead of just hardcoding the hierarchy. 

it's probably somewhat overkill but I just didn't feel comfortable with code that assumed an implicit rule vs just writing code that could handle a hierarchy.

At some later date if we decide to add some type of layering into the flyout, this code would just break and we wouldn't really know it.

2025-02-27 20:38 UTC, PureWeen commented
/azp run

2025-02-28 09:31 UTC, prakashKannanSf3972 commented
> 
> The unit test is somewhat contrived for the purposes of future proofing I just wanted to validate that in nested scenarios the code would still work instead of just hardcoding the hierarchy.
> 
> it's probably somewhat overkill but I just didn't feel comfortable with code that assumed an implicit rule vs just writing code that could handle a hierarchy.
> 
> At some later date if we decide to add some type of layering into the flyout, this code would just break and we wouldn't really know it.

@PureWeen, 

Understood, Thank you for the clarification :)

2025-03-02 22:12 UTC, PureWeen commented
/azp run

2025-03-03 23:00 UTC, PureWeen requested changes
Fix branch

2025-03-06 07:19 UTC, prakashKannanSf3972 commented
Closing this PR due to branch conflicts. A new PR ( #28209 ) has been created with the same changes to address the issue.

2025-03-06 07:19 UTC, closed without merging