Fixed the FlyoutPage.Flyout Disappearing When Maximizing the Window on Mac Platform
dotnet/maui pull request #26701
Opened 2024-12-18 13:14 UTC by NanthiniMahalingam

### Issue Details

- FlyoutPage.Flyout disappeared When the FlyoutPage is maximized

### Root Cause

- When the FlyoutPage is maximized, the flyout is removed even when IsPresented is true. This causes the FlyoutPage's flyout to disappear.

### Description of Change

- While resizing the window on the Mac platform, I have restricted the flyout removal function when IsPresented is true.

### Issues Fixed
Fixes https://github.com/dotnet/maui/issues/22719

Validated the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Output

|Before|After|
|--|--|
| <video src="https://github.com/user-attachments/assets/079fceb7-02cd-430c-be9c-014838a1dc4f" >| <video src="https://github.com/user-attachments/assets/e13d7b26-5090-409b-aaf6-e375791854c2">|

2024-12-23 15:25 UTC, Redth commented
/azp run

2025-01-08 21:09 UTC, PureWeen requested changes

2025-01-08 21:09 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs
> +				if (FlyoutPageController.ShouldShowSplitMode || Presented)
I think this causes the flyout to open in too many scenarios.

For example, if I'm on an ipad now and I rotate to landscape and then back to portrait the flyout will remain open. 

we probably need to condition on the type of transition that's happening here so this code doesn't run when it's just related to a size change

2025-01-08 21:11 UTC, PureWeen commented
Also, you can write a test for this by slightly modifying the flyoutpage class

Checkout

https://github.com/dotnet/maui/blob/720226dd001d7a7de93d56fb613a77a9f0649374/src/Controls/tests/TestCases.HostApp/Issues/Issue18161.xaml.cs#L26

And you'll see a way to make it operate on an iphone like it does on an iPAd
which will let you write a test and validate behavior

2025-01-09 14:55 UTC, NanthiniMahalingam commented on src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs
> +				if (FlyoutPageController.ShouldShowSplitMode || Presented)
Hi @PureWeen 

- In the user sample, the IsPresented property is set to true for any flyout behavior. The FlyoutPage.Flyout always opens at load time regardless of orientation or flyout behavior.
- According to this approach, when resizing or changing orientation, the flyout should be visible when the IsPresented value is true, correct? Previously, when resizing or changing orientation, IsPresented was not considered and was ensured only with the ShouldShowSplitMode property.
- In this fix, we have ensured that IsPresented is considered regardless of orientation or flyout behavior.
- Based on your update, should we avoid considering IsPresented when changing the orientation and flyout behavior?

2025-01-16 19:29 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs
> +				if (FlyoutPageController.ShouldShowSplitMode || Presented)
Add the following code to the sandbox

```C#
protected override Window CreateWindow(IActivationState? activationState)

    {

        // To test shell scenarios, change this to true

        bool useShell = false;



        if (!useShell)

        {

            return new Window(

                new FlyoutPage()

                {

                    Flyout = new MainPage() { Title = "Flyout", Background = Colors.Purple },

                    Detail = new NavigationPage(new MainPage() { Title = "Flyout", Background = Colors.Green }) { Title = "Flyout" }

                }

            );

        }

        else

        {

            return new Window(new SandboxShell());

        }

    }
```




- launch to an ipad in landscape mode
- rotate to portrait
- flyout is left open

2025-01-17 12:12 UTC, jsuarezruiz commented
/azp run

2025-01-21 12:18 UTC, jsuarezruiz commented
/azp run

2025-01-21 14:23 UTC, jsuarezruiz requested changes

2025-01-21 14:23 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22719.cs
> +		VerifyScreenshot();
The snapshot is pending on Windows. Already available in the latest build.
![image](https://github.com/user-attachments/assets/bba962a8-647a-4787-9225-3eda21f99cdb)
Could you commit it?

2025-01-22 13:07 UTC, NanthiniMahalingam commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22719.cs
> +		VerifyScreenshot();
Hi @jsuarezruiz ,

- I have committed the Windows platform output image. Could you please verify it?

2025-01-23 07:25 UTC, jsuarezruiz commented
/azp run

2025-01-30 22:21 UTC, PureWeen approved these changes, later dismissed

2025-01-30 22:33 UTC, PureWeen requested changes
I added code to the test in order to replicate split mode

Let me know if that makes sense and matches the test you added?

2025-01-31 13:23 UTC, NanthiniMahalingam commented
> I added code to the test in order to replicate split mode
> 
> Let me know if that makes sense and matches the test you added?

- When using FlyoutLayoutBehavior.SplitOnPortrait, the flyout appears at load time. However, when changing the orientation from landscape to portrait, the flyout does not appear because FlyoutOverlapsDetailsInPopoverMode(https://github.com/NanthiniMahalingam/maui/blob/91aada4eae045e69924d358cb1244ba4b96294d6/src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs#L209) is set to false for iPhone.

2025-02-06 07:00 UTC, jsuarezruiz commented
/azp run

2025-02-06 07:36 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs
> +			if (!OperatingSystem.IsMacCatalyst())
The Flyout state will also be maintained when resizing the window for example with this change. What is the behavior on Windows? While the change seems fine to me, I do think the behavior should be aligned between platforms.

2025-02-11 14:13 UTC, sheiksyedm commented
/azp run

2025-02-12 12:01 UTC, jsuarezruiz commented
/rebase

2025-02-13 13:25 UTC, PureWeen commented
> > I added code to the test in order to replicate split mode
> > Let me know if that makes sense and matches the test you added?
> 
> * When using FlyoutLayoutBehavior.SplitOnPortrait, the flyout appears at load time. However, when changing the orientation from landscape to portrait, the flyout does not appear because FlyoutOverlapsDetailsInPopoverMode(https://github.com/NanthiniMahalingam/maui/blob/91aada4eae045e69924d358cb1244ba4b96294d6/src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs#L209) is set to false for iPhone.

I think that's fine

The purpose of my changes was to validate the scenario where

- I'm in portrait
- change to landscape
- change to portrait
- Flyout is closed

So for the test set it to SplitOnLandscape

And then perform the actions above to verify the flyout doesn't stay open.

2025-02-14 10:11 UTC, NanthiniMahalingam commented
> > > I added code to the test in order to replicate split mode
> > > Let me know if that makes sense and matches the test you added?
> > 
> > 
> > 
> > * When using FlyoutLayoutBehavior.SplitOnPortrait, the flyout appears at load time. However, when changing the orientation from landscape to portrait, the flyout does not appear because FlyoutOverlapsDetailsInPopoverMode(https://github.com/NanthiniMahalingam/maui/blob/91aada4eae045e69924d358cb1244ba4b96294d6/src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs#L209) is set to false for iPhone.
> 
> I think that's fine
> 
> The purpose of my changes was to validate the scenario where
> 
> * I'm in portrait
> * change to landscape
> * change to portrait
> * Flyout is closed
> 
> So for the test set it to SplitOnLandscape
> 
> And then perform the actions above to verify the flyout doesn't stay open.

Hi @PureWeen 

I have validated the following scenario with FlyoutBehavior set to SplitOnLandscape:
ShouldShowSplitMode returns true when the device orientation is landscape.
Steps:

- Start in portrait mode.
- Change to landscape mode.
- Change back to portrait mode.
- The flyout is closed.

The flyout does not remain open when switching from landscape to portrait.

2025-02-18 20:50 UTC, PureWeen submitted a review, later dismissed

2025-02-18 20:50 UTC, PureWeen commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22719.cs
> +		App.SetOrientationLandscape();
Can we split the tests up for this one? 

We're essentially wanting to test two different things at this point

1) ShouldFlyoutBeVisibleAfterMaximizingWindow
2) Rotating the device to landscape and then back to portrait doesn't keep the flyout open. 

You could just create a second test that's like
Issue22719_1.xaml

And that will just have the tests based around validating orientation not keeping the flyout open

2025-02-19 19:05 UTC, PureWeen commented
@NanthiniMahalingam is this ready to be re-reviewed?

2025-02-20 09:43 UTC, NanthiniMahalingam commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22719.cs
> +		App.SetOrientationLandscape();
Hi @PureWeen 
I have split the test case for orientation and window maximizing scenarios. Could you please verify it?

2025-02-20 12:50 UTC, NanthiniMahalingam commented
> @NanthiniMahalingam is this ready to be re-reviewed?

Hi @PureWeen 
Yes, the PR is ready for review.

2025-02-21 12:08 UTC, jsuarezruiz commented
/azp run

2025-02-25 09:51 UTC, jsuarezruiz commented
/rebase

2025-02-27 07:16 UTC, NanthiniMahalingam commented on src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs
> +				if (FlyoutOverlapsDetailsInPopoverMode)
> Can simplify it and improve readability with some changes:
> 
> ```
> bool shouldShowSplitMode = FlyoutPageController.ShouldShowSplitMode;
> 
> if (FlyoutOverlapsDetailsInPopoverMode)
> {
>     UpdatePresented(shouldShowSplitMode);
> }
> else if (!shouldShowSplitMode && _presented)
> {
>     UpdatePresented(false);
> }
> ```
> 
> Simplified the nested if statements by combining conditions and using an else if block, in addition to determined the value to pass to UpdatePresented with a boolean variable.

Hi @jsuarezruiz 

- I've simplified the nested if conditions. Let me know if you have any further concerns.

2025-03-27 07:52 UTC, jsuarezruiz commented
/azp run

2025-06-13 11:27 UTC, jsuarezruiz commented
/rebase

2025-10-27 10:50 UTC, jsuarezruiz commented
/rebase

2025-12-08 10:29 UTC, StephaneDelcroix approved these changes
works

2025-12-16 20:54 UTC, merged