Radio button's default template improvements
dotnet/maui pull request #26719
Opened 2024-12-19 01:21 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26689

```
<RadioButton
    Content="wwa"
    BackgroundColor="Red"
    HeightRequest="50"
    Margin="0,70,0,0"
    TextColor="Black"/>
```

|Before|After|
|--|--|
|<img src="https://github.com/user-attachments/assets/13f3bcd8-e26f-4ed4-9510-69b2c6744d41" width="300px"/>|<img src="https://github.com/user-attachments/assets/3801fdfb-9152-401a-b2a2-f8933759db1c" width="300px"/>|

2024-12-20 18:05 UTC, PureWeen commented
/azp run

2025-01-15 06:48 UTC, jsuarezruiz commented
/azp run

2025-01-15 15:08 UTC, mattleibow approved these changes, later dismissed

2025-01-15 16:05 UTC, PureWeen requested changes
Looks like unit tests are failing

Border Style properties should not affect RadioButton(property: BindableProperty { DeclaringType = typeof(Microsoft.Maui.Controls.VisualElement), DefaultBindingMode = OneWay, DefaultValue = 0, IsReadOnly = False, PropertyName = "Rotation", ... }, value: 0.

2025-01-17 16:13 UTC, kubaflo commented
The changes required unit tests adjustments

2025-01-21 10:40 UTC, jsuarezruiz commented
/rebase

2025-01-21 10:40 UTC, jsuarezruiz commented
/azp run

2025-01-29 20:59 UTC, PureWeen approved these changes

2025-01-29 21:00 UTC, merged