Fixed [Android] ListView scroll position maintains after items refresh
dotnet/maui pull request #26723
Opened 2024-12-19 10:22 UTC by NirmalKumarYuvaraj

### Issue Details:
ListView scroll position maintains after cleared and added data to the existing collection.
 
### Root Cause:
The native Android ListView retains its scroll position even after the data is reset.
 
### Description of Change:
When the data is reset, the scroll position is programmatically set to the 0th item (top of the list) on CollectionChanged event.
 
**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
### Reference:
https://stackoverflow.com/questions/2889793/android-listview-scrolling-to-top
 
### Issues Fixed:
 
Fixes #26661 
Fixes #25256
 
### Screenshots
| Before Issue Fix | After Issue Fix |
|--|--|
| <video src="https://github.com/user-attachments/assets/37d76048-6433-4dcf-adad-53cee98a2fd5"> |<video src="https://github.com/user-attachments/assets/c6c146b5-63a6-4774-87f4-f56745429a15" >|

2025-01-08 13:06 UTC, jfversluis commented
/azp run

2025-01-10 12:02 UTC, jsuarezruiz reviewed
Could include a related test?

2025-01-15 13:22 UTC, KarthikRajaKalaimani commented
> Could include a related test?

@jsuarezruiz  The test case was initially disabled, but it was enabled for the Windows platform after this PR #26674 . I have now enabled the test case for the Android platform.

2025-01-16 10:35 UTC, jsuarezruiz commented
/azp run

2025-02-25 09:52 UTC, jsuarezruiz commented
/rebase

2025-02-26 11:54 UTC, jsuarezruiz commented
/rebase

2025-02-26 11:56 UTC, jsuarezruiz requested changes

2025-02-26 11:56 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewAdapter.cs
> +				_realListView.SmoothScrollToPosition(0);
With this change, we align the behavior between all platforms?

2025-02-26 11:56 UTC, jsuarezruiz commented on src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewAdapter.cs
> +				_realListView.SmoothScrollToPosition(0);
Add a comment to explain the purpose of scrolling to position 0 when the action is Reset.

2025-02-28 05:00 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewAdapter.cs
> +				_realListView.SmoothScrollToPosition(0);
> With this change, we align the behavior between all platforms?

Yes, on the other platforms, the scroll position was automatically set to 0, so this change ensures consistent behavior across all platforms.

2025-02-28 05:00 UTC, KarthikRajaKalaimani commented on src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewAdapter.cs
> +				_realListView.SmoothScrollToPosition(0);
> Add a comment to explain the purpose of scrolling to position 0 when the action is Reset.

@jsuarezruiz  Added a comment to explain why the scroll position is set to the 0th position.

2025-03-25 07:36 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:50 UTC, jsuarezruiz commented
/azp run

2025-03-26 08:43 UTC, jsuarezruiz requested changes
The test **Issue7167Test** is failing on Android:

`System.InvalidOperationException : Did not find any elements in the list: 15, 20, 30, 40, 60, 80`

Is a ListView test doing scroll, could you review if is related with the changes?

2025-08-16 14:37 UTC, PureWeen commented
As we obsolete ListView in .NET 10, we'll no longer be accepting PRs for ListView so we can stay focused on CollectionView and ensuring it meets and exceeds everyone's needs.

2025-08-16 14:37 UTC, closed without merging