Fixed IsEnabled Property not works on Tabs
dotnet/maui pull request #26728
Opened 2024-12-19 14:30 UTC by NirmalKumarYuvaraj

### Issue Details
In the Shell, when the Tab.isEnabled property is set to false, the tab should be non-interactive and prevent user interaction. the current behavior allows the tab to be clicked.

### Root Cause
The IsEnabled property is not correctly mapped to the TabBar.Items.IsEnabled property on iOS and macOS. In Windows, implementation property for IsEnabled property is not handled.
 
### Description of change
A new method, UpdateCellEnabled, has been created to map the ShellSection.IsEnabled value to the Tabbar.Items.IsEnabled property on the iOS platform.

For the Windows platform, a new property was added to the NavigationViewItemViewModel and registered within the NavigationViewItem in the TabbedPageXaml.Windows page. The BaseShellItem.IsEnabled property is now mapped to the newly introduced IsEnabled property in the NavigationViewItemViewModel. Additionally, the IsEnabled property has been updated to respond to runtime changes through the property-changed event.
 
### Validated the Behavior in the following Platforms
 
- [x] Android
- [x] iOS
- [x] mac
- [x] WinUI
 
### Issue fixed
Fixes #5161

### Screenshots
| Before Issue Fix | After Issue Fix |
|--|--|
|<video src="https://github.com/user-attachments/assets/343f9cab-081e-4cc0-b0ff-f86320186f6f">|<video src='https://github.com/user-attachments/assets/fb45fd5d-56bb-420e-a47b-ac9a74d85f9d'>|

2024-12-23 15:25 UTC, Redth commented
/azp run

2025-01-02 17:24 UTC, Redth commented
/azp run

2025-01-03 07:21 UTC, NirmalKumarYuvaraj commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5161.cs
> +public Issue5161(TestDevice testDevice) : base(testDevice)
Thank you for identifying the inconsistency in the indentation. I have updated the code to reflect the corrected formatting as suggested.

2025-01-10 08:18 UTC, StephaneDelcroix commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
> +			for (int i = 1; i < TabBar.Items.Length; i++)
start at 1 ?

2025-01-10 08:18 UTC, StephaneDelcroix commented
/azp run

2025-01-20 11:47 UTC, jsuarezruiz commented
/rebase

2025-01-20 11:48 UTC, jsuarezruiz commented
/azp run

2025-01-21 14:45 UTC, StephaneDelcroix commented
/azp run

2025-01-21 14:46 UTC, StephaneDelcroix submitted a review, later dismissed

2025-01-31 16:06 UTC, jfversluis commented
/rebase

2025-02-05 12:39 UTC, rmarinho requested changes
Some little changes, we try not use the private keyword, also we try to use the brackets for making sure  we don't missing something that should be in the if statement. 

When making the changes please rebase on top of main too.

2025-02-05 12:39 UTC, rmarinho commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
> +		private void UpdateCellsEnabled()
```suggestion
	 void UpdateCellsEnabled()
```

2025-02-05 12:39 UTC, rmarinho commented on src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
> +		private void OnShellItemPropertyChanged(object? sender, PropertyChangedEventArgs e)
```suggestion
		void OnShellItemPropertyChanged(object? sender, PropertyChangedEventArgs e)
```

2025-02-05 12:39 UTC, rmarinho commented on src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
> +				return;
```suggestion
			if (_mainLevelTabs == null || sender is not BaseShellItem shellItem)
			{
				return;
			}
```

2025-02-05 13:56 UTC, Dhivya-SF4094 commented on src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
> +		private void UpdateCellsEnabled()
Removed private keyword. Could you please review.

2025-02-05 13:56 UTC, Dhivya-SF4094 commented on src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
> +		private void OnShellItemPropertyChanged(object? sender, PropertyChangedEventArgs e)
Removed private keyword. Could you please review.

2025-02-05 13:57 UTC, Dhivya-SF4094 commented on src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
> +				return;
Ensured brackets {} are used for if statements to prevent potential issues.

2025-03-25 07:57 UTC, jsuarezruiz commented
/rebase

2025-03-25 08:08 UTC, jsuarezruiz commented
/rebase

2025-03-26 08:04 UTC, jsuarezruiz commented
/rebase

2025-03-26 08:39 UTC, jsuarezruiz commented
/azp run

2025-07-14 17:52 UTC, rmarinho submitted a review, later dismissed

2025-07-14 17:53 UTC, rmarinho commented
/azp run

2025-07-16 05:28 UTC, jsuarezruiz commented
/azp run

2025-07-28 11:02 UTC, jsuarezruiz commented
/azp run

2025-08-28 13:18 UTC, jfversluis commented
/rebase

2025-11-13 07:04 UTC, sheiksyedm commented
/rebase

2025-11-13 07:53 UTC, sheiksyedm commented
/azp run

2025-12-22 10:43 UTC, sheiksyedm commented
/rebase

2026-02-20 13:59 UTC, rmarinho commented
<!-- AI Summary -->

## 🤖 AI Summary

<!-- SECTION:PR-REVIEW -->
<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed CI failure for windows platform</strong> · <a href="https://github.com/dotnet/maui/commit/9cd908ac9f63078a8d57fc2cbf0e6850a2610e20"><code>9cd908a</code></a></summary>

---

**Issue:** #5161 - ShellContent IsEnabledProperty does not work (also fixes #32996)
**PR Author:** NirmalKumarYuvaraj (community/Syncfusion)
**Platforms Affected:** iOS, Android (issue report), Windows (PR also fixes)
**Files Changed:** 4 implementation files, 3 test files

### Summary
Shell tabs with `IsEnabled=false` remain interactive. The tab can still be tapped and navigated to.

### Fix Approach
 `TabBar.Items[i].Enabled`
- **Windows**: Added `IsEnabled` property to `NavigationViewItemViewModel`, bound it in `TabbedPageStyle.xaml`, and added `OnShellItemPropertyChanged` to handle runtime changes in `ShellItemHandler.Windows.cs`

### Reviewer Feedback Status
| File | Reviewer | Feedback | Status |
|------|----------|----------|--------|
|  | rmarinho | Remove  keyword |  Applied |
|  | rmarinho | Remove  keyword |  Applied |
|  | rmarinho | Use brackets for if statements |  Applied |
|  | MartyIX | Fix constructor indentation |  Applied |
| `ShellItemRenderer.cs:317` | StephaneDelcroix | "start at 1?" (loop index  No explicit response |question) | 

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #26728 | Map IsEnabled to TabBar.Items on iOS; Add IsEnabled ViewModel + handler on    PENDING (Gate) | `ShellItemRenderer.cs`, `ShellItemHandler.Windows.cs`, `TabbedPageStyle.xaml`, `TabbedPage.Windows.cs`, `NavigationViewItemViewModel.cs` | Original PR |Windows |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed CI failure for windows platform</strong> · <a href="https://github.com/dotnet/maui/commit/9cd908ac9f63078a8d57fc2cbf0e6850a2610e20"><code>9cd908a</code></a></summary>

---

** FAILEDResult:** 
**Platform:** ios
**Mode:** Full Verification

- Tests FAIL without  NO (tests PASSED without fix)fix: 
- Tests PASS with fix YES: 

**Root Cause of Gate Failure:**
The tests pass WITHOUT the PR's fix because the iOS bug was **already fixed in the base branch** (`a6129347`). The base branch contains `SetTabItemsEnabledState()` which handles the same initial IsEnabled state that the PR's `UpdateCellsEnabled()` adds. The PR's iOS changes are therefore **redundant**.

The base branch already has:
1. `SetTabItemsEnabledState()` - sets initial IsEnabled state in `CreateTabRenderers`
2. `OnShellSectionPropertyChanged()` - handles runtime IsEnabled changes
3. iOS 26-specific handling in a separate code path

The Windows changes (new `IsEnabled` property in `NavigationViewItemViewModel`, `TabbedPageStyle.xaml` binding, and `OnShellItemPropertyChanged`) are **genuinely new** - the base branch does NOT have Windows `IsEnabled` support. However, the test is `PlatformAffected.iOS` only and does not cover Windows.

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed CI failure for windows platform</strong> · <a href="https://github.com/dotnet/maui/commit/9cd908ac9f63078a8d57fc2cbf0e6850a2610e20"><code>9cd908a</code></a></summary>

---

**Status:** SKIPPED - Gate did not pass

Gate failed because the iOS bug was already fixed in the base branch (`SetTabItemsEnabledState()` in `a6129347`). try-fix exploration was not performed as it requires Gate to pass first.

**Selected Fix:** N/A (Gate not passed)
**Exhausted:** N/A

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Fixed CI failure for windows platform</strong> · <a href="https://github.com/dotnet/maui/commit/9cd908ac9f63078a8d57fc2cbf0e6850a2610e20"><code>9cd908a</code></a></summary>

---

Final Recommendation: REQUEST CHANGES## 

### Summary

PR #26728 fixes `ShellContent.IsEnabled` not being respected for tabs in Shell on iOS, Windows, and macOS. The PR is a community contribution (Syncfusion/NirmalKumarYuvaraj) targeting issue #5161.

**Gate outcome**: Tests pass both with and without the PR's iOS fix because the iOS bug was **already fixed in the base branch** via `SetTabItemsEnabledState()`. The Windows fix is genuinely new and valid, but contains an event subscription bug that needs correction.

---

### Root Cause (Original Bug)

`ShellSection.IsEnabled = false` was not applied to native tab items when tabs were first created, and not mapped to the Windows NavigationView at all. On iOS, the initial enabled state was never applied to `UITabBarItem.Enabled`. On Windows, `NavigationViewItemViewModel` had no `IsEnabled` property.

---

### Code Review Findings

#### 
**File**: `src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs`

`MapMenuItems()` is called from multiple places (initial `ConnectHandler`, `OnItemsChanged`, `UpdateTitle()`, `UpdateCurrentItem()`). Each call adds `item.PropertyChanged += OnShellItemPropertyChanged` **without first removing it**. Since `DisconnectHandler` only removes one subscription per item, this creates dangling event handlers and duplicate `OnShellItemPropertyChanged` calls.

**Fix needed**: Unsubscribe before subscribing:
```csharp
item.PropertyChanged -= OnShellItemPropertyChanged;
item.PropertyChanged += OnShellItemPropertyChanged;
```

#### 
**File**: `src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs`

The base branch (`a6129347`) already contains `SetTabItemsEnabledState()` which applies the initial IsEnabled state to tab items in both `CreateTabRenderers()` and `OnItemsCollectionChanged()`. The PR's `UpdateCellsEnabled()` does the same thing and is now **redundant**. Having both called in sequence in `CreateTabRenderers()` is confusing.

The PR's `MaxTabs` constant (replacing the magic number `5`) is a valid cleanup, but `UpdateCellsEnabled()` itself should be removed.

#### 
**File**: `src/Controls/tests/TestCases.HostApp/Issues/Issue5161.cs`

The test host app class is marked `PlatformAffected.iOS` only, but the PR fixes Windows (and potentially Android/macOS) as well. No test validates the Windows behavior.

---

### What's Good About This PR

- Windows `IsEnabled` support is genuinely new and a real fix
- `NavigationViewItemViewModel.IsEnabled` property follows existing patterns (`IsSelected`)
- XAML binding approach (`IsEnabled="{Binding IsEnabled}"`) is clean and idiomatic
- `OnShellItemPropertyChanged` correctly handles runtime `IsEnabled` changes on Windows
- `DisconnectHandler` properly unsubscribes (the subscription leak is fixable)
- Reviewer feedback (remove `private` keyword, add brackets) was addressed

---

### Requested Changes

1. **[Critical]** Fix duplicate event subscription in `MapMenuItems()`:
   ```csharp
   item.PropertyChanged -= OnShellItemPropertyChanged;  // Add this line
   item.PropertyChanged += OnShellItemPropertyChanged;
   ```

2. **[Important]** Remove redundant `UpdateCellsEnabled()` from `CreateTabRenderers()` on iOS. The `SetTabItemsEnabledState()` call (already there) handles the same thing. Remove both the method call and the method definition, or consolidate into `SetTabItemsEnabledState()`.

3. **[Recommended]** Expand test to cover Windows: add `PlatformAffected.All` or at minimum document which platforms the test covers, and consider adding a Windows-specific test.

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed |  [...]

2026-02-20 14:18 UTC, jfversluis commented
@NirmalKumarYuvaraj looks like this is probably already fixed by https://github.com/dotnet/maui/pull/33369 and or https://github.com/dotnet/maui/pull/33337 can you confirm?

2026-02-23 05:05 UTC, Dhivya-SF4094 commented
> @NirmalKumarYuvaraj looks like this is probably already fixed by #33369 and or #33337 can you confirm?

@jfversluis I have validated this PR against the latest main after the recent iOS changes were merged.
The issue is now fully resolved on the iOS platform by the merged PR, so the iOS-specific changes included in this PR are no longer required.
However, I re-verified the behavior on the Windows platform, and the issue still reproduces there. The Windows fix included in this PR is still necessary and works as expected.

2026-02-23 15:51 UTC, jfversluis approved these changes

2026-02-23 15:55 UTC, merged