[iOS] [Android] Fix for the FontImageSource color is not applied properly to the Tab Icon
dotnet/maui pull request #26757
Opened 2024-12-20 16:15 UTC by Tamilarasan-Paranthaman

### Root Cause of the issue 

#### iOS

- The regression occurred because a previous PR changed the UIImageRenderingMode to Automatic, causing the TabbedPage tab icon to ignore the FontImageSource.Color.
 
#### Android
 
- In Android, setting the FontImageSource.Color does not apply to the TabbedPage icon.

### Description of Change

#### iOS
I have resolved the issue by setting the UIImageRenderingMode to Automatic when the FontImageSource is null. If the color is already applied to the FontImageSource, the UIImageRenderingMode is set to AlwaysOriginal.
 
#### Android
 
 
I have fixed the TabIcon color issue for the default TabBar placement in the SetIconColorFilter method. If the FontImageSource color is specified in the sample, it returns null and no need to update the color. If the FontImageSource color is null, the method retrieves the color using GetItemIconTintColorState to apply the appropriate color based on SelectedTabColor and UnselectedTabColor.
 
Additionally, some common cases were broken in the GetItemIconTintColorState method. For example, if no SelectedTabColor, UnselectedTabColor, or ContentPage FontImageSource color is provided, the TabIcons should use the default color. However, the method was returning null prematurely, preventing the default color from being applied to the TabIcons.
 
I have also addressed these additional cases. For instance, if none of the SelectedTabColor, UnselectedTabColor, or ContentPage FontImageSource colors are specified, the TabIcons will now correctly use the default color.
 

### Regressed PR

- https://github.com/dotnet/maui/pull/22437

### Revert PR

- https://github.com/dotnet/maui/pull/26048

### Issues Fixed

Fixes #26662

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

#### Android

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <img src="https://github.com/user-attachments/assets/4fdb405c-4e0b-4ac9-bfa7-58d793dca3ca"> | <img  src="https://github.com/user-attachments/assets/cb0464bf-7f9f-4165-95e1-3459d07245ae"> |

#### iOS

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <img  src="https://github.com/user-attachments/assets/4162fdaf-8e29-4e2c-8b72-56e7a41fb0d2"> | <img src="https://github.com/user-attachments/assets/6d62e00b-be70-4658-b773-a42f4e5abdca"> |

2025-01-10 07:36 UTC, jsuarezruiz commented
/azp run

2025-01-18 17:55 UTC, jfversluis commented
/rebase

2025-01-20 11:43 UTC, jsuarezruiz commented
/rebase

2025-01-29 23:16 UTC, PureWeen requested changes

2025-01-29 23:16 UTC, PureWeen commented on src/Controls/tests/TestCases.HostApp/Issues/Issue26662.xaml.cs
> +					Color = Colors.Violet,
Can we add a test that only changes the Color on the FontImageSource and verify that that will update the color?

2025-01-31 06:29 UTC, Ahamed-Ali commented on src/Controls/tests/TestCases.HostApp/Issues/Issue26662.xaml.cs
> +					Color = Colors.Violet,
Hi @PureWeen ,

Changing the `Color` property directly in `IconImageSource` does not trigger notifications at the Source level.

In TabbedPageManager on Android, `Page.PropertyChanged `only detects changes to IconImageSource, and this behavior is consistent across all platforms.

Currently, FontImageSource property changes are not handled in the TabbedPage implementation across platforms. We may need to add support for these changes to ensure proper updates.

Additionally, the user is following the same approach used in our test sample.

2025-02-03 21:10 UTC, PureWeen commented on src/Controls/tests/TestCases.HostApp/Issues/Issue26662.xaml.cs
> +					Color = Colors.Violet,
It should trigger on the Source Level

changing the color triggers a source changed event

![image](https://github.com/user-attachments/assets/e19439a0-fc63-4254-9fd1-fdeb94ea8b94)

which fires a source changed event
![image](https://github.com/user-attachments/assets/cffed497-6406-4947-a8fd-0fc1c3718614)

It seems like we're just doing a bad job of listening for that event? 

I don't think we need to block this PR on this but it seems like we should be watching for the SourceChanged event more places and then reacting based on that. Can you create an issue?

2025-02-03 21:12 UTC, PureWeen approved these changes, later dismissed

2025-02-04 08:17 UTC, Ahamed-Ali commented on src/Controls/tests/TestCases.HostApp/Issues/Issue26662.xaml.cs
> +					Color = Colors.Violet,
Hi @PureWeen ,
I meant the previous comment, as no implementation was added while changing the image source color property. As you mentioned, I have created a separate issue #[27549](https://github.com/dotnet/maui/issues/27549)  for this

2025-02-05 13:17 UTC, AlleSchonWeg commented
Hi @Tamilarasan-Paranthaman 
in my app i set UnselectedTabColor and SelectedTabColor: 

```XAML
 UnselectedTabColor="{AppThemeBinding Light=Blue, Dark=Red}"
 SelectedTabColor="{AppThemeBinding Light=Yellow, Dark=Green}"
```
i also used FontImageSource , but without a color:
```XAML
<NavigationPage.IconImageSource>
	<FontImageSource FontFamily="..."
					 Glyph="..."
					 Size="20" />
</NavigationPage.IconImageSource>
```

Is this still working if you PR is merged? Do you use UnselectedTabColor/SelectedTabColor is no color is set in FontImageSource?

Thank you

2025-02-06 13:31 UTC, Tamilarasan-Paranthaman commented
> Hi @Tamilarasan-Paranthaman in my app i set UnselectedTabColor and SelectedTabColor:
> 
> ```
>  UnselectedTabColor="{AppThemeBinding Light=Blue, Dark=Red}"
>  SelectedTabColor="{AppThemeBinding Light=Yellow, Dark=Green}"
> ```
> 
> i also used FontImageSource , but without a color:
> 
> ```
> <NavigationPage.IconImageSource>
> 	<FontImageSource FontFamily="..."
> 					 Glyph="..."
> 					 Size="20" />
> </NavigationPage.IconImageSource>
> ```
> 
> Is this still working if you PR is merged? Do you use UnselectedTabColor/SelectedTabColor is no color is set in FontImageSource?
> 
> Thank you

@AlleSchonWeg, I would like to confirm that if no color is specified for the FontImageSource icon, the icon color will be determined by the SelectedTabColor/UnselectedTabColor. Additionally, I have added a test case in this PR to verify that when no color is provided for the FontImageSource icon on the first page, the icon color is correctly applied based on the SelectedTabColor/UnselectedTabColor.

2025-02-27 15:32 UTC, mattleibow reviewed
not quite a review, but we probably don't need to list the issues just the reasoning.

2025-03-03 05:06 UTC, Tamilarasan-Paranthaman commented on src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs
> +			// https://github.com/dotnet/maui/issues/12250
@mattleibow, Got it! I have removed the issue list.

2025-03-03 10:41 UTC, jsuarezruiz commented
/azp run

2025-03-03 18:55 UTC, mattleibow commented on src/Controls/tests/TestCases.HostApp/Issues/Issue26662.xaml.cs
> +					Color = Colors.Violet,
That PR was merged, do we have a test in this PR yet?

2025-03-03 19:07 UTC, mattleibow reviewed
This looks good. I have 2 questions:

* Is there a `myimagesource.Color = newColor` test?
* There may be a bad code path that appears that it will never be hit, but just in case...

2025-03-03 19:07 UTC, mattleibow commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				defaultColor = GetDefaultColor(defaultColor);
If I am understanding the code path of the usage of the `GetDefaultColor`, if the `BarItemColor` is not set, then the value of `defaultColor` that is passed into the method will be the initial 0. In fact, since this is a local variable, it will always be 0. Is that OK?

2025-03-03 19:07 UTC, mattleibow requested changes
Gotta pick red or green for the machine!

2025-03-06 09:44 UTC, Ahamed-Ali commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				defaultColor = GetDefaultColor(defaultColor);
- I have modified the test sample to change the` icon color directly` in the button click event method. 

- I have removed the unnecessary parameter from the `GetDefaultColor` method. 

Could you please review and let us know if you have any other concerns?

2025-03-18 12:18 UTC, jsuarezruiz commented
/rebase

2025-03-18 12:30 UTC, jsuarezruiz commented
/azp run

2025-03-18 13:00 UTC, jsuarezruiz commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +						defaultColor = new Color(1, 1, 1, 0.6f).ToPlatform();
Is possible to use a resource system color?

2025-03-18 17:10 UTC, rmarinho commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +						defaultColor = new Color(1, 1, 1, 0.6f).ToPlatform();
OR point to where in android we grabbed these default values.

2025-03-18 17:13 UTC, rmarinho commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				_orignalTabIconColors = IsBottomTabPlacement ? _bottomNavigationView.ItemIconTintList : _tabLayout.TabIconTint;
```suggestion
			if (_orignalTabIconColors is null)
			{
				_orignalTabIconColors = IsBottomTabPlacement ? _bottomNavigationView.ItemIconTintList : _tabLayout.TabIconTint;
			}
```

2025-03-18 17:14 UTC, rmarinho commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				checkedColor = GetDefaultColor();
```suggestion
			if (barSelectedItemColor is not null)
			{
				checkedColor = barSelectedItemColor.ToPlatform().ToArgb();
			}	
			else
			{
				checkedColor = GetDefaultColor();
			}
```

2025-03-18 17:15 UTC, rmarinho commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				defaultColor = GetDefaultColor();
I would keep the brackets, we prefer it.

2025-03-18 17:18 UTC, rmarinho approved these changes, later dismissed
Just small comments

2025-03-18 17:18 UTC, rmarinho commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
>  #pragma warning disable XAOBS001 // Obsolete
Since we are touching this code, can we check if theres a modern way (not obsolete) to improve getting the style attributes

2025-03-19 13:41 UTC, Ahamed-Ali commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
>  #pragma warning disable XAOBS001 // Obsolete
I have updated the code to retrieve `style attributes` using a modern approach without obsolete method. @rmarinho

2025-03-19 13:43 UTC, Ahamed-Ali commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +						defaultColor = new Color(1, 1, 1, 0.6f).ToPlatform();
- The use of `hardcoded` colors has already been implemented as a fallback. If retrieving the default color from style attributes fails, the application avoids breaking by assigning a predefined default color. 

- I have now updated the code to fetch the resource color and assign it to the default color based on the theme. Please let me know if you have any other concerns. @jfversluis / @rmarinho

2025-03-19 13:44 UTC, Ahamed-Ali commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				defaultColor = GetDefaultColor();
Changed

2025-03-19 13:44 UTC, Ahamed-Ali commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				checkedColor = GetDefaultColor();
Changed

2025-03-19 13:45 UTC, Ahamed-Ali commented on src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
> +				_orignalTabIconColors = IsBottomTabPlacement ? _bottomNavigationView.ItemIconTintList : _tabLayout.TabIconTint;
changed

2025-03-19 17:26 UTC, rmarinho commented
/rebase

2025-03-19 17:27 UTC, rmarinho approved these changes

2025-03-19 17:36 UTC, rmarinho commented
/azp run MAUI-public

2025-03-19 17:46 UTC, rmarinho commented
/azp run MAUI-public

2025-03-19 20:21 UTC, merged