Fix up relevant CA1416 warnings - Set 3
dotnet/maui pull request #26751
Opened 2024-12-20 14:35 UTC by Tamilarasan-Paranthaman

### Description of Change

The CA1416 warnings were already resolved in PR https://github.com/dotnet/maui/pull/26593  

In this PR, we have divided the file changes from the previous PR into smaller, more manageable groups and added test cases for the affected areas to ensure proper functionality.

2024-12-23 15:25 UTC, Redth commented
/azp run

2025-01-06 08:56 UTC, PureWeen commented
/azp run

2025-01-06 15:57 UTC, mattleibow commented
/rebase

2025-01-06 16:15 UTC, mattleibow requested changes
Thanks for the PR, I have a review and I think we can just move to the new things. No need to have old code in here that we have to maintain just because we always had it.

And one small if block change needed.

2025-01-06 16:15 UTC, mattleibow commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
nit: can we reverse the polarity here :) 

It makes it a bit easier to read if the first is the latest version and then the else gets older. If 17 else 16 else 15.

2025-01-06 16:15 UTC, mattleibow commented on src/Core/src/Platform/iOS/MauiUIApplicationDelegate.Menu.cs
> +			if (OperatingSystem.IsMacCatalystVersionAtLeast(16) || OperatingSystem.IsIOSVersionAtLeast(16))
I think this changes the logic? We need to keep the iOS 14 here, but wrap the inner if block on lines 51/53 with this check. We still need to have this block for the fallback on line 66 which is in this main block.

2025-01-06 16:15 UTC, mattleibow commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
Also, why do we need this block for ios 17+? It seems to have been around since iOS 10? Can we just use that code? The UIGraphics style is obsolete in iOS 18, but we don't need to use that as the main flag here.

2025-01-06 16:15 UTC, mattleibow commented on src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs
> +			var renderer = new UIGraphicsImageRenderer(imagesize);
For example, here you switched directly to the new way without keeping the old way. I think this is better? Thoughts?

2025-01-10 13:49 UTC, mattleibow commented
/azp run

2025-01-13 12:05 UTC, Tamilarasan-Paranthaman commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
@mattleibow, it seems that BeginImageContextWithOptions is not supported on iOS 17.0 and later.

<img width="673" alt="image" src="https://github.com/user-attachments/assets/a56ad8eb-4efa-4a99-9c77-7ed4286b0df7" />


<img width="527" alt="image" src="https://github.com/user-attachments/assets/84dbf502-83ce-4022-9b6e-97c7ca90e9be" />




As @mattleibow suggested [here](https://github.com/dotnet/maui/pull/26751#discussion_r1904349779), should we adopt the new approach for older versions as well, @PureWeen?
 
```C#

public Task<IScreenshotResult> CaptureAsync(UIWindow window)
{
	_ = window ?? throw new ArgumentNullException(nameof(window));

	using var renderer = new UIGraphicsImageRenderer(window.Bounds.Size);
	var resultImage = renderer.CreateImage((UIGraphicsImageRendererContext imageContext) =>
	{
		if (!TryRender(window, out _))
		{
			// TODO: test/handle this case
		}
	});
	var screenshotResult = new ScreenshotResult(resultImage);
	return Task.FromResult<IScreenshotResult>(screenshotResult);
}

var screenshotResult = new ScreenshotResult(resultImage);
return Task.FromResult<IScreenshotResult?>(screenshotResult);
```

Could you please share your thoughts on this, @PureWeen ?

2025-02-13 08:33 UTC, StephaneDelcroix approved these changes, later dismissed

2025-02-27 15:52 UTC, jfversluis approved these changes, later dismissed

2025-03-03 17:57 UTC, mattleibow requested changes
I think we should just use the new mechanism for drawing and not have the old way and checks.

2025-03-03 17:57 UTC, mattleibow commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
Can we just replace and use the new method?

2025-03-03 17:57 UTC, mattleibow commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
Can we use the new method here instead of the different mechanisms.

2025-03-03 17:57 UTC, mattleibow commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			using var renderer = new UIGraphicsImageRenderer(layer.Bounds.Size);
Just use the new way.

2025-03-03 17:57 UTC, mattleibow commented on src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
Just use the new way for both chunks here.

2025-03-04 13:43 UTC, Tamilarasan-Paranthaman commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
@mattleibow, I have removed the old approach.

2025-03-04 13:43 UTC, Tamilarasan-Paranthaman commented on src/Essentials/src/Screenshot/Screenshot.ios.cs
> +			using var renderer = new UIGraphicsImageRenderer(layer.Bounds.Size);
Modified

2025-03-04 13:43 UTC, Tamilarasan-Paranthaman commented on src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs
> +			if (!OperatingSystem.IsIOSVersionAtLeast(17))
I have modified it

2025-05-13 12:51 UTC, rmarinho commented
Can we please rebase maybe target the inflight branch is better

2025-05-15 07:47 UTC, Tamilarasan-Paranthaman commented
> Can we please rebase maybe target the inflight branch is better

@rmarinho, I have rebased the branch, resolved the conflicts, and updated the target to the `inflight/current`  branch. Please have a look and let me know if you have any concerns.

2025-05-22 23:15 UTC, mattleibow requested changes
I think something went wrong with the rebase/merge... :(

2025-05-22 23:15 UTC, mattleibow commented
@PureWeen you broke it! 😿

2025-05-23 11:20 UTC, Tamilarasan-Paranthaman commented
> I think something went wrong with the rebase/merge... :(

@mattleibow  I have rebased the branch and resolved the conflicts. Please have a look and let me know if you have any concerns.

2025-05-24 12:42 UTC, mattleibow approved these changes

2025-05-24 12:43 UTC, merged