[iOS] Flyout Items Not Displayed in RightToLeft FlowDirection in Ladscape - fix
dotnet/maui pull request #26762
Opened 2024-12-20 16:55 UTC by kubaflo

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26726

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/b30521bb-e013-49fa-bd3b-e015c5b19c18" width="300px"/>|<video src="https://github.com/user-attachments/assets/17427d27-5670-40dc-b96e-7f9e374847b4" width="300px"/>|

2024-12-25 15:31 UTC, jfversluis commented
/azp run

2025-01-10 07:35 UTC, jsuarezruiz requested changes
Could you include a test? Let me know if needs something.

2025-01-11 11:56 UTC, kubaflo commented
> Could you include a test? Let me know if needs something.

Done :)

2025-08-07 09:41 UTC, jfversluis commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2818.cs
> +	[FailsOnIOSWhenRunningOnXamarinUITest] //https://github.com/dotnet/maui/issues/26726
Why is this added? Isn't that what we're trying to fix wit this PR?

2025-08-07 09:41 UTC, jfversluis approved these changes, later dismissed

2025-08-07 12:20 UTC, jfversluis commented
/rebase

2025-08-07 23:19 UTC, kubaflo commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2818.cs
> +	[FailsOnIOSWhenRunningOnXamarinUITest] //https://github.com/dotnet/maui/issues/26726
I've modified this test a bit to work in MAUI. It should work now. I'm not a fan of `await Task.Delay(2000);` that I've added, but I can't find other sensible way

2025-08-07 23:28 UTC, PureWeen commented
/azp run

2025-08-08 00:17 UTC, kubaflo commented
Hi @anandhan-rajagopal, do you happen to have any ideas on how we can avoid using Task.Delay in the UITest I’ve modified?

2026-03-05 01:07 UTC, kubaflo commented
<!-- AI Summary -->

## 🤖 AI Summary

<!-- SECTION:PR-REVIEW -->
<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Stabilize window size check in Issue2818 test</strong> · <a href="https://github.com/dotnet/maui/commit/bef57ff151c1bf291218419ed5dc9b60043ffd04"><code>bef57ff</code></a></summary>

---

**Issue:** #26726 - Flyout Items Not Displayed in RightToLeft FlowDirection on iOS in Landscape Orientation and Hamburger Icon Positioned Incorrectly
**PR:** #26762 - [iOS] Flyout Items Not Displayed in RightToLeft FlowDirection in Landscape - fix
**Platforms Affected:** iOS only
**Files Changed:** 1 implementation file, 1 test file

### Issue Summary
When `FlowDirection` is set to `RightToLeft` on a `FlyoutPage`, in landscape orientation on iOS:
- The flyout items are not visible when the flyout is opened
- The hamburger menu icon appears on the left instead of the right

### Fix Analysis
**File:** `src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs`

```diff
-flyoutFrame.X = (int)(flyoutFrame.Width * .25);
+flyoutFrame.X = (int)(frame.Width - flyoutFrame.Width);
```

In `LayoutChildren()`, when `IsRTL && !FlyoutOverlapsDetailsInPopoverMode`, the flyout's X position was being set to 25% of the flyout width. This means in landscape (wider screen), the flyout was being positioned off-screen or at an incorrect location. The fix correctly aligns the flyout to the right edge: `frame.Width - flyoutFrame.Width`.

### Test Changes
**File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2818.cs`
- Removed `TEST_FAILS_ON_IOS` compile guard, enabling the test to run on iOS
- Added new async test `RootViewSizeDoesntChangeAfterBackground` with a polling loop (up to 50100ms) to wait for window size to stabilize after backgrounding/foregrounding the app

### Reviewer Discussion
| Reviewer | Comment | Status |
|----------|---------|--------|
| jsuarezruiz | Requested test be added Resolved - test added | | 
| jfversluis | Asked about Task.Delay usage Resolved - author used polling loop instead | | 

### Potential Concerns
- The `[Issue]` attribute in `TestCases.HostApp/Issues/XFIssue/Issue2818.cs` has `PlatformAffected.Android` though the issue is iOS-specific. The test itself runs on iOS (the #if guard condition controls platform).
- The polling loop in `RootViewSizeDoesntChangeAfterBackground` (50100ms max = 5s) is a valid pattern per UITest guidelines.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #26762 | Correct flyout X position in RTL+landscape: `frame.Width - flyoutFrame.   PENDING (Gate) | `PhoneFlyoutPageRenderer.cs` (+1/-1) | Original PR |Width` |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Stabilize window size check in Issue2818 test</strong> · <a href="https://github.com/dotnet/maui/commit/bef57ff151c1bf291218419ed5dc9b60043ffd04"><code>bef57ff</code></a></summary>

---

** PARTIAL - Environment IssueResult:** 
**Platform:** ios
**Mode:** Full Verification

### Test Results

| Check | Expected | Actual | Result |
|-------|----------|--------|--------|
| Tests WITHOUT fix | FAIL | FAIL | | 
| Tests WITH fix | PASS |  |FAIL | 

### Detailed Results (WITH fix)

-  `RootViewMovesAndContentIsVisible` - **PASSED** [4 sec] - This test directly validates the RTL flyout positioning fix
 `RootViewSizeDoesntChangeAfterBackground` - **FAILED** [5 sec] - TearDown error: `Unable To Rotate Device`- 
-  `LabelWithPaddingIsNotTruncated` - **PASSED** [545 ms]

### Analysis

The Gate failure is due to an **environment issue** in TearDown, NOT a failure of the fix itself:

1. The test body of `RootViewSizeDoesntChangeAfterBackground` appears to have passed (no assertion error was thrown - only TearDown failed)
2. The TearDown calls `App.SetOrientationPortrait()` which throws `OpenQA.Selenium.UnknownErrorException : Unable To Rotate Device` - this is an iOS 26 simulator infrastructure issue
3. The primary test  (which directly tests the RTL flyout visibility bug) **PASSED** 

### Conclusion

Gate is marked as **FAILED** due to the environment-related TearDown rotation issue. The fix behavior itself appears correct based on the primary test passing.

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Stabilize window size check in Issue2818 test</strong> · <a href="https://github.com/dotnet/maui/commit/bef57ff151c1bf291218419ed5dc9b60043ffd04"><code>bef57ff</code></a></summary>

---

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #26762 | Correct flyout X position in RTL+landscape:  | , TearDown env  | `PhoneFlyoutPageRenderer.cs` (+1/-1) | Original PR |issue 

**Exhausted:** N/A - Fix phase skipped (Gate failed due to environment issue)
**Selected Fix:** PR's fix - Gate failure was due to an environment/infrastructure issue (iOS simulator `Unable To Rotate Device` in TearDown), not a failure of the fix logic. Primary test `RootViewMovesAndContentIsVisible` PASSED.

### Reason for Skipping Fix Phase

Gate failed with . Per autonomous execution rules, when Gate fails due to environment issues, the Fix phase is skipped and we proceed to Report. The primary test () that directly validates the RTL flyout positioning bug PASSED .

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Stabilize window size check in Issue2818 test</strong> · <a href="https://github.com/dotnet/maui/commit/bef57ff151c1bf291218419ed5dc9b60043ffd04"><code>bef57ff</code></a></summary>

---

##  Final Recommendation: APPROVE

### Summary

PR #26762 fixes a 1-line bug in `PhoneFlyoutPageRenderer.cs` that caused the flyout panel to be incorrectly positioned when `FlowDirection` is `RightToLeft` in landscape orientation on iOS. The fix is correct, minimal, and the primary validation test passed.

### Root Cause

In `LayoutChildren()`, the RTL flyout X position was calculated as:
```csharp
flyoutFrame.X = (int)(flyoutFrame.Width * .25);
```
This formula doesn't position the flyout at the right edge of the screen. In landscape mode (e.g., frame.Width=844, flyoutFrame.Width=312), this gives X= placing the flyout partially overlapping the content from the left side, making flyout items appear hidden.78 

The fix correctly calculates the right-aligned position:
```csharp
flyoutFrame.X = (int)(frame.Width - flyoutFrame.Width);
```
This positions the flyout so its right edge aligns with the screen's right edge (X=532 for the example above), which is the correct RTL behavior.

### Fix Quality

**Implementation (PhoneFlyoutPageRenderer.cs Excellent):** 
- Minimal 1-line change in exactly the right location
- Mathematically correct: `frame.Width - flyoutFrame.Width` is the standard formula for right-aligning an element
- No side effects on other code paths (only applies when `IsRTL && !FlyoutOverlapsDetailsInPopoverMode`)

**Tests (Issue2818.cs Good):** 
- Correctly removes `TEST_FAILS_ON_IOS` from the compile guard, enabling the existing `RootViewMovesAndContentIsVisible` test on iOS
- Adds `RootViewSizeDoesntChangeAfterBackground` to validate post-background stability
- Uses polling loop (50100ms max) which is a valid UITest pattern

### Test Results

| Test | Status | Notes |
|------|--------|-------|
|  |  PASSED | Primary test: validates RTL flyout visibility |
| ` TearDown env error | Test body lik [...]

2026-03-05 12:56 UTC, merged