Picker Selected item gets cleared in BindableLayout - Fix
dotnet/maui pull request #26777
Opened 2024-12-23 02:34 UTC by kubaflo

### Description of Change

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25729

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/93d5e25e-a1a8-4333-ba36-46f03ccdc573" width="300px"/>|<video src="https://github.com/user-attachments/assets/234ae49c-8c9b-4516-804d-ba83eb98e89e" width="300px"/>|

2024-12-23 03:30 UTC, PureWeen commented
/azp run

2025-01-06 15:53 UTC, rmarinho commented
Is it possible to add a test?

2025-01-06 16:48 UTC, kubaflo commented
@rmarinho I've added a UiTest :)

2025-01-06 17:23 UTC, mattleibow commented on src/Controls/src/Core/Picker/Picker.cs
> +			ResetItems(oldValue as IList, newValue as IList);
private.

2025-01-06 17:27 UTC, mattleibow commented on src/Controls/src/Core/Picker/Picker.cs
> +			if (oldValue is null || (newValue?.Count ?? -1) < oldValue.Count)
I feel like I am missing something here. What was the cause of the issue that resulted in items being cleared? This appears to just make sure that the clamping only happens if there was no previous value or if there are less/no items in the new list.

Was there some ordering issue where it would always reset to -1 or something?

2025-01-06 18:43 UTC, kubaflo commented on src/Controls/src/Core/Picker/Picker.cs
> +			if (oldValue is null || (newValue?.Count ?? -1) < oldValue.Count)
This method 'ClampSelectedIndex()'

```c#
void ClampSelectedIndex()
{
	var oldIndex = SelectedIndex;
	var newIndex = SelectedIndex.Clamp(-1, Items.Count - 1);
	//FIXME use the specificity of the caller
	SetValue(SelectedIndexProperty, newIndex, SetterSpecificity.FromHandler);
	// If the index has not changed, still need to change the selected item
	if (newIndex == oldIndex)
		UpdateSelectedItem(newIndex);
}
```

2025-01-07 16:48 UTC, mattleibow commented on src/Controls/src/Core/Picker/Picker.cs
> +			if (oldValue is null || (newValue?.Count ?? -1) < oldValue.Count)
I see, but why does the clamping only need to happen sometimes? Or is it a bad-ish name and it is just for the SetValue line firing when it shouldn't? What happens now when the UpdateSelectedItem no longer fires? Will the SelectedItem not be updated, or will it happen later?

I am not sure I see how the "only update if it was null before" matters if the clamped value will end up in the same place. Assuming it was at pos -1 with a null list, we add a list and the pos is still -1. We change the list and the pos should still be -1. Or if it was pos 10 and the new list is 15 items, the clamped value should stay 10 and we would still want the updated SelectedItem.

2025-01-07 16:48 UTC, mattleibow commented
/azp run

2025-01-07 17:00 UTC, kubaflo commented on src/Controls/src/Core/Picker/Picker.cs
> +			if (oldValue is null || (newValue?.Count ?? -1) < oldValue.Count)
It is more like this: 
When the binding is applied one more time, the ItemsCount is initially equal to 0 before it gets to it previous count and because of it the newIndex is set to -1

2025-01-07 18:26 UTC, mattleibow requested changes
Something strange is happening here. I made some changes to bind the selected index and it seems to clamp across VMs. For example, one picker has 3 items and the other has 4. Picking the last item in the 4, and then switching back to the 3 seems to update the VM to also be 3.

https://github.com/dotnet/maui/commit/29b3f3c7797ce7c375360223cb2fb5e5ae7942c0

Not sure if it is related...

https://github.com/user-attachments/assets/301a4b15-3931-44f3-b341-e0a1ee00ce2e

2025-01-07 18:31 UTC, kubaflo commented
> Something strange is happening here. I made some changes to bind the selected index and it seems to clamp across VMs. For example, one picker has 3 items and the other has 4. Picking the last item in the 4, and then switching back to the 3 seems to update the VM to also be 3.
> 
> [29b3f3c](https://github.com/dotnet/maui/commit/29b3f3c7797ce7c375360223cb2fb5e5ae7942c0)
> 
> Not sure if it is related...
> 
>  Media1.mp4

I see that's not good. I'm trying to find another fix. I have a suspicion that the fix will involve SelectedIndex, because it is always set to 0 on iOS on context change

2025-01-07 18:35 UTC, mattleibow commented
I just found out that this also happens with the selected ITEM. If you go from 4 items to 3 items, then going back to the 4 items results in the selection being null. Somehow...


https://github.com/user-attachments/assets/fa4404ad-34a7-49b2-b3d2-ba4dd3cab9e4

2025-01-08 01:12 UTC, kubaflo commented
@mattleibow I've discovered a simpler fix. Basically there's no need for 
<img width="662" alt="Screenshot 2025-01-08 at 02 07 27" src="https://github.com/user-attachments/assets/2f6ac2d0-71ed-4a3a-acd8-74ea49657af7" />
And this creates our unexpected behavior

Hi @BurningLights Is there a super important reason that I've missed, so that it cannot be removed?
https://github.com/dotnet/maui/pull/19728

2025-01-08 04:11 UTC, BurningLights commented
So, that code was some pre-existing code that was repeated in various methods and @PureWeen consolidated it in the one method as part of the pull request. As I understand it, that code is needed for cases with an ObservableCollection source, when the collection is updated that changes what item is at the SelectedIndex. For instance, if the SelectedItem is 4 and the item at index 2 is removed, the SelectedIndex will stay the same, but the SelectedItem changes to be what used to be the SelectedItem moves to index 3 and what was at index 5 is now the SelectedItem.

2025-01-08 19:42 UTC, kubaflo commented
@BurningLights thanks for joining this discussion!

I checked `if (newIndex == oldIndex && newIndex != -1)`, but it didn't work :////

However, I think I've found even a simpler solution, please have a look if you can :)

FYI @mattleibow

2025-01-09 01:00 UTC, BurningLights commented
I suspect that will make the TestSelectedIndexAssignedItemsSourceCollectionChangedClear Picker test fail, but if it doesn't, then I guess there's a different spot that updates the SelectedItem on a collection reset, so it would work.

2025-01-09 02:30 UTC, BurningLights commented
I think I've found the underlying bug, which, when fixed, could solve a lot of issues. It appears to me that this is not just a unique Picker issue, but an issue with changing the `BindingContext` in general. 

As an example, say Section 1 is displaying and Item 2 (`SelectedIndex` 1) is selected. Switching to Section 2 first updates the `ItemsSource` for the Picker with Section 2's Choices. That update works its way to the `ClampSelectedIndex` method, where the `SelectedIndex` does not change because Section 1 has 3 items and Section 2 does as well. The `SelectedItem` is updated, however, because the item at index 1 has changed from Item 2 on the Section 1 view model to Item 2 on the Section 2 model. And then the error comes in because this new `SelectedItem` is pushed up to the old binding context, the Section 1 view model, because the old binding has not been unapplied yet.

When switching back to Section 1, then as the bindings apply, the Item 2 from Section 2 is applied down to the Picker `SelectedItem`, which results in no item being selected because Section 1's Choices do not contain Item 2 from Section 2.

I believe this happens because of how changes to the `BindingContext` are handled in `BindableObject`.  `BindingContextPropertyChanged` calls `ApplyBindings(fromBindingContextChanged: true)`
https://github.com/dotnet/maui/blob/29f3c7a72945b9ee8f6f5d1acc9ab4535f1c33c4/src/Controls/src/Core/BindableObject.cs#L731

Which then calls `ApplyBinding` in a loop on each binding
https://github.com/dotnet/maui/blob/29f3c7a72945b9ee8f6f5d1acc9ab4535f1c33c4/src/Controls/src/Core/BindableObject.cs#L698

Which then unapplies that particular binding and then applies the new binding. Each binding has the binding to the old context unapplied and then the binding to the new context applied one-by-one, which means there are still bindings to the old context hanging around until the loop in `ApplyBindings` is complete.

I see there is an `UnapplyBindings` method, but a search of the whole code base shows it is not used anywhere. It seems to me that all of the bindings should be unapplied first, so all connections to the old context are severed, and then all the bindings applied with the new context.

2025-01-09 04:22 UTC, mattleibow commented
@StephaneDelcroix thoughts?

2025-01-23 08:02 UTC, StephaneDelcroix commented on src/Controls/src/Core/Picker/Picker.cs
> -			ClampSelectedIndex();
can you figure out in which case UpdateSelectedIndex invoked from ClampSelectedIndex was useful? I'm worried that by removing that (apparently useless and duplicate) call we might regress something else

2025-01-23 13:26 UTC, kubaflo commented on src/Controls/src/Core/Picker/Picker.cs
> -			ClampSelectedIndex();
@BurningLights do you happen to remember it?

2025-01-23 21:53 UTC, PureWeen commented
/azp run

2025-01-24 04:19 UTC, BurningLights commented on src/Controls/src/Core/Picker/Picker.cs
> -			ClampSelectedIndex();
The `ClampSelectedIndex` call that then calls `UpdateSelectedItem` is necessary for the case where a collection changes in a way that keeps the `SelectedIndex` the same but changes what item is at that index. For instance, removing items at the beginning of the collection, or a complete collection re-ordering/replacement. Commenting out that call breaks some of the Picker unit tests.
![Screenshot 2025-01-23 223936](https://github.com/user-attachments/assets/441ec69c-66f2-4004-9774-b6c555b8db46)

Here is a video using the sample from the original issue, slightly modified to display the currently selected item for both sections, that I believe shows the underlying issue.

https://github.com/user-attachments/assets/d6389cc5-3ec1-4101-9bbe-66e643d5cb2e

Notice how when switching from Section 1 to Section 2, the selected item for section 1 changes from Choice 1.2 to Choice 2.2 from section 2. And then switching back from Section 2 to Section 1, the selected item for section 2 becomes Choice 1.3 from Section 1. Also, section 1 changes to no item being selected, since it is trying to re-select Choice 2.2 from section 2, which does not exist in the list of choices for section 1, which results in the selection being cleared.

I believe this is because of an underlying issue where a change in BindingContext goes through the bindings one-by-one, un-applying the old binding and applying the new binding. As a result, when switching from Section 1 to Section 2 the Picker `ItemsSource` is changed to the options for Section 2, while the binding to the Section 1 is still applied to `SelectedItem`. The `SelectedIndex` of 1 was still valid and so stayed the same, but the item at the index changed from Choice 1.2 from Section 1 to Choice 2.2 from Section 2, which is propagated up to the old Section 1 BindingContext binding to `SelectedItem` because that binding has not been unapplied yet.

It seems to me a proper fix would be when changing BindingContext, un-apply all the bindings to the old context first, and then apply all the new bindings to avoid that kind of cross-contamination. I believe this change could fix a number of issues, including #25729, #25842, and #26532.

2025-08-06 12:06 UTC, mahesh139 commented
any idea when this fix will be available? Google has SDK 35 requirement and we are stuck with Migration from Xamarin forms to MAUI due to this and couple of more issues.

2026-03-03 21:02 UTC, closed without merging