[iOS] Fixed ImageButton not honoring Padding value.
dotnet/maui pull request #26785
Opened 2024-12-23 14:55 UTC by NirmalKumarYuvaraj

### Issue Details

The ImageButton size calculation is incorrect. When an ImageButton has both padding and an image, its measured size does not adapt to include the padding values, causing the image to render smaller than expected.

### Root Cause

The ImageButton DesiredSize is determined solely based on the ImageSize during the SizeThatFitsImage calculation. As a result, the ImageButton renders according to the image size alone, without accounting for the padding values in its measurement.

### Description of Change

Updated the ImageButton to implement ICrossPlatformLayout for handling measurements, ensuring that content measurement accounts for padding values as expected, thereby improving the layout behavior.

**Tested the behaviour in the following platforms**

- [x] Android 
- [x] Windows 
- [x] iOS 
- [x] Mac

### Issue Fixed 
Fixes #22521

### Output
| Before | After |
|--|--|
| <img width="313" alt="image" src="https://github.com/user-attachments/assets/033bc9d0-a19d-431e-979f-0a98e045ba77" /> | <img width="319" alt="image" src="https://github.com/user-attachments/assets/6d0d4ad0-bb69-4bb7-999d-5a1cac184d91" />|

2025-01-06 08:19 UTC, AmrAlSayed0 commented on src/Controls/src/Core/ImageButton/ImageButton.iOS.cs
> +			double contentHeight = imageSize.Height + contentEdgeInsets.Top + contentEdgeInsets.Bottom;
[Thickness](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.thickness?view=net-maui-9.0) has a [HorizontalThickness](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.thickness.horizontalthickness?view=net-maui-9.0) and [VerticalThickness](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.thickness.verticalthickness?view=net-maui-9.0) properties you could use.

2025-01-08 13:12 UTC, jfversluis commented
/azp run

2025-01-08 18:18 UTC, PureWeen requested changes
Padding_Add failing

2025-01-09 08:20 UTC, prakashKannanSf3972 commented
> Padding_Add failing

@PureWeen , The failure was due to the macOS snapshot for Padding_Add not being updated earlier. The Snapshot has been updated, and the test is expected to pass in the next CI run.

2025-01-09 22:38 UTC, PureWeen requested changes
Fix conflicts

2025-01-10 09:15 UTC, prakashKannanSf3972 commented
> Fix conflicts

@PureWeen, Conflicts have been resolved.

2025-01-14 11:14 UTC, jsuarezruiz commented
/azp run

2025-01-14 21:37 UTC, PureWeen requested changes

2025-01-14 21:37 UTC, PureWeen commented on src/Controls/src/Core/ImageButton/ImageButton.iOS.cs
> +#nullable disable
I agree with @MartyIX 

This is a new file and it would be pretty easy to just remove this directive

2025-01-15 09:19 UTC, prakashKannanSf3972 commented
@MartyIX, @PureWeen,

Thank you for the review! The nullable directive code has been removed as suggested.

2025-01-16 19:54 UTC, PureWeen commented
/azp run

2025-01-29 20:30 UTC, PureWeen requested changes
Can you fix the conflicts @NirmalKumarYuvaraj

2025-01-30 06:49 UTC, prakashKannanSf3972 commented
> Can you fix the conflicts @NirmalKumarYuvaraj

@PureWeen, Conflicts have been resolved.

2025-02-03 13:30 UTC, jsuarezruiz commented
/rebase

2025-02-03 15:05 UTC, jsuarezruiz commented
/rebase

2025-02-03 16:32 UTC, jsuarezruiz commented
/azp run

2025-02-06 11:58 UTC, jsuarezruiz requested changes
The test Issue18242Test is failing on iOS. Small differences in the image related with the Padding:
![image](https://github.com/user-attachments/assets/35c44786-7b90-472b-9661-373df2f21344)
Could you review it?

2025-02-07 21:19 UTC, PureWeen commented
/azp run

2025-02-10 22:49 UTC, PureWeen commented
/azp run

2025-02-12 11:02 UTC, jsuarezruiz submitted a review, later dismissed

2025-02-13 09:36 UTC, prakashKannanSf3972 commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImageButtonUITests_Padding_Add_Added.png
@jsuarezruiz,

Updated the macOS snapshots as per your suggestion in the latest commit. Let me know if you have any further concerns. Thanks!

2025-02-13 09:37 UTC, prakashKannanSf3972 commented
> The test Issue18242Test is failing on iOS. Small differences in the image related with the Padding: ![image](https://private-user-images.githubusercontent.com/6755973/410445445-35c44786-7b90-472b-9661-373df2f21344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0MzU4NjEsIm5iZiI6MTczOTQzNTU2MSwicGF0aCI6Ii82NzU1OTczLzQxMDQ0NTQ0NS0zNWM0NDc4Ni03YjkwLTQ3MmItOTY2MS0zNzNkZjJmMjEzNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTNUMDgzMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBlNDI1MDc2MWIyMzg4ZTA0NGZiNDg4NGZkMTk2MTExNjY1Y2NiNTkwOTRiODlmOWM1NGMyZGZhMWMwZTkxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UASPhwnmo0RE16ONbRlh3pruLAi3_I-B_-TxjiCCGeg) Could you review it?



> The test Issue18242Test is failing on iOS. Small differences in the image related with the Padding: ![image](https://private-user-images.githubusercontent.com/6755973/410445445-35c44786-7b90-472b-9661-373df2f21344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0Mzk0ODgsIm5iZiI6MTczOTQzOTE4OCwicGF0aCI6Ii82NzU1OTczLzQxMDQ0NTQ0NS0zNWM0NDc4Ni03YjkwLTQ3MmItOTY2MS0zNzNkZjJmMjEzNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTNUMDkzMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMwY2JmMTllNjZlNWE0YjcxNGZjYmYxODliMzZhODkyNzZlMTIyOTZiNGJjMWU4YTYxNDE1NGNkYzBlYTc3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YnzhZgTe85G36bjjalgGWAwzgDwvPdmFyDKUhbM4bSM) Could you review it?

The failing test case has been verified and resolved. It has been successfully validated locally, and expect it will pass in the next CI run.

2025-02-13 13:00 UTC, PureWeen commented
/azp run

2025-02-13 15:36 UTC, PureWeen requested changes
is there a way we can encapsulate this a bit into this method?
https://github.com/dotnet/maui/blob/dc4af6c860639f9b48a99a04dd2c0e02c19ebc31/src/Core/src/Platform/iOS/ImageViewExtensions.cs#L71

It looks like they are basically the same except for the padding part?

Maybe we can create an internal version of this for now that takes padding?

2025-02-17 14:19 UTC, prakashKannanSf3972 commented
> is there a way we can encapsulate this a bit into this method?
> 
> https://github.com/dotnet/maui/blob/dc4af6c860639f9b48a99a04dd2c0e02c19ebc31/src/Core/src/Platform/iOS/ImageViewExtensions.cs#L71
> 
> It looks like they are basically the same except for the padding part?
> 
> Maybe we can create an internal version of this for now that takes padding?

@PureWeen,

Thanks for the suggestion! I have refactored the code to encapsulate the logic as recommended. The updated method now includes padding values for improved reusability while preserving the existing constraints. Please review and let me know if you have any further feedback!

2025-02-18 16:45 UTC, PureWeen commented
/azp run

2025-02-18 16:46 UTC, PureWeen approved these changes

2025-02-19 19:13 UTC, PureWeen requested changes
Looks like some new images will need to be added to the test

2025-02-21 12:08 UTC, jsuarezruiz commented
/azp run

2025-02-25 07:32 UTC, prakashKannanSf3972 commented
> Looks like some new images will need to be added to the test

New images have been added.

2025-03-02 22:11 UTC, PureWeen approved these changes

2025-03-03 17:44 UTC, merged