Android shadow performance
dotnet/maui pull request #26789
Opened 2024-12-23 16:46 UTC by albyrock87

### Description of Change

Apparently `DrawShadow` has an absurd impact on the performance.
Here's a speedscope from our app sorted by self time descending, also look at total time %!!!
![image](https://github.com/user-attachments/assets/ccee2c72-626e-4619-8ef6-2bf329aca230)

This PR moves the shadow computation to android level to avoid back and forth from C#.

I tried as much as possible to not break signatures.

### Issues Fixed

2024-12-23 16:53 UTC, PureWeen commented
/azp run

2024-12-23 22:45 UTC, PureWeen commented
/rebase

2024-12-23 22:47 UTC, PureWeen commented
/azp run

2024-12-24 13:45 UTC, AmrAlSayed0 commented
I'm late to the party but an attempt to improve shadow's performance was made before here https://github.com/dotnet/maui/pull/10523. Moving the code to the Java side might help but I think what would benefit the most is a shadow cache. All views that have the same size and the same shadow properties (very common scenario in CollectionView items for example) should use the same bitmap. This will eliminate a huge number of calls including C# to Java ones. There is an implementation of the shadow cache in the PR.

2024-12-24 13:50 UTC, albyrock87 commented
@AmrAlSayed0 thanks for sharing, I'll check it out.
This is still a very early WIP.
I also intend using Glide's bitmap pool for this, which should improve the performance by avoiding continuous allocations of the bitmaps.

2025-01-09 16:58 UTC, PureWeen commented
/azp run

2025-01-09 20:05 UTC, PureWeen commented
/azp run

2025-01-10 07:34 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
> +		private Exception? TryVerifyScreenshot(string fileName)
The build is failing at this point, could you take a look?
`D:\a\_work\1\s\src\Controls\tests\TestCases.Shared.Tests\Tests\Issues\Issue24414.cs(20,13): error CS7036: There is no argument given that corresponds to the required parameter 'fileName' of 'Issue24414.TryVerifyScreenshot(string)' [D:\a\_work\1\s\src\Controls\tests\TestCases.iOS.Tests\Controls.TestCases.iOS.Tests.csproj]`

2025-01-10 11:38 UTC, albyrock87 commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
> +		private Exception? TryVerifyScreenshot(string fileName)
@jsuarezruiz stupid mistake, I'm sorry.
It's fixed now, you can run AZP again, thanks!

2025-01-10 15:34 UTC, jonathanpeppers commented on src/Core/src/Platform/Android/WrapperView.cs
> +				float offsetY = Context.ToPixels(Shadow.Offset.Y);
This calls the `Context` property three times in a row. This will call into Java each time, doing the bookkeeping to lookup the C# object.

Can you store `Context` in a local to reuse it?

2025-01-10 15:34 UTC, jonathanpeppers commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/ShadowBitmapPool.java
> +                    Context applicationContext = context.getApplicationContext();
Do you have any details why to use `getApplicationContext`?

It looks like the `ShadowBitmapPool` is used once per `PlatformWrapperView`, which would have the same lifetime as an activity anyway?

If we used a single `ShadowBitmapPool` for the entire application, seems like `getApplicationContext` would be appropriate in that case.

2025-01-10 15:34 UTC, jonathanpeppers commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
> +        this.bitmapPool = ShadowBitmapPool.get(context);
So, we use 1 pool per `PlatformWrapperView`.

Can we use 1 pool for the entire application? That would allow many views to share the pool.

2025-01-10 15:37 UTC, PureWeen commented
/azp run

2025-01-10 23:33 UTC, albyrock87 commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
> +        this.bitmapPool = ShadowBitmapPool.get(context);
Actually that singleton method returns one pool for the entire application, so exactly what you're asking :)

2025-01-10 23:35 UTC, albyrock87 commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/ShadowBitmapPool.java
> +                    Context applicationContext = context.getApplicationContext();
See comment below: we use only one pool.

2025-01-10 23:35 UTC, albyrock87 commented on src/Core/src/Platform/Android/WrapperView.cs
> +				float offsetY = Context.ToPixels(Shadow.Offset.Y);
Good catch!

2025-01-12 17:09 UTC, PureWeen commented
/azp run

2025-01-13 08:37 UTC, AmrAlSayed0 commented
Correct me if I'm wrong but what this is doing is using a _**pool**_ not a _**cache**_. Which means that no 2 views will ever use the same bitmap, it's just that that bitmaps will be reused and recycled instead of being created each time it's needed to better conserve memory.

I was thinking of a cache for when, for example, 200 items in a CollectionView request the **_same exact_** bitmap cuz they have MeasureFirstItem set (hence same size) and have the same template (hence the same shadow properties) and the same bitmap can be set for both.

I know this PR is already doing too much so this maybe an optimization for a later time ..

2025-01-13 09:27 UTC, albyrock87 commented
@AmrAlSayed0 there's a small "cache" at the view's level which reuses the bitmap content when not `shadowInvalidated`.

But from my analysis, this is probably ineffective as every time something changes on the descendants (`requestLayout`) the shadow is being invalidated.

The reason for this invalidation is that the shadow is based on content pixels.
For example, you may have a collection view containing simple Labels with a shadow.
Now every label may have the same height, but the shadow will be different considering the text is different.

This is really a pain as Android doesn't offer a better way to draw a shadow based on the content.

What I've done here though, is detecting if you have a shadow applied to a solid rectangle, or a solid `Border`.
If that's the case the shadow will be drawn based on the shape directly on the rendering `Canvas`: this is super fast and we don't have to worry about bitmaps at all.

Unfortunately there is an edge case not covered, so I'm discussing with the MAUI team what to do.

Thanks for your input on this!

2025-01-14 20:52 UTC, PureWeen commented
/azp run

2025-01-15 11:10 UTC, jsuarezruiz requested changes

2025-01-15 11:10 UTC, jsuarezruiz commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
> +            return 4;
Why use this specific value?

2025-01-15 11:10 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.HostApp/Issues/Issue24414.xaml.cs
> +	private void OnTapGestureRecognizerTapped(object sender, EventArgs e)
Could also update the sample adding another Button to remove/add the shadows at runtime?

2025-01-15 11:10 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
>  		public void Issue24414Test()
The test is failing in all the platforms by differences in the shadows:
![image](https://github.com/user-attachments/assets/b2281854-476e-4fc5-823b-488dfe8afe33)
Maybe commits https://github.com/dotnet/maui/pull/26789/commits/14eecfec039e25a519f83de7053b13fbb6a1d8dc after include the snapshots had an impact?

Could you review the tests? Let me know if needs help with it.

2025-01-15 11:15 UTC, albyrock87 commented on src/Core/src/Platform/Android/WrapperView.cs
> +			_invalidateClip = true;
Yes, it will, and this is also covered in the new `24114` UI test.
The invalidation happens on Java side.

2025-01-15 11:15 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
>  		public void Issue24414Test()
On Android, could use https://github.com/dotnet/maui/blob/daf88668adc3479c15c03a87d8e320ce5f89503f/src/TestUtils/src/UITest.Appium/HelperExtensions.cs#L1771 to get memory info and validate never exceed a value, and avoid detecting degradation in memory consumption due to any change

2025-01-15 11:28 UTC, albyrock87 commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
> +            return 4;
I forgot to remove this, thanks!

2025-01-15 11:29 UTC, albyrock87 commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
>  		public void Issue24414Test()
Actually I have to capture all the shapshots because I changed the UI test.
I will on next commit+azp.

2025-01-15 15:11 UTC, albyrock87 commented
@jsuarezruiz I should have addressed all your feedbacks

2025-01-15 16:40 UTC, PureWeen commented
/azp run

2025-01-16 21:28 UTC, albyrock87 commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
> +			var allowedMemoryIncrease = new Dictionary<string, double>
@jonathanpeppers any suggestions on how to set up this properly?
The test is failing on CI.. maybe I should avoid checking some of them.. what do you think?

2025-01-19 01:12 UTC, albyrock87 commented on src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
> +                background.setBounds(left, top, right - left, bottom - top);
```suggestion
                background.setBounds(0, 0, right - left, bottom - top);
```
https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/view/View.java;l=25123;bpv=1;bpt=1

2025-01-21 15:50 UTC, rmarinho commented
/azp run

2025-01-22 13:13 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
> +				ClassicAssert.LessOrEqual(delta, allowedIncrease, $"Memory counter {counter.Key} increased by {delta * 100}% which is more than the expected {allowedIncrease * 100}%");
```
Memory counter totalPss increased by 1.0483696045116044% which is more than the expected 1%
Assert.That(arg1, Is.LessThanOrEqualTo(arg2))
Expected: less than or equal to 0.01d
But was:  0.010483696045116044d
```

2025-01-27 17:06 UTC, PureWeen commented
/azp run

2025-01-29 21:05 UTC, albyrock87 commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
> +				ClassicAssert.LessOrEqual(delta, allowedIncrease, $"Memory counter {counter.Key} increased by {delta * 100}% which is more than the expected {allowedIncrease * 100}%");
I've got no guidance from the team on how to check this properly so I've removed that part of the UI test in one of the recent commit.

2025-01-31 11:15 UTC, jsuarezruiz commented
/azp run

2025-02-03 10:08 UTC, albyrock87 commented
This PR depends on #27531 to fix MacCatalyst screenshot taking.

2025-02-04 00:19 UTC, PureWeen commented
/rebase

2025-02-04 00:20 UTC, PureWeen commented
/azp run

2025-02-04 11:56 UTC, albyrock87 commented
Failing tests look unrelated.

2025-02-05 09:44 UTC, jsuarezruiz commented on src/Core/tests/DeviceTests/Graphics/GraphicsTests.Android.cs
> +	public void SolidPaintTest(string hexColor)
Added some Device Tests to validate the `IsSolid` extension method.

2025-02-05 09:44 UTC, jsuarezruiz commented
/azp run

2025-02-06 15:28 UTC, jsuarezruiz submitted a review, later dismissed

2025-02-07 12:29 UTC, jsuarezruiz commented
Rebased and updated macOS snapshots after merge https://github.com/dotnet/maui/pull/27531

2025-02-07 12:29 UTC, jsuarezruiz commented
/azp run

2025-02-10 09:47 UTC, jsuarezruiz approved these changes

2025-02-10 16:06 UTC, PureWeen approved these changes

2025-02-10 16:06 UTC, merged