Fix ScrollToPosition.Center behavior in ScrollView on iOS and MacCatalyst
dotnet/maui pull request #26825
Opened 2024-12-26 14:11 UTC by devanathan-vaithiyanathan

### Issue Details
When scrolling a ScrollView using the ScrollToAsync method with the ScrollPosition.Center value, the item is incorrectly centered.

### Root Cause
The scroll offset values allow items to scroll into a negative position, causing the item to be incorrectly centered.
 
### Description of Change
We clamp the scroll offset values to ensure the item does not scroll into a negative position.

### Issues Fixed

Fixes #26760 

Validated the behaviour in the following platforms
 
- [] Android
- [] Windows
- [] iOS
- [] Mac

2025-01-02 17:24 UTC, Redth commented
/azp run

2025-01-31 12:01 UTC, jsuarezruiz commented
/rebase

2025-02-10 08:29 UTC, jfversluis commented
/rebase

2025-02-12 10:56 UTC, jsuarezruiz requested changes
The test ScrollToElement3End fails with small changes on Mac and iOS:
![image](https://github.com/user-attachments/assets/7f6905eb-90a4-4b39-a458-b56af2d47244)

Could you review it and see if is related with the changes?

2025-02-26 12:55 UTC, jsuarezruiz commented
/rebase

2025-02-26 12:56 UTC, jsuarezruiz commented
> > The test **ScrollToElement3End** fails with small changes on Mac and iOS: ![image](https://private-user-images.githubusercontent.com/6755973/412388274-7f6905eb-90a4-4b39-a458-b56af2d47244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0MzAxMzcsIm5iZiI6MTczOTQyOTgzNywicGF0aCI6Ii82NzU1OTczLzQxMjM4ODI3NC03ZjY5MDVlYi05MGE0LTRiMzktYTQ1OC1iNTZhZjJkNDcyNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTNUMDY1NzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY5Y2FkY2VjMWNjNmI0YTJiOTE2NTRmMTM3OGJmNjA3ZDllMjk1MWNmZjE0ZWU5ZmQ2NjEyNDkwY2QxZWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nI3-qX20F27CHKjA9IW1KsJ36mprmwDOvor4jKcqfDA)
> > Could you review it and see if is related with the changes?
> 
> @jsuarezruiz, Yes, the test failure is related to my changes, and the snapshot has a slight difference. Shall I commit the newly generated image?

Yes, thanks in advance.

2025-02-27 11:04 UTC, jsuarezruiz commented
/azp run

2025-02-27 15:24 UTC, rmarinho commented
/rebase

2025-02-27 15:25 UTC, rmarinho commented
/azp run

2025-03-07 07:50 UTC, jsuarezruiz commented
/rebase

2025-03-07 10:33 UTC, jsuarezruiz commented
/azp run

2025-03-25 07:43 UTC, jsuarezruiz commented
/rebase

2025-03-27 07:50 UTC, jsuarezruiz commented
/azp run

2025-05-08 20:48 UTC, PureWeen requested changes, later dismissed
Fix conflict

2025-05-12 06:26 UTC, Shalini-Ashokan commented
> Fix conflict

@PureWeen, I have resolved the conflicts.

2025-05-16 11:36 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2025-05-22 06:41 UTC, jsuarezruiz submitted a review, later dismissed

2025-06-06 23:13 UTC, gdougherty-cbt commented on src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
> +				var minScrollHorizontal = Math.Clamp(request.HorizontalOffset, 0, availableScrollWidth);
Just a heads up, I'm adapting this to fix the issue on my app via an overridden handler and ran into the following issue:

If the ContentSize Width of the scroll view is for whatever reason less than the width of the UIScrollView Frame's width, it causes an argument error.  I'd suggest the following changes to account for it.
```
var minScrollHorizontal = Math.Clamp(request.HorizontalOffset, 0, Math.Max(availableScrollWidth, 0));
var minScrollVertical = Math.Clamp(request.VerticalOffset, 0, Math.Max(availableScrollHeight, 0));
```

2025-06-17 07:41 UTC, Shalini-Ashokan commented on src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
> +				var minScrollHorizontal = Math.Clamp(request.HorizontalOffset, 0, availableScrollWidth);
@gdougherty-cbt,  I have updated the code section based on your suggestions.

2025-08-27 10:07 UTC, jfversluis commented
/rebase

2025-08-27 10:08 UTC, jfversluis commented
/azp run MAUI-UITests-public

2025-12-08 11:03 UTC, StephaneDelcroix approved these changes

2025-12-16 20:54 UTC, merged