Fixed Header and Footer template is not visible in CollectionView
dotnet/maui pull request #26844
Opened 2024-12-27 14:18 UTC by NirmalKumarYuvaraj

### Issue Details:
 
When both the HeaderTemplate and FooterTemplate are declared for a CollectionView, neither template is visible in the view.
 
### Root Cause:
In the StructuredItemsView handler, the UpdateHeader() and UpdateFooter() methods return null for the Header property, resulting in the switch case returning null as well. Additionally, both the Header and MauiContext are found to be null when mapped to the native ListViewBase.Header, causing the header to fail to render properly
 
### Description of Change:
Fixed by recalculating the Header value to account for both the Header and HeaderTemplate. Furthermore, the MauiContext was explicitly passed as a parameter to the ItemTemplateContext during the mapping process. This ensures that the MauiContext is properly associated with ListViewBase.Header, enabling the header to render as expected. Processed same for footer template in UpdateFooter()
 
**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
Issue not reproduced in iOS
 
### Issues Fixed:
 
Fixes #22892
 
### Screenshots
| Before Issue Fix | After Issue Fix |
|--|--|
| <Image src="https://github.com/user-attachments/assets/9690922c-86a2-442a-8007-e71366d26f5a">|<Image src="https://github.com/user-attachments/assets/b3bb96af-9d0c-4179-8fc6-d1196d2a49d2">|

2025-01-06 10:33 UTC, PureWeen commented
/azp run

2025-01-06 10:41 UTC, PureWeen requested changes

2025-01-06 10:41 UTC, PureWeen commented on src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
> +			var header = ItemsView.Header ?? ItemsView.HeaderTemplate;
If we just left this as `var header = ItemsView.Header`

And then just deleted the
case null:

would that do the same thing?

We might still want it to fall through to the `default` case

That way it will set both Header properties on the ListViewBase to null

2025-01-07 12:21 UTC, rmarinho reviewed
Needs some tweaks

2025-01-07 13:31 UTC, mattleibow commented on src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8761.cs
> -}
Maybe add a WaitForElement for the headertoo, then we know both are there.

2025-01-07 13:31 UTC, mattleibow commented on src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
> +			var header = ItemsView.Header ?? ItemsView.HeaderTemplate;
This code feels strange to me. The switch has logic in the default for the template as well as this variable. I wonder if this needs to be a simpler if block. Sort of what Rui is saying with the boolean.

```cs
if (ItemsView.Header is string text) {
  // explicit header text
  // ...
} else if (ItemsView.Header is View view) {
  // explicit header view 
  // ...
} else if (ItemsView.HeaderTemplate is DataTemplate template) {
  // header template
  // ...
} else {
  // both are null
  ListViewBase.HeaderTemplate = null;
  ListViewBase.Header = null;
}
```

The switch statement is weird to have it in this format because I am not sure it ever made sense to have the default case be the template. The header is either null or not null, so unless someone put a strange thing into the header - like a number - then we would never get a template.

2025-01-07 13:34 UTC, mattleibow commented on src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
> +			var header = ItemsView.Header ?? ItemsView.HeaderTemplate;
Previous comment was wrong :)

Having the switch here is fine, but the default case still having to check the header is a bit redundant? I would think it should just be a `case DataTemplate headerTemplate:`

And then we would not need the null and default would be the null where we null out both.

2025-01-07 14:01 UTC, rmarinho commented on src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
> +			var header = ItemsView.Header ?? ItemsView.HeaderTemplate;
I think we still need the null if you clear the template and we want to clear on the native side too.

2025-01-07 14:45 UTC, merged