[iOS] CarouselView with CarouselViewHandler2 make app crash when Loop="False" and user scroll to the last position - fix
dotnet/maui pull request #26868
Opened 2024-12-30 16:57 UTC by kubaflo

### Issues Fixed

Fixes #https://github.com/dotnet/maui/issues/26863

@rmarinho

2025-01-06 13:27 UTC, mattleibow reviewed
This looks sensible, is it possible to add a test for this? I feel like a device test that just renders the CV should trigger this?

Can you set the position via code, or does the user have to scroll manually for this to occur?

2025-01-06 13:27 UTC, mattleibow commented
/azp run

2025-01-07 14:03 UTC, rmarinho commented
/azp run

2025-01-07 14:03 UTC, rmarinho approved these changes

2025-01-07 17:02 UTC, rmarinho requested changes, later dismissed
Seems the test is failing 

```
AppShouldNotCrashOnScrollingCarouselViewWithoutLoop
```

2025-03-25 08:45 UTC, CleverSoftwarePoland commented
Any plans to fix this problem?

2025-03-25 09:16 UTC, bcaceiro commented
Also facing this issue. Cannot use the CarouselViewHandler2 (and .net10 is coming and it will be the default)

2025-03-25 09:58 UTC, CleverSoftwarePoland commented
> Also facing this issue. Cannot use the CarouselViewHandler2 (and .net10 is coming and it will be the default)

Did you find any workaround?

2025-03-25 11:03 UTC, kubaflo commented
Hi! @CleverSoftwarePoland, I don't know when it will make it into release but you can ask @rmarinho

2025-03-26 18:51 UTC, CleverSoftwarePoland commented
Any plans to try again to pass tests or we have to search for other solution? As right now CarouselViewHandler2 is broken when set to loop = false
@jfversluis @rmarinho

2025-04-22 11:43 UTC, seanrodda commented
@rmarinho @jfversluis 
What's needed to get this in the next release? I'm happy to help. Do you think it will be in .NET 9 SR7 ?

2025-04-22 11:56 UTC, jfversluis commented
@seanrodda what is always useful is to test the changes in a PR and let us know if that resolves your issue. Instructions for that can be found here: https://github.com/dotnet/maui/wiki/Testing-PR-Builds

2025-04-22 14:39 UTC, jfversluis approved these changes

2025-06-09 19:51 UTC, merged