[Windows] Fix for TabbedPage more menu items color.
dotnet/maui pull request #26876
Opened 2024-12-31 07:05 UTC by Tamilarasan-Paranthaman

### Root Cause of the issue 

- The TitleColor was used as the foreground color in the DataTemplate applied to the MenuItems. As a result, the color was applied to all items instead of being limited to the items in the NavigationView.

### Description of Change

- I removed the foreground color from the DataTemplate and applied the text color to the menu items in the NavigationView using the NavigationViewItemForeground. This resolved the issue, ensuring that the text color was applied exclusively to the menu items within the NavigationView, without affecting the items in the overflow menu presenter.

### Issues Fixed

Fixes #26754

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <img width="290" src="https://github.com/user-attachments/assets/cee6199d-b357-4a05-a5fb-36caf49f692b"> | <img width="290"  src="https://github.com/user-attachments/assets/6880593f-5483-4496-b0ee-a0f4fd832391"> |

### WinUI Reference

-  I have attached an image illustrating the behavior of the WinUI platform when applying the foreground color to a NavigationView item. The color was used exclusively for the items in the NavigationView, consistent with the behavior observed on other MAUI-supported platforms, such as Android, macOS, and iOS.

<img width="385" alt="WinUI-NV (1)" src="https://github.com/user-attachments/assets/63e57db2-cad6-42af-92a9-02c9f180f4de" />

2025-01-02 17:19 UTC, Redth commented
What does this look like when you change the system theme to dark mode?

2025-01-03 06:12 UTC, Tamilarasan-Paranthaman commented
> What does this look like when you change the system theme to dark mode?

@Redth, The menu item colors will change to white, similar to the behavior in WinUI, when the system theme is switched to Dark mode. I have attached a video for your reference.

<video src="https://github.com/user-attachments/assets/eaf29fa6-a39d-413f-be16-8fc4d4ee13d3">

2025-01-08 13:06 UTC, jfversluis commented
/azp run

2025-01-14 11:13 UTC, jsuarezruiz approved these changes

2025-01-16 11:21 UTC, jfversluis commented
Failing test is unrelated

2025-01-16 11:23 UTC, jfversluis commented
The macOS UI Tests for TabbedPage keeps failing so... is something happening here?

2025-01-16 19:27 UTC, PureWeen requested changes
I'd like to get @Foda 's thoughts on this one before merging

2025-01-17 07:10 UTC, Tamilarasan-Paranthaman commented
> The macOS UI Tests for TabbedPage keeps failing so... is something happening here? It seems weird, but want to make sure that this doesn't impact anything else

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/c82ef797-6d7a-4afa-85ad-5503418d8a73" />


@jfversluis, the **UpdatedSelectionIndicatorProperly** TabbedPage test appears to have failed due to the absence of a Mac screenshot. This screenshot seems to have already been added in the following PR ⁠#27028

2025-01-21 10:02 UTC, Mark-NC001 commented
I've tried it and yes I can read the menu text now (yay!), but for some reason the text colour for the unselected tab is now black!

![image](https://github.com/user-attachments/assets/c51540e0-d3c6-4928-820c-c7fa251b8956)

2025-01-27 10:35 UTC, Tamilarasan-Paranthaman commented
> I've tried it and yes I can read the menu text now (yay!), but for some reason the text colour for the unselected tab is now black!
> 
> ![image](https://private-user-images.githubusercontent.com/75133432/405168376-c51540e0-d3c6-4928-820c-c7fa251b8956.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc5NzMwMzYsIm5iZiI6MTczNzk3MjczNiwicGF0aCI6Ii83NTEzMzQzMi80MDUxNjgzNzYtYzUxNTQwZTAtZDNjNi00OTI4LTgyMGMtYzdmYTI1MWI4OTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI3VDEwMTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ODExZGQ3NWNiYzg1Mjk0NTE3MjJjNWNjMWQ1YTdiMmFlNTUyMmIxNTlmMzc1ZWRjNzc5OTdjMzNlNGVhZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eVkNXyZmpAPROeu61oC0QPM-HzpXe1GNbE-_Fns0Pbw)

@Mark-NC001, I am not entirely sure about the use case you mentioned. Based on the provided issue sample, you set the BarTextColor, which is applied to all items in the NavigationView. You can verify this in the image reference in the description (after the issue fix image).
 
From the given [sample](https://github.com/Mark-NC001/TabbedPageMenuIssue/blob/main/TabbedPageMenuIssue/MainPage.xaml), if the BarTextColor is not set, the SelectedTabColor and UnSelectedTabColor will be used. I have already verified that this is working as expected.
 
Could you please provide more details about the use case you tested for this? I will check it from my end.

2025-01-27 11:04 UTC, Mark-NC001 commented
> Could you please provide more details about the use case you tested for this? I will check it from my end.

@Tamilarasan-Paranthaman - I have done a Clean on my project and tried again, and it works fine! Sorry I should have tried that before my last post! Thank you for the fix! :-)

2025-01-30 20:46 UTC, Foda commented
/rebase

2025-02-13 08:31 UTC, StephaneDelcroix submitted a review, later dismissed

2025-02-26 12:56 UTC, jsuarezruiz commented
/rebase

2025-03-07 10:33 UTC, jsuarezruiz commented
/azp run

2025-03-25 07:43 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:59 UTC, jsuarezruiz commented
/azp run

2025-03-27 07:52 UTC, jsuarezruiz requested changes

2025-03-27 07:52 UTC, jsuarezruiz commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTabbedPageMenuItemTextColor.png
We changed the way to generate the Mac snapshots. Needs to update this reference snapshot.
<img width="336" alt="image" src="https://github.com/user-attachments/assets/67849e1c-c06c-49b5-829a-4b6db4e60784" />
Can get the generated snapshots from the latest build.

2025-03-27 09:28 UTC, Tamilarasan-Paranthaman commented on src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTabbedPageMenuItemTextColor.png
@jsuarezruiz, I have updated the Mac snapshot.

2025-07-15 12:11 UTC, jsuarezruiz commented
/rebase

2025-07-15 12:15 UTC, jsuarezruiz commented
/azp run

2025-08-12 10:15 UTC, jfversluis commented
/rebase

2025-08-12 14:54 UTC, jfversluis approved these changes

2025-08-12 14:54 UTC, merged