[Windows] Fix for FontImageSource color is not applied to the Tab Icon on the TabbedPage
dotnet/maui pull request #26888
Opened 2024-12-31 14:02 UTC by Tamilarasan-Paranthaman

### Root Cause of the issue 

- FontImageSource Icon color is not taken into the consideration while applying the selection foreground and unselectedforeground , it only takes based on the selected tabcolor and unselectedtab color.

### Description of Change

- I fixed the issue by getting the FontImageSource Icon color to store in IconColor property in the ViewModel , if the IconColor is not null , Foreground property gets the icon  color and applied on the icon foreground , if IconColor is null , Foreground Property gets the SelectedForeground and UnSelectedForeground based on IsSelected and applied to the icon foreground.

### Issues Fixed

Fixes #26752

### Tested the behaviour in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <img src="https://github.com/user-attachments/assets/56f1d847-44dd-4dfb-ab23-52c84fed01c1"> | <img src="https://github.com/user-attachments/assets/6c0ac748-5cd6-438c-b7a3-b98e8da2ddbd"> |

2025-01-09 10:53 UTC, jfversluis commented
/azp run

2025-01-14 11:12 UTC, jsuarezruiz commented on src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs
> +						vm.IconColor = (page.IconImageSource as FontImageSource)?.Color?.AsPaint()?.ToPlatform();
Could include an UITest and validate the colors with the `VerifyScreenshot` method?

2025-01-15 11:57 UTC, jsuarezruiz commented on src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs
> +						vm.IconColor = (page.IconImageSource as FontImageSource)?.Color?.AsPaint()?.ToPlatform();
Yes, in this PR, remove the **#if TEST_FAILS_ON_WINDOWS** compilation directive from the FontImageSourceColorShouldApplyOnTabIcon test and commit the snapshot to validate the test.

2025-02-13 08:31 UTC, StephaneDelcroix approved these changes, later dismissed

2025-02-13 22:15 UTC, PureWeen requested changes

2025-02-13 22:15 UTC, PureWeen commented on src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs
> +				if (sender is Page page)
Can this just fire a mapper change on `MapItemsSource" and that'll handle it?

Handler?.UpdateValue("ItemSource") ? 

MapItemsSource already has code that loops over the navigation items and syncs all the colors and icons

2025-02-17 07:41 UTC, Ahamed-Ali commented on src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs
> +				if (sender is Page page)
I checked this by using `Handler?.UpdateValue("ItemSource")` in PropertyChanged. The icon color changed dynamically, but the title color reset to black because MapItemSource also handled the title color.
 
When changing the IconImageSource color dynamically, our fix worked properly, preventing unnecessary changes to the title color and other properties.
 
Please let me know if you have any other concerns @PureWeen

2025-02-24 15:11 UTC, jsuarezruiz commented
/azp run

2025-02-25 10:03 UTC, jfversluis submitted a review, later dismissed

2025-03-03 22:45 UTC, PureWeen requested changes
Can you grab the test that's on 
https://github.com/dotnet/maui/pull/26757

And just include it here for now? That way we can test and validate this PR against that scenario?

We'll just resolve the conflicts once either of these merge

2025-03-05 10:37 UTC, jsuarezruiz commented
> #26757

Agree, will like to have the test from https://github.com/dotnet/maui/pull/26757/ here to validate the changes directly without wait to merge. We can fix conflicts later if necessary.

2025-03-05 10:37 UTC, jsuarezruiz requested changes
The fix looks good, but, could you include the test Issue26662 from https://github.com/dotnet/maui/pull/26757/files here?

2025-03-11 12:26 UTC, jsuarezruiz commented
/rebase

2025-03-12 08:01 UTC, jsuarezruiz commented
/azp run

2025-03-20 09:39 UTC, jsuarezruiz commented
/rebase

2025-03-26 07:57 UTC, jsuarezruiz commented
/azp run

2025-06-09 06:54 UTC, jsuarezruiz commented
/azp run MAUI-UITests-public

2025-08-27 13:47 UTC, jfversluis commented
/rebase

2025-08-27 13:54 UTC, jfversluis approved these changes

2025-08-29 12:09 UTC, merged