[Android / Windows] Fixed ListView.HasUnevenRows property run time changes
dotnet/maui pull request #26882
Opened 2024-12-31 10:30 UTC by NirmalKumarYuvaraj

### Issue Details

Modifying ListView.HasUnevenRows has no effect on UI.

### Root Cause

Runtime support for this property has not been implemented.

### Description of Change

Android - Added support for the ListView.HasUnevenRows property using a property-changed callback to force update the cell size.

Windows - Reset the item source to refresh the ListView.

Validated the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed

Fixes #26780

### Output

| Before | After |
| ------ | ----- |
| <video src="https://github.com/user-attachments/assets/e54862b5-93a2-4f47-870e-fbfe59f7e20a">| <video src="https://github.com/user-attachments/assets/1727e1d9-6c3c-4ea6-9544-d4a993b23f4d">| 
| <video src="https://github.com/user-attachments/assets/5c790fcb-253c-4da5-800a-7645aee07cd3"> | <video src="https://github.com/user-attachments/assets/6508bc60-c2ac-4e8c-be0c-ec711420e9f4"> |

2025-01-10 06:57 UTC, jsuarezruiz commented
/azp run

2025-01-16 06:37 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs
> +						height = (int)size.Height;
@MartyIX , Thanks for the suggestion. I have modified the code changes.

2025-01-21 12:18 UTC, jsuarezruiz commented
/azp run

2025-02-12 10:54 UTC, jsuarezruiz commented
/rebase

2025-03-07 10:33 UTC, jsuarezruiz commented
/rebase

2025-03-12 10:06 UTC, jsuarezruiz commented
/azp run

2025-03-25 07:42 UTC, jsuarezruiz commented
/rebase

2025-03-25 07:59 UTC, jsuarezruiz commented
/azp run

2025-05-30 20:16 UTC, mattleibow requested changes

2025-06-02 07:30 UTC, NirmalKumarYuvaraj commented on src/Controls/tests/TestCases.Android.Tests/snapshots/android/Bugzilla53834Test.png
@mattleibow , The Header cell height is explicitly set [here](https://github.com/NirmalKumarYuvaraj/maui/blob/4dc54213253d9733bc40e5b59327132ef1f59711/src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla53834.cs#L27). Previously, this height was not considered—it used the measured height from the MeasureVirtualView method. With this fix, it properly utilizes the explicitly set Height property.

2025-06-02 08:32 UTC, NirmalKumarYuvaraj commented on src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Bugzilla56298Test.png
Yes @mattleibow , GroupShortNameBinding causes failure in windows platform. In windows it is showing Time out waiting for element . I have shared the issue report for that below.

Issue - https://github.com/dotnet/maui/issues/27336

2025-06-02 08:32 UTC, NirmalKumarYuvaraj commented on src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla56298.cs
> +			//list.GroupShortNameBinding = new Binding(nameof(Group.Key));
https://github.com/dotnet/maui/pull/26882#discussion_r2120427943

2025-06-02 11:59 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Cells/Cell.cs
> +			if ((Parent is ListView) || (Parent is TableView))
@mattleibow , i have removed the TableView code changes

2025-06-02 12:00 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Cells/Cell.cs
> +			// Removed the HasUnevenRows check because we want to force the update size regardless true or false.
Done

2025-06-02 12:04 UTC, NirmalKumarYuvaraj commented on src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs
> +					height = _viewCell.Height > 0 ? (int)Context.ToPixels(_viewCell.Height) : (int)size.Height;
@mattleibow , The cell has a height property. When the user sets a negative value, we use the measured value to set its height. However, if the value is positive, we set the explicit height property as the cell's height.

2025-08-16 14:37 UTC, PureWeen commented
As we obsolete ListView in .NET 10, we'll no longer be accepting PRs for ListView so we can stay focused on CollectionView and ensuring it meets and exceeds everyone's needs.

2025-08-16 14:37 UTC, closed without merging