Essentials: Port xamarin/Essentials#1760
dotnet/maui pull request #2763
Opened 2021-09-29 19:42 UTC by dimonovdd

### Description of Change ###

**Port https://github.com/xamarin/Essentials/pull/1760** 

Apple changed behaviours and API for Photos Permission:

- [PHAuthorizationStatus.limited](https://developer.apple.com/documentation/photokit/phauthorizationstatus/limited) 
- [presentLimitedLibraryPicker(from:)](https://developer.apple.com/documentation/photokit/phphotolibrary/3616113-presentlimitedlibrarypicker)
- [PHAccessLevel](https://developer.apple.com/documentation/photokit/phaccesslevel)

### Related to issue ###

- https://github.com/xamarin/Essentials/issues/1635

### API Changes ###

Added: 
 
- [`PermissionStatus.Limited`](https://github.com/xamarin/Essentials/blob/91b12307b03e31d1f0980a101f97c63697a8e231/Xamarin.Essentials/Permissions/Permissions.shared.enums.cs#L21)
- [`class Permissions.PhotosAddOnly`](https://github.com/xamarin/Essentials/blob/91b12307b03e31d1f0980a101f97c63697a8e231/Xamarin.Essentials/Permissions/Permissions.ios.tvos.macos.cs#L47)

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [x] I'm not sure, please help me

2021-09-29 23:22 UTC, Redth commented
/azp run

2021-12-05 04:57 UTC, Redth approved these changes

2021-12-05 04:58 UTC, Redth commented
/azp run

2022-01-12 20:35 UTC, mattleibow requested changes

2022-01-12 20:35 UTC, mattleibow commented on src/Essentials/src/Permissions/Permissions.ios.tvos.macos.cs
> +                        Platform.GetCurrentUIViewController());
This actually pops up a dialog that requires user input. If we return without waiting, then potentially the app will try access photos that the user is still selecting/deselecting.

There is an overload that takes a completion / awaitable:

```cs
await PHPhotoLibrary.SharedPhotoLibrary.PresentLimitedLibraryPickerAsync(Platform.GetCurrentUIViewController());
```

2022-02-02 00:55 UTC, Redth approved these changes

2022-02-02 00:55 UTC, merged