Set up for unpackaged app projects
dotnet/maui pull request #3172
Opened 2021-10-28 22:55 UTC by mattleibow

### Description of Change ###

`nuff said!`

2021-10-29 18:06 UTC, Eilon requested changes

2021-10-29 18:06 UTC, Eilon commented on src/Core/src/Fonts/FontRegistrar.Windows.cs
> +				root = global::Windows.ApplicationModel.Package.Current.InstalledLocation.Path;
Is there a non-exceptional way to do this? Otherwise unpackaged apps will all get exceptions on startup?

2021-10-29 18:06 UTC, Eilon commented on src/Essentials/src/AppInfo/AppInfo.uwp.cs
> +				return Package.Current.Id.Name;
See earlier comment about exceptions. This doesn't look so nice ☹️

2021-11-05 19:06 UTC, mattleibow commented
This is totes hax! Needs a real fix in here. Probably not even this PR. Let me close to avoid confusion.

2021-11-05 19:06 UTC, closed without merging