Allow to use string to define StrokeShape
dotnet/maui pull request #3256
Opened 2021-11-04 12:44 UTC by jsuarezruiz

### Description of Change ###

Added TypeConverter (and tests) to allow set the StrokeShape like:

- fixes #2690 

```
StrokeShape="Rectangle"
StrokeShape="Ellipse"
StrokeShape="Polygon 0 48, 0 144, 96 150, 100 0, 192 0, 192 96, 50 96, 48 192, 150 200 144 48"
```

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

2021-11-16 17:00 UTC, hartez commented
This probably needs a test in the XAML unit tests, so we can ensure it works with/without XAMLC.

2021-11-23 17:02 UTC, rmarinho requested changes
Can you had a xaml unit test ? with xamlc

2021-12-09 15:58 UTC, jsuarezruiz commented
Sure, adding XAML tests.

2021-12-13 12:07 UTC, jsuarezruiz commented
/azp run

2022-02-14 13:50 UTC, StephaneDelcroix approved these changes

2022-02-14 14:46 UTC, rmarinho commented
@jsuarezruiz unit tests are failing

2022-02-15 09:37 UTC, jsuarezruiz commented
> @jsuarezruiz unit tests are failing

I have checked them locally and are passing. I've done rebase and I'll be waiting for the Build. 

![image](https://user-images.githubusercontent.com/6755973/154034427-9174ec7b-7d92-4b9a-af5d-d812cdb307aa.png)

2022-02-16 12:40 UTC, StephaneDelcroix commented on src/Controls/src/Core/Shapes/StrokeShapeTypeConverter.cs
> +		public const string Ellipse = "ellipse";
use `nameof()`

2022-02-16 12:40 UTC, StephaneDelcroix commented on src/Controls/tests/Xaml.UnitTests/Border.xaml.cs
> +			public void InitializeStrokeShape(bool useCompiledXaml)
```suggestion
			public void InitializeStrokeShape([Values (false, true)]bool useCompiledXaml)
```

2022-02-17 14:07 UTC, rmarinho approved these changes

2022-02-17 14:07 UTC, merged