[Android] Fix Switch color issues
dotnet/maui pull request #4134
Opened 2022-01-14 08:43 UTC by jsuarezruiz

### Description of Change ###

The default Switch colors are wrong. This PR set the same behavior we have in other platforms (for example: Windows).

Fixes #4085 

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

2022-01-15 17:16 UTC, PureWeen requested changes
Can we just delete all these defaults and set these to default values at the Controls level?

https://github.com/dotnet/maui/issues/4132

For now we could define theme via apptheme bindings like this

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Shell/Shell.cs#L620

2022-01-17 14:47 UTC, Redth approved these changes

2022-01-25 12:31 UTC, jsuarezruiz commented
> Can we just delete all these defaults and set these to default values at the Controls level?
> 
> #4132
> 
> For now we could define via apptheme bindings like this
> 
> https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Shell/Shell.cs#L620

Yes, but then we need to update the other platform handlers to do the same, remove setting defaults. Could be easy to do everything in all the platforms etc implementing #4132 or apply the changes specific to the Switch now?

2022-01-25 20:25 UTC, merged

2022-01-28 07:32 UTC, jsuarezruiz commented
Fixes also https://github.com/dotnet/maui/issues/4368