Add handling and tests for TextTransform for SearchBar/Editor/Entry
dotnet/maui pull request #4554
Opened 2022-02-08 05:56 UTC by hartez

Fixes #2990

2022-02-08 13:46 UTC, jsuarezruiz commented
/azp run

2022-02-11 19:16 UTC, rmarinho requested changes
```
  D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Editor\Editor.iOS.cs(7,4): error CS0234: The type or namespace name 'MauiTextViewExtensions' does not exist in the namespace 'Microsoft.Maui.Controls.Platform' (are you missing an assembly reference?) [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj]
  D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Entry\Entry.iOS.cs(7,4): error CS0234: The type or namespace name 'MauiTextViewExtensions' does not exist in the namespace 'Microsoft.Maui.Controls.Platform' (are you missing an assembly reference?) [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj]
```

2022-02-18 19:29 UTC, Redth commented on src/Controls/src/Core/Platform/Android/Extensions/ButtonExtensions.cs
> +			try
Accidental debug code merge here?

2022-02-21 15:30 UTC, rmarinho approved these changes

2022-02-22 15:52 UTC, hartez commented on src/Controls/src/Core/Platform/Android/Extensions/ButtonExtensions.cs
> +			try
Fixed.

2022-02-22 17:53 UTC, merged