[Windows] Implement IsFocused property and Focus(), Unfocus() methods
dotnet/maui pull request #4562
Opened 2022-02-08 13:18 UTC by jsuarezruiz

### Description of Change ###

Implement **IsFocused** property and **Focus**(), **Unfocus**() methods on Windows.

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

2022-02-08 16:27 UTC, hartez requested changes, later dismissed

2022-02-08 16:27 UTC, hartez commented on src/Core/src/Core/IView.cs
> +		/// Attemps to set focus to this View.
```suggestion
		/// Attempts to set focus to this View.
```

2022-02-09 13:40 UTC, jsuarezruiz commented
/azp run

2022-02-16 06:35 UTC, jsuarezruiz commented
/azp run

2022-02-17 19:01 UTC, Redth approved these changes

2022-02-19 15:51 UTC, Redth approved these changes

2022-02-19 15:51 UTC, merged