Refactor Accelerometer into an interface
dotnet/maui pull request #4630
Opened 2022-02-11 15:21 UTC by antonfirsov

## Description of the change

Contributes to #4497.

## Additions made

```C#
public interface IAccelerometer
{
	event EventHandler<AccelerometerChangedEventArgs>? ReadingChanged;
	event EventHandler? ShakeDetected;
	bool IsSupported { get; }
	bool IsMonitoring { get; }
	void Start(SensorSpeed sensorSpeed);
	void Stop();
}

public class AccelerometerImpl : IAccelerometer { /*... */ }
```

2022-02-11 17:50 UTC, rmarinho commented
/azp run

2022-02-14 14:26 UTC, rmarinho requested changes
Seems good, we just don't use `private` keyword

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.tizen.cs
> +		private void PlatformStart(SensorSpeed sensorSpeed)
```suggestion
		void PlatformStart(SensorSpeed sensorSpeed)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.tizen.cs
> +		private void PlatformStop()
```suggestion
		void PlatformStop()
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.tizen.cs
> +		private void DataUpdated(object sender, AccelerometerDataUpdatedEventArgs e)
```suggestion
		void DataUpdated(object sender, AccelerometerDataUpdatedEventArgs e)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.uwp.cs
> +		private void PlatformStart(SensorSpeed sensorSpeed)
```suggestion
		void PlatformStart(SensorSpeed sensorSpeed)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.uwp.cs
> +		private void DataUpdated(object sender, AccelerometerReadingChangedEventArgs e)
```suggestion
		void DataUpdated(object sender, AccelerometerReadingChangedEventArgs e)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.uwp.cs
> +		private void PlatformStop()
```suggestion
		void PlatformStop()
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.shared.cs
> +		private void ProcessShakeEvent(Vector3 acceleration)
```suggestion
		void ProcessShakeEvent(Vector3 acceleration)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.netstandard.tvos.macos.cs
> +		private void PlatformStart(SensorSpeed sensorSpeed) =>
```suggestion
		void PlatformStart(SensorSpeed sensorSpeed) =>
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.netstandard.tvos.macos.cs
> +		private void PlatformStop() =>
```suggestion
		void PlatformStop() =>
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.ios.watchos.cs
> +		private void PlatformStop() =>
```suggestion
		void PlatformStop() =>
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.ios.watchos.cs
> +		private void DataUpdated(CMAccelerometerData data, NSError error)
```suggestion
		void DataUpdated(CMAccelerometerData data, NSError error)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.ios.watchos.cs
> +		private void PlatformStart(SensorSpeed sensorSpeed)
```suggestion
		void PlatformStart(SensorSpeed sensorSpeed)
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.android.cs
> +		private void PlatformStop()
```suggestion
		void PlatformStop()
```

2022-02-14 14:26 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.android.cs
> +		private void PlatformStart(SensorSpeed sensorSpeed)
```suggestion
		void PlatformStart(SensorSpeed sensorSpeed)
```

2022-02-14 14:27 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.android.cs
> +		private AccelerometerImpl accelerometer;
```suggestion
		AccelerometerImpl accelerometer;
```

2022-02-14 14:28 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.android.cs
> +			this.accelerometer = accelerometer;
```suggestion
			_accelerometer = accelerometer;
```

2022-02-14 14:29 UTC, rmarinho commented on src/Essentials/src/Accelerometer/Accelerometer.android.cs
> +			accelerometer.OnChanged(data);
```suggestion
			_accelerometer.OnChanged(data);
```

2022-02-14 14:31 UTC, rmarinho commented
/azp run

2022-02-14 17:36 UTC, antonfirsov commented
@marinho thanks for pushing the style fixes! Is there something else I shall address?

Note that the Essentials project doesn't use the `_` prefix for fields in other types. Is it an inconsistency we should fix?

2022-02-14 17:53 UTC, rmarinho commented
Yeah Essentials was merged to our project and i think we didn't fixe the style when we merged. I would say if you can fix as we go we should.

2022-02-16 15:12 UTC, rmarinho approved these changes

2022-02-16 15:13 UTC, merged