Essentials.Gyroscope refactored to interface and singleton
dotnet/maui pull request #4649
Opened 2022-02-12 14:28 UTC by moljac

### Description of Change ###

Implements #

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

2022-02-14 14:37 UTC, rmarinho commented on src/Essentials/src/Gyroscope/Gyroscope.tizen.cs
> +		publicvoid Stop()
```suggestion
		public void Stop()
```

2022-02-14 14:37 UTC, rmarinho commented
/azp run

2022-02-15 14:42 UTC, rmarinho requested changes, later dismissed
UWP missing 

```
         D:\a\_work\1\s\src\Essentials\src\Gyroscope\Gyroscope.uwp.cs(6,49): error CS0736: 'GyroscopeImplementation' does not implement instance interface member 'IGyroscope.Start(SensorSpeed)'. 'GyroscopeImplementation.Start(SensorSpeed)' cannot implement the interface member because it is static. [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
```

2022-02-17 11:30 UTC, moljac commented
Seems like packing and testing fails. What can I do?

2022-02-21 10:19 UTC, moljac commented
/azp run

2022-02-21 14:52 UTC, moljac commented
/azp run

2022-02-21 14:57 UTC, moljac commented
/azp run

2022-02-23 13:00 UTC, rmarinho commented on src/Essentials/src/Gyroscope/Gyroscope.shared.cs
>  		public static bool IsMonitoring { get; private set; }
Shouldn't this be on the interface ?

2022-02-23 18:56 UTC, Redth commented on src/Essentials/src/Gyroscope/Gyroscope.shared.cs
>  		public static bool IsMonitoring { get; private set; }
Fixed.

2022-02-23 18:57 UTC, Redth approved these changes

2022-02-23 18:59 UTC, merged