Implement Padding property in ImageButtonHandler
dotnet/maui pull request #4665
Opened 2022-02-14 12:21 UTC by jsuarezruiz

### Description of Change ###

Implement **Padding** property in ImageButton.

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

2022-02-14 14:06 UTC, rmarinho approved these changes

2022-02-14 15:10 UTC, mattleibow commented on src/Core/src/Platform/Android/ImageButtonExtensions.cs
> +				);
How does this work with default paddings and 0 or -1? I know there is a bunch of logic with the "default"/"normal" button. Most notably, we need to make sure the default button looks correct and a padding of 0 does not have a negative space and is in fact a 0 padding.

2022-02-16 17:31 UTC, Redth commented
@jsuarezruiz  I don't see the padding value influencing MacCatalyst at all in the ImageButton gallery page.

2022-03-04 03:18 UTC, J-Swift commented
@jsuarezruiz I happened to be looking into this because I noticed it wasn't implemented yet, and noticed that your Android implementation won't work as expected due to an Android Framework bug which pads the entire button rather than just the content area (https://github.com/material-components/material-components-android/issues/2063).

This is what that looks like:
<img width="300" alt="Screen Shot 2022-03-03 at 10 11 32 PM" src="https://user-images.githubusercontent.com/734158/156692550-e8d31ea4-3507-41a4-aadf-f5a79f24c6c5.png">

I propose the following for the Android implementation:

```
public static void UpdatePadding(this ShapeableImageView platformButton, IImageButton imageButton)
{
		var pad = imageButton.Padding;

		// NOTE(jpr): post on handler to get around an Android Framework bug.
		// see: https://github.com/material-components/material-components-android/issues/2063
		platformButton.Post(() =>
		{
				platformButton.SetContentPadding(
					(int)platformButton.Context.ToPixels(pad.Left),
					(int)platformButton.Context.ToPixels(pad.Top),
					(int)platformButton.Context.ToPixels(pad.Right),
					(int)platformButton.Context.ToPixels(pad.Bottom)
				);
		});
}
```

which results in this

<img width="300" alt="Screen Shot 2022-03-03 at 10 13 53 PM" src="https://user-images.githubusercontent.com/734158/156692706-a60b302c-a28b-4798-9431-9c1c61c7b056.png">

2022-03-04 14:07 UTC, mattleibow requested changes
The padding may be wrong and there might be an android bug that we need to work around.

2022-03-11 13:56 UTC, jsuarezruiz commented
> @jsuarezruiz I happened to be looking into this because I noticed it wasn't implemented yet, and noticed that your Android implementation won't work as expected due to an Android Framework bug which pads the entire button rather than just the content area ([material-components/material-components-android#2063](https://github.com/material-components/material-components-android/issues/2063)).
> 
> This is what that looks like: <img alt="Screen Shot 2022-03-03 at 10 11 32 PM" width="300" src="https://user-images.githubusercontent.com/734158/156692550-e8d31ea4-3507-41a4-aadf-f5a79f24c6c5.png">
> 
> I propose the following for the Android implementation:
> 
> ```
> public static void UpdatePadding(this ShapeableImageView platformButton, IImageButton imageButton)
> {
> 		var pad = imageButton.Padding;
> 
> 		// NOTE(jpr): post on handler to get around an Android Framework bug.
> 		// see: https://github.com/material-components/material-components-android/issues/2063
> 		platformButton.Post(() =>
> 		{
> 				platformButton.SetContentPadding(
> 					(int)platformButton.Context.ToPixels(pad.Left),
> 					(int)platformButton.Context.ToPixels(pad.Top),
> 					(int)platformButton.Context.ToPixels(pad.Right),
> 					(int)platformButton.Context.ToPixels(pad.Bottom)
> 				);
> 		});
> }
> ```
> 
> which results in this
> 
> <img alt="Screen Shot 2022-03-03 at 10 13 53 PM" width="300" src="https://user-images.githubusercontent.com/734158/156692706-a60b302c-a28b-4798-9431-9c1c61c7b056.png">

Used the Jimmy workaround. Thanks for include the issue.

2022-03-25 11:01 UTC, rmarinho requested changes
Tests are failing on Android

https://dev.azure.com/xamarin/public/_build/results?buildId=58437&view=ms.vss-test-web.build-test-results-tab

2022-03-28 15:01 UTC, Redth commented
/azp run

2022-03-28 18:31 UTC, merged