Interfaced handlers for Label, NavigationView, Page
dotnet/maui pull request #4841
Opened 2022-02-22 20:57 UTC by antonfirsov

Contributes to #4378.

2022-02-22 22:16 UTC, PureWeen requested changes

2022-02-22 22:16 UTC, PureWeen commented on src/Core/src/Handlers/Label/LabelHandler.cs
> +		public static IPropertyMapper<ILabel, ILabelHandler> LabelMapper = new PropertyMapper<ILabel, ILabelHandler>(ViewHandler.ViewMapper)
`Mapper`

2022-02-23 00:07 UTC, antonfirsov commented on src/Core/src/Handlers/Label/LabelHandler.cs
> +		public static IPropertyMapper<ILabel, ILabelHandler> LabelMapper = new PropertyMapper<ILabel, ILabelHandler>(ViewHandler.ViewMapper)
addressed

2022-02-23 23:20 UTC, PureWeen approved these changes

2022-02-23 23:21 UTC, merged