Interfaced handlers for RefreshView and SearchBar
dotnet/maui pull request #4847
Opened 2022-02-23 01:38 UTC by antonfirsov

Contributes to https://github.com/dotnet/maui/issues/4378.

2022-02-23 01:39 UTC, antonfirsov commented on src/Core/src/Handlers/SearchBar/ISearchBarHandler.cs
> +		QueryEditor? QueryEditor { get; }
This seemed to be a straightforward addition greatly simplifying handler implementations.

2022-02-23 12:52 UTC, jsuarezruiz commented
/azp run

2022-02-23 13:05 UTC, rmarinho requested changes
```
/Users/builder/azdo/_work/1/s/src/Controls/src/Core/HandlerImpl/SearchBar/SearchBar.cs(15,21): error CS0117: 'SearchBarHandler' does not contain a definition for 'SearchBarMapper' [/Users/builder/azdo/_work/1/s/src/Controls/src/Core/Controls.Core.csproj]
```

2022-02-24 16:37 UTC, PureWeen requested changes

2022-02-24 16:37 UTC, PureWeen commented on src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
> +				platformHandler.PlatformView?.UpdatePlaceholderColor(searchBar, DefaultPlaceholderTextColors, platformHandler._editText);
Can this `_editText` be changed to `QueryEditor`?

2022-02-24 16:37 UTC, PureWeen commented on src/Core/src/Handlers/SearchBar/SearchBarHandler.Windows.cs
> +					platformHandler._queryTextBox);
`QueryEditor` ?

2022-02-24 21:20 UTC, PureWeen approved these changes

2022-02-24 22:28 UTC, merged