[GH-473] Port Font to Editor
dotnet/maui pull request #503
Opened 2021-03-13 21:59 UTC by pictos

### Description of Change ###

Implements #473

Implements #

### Additions made ###

- Adds Font property map to EditorHandler
- Adds Font mapping methods to EditorHandlerfor Android and iOS
- Adds extension methods to apply Font on Android/iOS
- Adds DeviceTests for initial Font values on iOS and Android

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

2021-03-14 06:48 UTC, mattleibow reviewed
Looks almost perfect but maybe also add the tests from Entry that also check the font size and attributes? Namely the `FontSizeInitializesCorrectly` and `FontAttributesInitializeCorrectly` tests.

Otherwise this is nice and clean and seems to have all the things.

Thanks!

2021-03-14 06:48 UTC, mattleibow commented
/azp run

2021-03-14 06:51 UTC, mattleibow commented
Also, could you add the entry to the sample MainPage. I know this is now almost impossible to test at this point, but once we got some navigation going this will all be much better.

2021-03-14 16:30 UTC, pictos commented
@mattleibow when you say `Entry` you mean `Editor` right?

2021-03-14 16:32 UTC, mattleibow commented
I mean copy the 2 tests from entry to editor

2021-03-14 16:34 UTC, pictos commented
@mattleibow I see, but when you talk about the MainPage.cs sample, is to add the Editor instead of the entry, right? (Yeah it's a dumb question from me, but just to make sure)

2021-03-14 16:39 UTC, mattleibow commented
Ah yeah. Editor. 🤦🏻‍♀️ So menu words looking the same.

2021-03-18 16:25 UTC, jsuarezruiz requested changes

2021-03-18 16:25 UTC, jsuarezruiz commented on src/Core/tests/DeviceTests/Handlers/Editor/EditorHandlerTests.Android.cs
> +			var label = new EditorStub()
Change label by editor

2021-03-18 16:25 UTC, jsuarezruiz commented on src/Core/src/Handlers/Editor/EditorHandler.cs
> +			[nameof(ILabel.Font)] = MapFont
Change `ILabel` by `IEditor`

2021-03-18 16:25 UTC, jsuarezruiz commented on src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
> +				throw new InvalidOperationException($"Unable to find service provider, the App.Current.Services was null.");
Not related with this PR, but we have this message repeated in several places. Maybe we can create some specific exceptions like `FontInitializationException` or group all the messages etc.

2021-03-18 16:25 UTC, jsuarezruiz commented
Thanks @pictos. Looks nice, just some small changes and I think is ready.

2021-03-19 10:30 UTC, jsuarezruiz approved these changes

2021-03-22 14:40 UTC, mattleibow approved these changes

2021-03-24 17:54 UTC, merged