Fix ArgumentException using OnPlatform with View type
dotnet/maui pull request #5073
Opened 2022-03-05 06:02 UTC by buyaa-n

### Fix #4509 Exception using OnPlatform with View type

While adding a View when the `value` is `OnPlatform<T>` it should pass the T instead of `value` as an argument of `Invoke`:

https://github.com/dotnet/maui/blob/8dd650231fc535f0475699bb2c7eacd3cbc30461/src/Controls/src/Xaml/ApplyPropertiesVisitor.cs#L146-L149

`OnPlatform<T>`  has implicit operator for getting the View for the current Platform, could not call/use that using reflection, so added parameter less `T GetValue()` the get runtime View, used it to get runtime view type and pass as argument of `Invoke`

Fixes # https://github.com/dotnet/maui/issues/4509

2022-03-05 06:05 UTC, buyaa-n commented on src/Controls/samples/Controls.Sample/Pages/Controls/RadioButtonGalleries/RadioButtonView.xaml
> +<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
The test xaml copied from the [repo](https://github.com/davidbritch/dotnet-maui-samples/blob/main/UserInterface/Views/RadioButtonDemos/RadioButtonDemos/Views/RadioButtonsExplainedPage.xaml) reported in the bug

2022-03-05 14:51 UTC, mattleibow commented
/azp run

2022-03-07 08:12 UTC, StephaneDelcroix requested changes
thanks for looking at this. unfortunately, specialising the xaml parser for OnPlatform isn't the right approach, as it fixes a special case, and not the general situation.

also, adding a page in the samples is good, but less useful than an actual unit test.

I'll give it a try in the coming days...

2022-03-07 16:56 UTC, buyaa-n commented
> thanks for looking at this. unfortunately, specialising the xaml parser for OnPlatform isn't the right approach, as it fixes a special case, and not the general situation.

Thanks for reviewing, so what is the general situation? I guess it should apply to any generic type not only OnPlatoform

> also, adding a page in the samples is good, but less useful than an actual unit test.
> 
> I'll give it a try in the coming days...

I can add unit test, i would like to finish what i started, please let me know what else needed

2022-03-09 21:30 UTC, closed without merging