GridLayout with absolute and auto
dotnet/maui pull request #513
Opened 2021-03-15 21:24 UTC by hartez

This is a first pass at GridLayout. It implements absolute row/column lengths and "auto" row/column lengths. Star values are accepted but not supported yet, and might do weird things. Row spacing and column spacing are implemented.

This is meant to make GridLayout available for use/testing so we can do more complex apps; it's not meant to be a complete solution. 

Known issues:

Star values don't work.
Items spanning multiple rows will still try to add RowSpacing at the end when they shouldn't.
Removing items from the Grid doesn't clean up row/column/span data

Unknown issues:

Hopefully none, probably many.

2021-03-16 07:14 UTC, feartDev approved these changes

2021-03-16 19:05 UTC, Redth approved these changes

2021-03-17 12:50 UTC, jsuarezruiz requested changes
Have some compiling errors in ControlGallery.csproj (mismatching type)

2021-03-23 22:55 UTC, rmarinho requested changes
We have unit tests failing

2021-03-24 08:32 UTC, rmarinho approved these changes

2021-03-24 09:06 UTC, jsuarezruiz approved these changes

2021-03-24 09:06 UTC, merged