Editorpredictivetext
dotnet/maui pull request #515
Opened 2021-03-15 21:39 UTC by hevey

### Description of Change ###

Implements #385

### Additions made ###

- Adds `bool IsTextPredictionEnabled { get; }` to the `IEditor` interface
- Adds IsTextPredictionEnabled property map to EditorHandler
- Adds PredictiveText mapping methods to LabelHandler for Android and iOS
- Adds extension methods to handle Predictive Text on Android/iOS
- Adds DeviceTests for testing IsTextPredictionEnabled values on iOS and Android

### PR Checklist ###

- [x] Targets the correct branch 
- [x] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

2021-03-15 21:39 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=515) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=515) before we can accept your contribution.<br/><br/>:x: hevey [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=515)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=515) it.</sub>

2021-03-16 11:55 UTC, jsuarezruiz requested changes
Is looking nice, could you add the  [PortHandler] attributes in the compatibility renderers?

2021-03-16 14:07 UTC, hevey commented
> Is looking nice, could you add the [PortHandler] attributes in the compatibility renderers?

Ok these have been added

2021-03-16 15:38 UTC, mf2223 approved these changes

2021-03-16 22:38 UTC, merged