[android] Ensure toolbar is removed from parent before adding to appbar
dotnet/maui pull request #5255
Opened 2022-03-12 05:15 UTC by J-Swift

### Description of Change

Ensure the android toolbar isn't a part of another view hierarchy before adding it. This mainly (only?) comes up when resetting `Application.MainPage` from something that originally had an Appbar (e.g. NavigationPage).

NOTE: There is a separate (probably partially related) issue that if you set a non-Appbar page as the new MainPage (e.g. change from a NavigationPage as root to a ContentPage as root), the Appbar will still appear. I believe this is due to the code here which triggers a MapToolbar on the Window https://github.com/dotnet/maui/blob/d9ec2b60efe3be835760695da35e38ad5c065c34/src/Core/src/Platform/Android/Navigation/NavigationRootManager.cs#L84 I haven't found a way to workaround that, but I think its better than the current state which is just crashing.

NOTE NOTE: I'm not sure why there are 2 different `MapToolbar` implementations, or why they slightly differed. One was checking if the toolbar was index-0, aka the backmost child, while the other just checked if the toolbar is at _any_ z-index. I only know that we need to ensure the toolbar gets removed from its parent before adding it to the parent, and it makes sense to me that it should be set to index-0.

### Issues Fixed

Possibly fixes #4311 and #5168

2022-03-12 15:57 UTC, PureWeen commented
> NOTE NOTE: I'm not sure why there are 2 different MapToolbar implementations, or why they slightly differed. 

Hmmmmm, it seems like an oversight or a bad merge. I'd say combine them. 

My one slight concern here is that in the past whenever I hit an issue where the toolbar already had a parent it was due to some other flaw higher up in the chain. I've written this same code and then deleted a few times now :-)

I feel like technically if you swap out the MainPage of the app the app container should remain stable.

I'm curious why a second appbarlayout is being created. Swapping out the ContentPage should just cause the `Toolbar` instance on the `Window` to change to null and then that MapToolbar code should remove the toolbar. 

I feel like if we fix this
> NOTE: There is a separate (probably partially related) issue that if you set a non-Appbar page as the new MainPage (e.g. change from a NavigationPage as root to a ContentPage as root), the Appbar will still appear. I believe this is due to the code here which triggers a MapToolbar on the Window

It'll also fix this issue without having to auto remove from the parent

2022-03-12 16:08 UTC, J-Swift commented
Yeah I 100% agree with all that, and I went down the path of trying to resolve the source issue (although the `removeFromParent` code should still be added), but wasn't able to pinpoint it. The crash was a roadblock to me on the app side though and can't be worked around from app code so I figured this PR was better than current affairs.

What ultimately leads to the toolbar funkiness (I think) is a combination of the `NavigationRootManager` line I link above, and the overloaded `MapToolbar` that takes an explicit `IToolbarElement`. I think the overload needs to be more intelligent about checking and bailing if it "shouldnt" add a `Toolbar`. Basically, I think it needs a check that looks something like this
https://github.com/dotnet/maui/blob/4d168ea1cdb42860a6645d2ad70123d648cb1e19/src/Core/src/Handlers/View/ViewHandler.Android.cs#L144

but like I said I'm not really sure what this overloaded API is providing to the system so I don't know what to add (I think its to support a custom provided Toolbar? I see your comment in https://github.com/dotnet/maui/pull/3513 mentioning that)

2022-03-12 17:12 UTC, PureWeen commented
> but like I said I'm not really sure what this overloaded API is providing to the system so I don't know what to add

It's there for `WindowHandler` because `WindowHandler` is an `IElementHandler` and `IWindow` doesn't inherit from `IView`. So the purpose was to have a single method service all the `MapToolbar` logic  (FlyoutViewHandler, ViewHandler, WindowHandler).

The code in `ViewHandler` should most likely just get changed to this

```C#
		public static void MapToolbar(IViewHandler handler, IView view)
		{
			if (handler.VirtualView is not IToolbarElement te || te.Toolbar == null)
				return;

			MapToolbar(handler, te);
		}

		internal static void MapToolbar(IElementHandler handler, IToolbarElement te)
		{
			if (te.Toolbar == null)
				return;
```

>  (although the removeFromParent code should still be added), 
> What ultimately leads to the toolbar funkiness (I think) is a combination of the NavigationRootManager line I link above,

This most likely means that the xplat data is representing the state of the world incorrectly. I'm guessing that there's a Toolbar that's still sticking around after the root page is swapped for a NavPage. 

If you've swapped out the mainpage for a content page then 
```C#
 _toolbarElement?.Toolbar?.Parent?.Handler?.UpdateValue(nameof(IToolbarElement.Toolbar)); 
 ```
 
 The `Toolbar` part of this statement should be null. 
 
 I think this needs to get set to null (and maybe call disconnect on the toolbar handler)
 https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/HandlerImpl/Window/Window.Impl.cs#L33-L40
 
 When the root page is swapped for a contentpage

2022-03-21 15:29 UTC, Redth commented
/azp run

2022-03-21 16:21 UTC, PureWeen requested changes
@J-Swift thoughts?
https://github.com/dotnet/maui/pull/5255

2022-03-21 17:02 UTC, J-Swift commented
@PureWeen I defer to you and the team on all this, I was just viewing it from the perspective of fixing my crashing : )

I dont have a solid enough understanding of the overall Maui app structure to judge how to manage the expected state. That said, its odd to me that we are doing things in `OnDisconnectHandler` that aren't undoing things setup in `OnConnectHandler`. I also think you still need to retain the 'conditionally remove Toolbar from parent' logic from my PR because it handles both cases:

- Toolbar has a different parent. I think this is important to check for since the Toolbar can be provided explicitly.
- Toolbar is a child other than index 0(i.e. make sure its placed at Z-index 0)

2022-03-21 20:11 UTC, PureWeen commented
@J-Swift 

> That said, its odd to me that we are doing things in OnDisconnectHandler that aren't undoing things setup in OnConnectHandler

I agree. The main issue I ran into with `ConnectHandler` is that it fires too early for me to do anything useful. With WinUI I don't have anything available to me until after `OnApplyTemplates` runs and then on `Android` `Toolbar.ConnectHandler` runs while the `ToPlatform` is getting called on the `Window` because it's ran from `Window.MapToolBar` which is too early for me to access the `AppBarLayout`. So the current setup is definitely less than desirable and I'd really like to get more of it organized into `ToolbarHandler`. I have some heavier `Toolbar` reworks I need to do to fix [this](https://github.com/dotnet/maui/issues/4263) so I'm hopeful I can organize it a bit better there.

2022-03-21 20:12 UTC, closed without merging