Update MAUI Graphics
dotnet/maui pull request #5552
Opened 2022-03-24 16:21 UTC by Redth

Updated to  6.0.300-rc.1.1167

2022-03-24 17:44 UTC, jsuarezruiz commented
/azp run

2022-03-25 08:51 UTC, jsuarezruiz approved these changes

2022-03-25 10:51 UTC, rmarinho requested changes, later dismissed
failing seems we don't have GradientStop ? 

```
      "D:\a\_work\1\s\Microsoft.Maui.BuildTasks.slnf" (Build target) (1:2) ->
       "D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj" (default target) (3:40) ->
       "D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj" (Build target) (3:55) ->
       (XamlPreCompile target) -> 
         D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Brush.Impl.cs(2,54): error CS0234: The type or namespace name 'GradientStop' does not exist in the namespace 'Microsoft.Maui.Graphics' (are you missing an assembly reference?) [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj]

```

2022-03-25 10:54 UTC, Redth commented
It moved and got renamed to avoid duplicate types in the xmlns

2022-03-26 01:02 UTC, mattleibow approved these changes

2022-03-28 18:02 UTC, merged