BlazorWebView public API tracking
dotnet/maui pull request #5672
Opened 2022-03-30 15:52 UTC by SteveSandersonMS

As a step towards https://github.com/dotnet/maui/issues/2539 and for longer-term API tracking, this PR adds the `Microsoft.CodeAnalysis.PublicApiAnalyzers` analyzer that we also use in the ASP.NET Core repo. It's only enabled for the BlazorWebView src projects (though other parts of MAUI could enable it easily if they wanted).

We don't strictly have to do this. However I don't see much drawback now the APIs should be mostly stable, and will help us to avoid any unwanted breaking change surprises in future releases.

2022-03-30 20:11 UTC, Eilon approved these changes

2022-04-04 15:54 UTC, mattleibow requested changes
Is it possible to generate all the files and insert this into the build for all projects? And maybe do this on the RC 1 branch so that we can get the baseline from there?

2022-04-04 15:57 UTC, SteveSandersonMS commented
> Is it possible to generate all the files and insert this into the build for all projects? And maybe do this on the RC 1 branch so that we can get the baseline from there?

@mattleibow Thanks but I don't want to do that as part of this PR. Each team who owns different parts of the codebase should enable it separately for their work, as they will have the necessary context on things like "does this need to have different outputs for different TFMs".

2022-04-04 16:02 UTC, mattleibow commented
@SteveSandersonMS I see the build is failing because you have a windows TFM that has a version, but we now have 2. The APIs are supposed to be the same so maybe we should just clip the number off - or use the $(TargetPlatformIdentifier) which will be android, ios, windows, maccatalyst.

2022-04-04 16:04 UTC, mattleibow commented
> "does this need to have different outputs for different TFMs".

Yes. Since we allow direct access to underlying platform APIs, several are exposed.

2022-04-06 14:33 UTC, mattleibow commented
Can we put all the files in a folder in the root? Maybe at `/<assembly-name>/<tfm>/Api.Shipped.txt`

2022-04-06 16:26 UTC, mattleibow approved these changes
I will do this for the rest of the repo.

And your comment about code owners is a good point.

2022-04-08 12:28 UTC, javiercn approved these changes

2022-04-08 16:31 UTC, merged