Fix for 3848 - FlexLayout doesn't measure content
dotnet/maui pull request #6085
Opened 2022-04-13 22:23 UTC by NogginBox

### Description of Change

I've fixed `FlexLayoutManager.Measure` so that it measures its children's frames to work out the bounding box of the content. The current implementation ignores the children completely.

This code sample behaves as expected and is sized correctly based on the content:
```
<StackLayout>
    <Label>Top</Label>
    <FlexLayout Grid.Row="0" Grid.Column="1" Wrap="Wrap" AlignContent="Start" AlignItems="Start">
        <BoxView BackgroundColor="AliceBlue" HeightRequest="40" WidthRequest="24" />
        <BoxView BackgroundColor="BlanchedAlmond" HeightRequest="24" WidthRequest="24" />
        <BoxView BackgroundColor="Chartreuse" HeightRequest="32" WidthRequest="24" />
        <BoxView BackgroundColor="DeepPink" HeightRequest="16" WidthRequest="24" />
        <BoxView BackgroundColor="Firebrick" HeightRequest="24" WidthRequest="24" />
        <BoxView BackgroundColor="Gold" HeightRequest="40" WidthRequest="24" />
        <BoxView BackgroundColor="HotPink" HeightRequest="16" WidthRequest="24" />
        <BoxView BackgroundColor="AliceBlue" HeightRequest="40" WidthRequest="24" />
        <BoxView BackgroundColor="BlanchedAlmond" HeightRequest="24" WidthRequest="24" />
        <BoxView BackgroundColor="Chartreuse" HeightRequest="32" WidthRequest="24" />
        <BoxView BackgroundColor="DeepPink" HeightRequest="16" WidthRequest="24" />
        <BoxView BackgroundColor="Firebrick" HeightRequest="24" WidthRequest="24" />
        <BoxView BackgroundColor="Gold" HeightRequest="40" WidthRequest="24" />
        <BoxView BackgroundColor="HotPink" HeightRequest="16" WidthRequest="24" />
    </FlexLayout>
    <Label>Bottom</Label>
</StackLayout>
```

The implementation was inspired and informed by StackLayoutManager.Measure.

### Issues Fixed

- Fixes #3848
- Fixes #3852

2022-04-14 18:11 UTC, rmarinho commented
/azp run

2022-04-15 10:34 UTC, NogginBox commented
How do I go about reviewing test failures and fixing?

2022-04-15 11:31 UTC, NogginBox commented
The tests got rerun and everything succeeded this time.

2022-04-20 10:10 UTC, rmarinho commented
Do you think you can add a unit test for this?

2022-04-20 17:43 UTC, NogginBox commented
@rmarinho I'm on holiday this week, but I'll look next week at the unit tests for StackLayoutManager and see if I can base them on that.

2022-04-29 08:31 UTC, mattleibow commented
/azp run

2022-04-29 13:21 UTC, mattleibow requested changes
Just marking this red so we don't forget to add a test. Just had an issue right now that appeared after a few merges because we did not have a test in a critical path. I am becoming more like Stephane and feeling test-greedy.

2022-04-29 15:39 UTC, NogginBox commented
@mattleibow I'm working on the tests, but have managed to completely bork my VS setup trying to get the latest Maui source to run. I think you've seen my call for help discussion. This implementation is running in my own project, but as a new class called NogginFlexLayout.

There were no tests for FlexLayout before so I've based them on the StackLayout ones.

2022-04-29 19:46 UTC, hartez commented
This all looks good, so rather than hold things up waiting for tests, I'm going to go ahead and merge this.

@NogginBox If you want to PR the tests later, that would be great; otherwise, I'll add some myself when I've got a moment.

2022-04-29 19:46 UTC, hartez approved these changes

2022-04-29 19:47 UTC, merged

2022-05-04 07:00 UTC, NogginBox commented
Started unit tests on this draft PR #6800

2022-05-23 07:35 UTC, Palku commented
Is FlexBox sizing only fixed for Windows or should it work in Android in RC3 as well? 
For me it works targeting Windows but not Android. In Android I have to do some ForceLayout() or toggle views back and forth to make the size update correctly.

2022-05-23 20:35 UTC, NogginBox commented
This change should work in all OS versions as there is no OS specific code in it. I did not test in Android though.

If the layout is correct on the first draw and only breaks when the size changes, then that sounds like a different issue.

2022-05-24 09:35 UTC, NogginBox commented
If it draws fine after a redraw then it seems like a different bug. It seems like the Measure method I fixed is not being called at all, or the things it is trying to measure do not have size yet.

Either way I think it needs a new bug ticket. No one will be tracking comments on a fixed PR.