Make Android sizing of ShapeViews consistent with iOS and Windows
dotnet/maui pull request #6206
Opened 2022-04-18 22:03 UTC by hartez

### Description of Change

Given no explicit width or height, ShapeViews on Android attempt to fill the given space; on iOS/Windows, they have no size. 
These changes make Android's measure of ShapeViews consistent with Windows/iOS when the width/height are not explicitly specified.

### Issues Fixed

Fixes #5119

2022-04-19 08:06 UTC, jsuarezruiz commented
Should it be the other way? That is, on all platforms if there is no space, the size of the Shape should be adjusted to the necessary BoundingBox or fill the available space.

2022-04-19 14:50 UTC, hartez commented
> Should it be the other way? That is, on all platforms if there is no space, the size of the Shape should be adjusted to the necessary BoundingBox or fill the available space.

We could mark this as a draft and revisit it after #5817 is merged.

2022-04-27 18:43 UTC, rachelkang approved these changes

2022-04-28 21:06 UTC, rmarinho requested changes
Build seems to be failing

2023-03-09 15:16 UTC, jsuarezruiz approved these changes

2023-03-14 22:32 UTC, rmarinho commented
Failing build

```
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(183,13): error CS0266: Cannot implicitly convert type 'Microsoft.Maui.DeviceTests.Stubs.RectangleStub' to 'Microsoft.Maui.Graphics.IShape'. An explicit conversion exists (are you missing a cast?) [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(191,31): error CS0117: 'PolygonStub' does not contain a definition for 'Points' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,28): error CS0117: 'LineStub' does not contain a definition for 'X1' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,36): error CS0117: 'LineStub' does not contain a definition for 'Y1' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,44): error CS0117: 'LineStub' does not contain a definition for 'X2' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,53): error CS0117: 'LineStub' does not contain a definition for 'Y2' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
```D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(183,13): error CS0266: Cannot implicitly convert type 'Microsoft.Maui.DeviceTests.Stubs.RectangleStub' to 'Microsoft.Maui.Graphics.IShape'. An explicit conversion exists (are you missing a cast?) [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(191,31): error CS0117: 'PolygonStub' does not contain a definition for 'Points' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,28): error CS0117: 'LineStub' does not contain a definition for 'X1' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,36): error CS0117: 'LineStub' does not contain a definition for 'Y1' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,44): error CS0117: 'LineStub' does not contain a definition for 'X2' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Core\tests\DeviceTests\Handlers\ShapeView\ShapeViewHandlerTests.cs(201,53): error CS0117: 'LineStub' does not contain a definition for 'Y2' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj::TargetFramework=net7.0-android]

2023-03-16 13:59 UTC, rmarinho approved these changes

2023-03-16 13:59 UTC, merged