Allow closing of windows when using a MainPage
dotnet/maui pull request #6316
Opened 2022-04-20 14:28 UTC by mattleibow

### Description of Change

The initial work in #4860, there was work to avoid clearing up the window that is still being used.

This PR reduces the prevention to only prevent the closure of the MainPage window.

### Issues Fixed

Fixes #6103
Related to: #4860

2022-04-20 14:42 UTC, Redth approved these changes

2022-04-20 15:43 UTC, rachelkang requested changes
Deploying to Android device is failing for me :(

2022-04-20 16:50 UTC, rachelkang commented
> Deploying to Android device is failing for me :(

@mattleibow here's a gist of the errors: https://gist.github.com/rachelkang/2751bf23ff2b579f8b63c1886be1ec51

I'm only seeing this on this branch and not on main / other branches

2022-04-20 18:40 UTC, mattleibow commented
These errors are not connected since the nugets are basically just a build task to write some text files.

Did you git clean?

2022-04-20 19:10 UTC, rachelkang commented
@mattleibow yeah I did git clean -xfd :/

This is what shows up in the error list:
Error	MSB3491	Could not write lines to file "obj\staticwebassets.pack.sentinel". The process cannot access the file 'C:\Users\rachelkang\maui1\src\Controls\samples\Controls.Sample\obj\staticwebassets.pack.sentinel' because it is being used by another process.	Maui.Controls.Sample	C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets	429

2022-04-21 04:31 UTC, mattleibow commented
> This is what shows up in the error list: Error MSB3491 Could not write lines to file "obj\staticwebassets.pack.sentinel". The process cannot access the file 'C:\Users\rachelkang\maui1\src\Controls\samples\Controls.Sample\obj\staticwebassets.pack.sentinel' because it is being used by another process. Maui.Controls.Sample C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets 429

Ah yeah, this is a known issue in our repo. Just run again and the next time should work. I think we have some build tasks that are running in the background so they conflict. 

 - maui: https://github.com/dotnet/maui/issues/2955
 - aspnetcore: https://github.com/dotnet/aspnetcore/issues/36880

2022-04-22 14:10 UTC, rachelkang approved these changes
LGTM and building happily now!

2022-04-22 19:59 UTC, merged