Updated Default project template title
dotnet/maui pull request #6319
Opened 2022-04-20 15:31 UTC by jsuarezruiz

### Description of Change

This will avoid confusion with the double title. @davidortinau What should be the new title?, ".NET MAUI" is fine?
![image](https://user-images.githubusercontent.com/6755973/164267409-0c500ed0-8db2-418a-9e04-794f9ee7a6df.png)

### Issues Fixed

Fixes #5732

2022-04-20 16:23 UTC, rmarinho approved these changes

2022-04-20 18:48 UTC, rachelkang requested changes

2022-04-20 18:48 UTC, rachelkang commented on src/Templates/src/templates/maui-mobile/AppShell.xaml
> +        Title=".NET MAUI"
Maybe ".NET MAUI App"

Or ideally, is there a way we could directly reference the App Title here?

2022-04-21 15:43 UTC, rachelkang commented
@davidortinau This looks great, thanks!

One question - what about the current count label? Should we keep that above the "Click me" button? (It doesn't make sense to remove it completely while keeping the SemanticReader.Announce logic, unless we reove both and make the button do somethng else)

2022-04-21 15:44 UTC, davidortinau commented
> @davidortinau This looks great, thanks!
> 
> One question - what about the current count label? Should we keep that above the "Click me" button? (It doesn't make sense to remove it completely while keeping the SemanticReader.Announce logic, unless we reove both and make the button do somethng else)

The button text updates now instead of the label. 

<img width="338" alt="image" src="https://user-images.githubusercontent.com/41873/164499295-1ca6a8a4-9b7e-4a53-ac56-7beaf1febaf8.png">

2022-04-21 15:45 UTC, rachelkang commented
@davidortinau Sorry, I see it now that you added it to update the button text

2022-04-25 20:30 UTC, Redth commented
@jsuarezruiz  @rachelkang not sure which colors we wanted in the conflict here, can you resolve them please?

2022-04-26 10:24 UTC, jsuarezruiz commented
/azp run

2022-04-27 14:56 UTC, merged