[foldable] Package reference instead of project reference
dotnet/maui pull request #6514
Opened 2022-04-26 20:59 UTC by conceptdev

Reverts #5891 and converts Foldable to a package, following instructions in #5894

### Description of Change

1. Update **Controls.Foldable.csproj** to make NuGet
1. Restore commented-out foldable code in the **Maui.Controls.Sample** project
1. Update **Maui.Controls.Sample.csproj** to use a `PackageReference`
1. Remove Foldable.csproj reference from **Samples.slnf**

### Issues Fixed

#5894 where a `GENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry'` was being generated in the CI builds, assumed to be because the Foldable project was being referenced and bringing in all its dependencies as duplicates...

2022-04-27 03:01 UTC, mattleibow approved these changes
😍

2022-04-27 03:04 UTC, mattleibow commented
/azp run

2022-04-27 07:35 UTC, rmarinho requested changes, later dismissed
```
         D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj : error NU1604: Project dependency Microsoft.Maui.Controls.Foldable does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [D:\a\_work\1\s\Microsoft.Maui.Samples.slnf]
         D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj : error NU1101: Unable to find package Microsoft.Maui.Controls.Foldable. No packages exist with this id in source(s): D:\a\_work\1\s\bin\dotnet\library-packs, darc-pub-dotnet-runtime-a21b9a2, dotnet-eng, dotnet-public, dotnet6, dotnet7, skiasharp [D:\a\_work\1\s\Microsoft.Maui.Samples.slnf]
         D:\a\_work\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj : error NU1604: Project dependency Microsoft.Maui.Controls.Foldable does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [D:\a\_work\1\s\Microsoft.Maui.Samples.slnf]
         D:\a\_work\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj : error NU1101: Unable to find package Microsoft.Maui.Controls.Foldable. No packages exist with this id in source(s): D:\a\_work\1\s\bin\dotnet\library-packs, darc-pub-dotnet-runtime-a21b9a2, dotnet-eng, dotnet-public, dotnet6, dotnet7, skiasharp [D:\a\_work\1\s\Microsoft.Maui.Samples.slnf]
```

2022-04-28 00:41 UTC, conceptdev commented
Latest commits build a NuGet package in the **/artifacts/** folder (thanks to **Microsoft.Maui.Packages.slnf**), but I'm not sure the sample will be able to load it...

![image](https://user-images.githubusercontent.com/199373/165653678-a5e8b9b2-e8da-41a9-99a0-5c8fb2729d84.png)

2022-04-28 00:57 UTC, PureWeen commented
/azp run

2022-04-28 03:56 UTC, conceptdev commented
Current error `D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj : error NU1101: Unable to find package Microsoft.Maui.Controls.Foldable. No packages exist with this id in source(s): D:\a\_work\1\s\bin\dotnet\library-packs, darc-pub-dotnet-runtime-a21b9a2, dotnet-eng, dotnet-public, dotnet6, dotnet7, skiasharp [D:\a\_work\1\s\Microsoft.Maui.Samples.slnf]`

There IS there is a **Microsoft.Maui.Controls.Foldable** NuGet, but it's in 
`D:\a\_work\1\s\artifacts\nuget`
and the Samples project is looking in 
`D:\a\_work\1\s\bin\dotnet\library-packs`

Need to figure out how to add another NuGet source for the sample project OR get the Foldable NuGet into the library-packs directory...

2022-04-28 21:41 UTC, PureWeen commented
/azp run

2022-04-29 03:19 UTC, conceptdev commented
It feels like what's happening on the server must be different to what's happening locally. Will probably roll-back these YAML changes that are trying to copy the **nupkg** around and revisit assumptions about what files are where 😬

2022-04-29 06:24 UTC, mattleibow commented
Is it in the artifact? Can you confirm in the artifact on devops or in the copy logs?

Maybe add a dir artifacts/* to a step after the download

2022-04-29 15:30 UTC, conceptdev commented
The Foldable NuGet is definitely in the **nuget** artifact at the end!

![image](https://user-images.githubusercontent.com/199373/165976090-5443e55e-dbd3-4216-a80e-58257ac66f80.png)

2022-04-29 19:49 UTC, mattleibow commented
I don't see the artifacts folder in here:

> error NU1101: Unable to find package Microsoft.Maui.Controls.Foldable. No packages exist with this id in source(s): D:\a\_work\1\s\bin\dotnet\library-packs, darc-pub-dotnet-runtime-a21b9a2, dotnet-eng, dotnet-public, dotnet6, dotnet7, skiasharp [D:\a\_work\1\s\Microsoft.Maui.Samples.slnf]

I got a feeling we need an extra step in the samples to copy nuget-only packages into a folder and then add that to the samples nuget.config. This can probably be done by copying the repo's nuget.config to a temporary location and then adding the path to the artifacts folder and then setting the `RestoreConfigFile` property to the path of the nuget.config: https://github.com/dotnet/maui/blob/main/eng/cake/dotnet.cake#L71

I am also thinking to prevent accidental issues, we should also make a new folder in the temp and copy the 2 foldable files in there and make the nuget.config point to that. By doing that we can make sure we get a build fail if suddenly a package is used instead of the workloads.

2022-04-29 21:22 UTC, conceptdev commented
@mattleibow yeah, that's why I was trying to copy the Foldable NuGet into `bin\dotnet\library-packs`, because it's already in the sources search list for the Samples project 😬

Still not sure why it wasn't working on the server, but either way it was a little hacky and your explanation/suggestion sounds more robust.

2022-07-19 00:01 UTC, mattleibow commented
After such a long time, we eventually got a bunch of things to make all this work much better.

2022-07-19 00:04 UTC, mattleibow commented on src/Controls/Foldable/src/Controls.Foldable.csproj
> +    <IsPackable>true</IsPackable>
WARNING! This will produce a nupkg that will be published to nuget.org

2022-07-26 11:25 UTC, rmarinho commented
@conceptdev  is this ready to be merged?

2022-07-26 16:17 UTC, conceptdev commented
I have not had a chance to test the NuGet. Will try to get it done today and approve if it works, thanks.

2022-08-05 10:05 UTC, rmarinho commented
@conceptdev  did you had a chance to try it ? thanks

2022-08-09 23:03 UTC, conceptdev commented
UPDATE: I was able to test the code in this branch and it still seems to work 💯 i.e. it detects the hinge when present and snaps the panes to it. 

RE: Matt's warning above about generating a NuGet - I'm assuming it will be a "preview" NuGet? What release date would we be aiming for with this package? I recall when working with Shane that there might still be some edge cases we need to test/verify.

2022-08-09 23:35 UTC, mattleibow commented
Right now, it will have the same branding and version as maui itself.

So in this merge world, it probably will be released as RC 1.

2022-08-10 18:11 UTC, conceptdev commented
@mattleibow thanks for the clarification! In that case, I wonder if the PMs should chime in as this sounds like a bit of a messaging decision as well as a technical one?

FWIW here's some screenshot of the sample on dual and single screens

![image](https://user-images.githubusercontent.com/199373/183985787-295c458c-06ba-48bc-88b2-1168587eb1ac.png)

![image](https://user-images.githubusercontent.com/199373/183985950-34d77176-4b65-4cf5-a264-52ff13ab7a15.png)

2022-08-11 15:28 UTC, merged