[Windows] Fix incorrectly Button with image size
dotnet/maui pull request #6542
Opened 2022-04-27 14:19 UTC by jsuarezruiz

### Description of Change

Fix incorrectly Button with image size on Windows.

### Issues Fixed

Fixes #5601

2022-04-27 20:31 UTC, PureWeen requested changes
@hartez it seems odd that we'd need to call invalidatemeasure here on the parent of the button. 

It looks like when you call it on button that call doesn't percolate up to the parent. Any thoughts why? I don't know if peppering around "Parent.Invalidates" like this is going to be a sustainable way to fix these issues.

2022-04-28 15:44 UTC, hartez approved these changes

2022-04-28 16:55 UTC, PureWeen approved these changes, later dismissed

2022-04-29 07:46 UTC, rmarinho commented
Closing because we merged #6637

2022-04-29 07:46 UTC, closed without merging