Set height/width on LP for ScrollView Content
dotnet/maui pull request #6794
Opened 2022-05-04 01:35 UTC by PureWeen

### Description of Change

### Issues Fixed

Fixes #6755

2022-05-04 09:59 UTC, jsuarezruiz approved these changes

2022-05-05 14:42 UTC, jsuarezruiz requested changes
Oops, now see more changes in more platforms. It seems that there are some tests failing.

2022-05-10 00:42 UTC, Redth approved these changes

2022-05-10 15:34 UTC, mattleibow approved these changes
Need to test this on a real machine, but so far all looks good.

2022-05-11 10:06 UTC, merged