[Core] Fix crash in DeviceStateTrigger
dotnet/maui pull request #6853
Opened 2022-05-05 11:06 UTC by jsuarezruiz

### Description of Change

Fix crash in DeviceStateTrigger.

![image](https://user-images.githubusercontent.com/6755973/166910976-9c13c4a1-f39c-4a5e-b90a-c754d23ae9f4.png)

### Issues Fixed

Fixes #6366

2022-05-05 11:35 UTC, mattleibow requested changes
Should we be calling updates in the ctor? I had a bunch of issues with the AdaptiveTrigger, so I moved them all into the attaching/detaching methods: 

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/AdaptiveTrigger.cs#L45-L59

I am wondering if we should do the same? Maybe Device is a bit different as this is always known at launch time and not window dependent, but it does seem more logical to run state changes only when attached?

2022-05-05 14:01 UTC, Redth approved these changes, later dismissed

2022-05-07 05:33 UTC, mattleibow approved these changes

2022-05-07 05:34 UTC, mattleibow commented
No tests? Let me add some!

2022-05-07 08:15 UTC, mattleibow approved these changes

2022-05-07 14:51 UTC, merged