Fix WinUI fully templated RadioButton
dotnet/maui pull request #6967
Opened 2022-05-09 21:46 UTC by PureWeen

### Description of Change

When fully templated WinUI needs to swap out the platform control for a `ContentPanel` so it's fully rendered from MAUI controls and not using the platform button at all

2022-05-09 21:48 UTC, PureWeen commented on src/Controls/src/Core/HandlerImpl/Frame.Impl.cs
> -		protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
This is copied from https://github.com/dotnet/maui/pull/6794

Without this change the code crashes

2022-05-10 10:12 UTC, jsuarezruiz commented
/azp run

2022-05-10 11:07 UTC, mattleibow requested changes
This is a breaking change and we can actually use the WinUI RadioButton.Template. Here I have basically swapped the entire radio with a grid - and then we can use the maui layout panel as a root:

```xaml

<RadioButton Content="Hello">
    <RadioButton.Template>
        <ControlTemplate TargetType="RadioButton">
            <Grid x:Name="RootGrid" Width="100" Height="100">

                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal" />
                        <VisualState x:Name="PointerOver" />
                        <VisualState x:Name="Pressed" />
                        <VisualState x:Name="Disabled" />
                    </VisualStateGroup>
                    <VisualStateGroup x:Name="CheckStates">
                        <VisualState x:Name="Checked">
                            <Storyboard>
                                <ObjectAnimationUsingKeyFrames  Storyboard.TargetName="RootGrid" Storyboard.TargetProperty="Background">
                                    <DiscreteObjectKeyFrame  KeyTime="0" Value="Green" />
                                </ObjectAnimationUsingKeyFrames>
                            </Storyboard>
                        </VisualState>
                        <VisualState x:Name="Unchecked" />
                        <VisualState x:Name="Indeterminate" />
                    </VisualStateGroup>
                </VisualStateManager.VisualStateGroups>

                <ContentPresenter Content="{TemplateBinding Content}" />

            </Grid>
        </ControlTemplate>
    </RadioButton.Template>
</RadioButton>
```

2022-05-10 15:32 UTC, mattleibow approved these changes
Looks good, but we probably should wait for @Redth to confirm that https://github.com/dotnet/maui/pull/6794 is good to go and then merge that and this together.

2022-05-11 10:06 UTC, merged