Fix CA1416 because we didn't set a min version
dotnet/maui pull request #700
Opened 2021-04-10 06:23 UTC by mattleibow

### Description of Change ###

CA1416 - This call site is reachable on: 'Windows' 10.0.17763.0 and later. 'XXX' is only supported on: 'Windows' 10.0.18362.0 and later.

2021-04-10 06:26 UTC, mattleibow commented on Directory.Build.props
> +    <TargetPlatformMinVersion Condition="'$(TargetPlatformMinVersion)' == '' and $(TargetFramework.Contains('-windows'))">10.0.17763.0</TargetPlatformMinVersion>
This is the fix for the warning.

2021-04-10 06:26 UTC, mattleibow commented on Directory.Build.props
> +    <MauiPlatforms Condition="'$(BuildForWinUI)' == 'true'">net6.0-windows10.0.18362.0</MauiPlatforms>
We can use the same version that WinUI does.

2021-04-10 06:26 UTC, mattleibow commented on src/Compatibility/Core/src/Compatibility-net6.csproj
> +    <None Include="bin\$(Configuration)\$(TargetFramework)\Microsoft.Maui.Controls.Compatibility\**\*.xbf" Visible="False" Pack="True" PackagePath="lib\$(TargetFramework)\Microsoft.Maui.Controls.Comp
Using the variable here just in case we update and we forget.

2021-04-12 10:35 UTC, jsuarezruiz approved these changes

2021-04-12 14:11 UTC, Redth approved these changes

2021-04-12 15:51 UTC, PureWeen requested changes
Nugets look like they don't work

![image](https://user-images.githubusercontent.com/5375137/114423615-f5fa3e80-9b7c-11eb-8d5c-5a6ebd88a27c.png)

I had the folders a wee bit different depending on where they got put

```
PackagePath="lib\net6.0-windows10.0.19041\Microsoft.Maui.Controls.Compatibility;runtimes\net6.0-windows10.0.19041.0\native\Microsoft.Maui.Controls.Compatibility"
```

don't remember if that was a factor

2021-04-12 19:42 UTC, PureWeen approved these changes

2021-04-12 19:43 UTC, merged