Implement Opacity property in ViewHandlers
dotnet/maui pull request #706
Opened 2021-04-12 10:36 UTC by jsuarezruiz

### Description of Change ###

Implement `Opacity` property in ViewHandlers.

### Platforms Affected ### 

- Core
- iOS
- macOS
- Android
- Windows

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

2021-05-26 20:09 UTC, mattleibow submitted a review, later dismissed

2021-05-26 22:10 UTC, mattleibow requested changes

2021-05-26 22:10 UTC, mattleibow commented on src/Core/src/Platform/Windows/ViewExtensions.cs
> +			nativeView.Opacity = view.Opacity;
Setting view visibility also makes use of this parameter, so the Visibility and Opacity properties need to use the same mapping method.

2021-06-01 22:36 UTC, hartez approved these changes

2021-06-02 04:22 UTC, mattleibow approved these changes

2021-06-02 04:22 UTC, merged