[Android] Correctly notify CheckBox Color changes
dotnet/maui pull request #7084
Opened 2022-05-12 11:51 UTC by jsuarezruiz

### Description of Change

 Correctly notify CheckBox Color changes.

```
<Style TargetType="CheckBox">
    <Setter Property="Color" Value="{AppThemeBinding Light=Yellow, Dark=Orange}" />
    <Setter Property="BackgroundColor" Value="{AppThemeBinding Light=White, Dark=Black}" />
</Style>
```

Light
![light-issue-1](https://user-images.githubusercontent.com/6755973/168068632-8675c81e-05ac-449b-956a-f23c58b6f9c3.PNG)

Dark
![dark-issue-1](https://user-images.githubusercontent.com/6755973/168068630-1d2dfb23-f974-44ba-8dd3-0eefcac981e8.PNG)

### Issues Fixed

Fixes #6253

2022-05-16 11:05 UTC, mattleibow approved these changes

2022-05-16 11:09 UTC, mattleibow requested changes
Can we add a test for this like this: https://github.com/dotnet/maui/blob/main/src/Controls/tests/DeviceTests/Elements/Page/PageTests.cs#L67-L84

Preferably we need a way to see if a property changes that a set of handler events fire, but this is technically better as we check for colors.

2022-05-27 02:06 UTC, mattleibow reviewed
The test logic should be cross-platform, so should we move the test into the shared code so it runs on all platforms?

2022-07-20 15:22 UTC, PureWeen approved these changes

2022-07-20 15:22 UTC, merged