Implement Entry IsSpellCheckEnabled property
dotnet/maui pull request #7442
Opened 2022-05-24 14:10 UTC by jsuarezruiz

### Description of Change

Implement Entry `IsSpellCheckEnabled `property.

2022-05-31 14:30 UTC, rmarinho commented
@jsuarezruiz  any idea why tests are failing ?

2022-06-02 08:44 UTC, mattleibow approved these changes
Looks good, just the API breaks are gonna be fun.

2022-06-08 10:10 UTC, rmarinho commented
@jsuarezruiz  can you add this to the API ?

2022-09-02 12:34 UTC, rmarinho commented
@jsuarezruiz can you rebase this one ? i might have screwed it up

2022-11-03 08:06 UTC, jsuarezruiz commented
To help focus and move faster, we're going to have fewer open PRs and focus on the ones we'll be working on in each release. This PR is not included in the next release so I close it for now. I will reopen it and adapt to changes later.

2023-03-22 13:55 UTC, rmarinho approved these changes

2023-03-22 14:35 UTC, mandel-macaque requested changes
Minor nit, but I think using HasFlag will make the coder  ore readable and accessible to more jr devs.

2023-03-22 16:05 UTC, jsuarezruiz commented on src/Core/src/Platform/Android/EditTextExtensions.cs
> +					if ((nativeInputTypeToUpdate & InputTypes.TextFlagNoSuggestions) != InputTypes.TextFlagNoSuggestions)
Changed.

2023-03-22 16:50 UTC, mandel-macaque approved these changes

2023-03-22 20:19 UTC, merged

2023-03-22 22:01 UTC, mattleibow commented
This was reverted in https://github.com/dotnet/maui/pull/14147