Fix issue when the title is an empty string
dotnet/maui pull request #7638
Opened 2022-05-31 17:53 UTC by Egaros

### Description of Change

Fix case when the title set to string empty is still exist

### Issues Fixed

Fixes  #7198

2022-06-01 07:49 UTC, jsuarezruiz approved these changes

2022-06-02 08:05 UTC, mattleibow commented
/azp run

2022-06-02 08:56 UTC, mattleibow approved these changes

2022-06-02 15:23 UTC, rmarinho commented
/azp run

2022-06-06 15:44 UTC, PureWeen requested changes

2022-06-06 19:11 UTC, Egaros commented on src/Controls/src/Core/ShellToolbar.cs
> +				IsVisible = ((BackButtonVisible && !String.IsNullOrEmpty(Title)) ||
Hi,

According to issue #7198, the fact that the title is empty has been reported as an issue.

This happened when the back button was visible, but it is possible that I was wrong when understanding what to do to fix this bug.

2022-06-10 16:47 UTC, PureWeen commented on src/Controls/src/Core/ShellToolbar.cs
> +				IsVisible = ((BackButtonVisible && !String.IsNullOrEmpty(Title)) ||
You're correct @Egaros 

I wasn't thinking about this correctly in terms of windows. 
I fixed this in a slightly different way here
https://github.com/dotnet/maui/pull/7932

And added a test

2022-06-10 16:47 UTC, PureWeen commented
Alternate PR
https://github.com/dotnet/maui/pull/7932

2022-06-10 16:47 UTC, closed without merging

2022-06-10 20:00 UTC, Egaros commented on src/Controls/src/Core/ShellToolbar.cs
> +				IsVisible = ((BackButtonVisible && !String.IsNullOrEmpty(Title)) ||
Oh ok, I see, thanks