[Android] Fix issue using DynamicResource TextColor on Label FormattedString
dotnet/maui pull request #7793
Opened 2022-06-06 15:45 UTC by jsuarezruiz

### Description of Change

Fix issue using DynamicResource TextColor on Label FormattedString on Android.

### Issues Fixed

Fixes #7464

2022-06-14 18:50 UTC, hartez commented
@jsuarezruiz Needs to be targeted to net6.0 branch.

2022-06-18 05:30 UTC, mattleibow approved these changes

2022-06-18 05:32 UTC, mattleibow requested changes
Can we add a DeviceTest for this? I am assuming this is not directly related to dynamic resources but rather the fact that the text color is changing after the UI is rendered?

2022-06-23 15:45 UTC, hartez approved these changes

2022-06-23 15:46 UTC, merged