[Android] Fix clear button not working on Entry
dotnet/maui pull request #7992
Opened 2022-06-13 14:19 UTC by jsuarezruiz

### Description of Change

Fix clear button not working on Entry. The FlowDirection used when checking if the tapped point is inside the Clear button Rect was not correct. This PR adds changes to correct the issue.

![fix-7963](https://user-images.githubusercontent.com/6755973/173374583-e4622eb2-2f6f-45c7-9508-18a7e1d161db.gif)
 
Can use the .NET MAUI Gallery and the Entry samples to verify the changes.

### Issues Fixed

Fixes #7963

2022-06-13 22:45 UTC, rachelkang requested changes
Hmm it still appears to not be working for me

I added the following to Sandbox and the clear button still appears to not be functional:

``` 
    <VerticalStackLayout>

            <Entry
                HorizontalOptions="Center"
                WidthRequest="300"
                ClearButtonVisibility="WhileEditing"
                BackgroundColor="LightGray"
                Text="ClearButtonVisibility" />
            
    </VerticalStackLayout>
```
Am I missing something?

2022-06-22 11:07 UTC, jsuarezruiz commented
> Hmm it still appears to not be working for me
> 
> I added the following to Sandbox and the clear button still appears to not be functional:
> 
> ```
>     <VerticalStackLayout>
> 
>             <Entry
>                 HorizontalOptions="Center"
>                 WidthRequest="300"
>                 ClearButtonVisibility="WhileEditing"
>                 BackgroundColor="LightGray"
>                 Text="ClearButtonVisibility" />
>             
>     </VerticalStackLayout>
> ```
> 
> Am I missing something?

Could you try it again?

```
<VerticalStackLayout>
      <Entry
          HorizontalOptions="Center"
          WidthRequest="300"
          ClearButtonVisibility="WhileEditing"
          BackgroundColor="LightGray"
          Text="ClearButtonVisibility" />
      <Entry
          HorizontalOptions="Center"
          WidthRequest="300"
          FlowDirection="RightToLeft"
          ClearButtonVisibility="WhileEditing"
          BackgroundColor="LightGray"
          Text="ClearButtonVisibility" />
      <Entry
          HorizontalOptions="Center"
          ClearButtonVisibility="WhileEditing"
          BackgroundColor="LightGray"
          Text="ClearButtonVisibility" />
      <Entry
          HorizontalOptions="Center"
          ClearButtonVisibility="WhileEditing" 
          FlowDirection="RightToLeft"
          BackgroundColor="LightGray"
          Text="ClearButtonVisibility" />
  </VerticalStackLayout>
```

2022-07-18 06:24 UTC, xlawswants commented
> 
you can set the Text for "" or empty value ,You will see the phenomenon of the bug, the delete button will not show

2022-07-19 16:49 UTC, hartez commented
The button does not disappear when the text length goes to zero during editing, and the button does not appear if the text length was zero when the Entry gained focus.

2022-07-19 17:11 UTC, hartez commented
Okay, fixed it so the clear button status updates when the text changes. The button now appears when you add text to a blank entry, and disappears when the entry no longer has text.

2022-07-22 18:52 UTC, rachelkang commented on src/Core/src/Platform/Android/EditTextExtensions.cs
> +			var x = motionEvent.RawX;
@hartez what is RawX vs GetX?

2022-07-22 18:52 UTC, rachelkang approved these changes
LGTM! Working now, yay :)

2022-07-22 19:22 UTC, merged