[Windows] Fix DatePicker TextColor property
dotnet/maui pull request #7995
Opened 2022-06-13 15:23 UTC by jsuarezruiz

### Description of Change

Fix TextColor property on Windows DatePicker.

![image](https://user-images.githubusercontent.com/6755973/173388150-bfff9f7a-21c9-4a76-91df-b38da6451c0f.png)

### Issues Fixed

Fixes #7924

2022-06-13 15:24 UTC, jsuarezruiz commented on src/Core/src/Platform/Windows/DatePickerExtensions.cs
> +		static readonly string[] TextColorResourceKeys =
This is the main change.

2022-07-19 16:38 UTC, jsuarezruiz commented
> Is it possible do add a windows device test for this ?

Sure thing. Added all the existing DatePicker tests to Windows.

![windows-datepicker](https://user-images.githubusercontent.com/6755973/179803678-f797f5ed-d00f-4bd2-a123-40c0dc07d2c5.gif)

2022-07-20 20:32 UTC, PureWeen requested changes

2022-07-20 20:32 UTC, PureWeen commented on src/Core/src/Platform/Windows/DateTimeExtensions.cs
> +		public static DateTimeOffset ToDateTimeOffset(this DateTime dateTime)
What's the use case here? Can you add a test for this change?

2022-07-25 22:23 UTC, PureWeen approved these changes

2022-07-26 16:55 UTC, merged

2022-09-08 11:31 UTC, 1888games commented
Should this have fixed the picker control, also detailed in the original issue? I am still seeing black text regardless of what is set, when using the picker control in 17.4.0 Preview 1.

https://github.com/dotnet/maui/issues/7924

2022-11-13 19:38 UTC, handysharp commented
Picker text color still not working properly as per 1888games (Sept 8). When over picker, the text goes to black. Sometimes stays like that and sometimes goes back to selected color override in xaml when item selected. I assume it should turn black only when hovering over but otherwise should be the coded color??

2023-10-02 09:41 UTC, m-calvi commented
I still have this problem on the DatePicker control, changing the text colour and hovering the mouse over it turns the text black. I'm using .NET 7.0

2023-10-16 12:20 UTC, larsduewel commented
Same problem here the PointerOver TextColor can be set, but it is ignored.