[essentials] use Lazy<T> for Android application-wide values
dotnet/maui pull request #7996
Opened 2022-06-13 15:48 UTC by jonathanpeppers

Context: https://github.com/unoplatform/performance/tree/master/src/dopes/DopeTestMaui

I was reviewing a benchmark/sample that puts lots of labels on the
screen that say "dope" and measures how many per second. Personally, I
would have chosen some other word like `LOL`, so you could have a
`LOLs/s` average. LOL?

Reviewing `dotnet trace` output, I saw:

    1.06s (6.3%) Microsoft.Maui.Essentials!Microsoft.Maui.ApplicationModel.AppInfoImplementation.get_RequestedLayoutDirection()
    4.46ms (0.03%) Microsoft.Maui.Essentials!Microsoft.Maui.ApplicationModel.AppInfoImplementation.get_RequestedTheme()

So approximately 6.3% of the time was spent querying if layouts are
RTL or not? And 0.03% checking dark mode?

I went through `AppInfoImplementation` on Android, and simply used
`Lazy<T>` for every value that queries `Application.Context`. These
values cannot change after the app launches, so they don't need to be
computed on every call.

If these values ever need to match a `Context` for multiple
activities, we should re-evaluate this caching. A dictionary using a
key of `Context.Handle` might work for that case.

We can also remove places with `#if __ANDROID_24__` as they are always
true in .NET 6. Runtime checks using `OperatingSystem` should be used
going forward.

## Results ##

A `Release` build on a Pixel 5 device, I was getting:

    Before: 55.42 Dopes/s
    After:  64.23 Dopes/s

![image](https://user-images.githubusercontent.com/840039/173393229-820cd7f1-9ce6-450e-a481-f850cb73717a.png)
![image](https://user-images.githubusercontent.com/840039/173393158-7990bf4d-7e13-455b-8a22-4c2d06821fbd.png)

This should help the performance of `Label` in any .NET MAUI
application running on Android.

2022-06-13 22:31 UTC, akoeplinger commented on src/Essentials/src/AppInfo/AppInfo.android.cs
> +			if (!OperatingSystem.IsAndroidVersionAtLeast(17))
this can be removed too since the min supported Android version in .NET 6 is 21

2022-06-14 18:04 UTC, mattleibow approved these changes

2022-06-14 18:05 UTC, mattleibow commented
Can we retarget to net6.0 and these changes will flow up to main and net7

2022-06-14 18:05 UTC, mattleibow requested changes
Retarget

2022-06-14 19:58 UTC, jonathanpeppers commented
@mattleibow I think I want this in .NET 7-only.

2022-06-14 21:27 UTC, jonathanpeppers commented
@mattleibow ok, I understand now after asking in Teams. This can go to `main`.

2022-06-16 01:17 UTC, mattleibow approved these changes

2022-06-16 01:18 UTC, merged

2023-03-15 13:56 UTC, mattleibow commented
Some of the APIs should not have been cached - theme and layout direction. These have been reverted in https://github.com/dotnet/maui/pull/11200

That PR was not a plain revert and instead cache the values in Controls where we get events when the theme changes.