[android] avoid View.Context where unecessary
dotnet/maui pull request #8001
Opened 2022-06-13 21:25 UTC by jonathanpeppers

Context: https://github.com/dotnet/maui/pull/7996
Context: https://github.com/unoplatform/performance/tree/master/src/dopes/DopeTestMaui

Building upon my changes in #7996 (same sample), I noticed:

    7.60s (14%) mono.android!Android.Views.View.get_Context()

14% of the time is literally spent calling `View.Context`!

We did a little investigation on the underlying Java interop, this is
basically doing:

1. Call into JNI, get an `IntPtr`.
2. See if that `IntPtr` maps to a C# object that is already alive.
3. Return the C# object, or create a new one if needed.

We can actually avoid all this work, in this case.

For example:

    5.48s (10%) microsoft.maui!Microsoft.Maui.Platform.TransformationExtensions.UpdateAnchorX(Android.Views.View,Microsoft.Maui.IView)
    4.28s (8.2%) microsoft.maui!Microsoft.Maui.Platform.TransformationExtensions.UpdateAnchorY(Android.Views.View,Microsoft.Maui.IView)

These extension methods call `View.Context` twice:

    public static void UpdateTranslationY(this AView platformView, IView view)
    {
        if (platformView.Context == null)
            return;
        platformView.TranslationY = platformView.Context.ToPixels(view.TranslationY);
    }

We can actually, make an overload for `ToPixels()` to where
`View.Context` wouldn't be called *at all*:

    internal static float ToPixels (this View view, double dp)
    {
        if (s_displayDensity != float.MinValue)
            return (float)Math.Ceiling(dp * s_displayDensity);
        return view.Context.ToPixels(dp);
    }

I used this everywhere I saw it appearing in `dotnet trace` output.

Next, I saw `View.Context` being called a lot from `LayoutViewGroup`
and `ContentViewGroup`. I could simply store the value in the
constructor for these types, make it non-nullable, and remove null
checks.

## Results ##

A `Release` build on a Pixel 5 device, I was getting:

    Before: 64.23 Dopes/s
    After:  81.70 Dopes/s

![image](https://user-images.githubusercontent.com/840039/173447917-e9d11ff8-249b-4777-a468-1786e2c8a1cc.png)

2022-06-14 18:09 UTC, mattleibow requested changes
Looks good. Can we retarget to net6.0 so we don't lose these changes. We merge from net6 to main to net7

2022-06-14 18:42 UTC, jonathanpeppers commented
@mattleibow I'm not sure I would want these in .NET 6, is that the only option?

2022-06-14 21:25 UTC, jonathanpeppers commented
@mattleibow ok, I understand now after asking in Teams. This can go to `main`.

2022-06-16 01:22 UTC, mattleibow approved these changes

2022-06-16 01:22 UTC, merged