[Android] Fix crash using ContentViews inside CollectionView
dotnet/maui pull request #8051
Opened 2022-06-15 12:34 UTC by jsuarezruiz

### Description of Change

Fix crash using ContentViews inside CollectionView on Android.

![Screenshot_1655294499](https://user-images.githubusercontent.com/6755973/173840501-64a9c8bc-5ae1-47c6-9d4c-4541f883d2a7.png)

### Issues Fixed

Fixes #7884

2022-06-20 14:37 UTC, rmarinho commented
This should be the same issue we discussed before with @PureWeen  where adding the same view without removing it will hide the issue.

Can you also add a test for this please?

2022-06-20 15:32 UTC, PureWeen requested changes

2022-06-26 13:51 UTC, Phenek commented
This is interesting, 
I don't understand why this view has a parent before add it for the first time.

PS: On iOS part the CollectionView is just not populate, no crash. So iOS could be also related.

2022-11-03 08:24 UTC, jsuarezruiz commented
To help focus and move faster, we're going to have fewer open PRs and focus on the ones we'll be working on in each release. This PR is not included in the next release so I close it for now. I will reopen it and adapt to changes later.

2022-11-03 08:24 UTC, closed without merging