Automatically add MauiIcon to AndroidManifest.xml
dotnet/maui pull request #8063
Opened 2022-06-15 13:45 UTC by mattleibow

Re-PR of #7968

### Description of Change

On Android (and iOS / Mac Catalyst) the app icons are not actually added to the manifests because that code was not written. For some reason I had determined that people would always use the same filename and thus the templates would be good - and somehow knowledge would arrive in the brains of devs to go change values in the platform files when editing the csproj.

This was obviously wrong and even though the docs are technically incorrect because they do not state that you have to change values in the manifest, this PR goes ahead and does the expected thing and makes sure there is an icon in the manifest.

> NOTE: the Android templates change here to no longer explicitly set the icon in the working directory, but existing users will still have it. This needs to be documented on how to remove and/or specify: https://github.com/dotnet/docs-maui/issues/611

### Issues Fixed

 - Fixes the first part of #7786
 - Fixes #7971

2022-06-15 14:19 UTC, jonathanpeppers requested changes

2022-06-15 14:25 UTC, jonathanpeppers commented on .nuspec/Microsoft.Maui.Resizetizer.targets
> +            GeneratedFilename="AndroidManifest.xml" />
Alternatively, could you write to MAUI's own manifest and use the manifest merging feature?

2022-06-15 15:14 UTC, mattleibow commented on .nuspec/Microsoft.Maui.Resizetizer.targets
> +            GeneratedFilename="AndroidManifest.xml" />
maybe we just need to document this and fix it in net7 then. @redth @davidortinau  @davidbritch

2022-07-18 23:26 UTC, mattleibow commented
Closing this as the issue needs to be fixed in the SDKs:
 - https://github.com/xamarin/xamarin-macios/issues/12790
 - https://github.com/xamarin/xamarin-android/issues/7147

2022-07-18 23:26 UTC, closed without merging