Add a new Attribute for static methods. [OnHotReload]
dotnet/maui pull request #833
Opened 2021-04-23 23:30 UTC by Clancey

This allows us to hook into the HotReload for a specific type. This will allow us to register a class or reset defaults when a class is HotReloaded

2021-04-24 03:46 UTC, mattleibow requested changes
I think I like this. Simple and sweet, but powerful. Also better than the unit as well as only accessed via reflection meaning it can get linked. 

Does it support private methods?

2021-04-24 03:47 UTC, mattleibow approved these changes

2021-04-27 12:09 UTC, jsuarezruiz requested changes
I like it!. 

Just a small change to fix the build:
`ReflectionMethodComparer.Equals(MethodInfo g1, MethodInfo g2)` in HotReloadExtensions.cs must be `ReflectionMethodComparer.Equals(MethodInfo? g1, MethodInfo? g2)`
(Nullability checks)

2021-05-05 12:06 UTC, jsuarezruiz approved these changes

2021-05-05 12:07 UTC, merged