[Windows] Add a root view for a window to manage pages and overlays
dotnet/maui pull request #8428
Opened 2022-06-29 18:25 UTC by mattleibow

### Description of Change

Over the last set of commits, we tried to improve performance and reduce the view nesting and layout churn. Inadvertently we removed a root view that appeared to not be used. https://github.com/dotnet/maui/pull/7172 This is a result of code not actually using the type and was just casting to Panel or some other base type.

This PR adds the view back, but also adds it back in a more useful way. Most notable the page managers use the type directly to add pages and the overly managers use it to add overlays. Instead of everyone grabbing the view and putting their bits in, we should use the new api so that overlays correctly are added to the top and pages underneath.

### Issues Fixed

Fixes #8096

2022-06-29 18:52 UTC, drasticactions commented
@mattleibow Can you try hovering over the Live Visual Tree in Visual Studio and verify that the adorners are appearing again over MAUI elements? I don't _think_ there is an API change here so the current version (I think) "should just work (tm)".

2022-06-30 10:32 UTC, jsuarezruiz commented
/azp run

2022-06-30 15:45 UTC, hartez approved these changes

2022-06-30 16:43 UTC, PureWeen requested changes
I merged this with the net6.0 branch to get the RequestedTheme fixes. It seems like the `modal` tests on WinUI are crashing with this change. 

If I switch to net6.0 they run fine.
If I run it from this branch they crash.

![image](https://user-images.githubusercontent.com/5375137/176732701-9d8385e3-0d4e-4e2f-8c23-b0e949aec25a.png)

2022-06-30 20:10 UTC, mattleibow reviewed
Works for me on Android and Windows. There is a bit of an offset for Android, but @drasticactions  has a PR/Fix/Merged in the UI Tools repos.

2022-06-30 20:23 UTC, PureWeen approved these changes

2022-06-30 20:46 UTC, merged