Implement more WinUI TimePickerHandler properties
dotnet/maui pull request #858
Opened 2021-04-27 12:04 UTC by jsuarezruiz

### Description of Change ###

Implement more WinUI TimePickerHandler properties:
- Format
- Font
- CharacterSpacing

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might effect accessibility?
No

2021-05-07 13:57 UTC, rmarinho requested changes
I m getting this error message

![image](https://user-images.githubusercontent.com/1235097/117460507-7e81ba00-af44-11eb-90c3-8b3ebd60b051.png)

2021-05-07 14:00 UTC, rmarinho commented
Merging main fixed the issue above but now the layout is crazy

![image](https://user-images.githubusercontent.com/1235097/117460940-f2bc5d80-af44-11eb-8067-160ef88228ab.png)

2021-06-01 20:51 UTC, hartez commented
@rmarinho The character spacing is a known WinUI bug, so there's not much we can do about that until they've fixed it.

For the Format, the WinUI TimePicker doesn't support much in the way of formatting. Try `Format = "HH:mm"` and you can see that it will switch to the 24 hour clock; that's about all we can do. Works the same way in Forms.

2021-06-01 20:51 UTC, hartez approved these changes

2021-06-08 17:54 UTC, rmarinho approved these changes

2021-06-09 09:48 UTC, merged