Implement more WinUI DatePickerHandler properties
dotnet/maui pull request #859
Opened 2021-04-27 12:05 UTC by jsuarezruiz

### Description of Change ###

Implement more WinUI DatePickerHandler properties

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might effect accessibility?
No

2021-05-06 14:19 UTC, rmarinho requested changes

2021-05-06 14:19 UTC, rmarinho commented on src/Core/src/Platform/Windows/DatePickerExtensions.cs
> +			nativeDatePicker.Date = new DateTimeOffset(new DateTime(dateTime.Ticks, DateTimeKind.Unspecified));
Shouldn't this handle the Format ?

2021-05-07 17:09 UTC, rmarinho commented
Font and Format seem to be working, but max and min date  seems something wrong..

```
verticalStack.Add(new DatePicker { MinimumDate = DateTime.Now.AddDays(-1), Date = DateTime.Now, MaximumDate = DateTime.Now.AddDays(1) });
```

this still allows me to select days and months

![image](https://user-images.githubusercontent.com/1235097/117484637-463ba500-af5f-11eb-9403-05297c35e67a.png)

2021-05-26 19:10 UTC, hartez commented
> Font and Format seem to be working, but max and min date seems something wrong..
> 
> ```
> new DatePicker { MinimumDate = DateTime.Now.AddDays(-1), Date = DateTime.Now, MaximumDate = DateTime.Now.AddDays(1) };
> ```
> 
> this still allows me to select days and months
> 

This is a limitation of the WinUI DatePicker; it can only restrict the selectable years: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.datepicker?view=winui-3.0#date-values

So the best we can do out of the box is set MinYear and MaxYear. Hopefully at some point we can include support for the CalendarDatePicker, where MinimumDate/MaximumDate is more useful.

2021-05-26 19:29 UTC, merged