[Windows] Fix Entry placeholder position using VerticalTextAlignment
dotnet/maui pull request #8684
Opened 2022-07-12 17:09 UTC by jsuarezruiz

### Description of Change

Fix Entry placeholder position using VerticalTextAlignment. This PR include changes to get the placeholder TextBlock and update the VerticalTextAlignment.

![image](https://user-images.githubusercontent.com/6755973/178551768-525331b9-277a-4f13-9b6a-6bf0c1018b63.png)

### Issues Fixed

Fixes #7844

2022-07-12 23:45 UTC, mattleibow reviewed
Is it possible to add a unit test for this?

2022-10-17 19:31 UTC, JPfahl commented
Is this ever going to make it into production?  TimePickers and Labels do not align vertically either.

2022-10-17 20:47 UTC, mattleibow commented on src/Core/src/Handlers/Entry/EntryHandler.Windows.cs
> +				handler.PlatformView?.UpdateVerticalTextAlignment(entry, entryHandler._placeholder);
Is it possible to find the placeholder via the name or view apis? Then we don't need to cast and avoid concrete types in these mappers.

2022-12-13 18:25 UTC, mattleibow requested changes
Superseded by https://github.com/dotnet/maui/pull/12059

2022-12-13 18:25 UTC, mattleibow commented
Superseded by https://github.com/dotnet/maui/pull/12059

2022-12-13 18:25 UTC, closed without merging