Propagate semantic properties from FlyoutItem
dotnet/maui pull request #9270
Opened 2022-08-08 17:16 UTC by PureWeen

### Description of Change

- Propagate any `SemanticProperties` set to the templated `Grid` created inside the FlyoutItems. 
- Fix a few spots on WinUI where it would Tab to empty content. I've disabled the TabStop for the templated content controls used to render the flyoutitems and the flyout footer. This way it now tabs directly to the actual content. By default the Navigation items on the WinUI NavigationView can be navigated via arrow keys not by tab. 
  -  One thing to note here is that navigating via tab/arrow keys is broken on WinUI if you do it with a debugger [attached](https://github.com/microsoft/microsoft-ui-xaml/issues/2521#issuecomment-655209746). So, after you've launched your code stop the debugger and then re-launch the app to test

### Issues Fixed
Fixes #9066

2022-08-08 17:17 UTC, PureWeen commented on src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRecyclerAdapter.cs
> -						AutomationPropertiesProvider.AccessibilitySettingsChanged(_itemView, value);
This is now propagated through `SemanticProperties` bindings

2022-08-18 18:54 UTC, rachelkang requested changes
As shared offline, the current behavior I'm noticing is as follows:
* Narrator announces invisible/nonexistent images for each of the flyout items
* Narrator reads the flyout item text twice - both on the item, and the text label itself
* Keyboard navigation doesn't work as expected

That being said, the core issue is indeed fixed! The flyout item text is read aloud for how it's shown on the UI, and not based on the name of the control behind the scenes

2022-08-18 19:45 UTC, PureWeen commented
@rachelkang should be fixed can you try again?

2022-08-22 16:38 UTC, rachelkang approved these changes

2022-08-22 19:55 UTC, merged