[Core] Fix ImageButton IsLoading property
dotnet/maui pull request #9917
Opened 2022-09-05 12:27 UTC by jsuarezruiz

### Description of Change

Fix ImageButton IsLoading property. Until now, the property has never really been established properly. This PR add changes to propagate the property changes.

### Issues Fixed

Fixes #9073

2022-09-05 12:27 UTC, jsuarezruiz commented on src/Controls/src/Core/HandlerImpl/ImageButton/ImageButton.Impl.cs
> +			((IImageController)this)?.SetIsLoading(isLoading);
This is the main change.

2022-09-05 18:33 UTC, mattleibow requested changes
Can we add a test for this?

2022-09-07 11:29 UTC, jsuarezruiz commented
> Can we add a test for this?

Sure, added device tests.

2022-09-12 10:35 UTC, rmarinho approved these changes

2022-09-12 10:36 UTC, merged