[Android] Fix crash opening Shell app via notification tray
dotnet/maui pull request #9933
Opened 2022-09-06 07:23 UTC by jsuarezruiz

### Description of Change

Fix crash opening Shell app via notification tray.

![fix-9090](https://user-images.githubusercontent.com/6755973/188572264-d3682447-a3bf-41e9-aa59-d5c5a362aebb.gif)

### Issues Fixed

Fixes #9090

2022-09-06 14:46 UTC, PureWeen submitted a review, later dismissed

2022-09-06 17:02 UTC, mattleibow commented
@PureWeen  what was that question? I see no question here.

2022-09-06 17:08 UTC, PureWeen requested changes
From the screen shot it looks like you're still using the FlyoutPage as the root

Can you try testing this with Shell?

2022-09-07 11:55 UTC, jsuarezruiz commented
> From the screen shot it looks like you're still using the FlyoutPage as the root
> 
> Can you try testing this with Shell?

Yes, this is the same tests using Shell.

![fix-shell-crash](https://user-images.githubusercontent.com/6755973/188872452-15c45645-07d2-41f8-a6e4-111fddb287f7.gif)

2022-09-07 15:21 UTC, PureWeen approved these changes

2022-09-07 15:21 UTC, merged