Fix root page swapping
dotnet/maui pull request #9955
Opened 2022-09-06 23:52 UTC by PureWeen

### Description of Change

### Issues Fixed

Fixes #

2022-09-07 19:43 UTC, PureWeen commented on src/TestUtils/src/DeviceTests.Runners/VisualRunner/ViewModels/TestCaseViewModel.cs
> +		// TestCases with strongly typed class data for some reason don't get split into different
https://github.com/dotnet/maui/issues/9976

2022-09-08 14:57 UTC, jsuarezruiz requested changes
Testing on different platforms.

On Android, seems to work correctly.
![fix-root -droid](https://user-images.githubusercontent.com/6755973/189155804-775e8515-f18a-4f4f-9fd6-6e27d981e922.gif)
But on Windows, the NavigationBar background is not rendering and the position seems wrong.
![fix-root -win](https://user-images.githubusercontent.com/6755973/189155817-02e45a00-5be1-4eed-9ed8-0f020cea8d9a.gif)


`Application.Current.MainPage = new NavigationPage(new ControlsPage());`

2022-09-08 22:39 UTC, PureWeen commented
Should be fixed now @jsuarezruiz

2022-09-09 07:30 UTC, janseris commented
@jsuarezruiz hi could you share the sample testing app? It looks very useful for diagnosing bugs

2022-09-14 23:16 UTC, hartez approved these changes
Looks good, I have some nitpicky style/clarity things; you can take them or leave them.

2022-09-14 23:16 UTC, hartez commented on src/Controls/tests/DeviceTests/Stubs/WindowHandlerStub.iOS.cs
> +				if (platformView
Can we create a local here for PresentedViewController, just for clarity?
`var pvc = platformView?.RootViewController?.PresentedViewController;`?

2022-09-14 23:16 UTC, hartez commented on src/Core/src/WindowOverlay/WindowOverlay.Android.cs
> +			if (Window?.Content?.Handler == null)
Can we roll the null check on 22 into this? And maybe create a local for Window?.Content since we access it multiple times.

2022-09-15 13:54 UTC, jsuarezruiz approved these changes

2022-09-15 13:56 UTC, merged