Fix AdaptiveTriggers
dotnet/maui pull request #9984
Opened 2022-09-08 11:32 UTC by jsuarezruiz

### Description of Change

Fix AdaptiveTriggers.

```
<Style TargetType="StackLayout">
    <Setter Property="VisualStateManager.VisualStateGroups">
        <VisualStateGroupList>
            <VisualStateGroup>
                <VisualState x:Name="Vertical">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="0" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor"
                        Value="Red"   />
                    </VisualState.Setters>
                </VisualState>
                <VisualState x:Name="Horizontal">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="600" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor"
                        Value="Green"   />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </Setter>
</Style>
```

NavigationPage
![fix-8492](https://user-images.githubusercontent.com/6755973/189111644-db6d7ca8-3824-4dc5-93d1-2cc9afd0f9a9.gif)

Shell
![fix-8492-shell](https://user-images.githubusercontent.com/6755973/189111653-3bd148cb-b602-4477-b9e2-5a2fdbae83b9.gif)

### Issues Fixed

Fixes #8492

2022-09-27 01:01 UTC, chabiss approved these changes

2022-09-27 11:32 UTC, jsuarezruiz commented on src/Controls/src/Core/AdaptiveTrigger.cs
> +			var page = _window?.Page;
We can create an extension method with this piece of code.

2022-09-27 12:30 UTC, mattleibow requested changes
What happen when shell does a navigation or something that replaces the page occurs? The existing code is not perfect as it attaches to the page size event, but what happens when the window replaced the page?

I wonder if there is some other way we should be doing this - maybe looking up the view hierarchy and getting the first page and then tracking that?

What happens if the view that this trigger is attached to moves from one page to another - like for drag & drop?

2022-09-28 16:30 UTC, mattleibow approved these changes

2022-09-28 20:13 UTC, merged